import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import postcss from 'postcss';

/** Matches the established eager stylesheet order, including v078's own import. */
export function activeCssSources(root){
 const manifest=JSON.parse(readFileSync(new URL('src/styles-src/presentation-order.json',root),'utf8'));
 if(manifest.schema!==1||!Array.isArray(manifest.sources)||new Set(manifest.sources).size!==manifest.sources.length)throw new Error('Invalid or duplicate presentation CSS sources');
 return manifest.sources;
}
function loadExpandedCss(url,chain=[]){
 if(chain.includes(url.href))throw new Error('Cyclic CSS import: '+url.href);
 const tree=postcss.parse(readFileSync(url,'utf8'),{from:fileURLToPath(url)});
 tree.walkAtRules('import',rule=>{
  const match=rule.params.match(/^['"](\.\/[^'"]+\.css)['"]$/);
  if(!match)throw new Error('Unsupported CSS import must be reviewed: '+rule.params);
  const imported=loadExpandedCss(new URL(match[1],url),[...chain,url.href]);
  rule.replaceWith(...imported.nodes);
 });return tree;
}
export function loadCssCascade(root){return activeCssSources(root).map(file=>({file,original:readFileSync(new URL(file,root),'utf8'),tree:loadExpandedCss(new URL(file,root))}))}
function contextOf(rule){
 const context=[];let safe=true;
 for(let parent=rule.parent;parent.type!=='root';parent=parent.parent){
  if(parent.type!=='atrule'){safe=false;context.unshift([parent.type]);continue;}
  context.unshift([parent.name,parent.params]);
  if(!['media','supports'].includes(parent.name))safe=false;
 }
 return {context,safe};
}
/** Removes only an earlier byte-identical declaration covered by a later one.
 * No selector merging, property/value rewriting, conditional hoisting or order change.
 * Layers, scopes, containers, nested rules and keyframes are deliberately excluded.
 */
export function consolidateCssCascade(entries){
 const seen=new Map(),removed=[];
 for(const entry of [...entries].reverse()){
  const rules=[];entry.tree.walkRules(rule=>rules.push(rule));
  for(const rule of rules.reverse()){
   const {context,safe}=contextOf(rule);if(!safe)continue;
   for(const declaration of [...rule.nodes].reverse()){
    if(declaration.type!=='decl')continue;
    const key=JSON.stringify([context,rule.selector,declaration.prop,declaration.value,!!declaration.important]);
    const here={file:entry.file,line:declaration.source.start.line};
    if(seen.has(key)){removed.push({...here,coveredBy:seen.get(key),selector:rule.selector,property:declaration.prop,value:declaration.value,important:!!declaration.important,context});declaration.remove();}
    else seen.set(key,here);
   }
   if(!rule.nodes.some(node=>node.type!=='comment'))rule.remove();
  }
 }
 return removed;
}
/** Order-sensitive semantic fingerprint; comments and empty conditional shells are ignored. */
export function cssCascadeFingerprint(entries){
 const rows=[];
 for(const entry of entries){
  const visit=(node,context=[])=>{
   if(node.type==='comment')return;
   if(node.type==='rule'){
    const values=(node.nodes||[]).filter(child=>child.type==='decl').map(child=>[child.prop,child.value,!!child.important]);
    if(values.length)rows.push(['rule',context,node.selector,values]);
    for(const child of node.nodes||[])if(!['decl','comment'].includes(child.type))visit(child,[...context,['selector',node.selector]]);
   }else if(node.type==='atrule'){
    if(node.nodes){
     const declarations=node.nodes.filter(child=>child.type==='decl').map(child=>[child.prop,child.value,!!child.important]);
     if(declarations.length)rows.push(['atrule',context,node.name,node.params,declarations]);
     // Layer declarations establish ordering even if empty.
     if(node.name==='layer')rows.push(['layer',context,node.params]);
     for(const child of node.nodes)if(!['decl','comment'].includes(child.type))visit(child,[...context,[node.name,node.params]]);
    }else rows.push(['atrule',context,node.name,node.params]);
   }else for(const child of node.nodes||[])visit(child,context);
  };visit(entry.tree);
 }
 return createHash('sha256').update(JSON.stringify(rows)).digest('hex');
}
export function renderConsolidatedCss(entries){return ('/* Generated by maintain:aggregates from styles-src/presentation-order.json. Do not edit. */\n'+entries.map(entry=>entry.tree.toString()).join('\n')).trimEnd()+'\n'}
export function parseCssOutput(content){return [{file:'src/midPresentation.css',tree:postcss.parse(content)}]}
