import fs from 'node:fs';
const read=path=>fs.readFileSync(new URL(path,import.meta.url),'utf8');
const updater=read('../src/v078.ts');
const main=read('../src/main.tsx');
const pwa=read('../src/pwa.ts');
const serviceWorker=read('../public/service-worker.js');
const legacyWorker=read('../public/sw.js');
const failures=[];
for(const token of["new URL('./version.json',document.baseURI)","cache:'no-store'",'mid-refresh','_mid_reload','registration.update()','SKIP_WAITING','controllerchange','location.replace','visibilitychange','pageshow'])if(!updater.includes(token))failures.push(`Updater-Merkmal fehlt: ${token}`);
if(updater.includes('mid-update-pending'))failures.push('grau/weiß auslösende Update-Zwischenklasse ist noch vorhanden');
if(!main.includes('registerMidServiceWorker')||main.includes("register(new URL('./sw.js'"))failures.push('App verwendet nicht ausschließlich die zentrale Service-Worker-Registrierung');
if(!pwa.includes("new URL('./service-worker.js',document.baseURI)")||!pwa.includes("updateViaCache:'none'"))failures.push('Service-Worker wird nicht cachefrei über den einheitlichen Pfad registriert');
const installBody=serviceWorker.match(/self\.addEventListener\('install',[\s\S]*?\n\}\);/)?.[0]||'';
if(!installBody||installBody.includes('skipWaiting'))failures.push('Service Worker aktiviert sich weiterhin unkontrolliert während install');
if(!serviceWorker.includes("if(event.data?.type==='SKIP_WAITING')self.skipWaiting()"))failures.push('kontrollierte SKIP_WAITING-Nachricht fehlt');
if(!serviceWorker.includes("fetch(request,{cache:'no-store'})"))failures.push('Navigation wird nicht netzwerkfrisch geladen');
if(serviceWorker!==legacyWorker)failures.push('Kompatibilitäts-Service-Worker sw.js weicht vom primären Service Worker ab');
const descriptor=JSON.parse(read('../public/version.json'));
const pkg=JSON.parse(read('../package.json'));
if(descriptor.version!==pkg.version)failures.push('Versionsdatei und Paketversion weichen ab');
if(!serviceWorker.includes(`mid-shell-v${pkg.version}`))failures.push('Service-Worker-Cacheversion stimmt nicht mit Paketversion überein');
if(failures.length){console.error('Updater-Prüfung fehlgeschlagen:\n- '+failures.join('\n- '));process.exit(1)}
console.log(`Updater geprüft: ein Service Worker, kontrollierte Aktivierung, controllerchange, cachefreier Seitenwechsel und Reload-Schutz für ${descriptor.version}.`);
