const ANALYSIS_CACHE_PREFIX='mid:analysis-cache:';
const ANALYSIS_CACHE_MEMORY=new Map<string,string>();
const STATION_ANALYSIS_CACHE_SCHEMA='v2';
type AnalysisCacheEntry<T>={savedAt:number;value:T;distanceM:number};
function analysisCacheStorageKind(kind:string){return kind==='station'||kind==='station-provisional'?`${kind}:${STATION_ANALYSIS_CACHE_SCHEMA}`:kind}
function analysisCacheKey(kind:string,latitude:number,longitude:number){const storageKind=analysisCacheStorageKind(kind);return`${ANALYSIS_CACHE_PREFIX}${storageKind}:${latitude.toFixed(3)}:${longitude.toFixed(3)}`}
function analysisCacheCoordinates(kind:string,key:string){const storageKind=analysisCacheStorageKind(kind),prefix=`${ANALYSIS_CACHE_PREFIX}${storageKind}:`;if(!key.startsWith(prefix))return null;const match=key.slice(prefix.length).match(/^(-?\d+(?:\.\d+)?):(-?\d+(?:\.\d+)?)$/);return match?{latitude:Number(match[1]),longitude:Number(match[2])}:null}
function analysisDistanceMeters(latitude:number,longitude:number,otherLatitude:number,otherLongitude:number){const rad=Math.PI/180,dLat=(otherLatitude-latitude)*rad,dLon=(otherLongitude-longitude)*rad,lat1=latitude*rad,lat2=otherLatitude*rad,h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 12742000*Math.asin(Math.min(1,Math.sqrt(h)))}
function parseAnalysisCacheEntry<T>(raw:string|null,maxAgeMs:number,distanceM=0):AnalysisCacheEntry<T>|null{try{if(!raw)return null;const parsed=JSON.parse(raw) as{savedAt?:number;value?:T},savedAt=Number(parsed.savedAt),age=Date.now()-savedAt;if(!Number.isFinite(savedAt)||age<0||age>maxAgeMs||parsed.value===undefined||parsed.value===null)return null;return{savedAt,value:parsed.value,distanceM}}catch{return null}}
export function readAnalysisCacheEntry<T>(kind:string,latitude:number,longitude:number,maxAgeMs:number,nearbyRadiusM=450):AnalysisCacheEntry<T>|null{try{const exact=parseAnalysisCacheEntry<T>(ANALYSIS_CACHE_MEMORY.get(analysisCacheKey(kind,latitude,longitude))??null,maxAgeMs);if(exact)return exact;let best:AnalysisCacheEntry<T>|null=null;const storageKind=analysisCacheStorageKind(kind),prefix=`${ANALYSIS_CACHE_PREFIX}${storageKind}:`;for(const[key,raw]of ANALYSIS_CACHE_MEMORY){if(!key.startsWith(prefix))continue;const coordinates=analysisCacheCoordinates(kind,key);if(!coordinates)continue;const distanceM=analysisDistanceMeters(latitude,longitude,coordinates.latitude,coordinates.longitude);if(distanceM>nearbyRadiusM)continue;const entry=parseAnalysisCacheEntry<T>(raw,maxAgeMs,distanceM);if(!entry)continue;if(!best||entry.savedAt>best.savedAt||entry.savedAt===best.savedAt&&entry.distanceM<best.distanceM)best=entry}return best}catch{return null}}
export function readAnalysisCache<T>(kind:string,latitude:number,longitude:number,maxAgeMs:number,nearbyRadiusM=450):T|null{return readAnalysisCacheEntry<T>(kind,latitude,longitude,maxAgeMs,nearbyRadiusM)?.value??null}
export function writeAnalysisCache<T>(kind:string,latitude:number,longitude:number,value:T|null|undefined){if(value===undefined||value===null)return;try{ANALYSIS_CACHE_MEMORY.set(analysisCacheKey(kind,latitude,longitude),JSON.stringify({savedAt:Date.now(),value}));const storageKind=analysisCacheStorageKind(kind),prefix=`${ANALYSIS_CACHE_PREFIX}${storageKind}:`,entries:Array<{key:string;savedAt:number}>=[];for(const[key,raw]of ANALYSIS_CACHE_MEMORY){if(!key.startsWith(prefix))continue;try{const savedAt=Number(JSON.parse(raw||'null')?.savedAt)||0;entries.push({key,savedAt})}catch{entries.push({key,savedAt:0})}}if(entries.length>24)for(const entry of entries.sort((a,b)=>b.savedAt-a.savedAt).slice(24))ANALYSIS_CACHE_MEMORY.delete(entry.key)}catch{}}
