import {useMemo,useState} from 'react';
import {BadgeCheck,Check,ClipboardCopy,RefreshCw,Smartphone,Watch} from 'lucide-react';
import type {Location,WindUnit} from './weather';
import {APPLE_WIDGET_FAMILIES,NATIVE_WIDGET_SCHEMA,nativeWidgetFeedUrl,verifyNativeWidgetFeed} from './nativeWidget';

export function AppleWidgetSettings({location,unit}:{location:Location|null;unit:WindUnit}){
 const[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[copied,setCopied]=useState(false),feedUrl=useMemo(()=>nativeWidgetFeedUrl(location,unit),[location?.latitude,location?.longitude,location?.name,location?.timezone,unit]);
 const copy=async()=>{if(!feedUrl)return;try{await navigator.clipboard.writeText(feedUrl);setCopied(true);setStatus('Feed-Adresse kopiert.');window.setTimeout(()=>setCopied(false),1800)}catch{setStatus('Kopieren nicht möglich. Die Adresse kann markiert und manuell kopiert werden.')}};
 const check=async()=>{if(!location)return;const controller=new AbortController();setBusy(true);setStatus('Widget-Datenfeed wird geprüft …');try{const data=await verifyNativeWidgetFeed(location,unit,controller.signal),hours=data.hourly?.length??0,days=data.daily?.length??0;setStatus(`${data.location?.name||location.name} · ${hours} Stunden · ${days} Tage · Schema ${data.schema}`)}catch(error){setStatus(error instanceof Error?error.message:String(error))}finally{setBusy(false)}};
 return <section className="settings-section apple-widget-settings"><header><span>Apple-Plattformen</span><h3>Widgets & Komplikationen</h3><p>MID stellt einen stabilen, kompakten Datenvertrag und eine Apple-System-Vorlage für eine spätere native iPhone-, iPad- und Apple-Watch-App bereit.</p></header><div className="apple-widget-readiness-grid"><article><Smartphone size={23}/><span><strong>iOS & iPadOS</strong><small>Vorbereitet für Home-Screen-, Lock-Screen- und StandBy-Widgets.</small></span><b>bereit</b></article><article><Watch size={23}/><span><strong>watchOS</strong><small>Vorbereitet für Inline-, Kreis-, Rechteck- und Eck-Komplikationen sowie Smart Stack.</small></span><b>bereit</b></article><article><BadgeCheck size={23}/><span><strong>Datenvertrag</strong><small>{NATIVE_WIDGET_SCHEMA} · {APPLE_WIDGET_FAMILIES.length} vorbereitete Widgetfamilien.</small></span><b>v1</b></article></div><div className="apple-widget-feed-card"><header><span><strong>Widget-Datenfeed</strong><small>{location?`Aktueller Standort: ${location.name}`:'Zuerst einen Standort im Dashboard wählen.'}</small></span><div><button type="button" onClick={()=>void check()} disabled={!location||busy}>{busy?<RefreshCw className="spin" size={16}/>:<RefreshCw size={16}/>}Prüfen</button><button type="button" onClick={()=>void copy()} disabled={!feedUrl}>{copied?<Check size={16}/>:<ClipboardCopy size={16}/>}Kopieren</button></div></header><code>{feedUrl||'Datenfeed oder Standort noch nicht verfügbar.'}</code>{status&&<small role="status">{status}</small>}</div><p className="apple-widget-note"><strong>Vorbereitungsstand:</strong> Der Datenfeed für iPhone, iPad und Apple Watch ist vorbereitet. Installierbare Widgets und Komplikationen werden mit der jeweiligen nativen App-Integration aktiviert.</p></section>
}
