import {createPortal} from 'react-dom';
import {useEffect,useLayoutEffect,useRef,useState,type CSSProperties,type PointerEvent as ReactPointerEvent,type ReactNode,type RefObject} from 'react';

export type AppPortalAlign='start'|'center'|'end';
export type AppPortalRole='tooltip'|'dialog';

type PortalPosition={left:number;top:number;width:number;above:boolean};
const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value));

export function AppPortalPopover({anchorRef,open,onClose,className='',children,width=360,positionKey,align='center',role='tooltip',ariaLabel,id,swipeToDismiss=true,gap=8}:{anchorRef:RefObject<HTMLElement|null>;open:boolean;onClose:()=>void;className?:string;children:ReactNode;width?:number;positionKey?:unknown;align?:AppPortalAlign;role?:AppPortalRole;ariaLabel?:string;id?:string;swipeToDismiss?:boolean;gap?:number}){
 const layerRef=useRef<HTMLDivElement>(null),swipeRef=useRef<{pointerId:number;x:number;y:number}|null>(null),[position,setPosition]=useState<PortalPosition>({left:8,top:8,width:Math.min(width,360),above:false});
 useLayoutEffect(()=>{if(!open||typeof window==='undefined')return;let frame=0;const update=()=>{frame=0;const anchor=anchorRef.current;if(!anchor)return;const rect=anchor.getBoundingClientRect(),availableWidth=Math.max(160,window.innerWidth-16),actualWidth=Math.min(width,availableWidth),height=layerRef.current?.offsetHeight??160;let left=align==='start'?rect.left:align==='end'?rect.right-actualWidth:rect.left+rect.width/2-actualWidth/2;left=clamp(left,8,Math.max(8,window.innerWidth-actualWidth-8));let top=rect.bottom+gap,above=false;if(top+height>window.innerHeight-8&&rect.top-height-gap>=8){top=rect.top-height-gap;above=true}else top=clamp(top,8,Math.max(8,window.innerHeight-height-8));setPosition(current=>current.left===left&&current.top===top&&current.width===actualWidth&&current.above===above?current:{left,top,width:actualWidth,above})},schedule=()=>{if(!frame)frame=window.requestAnimationFrame(update)},scrollOptions={capture:true,passive:true} as AddEventListenerOptions;schedule();window.addEventListener('resize',schedule,{passive:true});window.addEventListener('scroll',schedule,scrollOptions);return()=>{if(frame)window.cancelAnimationFrame(frame);window.removeEventListener('resize',schedule);window.removeEventListener('scroll',schedule,scrollOptions)}},[align,anchorRef,gap,open,positionKey,width]);
 useEffect(()=>{if(!open)return;const dismiss=(event:PointerEvent)=>{const target=event.target as Node|null;if(!target||anchorRef.current?.contains(target)||layerRef.current?.contains(target))return;onClose()},escape=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};document.addEventListener('pointerdown',dismiss,true);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',dismiss,true);document.removeEventListener('keydown',escape)}},[anchorRef,onClose,open]);
 if(!open||typeof document==='undefined')return null;
 const style:CSSProperties={left:position.left,top:position.top,width:position.width},pointerDown=(event:ReactPointerEvent<HTMLDivElement>)=>{if(!swipeToDismiss||event.pointerType!=='touch')return;swipeRef.current={pointerId:event.pointerId,x:event.clientX,y:event.clientY}},pointerUp=(event:ReactPointerEvent<HTMLDivElement>)=>{const start=swipeRef.current;swipeRef.current=null;if(!swipeToDismiss||!start||start.pointerId!==event.pointerId)return;const dx=event.clientX-start.x,dy=event.clientY-start.y;if(dy>72&&Math.abs(dy)>Math.abs(dx)*1.35)onClose()};
 return createPortal(<div ref={layerRef} id={id} className={`${className} app-portal-popover${position.above?' above':''}`.trim()} role={role} aria-label={ariaLabel} style={style} onPointerDown={pointerDown} onPointerUp={pointerUp} onPointerCancel={()=>{swipeRef.current=null}}>{children}</div>,document.body);
}
