import {CLOUD_WEATHER_LABEL,SIGNIFICANT_WEATHER_STYLES,cloudWeatherAt,cloudWeatherDescription,type CloudWeatherData} from './cloudWeatherData';
import {loadModelMapGeography,type ModelMapGeography} from './modelMapGeography';
import {mercatorY} from './precipitationTotals';
type Place={name:string;latitude:number;longitude:number};
const xml=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
export function cloudWeatherSvg(data:CloudWeatherData,raster:string,places:Place[],states:ModelMapGeography['states']=[]){
 const west=data.lons[0],east=data.lons.at(-1)!,south=mercatorY(data.lats[0]),north=mercatorY(data.lats.at(-1)!),mapHeight=Math.round(1000*(north-south)/((east-west)*Math.PI/180)),legendY=150+mapHeight,height=legendY+150+Math.ceil(SIGNIFICANT_WEATHER_STYLES.length/3)*25+places.length*28;
 const x=(lon:number)=>50+(lon-west)/(east-west)*1000,y=(lat:number)=>140+(north-mercatorY(lat))/(north-south)*mapHeight;
 const paths=states.flatMap(s=>s.rings.map(r=>`<path d="${r.map(([lon,lat],i)=>`${i?'L':'M'}${x(lon).toFixed(1)},${y(lat).toFixed(1)}`).join(' ')}Z"/>`)).join('');
 return `<svg xmlns="http://www.w3.org/2000/svg" width="1100" height="${height}"><defs><linearGradient id="cloud"><stop stop-color="#fff"/><stop offset="1" stop-color="#696969"/></linearGradient><clipPath id="map"><rect x="50" y="140" width="1000" height="${mapHeight}"/></clipPath></defs><rect width="1100" height="${height}" fill="#f7fafc"/><g font-family="Arial,sans-serif" fill="#152b40"><text x="50" y="42" font-size="27" font-weight="bold">MID · ${CLOUD_WEATHER_LABEL}</text><text x="50" y="78" font-size="18">${xml(data.model)} · Lauf ${xml(data.run)} · gültig ${xml(data.time)}</text><text x="50" y="110" font-size="15">Gleicher Lauf, Termin und Raster · direkte Modellwerte · keine amtliche Warnung</text><g clip-path="url(#map)"><image href="${raster}" x="50" y="140" width="1000" height="${mapHeight}" preserveAspectRatio="none"/><g fill="none" stroke="#20384d" stroke-width="1">${paths}</g></g><text x="50" y="${legendY+28}" font-size="16">Wolken 0–100 %</text><rect x="210" y="${legendY+12}" width="180" height="18" fill="url(#cloud)"/>${SIGNIFICANT_WEATHER_STYLES.map((s,i)=>`<rect x="${50+i%3*335}" y="${legendY+48+Math.floor(i/3)*25}" width="16" height="13" fill="${s.color}"/><text x="${74+i%3*335}" y="${legendY+60+Math.floor(i/3)*25}" font-size="13">${xml(s.label)}</text>`).join('')}${places.map((p,i)=>{const value=cloudWeatherAt(data,p.latitude,p.longitude);return `<text x="50" y="${legendY+85+Math.ceil(SIGNIFICANT_WEATHER_STYLES.length/3)*25+i*28}" font-size="14">${xml(p.name)} · ${value?xml(`${value.cloud===null?'Wolken unbekannt':Math.round(value.cloud)+' % Wolken'} · ${cloudWeatherDescription(value.weather)}`):'nicht abgedeckt'}</text>`}).join('')}<text x="50" y="${height-25}" font-size="13">DWD · CC BY 4.0 · bearbeitet durch MID · Grenzen: Natural Earth · Fehlende Werte bleiben unbekannt</text></g></svg>`;
}
export async function exportCloudWeather(data:CloudWeatherData,raster:string,places:Place[],kind:'svg'|'png'){
 const geography=await loadModelMapGeography();let blob=new Blob([cloudWeatherSvg(data,raster,places,geography.states)],{type:'image/svg+xml'});
 if(kind==='png'){const url=URL.createObjectURL(blob);try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const c=canvas.getContext('2d');if(!c)throw Error('Bildexport nicht verfügbar.');c.drawImage(image,0,0);blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('PNG nicht verfügbar.')),'image/png'));}finally{URL.revokeObjectURL(url)}}
 const name=`MID-${data.model}-Wolken-Wetter-${data.time.slice(0,13).replace(/[^0-9]/g,'')}.${kind}`,file=new File([blob],name,{type:blob.type}),share={title:'MID · '+CLOUD_WEATHER_LABEL,files:[file]};if(navigator.share&&navigator.canShare?.(share)){await navigator.share(share);return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);
}
