import type {Location,Station,Weather} from './weather';
import {buildWorkerUrl,workerBaseCandidates} from './workerClient';
import {recordCustomSensorObservation} from './forecastVerification';

export const CONNECTED_STATION_SETTINGS_KEY='mid:connected-station:v1';
export type ConnectedStationProvider='none'|'netatmo'|'generic-json';
export type ConnectedStationConfig={
 enabled:boolean;
 provider:ConnectedStationProvider;
 connectionId:string;
 selectedDeviceId:string;
 selectedModuleId:string;
 genericUrl:string;
 genericLabel:string;
 genericBearerToken:string;
 maxDistanceKm:number;
};
export type ConnectedStationDevice={id:string;name:string;latitude?:number;longitude?:number;elevation?:number;modules:{id:string;name:string;type:string}[]};
export type ConnectedStationStatus={configured:boolean;connected:boolean;provider?:string;devices?:ConnectedStationDevice[];message?:string;redirectUri?:string;requires?:string[];missing?:string[];error?:string};
export type ConnectedStationObservation={station:Station;quality:number;issues:string[];accepted:string[];rejected:string[]};

type NetatmoObservationReply={ok?:boolean;error?:string;observation?:any;device?:ConnectedStationDevice;quality?:number;issues?:string[]};
const DEFAULT_CONFIG:ConnectedStationConfig={enabled:false,provider:'none',connectionId:'',selectedDeviceId:'',selectedModuleId:'',genericUrl:'',genericLabel:'Eigene Wetterstation',genericBearerToken:'',maxDistanceKm:15};

function randomId(){const bytes=crypto.getRandomValues(new Uint8Array(24));let raw='';for(const byte of bytes)raw+=String.fromCharCode(byte);return btoa(raw).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
export function readConnectedStationConfig():ConnectedStationConfig{try{const parsed=JSON.parse(localStorage.getItem(CONNECTED_STATION_SETTINGS_KEY)||'{}') as Partial<ConnectedStationConfig>;return{...DEFAULT_CONFIG,...parsed,connectionId:String(parsed.connectionId||randomId()),maxDistanceKm:Math.max(1,Math.min(100,Number(parsed.maxDistanceKm)||15))}}catch{return{...DEFAULT_CONFIG,connectionId:randomId()}}}
export function writeConnectedStationConfig(change:Partial<ConnectedStationConfig>){const next={...readConnectedStationConfig(),...change};localStorage.setItem(CONNECTED_STATION_SETTINGS_KEY,JSON.stringify(next));window.dispatchEvent(new CustomEvent('mid:connected-station-settings',{detail:next}));return next}

async function workerPost<T extends{error?:string}>(mode:string,body:unknown):Promise<T>{const candidates=workerBaseCandidates('general');if(!candidates.length)throw new Error('Cloudflare Worker ist nicht konfiguriert.');const errors:string[]=[];for(const base of candidates){try{const response=await fetch(buildWorkerUrl(base,mode),{method:'POST',cache:'no-store',headers:{Accept:'application/json','Content-Type':'application/json','Cache-Control':'no-cache'},body:JSON.stringify(body)}),text=await response.text();let data:T;try{data=JSON.parse(text) as T}catch{throw new Error(`Ungültige Worker-Antwort (HTTP ${response.status}).`)}if(!response.ok||data.error)throw new Error(data.error||`HTTP ${response.status}`);return data}catch(error){errors.push(error instanceof Error?error.message:String(error))}}throw new Error(errors.at(-1)||'Stationsdienst nicht erreichbar.')}

export async function connectedStationStatus(config=readConnectedStationConfig()){if(config.provider!=='netatmo')return{configured:true,connected:false,provider:config.provider} as ConnectedStationStatus;return workerPost<ConnectedStationStatus>('netatmo-status',{connectionId:config.connectionId})}
export async function startNetatmoConnection(config=readConnectedStationConfig()){const returnUrl=`${location.origin}${location.pathname}${location.search?location.search:''}`,reply=await workerPost<{authorizeUrl?:string;error?:string}>('netatmo-auth-start',{connectionId:config.connectionId,returnUrl});if(!reply.authorizeUrl)throw new Error('Netatmo-Autorisierungsadresse fehlt.');location.assign(reply.authorizeUrl)}
export async function disconnectNetatmo(config=readConnectedStationConfig()){await workerPost<{ok?:boolean;error?:string}>('netatmo-disconnect',{connectionId:config.connectionId});return writeConnectedStationConfig({selectedDeviceId:'',selectedModuleId:''})}

function distanceKm(aLat:number,aLon:number,bLat:number,bLon:number){const rad=Math.PI/180,dLat=(bLat-aLat)*rad,dLon=(bLon-aLon)*rad,lat1=aLat*rad,lat2=bLat*rad,h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 12742*Math.asin(Math.min(1,Math.sqrt(h)))}
function finite(value:unknown){const number=Number(value);return Number.isFinite(number)?number:undefined}
function windKt(value:unknown,unit:unknown){const number=finite(value);if(number===undefined)return undefined;const normalized=String(unit||'kt').toLowerCase();if(normalized==='kmh'||normalized==='km/h')return number/1.852;if(normalized==='mph')return number*.868976;if(normalized==='ms'||normalized==='m/s')return number*1.94384;return number}
function temperatureC(value:unknown,unit:unknown){const number=finite(value);if(number===undefined)return undefined;return String(unit||'c').toLowerCase().startsWith('f')?(number-32)*5/9:number}
function pressureHpa(value:unknown){const number=finite(value);if(number===undefined)return undefined;return number>2000?number/100:number}
function rainMm(value:unknown,unit:unknown){const number=finite(value);if(number===undefined)return undefined;return String(unit||'mm').toLowerCase().includes('in')?number*25.4:number}
function field(source:any,...paths:string[]){for(const path of paths){let value=source;for(const part of path.split('.'))value=value?.[part];if(value!==undefined&&value!==null&&value!=='')return value}return undefined}
function normalizeGeneric(payload:any,label:string):Station{const timestamp=field(payload,'timestamp','time','observedAt','observation.timestamp'),latitude=finite(field(payload,'latitude','lat','station.latitude','station.lat')),longitude=finite(field(payload,'longitude','lon','lng','station.longitude','station.lon')),height=finite(field(payload,'elevation','altitude','station.elevation','station.altitude')),temperature=temperatureC(field(payload,'temperature','temp','outdoor.temperature','observation.temperature'),field(payload,'temperatureUnit','units.temperature')),humidity=finite(field(payload,'humidity','outdoor.humidity','observation.humidity')),pressure=pressureHpa(field(payload,'pressure','pressureHpa','observation.pressure')),windSpeed=windKt(field(payload,'windSpeed','wind.speed','observation.windSpeed'),field(payload,'windUnit','units.wind')),windGust=windKt(field(payload,'gust','windGust','wind.gust','observation.gust'),field(payload,'windUnit','units.wind')),windDirection=finite(field(payload,'windDirection','wind.direction','observation.windDirection')),precipitation=rainMm(field(payload,'precipitation','rain','rainIncrement','rainRate','observation.precipitation','observation.rainRate'),field(payload,'precipitationUnit','units.precipitation')),cloudCover=finite(field(payload,'cloudCover','clouds','observation.cloudCover'));return{name:String(field(payload,'stationName','name','station.name')||label),provider:'Eigene Wetterstation · Standard-JSON',stationId:String(field(payload,'stationId','id','station.id')||'generic-json'),latitude,longitude,height,timestamp:timestamp?new Date(typeof timestamp==='number'&&timestamp<1e12?timestamp*1000:timestamp).toISOString():new Date().toISOString(),temperature,humidity,pressure,pressureReference:pressure!==undefined?'station':undefined,windSpeed,windGust,windDirection,windUnit:'kt',precipitation,cloudCover,networkClass:'pws',analysisMethod:'Eigene Wetterstation · plausibilisiert'}}

export function validateConnectedStation(station:Station,location:Location,background?:Station|null,weather?:Weather|null):ConnectedStationObservation{const issues:string[]=[],accepted:string[]=[],rejected:string[]=[],now=Date.now(),stamp=Date.parse(String(station.timestamp||'')),ageMinutes=Number.isFinite(stamp)?Math.max(0,(now-stamp)/60000):999,distance=Number.isFinite(station.latitude)&&Number.isFinite(station.longitude)?distanceKm(location.latitude,location.longitude,Number(station.latitude),Number(station.longitude)):undefined;let quality=1;if(ageMinutes>45)throw new Error('Stationsmessung ist älter als 45 Minuten.');if(ageMinutes>20){quality-=.18;issues.push(`Messung ${Math.round(ageMinutes)} Minuten alt`)}if(distance!==undefined&&distance>readConnectedStationConfig().maxDistanceKm)throw new Error(`Station liegt ${distance.toFixed(1)} km vom aktiven Standort entfernt.`);if(distance!==undefined&&distance>5){quality-=.12;issues.push(`Stationsdistanz ${distance.toFixed(1)} km`)}const current=weather?.current as any,referenceTemp=finite(background?.temperature??current?.temperature_2m),referencePressure=finite(background?.pressure??current?.pressure_msl),clean:{[key:string]:any}={...station,distance:distance===undefined?undefined:distance*1000,trustFactor:Math.round(quality*100)};const check=(key:keyof Station,min:number,max:number,reference?:number,tolerance?:number)=>{const value=finite(station[key]);if(value===undefined)return;if(value<min||value>max||reference!==undefined&&tolerance!==undefined&&Math.abs(value-reference)>tolerance){delete clean[key];rejected.push(String(key));issues.push(`${String(key)} unplausibel`)}else accepted.push(String(key))};check('temperature',-55,60,referenceTemp,12);check('humidity',0,100);check('pressure',850,1100,referencePressure,35);check('windSpeed',0,100);check('windGust',0,150);check('windDirection',0,360);check('precipitation',0,100);check('cloudCover',0,100);if(finite(clean.windSpeed)!==undefined&&finite(clean.windGust)!==undefined&&Number(clean.windGust)<Number(clean.windSpeed)){clean.windGust=clean.windSpeed;issues.push('Böe punktweise an Windniveau angeglichen')}if(!accepted.length)throw new Error('Keine plausiblen Messwerte verfügbar.');quality=Math.max(.35,quality-rejected.length*.08);clean.trustFactor=Math.round(quality*100);clean.uncertainty=Number((1.15-quality).toFixed(2));return{station:clean as Station,quality,issues,accepted,rejected}}

export async function testGenericStation(config=readConnectedStationConfig()){const url=new URL(config.genericUrl);if(url.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(url.hostname))throw new Error('Standard-JSON benötigt HTTPS.');const headers:Record<string,string>={Accept:'application/json','Cache-Control':'no-cache'};if(config.genericBearerToken)headers.Authorization=`Bearer ${config.genericBearerToken}`;const response=await fetch(url.toString(),{cache:'no-store',headers});if(!response.ok)throw new Error(`Stations-JSON HTTP ${response.status}`);return normalizeGeneric(await response.json(),config.genericLabel)}
export async function fetchConnectedStation(location:Location,background?:Station|null,weather?:Weather|null,signal?:AbortSignal):Promise<ConnectedStationObservation|null>{const config=readConnectedStationConfig();if(!config.enabled||config.provider==='none')return null;let station:Station;if(config.provider==='netatmo'){const reply=await workerPost<NetatmoObservationReply>('netatmo-observation',{connectionId:config.connectionId,deviceId:config.selectedDeviceId,moduleId:config.selectedModuleId});if(!reply.observation)throw new Error('Netatmo liefert keine aktuelle Außenmessung.');station=reply.observation as Station}else station=await testGenericStation(config);if(signal?.aborted)throw signal.reason;const result=validateConnectedStation(station,location,background,weather);recordCustomSensorObservation(`${location.latitude.toFixed(5)}:${location.longitude.toFixed(5)}`,{timestamp:result.station.timestamp,label:result.station.name,temperature:result.station.temperature,precipitation:result.station.precipitation,gust:result.station.windGust,cloudCover:result.station.cloudCover,quality:result.quality,provider:config.provider},weather?.timezone);return result}

export function mergeConnectedStation(base:Station|null,own:Station|null){if(!own)return base;if(!base)return own;const keys:(keyof Station)[]=['temperature','humidity','dewPoint','pressure','windSpeed','windDirection','windGust','visibility','cloudCover','ceilingHft','cloudBaseHft','precipitation'];const merged:Station={...base,...own,sourceProviders:[own.provider||'Eigene Wetterstation',...(base.sourceProviders??[base.provider||'Referenznetz'])],stationCount:(base.stationCount??1)+1,blended:false};for(const key of keys)if(own[key]===undefined)Object.assign(merged,{[key]:base[key]});return merged}
