import {useMemo,useState} from 'react';
import {AlertTriangle,Cloud,Clock3,Eye,MapPin,Plane,RefreshCw,Route as RouteIcon,Snowflake,Wind,Zap} from 'lucide-react';
import {fetchWorkerJson} from './workerClient';
import {displayInputFromUtc,displayTimeLabel,formatDisplayDateTime,utcInputFromDisplay} from './timeDisplay';

const ROUTE_KEY='mid:flightCrossSection:route';
const MODEL_KEY='mid:flightCrossSection:model';
const FL_KEY='mid:flightCrossSection:flightLevel';
const SAMPLES_KEY='mid:flightCrossSection:samples';
const START_KEY='mid:flightCrossSection:start';
const END_KEY='mid:flightCrossSection:end';
const CORRIDOR_KEY='mid:flightCrossSection:corridorKm';

type ModelOption={id:string;label:string;detail:string};
const MODELS:ModelOption[]=[
 {id:'best_match',label:'Best Match',detail:'ortsabhängig optimierte Modellwahl'},
 {id:'dwd_icon_eu',label:'DWD ICON-EU',detail:'Europa · hohe räumliche Auflösung'},
 {id:'ecmwf_ifs',label:'ECMWF IFS',detail:'global · robuste synoptische Entwicklung'},
 {id:'ncep_gfs025',label:'NOAA GFS 0,25°',detail:'global · lange Vorhersage'},
 {id:'dwd_icon',label:'DWD ICON Global',detail:'global · DWD-Modell'}
];

type Severity='watch'|'caution';
type CrossLevel={pressure:number;height:number|null;temperature:number|null;humidity:number|null;cloud:number|null;windSpeed:number|null;windDirection:number|null};
type CrossCorridorSample={offsetKm:number;latitude:number;longitude:number;elevation:number;validTime:string;precipitation:number|null;precipitationProbability?:number|null;visibility?:number|null;weatherCode?:number|null;cape?:number|null;freezingLevel?:number|null;gust?:number|null;levels:CrossLevel[]};
type CrossPoint={fraction:number;distanceKm:number;latitude:number;longitude:number;elevation:number;validTime:string;precipitation:number|null;precipitationProbability?:number|null;visibility?:number|null;weatherCode?:number|null;cape?:number|null;freezingLevel?:number|null;gust?:number|null;levels:CrossLevel[];corridorSamples?:CrossCorridorSample[]};
type CrossWaypoint={id:string;name:string;latitude:number;longitude:number;elevation:number;fraction:number;distanceKm:number};
type OfficialSignal={kind:string;label:string;level:'none'|'watch'|'caution';detail:string;source?:string;issuer?:string;validFrom?:string;validTo?:string;distanceKm?:number;value?:number;unit?:string};
type OfficialCheckpoint={id:string;label:string;fraction:number;distanceKm:number;validTime:string;signals:OfficialSignal[];sources?:{id:string;label:string;status:string;detail?:string}[]};
type RouteRegion={fraction:number;distanceKm:number;latitude:number;longitude:number;label:string;admin1?:string;country?:string};
type CrossSectionData={route:string;waypoints:CrossWaypoint[];points:CrossPoint[];totalDistanceKm:number;startTime:string;endTime:string;flightLevel:number;corridorKm?:number;corridorHalfWidthKm?:number;regions?:RouteRegion[];model:string;modelLabel:string;generatedAt:string;source:string;weatherSampleCount?:number;officialBriefing?:OfficialCheckpoint[];version?:string;error?:string};
type PointHazard={kind:'icing'|'turbulence'|'convection'|'wind'|'precipitation'|'visibility'|'ceiling';label:string;severity:Severity;detail:string};
type HazardRun={kind:PointHazard['kind'];label:string;severity:Severity;startIndex:number;endIndex:number;detail:string};

function storageGet(key:string,fallback:string){try{return localStorage.getItem(key)??fallback}catch{return fallback}}
function storageSet(key:string,value:string){try{localStorage.setItem(key,value)}catch{}}
function utcInput(date:Date){return date.toISOString().slice(0,16)}
function initialStart(){const saved=storageGet(START_KEY,'');if(saved)return saved;const date=new Date();date.setUTCMinutes(0,0,0);date.setUTCHours(date.getUTCHours()+1);return utcInput(date)}
function initialEnd(start:string){const saved=storageGet(END_KEY,'');if(saved)return saved;const date=new Date(`${start}:00Z`);date.setUTCHours(date.getUTCHours()+2);return utcInput(date)}
function parseUtcInput(value:string){const parsed=Date.parse(`${value}:00Z`);return Number.isFinite(parsed)?new Date(parsed).toISOString():''}
function finite(value:unknown):number|null{const number=Number(value);return value===null||value===undefined||value===''||!Number.isFinite(number)?null:number}
function hft(metres:number|null){return metres===null?null:metres*3.28084/100}
function mixDirection(a:number,b:number,f:number){const delta=((b-a+540)%360)-180;return(a+delta*f+360)%360}
function routeCodes(value:string){return value.toUpperCase().split(/[^A-Z0-9]+/).map(item=>item.trim()).filter(Boolean)}
function timeLabel(value:string){return formatDisplayDateTime(value,undefined,{hour:'2-digit',minute:'2-digit',hourCycle:'h23'})}
function dateTimeLabel(value:string){return formatDisplayDateTime(value,undefined,{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'})}
function levelRows(levels:CrossLevel[],key:'temperature'|'humidity'|'cloud'|'windSpeed'|'windDirection'){return levels.map(level=>({height:hft(finite(level.height)),value:finite(level[key])})).filter((row):row is {height:number;value:number}=>row.height!==null&&row.value!==null).sort((a,b)=>a.height-b.height)}
function interpolateLevel(levels:CrossLevel[],targetHft:number,key:'temperature'|'humidity'|'cloud'|'windSpeed'|'windDirection'){
 const rows=levelRows(levels,key);if(!rows.length)return null;if(targetHft<=rows[0].height)return rows[0].value;if(targetHft>=rows.at(-1)!.height)return rows.at(-1)!.value;
 for(let index=1;index<rows.length;index++){const a=rows[index-1],b=rows[index];if(targetHft<=b.height){const f=(targetHft-a.height)/Math.max(1,b.height-a.height);return key==='windDirection'?mixDirection(a.value,b.value,f):a.value+(b.value-a.value)*f}}
 return null;
}
function windVector(speed:number,directionFrom:number){const towards=(directionFrom+180)%360,rad=towards*Math.PI/180;return{east:Math.sin(rad)*speed,north:Math.cos(rad)*speed}}
function windShearAt(levels:CrossLevel[],flightLevel:number){const lowSpeed=interpolateLevel(levels,Math.max(0,flightLevel-20),'windSpeed'),highSpeed=interpolateLevel(levels,flightLevel+20,'windSpeed'),lowDirection=interpolateLevel(levels,Math.max(0,flightLevel-20),'windDirection'),highDirection=interpolateLevel(levels,flightLevel+20,'windDirection');if([lowSpeed,highSpeed,lowDirection,highDirection].some(value=>value===null))return null;const a=windVector(lowSpeed!,lowDirection!),b=windVector(highSpeed!,highDirection!),difference=Math.hypot(b.east-a.east,b.north-a.north);return difference/4}
function estimatedCloudBaseFtAgl(point:CrossPoint){const rows=point.levels.map(level=>({height:hft(finite(level.height)),cloud:finite(level.cloud),humidity:finite(level.humidity)})).filter((row):row is {height:number;cloud:number|null;humidity:number|null}=>row.height!==null).sort((a,b)=>a.height-b.height),base=rows.find(row=>(row.cloud??0)>=55||(row.humidity??0)>=92);if(!base)return null;return Math.max(0,base.height*100-point.elevation*3.28084)}
function pointHazardsSingle(point:CrossPoint|CrossCorridorSample,index:number,flightLevel:number,terminal:boolean):PointHazard[]{
 const hazards:PointHazard[]=[],temperature=interpolateLevel(point.levels,flightLevel,'temperature'),humidity=interpolateLevel(point.levels,flightLevel,'humidity'),cloud=interpolateLevel(point.levels,flightLevel,'cloud'),windSpeed=interpolateLevel(point.levels,flightLevel,'windSpeed'),shear=windShearAt(point.levels,flightLevel),precipitation=finite(point.precipitation)??0,cape=finite(point.cape)??0,weatherCode=finite(point.weatherCode)??0,visibility=finite(point.visibility),cloudBase=estimatedCloudBaseFtAgl(point as CrossPoint);
 const inCloud=(cloud??0)>=55||(humidity??0)>=90;
 if(inCloud&&temperature!==null&&temperature<=2&&temperature>=-25){const severe=(cloud??0)>=80&&(humidity??0)>=93&&temperature>=-16&&temperature<=1&&(precipitation>=.3||(cloud??0)>=92);hazards.push({kind:'icing',label:'Vereisung',severity:severe?'caution':'watch',detail:`FL${String(Math.round(flightLevel)).padStart(3,'0')}: ${Math.round(temperature)} °C · Wolken ${Math.round(cloud??0)} % · RH ${Math.round(humidity??0)} %${precipitation>0?` · ${precipitation.toFixed(1)} mm/h Niederschlag`:''}`})}
 if(shear!==null&&shear>=4){hazards.push({kind:'turbulence',label:'Turbulenz / vertikale Windscherung',severity:shear>=7?'caution':'watch',detail:`Modellierte Vektorscherung um FL${String(Math.round(flightLevel)).padStart(3,'0')}: ${shear.toFixed(1)} kt je 1000 ft`})}
 const thunder=[95,96,99].includes(Math.round(weatherCode));if(thunder||cape>=450&&(precipitation>=.25||(cloud??0)>=70)){hazards.push({kind:'convection',label:'Konvektion / Gewitter',severity:thunder||cape>=900?'caution':'watch',detail:`${thunder?'Gewittersignal im Wettercode':`CAPE ${Math.round(cape)} J/kg`}${precipitation>0?` · Niederschlag ${precipitation.toFixed(1)} mm/h`:''}`})}
 if(windSpeed!==null&&windSpeed>=45)hazards.push({kind:'wind',label:'Starker Höhenwind',severity:windSpeed>=65?'caution':'watch',detail:`Wind am gewählten Niveau etwa ${Math.round(windSpeed)} kt`});
 if(precipitation>=.6&&!thunder)hazards.push({kind:'precipitation',label:'Markanter Niederschlag',severity:precipitation>=2?'caution':'watch',detail:`Modellierte Rate etwa ${precipitation.toFixed(1)} mm/h`});
 if(terminal&&visibility!==null&&visibility<10000)hazards.push({kind:'visibility',label:index===0?'Startsicht':'Landesicht',severity:visibility<5000?'caution':'watch',detail:`Bodensicht ${visibility<1000?`${Math.round(visibility/100)*100} m`:`${(visibility/1000).toFixed(1)} km`}`});
 if(terminal&&cloudBase!==null&&cloudBase<2500)hazards.push({kind:'ceiling',label:index===0?'Wolkenuntergrenze Start':'Wolkenuntergrenze Landung',severity:cloudBase<1000?'caution':'watch',detail:`Diagnostische Untergrenze etwa ${cloudBase<100?'<100':Math.round(cloudBase/100)*100} ft AGL`});
 return hazards;
}
function pointHazards(point:CrossPoint,index:number,total:number,flightLevel:number,corridorHalfWidthKm=0):PointHazard[]{
 const terminal=index===0||index===total-1,sets=[pointHazardsSingle(point,index,flightLevel,terminal),...(point.corridorSamples??[]).map(sample=>pointHazardsSingle(sample,index,flightLevel,false))],byKind=new Map<PointHazard['kind'],PointHazard>();
 for(const hazards of sets)for(const hazard of hazards){const current=byKind.get(hazard.kind);if(!current||severityRank(hazard.severity)>severityRank(current.severity))byKind.set(hazard.kind,hazard)}
 return [...byKind.values()].map(hazard=>terminal||corridorHalfWidthKm<=0?hazard:{...hazard,detail:`${hazard.detail} · innerhalb ±${Math.round(corridorHalfWidthKm)} km Korridor`});
}
function severityRank(value:Severity){return value==='caution'?2:1}
function hazardRuns(data:CrossSectionData){const perPoint=data.points.map((point,index)=>pointHazards(point,index,data.points.length,data.flightLevel,data.corridorHalfWidthKm??0)),kinds=['icing','turbulence','convection','wind','precipitation','visibility','ceiling'] as const,runs:HazardRun[]=[];for(const kind of kinds){let active:HazardRun|null=null;for(let index=0;index<perPoint.length;index++){const hazard=perPoint[index].find(item=>item.kind===kind);if(hazard){if(!active)active={kind,label:hazard.label,severity:hazard.severity,startIndex:index,endIndex:index,detail:hazard.detail};else{active.endIndex=index;if(severityRank(hazard.severity)>severityRank(active.severity)){active.severity=hazard.severity;active.detail=hazard.detail}}}else if(active){runs.push(active);active=null}}if(active)runs.push(active)}return runs.sort((a,b)=>severityRank(b.severity)-severityRank(a.severity)||a.startIndex-b.startIndex)}
function nearestWaypoint(data:CrossSectionData,fraction:number){return data.waypoints.reduce((best,waypoint)=>Math.abs(waypoint.fraction-fraction)<Math.abs(best.fraction-fraction)?waypoint:best,data.waypoints[0])}
function nearestRegion(data:CrossSectionData,fraction:number){const regions=data.regions??[];return regions.length?regions.reduce((best,region)=>Math.abs(region.fraction-fraction)<Math.abs(best.fraction-fraction)?region:best,regions[0]):null}
function regionalPositionLabel(data:CrossSectionData,point:CrossPoint){const region=nearestRegion(data,point.fraction);if(region?.label)return`Raum ${region.label}`;const nearest=nearestWaypoint(data,point.fraction);return`Raum ${nearest.name||nearest.id}`}
function runWhere(data:CrossSectionData,run:HazardRun){const start=data.points[run.startIndex],end=data.points[run.endIndex],mid=data.points[Math.round((run.startIndex+run.endIndex)/2)],a=regionalPositionLabel(data,start),b=regionalPositionLabel(data,end),m=regionalPositionLabel(data,mid),startKm=Math.round(start.distanceKm/10)*10,endKm=Math.round(end.distanceKm/10)*10,corridor=data.corridorKm??0;if(a===b||run.endIndex-run.startIndex<=1)return`${m} · etwa km ${Math.round(((start.distanceKm+end.distanceKm)/2)/10)*10}${corridor?` · ${Math.round(corridor)}-km-Korridor`:''}`;return`${a} bis ${b} · etwa km ${startKm}–${endKm}${corridor?` · ${Math.round(corridor)}-km-Korridor`:''}`}
function runWhen(data:CrossSectionData,run:HazardRun){const start=data.points[run.startIndex],end=data.points[run.endIndex],a=timeLabel(start.validTime),b=timeLabel(end.validTime);return a===b?`${a} Uhr`:`${a}–${b} Uhr`}
function compass(direction:number|null){if(direction===null)return'–';const labels=['N','NO','O','SO','S','SW','W','NW'];return`${Math.round(direction)}° ${labels[Math.round((((direction%360)+360)%360)/45)%8]}`}
function hazardIcon(kind:HazardRun['kind']){if(kind==='icing')return <Snowflake size={17}/>;if(kind==='turbulence'||kind==='wind')return <Wind size={17}/>;if(kind==='convection')return <Zap size={17}/>;if(kind==='visibility')return <Eye size={17}/>;if(kind==='ceiling')return <Cloud size={17}/>;return <Cloud size={17}/>}
function officialSignals(data:CrossSectionData){const seen=new Set<string>(),rows:{checkpoint:OfficialCheckpoint;signal:OfficialSignal}[]=[];for(const checkpoint of data.officialBriefing??[]){for(const signal of checkpoint.signals??[]){if(signal.level==='none')continue;const key=[checkpoint.id,signal.kind,signal.source,signal.detail].join('|');if(seen.has(key))continue;seen.add(key);rows.push({checkpoint,signal})}}return rows.sort((a,b)=>(b.signal.level==='caution'?2:1)-(a.signal.level==='caution'?2:1))}
function routeOverview(data:CrossSectionData,runs:HazardRun[]){const cruise=data.points.map(point=>({speed:interpolateLevel(point.levels,data.flightLevel,'windSpeed'),direction:interpolateLevel(point.levels,data.flightLevel,'windDirection'),cloud:interpolateLevel(point.levels,data.flightLevel,'cloud'),temperature:interpolateLevel(point.levels,data.flightLevel,'temperature'),freezing:hft(finite(point.freezingLevel))})),maxWind=Math.max(0,...cruise.map(row=>row.speed??0)),meanCloud=cruise.length?cruise.reduce((sum,row)=>sum+(row.cloud??0),0)/cruise.length:0,temperatures=cruise.map(row=>row.temperature).filter((value):value is number=>value!==null),freezing=cruise.map(row=>row.freezing).filter((value):value is number=>value!==null),danger=runs.filter(run=>run.severity==='caution').length,watch=runs.filter(run=>run.severity==='watch').length;return{maxWind,meanCloud,tempMin:temperatures.length?Math.min(...temperatures):null,tempMax:temperatures.length?Math.max(...temperatures):null,freezingMin:freezing.length?Math.min(...freezing):null,freezingMax:freezing.length?Math.max(...freezing):null,danger,watch}}

export default function CrossSectionPanel(){
 const[start,setStart]=useState(initialStart),[end,setEnd]=useState(()=>initialEnd(initialStart())),[route,setRoute]=useState(()=>storageGet(ROUTE_KEY,'EDDG_EDDF')),[flightLevel,setFlightLevel]=useState(()=>Math.max(0,Math.min(550,Number(storageGet(FL_KEY,'100'))||100))),[model,setModel]=useState(()=>storageGet(MODEL_KEY,'best_match')),[samples,setSamples]=useState(()=>Math.max(17,Math.min(49,Number(storageGet(SAMPLES_KEY,'25'))||25))),[corridorKm,setCorridorKm]=useState(()=>Math.max(20,Math.min(120,Number(storageGet(CORRIDOR_KEY,'40'))||40))),[loading,setLoading]=useState(false),[error,setError]=useState(''),[data,setData]=useState<CrossSectionData|null>(null);
 const codes=routeCodes(route),validRoute=codes.length>=2&&codes.length<=8&&codes.every(code=>/^[A-Z]{4}$/.test(code)),modelOption=MODELS.find(item=>item.id===model)??MODELS[0],runs=useMemo(()=>data?hazardRuns(data):[],[data]),official=useMemo(()=>data?officialSignals(data):[],[data]),overview=useMemo(()=>data?routeOverview(data,runs):null,[data,runs]);
 async function generate(){
  const startIso=parseUtcInput(start),endIso=parseUtcInput(end);if(!validRoute){setError('Bitte 2 bis 8 gültige ICAO-Kennungen mit Leerzeichen, Bindestrich oder Unterstrich eingeben.');return}if(!startIso||!endIso||Date.parse(endIso)<Date.parse(startIso)){setError('Start- und Landezeit müssen gültig sein; die Landung darf nicht vor dem Start liegen.');return}
  setLoading(true);setError('');storageSet(ROUTE_KEY,codes.join('_'));storageSet(MODEL_KEY,model);storageSet(FL_KEY,String(flightLevel));storageSet(SAMPLES_KEY,String(samples));storageSet(CORRIDOR_KEY,String(corridorKm));storageSet(START_KEY,start);storageSet(END_KEY,end);
  try{const response=await fetchWorkerJson<CrossSectionData>('flight-cross-section',{route:codes.join('_'),start:startIso,end:endIso,flight_level:Math.round(flightLevel),model,samples,corridor_km:Math.round(corridorKm)},{purpose:'meteogram',timeoutMs:62000});setData(response)}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setLoading(false)}
 }
 return <section className="flight-cross-section flight-route-briefing">
  <header className="flight-section-head"><div><span>Flugmeteorologie</span><h3>Cross Section · Streckenbriefing</h3><p>Gefahren entlang der Route, am gewählten Flugniveau und passend zu Start- und Landezeit.</p></div><span className="flight-source-badge">Modellprofil + ICAO</span></header>
  <form className="flight-cross-form" onSubmit={event=>{event.preventDefault();void generate()}}>
   <label className="flight-route-input"><span>Route · ICAO-Kennungen</span><div><RouteIcon size={16}/><input value={route} onChange={event=>setRoute(event.target.value.toUpperCase())} placeholder="EDDG EDDL EDDF" autoCapitalize="characters" spellCheck={false}/></div><small>2–8 Orte in Flugrichtung; Zwischenpunkte sind möglich.</small></label>
   <label><span>Start · {displayTimeLabel()}</span><input type="datetime-local" value={displayInputFromUtc(start)} onChange={event=>setStart(utcInputFromDisplay(event.target.value))} step="300"/></label>
   <label><span>Landung · {displayTimeLabel()}</span><input type="datetime-local" value={displayInputFromUtc(end)} onChange={event=>setEnd(utcInputFromDisplay(event.target.value))} step="300"/></label>
   <label><span>Flughöhe</span><div className="flight-number-field"><b>FL</b><input type="number" min="0" max="550" step="10" value={flightLevel} onChange={event=>setFlightLevel(Math.max(0,Math.min(550,Number(event.target.value)||0)))}/></div><small>Einheit: Flight Level / 100 ft.</small></label>
   <label><span>Modell</span><select value={model} onChange={event=>setModel(event.target.value)}>{MODELS.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select><small>{modelOption.detail}</small></label>
   <label><span>Streckendichte</span><select value={samples} onChange={event=>setSamples(Number(event.target.value))}><option value="17">17 · schnell</option><option value="25">25 · ausgewogen</option><option value="33">33 · detailliert</option><option value="41">41 · hoch</option><option value="49">49 · maximal</option></select><small>Mehr Punkte erhöhen Orts- und Zeitauflösung.</small></label>
   <label><span>Analysekorridor</span><select value={corridorKm} onChange={event=>setCorridorKm(Number(event.target.value))}><option value="20">20 km · ±10 km</option><option value="40">40 km · ±20 km</option><option value="60">60 km · ±30 km</option><option value="80">80 km · ±40 km</option><option value="120">120 km · ±60 km</option></select><small>Breiter Korridor reduziert falsche Ortsgenauigkeit und erfasst Hazards neben der Ideallinie.</small></label>
   <button type="submit" className="primary flight-generate" disabled={loading||!validRoute}>{loading?<RefreshCw className="spin" size={16}/>:<Plane size={16}/>} {loading?'Strecke wird analysiert …':'Streckenbriefing erstellen'}</button>
  </form>
  <div className="flight-guide"><AlertTriangle size={15}/><span>Automatisiertes Screening aus Druckniveaumodellen plus verfügbaren ICAO-Flugwetterprodukten. Kein Ersatz für ein vorgeschriebenes amtliches Flugwetterbriefing.</span></div>
  {error&&<div className="error">{error}</div>}
  {data&&overview&&<div className="flight-briefing-result">
   <div className="flight-result-toolbar"><div><b>{data.route.replaceAll('_',' → ')}</b><small>{Math.round(data.totalDistanceKm)} km · FL{String(data.flightLevel).padStart(3,'0')} · {dateTimeLabel(data.startTime)} → {dateTimeLabel(data.endTime)} · {data.modelLabel}</small></div><span className={`flight-briefing-status ${overview.danger?'caution':overview.watch?'watch':'ok'}`}>{overview.danger?`${overview.danger} kritisch`:overview.watch?`${overview.watch} beachten`:'keine markante Modellgefahr'}</span></div>
   <div className="flight-briefing-overview">
    <article><AlertTriangle size={17}/><span><small>Streckenlage</small><strong>{overview.danger} kritisch · {overview.watch} beachten</strong></span></article>
    <article><Wind size={17}/><span><small>Höhenwind</small><strong>max. {Math.round(overview.maxWind)} kt</strong></span></article>
    <article><Cloud size={17}/><span><small>Bewölkung am FL</small><strong>Ø {Math.round(overview.meanCloud)} %</strong></span></article>
    <article><Snowflake size={17}/><span><small>Nullgradniveau</small><strong>{overview.freezingMin===null?'–':`FL${Math.round(overview.freezingMin)}–${Math.round(overview.freezingMax??overview.freezingMin)}`}</strong></span></article>
   </div>
   <section className="flight-route-hazards"><header><div><AlertTriangle size={18}/><span><small>MODELLDIAGNOSTIK</small><strong>Wann und in welchem größeren Raum ist etwas zu erwarten?</strong></span></div></header>{runs.length?<div className="flight-route-hazard-list">{runs.map((run,index)=><article key={`${run.kind}-${run.startIndex}-${index}`} className={run.severity}><div className="flight-route-hazard-icon">{hazardIcon(run.kind)}</div><div><header><strong>{run.label}</strong><span>{run.severity==='caution'?'kritisch':'beachten'}</span></header><p>{run.detail}</p><footer><span><MapPin size={13}/>{runWhere(data,run)}</span><span><Clock3 size={13}/>{runWhen(data,run)}</span></footer></div></article>)}</div>:<div className="flight-route-clear"><Plane size={19}/><span><strong>Keine markante Modellgefahr am gewählten Flugprofil.</strong><small>Amtliche Meldungen und lokale Start-/Landebedingungen trotzdem separat prüfen.</small></span></div>}</section>
   <section className="flight-route-official"><header><div><Plane size={18}/><span><small>AMTLICHE / OPERATIVE SIGNALE</small><strong>Route, Start und Ziel</strong></span></div></header>{official.length?<div className="flight-route-hazard-list official">{official.map(({checkpoint,signal},index)=>{const region=nearestRegion(data,checkpoint.fraction),place=region?.label?`Raum ${region.label} · ${checkpoint.label}`:checkpoint.label;return <article key={`${checkpoint.id}-${signal.kind}-${index}`} className={signal.level==='caution'?'caution':'watch'}><div className="flight-route-hazard-icon"><AlertTriangle size={17}/></div><div><header><strong>{signal.label}</strong><span>{signal.level==='caution'?'kritisch':'beachten'}</span></header><p>{signal.detail}</p><footer><span><MapPin size={13}/>{place} · etwa km {Math.round(checkpoint.distanceKm/10)*10}</span><span><Clock3 size={13}/>{timeLabel(checkpoint.validTime)} Uhr</span>{signal.source&&<span>{signal.source}</span>}</footer></div></article>})}</div>:<div className="flight-route-clear"><Plane size={19}/><span><strong>Keine markanten amtlichen Signale an den geprüften Streckenpunkten.</strong><small>Verfügbare Quellen wurden für Start, En-route und Ziel geprüft; Zugänge können regional unterschiedlich sein.</small></span></div>}</section>
   <div className="flight-point-cards">{data.waypoints.map((waypoint,index)=>{const point=data.points.reduce((best,row)=>Math.abs(row.fraction-waypoint.fraction)<Math.abs(best.fraction-waypoint.fraction)?row:best,data.points[0]),speed=interpolateLevel(point.levels,data.flightLevel,'windSpeed'),direction=interpolateLevel(point.levels,data.flightLevel,'windDirection');return <article key={`${waypoint.id}-${index}`}><header><b>{waypoint.id}</b><span>{Math.round(waypoint.distanceKm)} km</span></header><strong>{waypoint.name||'Flugplatz'}</strong><small>{timeLabel(point.validTime)} Uhr · FL{String(data.flightLevel).padStart(3,'0')} · {compass(direction)} / {speed===null?'–':`${Math.round(speed)} kt`}</small></article>})}</div>
   <small className="flight-data-note">Quelle: {data.source}. Hazards werden bewusst räumlich zusammengefasst: größere Städte/Gebiete und ein {Math.round(data.corridorKm??corridorKm)} km breiter Korridor statt punktgenauer Scheingenauigkeit. Die frühere Cross-Section-Grafik bleibt durch das handlungsorientierte Streckenbriefing ersetzt.</small>
  </div>}
  {!data&&!loading&&!error&&<div className="flight-empty"><Plane size={28}/><strong>Route, Zeit und Flughöhe festlegen</strong><span>MID untersucht anschließend die Strecke in Flugrichtung und nennt relevante Gefahren mit Ort und erwartetem Zeitfenster.</span></div>}
 </section>;
}
