import {useRef,useState,type PointerEvent as ReactPointerEvent} from 'react';
import {ChevronDown,ChevronUp,GripVertical,LayoutGrid,RotateCcw} from 'lucide-react';
import {DASHBOARD_MODULE_DEFINITIONS,defaultDashboardModuleSettings,moveDashboardModule,type DashboardModuleId,type DashboardModuleSettings} from './dashboardModules';

export type DashboardModuleSettingsUpdater=DashboardModuleSettings|((current:DashboardModuleSettings)=>DashboardModuleSettings);
export function DashboardModuleSettingsPanel({settings,onChange,advancedMode}:{settings:DashboardModuleSettings;onChange:(update:DashboardModuleSettingsUpdater)=>void;advancedMode:boolean}){
 const[dragId,setDragId]=useState<DashboardModuleId|null>(null),[dragOverId,setDragOverId]=useState<DashboardModuleId|null>(null),pointerDrag=useRef<{id:DashboardModuleId;pointerId:number}|null>(null),pendingTarget=useRef<DashboardModuleId|null>(null),frame=useRef(0);
 const definitions=new Map(DASHBOARD_MODULE_DEFINITIONS.map(item=>[item.id,item]));
 const commitMove=(source:DashboardModuleId,target:DashboardModuleId)=>onChange(current=>moveDashboardModule(current,source,target));
 const flush=()=>{frame.current=0;const active=pointerDrag.current,target=pendingTarget.current;pendingTarget.current=null;if(active&&target&&active.id!==target){setDragOverId(target);commitMove(active.id,target)}};
 const finish=()=>{if(frame.current){cancelAnimationFrame(frame.current);frame.current=0}flush();pointerDrag.current=null;pendingTarget.current=null;setDragId(null);setDragOverId(null)};
 const pointerStart=(event:ReactPointerEvent<HTMLSpanElement>,id:DashboardModuleId)=>{if(event.pointerType==='mouse')return;event.preventDefault();event.stopPropagation();event.currentTarget.setPointerCapture(event.pointerId);pointerDrag.current={id,pointerId:event.pointerId};setDragId(id)};
 const pointerMove=(event:ReactPointerEvent<HTMLSpanElement>)=>{const active=pointerDrag.current;if(!active||active.pointerId!==event.pointerId)return;event.preventDefault();const id=document.elementFromPoint(event.clientX,event.clientY)?.closest<HTMLElement>('[data-dashboard-module-id]')?.dataset.dashboardModuleId as DashboardModuleId|undefined;if(!id||id===active.id||id===pendingTarget.current)return;pendingTarget.current=id;if(!frame.current)frame.current=requestAnimationFrame(flush)};
 const pointerEnd=(event:ReactPointerEvent<HTMLSpanElement>)=>{if(pointerDrag.current?.pointerId===event.pointerId)finish()};
 const moveBy=(id:DashboardModuleId,delta:number)=>{const index=settings.order.indexOf(id),target=settings.order[index+delta];if(target)commitMove(id,target)};
 return <section className="settings-section dashboard-module-settings"><header><span>Dashboard</span><h3>Sektionen und Reihenfolge</h3><p>Module können ein- oder ausgeschaltet und am Griff verschoben werden. Die Kurzfristvorhersage ist standardmäßig direkt vor der 7-Tage-Vorhersage einsortiert.</p><button type="button" className="dashboard-module-reset" onClick={()=>onChange(defaultDashboardModuleSettings())}><RotateCcw size={15}/><span>Standard wiederherstellen</span></button></header><div className="dashboard-module-list" role="list" aria-label="Dashboard-Sektionen">{settings.order.map((id,index)=>{const definition=definitions.get(id);if(!definition)return null;const unavailable=Boolean(definition.advancedOnly&&!advancedMode);return <div role="listitem" key={id} data-dashboard-module-id={id} draggable className={`dashboard-module-item${dragId===id?' dragging':''}${dragOverId===id&&dragId!==id?' drag-over':''}${unavailable?' unavailable':''}`} onDragStart={event=>{event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',id);setDragId(id)}} onDragOver={event=>{event.preventDefault();setDragOverId(current=>current===id?current:id)}} onDrop={event=>{event.preventDefault();const source=(dragId||event.dataTransfer.getData('text/plain')) as DashboardModuleId;commitMove(source,id);finish()}} onDragEnd={finish}><span className="dashboard-module-grip" title="Zum Verschieben ziehen" aria-hidden="true" onPointerDown={event=>pointerStart(event,id)} onPointerMove={pointerMove} onPointerUp={pointerEnd} onPointerCancel={pointerEnd}><GripVertical size={18}/></span><label><input type="checkbox" checked={settings.enabled[id]} onChange={event=>{const checked=event.target.checked;onChange(current=>({...current,enabled:{...current.enabled,[id]:checked}}))}}/><LayoutGrid size={18}/><span><strong>{definition.label}</strong><small>{definition.description}{definition.conditional?` · ${definition.conditional}`:''}{unavailable?' · nur im Erweiterten Modus':''}</small></span></label><span className="dashboard-module-order-actions"><button type="button" disabled={index===0} onClick={()=>moveBy(id,-1)} aria-label={`${definition.label} nach oben verschieben`}><ChevronUp size={15}/></button><button type="button" disabled={index===settings.order.length-1} onClick={()=>moveBy(id,1)} aria-label={`${definition.label} nach unten verschieben`}><ChevronDown size={15}/></button></span></div>})}</div></section>
}
