import {buildWorkerUrl,workerBaseCandidates} from './workerClient';

export const DEVICE_SYNC_CONFIG_KEY='mid:device-sync:v1';
export type DeviceSyncConfig={enabled:boolean;syncKey:string;deviceId:string;lastSyncAt?:string;pendingChangedAt?:string;lastMessage?:string};
type SyncSnapshot={schema:'mid-device-state';version:1;updatedAt:string;values:Record<string,string>};
type EncryptedBlob={iv:string;data:string};
type WorkerSyncReply={ok?:boolean;error?:string;updatedAt?:string;blob?:EncryptedBlob;version?:string};

let internalWrite=false;
let syncTimer:number|undefined;
let periodicTimer:number|undefined;
const encoder=new TextEncoder(),decoder=new TextDecoder();
const EXCLUDED_PREFIXES=['mid:analysis-cache:','mid:ensemble:','mid:worker:lastGood','mid:device-sync:','mid:connected-station:','mid:twin-background-','mid:update','mid:runtime','mid:state-restored'];
const EXCLUDED_KEYS=new Set(['mid:lastLocation','mid:lastTrackedLocation']);

function b64url(bytes:Uint8Array){let raw='';for(const byte of bytes)raw+=String.fromCharCode(byte);return btoa(raw).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function fromB64url(value:string){const normalized=value.replace(/-/g,'+').replace(/_/g,'/'),raw=atob(normalized+'='.repeat((4-normalized.length%4)%4)),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes}
export function normaliseDeviceSyncCode(value:string){return String(value||'').replace(/[^A-Za-z0-9_-]/g,'')}
export function formatDeviceSyncCode(value:string){const clean=normaliseDeviceSyncCode(value);return clean.match(/.{1,8}/g)?.join('-')||clean}
function randomToken(bytes=32){return b64url(crypto.getRandomValues(new Uint8Array(bytes)))}
function newDeviceId(){return randomToken(12)}
export function readDeviceSyncConfig():DeviceSyncConfig{try{const parsed=JSON.parse(localStorage.getItem(DEVICE_SYNC_CONFIG_KEY)||'{}') as Partial<DeviceSyncConfig>;return{enabled:Boolean(parsed.enabled),syncKey:normaliseDeviceSyncCode(parsed.syncKey||''),deviceId:String(parsed.deviceId||newDeviceId()),lastSyncAt:parsed.lastSyncAt,pendingChangedAt:parsed.pendingChangedAt,lastMessage:parsed.lastMessage}}catch{return{enabled:false,syncKey:'',deviceId:newDeviceId()}}}
function writeConfig(config:DeviceSyncConfig){internalWrite=true;try{localStorage.setItem(DEVICE_SYNC_CONFIG_KEY,JSON.stringify(config))}finally{internalWrite=false}}
export function createDeviceSyncConfig(){const config:DeviceSyncConfig={enabled:true,syncKey:randomToken(32),deviceId:newDeviceId(),pendingChangedAt:new Date().toISOString()};writeConfig(config);return config}
export function disableDeviceSync(){const current=readDeviceSyncConfig();writeConfig({...current,enabled:false,lastMessage:'Synchronisation auf diesem Gerät deaktiviert.'})}
export function useDeviceSyncCode(code:string){const syncKey=normaliseDeviceSyncCode(code);if(syncKey.length<32)throw new Error('Der Synchronisationscode ist zu kurz oder unvollständig.');const config:DeviceSyncConfig={enabled:true,syncKey,deviceId:readDeviceSyncConfig().deviceId||newDeviceId()};writeConfig(config);return config}
function isSyncableKey(key:string){if(['theme','windUnit'].includes(key))return true;if(!key.startsWith('mid:'))return false;if(EXCLUDED_KEYS.has(key)||EXCLUDED_PREFIXES.some(prefix=>key.startsWith(prefix)))return false;return true}
function collectSnapshot():SyncSnapshot{const values:Record<string,string>={};for(let index=0;index<localStorage.length;index++){const key=localStorage.key(index);if(!key||!isSyncableKey(key))continue;const value=localStorage.getItem(key);if(value!==null)values[key]=value}return{schema:'mid-device-state',version:1,updatedAt:new Date().toISOString(),values}}
async function aesKey(syncKey:string){const digest=await crypto.subtle.digest('SHA-256',encoder.encode(syncKey));return crypto.subtle.importKey('raw',digest,{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function encryptSnapshot(snapshot:SyncSnapshot,syncKey:string):Promise<EncryptedBlob>{const iv=crypto.getRandomValues(new Uint8Array(12)),key=await aesKey(syncKey),cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,encoder.encode(JSON.stringify(snapshot))));return{iv:b64url(iv),data:b64url(cipher)}}
async function decryptSnapshot(blob:EncryptedBlob,syncKey:string):Promise<SyncSnapshot>{const key=await aesKey(syncKey),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromB64url(blob.iv)},key,fromB64url(blob.data)),snapshot=JSON.parse(decoder.decode(plain)) as SyncSnapshot;if(snapshot.schema!=='mid-device-state'||snapshot.version!==1||!snapshot.values)throw new Error('Der Synchronisationsstand besitzt ein ungültiges Format.');return snapshot}
async function workerPost(mode:string,body:unknown){const candidates=workerBaseCandidates('general');if(!candidates.length)throw new Error('Cloudflare Worker ist nicht konfiguriert.');const errors:string[]=[];for(const base of candidates){try{const response=await fetch(buildWorkerUrl(base,mode),{method:'POST',cache:'no-store',headers:{Accept:'application/json','Content-Type':'application/json','Cache-Control':'no-cache'},body:JSON.stringify(body)}),text=await response.text();let data:WorkerSyncReply={};try{data=text?JSON.parse(text):{}}catch{throw new Error(`Ungültige Worker-Antwort (HTTP ${response.status}).`)}if(!response.ok||data.error)throw new Error(data.error||`HTTP ${response.status}`);return data}catch(error){errors.push(error instanceof Error?error.message:String(error))}}throw new Error(errors.at(-1)||'Synchronisationsdienst ist nicht erreichbar.')}
function applySnapshot(snapshot:SyncSnapshot){internalWrite=true;try{const remove:string[]=[];for(let index=0;index<localStorage.length;index++){const key=localStorage.key(index);if(key&&isSyncableKey(key)&&!(key in snapshot.values))remove.push(key)}for(const key of remove)localStorage.removeItem(key);for(const[key,value]of Object.entries(snapshot.values))if(isSyncableKey(key))localStorage.setItem(key,value)}finally{internalWrite=false}}
export async function pushDeviceSync(config=readDeviceSyncConfig()){if(!config.enabled||config.syncKey.length<32)return false;const snapshot=collectSnapshot(),blob=await encryptSnapshot(snapshot,config.syncKey),reply=await workerPost('device-sync-push',{syncKey:config.syncKey,deviceId:config.deviceId,updatedAt:snapshot.updatedAt,blob}),next={...config,lastSyncAt:reply.updatedAt||snapshot.updatedAt,pendingChangedAt:undefined,lastMessage:'Lokaler Stand wurde verschlüsselt synchronisiert.'};writeConfig(next);window.dispatchEvent(new CustomEvent('mid:device-sync-status',{detail:next}));return true}
export async function pullDeviceSync(config=readDeviceSyncConfig(),apply=true){if(!config.enabled||config.syncKey.length<32)return{found:false,applied:false};try{const reply=await workerPost('device-sync-pull',{syncKey:config.syncKey});if(!reply.blob||!reply.updatedAt)return{found:false,applied:false};const snapshot=await decryptSnapshot(reply.blob,config.syncKey),remoteTime=Date.parse(reply.updatedAt||snapshot.updatedAt),localPending=Date.parse(config.pendingChangedAt||''),lastSync=Date.parse(config.lastSyncAt||'');if(Number.isFinite(localPending)&&localPending>Math.max(lastSync||0,remoteTime||0)){await pushDeviceSync(config);return{found:true,applied:false}}if(apply&&(!Number.isFinite(lastSync)||remoteTime>lastSync+1000)){applySnapshot(snapshot);const next={...config,lastSyncAt:reply.updatedAt,pendingChangedAt:undefined,lastMessage:'Aktueller Geräteverbund wurde übernommen.'};writeConfig(next);window.dispatchEvent(new CustomEvent('mid:device-sync-status',{detail:next}));return{found:true,applied:true}}const next={...config,lastSyncAt:reply.updatedAt||config.lastSyncAt,lastMessage:'Geräte sind bereits auf demselben Stand.'};writeConfig(next);window.dispatchEvent(new CustomEvent('mid:device-sync-status',{detail:next}));return{found:true,applied:false}}catch(error){if(error instanceof Error&&/nicht gefunden/i.test(error.message))return{found:false,applied:false};throw error}}
export async function syncDeviceStateNow(){const config=readDeviceSyncConfig();if(!config.enabled)return false;const pulled=await pullDeviceSync(config,true);if(!pulled.found)await pushDeviceSync(readDeviceSyncConfig());return true}
export async function restoreDeviceSyncState(){const config=readDeviceSyncConfig();if(!config.enabled||config.syncKey.length<32)return false;try{return(await pullDeviceSync(config,true)).applied}catch{return false}}
function markChanged(){if(internalWrite)return;const config=readDeviceSyncConfig();if(!config.enabled||config.syncKey.length<32)return;writeConfig({...config,pendingChangedAt:new Date().toISOString()});window.clearTimeout(syncTimer);syncTimer=window.setTimeout(()=>void pushDeviceSync(readDeviceSyncConfig()).catch(()=>undefined),2200)}
export function startDeviceSyncBridge(){const originalSet=localStorage.setItem.bind(localStorage),originalRemove=localStorage.removeItem.bind(localStorage);try{localStorage.setItem=((key:string,value:string)=>{originalSet(key,value);if(isSyncableKey(key))markChanged()}) as typeof localStorage.setItem;localStorage.removeItem=((key:string)=>{originalRemove(key);if(isSyncableKey(key))markChanged()}) as typeof localStorage.removeItem}catch{}const refresh=()=>{if(document.visibilityState==='visible')void syncDeviceStateNow().catch(()=>undefined)};document.addEventListener('visibilitychange',refresh);window.addEventListener('pagehide',()=>void pushDeviceSync(readDeviceSyncConfig()).catch(()=>undefined));window.addEventListener('storage',event=>{if(event.key===DEVICE_SYNC_CONFIG_KEY||event.key&&isSyncableKey(event.key))void syncDeviceStateNow().catch(()=>undefined)});periodicTimer=window.setInterval(refresh,5*60000);return()=>{window.clearInterval(periodicTimer);document.removeEventListener('visibilitychange',refresh)}}
