import {exportForecastVerificationArchive,importForecastVerificationArchive,type ForecastVerificationArchiveBundle,type ForecastVerificationArchiveStats} from './forecastVerification';
import {buildWorkerUrl,workerBaseCandidates} from './workerClient';
import {collectPortableUserData,isPortableUserDataKey,replacePortableUserData} from './portableUserData';

export const DEVICE_SYNC_CONFIG_KEY='mid:device-sync:v1';
export const DEVICE_SYNC_PENDING_KEY='mid:device-sync:pending-code';
const DEVICE_SYNC_HASH_KEY='mid-sync';
export type DeviceSyncConfig={
 enabled:boolean;
 syncKey:string;
 deviceId:string;
 lastSyncAt?:string;
 pendingChangedAt?:string;
 lastMessage?:string;
 lastArchiveSyncAt?:string;
 archiveLocations?:number;
 archiveCaptures?:number;
 archiveReferences?:number;
 archiveObservations?:number;
 archiveBytes?:number;
 archiveMessage?:string;
 lastArchiveRevision?:string;
};
type SyncSnapshot={schema:'mid-device-state';version:1|2;updatedAt:string;values:Record<string,string>};
type EncryptedBlob={iv:string;data:string};
type WorkerSyncReply={ok?:boolean;error?:string;updatedAt?:string;blob?:EncryptedBlob;version?:string;found?:boolean;revision?:string;iv?:string;chunks?:number;bytes?:number;chunk?:string};
type ArchiveManifest={found:boolean;updatedAt?:string;revision?:string;iv?:string;chunks?:number;bytes?:number};

let internalWrite=false;
let syncTimer:number|undefined;
let periodicTimer:number|undefined;
let archiveSyncPromise:Promise<unknown>|null=null,deviceSyncPromise:Promise<boolean>|null=null,forceSyncQueued=false;
const encoder=new TextEncoder(),decoder=new TextDecoder();
const ARCHIVE_CHUNK_SIZE=600000;
const MAX_ARCHIVE_CHUNKS=24;
const FAVORITES_KEY='mid:favorites';
const FAVORITES_UPDATED_AT_KEY='mid:favorites:updated-at';

function b64url(bytes:Uint8Array){let raw='';for(const byte of bytes)raw+=String.fromCharCode(byte);return btoa(raw).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function fromB64url(value:string){const normalized=value.replace(/-/g,'+').replace(/_/g,'/'),raw=atob(normalized+'='.repeat((4-normalized.length%4)%4)),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes}
export function normaliseDeviceSyncCode(value:string){return String(value||'').replace(/[^A-Za-z0-9_-]/g,'')}
export function formatDeviceSyncCode(value:string){const clean=normaliseDeviceSyncCode(value);return clean.match(/.{1,8}/g)?.join('-')||clean}
export function parseDeviceSyncTransfer(value:string){
 const raw=String(value||'').trim();if(!raw)return'';
 const decode=(candidate:string)=>{try{return normaliseDeviceSyncCode(decodeURIComponent(candidate))}catch{return normaliseDeviceSyncCode(candidate)}};
 try{
  const url=new URL(raw,typeof location!=='undefined'?location.href:'https://mid.invalid/'),hashParams=new URLSearchParams(url.hash.replace(/^#/,'')),explicit=hashParams.get(DEVICE_SYNC_HASH_KEY)||url.searchParams.get(DEVICE_SYNC_HASH_KEY)||'';
  if(explicit)return decode(explicit);
 }catch{}
 const marked=raw.match(/(?:^|[?#&])mid-sync=([^&#]+)/i)?.[1]||raw.match(/^mid-sync:(.+)$/i)?.[1]||'';
 if(marked)return decode(marked);
 // Nur ein eigenständig übergebener Synchronisationscode darf ohne Marker akzeptiert
 // werden. Normale App-/Update-URLs dürfen niemals durch Entfernen ihrer Sonderzeichen
 // versehentlich zu einem vermeintlichen Gerätecode werden.
 if(/^[A-Za-z0-9_-]{32,}$/.test(raw))return normaliseDeviceSyncCode(raw);
 return'';
}
export function buildDeviceSyncTransferUrl(syncKey:string){
 const clean=normaliseDeviceSyncCode(syncKey);if(clean.length<32)throw new Error('Der Synchronisationscode ist unvollständig.');
 const base=typeof location!=='undefined'?new URL(location.href):new URL('https://mid.invalid/');base.hash=`${DEVICE_SYNC_HASH_KEY}=${encodeURIComponent(clean)}`;return base.toString();
}
export function storePendingDeviceSyncCode(code:string){const clean=normaliseDeviceSyncCode(code);if(clean.length>=32)try{sessionStorage.setItem(DEVICE_SYNC_PENDING_KEY,clean)}catch{}return clean}
export function readPendingDeviceSyncCode(){try{return normaliseDeviceSyncCode(sessionStorage.getItem(DEVICE_SYNC_PENDING_KEY)||'')}catch{return''}}
export function clearPendingDeviceSyncCode(){try{sessionStorage.removeItem(DEVICE_SYNC_PENDING_KEY)}catch{}}
export function consumeDeviceSyncTransferFromLocation(){
 if(typeof location==='undefined')return'';const code=parseDeviceSyncTransfer(location.href);if(code.length<32)return'';storePendingDeviceSyncCode(code);
 try{const cleanUrl=new URL(location.href);cleanUrl.hash='';history.replaceState(history.state,'',cleanUrl.toString())}catch{}
 return code;
}
function randomToken(bytes=32){return b64url(crypto.getRandomValues(new Uint8Array(bytes)))}
function newDeviceId(){return randomToken(12)}
export function readDeviceSyncConfig():DeviceSyncConfig{try{const parsed=JSON.parse(localStorage.getItem(DEVICE_SYNC_CONFIG_KEY)||'{}') as Partial<DeviceSyncConfig>;return{enabled:Boolean(parsed.enabled),syncKey:normaliseDeviceSyncCode(parsed.syncKey||''),deviceId:String(parsed.deviceId||newDeviceId()),lastSyncAt:parsed.lastSyncAt,pendingChangedAt:parsed.pendingChangedAt,lastMessage:parsed.lastMessage,lastArchiveSyncAt:parsed.lastArchiveSyncAt,archiveLocations:Number(parsed.archiveLocations)||0,archiveCaptures:Number(parsed.archiveCaptures)||0,archiveReferences:Number(parsed.archiveReferences)||0,archiveObservations:Number(parsed.archiveObservations)||0,archiveBytes:Number(parsed.archiveBytes)||0,archiveMessage:parsed.archiveMessage,lastArchiveRevision:parsed.lastArchiveRevision}}catch{return{enabled:false,syncKey:'',deviceId:newDeviceId()}}}
function writeConfig(config:DeviceSyncConfig){internalWrite=true;try{localStorage.setItem(DEVICE_SYNC_CONFIG_KEY,JSON.stringify(config))}finally{internalWrite=false}}
function dispatchConfig(config:DeviceSyncConfig){writeConfig(config);window.dispatchEvent(new CustomEvent('mid:device-sync-status',{detail:config}))}
export function createDeviceSyncConfig(){const config:DeviceSyncConfig={enabled:true,syncKey:randomToken(32),deviceId:newDeviceId(),pendingChangedAt:new Date().toISOString()};writeConfig(config);return config}
export function disableDeviceSync(){const current=readDeviceSyncConfig();dispatchConfig({...current,enabled:false,lastMessage:'Synchronisation auf diesem Gerät deaktiviert.'})}
export function useDeviceSyncCode(code:string){const syncKey=normaliseDeviceSyncCode(code);if(syncKey.length<32)throw new Error('Der Synchronisationscode ist zu kurz oder unvollständig.');const current=readDeviceSyncConfig(),config:DeviceSyncConfig={...current,enabled:true,syncKey,deviceId:current.deviceId||newDeviceId(),lastSyncAt:undefined,lastArchiveSyncAt:undefined,pendingChangedAt:undefined};writeConfig(config);return config}
function collectSnapshot():SyncSnapshot{const{values}=collectPortableUserData();return{schema:'mid-device-state',version:2,updatedAt:new Date().toISOString(),values}}
async function aesKey(syncKey:string){const digest=await crypto.subtle.digest('SHA-256',encoder.encode(syncKey));return crypto.subtle.importKey('raw',digest,{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function encryptPayload(value:unknown,syncKey:string):Promise<EncryptedBlob>{const iv=crypto.getRandomValues(new Uint8Array(12)),key=await aesKey(syncKey),cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,encoder.encode(JSON.stringify(value))));return{iv:b64url(iv),data:b64url(cipher)}}
async function decryptPayload<T>(blob:EncryptedBlob,syncKey:string):Promise<T>{const key=await aesKey(syncKey),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromB64url(blob.iv)},key,fromB64url(blob.data));return JSON.parse(decoder.decode(plain)) as T}
async function encryptSnapshot(snapshot:SyncSnapshot,syncKey:string){return encryptPayload(snapshot,syncKey)}
async function decryptSnapshot(blob:EncryptedBlob,syncKey:string){const snapshot=await decryptPayload<SyncSnapshot>(blob,syncKey);if(snapshot.schema!=='mid-device-state'||![1,2].includes(snapshot.version)||!snapshot.values)throw new Error('Der Synchronisationsstand besitzt ein ungültiges Format.');return snapshot}
async function workerPost<T extends WorkerSyncReply=WorkerSyncReply>(mode:string,body:unknown){const candidates=workerBaseCandidates('general');if(!candidates.length)throw new Error('Cloudflare Worker ist nicht konfiguriert.');const errors:string[]=[];for(const base of candidates){try{const response=await fetch(buildWorkerUrl(base,mode),{method:'POST',cache:'no-store',headers:{Accept:'application/json','Content-Type':'application/json','Cache-Control':'no-cache'},body:JSON.stringify(body)}),text=await response.text();let data:T={} as T;try{data=text?JSON.parse(text) as T:{} as T}catch{throw new Error(`Ungültige Worker-Antwort (HTTP ${response.status}).`)}if(!response.ok||data.error){const message=data.error||`HTTP ${response.status}`;if(/nicht freigegebener ursprung/i.test(message)){const origin=typeof location!=='undefined'?location.origin:'diese Web-App';throw new Error(`${origin} ist im eingesetzten Cloudflare-Worker noch nicht freigegeben. Bitte den aktuellen MID-Worker hochladen.`)}throw new Error(message)}return data}catch(error){errors.push(error instanceof Error?error.message:String(error))}}throw new Error(errors.at(-1)||'Synchronisationsdienst ist nicht erreichbar.')}
function favoriteRevision(value:string|undefined|null){const parsed=Date.parse(String(value||''));return Number.isFinite(parsed)?parsed:Number.NaN}
function prepareSnapshotForApply(snapshot:SyncSnapshot){const values={...snapshot.values},localFavorites=localStorage.getItem(FAVORITES_KEY),localFavoriteRevisionText=localStorage.getItem(FAVORITES_UPDATED_AT_KEY),localFavoriteRevision=favoriteRevision(localFavoriteRevisionText),remoteFavoriteRevision=favoriteRevision(values[FAVORITES_UPDATED_AT_KEY]),preserveLocalFavorites=localFavorites!==null&&Number.isFinite(localFavoriteRevision)&&(!Number.isFinite(remoteFavoriteRevision)||localFavoriteRevision>remoteFavoriteRevision+1000);if(preserveLocalFavorites){values[FAVORITES_KEY]=localFavorites;values[FAVORITES_UPDATED_AT_KEY]=localFavoriteRevisionText!}return{values,preserveLocalFavorites}}
function applySnapshot(snapshot:SyncSnapshot){const prepared=prepareSnapshotForApply(snapshot);internalWrite=true;try{return{changed:replacePortableUserData(prepared.values,localStorage,snapshot.version>=2),preservedLocalFavorites:prepared.preserveLocalFavorites}}finally{internalWrite=false}}
function archiveConfig(config:DeviceSyncConfig,stats:ForecastVerificationArchiveStats,bytes:number,message:string,updatedAt:string,revision?:string){return{...config,lastArchiveSyncAt:updatedAt,lastArchiveRevision:revision||config.lastArchiveRevision,archiveLocations:stats.locations,archiveCaptures:stats.captures,archiveReferences:stats.references,archiveObservations:stats.observations,archiveBytes:bytes,archiveMessage:message}}

export async function pushDeviceSync(config=readDeviceSyncConfig()){if(!config.enabled||config.syncKey.length<32)return false;const snapshot=collectSnapshot(),blob=await encryptSnapshot(snapshot,config.syncKey),reply=await workerPost('device-sync-push',{syncKey:config.syncKey,deviceId:config.deviceId,updatedAt:snapshot.updatedAt,blob}),next={...config,lastSyncAt:reply.updatedAt||snapshot.updatedAt,pendingChangedAt:undefined,lastMessage:'Alle portablen MID-Daten dieser Web-App wurden verschlüsselt synchronisiert.'};dispatchConfig(next);return true}
export async function pullDeviceSync(config=readDeviceSyncConfig(),apply=true){if(!config.enabled||config.syncKey.length<32)return{found:false,applied:false};try{const reply=await workerPost('device-sync-pull',{syncKey:config.syncKey});if(!reply.blob||!reply.updatedAt)return{found:false,applied:false};const snapshot=await decryptSnapshot(reply.blob,config.syncKey),remoteTime=Date.parse(reply.updatedAt||snapshot.updatedAt),localPending=Date.parse(config.pendingChangedAt||''),lastSync=Date.parse(config.lastSyncAt||'');if(Number.isFinite(localPending)&&localPending>Math.max(lastSync||0,remoteTime||0)){await pushDeviceSync(config);return{found:true,applied:false}}if(apply&&(!Number.isFinite(lastSync)||remoteTime>lastSync+1000)){const applied=applySnapshot(snapshot),changed=applied.changed,next={...readDeviceSyncConfig(),lastSyncAt:reply.updatedAt,pendingChangedAt:undefined,lastMessage:applied.preservedLocalFavorites?'Neuere lokale Favoriten wurden geschützt; übrige portable Daten wurden abgeglichen.':changed?'Favoriten, Einstellungen, Standorte und Wetterzwilling-Daten wurden vollständig übernommen.':'Alle portablen MID-Daten sind bereits auf demselben Stand.'};dispatchConfig(next);if(applied.preservedLocalFavorites)await pushDeviceSync(readDeviceSyncConfig());if(changed)try{window.dispatchEvent(new CustomEvent('mid:device-sync-applied',{detail:{updatedAt:reply.updatedAt}}))}catch{}return{found:true,applied:changed}}const next={...readDeviceSyncConfig(),lastSyncAt:reply.updatedAt||config.lastSyncAt,lastMessage:'Alle portablen MID-Daten sind bereits auf demselben Stand.'};dispatchConfig(next);return{found:true,applied:false}}catch(error){if(error instanceof Error&&/nicht gefunden/i.test(error.message))return{found:false,applied:false};throw error}}

async function remoteArchiveManifest(config:DeviceSyncConfig):Promise<ArchiveManifest>{try{const reply=await workerPost('device-sync-archive-manifest',{syncKey:config.syncKey});return{found:Boolean(reply.found!==false&&reply.revision&&reply.iv&&reply.chunks),updatedAt:reply.updatedAt,revision:reply.revision,iv:reply.iv,chunks:Number(reply.chunks)||0,bytes:Number(reply.bytes)||0}}catch(error){if(error instanceof Error&&/nicht gefunden/i.test(error.message))return{found:false};throw error}}
export async function pushWeatherTwinArchive(config=readDeviceSyncConfig(),force=false){if(!config.enabled||config.syncKey.length<32)return false;if(archiveSyncPromise)return archiveSyncPromise as Promise<boolean>;archiveSyncPromise=(async()=>{const bundle=await exportForecastVerificationArchive(),localTime=Date.parse(bundle.updatedAt),lastTime=Date.parse(config.lastArchiveSyncAt||'');if(!force&&Number.isFinite(lastTime)&&Number.isFinite(localTime)&&lastTime>=localTime)return false;const blob=await encryptPayload(bundle,config.syncKey),chunks=[] as string[];for(let offset=0;offset<blob.data.length;offset+=ARCHIVE_CHUNK_SIZE)chunks.push(blob.data.slice(offset,offset+ARCHIVE_CHUNK_SIZE));if(chunks.length>MAX_ARCHIVE_CHUNKS)throw new Error(`Das verschlüsselte Wetterzwilling-Archiv ist mit ${Math.round(blob.data.length/1024/1024*10)/10} MB zu groß für die aktuelle Synchronisation.`);const revision=randomToken(12);for(let index=0;index<chunks.length;index++)await workerPost('device-sync-archive-chunk-push',{syncKey:config.syncKey,revision,index,total:chunks.length,chunk:chunks[index]});const reply=await workerPost('device-sync-archive-commit',{syncKey:config.syncKey,revision,iv:blob.iv,chunks:chunks.length,bytes:blob.data.length,updatedAt:bundle.updatedAt,deviceId:config.deviceId}),stats:ForecastVerificationArchiveStats={...bundle.counts,updatedAt:bundle.updatedAt},message=`Vollständiges Wetterzwilling-Langzeitarchiv verschlüsselt gesichert: ${stats.locations} Standorte · ${stats.captures+stats.references+stats.observations} Datensätze.`;dispatchConfig(archiveConfig(readDeviceSyncConfig(),stats,blob.data.length,message,reply.updatedAt||bundle.updatedAt,revision));return true})().finally(()=>{archiveSyncPromise=null});return archiveSyncPromise as Promise<boolean>}
export async function pullWeatherTwinArchive(config=readDeviceSyncConfig()){if(!config.enabled||config.syncKey.length<32)return{found:false,applied:false};const manifest=await remoteArchiveManifest(config);if(!manifest.found||!manifest.revision||!manifest.iv||!manifest.chunks)return{found:false,applied:false};const remoteTime=Date.parse(manifest.updatedAt||''),localTime=Date.parse(config.lastArchiveSyncAt||''),sameRevision=Boolean(config.lastArchiveRevision&&manifest.revision===config.lastArchiveRevision);if(sameRevision||(!config.lastArchiveRevision&&Number.isFinite(remoteTime)&&Number.isFinite(localTime)&&remoteTime<=localTime+1000))return{found:true,applied:false};if(manifest.chunks>MAX_ARCHIVE_CHUNKS)throw new Error('Das entfernte Wetterzwilling-Archiv überschreitet die unterstützte Größe.');const chunks:string[]=[];for(let index=0;index<manifest.chunks;index++){const reply=await workerPost('device-sync-archive-chunk-pull',{syncKey:config.syncKey,revision:manifest.revision,index});if(typeof reply.chunk!=='string')throw new Error(`Archivteil ${index+1} von ${manifest.chunks} fehlt.`);chunks.push(reply.chunk)}const bundle=await decryptPayload<ForecastVerificationArchiveBundle>({iv:manifest.iv,data:chunks.join('')},config.syncKey),stats=await importForecastVerificationArchive(bundle),message=`Vollständiges Wetterzwilling-Langzeitarchiv übernommen: ${stats.locations} Standorte · ${stats.captures+stats.references+stats.observations} Datensätze.`;dispatchConfig(archiveConfig(readDeviceSyncConfig(),stats,manifest.bytes||chunks.reduce((sum,chunk)=>sum+chunk.length,0),message,manifest.updatedAt||bundle.updatedAt,manifest.revision));return{found:true,applied:true,stats}}

async function runDeviceSyncOnce(forceArchive=false){const config=readDeviceSyncConfig();if(!config.enabled||navigator.onLine===false)return false;const[pulled,archivePulled]=await Promise.all([pullDeviceSync(config,true),pullWeatherTwinArchive(config)]),current=readDeviceSyncConfig();if(!pulled.found||current.pendingChangedAt)await pushDeviceSync(current);await pushWeatherTwinArchive(readDeviceSyncConfig(),forceArchive||!archivePulled.found);const next=readDeviceSyncConfig();dispatchConfig({...next,lastMessage:'Geräteabgleich einschließlich vollständigem Wetterzwilling-Langzeitarchiv abgeschlossen.'});return true}
export function syncDeviceStateNow(forceArchive=false){forceSyncQueued=forceSyncQueued||forceArchive;if(deviceSyncPromise)return deviceSyncPromise;deviceSyncPromise=(async()=>{let result=false;do{const force=forceSyncQueued;forceSyncQueued=false;result=await runDeviceSyncOnce(force)||result}while(forceSyncQueued);return result})().finally(()=>{deviceSyncPromise=null});return deviceSyncPromise}
export async function restoreDeviceSyncState(){const config=readDeviceSyncConfig();if(!config.enabled||config.syncKey.length<32||navigator.onLine===false)return false;try{const[state,archive]=await Promise.all([pullDeviceSync(config,true),pullWeatherTwinArchive(config)]);return state.applied||archive.applied}catch{return false}}
function markChanged(){if(internalWrite)return;const config=readDeviceSyncConfig();if(!config.enabled||config.syncKey.length<32)return;writeConfig({...config,pendingChangedAt:new Date().toISOString()});window.clearTimeout(syncTimer);syncTimer=window.setTimeout(()=>void pushDeviceSync(readDeviceSyncConfig()).catch(()=>undefined),850)}
export function startDeviceSyncBridge(){const originalSet=localStorage.setItem.bind(localStorage),originalRemove=localStorage.removeItem.bind(localStorage);let archiveTimer:number|undefined,reloadTimer:number|undefined;try{localStorage.setItem=((key:string,value:string)=>{if(localStorage.getItem(key)===value)return;originalSet(key,value);if(isPortableUserDataKey(key))markChanged()}) as typeof localStorage.setItem;localStorage.removeItem=((key:string)=>{if(localStorage.getItem(key)===null)return;originalRemove(key);if(isPortableUserDataKey(key))markChanged()}) as typeof localStorage.removeItem}catch{}const refresh=()=>{if(document.visibilityState==='visible'&&navigator.onLine!==false)void syncDeviceStateNow(false).catch(()=>undefined)},pagehide=()=>void pushDeviceSync(readDeviceSyncConfig()).catch(()=>undefined),storage=(event:StorageEvent)=>{if(event.key===DEVICE_SYNC_CONFIG_KEY||event.key&&isPortableUserDataKey(event.key))refresh()},archiveChanged=()=>{window.clearTimeout(archiveTimer);archiveTimer=window.setTimeout(()=>void syncDeviceStateNow(true).catch(()=>undefined),1800)},remoteApplied=()=>{if(document.visibilityState!=='visible')return;window.clearTimeout(reloadTimer);reloadTimer=window.setTimeout(()=>{try{const marker='mid:device-sync:last-reload';const last=Number(sessionStorage.getItem(marker)||0);if(Date.now()-last<8000)return;sessionStorage.setItem(marker,String(Date.now()))}catch{}location.reload()},450)};document.addEventListener('visibilitychange',refresh);window.addEventListener('pagehide',pagehide);window.addEventListener('storage',storage);window.addEventListener('online',refresh);window.addEventListener('mid:weather-twin-archive-changed',archiveChanged as EventListener);window.addEventListener('mid:backup-restored',archiveChanged as EventListener);window.addEventListener('mid:device-sync-applied',remoteApplied as EventListener);periodicTimer=window.setInterval(refresh,2*60000);return()=>{window.clearInterval(periodicTimer);window.clearTimeout(archiveTimer);window.clearTimeout(reloadTimer);document.removeEventListener('visibilitychange',refresh);window.removeEventListener('pagehide',pagehide);window.removeEventListener('storage',storage);window.removeEventListener('online',refresh);window.removeEventListener('mid:weather-twin-archive-changed',archiveChanged as EventListener);window.removeEventListener('mid:backup-restored',archiveChanged as EventListener);window.removeEventListener('mid:device-sync-applied',remoteApplied as EventListener)}}
