import {exportForecastVerificationArchive,importForecastVerificationArchive,type ForecastVerificationArchiveBundle,type ForecastVerificationArchiveStats} from './forecastVerification';
import {buildWorkerUrl,workerBaseCandidates} from './workerClient';

export const DEVICE_SYNC_CONFIG_KEY='mid:device-sync:v1';
export type DeviceSyncConfig={
 enabled:boolean;
 syncKey:string;
 deviceId:string;
 lastSyncAt?:string;
 pendingChangedAt?:string;
 lastMessage?:string;
 lastArchiveSyncAt?:string;
 archiveLocations?:number;
 archiveCaptures?:number;
 archiveReferences?:number;
 archiveObservations?:number;
 archiveBytes?:number;
 archiveMessage?:string;
};
type SyncSnapshot={schema:'mid-device-state';version:1;updatedAt:string;values:Record<string,string>};
type EncryptedBlob={iv:string;data:string};
type WorkerSyncReply={ok?:boolean;error?:string;updatedAt?:string;blob?:EncryptedBlob;version?:string;found?:boolean;revision?:string;iv?:string;chunks?:number;bytes?:number;chunk?:string};
type ArchiveManifest={found:boolean;updatedAt?:string;revision?:string;iv?:string;chunks?:number;bytes?:number};

let internalWrite=false;
let syncTimer:number|undefined;
let periodicTimer:number|undefined;
let archiveSyncPromise:Promise<unknown>|null=null;
const encoder=new TextEncoder(),decoder=new TextDecoder();
const EXCLUDED_PREFIXES=['mid:analysis-cache:','mid:ensemble:','mid:worker:lastGood','mid:device-sync:','mid:connected-station:','mid:twin-background-','mid:update','mid:runtime','mid:state-restored'];
const EXCLUDED_KEYS=new Set(['mid:lastLocation','mid:lastTrackedLocation']);
const ARCHIVE_CHUNK_SIZE=600000;
const MAX_ARCHIVE_CHUNKS=24;

function b64url(bytes:Uint8Array){let raw='';for(const byte of bytes)raw+=String.fromCharCode(byte);return btoa(raw).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function fromB64url(value:string){const normalized=value.replace(/-/g,'+').replace(/_/g,'/'),raw=atob(normalized+'='.repeat((4-normalized.length%4)%4)),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes}
export function normaliseDeviceSyncCode(value:string){return String(value||'').replace(/[^A-Za-z0-9_-]/g,'')}
export function formatDeviceSyncCode(value:string){const clean=normaliseDeviceSyncCode(value);return clean.match(/.{1,8}/g)?.join('-')||clean}
function randomToken(bytes=32){return b64url(crypto.getRandomValues(new Uint8Array(bytes)))}
function newDeviceId(){return randomToken(12)}
export function readDeviceSyncConfig():DeviceSyncConfig{try{const parsed=JSON.parse(localStorage.getItem(DEVICE_SYNC_CONFIG_KEY)||'{}') as Partial<DeviceSyncConfig>;return{enabled:Boolean(parsed.enabled),syncKey:normaliseDeviceSyncCode(parsed.syncKey||''),deviceId:String(parsed.deviceId||newDeviceId()),lastSyncAt:parsed.lastSyncAt,pendingChangedAt:parsed.pendingChangedAt,lastMessage:parsed.lastMessage,lastArchiveSyncAt:parsed.lastArchiveSyncAt,archiveLocations:Number(parsed.archiveLocations)||0,archiveCaptures:Number(parsed.archiveCaptures)||0,archiveReferences:Number(parsed.archiveReferences)||0,archiveObservations:Number(parsed.archiveObservations)||0,archiveBytes:Number(parsed.archiveBytes)||0,archiveMessage:parsed.archiveMessage}}catch{return{enabled:false,syncKey:'',deviceId:newDeviceId()}}}
function writeConfig(config:DeviceSyncConfig){internalWrite=true;try{localStorage.setItem(DEVICE_SYNC_CONFIG_KEY,JSON.stringify(config))}finally{internalWrite=false}}
function dispatchConfig(config:DeviceSyncConfig){writeConfig(config);window.dispatchEvent(new CustomEvent('mid:device-sync-status',{detail:config}))}
export function createDeviceSyncConfig(){const config:DeviceSyncConfig={enabled:true,syncKey:randomToken(32),deviceId:newDeviceId(),pendingChangedAt:new Date().toISOString()};writeConfig(config);return config}
export function disableDeviceSync(){const current=readDeviceSyncConfig();dispatchConfig({...current,enabled:false,lastMessage:'Synchronisation auf diesem Gerät deaktiviert.'})}
export function useDeviceSyncCode(code:string){const syncKey=normaliseDeviceSyncCode(code);if(syncKey.length<32)throw new Error('Der Synchronisationscode ist zu kurz oder unvollständig.');const current=readDeviceSyncConfig(),config:DeviceSyncConfig={...current,enabled:true,syncKey,deviceId:current.deviceId||newDeviceId(),lastSyncAt:undefined,lastArchiveSyncAt:undefined,pendingChangedAt:undefined};writeConfig(config);return config}
function isSyncableKey(key:string){if(['theme','windUnit'].includes(key))return true;if(!key.startsWith('mid:'))return false;if(EXCLUDED_KEYS.has(key)||EXCLUDED_PREFIXES.some(prefix=>key.startsWith(prefix)))return false;return true}
function collectSnapshot():SyncSnapshot{const values:Record<string,string>={};for(let index=0;index<localStorage.length;index++){const key=localStorage.key(index);if(!key||!isSyncableKey(key))continue;const value=localStorage.getItem(key);if(value!==null)values[key]=value}return{schema:'mid-device-state',version:1,updatedAt:new Date().toISOString(),values}}
async function aesKey(syncKey:string){const digest=await crypto.subtle.digest('SHA-256',encoder.encode(syncKey));return crypto.subtle.importKey('raw',digest,{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function encryptPayload(value:unknown,syncKey:string):Promise<EncryptedBlob>{const iv=crypto.getRandomValues(new Uint8Array(12)),key=await aesKey(syncKey),cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,encoder.encode(JSON.stringify(value))));return{iv:b64url(iv),data:b64url(cipher)}}
async function decryptPayload<T>(blob:EncryptedBlob,syncKey:string):Promise<T>{const key=await aesKey(syncKey),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:fromB64url(blob.iv)},key,fromB64url(blob.data));return JSON.parse(decoder.decode(plain)) as T}
async function encryptSnapshot(snapshot:SyncSnapshot,syncKey:string){return encryptPayload(snapshot,syncKey)}
async function decryptSnapshot(blob:EncryptedBlob,syncKey:string){const snapshot=await decryptPayload<SyncSnapshot>(blob,syncKey);if(snapshot.schema!=='mid-device-state'||snapshot.version!==1||!snapshot.values)throw new Error('Der Synchronisationsstand besitzt ein ungültiges Format.');return snapshot}
async function workerPost<T extends WorkerSyncReply=WorkerSyncReply>(mode:string,body:unknown){const candidates=workerBaseCandidates('general');if(!candidates.length)throw new Error('Cloudflare Worker ist nicht konfiguriert.');const errors:string[]=[];for(const base of candidates){try{const response=await fetch(buildWorkerUrl(base,mode),{method:'POST',cache:'no-store',headers:{Accept:'application/json','Content-Type':'application/json','Cache-Control':'no-cache'},body:JSON.stringify(body)}),text=await response.text();let data:T={} as T;try{data=text?JSON.parse(text) as T:{} as T}catch{throw new Error(`Ungültige Worker-Antwort (HTTP ${response.status}).`)}if(!response.ok||data.error)throw new Error(data.error||`HTTP ${response.status}`);return data}catch(error){errors.push(error instanceof Error?error.message:String(error))}}throw new Error(errors.at(-1)||'Synchronisationsdienst ist nicht erreichbar.')}
function applySnapshot(snapshot:SyncSnapshot){internalWrite=true;try{const remove:string[]=[];for(let index=0;index<localStorage.length;index++){const key=localStorage.key(index);if(key&&isSyncableKey(key)&&!(key in snapshot.values))remove.push(key)}for(const key of remove)localStorage.removeItem(key);for(const[key,value]of Object.entries(snapshot.values))if(isSyncableKey(key))localStorage.setItem(key,value)}finally{internalWrite=false}}
function archiveConfig(config:DeviceSyncConfig,stats:ForecastVerificationArchiveStats,bytes:number,message:string,updatedAt:string){return{...config,lastArchiveSyncAt:updatedAt,archiveLocations:stats.locations,archiveCaptures:stats.captures,archiveReferences:stats.references,archiveObservations:stats.observations,archiveBytes:bytes,archiveMessage:message}}

export async function pushDeviceSync(config=readDeviceSyncConfig()){if(!config.enabled||config.syncKey.length<32)return false;const snapshot=collectSnapshot(),blob=await encryptSnapshot(snapshot,config.syncKey),reply=await workerPost('device-sync-push',{syncKey:config.syncKey,deviceId:config.deviceId,updatedAt:snapshot.updatedAt,blob}),next={...config,lastSyncAt:reply.updatedAt||snapshot.updatedAt,pendingChangedAt:undefined,lastMessage:'Lokaler Einstellungsstand wurde verschlüsselt synchronisiert.'};dispatchConfig(next);return true}
export async function pullDeviceSync(config=readDeviceSyncConfig(),apply=true){if(!config.enabled||config.syncKey.length<32)return{found:false,applied:false};try{const reply=await workerPost('device-sync-pull',{syncKey:config.syncKey});if(!reply.blob||!reply.updatedAt)return{found:false,applied:false};const snapshot=await decryptSnapshot(reply.blob,config.syncKey),remoteTime=Date.parse(reply.updatedAt||snapshot.updatedAt),localPending=Date.parse(config.pendingChangedAt||''),lastSync=Date.parse(config.lastSyncAt||'');if(Number.isFinite(localPending)&&localPending>Math.max(lastSync||0,remoteTime||0)){await pushDeviceSync(config);return{found:true,applied:false}}if(apply&&(!Number.isFinite(lastSync)||remoteTime>lastSync+1000)){applySnapshot(snapshot);const next={...readDeviceSyncConfig(),lastSyncAt:reply.updatedAt,pendingChangedAt:undefined,lastMessage:'Aktueller Geräteverbund wurde übernommen.'};dispatchConfig(next);return{found:true,applied:true}}const next={...readDeviceSyncConfig(),lastSyncAt:reply.updatedAt||config.lastSyncAt,lastMessage:'Geräte sind bereits auf demselben Einstellungsstand.'};dispatchConfig(next);return{found:true,applied:false}}catch(error){if(error instanceof Error&&/nicht gefunden/i.test(error.message))return{found:false,applied:false};throw error}}

async function remoteArchiveManifest(config:DeviceSyncConfig):Promise<ArchiveManifest>{try{const reply=await workerPost('device-sync-archive-manifest',{syncKey:config.syncKey});return{found:Boolean(reply.found!==false&&reply.revision&&reply.iv&&reply.chunks),updatedAt:reply.updatedAt,revision:reply.revision,iv:reply.iv,chunks:Number(reply.chunks)||0,bytes:Number(reply.bytes)||0}}catch(error){if(error instanceof Error&&/nicht gefunden/i.test(error.message))return{found:false};throw error}}
export async function pushWeatherTwinArchive(config=readDeviceSyncConfig(),force=false){if(!config.enabled||config.syncKey.length<32)return false;if(archiveSyncPromise)return archiveSyncPromise as Promise<boolean>;archiveSyncPromise=(async()=>{const bundle=await exportForecastVerificationArchive(),localTime=Date.parse(bundle.updatedAt),lastTime=Date.parse(config.lastArchiveSyncAt||'');if(!force&&Number.isFinite(lastTime)&&Number.isFinite(localTime)&&lastTime>=localTime)return false;const blob=await encryptPayload(bundle,config.syncKey),chunks=[] as string[];for(let offset=0;offset<blob.data.length;offset+=ARCHIVE_CHUNK_SIZE)chunks.push(blob.data.slice(offset,offset+ARCHIVE_CHUNK_SIZE));if(chunks.length>MAX_ARCHIVE_CHUNKS)throw new Error(`Das verschlüsselte Wetterzwilling-Archiv ist mit ${Math.round(blob.data.length/1024/1024*10)/10} MB zu groß für die aktuelle Synchronisation.`);const revision=randomToken(12);for(let index=0;index<chunks.length;index++)await workerPost('device-sync-archive-chunk-push',{syncKey:config.syncKey,revision,index,total:chunks.length,chunk:chunks[index]});const reply=await workerPost('device-sync-archive-commit',{syncKey:config.syncKey,revision,iv:blob.iv,chunks:chunks.length,bytes:blob.data.length,updatedAt:bundle.updatedAt,deviceId:config.deviceId}),stats:ForecastVerificationArchiveStats={...bundle.counts,updatedAt:bundle.updatedAt},message=`Vollständiges Wetterzwilling-Langzeitarchiv verschlüsselt gesichert: ${stats.locations} Standorte · ${stats.captures+stats.references+stats.observations} Datensätze.`;dispatchConfig(archiveConfig(readDeviceSyncConfig(),stats,blob.data.length,message,reply.updatedAt||bundle.updatedAt));return true})().finally(()=>{archiveSyncPromise=null});return archiveSyncPromise as Promise<boolean>}
export async function pullWeatherTwinArchive(config=readDeviceSyncConfig()){if(!config.enabled||config.syncKey.length<32)return{found:false,applied:false};const manifest=await remoteArchiveManifest(config);if(!manifest.found||!manifest.revision||!manifest.iv||!manifest.chunks)return{found:false,applied:false};if(manifest.chunks>MAX_ARCHIVE_CHUNKS)throw new Error('Das entfernte Wetterzwilling-Archiv überschreitet die unterstützte Größe.');const chunks:string[]=[];for(let index=0;index<manifest.chunks;index++){const reply=await workerPost('device-sync-archive-chunk-pull',{syncKey:config.syncKey,revision:manifest.revision,index});if(typeof reply.chunk!=='string')throw new Error(`Archivteil ${index+1} von ${manifest.chunks} fehlt.`);chunks.push(reply.chunk)}const bundle=await decryptPayload<ForecastVerificationArchiveBundle>({iv:manifest.iv,data:chunks.join('')},config.syncKey),stats=await importForecastVerificationArchive(bundle),message=`Vollständiges Wetterzwilling-Langzeitarchiv übernommen: ${stats.locations} Standorte · ${stats.captures+stats.references+stats.observations} Datensätze.`;dispatchConfig(archiveConfig(readDeviceSyncConfig(),stats,manifest.bytes||chunks.reduce((sum,chunk)=>sum+chunk.length,0),message,manifest.updatedAt||bundle.updatedAt));return{found:true,applied:true,stats}}

export async function syncDeviceStateNow(forceArchive=false){const config=readDeviceSyncConfig();if(!config.enabled)return false;const pulled=await pullDeviceSync(config,true),archivePulled=await pullWeatherTwinArchive(readDeviceSyncConfig());const current=readDeviceSyncConfig();if(!pulled.found||current.pendingChangedAt)await pushDeviceSync(current);await pushWeatherTwinArchive(readDeviceSyncConfig(),forceArchive||!archivePulled.found);const next=readDeviceSyncConfig();dispatchConfig({...next,lastMessage:'Geräteabgleich einschließlich vollständigem Wetterzwilling-Langzeitarchiv abgeschlossen.'});return true}
export async function restoreDeviceSyncState(){const config=readDeviceSyncConfig();if(!config.enabled||config.syncKey.length<32)return false;try{const state=await pullDeviceSync(config,true),archive=await pullWeatherTwinArchive(readDeviceSyncConfig());return state.applied||archive.applied}catch{return false}}
function markChanged(){if(internalWrite)return;const config=readDeviceSyncConfig();if(!config.enabled||config.syncKey.length<32)return;writeConfig({...config,pendingChangedAt:new Date().toISOString()});window.clearTimeout(syncTimer);syncTimer=window.setTimeout(()=>void pushDeviceSync(readDeviceSyncConfig()).catch(()=>undefined),2200)}
export function startDeviceSyncBridge(){const originalSet=localStorage.setItem.bind(localStorage),originalRemove=localStorage.removeItem.bind(localStorage);try{localStorage.setItem=((key:string,value:string)=>{originalSet(key,value);if(isSyncableKey(key))markChanged()}) as typeof localStorage.setItem;localStorage.removeItem=((key:string)=>{originalRemove(key);if(isSyncableKey(key))markChanged()}) as typeof localStorage.removeItem}catch{}const refresh=()=>{if(document.visibilityState==='visible')void syncDeviceStateNow(false).catch(()=>undefined)};document.addEventListener('visibilitychange',refresh);window.addEventListener('pagehide',()=>void pushDeviceSync(readDeviceSyncConfig()).catch(()=>undefined));window.addEventListener('storage',event=>{if(event.key===DEVICE_SYNC_CONFIG_KEY||event.key&&isSyncableKey(event.key))void syncDeviceStateNow(false).catch(()=>undefined)});periodicTimer=window.setInterval(refresh,5*60000);return()=>{window.clearInterval(periodicTimer);document.removeEventListener('visibilitychange',refresh)}}
