import {useEffect,useState} from 'react';
import {Check,ClipboardCopy,Cloud,Link2,RefreshCw,ShieldCheck} from 'lucide-react';
import {createDeviceSyncConfig,disableDeviceSync,formatDeviceSyncCode,pullDeviceSync,pullWeatherTwinArchive,pushDeviceSync,pushWeatherTwinArchive,readDeviceSyncConfig,syncDeviceStateNow,useDeviceSyncCode,type DeviceSyncConfig} from './deviceSync';

export function DeviceSyncSettings(){
 const[config,setConfig]=useState<DeviceSyncConfig>(()=>readDeviceSyncConfig()),[joinCode,setJoinCode]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(config.lastMessage||'');
 useEffect(()=>{const update=(event:Event)=>{const detail=(event as CustomEvent<DeviceSyncConfig>).detail;setConfig(detail||readDeviceSyncConfig());if(detail?.lastMessage)setMessage(detail.lastMessage)};window.addEventListener('mid:device-sync-status',update);return()=>window.removeEventListener('mid:device-sync-status',update)},[]);
 const run=async(task:()=>Promise<unknown>)=>{setBusy(true);setMessage('Synchronisation läuft …');try{await task();const next=readDeviceSyncConfig();setConfig(next);setMessage(next.lastMessage||'Synchronisation abgeschlossen.')}catch(error){setMessage(error instanceof Error?error.message:String(error))}finally{setBusy(false)}};
 const toggle=async(enabled:boolean)=>{if(!enabled){disableDeviceSync();setConfig(readDeviceSyncConfig());setMessage('Synchronisation auf diesem Gerät deaktiviert.');return}const next=config.syncKey?{...config,enabled:true}:createDeviceSyncConfig();if(config.syncKey){localStorage.setItem('mid:device-sync:v1',JSON.stringify(next))}setConfig(next);await run(async()=>{await pushDeviceSync(next);await pushWeatherTwinArchive(readDeviceSyncConfig(),true)})};
 const connect=async()=>{await run(async()=>{const next=useDeviceSyncCode(joinCode);const result=await pullDeviceSync(next,true),archive=await pullWeatherTwinArchive(readDeviceSyncConfig());if(!result.found&&!archive.found)throw new Error('Zu diesem Synchronisationscode wurde noch kein gespeicherter Stand gefunden.');setJoinCode('');window.setTimeout(()=>location.reload(),350)})};
 const copy=async()=>{try{await navigator.clipboard.writeText(formatDeviceSyncCode(config.syncKey));setMessage('Synchronisationscode kopiert.')}catch{setMessage('Kopieren ist in diesem Browser nicht verfügbar.')}};
 return <section className="device-sync-settings"><header><Cloud size={21}/><span><strong>Geräteübergreifende Synchronisation</strong><small>Favoriten, Einstellungen, Profile sowie das vollständige Wetterzwilling-Langzeitarchiv aus IndexedDB verschlüsselt zwischen MID-Geräten abgleichen.</small></span></header><label className="settings-toggle-card"><input type="checkbox" checked={config.enabled} disabled={busy} onChange={event=>void toggle(event.target.checked)}/><ShieldCheck size={21}/><span><strong>Auf diesem Gerät aktivieren</strong><small>Auch sämtliche Prognosesnapshots, Beobachtungen und Rückblicke werden vor dem Upload im Browser mit AES-GCM verschlüsselt. Der Worker kennt den Klartext nicht.</small></span></label>{config.enabled&&<div className="device-sync-content"><div className="device-sync-code"><label><span>Persönlicher Synchronisationscode</span><input readOnly value={formatDeviceSyncCode(config.syncKey)} aria-label="Synchronisationscode"/></label><button type="button" onClick={()=>void copy()}><ClipboardCopy size={16}/>Kopieren</button></div><div className="device-sync-actions"><button type="button" disabled={busy} onClick={()=>void run(()=>syncDeviceStateNow(true))}>{busy?<RefreshCw className="spin" size={16}/>:<RefreshCw size={16}/>}Jetzt synchronisieren</button><small>{config.lastSyncAt?`Einstellungen zuletzt ${new Date(config.lastSyncAt).toLocaleString('de-DE')}`:'Noch kein erfolgreicher Einstellungsabgleich'}</small><small>{config.lastArchiveSyncAt?`Langzeitarchiv zuletzt ${new Date(config.lastArchiveSyncAt).toLocaleString('de-DE')} · ${config.archiveLocations||0} Standorte · ${(config.archiveCaptures||0)+(config.archiveReferences||0)+(config.archiveObservations||0)} Datensätze`:'Vollständiges Wetterzwilling-Langzeitarchiv noch nicht gesichert'}</small></div></div>}<div className="device-sync-join"><header><Link2 size={18}/><span><strong>Bestehenden Geräteverbund verwenden</strong><small>Code eines bereits synchronisierten MID-Geräts eingeben.</small></span></header><div><input value={joinCode} onChange={event=>setJoinCode(event.target.value)} placeholder="Synchronisationscode" autoCapitalize="off" autoCorrect="off"/><button type="button" disabled={busy||joinCode.replace(/[^A-Za-z0-9_-]/g,'').length<32} onClick={()=>void connect()}><Check size={16}/>Verbinden</button></div></div>{message&&<p className="device-sync-message" role="status">{message}</p>}</section>
}
