import {useEffect,useMemo} from 'react';
import {divIcon} from 'leaflet';
import {MapContainer,Marker,TileLayer,Tooltip,WMSTileLayer,useMap,useMapEvents} from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import HymecNgOverlay,{type HymecNgOverlayStatus} from './HymecNgOverlay';
import type {HymecNgMeta} from './HymecNgSource';
import {compositeWmsProxy,type CompositeProduct,type RainViewerResponse} from './CompositeData';

export type DwdCompositePrecipSource='hymecng'|'rainviewer'|'dwd-radar'|'none';

function locationIcon(){return divIcon({className:'mid-dwd-location-pin',iconSize:[26,34],iconAnchor:[13,32],html:'<svg viewBox="0 0 24 30" aria-hidden="true"><path d="M12 28C8.1 22.6 3.5 17.7 3.5 11.7A8.5 8.5 0 0 1 12 3.2a8.5 8.5 0 0 1 8.5 8.5c0 6-4.6 10.9-8.5 16.3Z"/><circle cx="12" cy="11.7" r="3.1"/></svg>'})}
function SyncView({latitude,longitude}:{latitude:number;longitude:number}){const map=useMap();useEffect(()=>{map.setView([latitude,longitude],map.getZoom(),{animate:false})},[map,latitude,longitude]);return null}
function PointPicker({onPoint}:{onPoint:(latitude:number,longitude:number)=>void}){useMapEvents({click:event=>onPoint(event.latlng.lat,event.latlng.lng)});return null}
function closestProductTime(product:CompositeProduct|null|undefined,target?:string){if(!product)return'';const targetMs=Date.parse(target||''),times=(product.times||[]).map(value=>typeof value==='number'?value:Date.parse(String(value))).filter(Number.isFinite) as number[];if(times.length&&Number.isFinite(targetMs)){let best=times[0],distance=Math.abs(best-targetMs);for(const value of times){const next=Math.abs(value-targetMs);if(next<distance){best=value;distance=next}}if(distance<=45*60000)return new Date(best).toISOString()}const latest=typeof product.latestTime==='number'?product.latestTime:Date.parse(String(product.latestTime||''));if(Number.isFinite(latest))return new Date(latest).toISOString();if(times.length)return new Date(times.at(-1)!).toISOString();return''}
function latestRainViewerFrame(rainViewer:RainViewerResponse|null|undefined){const frames=rainViewer?.radar?.past||[];return frames.length?frames[frames.length-1]:null}

export default function DwdPrecipitationMap({latitude,longitude,locationName,satelliteAt,satelliteProduct,hymecMeta,rainViewer,radarLayer,radarTime,markerVisible,onPoint,onHymecStatus,onSatelliteStatus,onPrecipitationStatus}:{latitude:number;longitude:number;locationName?:string;satelliteAt?:string;satelliteProduct?:CompositeProduct|null;hymecMeta:HymecNgMeta|null;rainViewer?:RainViewerResponse|null;radarLayer?:string;radarTime?:string;markerVisible:boolean;onPoint:(latitude:number,longitude:number)=>void;onHymecStatus?:(status:HymecNgOverlayStatus,message?:string)=>void;onSatelliteStatus?:(status:'idle'|'loading'|'ready'|'error',message?:string)=>void;onPrecipitationStatus?:(source:DwdCompositePrecipSource,status:'idle'|'loading'|'ready'|'error',message?:string)=>void}){
 const markerIcon=useMemo(()=>locationIcon(),[]),satelliteProxy=satelliteProduct?compositeWmsProxy(satelliteProduct.provider):'',dwdProxy=compositeWmsProxy('dwd'),satelliteTime=closestProductTime(satelliteProduct,satelliteAt),satelliteParams=useMemo(()=>({layers:satelliteProduct?.layer||'',styles:'',format:'image/png',transparent:true,version:satelliteProduct?.provider==='eumetsat'?'1.3.0':'1.1.1',...(satelliteTime&&!satelliteProduct?.latestOnly?{time:satelliteTime}:{}),tiled:true} as any),[satelliteProduct?.layer,satelliteProduct?.provider,satelliteProduct?.latestOnly,satelliteTime]),rainFrame=latestRainViewerFrame(rainViewer),rainUrl=rainFrame&&rainViewer?.host?`${rainViewer.host}${rainFrame.path}/512/{z}/{x}/{y}/2/1_1.png`:'',precipSource:DwdCompositePrecipSource=hymecMeta?.available&&hymecMeta.fileUrl?'hymecng':rainUrl?'rainviewer':radarLayer&&dwdProxy&&radarTime?'dwd-radar':'none',radarParams=useMemo(()=>({layers:radarLayer||'',styles:'',format:'image/png',transparent:true,version:'1.1.1',...(radarTime?{time:radarTime}:{}),tiled:true} as any),[radarLayer,radarTime]);
 useEffect(()=>{if(!satelliteProduct||!satelliteProxy){onSatelliteStatus?.('error','Kein aktuelles Satellitenprodukt verfügbar.');return}if(!satelliteTime){onSatelliteStatus?.('error','Satellitenprodukt ohne verifizierbaren Zeitstempel wird nicht angezeigt.');return}onSatelliteStatus?.('loading')},[satelliteProduct,satelliteProxy,satelliteAt,satelliteTime,onSatelliteStatus]);
 useEffect(()=>{if(precipSource==='hymecng'){onPrecipitationStatus?.('hymecng','loading','DWD HymecNG wird geladen.');return}if(precipSource==='rainviewer'){onPrecipitationStatus?.('rainviewer','loading','Radar-Fallback mit Regen-/Schnee-Differenzierung wird geladen.');return}if(precipSource==='dwd-radar'){onPrecipitationStatus?.('dwd-radar','loading','DWD Niederschlagsradar wird geladen.');return}onPrecipitationStatus?.('none','error','Keine aktuelle Niederschlagsdarstellung verfügbar.')},[precipSource,onPrecipitationStatus]);
 const canShowSatellite=Boolean(satelliteProduct&&satelliteProxy&&satelliteTime);
 return <MapContainer className="dwd-precip-type-radar__leaflet" center={[latitude,longitude]} zoom={8} minZoom={5} maxZoom={12} zoomControl={false} attributionControl={false} scrollWheelZoom={false} doubleClickZoom touchZoom dragging preferCanvas>
  <TileLayer url="https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png" opacity={canShowSatellite?.62:.95} maxZoom={19} attribution="&copy; OpenStreetMap-Mitwirkende &copy; CARTO"/>
  {canShowSatellite?<WMSTileLayer key={`sat:${satelliteProduct!.provider}:${satelliteProduct!.layer}:${satelliteTime||'latest'}`} url={satelliteProxy} opacity={.62} zIndex={300} params={satelliteParams} eventHandlers={{load:()=>onSatelliteStatus?.('ready',`${satelliteProduct!.label}${satelliteTime?` · ${satelliteTime.slice(11,16)} UTC`:''}`),tileerror:()=>onSatelliteStatus?.('error','Das aktuelle Satellitenbild konnte nicht geladen werden.')}} attribution={satelliteProduct!.provider==='dwd'?'Satellit &copy; DWD':'Satellit &copy; EUMETSAT'}/>:null}
  {precipSource==='hymecng'&&hymecMeta?<HymecNgOverlay key={hymecMeta.fileUrl} meta={hymecMeta} opacity={.9} onStatus={(status,message)=>{onHymecStatus?.(status,message);onPrecipitationStatus?.('hymecng',status,message)}}/>:null}
  {precipSource==='rainviewer'&&rainUrl?<TileLayer key={`rainviewer:${rainFrame!.time}`} url={rainUrl} opacity={.78} zIndex={430} maxNativeZoom={7} maxZoom={12} eventHandlers={{load:()=>onPrecipitationStatus?.('rainviewer','ready',`RainViewer Radar · Regen/Schnee · ${new Date(rainFrame!.time*1000).toISOString().slice(11,16)} UTC`),tileerror:()=>onPrecipitationStatus?.('rainviewer','error','Radar-Fallback konnte nicht geladen werden.')}} attribution="Radar &copy; RainViewer"/>:null}
  {precipSource==='dwd-radar'&&radarLayer&&dwdProxy?<WMSTileLayer key={`radar:${radarLayer}:${radarTime||'latest'}`} url={dwdProxy} opacity={.74} zIndex={430} params={radarParams} eventHandlers={{load:()=>onPrecipitationStatus?.('dwd-radar','ready',`DWD Niederschlagsradar${radarTime?` · ${radarTime.slice(11,16)} UTC`:''} · nur Intensität`),tileerror:()=>onPrecipitationStatus?.('dwd-radar','error','DWD Niederschlagsradar konnte nicht geladen werden.')}} attribution="Radar &copy; DWD"/>:null}
  <SyncView latitude={latitude} longitude={longitude}/><PointPicker onPoint={onPoint}/>{markerVisible?<Marker position={[latitude,longitude]} icon={markerIcon} zIndexOffset={900}><Tooltip permanent direction="top" offset={[0,-31]} opacity={.96}>{locationName||'gewählter Ort'}</Tooltip></Marker>:null}
 </MapContainer>;
}
