import {useCallback,useEffect,useMemo,useRef,useState,type CSSProperties,type MouseEvent} from 'react';
import {ExternalLink,Info,MapPin,RotateCcw,ZoomIn,ZoomOut} from 'lucide-react';
import {buildWorkerUrl,fetchWorkerJson,workerBaseCandidates} from './workerClient';
import type {Location} from './weather';
import {formatDisplayDateTime} from './timeDisplay';

const DWD_PRODUCT_PAGE='https://www.dwd.de/DE/leistungen/wolken_niederschlagsart/wolken_niederschlagsart.html';
const COVERAGE={west:5.45,east:15.55,south:47.0,north:55.2};
// Ausschließlich zur Zentrierung und Kennzeichnung innerhalb des unveränderten
// DWD-Originalbilds. Die an dauerhaft sichtbaren DWD-Stadtankern in Nord, Süd,
// Ost und West geprüfte bilineare Abbildung gleicht die leichte
// projektionsbedingte Meridiankonvergenz aus. Sie macht aus dem PNG ausdrücklich
// keinen Karten-/Rasterlayer.
const DWD_IMAGE_GEO_CENTER={longitude:10,latitude:51.5} as const;
const DWD_IMAGE_GEO_BILINEAR={
 x:{origin:.506145794481,lon:.0527570530389,lat:.0000737501280844,cross:-.0015334680047},
 y:{origin:.401459603686,lon:.0000554164716641,lat:-.0818027514158,cross:-.000302836311194}
} as const;
// Normierter Ausschnitt der im amtlichen PNG eingebetteten DWD-Legende. Das
// Inset verwendet dieselbe Bildantwort und zeichnet keine Farbtabelle nach.
const DWD_ORIGINAL_LEGEND_WINDOW={left:.018,top:.665,width:.184,height:.242} as const;
export const DWD_PRECIPITATION_TYPE_COVERAGE=COVERAGE;
export const DWD_PRECIPITATION_TYPE_LEGEND=[
 {label:'großer Hagel',color:'#b000d6'},{label:'kleiner Hagel',color:'#d000f5'},{label:'Graupel',color:'#ffd633'},{label:'gefrierender Regen',color:'#ff1c00'},{label:'gefr. Sprühregen',color:'#d80000'},{label:'Schnee',color:'#ff21d1'},{label:'Schneeregen',color:'#ff70df'},{label:'Regen',color:'#00c778'},{label:'Sprühregen',color:'#19dca4'},{label:'nicht klassifizierbar',color:'#7f7f7f'},{label:'kein Niederschlag',color:'#c9c9c9'}
] as const;

type RadarMeta={observedAt?:string;publishedAt?:string;radarAt?:string;satelliteAt?:string;componentTimeNote?:string};
type RadarPointInfo={error?:string;precipitationLabel:string;precipitationColor?:string;cloudLabel:string;confidence?:'high'|'medium'|'low';observedAt?:string;latitude?:number;longitude?:number;rgb?:[number,number,number];note?:string};
type PointInspection={loading:boolean;error?:string;info?:RadarPointInfo};
type ImagePoint={x:number;y:number};
type ImageSize={width:number;height:number};

function clamp(value:number,min:number,max:number){return Math.min(max,Math.max(min,value))}
function countryCode(location:Location){return String(location.country_code||location.country||'').trim().toUpperCase()}
export function dwdPrecipitationTypeCoverage(location:Location){const latitude=Number(location.latitude),longitude=Number(location.longitude),code=countryCode(location),within=Number.isFinite(latitude)&&Number.isFinite(longitude)&&latitude>=COVERAGE.south&&latitude<=COVERAGE.north&&longitude>=COVERAGE.west&&longitude<=COVERAGE.east;if(code&&code!=='DE'&&code!=='DEU'&&code!=='GERMANY'&&code!=='DEUTSCHLAND')return false;return within}
export function dwdPrecipitationTypeImagePosition(location:Pick<Location,'latitude'|'longitude'>):ImagePoint{const latitude=Number(location.latitude),longitude=Number(location.longitude),lon=longitude-DWD_IMAGE_GEO_CENTER.longitude,lat=latitude-DWD_IMAGE_GEO_CENTER.latitude,x=DWD_IMAGE_GEO_BILINEAR.x.origin+DWD_IMAGE_GEO_BILINEAR.x.lon*lon+DWD_IMAGE_GEO_BILINEAR.x.lat*lat+DWD_IMAGE_GEO_BILINEAR.x.cross*lon*lat,y=DWD_IMAGE_GEO_BILINEAR.y.origin+DWD_IMAGE_GEO_BILINEAR.y.lon*lon+DWD_IMAGE_GEO_BILINEAR.y.lat*lat+DWD_IMAGE_GEO_BILINEAR.y.cross*lon*lat;return{x:clamp(x,0,1),y:clamp(y,0,1)}}
function geoFromImagePoint(x:number,y:number){const gx=DWD_IMAGE_GEO_BILINEAR.x,gy=DWD_IMAGE_GEO_BILINEAR.y,linearDet=gx.lon*gy.lat-gx.lat*gy.lon;if(Math.abs(linearDet)<1e-12)return{longitude:NaN,latitude:NaN};const px=x-gx.origin,py=y-gy.origin;let lon=(px*gy.lat-gx.lat*py)/linearDet,lat=(gx.lon*py-px*gy.lon)/linearDet;for(let iteration=0;iteration<7;iteration+=1){const residualX=gx.origin+gx.lon*lon+gx.lat*lat+gx.cross*lon*lat-x,residualY=gy.origin+gy.lon*lon+gy.lat*lat+gy.cross*lon*lat-y,j11=gx.lon+gx.cross*lat,j12=gx.lat+gx.cross*lon,j21=gy.lon+gy.cross*lat,j22=gy.lat+gy.cross*lon,det=j11*j22-j12*j21;if(Math.abs(det)<1e-12)break;const lonStep=(residualX*j22-j12*residualY)/det,latStep=(j11*residualY-residualX*j21)/det;lon-=lonStep;lat-=latStep;if(Math.max(Math.abs(lonStep),Math.abs(latStep))<1e-9)break}return{longitude:lon+DWD_IMAGE_GEO_CENTER.longitude,latitude:lat+DWD_IMAGE_GEO_CENTER.latitude}}
function dwdLocationCropWidth(viewportWidth:number){if(viewportWidth>=1320)return .72;if(viewportWidth>=1080)return .67;if(viewportWidth>=860)return .61;if(viewportWidth>=660)return .55;if(viewportWidth>=540)return .49;if(viewportWidth>=420)return .44;return .40}
function formatDwdSourceTimestamp(value:string|undefined){return value?formatDisplayDateTime(value,undefined,{hour:'2-digit',minute:'2-digit',hourCycle:'h23'}):'–'}
function exactProductUrls(slot:number){return workerBaseCandidates('radar').map(base=>buildWorkerUrl(base,'dwd-precipitation-type-image',{slot}).toString())}
function originalLegendImageStyle(){const window=DWD_ORIGINAL_LEGEND_WINDOW;return{width:`${(100/window.width).toFixed(6)}%`,left:`${(-(window.left/window.width)*100).toFixed(6)}%`,top:`${(-(window.top/window.height)*100).toFixed(6)}%`} as CSSProperties}
function originalLegendFrameStyle(imageSize:ImageSize){const window=DWD_ORIGINAL_LEGEND_WINDOW,ratio=(window.width*Math.max(1,imageSize.width))/(window.height*Math.max(1,imageSize.height));return{aspectRatio:String(ratio)} as CSSProperties}

export function DwdPrecipitationTypeRadar({location,enabled=true}:{location:Location;enabled?:boolean}){
 const covered=dwdPrecipitationTypeCoverage(location),[refreshSlot,setRefreshSlot]=useState(()=>Math.floor(Date.now()/300000)),[imageUrl,setImageUrl]=useState(''),[imageSize,setImageSize]=useState<ImageSize>({width:1,height:1}),[meta,setMeta]=useState<RadarMeta|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[pointInfo,setPointInfo]=useState<PointInspection|null>(null),[zoom,setZoom]=useState(1),[viewportWidth,setViewportWidth]=useState(720),viewportRef=useRef<HTMLDivElement|null>(null),canvasRef=useRef<HTMLDivElement|null>(null),urls=useMemo(()=>exactProductUrls(refreshSlot),[refreshSlot]),locationPoint=useMemo(()=>dwdPrecipitationTypeImagePosition(location),[location.latitude,location.longitude]),cropWidth=dwdLocationCropWidth(viewportWidth),canvasStyle=useMemo(()=>({width:`${((zoom/cropWidth)*100).toFixed(6)}%`}) as CSSProperties,[cropWidth,zoom]),markerStyle=useMemo(()=>({left:`${(locationPoint.x*100).toFixed(5)}%`,top:`${(locationPoint.y*100).toFixed(5)}%`}) as CSSProperties,[locationPoint.x,locationPoint.y]);
 useEffect(()=>{const timer=window.setInterval(()=>setRefreshSlot(Math.floor(Date.now()/300000)),60000);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{setZoom(1);setPointInfo(null)},[location.latitude,location.longitude]);
 useEffect(()=>{const node=viewportRef.current;if(!node||typeof ResizeObserver==='undefined')return;let frame=0;const update=()=>{if(frame)return;frame=window.requestAnimationFrame(()=>{frame=0;const width=Math.max(280,Math.round(node.clientWidth||280));setViewportWidth(current=>current===width?current:width)})},observer=new ResizeObserver(update);update();observer.observe(node);return()=>{if(frame)window.cancelAnimationFrame(frame);observer.disconnect()}},[enabled,covered]);
 useEffect(()=>{
  if(!enabled||!covered){setImageUrl('');setMeta(null);setLoading(false);setError('');return}
  let cancelled=false,objectUrl='';setLoading(true);setError('');setPointInfo(null);
  const load=async()=>{let lastError='';for(const url of urls){try{const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`DWD-Bild HTTP ${response.status}`);const type=String(response.headers.get('content-type')||'');if(!type.startsWith('image/'))throw new Error('DWD-Antwort ist kein Bild.');const blob=await response.blob();if(cancelled)return;objectUrl=URL.createObjectURL(blob);setImageUrl(objectUrl);setMeta({observedAt:response.headers.get('x-mid-observed-at')||undefined,publishedAt:response.headers.get('last-modified')||undefined,radarAt:response.headers.get('x-mid-radar-at')||undefined,satelliteAt:response.headers.get('x-mid-satellite-at')||undefined,componentTimeNote:'Radar- und Satellitenzeit stammen aus demselben Datenabruf wie das dargestellte amtliche DWD-Originalbild.'});setLoading(false);return}catch(nextError){lastError=nextError instanceof Error?nextError.message:String(nextError)}}if(cancelled)return;setImageUrl('');setMeta(null);setLoading(false);setError(lastError||'DWD-Originalprodukt derzeit nicht verfügbar.')};
  void load();return()=>{cancelled=true;if(objectUrl)URL.revokeObjectURL(objectUrl)}
 },[enabled,covered,urls]);
 const centerImagePoint=useCallback((point:ImagePoint)=>{const viewport=viewportRef.current,canvas=canvasRef.current;if(!viewport||!canvas)return;const left=point.x*canvas.scrollWidth-viewport.clientWidth/2,top=point.y*canvas.scrollHeight-viewport.clientHeight/2;viewport.scrollLeft=clamp(left,0,Math.max(0,canvas.scrollWidth-viewport.clientWidth));viewport.scrollTop=clamp(top,0,Math.max(0,canvas.scrollHeight-viewport.clientHeight))},[]);
 const scheduleCenterImagePoint=useCallback((point:ImagePoint)=>{const frames:number[]=[];const timers:number[]=[];const run=()=>centerImagePoint(point);run();frames.push(window.requestAnimationFrame(()=>{run();frames.push(window.requestAnimationFrame(run))}));timers.push(window.setTimeout(run,120));timers.push(window.setTimeout(run,260));return()=>{frames.forEach(id=>window.cancelAnimationFrame(id));timers.forEach(id=>window.clearTimeout(id))}},[centerImagePoint]);
 useEffect(()=>{if(!imageUrl||loading)return;return scheduleCenterImagePoint(locationPoint)},[cropWidth,imageSize.height,imageSize.width,imageUrl,loading,locationPoint.x,locationPoint.y,scheduleCenterImagePoint,zoom]);
 if(!enabled||!covered)return null;
 const changeZoom=(next:number)=>{const clamped=Math.max(1,Math.min(5,Math.round(next)));if(clamped!==zoom)setZoom(clamped);else scheduleCenterImagePoint(locationPoint)};
 const resetZoom=()=>{setZoom(1);scheduleCenterImagePoint(locationPoint)};
 const inspectOriginalPoint=async(x:number,y:number,geoHint?:{latitude:number;longitude:number})=>{const geo=geoHint??geoFromImagePoint(x,y);setPointInfo({loading:true});try{const info=await fetchWorkerJson<RadarPointInfo>('dwd-precipitation-type-info',{x:x.toFixed(6),y:y.toFixed(6),lat:Number.isFinite(geo.latitude)?geo.latitude.toFixed(5):undefined,lon:Number.isFinite(geo.longitude)?geo.longitude.toFixed(5):undefined,expected:meta?.observedAt||''},{purpose:'radar',timeoutMs:10000,maxAgeMs:2*60000,staleIfErrorMs:5*60000,cacheKey:`dwd-precip-info:${meta?.observedAt||refreshSlot}:${x.toFixed(3)}:${y.toFixed(3)}`});setPointInfo({loading:false,info})}catch(nextError){setPointInfo({loading:false,error:nextError instanceof Error?nextError.message:'Punktanalyse nicht verfügbar.'})}};
 const inspectPoint=async(event:MouseEvent<HTMLImageElement>)=>{if(!imageUrl||loading)return;const rect=event.currentTarget.getBoundingClientRect(),x=Math.min(1,Math.max(0,(event.clientX-rect.left)/Math.max(1,rect.width))),y=Math.min(1,Math.max(0,(event.clientY-rect.top)/Math.max(1,rect.height)));await inspectOriginalPoint(x,y)};
 return <section className="dwd-precip-type-radar" aria-label="DWD Wolken und Niederschlagsart"><header><span><small>DWD · amtliches Kombinationsprodukt</small><strong>Wolken + Niederschlagsart</strong><em>Originalbild · zoombarer Ortsausschnitt · {location.name||'gewählter Ort'}</em></span><div className="dwd-precip-type-radar__actions"><details className="dwd-precip-type-radar__info"><summary aria-label="Legende der Niederschlagsarten anzeigen" title="Legende vergrößern"><Info size={16}/></summary><div className="dwd-precip-type-radar__legend" role="group" aria-label="DWD-Legende Niederschlagsarten"><strong>Niederschlagsart</strong>{DWD_PRECIPITATION_TYPE_LEGEND.map(item=><span key={item.label}><i style={{background:item.color}}/>{item.label}</span>)}</div></details><a href={DWD_PRODUCT_PAGE} target="_blank" rel="noreferrer" title="DWD-Originalprodukt öffnen"><ExternalLink size={16}/><span>DWD</span></a></div></header>
 <div className="dwd-precip-type-radar__timestamps"><span><b>Radar</b>{formatDwdSourceTimestamp(meta?.radarAt)}</span><span><b>Sat</b>{formatDwdSourceTimestamp(meta?.satelliteAt)}</span>{pointInfo?<span className="dwd-precip-type-radar__point-strip"><b>Bildpunkt</b>{pointInfo.loading?'wird ausgewertet …':pointInfo.error?pointInfo.error:pointInfo.info?`${pointInfo.info.precipitationLabel} · Wolken: ${pointInfo.info.cloudLabel}`:'–'}</span>:<span className="dwd-precip-type-radar__point-strip idle"><b>Bildpunkt</b>Antippen zur Auswertung · Bild oder Standortmarker</span>}<small title={meta?.componentTimeNote}>Zeitstände gehören zum angezeigten Originalprodukt</small></div>
 <div className="dwd-precip-type-radar__zoom-toolbar" aria-label="Bildzoom"><button type="button" onClick={()=>changeZoom(zoom-1)} disabled={zoom<=1} title="Verkleinern"><ZoomOut size={15}/></button><b>{Math.round(zoom*100)} %</b><button type="button" onClick={()=>changeZoom(zoom+1)} disabled={zoom>=5} title="Vergrößern"><ZoomIn size={15}/></button><button type="button" onClick={resetZoom} title="Ortsausschnitt zentrieren"><MapPin size={14}/><span>100 %</span></button></div>
 <div className="dwd-precip-type-radar__viewport-shell">
  {zoom>1?<button type="button" className="dwd-precip-type-radar__zoom-escape" onClick={resetZoom} aria-label="Zoom auf 100 Prozent zurücksetzen" title="Zum zentrierten Ortsausschnitt zurück"><RotateCcw size={14}/><span>100 %</span></button>:null}
  <div ref={viewportRef} className={`dwd-precip-type-radar__original-viewport${loading?' loading':''}${error?' failed':''}`} role="region" aria-label={`Standortzentrierter Ausschnitt des amtlichen DWD-Originalbilds um ${location.name||'den gewählten Ort'}`}>
   {loading?<span className="dwd-precip-type-radar__status">DWD-Originalprodukt wird geladen …</span>:null}
   {!loading&&error?<span className="dwd-precip-type-radar__status">{error}</span>:null}
   {!loading&&!error&&imageUrl?<div ref={canvasRef} className="dwd-precip-type-radar__original-canvas" style={canvasStyle}>
    <img className="dwd-precip-type-radar__original-image" src={imageUrl} alt="Amtliches DWD-Kombinationsbild aus Satellit und Radar-Niederschlagsart" onLoad={event=>setImageSize({width:event.currentTarget.naturalWidth||1,height:event.currentTarget.naturalHeight||1})} onClick={inspectPoint} draggable={false}/>
    <button type="button" className="dwd-precip-type-radar__location-marker" style={markerStyle} onClick={event=>{event.stopPropagation();void inspectOriginalPoint(locationPoint.x,locationPoint.y,{latitude:Number(location.latitude),longitude:Number(location.longitude)})}} aria-label={`Bildpunkt am Standort ${location.name||'gewählter Ort'} auswerten`} title={`${location.name||'Standort'} · Bildpunkt auswerten`}><MapPin size={18} aria-hidden="true"/></button>
   </div>:null}
  </div>
  {!loading&&!error&&imageUrl?<div className="dwd-precip-type-radar__source-legend" style={originalLegendFrameStyle(imageSize)} role="img" aria-label="Im DWD-Originalbild eingebettete Legende der Niederschlagsarten"><img src={imageUrl} alt="" aria-hidden="true" draggable={false} style={originalLegendImageStyle()}/></div>:null}
 </div><footer><span>Amtliches DWD-Originalbild ohne eigene Rekonstruktion. Der Ortsmarker zentriert nur den Bildausschnitt. Zoomen verändert ausschließlich die Ansicht; Bildpunkt-Auswertung bleibt an den Originalpixel gebunden.</span><small>Originallegende aus demselben DWD-Bild · Quelle: Deutscher Wetterdienst</small></footer></section>;
}
