import {useEffect,useMemo} from 'react';
import {HtmlMarker,MapCenter,MidMapLibre,RasterTileLayer,WmsTileLayer} from './MapLibreCore';
import HymecNgOverlay,{type HymecNgOverlayStatus} from './HymecNgOverlay';
import type {HymecNgMeta} from './HymecNgSource';
import {compositeWmsProxy,type CompositeProduct} from './CompositeData';
import {formatDisplayDateTime} from './timeDisplay';

export type DwdCompositePrecipSource='hymecng'|'none';
export type LayerStatus='idle'|'loading'|'ready'|'error';

const BKG_BASEMAP_COLOR_URL='https://sgx.geodatenzentrum.de/wmts_basemapde/tile/1.0.0/de_basemapde_web_raster_farbe/default/GLOBAL_WEBMERCATOR/{z}/{y}/{x}.png';
const BKG_RELIEF_WMS='https://sgx.geodatenzentrum.de/wms_basemapde_schummerung';

function escapeHtml(value:string){return value.replace(/[&<>\"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[char]||char))}
function locationHtml(){return '<svg viewBox="0 0 24 30" aria-hidden="true"><path d="M12 28C8.1 22.6 3.5 17.7 3.5 11.7A8.5 8.5 0 0 1 12 3.2a8.5 8.5 0 0 1 8.5 8.5c0 6-4.6 10.9-8.5 16.3Z"/><circle cx="12" cy="11.7" r="3.1"/></svg>'}
function closestProductTime(product:CompositeProduct|null|undefined,target?:string){if(!product)return'';const targetMs=Date.parse(target||''),times=(product.times||[]).map(value=>typeof value==='number'?value:Date.parse(String(value))).filter(Number.isFinite) as number[];if(times.length&&Number.isFinite(targetMs)){let best=times[0],distance=Math.abs(best-targetMs);for(const value of times){const next=Math.abs(value-targetMs);if(next<distance){best=value;distance=next}}if(distance<=45*60000)return new Date(best).toISOString()}const latest=typeof product.latestTime==='number'?product.latestTime:Date.parse(String(product.latestTime||''));if(Number.isFinite(latest))return new Date(latest).toISOString();if(times.length)return new Date(times.at(-1)!).toISOString();return''}

export default function DwdPrecipitationMap({latitude,longitude,locationName,satelliteAt,satelliteProduct,hymecMeta,radarLayer,radarTime,radarLatestOnly=false,markerVisible,onPoint,onHymecStatus,onSatelliteStatus,onRadarStatus,onPrecipitationStatus}:{latitude:number;longitude:number;locationName?:string;satelliteAt?:string;satelliteProduct?:CompositeProduct|null;hymecMeta:HymecNgMeta|null;radarLayer?:string;radarTime?:string;radarLatestOnly?:boolean;markerVisible:boolean;onPoint:(latitude:number,longitude:number)=>void;onHymecStatus?:(status:HymecNgOverlayStatus,message?:string)=>void;onSatelliteStatus?:(status:LayerStatus,message?:string)=>void;onRadarStatus?:(status:LayerStatus,message?:string)=>void;onPrecipitationStatus?:(source:DwdCompositePrecipSource,status:LayerStatus,message?:string)=>void}){
 const satelliteProxy=satelliteProduct?compositeWmsProxy(satelliteProduct.provider):'',dwdProxy=compositeWmsProxy('dwd'),satelliteTime=closestProductTime(satelliteProduct,satelliteAt),satelliteParams=useMemo(()=>({layers:satelliteProduct?.layer||'',styles:'',format:'image/png',transparent:true,version:satelliteProduct?.provider==='eumetsat'?'1.3.0':'1.1.1',...(satelliteTime&&!satelliteProduct?.latestOnly?{time:satelliteTime}:{}),tiled:true} as any),[satelliteProduct?.layer,satelliteProduct?.provider,satelliteProduct?.latestOnly,satelliteTime]),verifiedHymec=Boolean(hymecMeta?.available&&hymecMeta.fileUrl&&hymecMeta.classificationVerified===true),precipSource:DwdCompositePrecipSource=verifiedHymec?'hymecng':'none',radarParams=useMemo(()=>({layers:radarLayer||'dwd:Niederschlagsradar',styles:'',format:'image/png',transparent:true,version:'1.1.1',...(radarTime&&!radarLatestOnly?{time:radarTime}:{}),tiled:true} as any),[radarLayer,radarTime,radarLatestOnly]),canShowSatellite=Boolean(satelliteProduct&&satelliteProxy),canShowRadar=Boolean((radarLayer||'dwd:Niederschlagsradar')&&dwdProxy);
 useEffect(()=>{if(!canShowSatellite){onSatelliteStatus?.('error','Kein Satellitenlayer verfügbar.');return}onSatelliteStatus?.('loading',satelliteTime?'Satellitenbild wird geladen.':'Satellitenbild im neuesten WMS-Stand wird geladen; Zeit noch nicht verifiziert.')},[canShowSatellite,satelliteTime,onSatelliteStatus]);
 useEffect(()=>{if(!canShowRadar){onRadarStatus?.('error','DWD Niederschlagsradar nicht verfügbar.');return}onRadarStatus?.('loading',radarTime?'DWD-Radar wird geladen.':'DWD-Radar im neuesten WMS-Stand wird geladen; Zeit noch nicht verifiziert.')},[canShowRadar,radarTime,onRadarStatus]);
 useEffect(()=>{if(precipSource==='hymecng'){onPrecipitationStatus?.('hymecng','loading','Verifizierte DWD-HymecNG-Klassifikation wird geladen.');return}onPrecipitationStatus?.('none','error','Keine verifizierte aktuelle DWD-Niederschlagsart verfügbar; Ersatzklassen werden nicht eingeblendet.')},[precipSource,onPrecipitationStatus]);
 return <MidMapLibre className="dwd-precip-type-radar__maplibre" center={[latitude,longitude]} zoom={8} minZoom={5} maxZoom={12} attributionControl={false} scrollZoom={false} onClick={onPoint}>
  <MapCenter latitude={latitude} longitude={longitude}/><WmsTileLayer id="dwd-relief-base" baseUrl={BKG_RELIEF_WMS} opacity={1} params={{layers:'de_basemapde_web_raster_colordem',styles:'',format:'image/png',transparent:false,version:'1.1.1',tiled:true}} attribution="Relief © GeoBasis-DE / BKG"/>
  <RasterTileLayer id="dwd-basemap-color" url={BKG_BASEMAP_COLOR_URL} opacity={canShowSatellite?.68:.82} maxZoom={18} attribution="Kartendarstellung © GeoBasis-DE / BKG · CC BY 4.0"/>
  <WmsTileLayer id="dwd-relief-shade" baseUrl={BKG_RELIEF_WMS} opacity={.18} params={{layers:'de_basemapde_web_raster_combshade',styles:'',format:'image/png',transparent:true,version:'1.1.1',tiled:true}} attribution="Schummerung © GeoBasis-DE / BKG"/>
  {canShowSatellite?<WmsTileLayer id={`dwd-sat-${satelliteProduct!.provider}-${satelliteProduct!.layer}-${satelliteTime||'latest'}`} baseUrl={satelliteProxy} opacity={.52} params={satelliteParams} onReady={()=>onSatelliteStatus?.('ready',`${satelliteProduct!.label}${satelliteTime?` · ${formatDisplayDateTime(satelliteTime,undefined,{hour:'2-digit',minute:'2-digit',hourCycle:'h23'})}`:' · neuester WMS-Stand'}`)} onError={()=>onSatelliteStatus?.('error','Satellitenbild konnte nicht geladen werden.')} attribution={satelliteProduct!.provider==='dwd'?'Satellit © DWD':'Satellit © EUMETSAT'}/>:null}
  {canShowRadar?<WmsTileLayer id={`dwd-radar-${radarLayer||'Niederschlagsradar'}-${radarLatestOnly?'latest':radarTime||'latest'}`} baseUrl={dwdProxy} opacity={.78} params={radarParams} onReady={()=>onRadarStatus?.('ready',`DWD Niederschlagsradar · ${radarLatestOnly?'aktuellster WMS-Stand':radarTime?formatDisplayDateTime(radarTime,undefined,{hour:'2-digit',minute:'2-digit',hourCycle:'h23'}):'aktuellster WMS-Stand'} · Intensität`)} onError={()=>onRadarStatus?.('error','DWD Niederschlagsradar konnte nicht geladen werden.')} attribution="Radar © DWD"/>:null}
  {precipSource==='hymecng'&&hymecMeta?<HymecNgOverlay key={hymecMeta.fileUrl} meta={hymecMeta} opacity={.72} onStatus={(status,message)=>{onHymecStatus?.(status,message);onPrecipitationStatus?.('hymecng',status,message)}}/>:null}
  {markerVisible?<HtmlMarker latitude={latitude} longitude={longitude} html={locationHtml()} className="mid-dwd-location-pin" anchor="bottom" popupHtml={`<strong>${escapeHtml(locationName||'gewählter Ort')}</strong>`} zIndex={20}/>:null}
 </MidMapLibre>;
}
