import {useEffect,useMemo,useRef,useState,type CSSProperties,type MouseEvent} from 'react';
import {CloudRain,ExternalLink,Info,MapPin,RefreshCw} from 'lucide-react';
import {buildWorkerUrl,fetchWorkerJson,workerBaseCandidates} from './workerClient';
import type {Location} from './weather';

const DWD_PRODUCT_PAGE='https://www.dwd.de/DE/leistungen/wolken_niederschlagsart/wolken_niederschlagsart.html';
const DWD_DIRECT_IMAGE='https://www.dwd.de/DWD/wetter/sat/satwetter/njob_satrad.png';
const COVERAGE={west:5.45,east:15.55,south:47.0,north:55.2};
type DwdRasterCurve={value:number;intercept:number;slope:number;curvature:number;reference:number};
// Das Gradnetz im DWD-NinJo-Komposit ist projiziert: sowohl Breitenkreise als auch
// Meridianlinien weichen im Bild von einer einfachen kartesischen Geraden ab. Die
// Kalibrierung folgt deshalb direkt den sichtbaren Rasterlinien 6/8/10/12° E und
// 49/50/51/52° N. Die linearen Grundterme stammen aus den Rasterdurchgängen, die
// quadratischen Korrekturen aus der sichtbaren Linienkrümmung. Ortsnamen oder die
// weißen Stadt-Pluszeichen werden ausdrücklich NICHT als Georeferenzierungsanker benutzt.
// Längengradkurven: x = intercept + slope*y + curvature*(y-reference)^2.
const DWD_RASTER_LONGITUDE_CURVES:DwdRasterCurve[]=[
 {value:6,intercept:.31098212,slope:-.07044436,curvature:.1620,reference:.53},
 {value:8,intercept:.39703348,slope:-.03395512,curvature:.0607,reference:.53},
 {value:10,intercept:.48378011,slope:0,curvature:-.0406,reference:.53},
 {value:12,intercept:.57130179,slope:.03269307,curvature:-.1420,reference:.53}
];
// Breitengradkurven: y = intercept + slope*x + curvature*(x-reference)^2.
// Die Krümmung nimmt mit zunehmender Breite leicht zu, wie im projizierten DWD-Raster.
const DWD_RASTER_LATITUDE_CURVES:DwdRasterCurve[]=[
 {value:49,intercept:.64651429,slope:.01488340,curvature:-.1640,reference:.484},
 {value:50,intercept:.56749033,slope:.01558506,curvature:-.1680,reference:.484},
 {value:51,intercept:.47778116,slope:.03365028,curvature:-.1720,reference:.484},
 {value:52,intercept:.41065754,slope:.00464844,curvature:-.1770,reference:.484}
];
const PRECIPITATION_TYPE_LEGEND=[
 {label:'großer Hagel',color:'#b000d6'},{label:'kleiner Hagel',color:'#d000f5'},{label:'Graupel',color:'#ffd633'},{label:'gefrierender Regen',color:'#ff1c00'},{label:'gefr. Sprühregen',color:'#d80000'},{label:'Schnee',color:'#ff21d1'},{label:'Schneeregen',color:'#ff70df'},{label:'Regen',color:'#00c778'},{label:'Sprühregen',color:'#19dca4'},{label:'nicht klassifizierbar',color:'#7f7f7f'},{label:'kein Niederschlag',color:'#c9c9c9'}
] as const;

type RadarMeta={error?:string;observedAt?:string;publishedAt?:string;radarAt?:string;satelliteAt?:string;componentTimeNote?:string;width?:number;height?:number;checkedAt?:string};
type RadarPointInfo={error?:string;precipitationLabel:string;precipitationColor?:string;cloudLabel:string;confidence?:'high'|'medium'|'low';observedAt?:string;latitude?:number;longitude?:number;rgb?:[number,number,number];note?:string};
type RadarViewport={width:number;height:number};
type RadarCrop={left:number;top:number;width:number;height:number;markerLeft:number;markerTop:number};
type PointInspection={loading:boolean;error?:string;info?:RadarPointInfo};

function clamp(value:number,min:number,max:number){return Math.min(max,Math.max(min,value))}
function countryCode(location:Location){return String(location.country_code||location.country||'').trim().toUpperCase()}
export function dwdPrecipitationTypeCoverage(location:Location){const latitude=Number(location.latitude),longitude=Number(location.longitude),code=countryCode(location),within=Number.isFinite(latitude)&&Number.isFinite(longitude)&&latitude>=COVERAGE.south&&latitude<=COVERAGE.north&&longitude>=COVERAGE.west&&longitude<=COVERAGE.east;if(code&&code!=='DE'&&code!=='DEU'&&code!=='GERMANY'&&code!=='DEUTSCHLAND')return false;return within}
// Polarinterpolation des projizierten Gradnetzes. Sie ist ortsunabhängig und verwendet
// keine Stadtbeschriftungen oder Beispielorte als Anker.
function rasterBracket(lines:DwdRasterCurve[],value:number){if(value<=lines[0].value)return[lines[0],lines[1]] as const;const last=lines.length-1;if(value>=lines[last].value)return[lines[last-1],lines[last]] as const;for(let index=0;index<last;index++)if(value>=lines[index].value&&value<=lines[index+1].value)return[lines[index],lines[index+1]] as const;return[lines[0],lines[1]] as const}
function rasterCurveCoordinate(line:DwdRasterCurve,crossCoordinate:number){const delta=crossCoordinate-line.reference;return line.intercept+line.slope*crossCoordinate+line.curvature*delta*delta}
function rasterCoordinate(lines:DwdRasterCurve[],value:number,crossCoordinate:number){const[a,b]=rasterBracket(lines,value),first=rasterCurveCoordinate(a,crossCoordinate),second=rasterCurveCoordinate(b,crossCoordinate),span=b.value-a.value,t=span?((value-a.value)/span):0;return first+(second-first)*t}
function rasterValue(lines:DwdRasterCurve[],coordinate:number,crossCoordinate:number){let nearest:[DwdRasterCurve,DwdRasterCurve]|null=null,nearestDistance=Infinity;for(let index=0;index<lines.length-1;index++){const a=lines[index],b=lines[index+1],first=rasterCurveCoordinate(a,crossCoordinate),second=rasterCurveCoordinate(b,crossCoordinate),minimum=Math.min(first,second),maximum=Math.max(first,second);if(coordinate>=minimum&&coordinate<=maximum){const span=second-first,t=Math.abs(span)>1e-9?(coordinate-first)/span:0;return a.value+(b.value-a.value)*t}const distance=coordinate<minimum?minimum-coordinate:coordinate-maximum;if(distance<nearestDistance){nearestDistance=distance;nearest=[a,b]}}const[a,b]=nearest??[lines[0],lines[1]],first=rasterCurveCoordinate(a,crossCoordinate),second=rasterCurveCoordinate(b,crossCoordinate),span=second-first,t=Math.abs(span)>1e-9?(coordinate-first)/span:0;return a.value+(b.value-a.value)*t}
export function dwdPrecipitationTypeImagePosition(location:Pick<Location,'latitude'|'longitude'>){const latitude=Number(location.latitude),longitude=Number(location.longitude);let y=rasterCoordinate(DWD_RASTER_LATITUDE_CURVES,latitude,.484),x=rasterCoordinate(DWD_RASTER_LONGITUDE_CURVES,longitude,y);for(let iteration=0;iteration<7;iteration++){y=rasterCoordinate(DWD_RASTER_LATITUDE_CURVES,latitude,x);x=rasterCoordinate(DWD_RASTER_LONGITUDE_CURVES,longitude,y)}return{x:clamp(x,0,1)*100,y:clamp(y,0,1)*100}}
function geoFromImagePoint(x:number,y:number){let longitude=rasterValue(DWD_RASTER_LONGITUDE_CURVES,x,y),latitude=rasterValue(DWD_RASTER_LATITUDE_CURVES,y,x);for(let iteration=0;iteration<4;iteration++){longitude=rasterValue(DWD_RASTER_LONGITUDE_CURVES,x,y);latitude=rasterValue(DWD_RASTER_LATITUDE_CURVES,y,x)}return{longitude,latitude}}
function candidateImageUrls(slot:number){const workers=workerBaseCandidates('radar').map(base=>buildWorkerUrl(base,'dwd-precipitation-type-image',{slot}).toString());return[...new Set([...workers,`${DWD_DIRECT_IMAGE}?slot=${slot}`])]}
function formatDwdSourceTimestamp(value:string|undefined){if(!value)return'–';const stamp=Date.parse(value);if(!Number.isFinite(stamp))return value;const date=new Date(stamp),hour=String(date.getUTCHours()).padStart(2,'0'),minute=String(date.getUTCMinutes()).padStart(2,'0');return`${hour}:${minute} UTC`}
function radarCropWindow(location:Pick<Location,'latitude'|'longitude'>,viewport:RadarViewport):RadarCrop{const marker=dwdPrecipitationTypeImagePosition(location),centerX=marker.x/100,centerY=marker.y/100,aspect=Math.max(.9,Math.min(2.5,viewport.width/Math.max(1,viewport.height||1)));let cropWidth=viewport.width>=1320?.72:viewport.width>=1080?.67:viewport.width>=860?.61:viewport.width>=660?.55:viewport.width>=540?.49:viewport.width>=420?.44:.40;cropWidth=clamp(cropWidth,.36,.76);let cropHeight=cropWidth/aspect;cropHeight=clamp(cropHeight,.23,.66);if(cropHeight>.64){cropHeight=.64;cropWidth=clamp(cropHeight*aspect,.36,.78)}const left=clamp(centerX-cropWidth/2,0,1-cropWidth),top=clamp(centerY-cropHeight/2,0,1-cropHeight),markerLeft=(centerX-left)/cropWidth*100,markerTop=(centerY-top)/cropHeight*100;return{left,top,width:cropWidth,height:cropHeight,markerLeft,markerTop}}

export function DwdPrecipitationTypeRadar({location,enabled=true}:{location:Location;enabled?:boolean}){
 const covered=dwdPrecipitationTypeCoverage(location),viewportRef=useRef<HTMLDivElement|null>(null),[refreshSlot,setRefreshSlot]=useState(()=>Math.floor(Date.now()/300000)),[imageUrl,setImageUrl]=useState(''),[loading,setLoading]=useState(false),[failed,setFailed]=useState(false),[meta,setMeta]=useState<RadarMeta|null>(null),[markerVisible,setMarkerVisible]=useState(true),[viewportSize,setViewportSize]=useState<RadarViewport>({width:960,height:520}),[pointInfo,setPointInfo]=useState<PointInspection|null>(null),urls=useMemo(()=>candidateImageUrls(refreshSlot),[refreshSlot]),crop=useMemo(()=>radarCropWindow(location,viewportSize),[location.latitude,location.longitude,viewportSize.width,viewportSize.height]);
 useEffect(()=>{const timer=window.setInterval(()=>setRefreshSlot(Math.floor(Date.now()/300000)),60000);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{const node=viewportRef.current;if(!node||typeof ResizeObserver==='undefined')return;let frame=0;const update=()=>{if(frame)return;frame=window.requestAnimationFrame(()=>{frame=0;const next={width:Math.max(280,Math.round(node.clientWidth||280)),height:Math.max(180,Math.round(node.clientHeight||180))};setViewportSize(current=>current.width===next.width&&current.height===next.height?current:next)})},observer=new ResizeObserver(update);update();observer.observe(node);return()=>{if(frame)window.cancelAnimationFrame(frame);observer.disconnect()}},[enabled,covered]);
 useEffect(()=>{if(!enabled||!covered){setImageUrl('');setFailed(false);setLoading(false);setMeta(null);return}let cancelled=false,index=0,probe:HTMLImageElement|undefined;setLoading(true);setFailed(false);setPointInfo(null);const next=()=>{if(cancelled)return;const url=urls[index++];if(!url){setLoading(false);setFailed(true);return}probe=new Image();probe.referrerPolicy='no-referrer';probe.onload=()=>{if(cancelled)return;setImageUrl(url);setLoading(false);setFailed(false)};probe.onerror=next;probe.src=url};next();void fetchWorkerJson<RadarMeta>('dwd-precipitation-type-meta',{}, {purpose:'radar',timeoutMs:16000,maxAgeMs:4*60000,staleIfErrorMs:20*60000,cacheKey:`dwd-precip-type-meta:${refreshSlot}`}).then(value=>{if(!cancelled)setMeta(value)}).catch(()=>{if(!cancelled)setMeta(null)});return()=>{cancelled=true;if(probe){probe.onload=null;probe.onerror=null}}},[enabled,covered,urls,refreshSlot]);
 if(!enabled||!covered)return null;
 const imageStyle={width:`${(100/crop.width).toFixed(6)}%`,height:`${(100/crop.height).toFixed(6)}%`,left:`${(-(crop.left/crop.width)*100).toFixed(6)}%`,top:`${(-(crop.top/crop.height)*100).toFixed(6)}%`} as CSSProperties;
 const markerStyle={left:`${crop.markerLeft.toFixed(4)}%`,top:`${crop.markerTop.toFixed(4)}%`} as CSSProperties;
 const inspectPoint=async(event:MouseEvent<HTMLDivElement>)=>{if(!viewportRef.current||loading||failed)return;const viewport=viewportRef.current.getBoundingClientRect(),relativeX=clamp((event.clientX-viewport.left)/Math.max(1,viewport.width),0,1),relativeY=clamp((event.clientY-viewport.top)/Math.max(1,viewport.height),0,1),fullX=clamp(crop.left+relativeX*crop.width,0,1),fullY=clamp(crop.top+relativeY*crop.height,0,1),geo=geoFromImagePoint(fullX,fullY);setPointInfo({loading:true});try{const info=await fetchWorkerJson<RadarPointInfo>('dwd-precipitation-type-info',{x:fullX.toFixed(6),y:fullY.toFixed(6),lat:geo.latitude.toFixed(5),lon:geo.longitude.toFixed(5)},{purpose:'radar',timeoutMs:10000,maxAgeMs:2*60000,staleIfErrorMs:10*60000,cacheKey:`dwd-precip-info:${refreshSlot}:${fullX.toFixed(3)}:${fullY.toFixed(3)}`});setPointInfo({loading:false,info})}catch(error){setPointInfo({loading:false,error:error instanceof Error?error.message:'Punktanalyse nicht verfügbar.'})}};
 return <section className="dwd-precip-type-radar" aria-label="DWD Wolken und Niederschlagsart"><header><span><small>DWD · Satellit + Radar</small><strong>Wolken + Niederschlagsart</strong><em>Ausschnitt um {location.name||'den gewählten Ort'}</em></span><div className="dwd-precip-type-radar__actions"><button type="button" className={`dwd-precip-type-radar__marker-toggle${markerVisible?' active':''}`} onClick={()=>setMarkerVisible(value=>!value)} title={markerVisible?'Standortmarker ausblenden':'Standortmarker einblenden'} aria-pressed={markerVisible}><MapPin size={16}/></button><details className="dwd-precip-type-radar__info"><summary aria-label="Legende der Niederschlagsarten anzeigen" title="Legende"><Info size={16}/></summary><div className="dwd-precip-type-radar__legend" role="group" aria-label="DWD-Legende Niederschlagsarten"><strong>Niederschlagsart</strong>{PRECIPITATION_TYPE_LEGEND.map(item=><span key={item.label}><i style={{background:item.color}}/>{item.label}</span>)}</div></details><a href={DWD_PRODUCT_PAGE} target="_blank" rel="noreferrer" title="DWD-Originalprodukt öffnen"><ExternalLink size={16}/><span>DWD</span></a></div></header>
 <div className="dwd-precip-type-radar__timestamps"><span><b>Radar</b>{formatDwdSourceTimestamp(meta?.radarAt)}</span><span><b>Sat</b>{formatDwdSourceTimestamp(meta?.satelliteAt)}</span>{pointInfo?<span className="dwd-precip-type-radar__point-strip"><b>Bildpunkt</b>{pointInfo.loading?'wird ausgewertet …':pointInfo.error?pointInfo.error:pointInfo.info?`${pointInfo.info.precipitationLabel} · Wolken: ${pointInfo.info.cloudLabel}`:'–'}</span>:<span className="dwd-precip-type-radar__point-strip idle"><b>Bildpunkt</b>Antippen zur Auswertung</span>}{meta?.componentTimeNote?<small title={meta.componentTimeNote}>Zeitstand · DWD-Quelldaten</small>:null}</div>
 <div ref={viewportRef} className={`dwd-precip-type-radar__viewport${loading?' loading':''}${failed?' failed':''}`} role="img" aria-label={`Gezoomter Ausschnitt des DWD-Produkts Wolken und Niederschlagsart um ${location.name||'den gewählten Ort'}`} onClick={inspectPoint}>
  {!failed&&imageUrl&&<img className="dwd-precip-type-radar__image" src={imageUrl} alt="" aria-hidden="true" draggable={false} style={imageStyle}/>}
  {loading&&<span className="dwd-precip-type-radar__status"><RefreshCw className="spin" size={18}/>DWD-Bild wird geladen …</span>}
  {failed&&<span className="dwd-precip-type-radar__status"><CloudRain size={18}/>DWD-Bild vorübergehend nicht verfügbar.</span>}
  {!loading&&!failed&&markerVisible?<button type="button" className="dwd-precip-type-radar__marker" style={markerStyle} onClick={event=>{event.stopPropagation();setMarkerVisible(false)}} title="Standortmarker ausblenden" aria-label="Standortmarker ausblenden"><MapPin size={22}/><i/></button>:null}
 </div><footer><span>Antippen wertet den gewählten Bildpunkt aus und zeigt Niederschlagsart sowie Wolkensignal direkt oberhalb an.</span><small>Quelle: Deutscher Wetterdienst · Deutschland-Abdeckung</small></footer></section>;
}
