export type Severity='watch'|'caution';
export type CrossLevel={pressure:number;height:number|null;temperature:number|null;humidity:number|null;cloud:number|null;windSpeed:number|null;windDirection:number|null};
export type CrossCorridorSample={offsetKm:number;latitude:number;longitude:number;elevation:number;validTime:string;precipitation:number|null;precipitationProbability?:number|null;visibility?:number|null;weatherCode?:number|null;cape?:number|null;freezingLevel?:number|null;gust?:number|null;levels:CrossLevel[]};
export type CrossPoint={fraction:number;distanceKm:number;latitude:number;longitude:number;elevation:number;validTime:string;precipitation:number|null;precipitationProbability?:number|null;visibility?:number|null;weatherCode?:number|null;cape?:number|null;freezingLevel?:number|null;gust?:number|null;levels:CrossLevel[];corridorSamples?:CrossCorridorSample[]};
export type CrossWaypoint={id:string;name:string;latitude:number;longitude:number;elevation:number;fraction:number;distanceKm:number};
export type OfficialSignal={kind:string;label:string;level:'none'|'watch'|'caution';detail:string;source?:string;issuer?:string;validFrom?:string;validTo?:string;distanceKm?:number;value?:number;unit?:string};
export type OfficialCheckpoint={id:string;label:string;fraction:number;distanceKm:number;validTime:string;signals:OfficialSignal[];sources?:{id:string;label:string;status:string;detail?:string}[]};
export type RouteRegion={fraction:number;distanceKm:number;latitude:number;longitude:number;label:string;admin1?:string;country?:string};
export type CrossSectionData={route:string;waypoints:CrossWaypoint[];points:CrossPoint[];totalDistanceKm:number;startTime:string;endTime:string;flightLevel:number;corridorKm?:number;corridorHalfWidthKm?:number;regions?:RouteRegion[];model:string;modelLabel:string;generatedAt:string;source:string;weatherSampleCount?:number;officialBriefing?:OfficialCheckpoint[];version?:string;error?:string};
export type PointHazard={kind:'icing'|'turbulence'|'convection'|'wind'|'precipitation'|'visibility'|'ceiling';label:string;severity:Severity;detail:string};
export type HazardRun={kind:PointHazard['kind'];label:string;severity:Severity;startIndex:number;endIndex:number;detail:string};
export type VerticalHazardKind='cloud'|'icing'|'turbulence'|'convection'|'wind';
export type VerticalHazardRun={kind:VerticalHazardKind;label:string;severity:Severity;startIndex:number;endIndex:number;baseFl:number;topFl:number;detail:string};
export type HazardTransitionWindow={entryFrom:string;entryTo:string;exitFrom:string;exitTo:string;fromRouteStart:boolean;toRouteEnd:boolean};

export function finite(value:unknown):number|null{const parsed=Number(value);return value===null||value===undefined||value===''||!Number.isFinite(parsed)?null:parsed}
export function hft(metres:number|null){return metres===null?null:metres*3.28084/100}
// ISA pressure altitude: FL is not a geometric height. Applicable through FL550.
export function flightPressureHpa(flightLevel:number){const metres=flightLevel*100*.3048;return metres<=11000?1013.25*Math.pow(1-.0065*metres/288.15,5.2558797):226.3206*Math.exp(-9.80665*(metres-11000)/(287.05287*216.65))}
export function flightTargetHeightHft(point:Pick<CrossPoint,'levels'|'elevation'>,flightLevel:number):number|null{
 const terrain=hft(finite(point.elevation));if(terrain===null||!Number.isFinite(flightLevel))return null;
 if(flightLevel<50)return terrain+Math.max(0,flightLevel);
 const pressure=flightPressureHpa(flightLevel),rows=point.levels.filter(row=>finite(row.pressure)!==null&&row.pressure>0&&finite(row.height)!==null).sort((a,b)=>b.pressure-a.pressure);
 for(let i=0;i<rows.length;i++){const a=rows[i],b=rows[i+1];let height:number|null=null;if(Math.abs(a.pressure-pressure)<.001)height=hft(a.height);else if(b&&a.pressure>=pressure&&b.pressure<=pressure&&a.pressure>b.pressure){const fraction=Math.log(a.pressure/pressure)/Math.log(a.pressure/b.pressure);height=hft(Number(a.height)+(Number(b.height)-Number(a.height))*fraction)}if(height!==null)return height>=terrain?height:null}
 return null;
}
export function flightProfileValue(point:Pick<CrossPoint,'levels'|'elevation'>,flightLevel:number,key:'temperature'|'humidity'|'cloud'|'windSpeed'|'windDirection'){
 const target=flightTargetHeightHft(point,flightLevel);if(target===null)return null;return interpolateLevel(point.levels.filter(level=>finite(level.height)!==null&&Number(level.height)>=point.elevation),target,key);
}
export function formatMslHeight(value:number){return `${Math.round(value*100/100)*100} ft MSL`}
export function normalizeFlightLevel(value:number){const safe=Math.max(0,Math.min(550,Number.isFinite(value)?value:0));return safe<50?Math.round(safe):Math.round(safe/10)*10}
export function flightLevelFromAltitudeInput(mode:'fl'|'agl',value:number){if(!Number.isFinite(value))return null;if(mode==='agl')return normalizeFlightLevel(Math.max(0,Math.min(4900,value))/100);return normalizeFlightLevel(Math.max(50,Math.min(550,value)))}
export function altitudeInputFromFlightLevel(mode:'fl'|'agl',flightLevel:number){const normalized=normalizeFlightLevel(flightLevel);return mode==='agl'?String(Math.min(49,normalized)*100):String(Math.max(50,normalized))}
export function formatSelectedAltitudeLabel(flightLevel:number){const normalized=normalizeFlightLevel(flightLevel);return normalized<50?`${normalized<=0?'SFC':`${normalized*100} ft AGL`}`:`FL${String(normalized).padStart(3,'0')}`}
function formatAltitudeBand(baseFl:number,topFl:number){return `${formatMslHeight(baseFl)}–${formatMslHeight(topFl)}`}
function mixDirection(a:number,b:number,f:number){const delta=((b-a+540)%360)-180;return(a+delta*f+360)%360}
function levelRows(levels:CrossLevel[],key:'temperature'|'humidity'|'cloud'|'windSpeed'|'windDirection'){return levels.map(level=>({height:hft(finite(level.height)),value:finite(level[key])})).filter((row):row is {height:number;value:number}=>row.height!==null&&row.value!==null).sort((a,b)=>a.height-b.height)}
export function interpolateLevel(levels:CrossLevel[],targetHft:number,key:'temperature'|'humidity'|'cloud'|'windSpeed'|'windDirection'){
 const rows=levelRows(levels,key);if(!rows.length||!Number.isFinite(targetHft)||targetHft<rows[0].height||targetHft>rows.at(-1)!.height)return null;if(targetHft===rows[0].height)return rows[0].value;if(targetHft===rows.at(-1)!.height)return rows.at(-1)!.value;
 for(let index=1;index<rows.length;index++){const a=rows[index-1],b=rows[index];if(targetHft<=b.height){const f=(targetHft-a.height)/Math.max(1e-9,b.height-a.height);return key==='windDirection'?mixDirection(a.value,b.value,f):a.value+(b.value-a.value)*f}}
 return null;
}
function windVector(speed:number,directionFrom:number){const towards=(directionFrom+180)%360,rad=towards*Math.PI/180;return{east:Math.sin(rad)*speed,north:Math.cos(rad)*speed}}
function vectorShear(low:{speed:number;direction:number;height:number},high:{speed:number;direction:number;height:number}){const a=windVector(low.speed,low.direction),b=windVector(high.speed,high.direction),thousandFeet=Math.max(.5,(high.height-low.height)/10);return Math.hypot(b.east-a.east,b.north-a.north)/thousandFeet}
function windShearAt(levels:CrossLevel[],flightLevel:number){const lowSpeed=interpolateLevel(levels,Math.max(0,flightLevel-20),'windSpeed'),highSpeed=interpolateLevel(levels,flightLevel+20,'windSpeed'),lowDirection=interpolateLevel(levels,Math.max(0,flightLevel-20),'windDirection'),highDirection=interpolateLevel(levels,flightLevel+20,'windDirection');if([lowSpeed,highSpeed,lowDirection,highDirection].some(value=>value===null))return null;return vectorShear({speed:lowSpeed!,direction:lowDirection!,height:Math.max(0,flightLevel-20)},{speed:highSpeed!,direction:highDirection!,height:flightLevel+20})}
function estimatedCloudBaseFtAgl(point:CrossPoint){const rows=point.levels.map(level=>({height:hft(finite(level.height)),cloud:finite(level.cloud),humidity:finite(level.humidity)})).filter((row):row is {height:number;cloud:number|null;humidity:number|null}=>row.height!==null&&finite(point.elevation)!==null&&row.height>=point.elevation*3.28084/100).sort((a,b)=>a.height-b.height),base=rows.find(row=>(row.cloud??0)>=55||(row.humidity??0)>=92);if(!base)return null;return Math.max(0,base.height*100-point.elevation*3.28084)}
function mergeHazardsByKind(list:PointHazard[]){const byKind=new Map<PointHazard['kind'],PointHazard>();for(const hazard of list){const current=byKind.get(hazard.kind);if(!current||severityRank(hazard.severity)>severityRank(current.severity))byKind.set(hazard.kind,hazard)}return[...byKind.values()]}

function pointHazardsSingle(point:CrossPoint|CrossCorridorSample,index:number,flightLevel:number,terminal:boolean):PointHazard[]{
 const normalizedFlightLevel=normalizeFlightLevel(flightLevel),altitudeLabel=formatSelectedAltitudeLabel(normalizedFlightLevel),hazards:PointHazard[]=[],temperature=flightProfileValue(point,normalizedFlightLevel,'temperature'),humidity=flightProfileValue(point,normalizedFlightLevel,'humidity'),cloud=flightProfileValue(point,normalizedFlightLevel,'cloud'),windSpeed=flightProfileValue(point,normalizedFlightLevel,'windSpeed'),shear=windShearAt(point.levels,flightTargetHeightHft(point,normalizedFlightLevel)??NaN),precipitation=finite(point.precipitation)??0,cape=finite(point.cape)??0,weatherCode=finite(point.weatherCode)??0,visibility=finite(point.visibility),cloudBase=estimatedCloudBaseFtAgl(point as CrossPoint),inCloud=(cloud??0)>=55||(humidity??0)>=90;
 if(inCloud&&temperature!==null&&temperature<=2&&temperature>=-25){const severe=(cloud??0)>=80&&(humidity??0)>=93&&temperature>=-16&&temperature<=1&&(precipitation>=.3||(cloud??0)>=92);hazards.push({kind:'icing',label:'Vereisung',severity:severe?'caution':'watch',detail:`${altitudeLabel}: ${Math.round(temperature)} °C · Wolken ${Math.round(cloud??0)} % · RH ${Math.round(humidity??0)} %${precipitation>0?` · ${precipitation.toFixed(1)} mm/h Niederschlag`:''}`})}
 if(shear!==null&&shear>=4)hazards.push({kind:'turbulence',label:'Turbulenz / vertikale Windscherung',severity:shear>=7?'caution':'watch',detail:`Modellierte Vektorscherung um ${altitudeLabel}: ${shear.toFixed(1)} kt je 1000 ft`});
 const thunder=[95,96,99].includes(Math.round(weatherCode));if(thunder||cape>=450&&(precipitation>=.25||(cloud??0)>=70))hazards.push({kind:'convection',label:'Konvektion / Gewitter',severity:thunder||cape>=900?'caution':'watch',detail:`${thunder?'Gewittersignal im Wettercode':`CAPE ${Math.round(cape)} J/kg`}${precipitation>0?` · Niederschlag ${precipitation.toFixed(1)} mm/h`:''}`});
 if(windSpeed!==null&&windSpeed>=45)hazards.push({kind:'wind',label:'Starker Höhenwind',severity:windSpeed>=65?'caution':'watch',detail:`Wind am gewählten Niveau etwa ${Math.round(windSpeed)} kt`});
 if(precipitation>=.6&&!thunder)hazards.push({kind:'precipitation',label:'Markanter Niederschlag',severity:precipitation>=2?'caution':'watch',detail:`Modellierte Rate etwa ${precipitation.toFixed(1)} mm/h`});
 if(terminal&&visibility!==null&&visibility<10000)hazards.push({kind:'visibility',label:index===0?'Startsicht':'Landesicht',severity:visibility<5000?'caution':'watch',detail:`Bodensicht ${visibility<1000?`${Math.round(visibility/100)*100} m`:`${(visibility/1000).toFixed(1)} km`}`});
 if(terminal&&cloudBase!==null&&cloudBase<2500)hazards.push({kind:'ceiling',label:index===0?'Wolkenuntergrenze Start':'Wolkenuntergrenze Landung',severity:cloudBase<1000?'caution':'watch',detail:`Diagnostische Untergrenze etwa ${cloudBase<100?'<100':Math.round(cloudBase/100)*100} ft AGL`});
 return hazards;
}
function terminalBandHazards(point:CrossPoint,index:number,flightLevel:number):PointHazard[]{const terminalLabel=index===0?'Start':'Landung',upperBound=flightTargetHeightHft(point,flightLevel)??NaN,rows=profileRows(point).filter(row=>row.height>=Number(hft(point.elevation))&&row.height<=upperBound),hazards:PointHazard[]=[];if(!rows.length)return hazards;const bandLabel=formatAltitudeBand(Number(hft(point.elevation)),upperBound);const icingRows=rows.filter(row=>((row.cloud??0)>=55||(row.humidity??0)>=90)&&row.temperature!==null&&row.temperature<=2&&row.temperature>=-25);if(icingRows.length){const cloudMax=Math.max(...icingRows.map(row=>row.cloud??0)),tempMin=Math.min(...icingRows.map(row=>Number(row.temperature))),tempMax=Math.max(...icingRows.map(row=>Number(row.temperature)));hazards.push({kind:'icing',label:`Vereisung ${terminalLabel}`,severity:cloudMax>=82&&icingRows.some(row=>Number(row.temperature)>=-16)?'caution':'watch',detail:`Zwischen ${bandLabel}: ${Math.round(tempMin)} bis ${Math.round(tempMax)} °C · max. Wolken ${Math.round(cloudMax)} %`})}const windRows=rows.filter(row=>(row.windSpeed??0)>=45);if(windRows.length){const peak=Math.max(...windRows.map(row=>Number(row.windSpeed)));hazards.push({kind:'wind',label:`Windprofil ${terminalLabel}`,severity:peak>=65?'caution':'watch',detail:`Zwischen ${bandLabel}: max. ${Math.round(peak)} kt`})}const shearRows:{height:number;shear:number}[]=[];for(let rowIndex=1;rowIndex<rows.length;rowIndex++){const a=rows[rowIndex-1],b=rows[rowIndex];if([a.windSpeed,a.windDirection,b.windSpeed,b.windDirection].some(value=>value===null)||b.height-a.height<2)continue;const shear=vectorShear({speed:a.windSpeed!,direction:a.windDirection!,height:a.height},{speed:b.windSpeed!,direction:b.windDirection!,height:b.height});if(shear>=4)shearRows.push({height:(a.height+b.height)/2,shear})}if(shearRows.length){const peak=Math.max(...shearRows.map(row=>row.shear));hazards.push({kind:'turbulence',label:`Turbulenz / Windscherung ${terminalLabel}`,severity:peak>=7?'caution':'watch',detail:`Zwischen ${bandLabel}: max. ${peak.toFixed(1)} kt je 1000 ft`})}return hazards}
function severityRank(value:Severity){return value==='caution'?2:1}
function pointHazards(point:CrossPoint,index:number,total:number,flightLevel:number,corridorHalfWidthKm=0){const terminal=index===0||index===total-1,primary=terminal?mergeHazardsByKind([...pointHazardsSingle(point,index,flightLevel,terminal),...terminalBandHazards(point,index,flightLevel)]):pointHazardsSingle(point,index,flightLevel,false),sets=[primary,...(point.corridorSamples??[]).map(sample=>pointHazardsSingle(sample,index,flightLevel,false))],byKind=new Map<PointHazard['kind'],PointHazard>();for(const hazards of sets)for(const hazard of hazards){const current=byKind.get(hazard.kind);if(!current||severityRank(hazard.severity)>severityRank(current.severity))byKind.set(hazard.kind,hazard)}return[...byKind.values()].map(hazard=>terminal||corridorHalfWidthKm<=0?hazard:{...hazard,detail:`${hazard.detail} · innerhalb ±${Math.round(corridorHalfWidthKm)} km Korridor`})}
export function hazardRuns(data:CrossSectionData){const perPoint=data.points.map((point,index)=>pointHazards(point,index,data.points.length,data.flightLevel,data.corridorHalfWidthKm??0)),kinds=['icing','turbulence','convection','wind','precipitation','visibility','ceiling'] as const,runs:HazardRun[]=[];for(const kind of kinds){let active:HazardRun|null=null;for(let index=0;index<perPoint.length;index++){const hazard=perPoint[index].find(item=>item.kind===kind);if(hazard){if(!active)active={kind,label:hazard.label,severity:hazard.severity,startIndex:index,endIndex:index,detail:hazard.detail};else{active.endIndex=index;if(severityRank(hazard.severity)>severityRank(active.severity)){active.severity=hazard.severity;active.detail=hazard.detail}}}else if(active){runs.push(active);active=null}}if(active)runs.push(active)}return runs.sort((a,b)=>severityRank(b.severity)-severityRank(a.severity)||a.startIndex-b.startIndex)}

export function nearestWaypoint(data:CrossSectionData,fraction:number){return data.waypoints.reduce((best,waypoint)=>Math.abs(waypoint.fraction-fraction)<Math.abs(best.fraction-fraction)?waypoint:best,data.waypoints[0])}
export function nearestRegion(data:CrossSectionData,fraction:number){const regions=data.regions??[];return regions.length?regions.reduce((best,region)=>Math.abs(region.fraction-fraction)<Math.abs(best.fraction-fraction)?region:best,regions[0]):null}
export function regionalPositionLabel(data:CrossSectionData,point:CrossPoint){const region=nearestRegion(data,point.fraction);if(region?.label)return`Raum ${region.label}`;const nearest=nearestWaypoint(data,point.fraction);return`Raum ${nearest.name||nearest.id}`}
export function runWhere(data:CrossSectionData,run:Pick<HazardRun,'startIndex'|'endIndex'>){const start=data.points[run.startIndex],end=data.points[run.endIndex],mid=data.points[Math.round((run.startIndex+run.endIndex)/2)],a=regionalPositionLabel(data,start),b=regionalPositionLabel(data,end),m=regionalPositionLabel(data,mid),startKm=Math.round(start.distanceKm/10)*10,endKm=Math.round(end.distanceKm/10)*10,corridor=data.corridorKm??0;if(a===b||run.endIndex-run.startIndex<=1)return`${m} · etwa km ${Math.round(((start.distanceKm+end.distanceKm)/2)/10)*10}${corridor?` · ${Math.round(corridor)}-km-Korridor`:''}`;return`${a} bis ${b} · etwa km ${startKm}–${endKm}${corridor?` · ${Math.round(corridor)}-km-Korridor`:''}`}
function epoch(value:string,fallback:number){const parsed=Date.parse(value);return Number.isFinite(parsed)?parsed:fallback}
function iso(value:number){return new Date(value).toISOString()}
function routeSpanEpochs(data:CrossSectionData){const startEpoch=epoch(data.startTime,Date.now()),rawEnd=epoch(data.endTime,startEpoch);return{startEpoch,endEpoch:Math.max(startEpoch,rawEnd)}}
export function routeFractionEpoch(data:CrossSectionData,fraction:number){const {startEpoch,endEpoch}=routeSpanEpochs(data),safeFraction=Math.max(0,Math.min(1,Number.isFinite(fraction)?fraction:0));return startEpoch+(endEpoch-startEpoch)*safeFraction}
export function routeTimeAtFraction(data:CrossSectionData,fraction:number){return iso(routeFractionEpoch(data,fraction))}
export function hazardTransitionWindow(data:CrossSectionData,run:Pick<HazardRun,'startIndex'|'endIndex'>):HazardTransitionWindow{const first=data.points[run.startIndex],last=data.points[run.endIndex],previous=data.points[run.startIndex-1],next=data.points[run.endIndex+1],firstEpoch=routeFractionEpoch(data,first?.fraction??0),lastEpoch=routeFractionEpoch(data,last?.fraction??0),previousMidFraction=previous?Math.max(0,(previous.fraction+(first?.fraction??0))/2):0,nextMidFraction=next?Math.min(1,((last?.fraction??1)+next.fraction)/2):1;return{entryFrom:iso(run.startIndex===0?routeFractionEpoch(data,0):routeFractionEpoch(data,previousMidFraction)),entryTo:iso(firstEpoch),exitFrom:iso(lastEpoch),exitTo:iso(run.endIndex===data.points.length-1?routeFractionEpoch(data,1):routeFractionEpoch(data,nextMidFraction)),fromRouteStart:run.startIndex===0,toRouteEnd:run.endIndex===data.points.length-1}}

type VerticalPointHazard={kind:VerticalHazardKind;label:string;severity:Severity;baseFl:number;topFl:number;detail:string};
function profileRows(sample:CrossPoint|CrossCorridorSample){return sample.levels.map(level=>({height:hft(finite(level.height)),temperature:finite(level.temperature),humidity:finite(level.humidity),cloud:finite(level.cloud),windSpeed:finite(level.windSpeed),windDirection:finite(level.windDirection)})).filter((row):row is {height:number;temperature:number|null;humidity:number|null;cloud:number|null;windSpeed:number|null;windDirection:number|null}=>row.height!==null&&row.height>=Number(hft(sample.elevation))).sort((a,b)=>a.height-b.height)}
function verticalPointHazards(sample:CrossPoint|CrossCorridorSample):VerticalPointHazard[]{
 const rows=profileRows(sample),hazards:VerticalPointHazard[]=[];if(!rows.length)return hazards;const cloudRows=rows.filter(row=>(row.cloud??0)>=55||(row.humidity??0)>=90),maxCloud=Math.max(0,...cloudRows.map(row=>row.cloud??0));
 if(cloudRows.length)hazards.push({kind:'cloud',label:'Vertikale Bewölkung',severity:maxCloud>=90?'caution':'watch',baseFl:cloudRows[0].height,topFl:cloudRows.at(-1)!.height,detail:`max. ${Math.round(maxCloud)} % · feuchte/geschlossene Schichten`});
 const icingRows=cloudRows.filter(row=>row.temperature!==null&&row.temperature>=-25&&row.temperature<=2),icingCloud=Math.max(0,...icingRows.map(row=>row.cloud??0));if(icingRows.length)hazards.push({kind:'icing',label:'Vereisungsschicht',severity:icingCloud>=82&&icingRows.some(row=>Number(row.temperature)>=-16)?'caution':'watch',baseFl:icingRows[0].height,topFl:icingRows.at(-1)!.height,detail:`${Math.round(Math.min(...icingRows.map(row=>Number(row.temperature))))} bis ${Math.round(Math.max(...icingRows.map(row=>Number(row.temperature))))} °C · max. Wolken ${Math.round(icingCloud)} %`});
 const windRows=rows.filter(row=>(row.windSpeed??0)>=45);if(windRows.length){const peak=Math.max(...windRows.map(row=>Number(row.windSpeed)));hazards.push({kind:'wind',label:'Starker Höhenwind',severity:peak>=65?'caution':'watch',baseFl:windRows[0].height,topFl:windRows.at(-1)!.height,detail:`Spitze etwa ${Math.round(peak)} kt`})}
 const shearRows:{height:number;shear:number}[]=[];for(let index=1;index<rows.length;index++){const a=rows[index-1],b=rows[index];if([a.windSpeed,a.windDirection,b.windSpeed,b.windDirection].some(value=>value===null)||b.height-a.height<2)continue;const shear=vectorShear({speed:a.windSpeed!,direction:a.windDirection!,height:a.height},{speed:b.windSpeed!,direction:b.windDirection!,height:b.height});if(shear>=4)shearRows.push({height:(a.height+b.height)/2,shear})}if(shearRows.length){const peak=Math.max(...shearRows.map(row=>row.shear));hazards.push({kind:'turbulence',label:'Turbulenz / Windscherung',severity:peak>=7?'caution':'watch',baseFl:Math.max(0,Math.min(...shearRows.map(row=>row.height))-10),topFl:Math.max(...shearRows.map(row=>row.height))+10,detail:`max. Vektorscherung ${peak.toFixed(1)} kt je 1000 ft`})}
 const cape=finite(sample.cape)??0,code=Math.round(finite(sample.weatherCode)??-1),precipitation=Math.max(0,finite(sample.precipitation)??0),convective=[95,96,99].includes(code)||cape>=450&&(precipitation>=.25||maxCloud>=70);if(convective){const top=cloudRows.at(-1)?.height??rows.at(-1)!.height,base=cloudRows[0]?.height??Math.max(0,top-120);hazards.push({kind:'convection',label:'Konvektive Vertikalausdehnung',severity:[95,96,99].includes(code)||cape>=900?'caution':'watch',baseFl:base,topFl:top,detail:`${[95,96,99].includes(code)?'Gewittersignal':`CAPE ${Math.round(cape)} J/kg`} · Wolkenobergrenze modellnah`})}
 return hazards;
}
function pointVerticalHazards(point:CrossPoint){const samples:[CrossPoint|CrossCorridorSample,...CrossCorridorSample[]]=[point,...(point.corridorSamples??[])],byKind=new Map<VerticalHazardKind,VerticalPointHazard>();for(const sample of samples)for(const hazard of verticalPointHazards(sample)){const current=byKind.get(hazard.kind);if(!current)byKind.set(hazard.kind,hazard);else byKind.set(hazard.kind,{...current,severity:severityRank(hazard.severity)>severityRank(current.severity)?hazard.severity:current.severity,baseFl:Math.min(current.baseFl,hazard.baseFl),topFl:Math.max(current.topFl,hazard.topFl),detail:severityRank(hazard.severity)>severityRank(current.severity)?hazard.detail:current.detail})}return[...byKind.values()]}
export function verticalHazardRuns(data:CrossSectionData){const perPoint=data.points.map(point=>pointVerticalHazards(point)),kinds=['cloud','icing','turbulence','convection','wind'] as const,runs:VerticalHazardRun[]=[];for(const kind of kinds){let active:VerticalHazardRun|null=null;for(let index=0;index<perPoint.length;index++){const hazard=perPoint[index].find(item=>item.kind===kind);if(hazard){if(!active)active={...hazard,startIndex:index,endIndex:index};else{active.endIndex=index;active.baseFl=Math.min(active.baseFl,hazard.baseFl);active.topFl=Math.max(active.topFl,hazard.topFl);if(severityRank(hazard.severity)>severityRank(active.severity)){active.severity=hazard.severity;active.detail=hazard.detail}}}else if(active){runs.push(active);active=null}}if(active)runs.push(active)}return runs.sort((a,b)=>severityRank(b.severity)-severityRank(a.severity)||a.startIndex-b.startIndex)}
export function verticalHazardDetail(run:VerticalHazardRun,corridorKm:number){const base=Math.max(0,Math.round(run.baseFl/5)*5),top=Math.max(base,Math.round(run.topFl/5)*5);return`${formatAltitudeBand(base,top)} · ${run.detail}${corridorKm?` · im ${Math.round(corridorKm)}-km-Korridor`:''}`}

export function compass(direction:number|null){if(direction===null)return'–';const labels=['N','NO','O','SO','S','SW','W','NW'];return`${Math.round(direction)}° ${labels[Math.round((((direction%360)+360)%360)/45)%8]}`}
export function officialSignals(data:CrossSectionData){const seen=new Set<string>(),rows:{checkpoint:OfficialCheckpoint;signal:OfficialSignal}[]=[];for(const checkpoint of data.officialBriefing??[])for(const signal of checkpoint.signals??[]){if(signal.level==='none')continue;const key=[checkpoint.id,signal.kind,signal.source,signal.detail].join('|');if(seen.has(key))continue;seen.add(key);rows.push({checkpoint,signal})}return rows.sort((a,b)=>(b.signal.level==='caution'?2:1)-(a.signal.level==='caution'?2:1))}
export function routeOverview(data:CrossSectionData,runs:HazardRun[]){const cruise=data.points.map(point=>({speed:flightProfileValue(point,data.flightLevel,'windSpeed'),cloud:flightProfileValue(point,data.flightLevel,'cloud'),temperature:flightProfileValue(point,data.flightLevel,'temperature'),freezing:hft(finite(point.freezingLevel))})),maxWind=Math.max(0,...cruise.map(row=>row.speed??0)),meanCloud=cruise.length?cruise.reduce((sum,row)=>sum+(row.cloud??0),0)/cruise.length:0,temperatures=cruise.map(row=>row.temperature).filter((value):value is number=>value!==null),freezing=cruise.map(row=>row.freezing).filter((value):value is number=>value!==null),danger=runs.filter(run=>run.severity==='caution').length,watch=runs.filter(run=>run.severity==='watch').length;return{missingProfile:!data.points.length||data.points.some(point=>[point,...(point.corridorSamples??[])].some(sample=>[sample.precipitation,sample.weatherCode,sample.cape,sample.visibility].some(value=>finite(value)===null)||['temperature','humidity','cloud','windSpeed','windDirection'].some(key=>flightProfileValue(sample,data.flightLevel,key as 'temperature')===null))),maxWind,meanCloud,tempMin:temperatures.length?Math.min(...temperatures):null,tempMax:temperatures.length?Math.max(...temperatures):null,freezingMin:freezing.length?Math.min(...freezing):null,freezingMax:freezing.length?Math.max(...freezing):null,danger,watch}}
