import {useEffect,useState} from 'react';
import {AGREEMENT_COLOR,AGREEMENT_LABEL,DATA_QUALITY_LABEL,agreementWindows,assessmentSummary,firstAgreementChange,type DayAssessment} from './ensembleAssessment';

function dateLabel(date:string){return new Date(`${date}T12:00:00Z`).toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',timeZone:'UTC'})}
function windowLabel(window:{start:string;end:string}){return window.start===window.end?dateLabel(window.start):`${dateLabel(window.start)} – ${dateLabel(window.end)}`}
function parameterQualityLabel(quality:'sufficient'|'limited'|'missing'){return quality==='sufficient'?'Datenbasis gut':quality==='limited'?'Datenbasis eingeschränkt':'Datenbasis nicht ausreichend'}

export function EnsembleAssessmentDetails({assessment}:{assessment:DayAssessment}){
 return <div className="mid-ensemble-assessment" style={{fontSize:12,lineHeight:1.45,maxHeight:'60vh',overflowY:'auto'}}>
  <strong>{assessmentSummary(assessment)}</strong>
  <p style={{margin:'5px 0 8px'}}>Konfidenz und Datenqualität werden getrennt bewertet. Der Index ist keine Trefferwahrscheinlichkeit und kein Wetterfreigabesignal. In der 14-Tage-Übersicht zeigt die Füllfarbe die Konfidenz; ein zusätzlicher Außenring kennzeichnet nur eine eingeschränkte, schwache oder nicht ausreichende Datenbasis.</p>
  <dl style={{margin:'8px 0'}}>{assessment.parameters.map(parameter=><div key={parameter.key} style={{padding:'6px 0',borderBottom:'1px solid var(--border, #8884)'}}>
   <dt style={{display:'flex',justifyContent:'space-between',gap:8}}><b>{parameter.label}</b><b style={{color:AGREEMENT_COLOR[parameter.agreement]}}>{parameter.agreement==='unknown'?'nicht bewertbar':`${AGREEMENT_LABEL[parameter.agreement]} · Index ${Math.round(parameter.score??0)}/100`}</b></dt>
   <dd style={{margin:0}}>{parameter.detail}<br/>{parameter.coverage?`${parameter.coverage.members}/${parameter.coverage.expectedMembers} vollständige Mitglieder · ${parameter.coverage.families}/${parameter.coverage.expectedFamilies} erwartete Modellgruppen · ${parameterQualityLabel(parameter.quality)}`:'Datenabdeckung unbekannt'}{Math.abs(parameter.calibrationAdjustment)>=.25?` · lokale Skill-Korrektur ${parameter.calibrationAdjustment>0?'+':''}${parameter.calibrationAdjustment.toLocaleString('de-DE',{maximumFractionDigits:1})} Indexpunkte`:''}</dd>
  </div>)}</dl>
  <p>Der meteorologische Teil bewertet vorlaufnormalisierte P10–P90-Spreads robust über Temperatur, Niederschlag und Wind/Böen; Sonnenschein erhält bewusst geringeres Gewicht und kann den ganzen Tag nicht allein auf „gering“ ziehen. Eine Regenwahrscheinlichkeit um 50 % bedeutet einen offenen Ereignisausgang, aber nicht automatisch eine schlechte probabilistische Prognose.</p>
  <details><summary style={{minHeight:32,cursor:'pointer'}}>Methodik, Datenstand und Kalibrierung</summary><p>Basisgrenzen bei kurzem Vorlauf: Temperatur 4/8 K; Niederschlag 3/10 mm pro Tag; Wind 8/16 kt; Böen 12/24 kt; relative Sonne 25/50 Prozentpunkte. Mit wachsendem Vorlauf werden diese Grenzen entsprechend dem typischerweise zunehmenden Ensemble-Spread stufenlos erweitert. Gleichzeitig begrenzt ein Vorlauf-Cap unrealistisch hohe Langfristkonfidenz.</p><p>Die Gesamtbewertung ist eine gewichtete robuste Aggregation: Niederschlag 32 %, Temperatur 28 %, Wind/Böen 28 %, Sonne 12 %. Erst mehrere schwache Kernparameter drücken die Gesamtbewertung deutlich. Fehlende oder ältere Daten verschlechtern primär die separat ausgewiesene Datenqualität; erst eine sehr schwache Datenbasis begrenzt die Gesamtaussage.</p><p>Hohe Datenqualität setzt mindestens zwei unabhängige Modellgruppen, sechs vollständige native Mitglieder, ausreichende erwartete Mitgliederabdeckung und aktuelle beitragende Läufe voraus. Erwartete Modellgruppen werden parameterweise bestimmt; ein Modell, das einen Parameter grundsätzlich nicht liefert, zählt dort nicht als Ausfall.</p>{assessment.calibrationApplied?<p>Lokale Skill-Kalibrierung aktiv: {assessment.calibrationSampleDays} abgeschlossene Rückblickstage. MID nutzt dafür bestehende lokale Fehler- und Brier-Auswertungen nur gedämpft und nur bis etwa 96 Stunden Vorlauf; Langfristtage werden nicht aus Kurzfriststatistik hoch- oder herunterkalibriert.</p>:<p>Lokale Skill-Kalibrierung derzeit nicht oder noch nicht ausreichend belegt. Die Anzeige bleibt dann vollständig ensemble- und vorlaufbasiert.</p>}{assessment.parameters.map(p=><p key={p.key}>{p.label}: {p.coverage?.oldestInitialisation?`ältester beitragender Lauf ${new Date(p.coverage.oldestInitialisation).toLocaleString('de-DE')}`:'Laufzeit nicht belegt'}</p>)}</details>
 </div>;
}

export function ForecastConfidenceOverview({assessments,outlook,advancedMode=false}:{assessments:DayAssessment[];outlook?:{headline:string;detail:string};advancedMode?:boolean}){
 const windows=agreementWindows(assessments),change=firstAgreementChange(assessments),first=assessments[0],limited=change??assessments.find(d=>d.agreement!=='high'||d.dataQuality==='poor'||d.dataQuality==='missing');
 const lowest=limited?.limiting.map(p=>p.label).join(', ')||'';
 return <section className="ensemble-forecast-compass cockpit-forecast-compass" aria-label="MID Prognose-Kompass">
  <header><span aria-hidden="true">◎</span><div><small>MID Prognose-Kompass</small><strong>Prognoseentwicklung</strong></div></header>
  <div><span><small>Gut vorhersagbare Zeiträume</small><b>{windows.length?windowLabel(windows[0]):'Noch kein durchgehend hohes Konfidenzfenster'}</b><em>{windows.length?'Hohe robuste Ensemblekonfidenz bei mindestens ausreichender Datenbasis.':'Mindestens zwei Kernparameter oder der Vorlauf begrenzen die gemeinsame Konfidenz.'}</em></span>
   <span><small>Erwartete Entwicklung</small><b>{outlook?.headline??'Tagesprognosen vergleichen'}</b><em>{outlook?.detail??'Auch eine gut vorhersagbare Entwicklung kann ungünstiges Wetter bedeuten.'}</em></span>
   <span><small>{change?'Konfidenz nimmt ab':'Begrenzender Bereich'}</small><b>{limited?`${dateLabel(limited.date)}${lowest?`: ${lowest}`:''}`:'Kein deutlich begrenzender Bereich erkannt'}</b><em>{limited?.dataQuality==='poor'||limited?.dataQuality==='missing'?`Datenbasis ${DATA_QUALITY_LABEL[limited.dataQuality]}; meteorologische Unsicherheit wird davon getrennt ausgewiesen.`:limited?'Die Ensemblelösungen streuen in mindestens einem Kernbereich stärker oder der Vorlauf begrenzt die Aussage.':'Die Kernparameter liegen innerhalb der vorlaufnormalisierten Konfidenzgrenzen.'}</em></span>
  </div>
  <details style={{marginTop:8,fontSize:13}}><summary style={{minHeight:40,cursor:'pointer'}}>Parameter und weitere Zeiträume</summary>
   {windows.length>1&&<p>Weitere hohe Konfidenzfenster: {windows.slice(1).map(windowLabel).join(' · ')}</p>}
   {first?.parameters.map(parameter=>{const periods=agreementWindows(assessments,parameter.key);return <p key={parameter.key}><b>{parameter.label}:</b> {periods.length?periods.map(windowLabel).join(' · '):'kein ausreichend belegtes Fenster mit hoher Parameterkonfidenz'}</p>})}
   <p>Fenster zeigen hohe robuste Ensemblekonfidenz für jeden enthaltenen Tag. Sie sind keine gemeinsame Eintrittswahrscheinlichkeit, keine Wetterfreigabe und keine Garantie. Datenlücken werden separat als Datenqualität gekennzeichnet und unterbrechen nur dann das Gesamtfenster, wenn die Basis schwach oder nicht ausreichend ist.</p>
   {advancedMode&&<p>Die Spreads werden mit dem Vorlauf normalisiert. Wo genügend lokale Rückblicksdaten vorhanden sind, fließen Brier-/Fehlerwerte mit starker Schrumpfung als kleine Skill-Korrektur ein; der angezeigte 0–100-Index bleibt ausdrücklich keine Prozentwahrscheinlichkeit.</p>}
  </details>
 </section>;
}

/** Re-evaluate run freshness in long-lived foreground and resumed PWA views. */
export function useEnsembleAssessmentTime(){const [now,setNow]=useState(Date.now);useEffect(()=>{const refresh=()=>setNow(Date.now()),timer=window.setInterval(refresh,60000);document.addEventListener("visibilitychange",refresh);return()=>{window.clearInterval(timer);document.removeEventListener("visibilitychange",refresh)}},[]);return now}
