import type {Day,EnsembleDay,Location} from './weather';

const PREFIX='mid:forecast-verification:v1:';
const MAX_CAPTURES=120;
export type ForecastPrediction={id:string;label:string;max:number;min:number;precipitation:number;probability:number};
export type ForecastCapture={targetDate:string;issuedAt:string;leadHours:number;predictions:ForecastPrediction[]};
export type ForecastReference={date:string;max:number;min:number;precipitation:number;source:string};
type Store={version:1;updatedAt:string;captures:ForecastCapture[];references:ForecastReference[]};
export type ForecastModelScore={id:string;label:string;days:number;temperatureMae:number;precipitationMae:number;brier:number;score:number;weight:number};
export type ForecastDayReview={date:string;issuedAt:string;leadHours:number;reference:ForecastReference;bestMatch?:ForecastPrediction;winner?:ForecastModelScore};
export type ForecastVerificationReport={days:number;models:ForecastModelScore[];reviews:ForecastDayReview[];bestModel?:ForecastModelScore;rainBrier?:number;temperatureMae?:number;weightingReady:boolean};

function finite(value:unknown,fallback=0){const number=Number(value);return Number.isFinite(number)?number:fallback}
function storeKey(locationKey:string){return`${PREFIX}${locationKey}`}
function emptyStore():Store{return{version:1,updatedAt:new Date().toISOString(),captures:[],references:[]}}
function readStore(locationKey:string):Store{try{const parsed=JSON.parse(localStorage.getItem(storeKey(locationKey))||'null') as Store|null;return parsed?.version===1&&Array.isArray(parsed.captures)&&Array.isArray(parsed.references)?parsed:emptyStore()}catch{return emptyStore()}}
function saveStore(locationKey:string,store:Store){try{localStorage.setItem(storeKey(locationKey),JSON.stringify({...store,updatedAt:new Date().toISOString(),captures:store.captures.slice(-MAX_CAPTURES),references:store.references.slice(-45)}))}catch{}}
function dateNoon(date:string){const match=date.match(/^(\d{4})-(\d{2})-(\d{2})$/);return match?Date.UTC(Number(match[1]),Number(match[2])-1,Number(match[3]),12):NaN}
function predictionValid(row:ForecastPrediction){return row.id&&row.label&&[row.max,row.min,row.precipitation,row.probability].every(Number.isFinite)}
function bestMatchPrediction(day:Day):ForecastPrediction{return{id:'best_match',label:'Open-Meteo Best Match',max:finite(day.max),min:finite(day.min),precipitation:Math.max(0,finite(day.precipitation)),probability:Math.max(0,Math.min(100,finite(day.probability)))}}
export function recordForecastCapture(locationKey:string,days:Day[],ensemble:EnsembleDay[]){if(!locationKey||!days.length)return;const now=Date.now(),slot=Math.floor(now/(3*3600000)),store=readStore(locationKey),ensembleByDate=new Map(ensemble.map(row=>[row.date,row]));for(const day of days.slice(0,3)){const target=dateNoon(day.date),leadHours=(target-now)/3600000;if(!Number.isFinite(leadHours)||leadHours<-12||leadHours>84)continue;const row=ensembleByDate.get(day.date),predictions=[bestMatchPrediction(day),...(row?.modelSummaries??[]).map(model=>({id:model.id,label:model.label,max:model.max,min:model.min,precipitation:model.precipitation,probability:model.precipitationProbability}))].filter(predictionValid),signature=`${day.date}:${slot}`,index=store.captures.findIndex(item=>`${item.targetDate}:${Math.floor(Date.parse(item.issuedAt)/(3*3600000))}`===signature),capture={targetDate:day.date,issuedAt:new Date(now).toISOString(),leadHours,predictions};if(index>=0)store.captures[index]=capture;else store.captures.push(capture)}saveStore(locationKey,store)}
function referenceRows(data:any,source:string){const daily=data?.daily??{},times=Array.isArray(daily.time)?daily.time:[];return times.map((date:string,index:number)=>({date:String(date),max:finite(daily.temperature_2m_max?.[index],NaN),min:finite(daily.temperature_2m_min?.[index],NaN),precipitation:Math.max(0,finite(daily.precipitation_sum?.[index],NaN)),source})).filter((row:ForecastReference)=>[row.max,row.min,row.precipitation].every(Number.isFinite)) as ForecastReference[]}
function utcDateOffset(days:number){const date=new Date(Date.now()+days*86400000);return date.toISOString().slice(0,10)}
async function retrospectiveBestMatchRequest(location:Location,signal?:AbortSignal){const params=new URLSearchParams({latitude:String(location.latitude),longitude:String(location.longitude),timezone:'auto',past_days:'14',forecast_days:'1',models:'best_match',daily:'temperature_2m_max,temperature_2m_min,precipitation_sum'}),response=await fetch(`https://api.open-meteo.com/v1/forecast?${params}`,{signal,cache:'no-store'});if(!response.ok)throw new Error(`Open-Meteo Rückblick HTTP ${response.status}`);return referenceRows(await response.json(),'Open-Meteo Best-Match-Rückblick')}
async function reanalysisReferenceRequest(location:Location,signal?:AbortSignal){const params=new URLSearchParams({latitude:String(location.latitude),longitude:String(location.longitude),timezone:'auto',start_date:utcDateOffset(-16),end_date:utcDateOffset(-1),models:'era5_land',daily:'temperature_2m_max,temperature_2m_min,precipitation_sum'});if(Number.isFinite(location.elevation))params.set('elevation',String(location.elevation));const response=await fetch(`https://archive-api.open-meteo.com/v1/archive?${params}`,{signal,cache:'no-store'});if(!response.ok)throw new Error(`Open-Meteo Reanalyse HTTP ${response.status}`);return referenceRows(await response.json(),'Open-Meteo ERA5-Land-Reanalyse')}
async function referenceRequest(location:Location,signal?:AbortSignal){const settled=await Promise.allSettled([retrospectiveBestMatchRequest(location,signal),reanalysisReferenceRequest(location,signal)]);if(signal?.aborted)throw new DOMException('Abgebrochen','AbortError');const fallback=settled[0].status==='fulfilled'?settled[0].value:[],reanalysis=settled[1].status==='fulfilled'?settled[1].value:[];if(!fallback.length&&!reanalysis.length){const messages=settled.filter((row):row is PromiseRejectedResult=>row.status==='rejected').map(row=>row.reason instanceof Error?row.reason.message:String(row.reason));throw new Error(messages.join(' · ')||'Kein Rückblick verfügbar.')}const merged=new Map(fallback.map(row=>[row.date,row]));for(const row of reanalysis)merged.set(row.date,row);return[...merged.values()].sort((a,b)=>a.date.localeCompare(b.date))}
export async function refreshForecastReferences(locationKey:string,location:Location,signal?:AbortSignal){const store=readStore(locationKey),rows=await referenceRequest(location,signal),byDate=new Map(store.references.map(row=>[row.date,row]));for(const row of rows)byDate.set(row.date,row);store.references=[...byDate.values()].sort((a,b)=>a.date.localeCompare(b.date)).slice(-45);saveStore(locationKey,store);return store}
function chosenCaptures(store:Store){const today=new Date().toISOString().slice(0,10),byDate=new Map<string,ForecastCapture[]>();for(const capture of store.captures)if(capture.targetDate<today){const list=byDate.get(capture.targetDate)??[];list.push(capture);byDate.set(capture.targetDate,list)}return[...byDate.entries()].map(([date,list])=>({date,capture:[...list].sort((a,b)=>Math.abs(a.leadHours-24)-Math.abs(b.leadHours-24))[0]})).sort((a,b)=>b.date.localeCompare(a.date))}
function predictionDayScore(prediction:ForecastPrediction,reference:ForecastReference){const temperature=(Math.abs(prediction.max-reference.max)+Math.abs(prediction.min-reference.min))/2,precipitation=Math.abs(prediction.precipitation-reference.precipitation),observed=reference.precipitation>=.1?1:0,probability=Math.max(0,Math.min(1,prediction.probability/100)),brier=(probability-observed)**2;return temperature+Math.min(4,precipitation*.35)+brier*3}
export function buildForecastVerificationReport(locationKey:string):ForecastVerificationReport{const store=readStore(locationKey),references=new Map(store.references.map(row=>[row.date,row])),chosen=chosenCaptures(store).filter(item=>references.has(item.date)).slice(0,30),stats=new Map<string,{id:string;label:string;days:number;temp:number;rain:number;brier:number}>(),reviews:ForecastDayReview[]=[];for(const item of chosen){const reference=references.get(item.date)!;for(const prediction of item.capture.predictions){const stat=stats.get(prediction.id)??{id:prediction.id,label:prediction.label,days:0,temp:0,rain:0,brier:0},rainObserved=reference.precipitation>=.1?1:0,probability=Math.max(0,Math.min(1,prediction.probability/100));stat.days++;stat.temp+=(Math.abs(prediction.max-reference.max)+Math.abs(prediction.min-reference.min))/2;stat.rain+=Math.abs(prediction.precipitation-reference.precipitation);stat.brier+=(probability-rainObserved)**2;stats.set(prediction.id,stat)}reviews.push({date:item.date,issuedAt:item.capture.issuedAt,leadHours:item.capture.leadHours,reference,bestMatch:item.capture.predictions.find(row=>row.id==='best_match')})}const raw=[...stats.values()].map(row=>{const temperatureMae=row.temp/row.days,precipitationMae=row.rain/row.days,brier=row.brier/row.days,score=temperatureMae+Math.min(4,precipitationMae*.35)+brier*3;return{id:row.id,label:row.label,days:row.days,temperatureMae,precipitationMae,brier,score,weight:0}}).sort((a,b)=>a.score-b.score),eligible=raw.filter(row=>row.days>=Math.min(3,chosen.length)),inverse=eligible.reduce((sum,row)=>sum+1/Math.max(.25,row.score),0);for(const row of raw)row.weight=inverse&&eligible.includes(row)?100*(1/Math.max(.25,row.score))/inverse:0;for(const review of reviews){const predictions=chosen.find(item=>item.date===review.date)?.capture.predictions??[],winner=[...predictions].sort((a,b)=>predictionDayScore(a,review.reference)-predictionDayScore(b,review.reference))[0];review.winner=winner?raw.find(score=>score.id===winner.id):undefined}const bestMatch=raw.find(row=>row.id==='best_match');return{days:chosen.length,models:raw,reviews,bestModel:raw[0],rainBrier:bestMatch?.brier,temperatureMae:bestMatch?.temperatureMae,weightingReady:chosen.length>=3&&eligible.length>=2}}
