import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {Activity,BarChart3,BrainCircuit,CheckCircle2,CloudRain,Database,MapPinned,RefreshCw,Scale,ShieldCheck,SlidersHorizontal,Target,Thermometer,ThumbsDown,ThumbsUp,Wifi} from 'lucide-react';
import type {Day,EnsembleDay,Hour,Location,RadarNowcast,Station} from './weather';
import {
 applyLocalTwinForecast,
 buildForecastVerificationReport,
 buildTwinRecommendations,
 fetchPrivateSensorObservation,
 readTwinSiteProfile,
 readWeatherTwinSettings,
 recordCustomSensorObservation,
 recordForecastCapture,
 recordLiveTwinObservation,
 recordTwinRecommendationFeedback,
 refreshForecastReferences,
 restoreForecastVerificationArchive,
 updateTwinSiteProfile,
 weatherRegimeLabel,
 writeWeatherTwinSettings,
 type ForecastParameter,
 type ForecastVerificationReport,
 type PrivateSensorSample,
 type TwinActivity,
 type TwinSiteProfile,
 type WeatherTwinSettings
} from './forecastVerification';
import {formatDecimal} from './format';

function dayLabel(value:string){const parts=value.split('-').map(Number),date=new Date(Date.UTC(parts[0],parts[1]-1,parts[2],12));return new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'2-digit',timeZone:'UTC'}).format(date)}
function qualityLabel(score:number){return score<=.75?'sehr gut':score<=1.25?'gut':score<=2?'befriedigend':'ausbaufähig'}
function confidenceLabel(value:'low'|'medium'|'high'){return value==='high'?'hoch':value==='medium'?'mittel':'vorläufig'}
function parameterLabel(value:ForecastParameter){return({temperature:'Temperatur',precipitation:'Niederschlagsmenge',probability:'Regenwahrscheinlichkeit',gust:'Böen',sunshine:'Sonnenschein'} as Record<ForecastParameter,string>)[value]}
function activityLabel(value:TwinActivity){return({commute:'Arbeitsweg',outdoor:'Draußenaktivität',garden:'Garten',rowing:'Rudern',dog:'Hundespaziergang',ski:'Berg-/Wintersport',heat:'Hitzeschutz'} as Record<TwinActivity,string>)[value]}
function terrainLabel(value:TwinSiteProfile['terrain']){return({plain:'Ebene',valley:'Tal/Kaltluftsenke',slope:'Hanglage',ridge:'Kuppe/Gipfel',coast:'Küsten-/Gewässerlage'} as Record<TwinSiteProfile['terrain'],string>)[value]}

export default function ForecastVerificationPanel({locationKey,location,days,ensemble,hours,station,radar}:{locationKey:string;location:Location;days:Day[];ensemble:EnsembleDay[];hours:Hour[];station?:Station|null;radar?:RadarNowcast|null}){
 const[report,setReport]=useState<ForecastVerificationReport>(()=>buildForecastVerificationReport(locationKey,days,ensemble,location)),[loading,setLoading]=useState(false),[error,setError]=useState(''),[settings,setSettings]=useState<WeatherTwinSettings>(()=>readWeatherTwinSettings()),[profile,setProfile]=useState<TwinSiteProfile>(()=>readTwinSiteProfile(locationKey,location)),[sensorBusy,setSensorBusy]=useState(false),[sensorMessage,setSensorMessage]=useState(''),[manualSensor,setManualSensor]=useState<PrivateSensorSample>({temperature:undefined,precipitation:undefined,gust:undefined});
 const refreshReport=()=>setReport(buildForecastVerificationReport(locationKey,days,ensemble,location));
 useEffect(()=>{let active=true;void restoreForecastVerificationArchive(locationKey).then(restored=>{if(active&&restored)refreshReport()});return()=>{active=false}},[locationKey]);
 useEffect(()=>{recordForecastCapture(locationKey,days,ensemble,location);recordLiveTwinObservation(locationKey,location,{station,radar,currentHour:hours.find(hour=>hour.epoch>=Date.now())??hours[0]});refreshReport()},[locationKey,location.latitude,location.longitude,days,ensemble,hours,station?.timestamp,radar?.observedAt]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');refreshForecastReferences(locationKey,location,controller.signal).then(refreshReport).catch(reason=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:String(reason))}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[locationKey,location.latitude,location.longitude,days,ensemble]);
 useEffect(()=>{if(!settings.privateSensorUrl)return;const controller=new AbortController();setSensorBusy(true);fetchPrivateSensorObservation(locationKey,controller.signal).then(ok=>{if(ok){setSensorMessage('Privater Sensor wurde übernommen.');refreshReport()}}).catch(reason=>{if(!controller.signal.aborted)setSensorMessage(reason instanceof Error?reason.message:String(reason))}).finally(()=>{if(!controller.signal.aborted)setSensorBusy(false)});return()=>controller.abort()},[locationKey,settings.privateSensorUrl]);
 useEffect(()=>{const onSettings=(event:Event)=>setSettings((event as CustomEvent<WeatherTwinSettings>).detail||readWeatherTwinSettings()),onProfile=(event:Event)=>setProfile((event as CustomEvent<TwinSiteProfile>).detail||readTwinSiteProfile(locationKey,location));window.addEventListener('mid:weather-twin-settings',onSettings);window.addEventListener('mid:weather-twin-profile',onProfile);return()=>{window.removeEventListener('mid:weather-twin-settings',onSettings);window.removeEventListener('mid:weather-twin-profile',onProfile)}},[locationKey,location]);
 const latest=report.reviews[0],best=report.bestModel,ranking=report.models.filter(row=>!['best_match','mid_local_weighted','equal_weighted'].includes(row.id)).slice(0,8),rainReliability=Number.isFinite(report.rainBrier)?report.rainBrier!<=.12?'hoch':report.rainBrier!<=.24?'mittel':'gering':'–',segments=report.segments.filter(segment=>segment.days>=2).slice(0,10),weightedGain=Number.isFinite(report.weightedImprovement)?`${report.weightedImprovement!>=0?'+':''}${formatDecimal(report.weightedImprovement!,1,1)} %`:'noch offen',recommendations=useMemo(()=>buildTwinRecommendations(locationKey,hours,radar),[locationKey,hours,radar,settings]),activeDays=useMemo(()=>applyLocalTwinForecast(locationKey,days,ensemble,radar),[locationKey,days,ensemble,radar,settings]);
 const intro=useMemo(()=>report.days?`${report.days} abgeschlossene Tage mit ${report.samples} Horizont-Vergleichen ausgewertet`:'MID beginnt jetzt mit dem unabhängigen lokalen Prognosearchiv.',[report.days,report.samples]);
 const spatialFacts=useMemo(()=>{const facts:string[]=[];if(Number.isFinite(station?.distance))facts.push(`Referenzmessung ${formatDecimal(Number(station!.distance),1,1)} km entfernt`);if(radar&&radar.source!=='model'){if(Number.isFinite(radar.arrivalMinutes)&&Number(radar.arrivalMinutes)<=240)facts.push(`Radar-/Nowcast-Signal in etwa ${Math.max(0,Math.round(Number(radar.arrivalMinutes)))} min relevant`);if(Number.isFinite(radar.motionDirectionDeg))facts.push(`Echozugrichtung ${Math.round(Number(radar.motionDirectionDeg))}° · Qualität ${radar.quality||'nicht klassifiziert'}`)}facts.push(`${terrainLabel(profile.terrain)} · ${profile.exposure==='exposed'?'exponiert':profile.exposure==='sheltered'?'windgeschützt':'neutral'}${profile.waterInfluence?' · Gewässereinfluss':''}`);return facts},[station?.distance,radar?.arrivalMinutes,radar?.motionDirectionDeg,radar?.quality,radar?.source,profile.terrain,profile.exposure,profile.waterInfluence,location.elevation]);
 const patchSettings=(change:Partial<WeatherTwinSettings>)=>setSettings(writeWeatherTwinSettings(change));
 const patchActivity=(activity:TwinActivity,enabled:boolean)=>patchSettings({activities:{...settings.activities,[activity]:{...settings.activities[activity],enabled}}});
 const patchProfile=(change:Partial<TwinSiteProfile>)=>setProfile(updateTwinSiteProfile(locationKey,location,change));
 const manualSubmit=(event:FormEvent)=>{event.preventDefault();const ok=recordCustomSensorObservation(locationKey,{...manualSensor,label:settings.privateSensorLabel});setSensorMessage(ok?'Eigene Messung wurde archiviert.':'Messung konnte nicht gespeichert werden.');if(ok){setManualSensor({temperature:undefined,precipitation:undefined,gust:undefined});refreshReport()}};
 const sensorNumber=(key:'temperature'|'precipitation'|'gust',value:string)=>setManualSensor(current=>({...current,[key]:value===''?undefined:Number(value)}));
 return <section className="forecast-verification weather-twin-panel"><header><div><span>Prognosegüte und Rückblick · lokaler Wetterzwilling</span><h3>Prognosegüte, Lernen, Assimilation und persönliche Wirkung</h3><small>Was wurde vorhergesagt – was zeigt der Rückblick? Wie verbessert MID die nächste Entscheidung?</small></div>{loading&&<RefreshCw className="spin" size={18}/>}</header>
  <div className={`weather-twin-health ${report.health.status}`}><BrainCircuit size={24}/><span><strong>{report.health.label}</strong><small>Systemgüte {Math.round(report.health.score)} % · Archivstand {new Date(report.archiveUpdatedAt).toLocaleString('de-DE')}</small></span><em>{report.health.issues.length?report.health.issues.join(' · '):'Beobachtung, Kontrollgruppen und lokales Lernen sind verfügbar.'}</em></div>
  <p>{intro}. MID hält ursprüngliche Prognosestände unverändert fest, trennt +12, +24, +48 und +72 Stunden, bewertet Parameter und Wetterlagen separat und vergleicht Best Match, einfaches Multimodellmittel und die lokal gelernte MID-Prognose.</p>
  {error&&<div className="forecast-verification-note">Rückblick derzeit nicht vollständig aktualisierbar: {error}</div>}
  <section className="weather-twin-controls"><header><SlidersHorizontal size={19}/><span><strong>Aktiver Wetterzwilling</strong><small>Die Rohprognose bleibt im Archiv erhalten; nur die sichtbare Hauptprognose kann lokal korrigiert werden.</small></span></header><div><label><input type="checkbox" checked={settings.useAsMainForecast} onChange={event=>patchSettings({useAsMainForecast:event.target.checked})}/><span><b>Als Hauptprognose verwenden</b><small>Nur bei freigegebener lokaler Gewichtung; ansonsten bleibt Best Match sichtbar.</small></span></label><label><input type="checkbox" checked={settings.nowcastAssimilation} onChange={event=>patchSettings({nowcastAssimilation:event.target.checked})}/><span><b>Radar-/Nowcast-Assimilation</b><small>Beobachtete Niederschlagssignale werden ausschließlich in den ersten Stunden einbezogen.</small></span></label><label><input type="checkbox" checked={settings.biasCorrection} onChange={event=>patchSettings({biasCorrection:event.target.checked})}/><span><b>Lokale Bias-Korrektur</b><small>Systematische Abweichungen werden je Wetterlage und Horizont abgeschwächt korrigiert.</small></span></label><label><input type="checkbox" checked={settings.probabilityCalibration} onChange={event=>patchSettings({probabilityCalibration:event.target.checked})}/><span><b>Wahrscheinlichkeiten kalibrieren</b><small>Regenwahrscheinlichkeiten werden mit der tatsächlich beobachteten Trefferhäufigkeit verglichen.</small></span></label></div></section>
  <section className="weather-twin-truth"><header><Database size={19}/><span><strong>Unabhängige Wetterwahrheit</strong><small>Messung vor Analyse, Reanalyse vor Modellrückblick.</small></span></header><div className="weather-twin-source-chips">{report.health.sources.length?report.health.sources.map(source=><span key={source}>{source}</span>):<span>Lernphase – noch keine abgeschlossene unabhängige Referenz</span>}</div>{latest&&<p><b>{dayLabel(latest.reference.date)}:</b> {latest.reference.source} · Qualität {Math.round(latest.reference.quality*100)} % · Vertrauen {confidenceLabel(latest.reference.confidence)}{latest.reference.coverageHours?` · ${formatDecimal(latest.reference.coverageHours,1,1)} h lokale Abdeckung`:''}</p>}</section>
  <section className="weather-twin-spatial"><header><MapPinned size={19}/><span><strong>Räumliche Umfeldanalyse</strong><small>Messdistanz, Zugbahn und Standortwirkung fließen getrennt und nachvollziehbar ein.</small></span></header><div>{spatialFacts.map(fact=><span key={fact}>{fact}</span>)}</div></section>
  <section className="weather-twin-site"><header><MapPinned size={19}/><span><strong>Lokaler Standortfingerabdruck</strong><small>Topografie und Standortwirkung werden getrennt von der Modellprognose gespeichert.</small></span><em>{profile.manual?'manuell verfeinert':'automatisch abgeleitet'}</em></header><div><label>Geländeform<select value={profile.terrain} onChange={event=>patchProfile({terrain:event.target.value as TwinSiteProfile['terrain']})}>{(['plain','valley','slope','ridge','coast'] as const).map(value=><option key={value} value={value}>{terrainLabel(value)}</option>)}</select></label><label>Exposition<select value={profile.exposure} onChange={event=>patchProfile({exposure:event.target.value as TwinSiteProfile['exposure']})}><option value="sheltered">windgeschützt</option><option value="neutral">neutral</option><option value="exposed">exponiert</option></select></label><label>Kaltluftsenke<select value={profile.coldPoolRisk} onChange={event=>patchProfile({coldPoolRisk:event.target.value as TwinSiteProfile['coldPoolRisk']})}><option value="low">gering</option><option value="medium">mittel</option><option value="high">hoch</option></select></label><label>Nebelrisiko<select value={profile.fogRisk} onChange={event=>patchProfile({fogRisk:event.target.value as TwinSiteProfile['fogRisk']})}><option value="low">gering</option><option value="medium">mittel</option><option value="high">hoch</option></select></label><label className="inline"><input type="checkbox" checked={profile.waterInfluence} onChange={event=>patchProfile({waterInfluence:event.target.checked})}/>Gewässer-/Küsteneinfluss</label></div></section>
  <section className="weather-twin-sensors"><header><Wifi size={19}/><span><strong>Eigene Sensoren</strong><small>Optionales JSON-Endpunktformat: timestamp, temperature, precipitation, rainRate, gust, cloudCover.</small></span></header><div className="weather-twin-sensor-url"><input value={settings.privateSensorLabel} onChange={event=>patchSettings({privateSensorLabel:event.target.value})} placeholder="Sensorname"/><input value={settings.privateSensorUrl} onChange={event=>patchSettings({privateSensorUrl:event.target.value})} placeholder="https://…/current.json" inputMode="url"/><button type="button" disabled={sensorBusy||!settings.privateSensorUrl} onClick={()=>{setSensorBusy(true);fetchPrivateSensorObservation(locationKey).then(ok=>{setSensorMessage(ok?'Sensor aktualisiert.':'Keine Messung übernommen.');refreshReport()}).catch(reason=>setSensorMessage(reason instanceof Error?reason.message:String(reason))).finally(()=>setSensorBusy(false))}}>{sensorBusy?<RefreshCw className="spin" size={15}/>:<RefreshCw size={15}/>}Abrufen</button></div><form onSubmit={manualSubmit}><input type="number" step="0.1" value={manualSensor.temperature??''} onChange={event=>sensorNumber('temperature',event.target.value)} placeholder="Temperatur °C"/><input type="number" step="0.1" min="0" value={manualSensor.precipitation??''} onChange={event=>sensorNumber('precipitation',event.target.value)} placeholder="Niederschlag mm"/><input type="number" step="0.1" min="0" value={manualSensor.gust??''} onChange={event=>sensorNumber('gust',event.target.value)} placeholder="Böe kt"/><button type="submit">Messung speichern</button></form>{sensorMessage&&<small>{sensorMessage}</small>}</section>
  {!report.days?<div className="forecast-verification-empty"><BarChart3 size={24}/><strong>Noch keine abgeschlossenen Vergleichstage</strong><span>Ab jetzt speichert MID unveränderliche Prognosestände, lokale Mess-/Analysesnapshots und nachträgliche Referenzen. Erste segmentierte Lerngewichte entstehen nach mehreren abgeschlossenen Fällen.</span></div>:<>
   <div className="forecast-verification-kpis"><article><Thermometer/><small>Temperaturfehler Best Match</small><strong>{Number.isFinite(report.temperatureMae)?`${formatDecimal(report.temperatureMae!,1,1)} K`:'–'}</strong></article><article><CloudRain/><small>Regenwahrscheinlichkeit</small><strong>{rainReliability}</strong></article><article><Target/><small>Bestes Einzelmodell</small><strong>{best?.label??'–'}</strong><em>{best?qualityLabel(best.score):''}</em></article><article><Scale/><small>MID-Gewichtung gegen Best Match</small><strong>{weightedGain}</strong><em>{Number.isFinite(report.weightedScore)?`MID ${formatDecimal(report.weightedScore!,2,2)} · Best Match ${formatDecimal(report.bestMatchScore!,2,2)} · Mittel ${formatDecimal(report.equalWeightedScore??NaN,2,2)}`:'Kontrollvergleich startet nach gespeicherten Lernprognosen'}</em></article></div>
   <section className="weather-twin-parameters"><header><Activity size={19}/><span><strong>Parametergetrennte Modellgüte</strong><small>Kein pauschaler Modellsieger: Temperatur, Regen, Böen und Sonne werden separat bewertet.</small></span></header><div>{(['temperature','precipitation','probability','gust','sunshine'] as ForecastParameter[]).map(parameter=>{const leader=report.parameterLeaders[parameter],metric=leader?.parameterMetrics[parameter];return <article key={parameter}><small>{parameterLabel(parameter)}</small><strong>{leader?.label??'noch offen'}</strong><span>{metric?`${metric.samples} Fälle · Fehler ${formatDecimal(metric.error,parameter==='probability'?2:1,parameter==='probability'?2:1)}`:'zu wenige Vergleichsfälle'}</span></article>})}</div></section>
   {latest&&<article className="forecast-day-review"><header><strong>{dayLabel(latest.date)}</strong><small>{weatherRegimeLabel(latest.regime)} · +{latest.horizon} h</small></header><div><span><b>Best Match</b>{latest.bestMatch?`${Math.round(latest.bestMatch.min)}–${Math.round(latest.bestMatch.max)} °C · ${formatDecimal(latest.bestMatch.precipitation,1,1)} mm · ${Math.round(latest.bestMatch.probability)} % Regen`:'nicht gespeichert'}</span><span><b>Referenz</b>{Math.round(latest.reference.min)}–{Math.round(latest.reference.max)} °C · {formatDecimal(latest.reference.precipitation,1,1)} mm<small>{latest.reference.source}</small></span><span><b>Tagessieger</b>{latest.winner?.label??'noch nicht bestimmbar'}{latest.localWeighted&&<small>MID lokal gewichtet war für diesen Stand prüfbar.</small>}</span></div></article>}
   <div className="forecast-segment-quality"><header><strong>Güte nach Wetterlage und Horizont</strong><small>Nur Segmente mit mindestens zwei auswertbaren Fällen.</small></header><div>{segments.map(segment=><article key={`${segment.regime}:${segment.horizon}`}><span><b>{weatherRegimeLabel(segment.regime)}</b><small>+{segment.horizon} h · {segment.days} Fälle</small></span><strong>{segment.bestModel?.label??'–'}</strong><em>{segment.bestModel?`Score ${formatDecimal(segment.bestModel.score,2,2)}`:'noch offen'}</em></article>)}</div></div>
   <section className="weather-twin-calibration"><header><ShieldCheck size={19}/><span><strong>Kalibrierung der Regenwahrscheinlichkeit</strong><small>Vorhersagehäufigkeit gegen tatsächlich eingetretenen Niederschlag.</small></span></header><div>{report.calibrations.length?report.calibrations.map(bin=><article key={bin.lower}><b>{bin.lower}–{bin.upper} %</b><span>prognostiziert Ø {Math.round(bin.forecastMean)} %</span><strong>eingetreten {Math.round(bin.observedFrequency)} %</strong><small>{bin.samples} Fälle · kalibriert {Math.round(bin.calibrated)} %</small></article>):<p>Noch keine ausreichend belegten Wahrscheinlichkeitsklassen.</p>}</div></section>
   <div className="forecast-model-ranking"><header><strong>Lokale Modellgüte insgesamt</strong><small>Niedrigerer Gesamtscore ist besser; Detailsegmente können andere Sieger haben.</small></header>{ranking.map((row,index)=><article key={row.id}><b>{index+1}</b><span><strong>{row.label}</strong><small>{row.days} Vergleiche · Temp. {formatDecimal(row.temperatureMae,1,1)} K · Regen {formatDecimal(row.precipitationMae,1,1)} mm · Brier {formatDecimal(row.brier,2,2)} · Vertrauen {confidenceLabel(row.confidence)}</small></span><em>{formatDecimal(row.score,2,2)}</em></article>)}</div>
   <div className="forecast-local-weights"><header><strong>Lokale Modellgewichtung · aktuelle Prognose</strong><small>{report.weightingReady?'Gewichte, Bias und Kalibrierung werden je Wetterlage und Vorhersagehorizont berechnet und gegen zwei Kontrollprognosen geprüft.':'Vorläufig – mindestens fünf Vergleichstage und zwei Modelle sind erforderlich.'}</small></header><div className="forecast-weighted-days">{report.currentForecasts.map((item,index)=><article key={item.date} className={item.ready?'ready':'pending'}><header><b>{dayLabel(item.date)}</b><small>{weatherRegimeLabel(item.regime)} · +{item.horizon} h · Vertrauen {confidenceLabel(item.confidence)}</small></header>{item.prediction?<strong>{Math.round(item.prediction.min)}–{Math.round(item.prediction.max)} °C · {formatDecimal(item.prediction.precipitation,1,1)} mm · {Math.round(item.prediction.probability)} % Regen</strong>:<strong>Noch nicht aktiv</strong>}<div>{item.weights.slice(0,4).map(weight=><span key={weight.id}><b>{Math.round(weight.weight)} %</b>{weight.label}</span>)}</div>{item.explanations.map(text=><small key={text}>{text}</small>)}{settings.useAsMainForecast&&item.prediction&&<em>In der Hauptprognose: {Math.round(activeDays[index]?.min??item.prediction.min)}–{Math.round(activeDays[index]?.max??item.prediction.max)} °C</em>}</article>)}</div></div>
  </>}
  <section className="weather-twin-personal"><header><CheckCircle2 size={19}/><span><strong>Persönlicher Entscheidungszwilling</strong><small>Optimale Zeitfenster und Auswirkungen werden getrennt vom meteorologischen Kern bewertet.</small></span><label><input type="checkbox" checked={settings.personalRecommendations} onChange={event=>patchSettings({personalRecommendations:event.target.checked})}/>aktiv</label></header><div className="weather-twin-activity-toggles">{(Object.keys(settings.activities) as TwinActivity[]).map(activity=><label key={activity}><input type="checkbox" checked={settings.activities[activity].enabled} onChange={event=>patchActivity(activity,event.target.checked)}/>{activityLabel(activity)}</label>)}</div>{settings.personalRecommendations&&<div className="weather-twin-recommendations">{recommendations.length?recommendations.map(item=><article key={item.id} className={item.assessment}><header><strong>{item.title}</strong><em>{item.window||'kein belastbares Fenster'}</em></header><b>{item.assessment==='good'?'günstig':item.assessment==='limited'?'eingeschränkt':'ungünstig'} · {Math.round(item.score)}/100</b><ul>{item.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul><footer><small>Vertrauen {confidenceLabel(item.confidence)}</small><button type="button" onClick={()=>recordTwinRecommendationFeedback(locationKey,item.id,true)} title="Empfehlung war hilfreich"><ThumbsUp size={14}/></button><button type="button" onClick={()=>recordTwinRecommendationFeedback(locationKey,item.id,false)} title="Empfehlung war nicht passend"><ThumbsDown size={14}/></button></footer></article>):<p>Noch kein geeignetes zukünftiges Stundenfenster verfügbar.</p>}</div>}</section>
 </section>
}
