import type {Day,EnsembleDay,Location} from './weather';

const PREFIX='mid:forecast-verification:v2:';
const LEGACY_PREFIX='mid:forecast-verification:v1:';
const MAX_CAPTURES=360;
const HORIZONS=[12,24,48,72] as const;
export type ForecastHorizon=typeof HORIZONS[number];
export type WeatherRegime='hochdruck'|'wechselhaft'|'schauer'|'dauerregen'|'gewitter'|'sturm'|'winterlich';
export type ForecastPrediction={id:string;label:string;max:number;min:number;precipitation:number;probability:number};
export type ForecastCapture={targetDate:string;issuedAt:string;leadHours:number;predictedRegime?:WeatherRegime;predictions:ForecastPrediction[]};
export type ForecastReference={date:string;max:number;min:number;precipitation:number;source:string;weatherCode?:number;gust?:number;sunshineDuration?:number;regime:WeatherRegime};
type Store={version:2;updatedAt:string;captures:ForecastCapture[];references:ForecastReference[]};
export type ForecastModelScore={id:string;label:string;days:number;temperatureMae:number;precipitationMae:number;brier:number;score:number;weight:number};
export type ForecastSegmentScore={regime:WeatherRegime;horizon:ForecastHorizon;days:number;models:ForecastModelScore[];bestModel?:ForecastModelScore};
export type ForecastDayReview={date:string;issuedAt:string;leadHours:number;horizon:ForecastHorizon;regime:WeatherRegime;reference:ForecastReference;bestMatch?:ForecastPrediction;localWeighted?:ForecastPrediction;winner?:ForecastModelScore};
export type LocalWeightedForecast={date:string;horizon:ForecastHorizon;regime:WeatherRegime;prediction?:ForecastPrediction;weights:{id:string;label:string;weight:number}[];ready:boolean;reason:string};
export type ForecastVerificationReport={days:number;samples:number;models:ForecastModelScore[];segments:ForecastSegmentScore[];reviews:ForecastDayReview[];bestModel?:ForecastModelScore;rainBrier?:number;temperatureMae?:number;weightingReady:boolean;weightedScore?:number;bestMatchScore?:number;weightedImprovement?:number;currentForecasts:LocalWeightedForecast[]};

type Evaluation={date:string;capture:ForecastCapture;reference:ForecastReference;horizon:ForecastHorizon;regime:WeatherRegime};
type RawStat={id:string;label:string;days:number;temp:number;rain:number;brier:number};

function finite(value:unknown,fallback=0){const number=Number(value);return Number.isFinite(number)?number:fallback}
function storeKey(locationKey:string){return`${PREFIX}${locationKey}`}
function legacyStoreKey(locationKey:string){return`${LEGACY_PREFIX}${locationKey}`}
function emptyStore():Store{return{version:2,updatedAt:new Date().toISOString(),captures:[],references:[]}}
function inferRegime(value:{weatherCode?:number;precipitation:number;gust?:number;sunshineDuration?:number;min?:number}){const code=Math.round(finite(value.weatherCode,0)),precipitation=Math.max(0,finite(value.precipitation)),gust=finite(value.gust,0),sunshine=finite(value.sunshineDuration,NaN),minimum=finite(value.min,10);if([95,96,97,99].includes(code))return'gewitter' as const;if(gust>=34)return'sturm' as const;if([71,73,75,77,85,86].includes(code)||(minimum<=1&&precipitation>=.2))return'winterlich' as const;if(precipitation>=5||[63,65].includes(code))return'dauerregen' as const;if([51,53,55,61,80,81,82].includes(code)||precipitation>=.5)return'schauer' as const;if(Number.isFinite(sunshine)&&sunshine>=7*3600&&precipitation<.2||[0,1].includes(code)&&precipitation<.2)return'hochdruck' as const;return'wechselhaft' as const}
export function weatherRegimeLabel(regime:WeatherRegime){return({hochdruck:'Hochdruck / sonnig',wechselhaft:'wechselhaft',schauer:'Schauerlage',dauerregen:'Dauerregenlage',gewitter:'Gewitterlage',sturm:'Sturmlage',winterlich:'winterliche Lage'} as Record<WeatherRegime,string>)[regime]}
function migrateStore(value:any):Store{const source=value&&Array.isArray(value.captures)&&Array.isArray(value.references)?value:emptyStore();return{version:2,updatedAt:String(source.updatedAt||new Date().toISOString()),captures:source.captures.map((capture:any)=>({...capture,predictions:Array.isArray(capture.predictions)?capture.predictions:[]})).filter((capture:ForecastCapture)=>capture.targetDate&&capture.issuedAt),references:source.references.map((reference:any)=>{const row={...reference,max:finite(reference.max,NaN),min:finite(reference.min,NaN),precipitation:Math.max(0,finite(reference.precipitation,NaN)),source:String(reference.source||'Rückblick')} as ForecastReference;row.regime=reference.regime||inferRegime(row);return row}).filter((row:ForecastReference)=>row.date&&[row.max,row.min,row.precipitation].every(Number.isFinite))}}
function readStore(locationKey:string):Store{try{const current=localStorage.getItem(storeKey(locationKey)),legacy=current?null:localStorage.getItem(legacyStoreKey(locationKey)),parsed=JSON.parse(current||legacy||'null'),store=migrateStore(parsed);if(!current&&legacy)saveStore(locationKey,store);return store}catch{return emptyStore()}}
function saveStore(locationKey:string,store:Store){try{localStorage.setItem(storeKey(locationKey),JSON.stringify({...store,version:2,updatedAt:new Date().toISOString(),captures:store.captures.slice(-MAX_CAPTURES),references:store.references.slice(-90)}))}catch{}}
function dateNoon(date:string){const match=date.match(/^(\d{4})-(\d{2})-(\d{2})$/);return match?Date.UTC(Number(match[1]),Number(match[2])-1,Number(match[3]),12):NaN}
function horizonBucket(leadHours:number):ForecastHorizon{return leadHours<=18?12:leadHours<=36?24:leadHours<=60?48:72}
function predictionValid(row:ForecastPrediction){return row.id&&row.label&&[row.max,row.min,row.precipitation,row.probability].every(Number.isFinite)}
function bestMatchPrediction(day:Day):ForecastPrediction{return{id:'best_match',label:'Open-Meteo Best Match',max:finite(day.max),min:finite(day.min),precipitation:Math.max(0,finite(day.precipitation)),probability:Math.max(0,Math.min(100,finite(day.probability)))}}
function predictedRegime(day:Day):WeatherRegime{return inferRegime({weatherCode:day.code,precipitation:day.precipitation,gust:day.gust,sunshineDuration:day.sunshineDuration,min:day.min})}
function predictionDayScore(prediction:ForecastPrediction,reference:ForecastReference){const temperature=(Math.abs(prediction.max-reference.max)+Math.abs(prediction.min-reference.min))/2,precipitation=Math.abs(prediction.precipitation-reference.precipitation),observed=reference.precipitation>=.1?1:0,probability=Math.max(0,Math.min(1,prediction.probability/100)),brier=(probability-observed)**2;return temperature+Math.min(4,precipitation*.35)+brier*3}
function chosenEvaluations(store:Store,beforeDate?:string){const today=new Date().toISOString().slice(0,10),references=new Map(store.references.filter(row=>!beforeDate||row.date<beforeDate).map(row=>[row.date,row])),byKey=new Map<string,ForecastCapture[]>();for(const capture of store.captures){if(capture.targetDate>=today||beforeDate&&capture.targetDate>=beforeDate||!references.has(capture.targetDate))continue;const horizon=horizonBucket(capture.leadHours),key=`${capture.targetDate}:${horizon}`,list=byKey.get(key)??[];list.push(capture);byKey.set(key,list)}const evaluations:Evaluation[]=[];for(const[key,list]of byKey){const[date,horizonText]=key.split(':'),horizon=Number(horizonText) as ForecastHorizon,capture=[...list].sort((a,b)=>Math.abs(a.leadHours-horizon)-Math.abs(b.leadHours-horizon))[0],reference=references.get(date);if(reference)evaluations.push({date,capture,reference,horizon,regime:reference.regime})}return evaluations.sort((a,b)=>b.date.localeCompare(a.date)||a.horizon-b.horizon)}
function statsFor(evaluations:Evaluation[],filter?:(evaluation:Evaluation)=>boolean){const stats=new Map<string,RawStat>();for(const evaluation of evaluations){if(filter&&!filter(evaluation))continue;for(const prediction of evaluation.capture.predictions){const stat=stats.get(prediction.id)??{id:prediction.id,label:prediction.label,days:0,temp:0,rain:0,brier:0},observed=evaluation.reference.precipitation>=.1?1:0,probability=Math.max(0,Math.min(1,prediction.probability/100));stat.days++;stat.temp+=(Math.abs(prediction.max-evaluation.reference.max)+Math.abs(prediction.min-evaluation.reference.min))/2;stat.rain+=Math.abs(prediction.precipitation-evaluation.reference.precipitation);stat.brier+=(probability-observed)**2;stats.set(prediction.id,stat)}}return[...stats.values()].map(row=>{const temperatureMae=row.temp/row.days,precipitationMae=row.rain/row.days,brier=row.brier/row.days,score=temperatureMae+Math.min(4,precipitationMae*.35)+brier*3;return{id:row.id,label:row.label,days:row.days,temperatureMae,precipitationMae,brier,score,weight:0} satisfies ForecastModelScore}).sort((a,b)=>a.score-b.score)}
function regularizedWeights(evaluations:Evaluation[],regime:WeatherRegime,horizon:ForecastHorizon,beforeDate?:string){const eligibleEvaluations=evaluations.filter(item=>(!beforeDate||item.date<beforeDate)),global=statsFor(eligibleEvaluations).filter(row=>!['best_match','mid_local_weighted'].includes(row.id)),segment=statsFor(eligibleEvaluations,item=>item.regime===regime&&item.horizon===horizon).filter(row=>!['best_match','mid_local_weighted'].includes(row.id)),globalById=new Map(global.map(row=>[row.id,row])),segmentById=new Map(segment.map(row=>[row.id,row])),ids=[...new Set([...global.map(row=>row.id),...segment.map(row=>row.id)])],weighted=ids.map(id=>{const globalRow=globalById.get(id),segmentRow=segmentById.get(id),days=segmentRow?.days??0,globalScore=globalRow?.score??8,score=((segmentRow?.score??globalScore)*days+globalScore*4)/(days+4);return{id,label:segmentRow?.label??globalRow?.label??id,days:Math.max(days,globalRow?.days??0),score,raw:1/Math.max(.35,score)}}).filter(row=>row.days>=2).sort((a,b)=>a.score-b.score);if(weighted.length<2||eligibleEvaluations.length<5)return[];const total=weighted.reduce((sum,row)=>sum+row.raw,0)||1;let normalized=weighted.map(row=>({...row,weight:100*row.raw/total}));const maxWeight=Math.max(...normalized.map(row=>row.weight));if(maxWeight>58){const excess=maxWeight-58,leader=normalized.find(row=>row.weight===maxWeight)!;leader.weight=58;const others=normalized.filter(row=>row!==leader),otherTotal=others.reduce((sum,row)=>sum+row.weight,0)||1;for(const row of others)row.weight+=excess*row.weight/otherTotal}return normalized}
function weightedPrediction(predictions:ForecastPrediction[],weights:{id:string;weight:number}[]):ForecastPrediction|undefined{const byId=new Map(predictions.map(row=>[row.id,row])),usable=weights.map(weight=>({weight,prediction:byId.get(weight.id)})).filter(row=>row.prediction) as {weight:{id:string;weight:number};prediction:ForecastPrediction}[],total=usable.reduce((sum,row)=>sum+row.weight.weight,0);if(usable.length<2||total<=0)return undefined;const mean=(selector:(prediction:ForecastPrediction)=>number)=>usable.reduce((sum,row)=>sum+selector(row.prediction)*row.weight.weight,0)/total;return{id:'mid_local_weighted',label:'MID lokal gewichtet',max:mean(row=>row.max),min:mean(row=>row.min),precipitation:Math.max(0,mean(row=>row.precipitation)),probability:Math.max(0,Math.min(100,mean(row=>row.probability)))}}
function currentPredictions(day:Day,row:EnsembleDay|undefined){return[bestMatchPrediction(day),...(row?.modelSummaries??[]).map(model=>({id:model.id,label:model.label,max:model.max,min:model.min,precipitation:model.precipitation,probability:model.precipitationProbability}))].filter(predictionValid)}
export function recordForecastCapture(locationKey:string,days:Day[],ensemble:EnsembleDay[]){if(!locationKey||!days.length)return;const now=Date.now(),slot=Math.floor(now/(3*3600000)),store=readStore(locationKey),ensembleByDate=new Map(ensemble.map(row=>[row.date,row])),historical=chosenEvaluations(store);for(const day of days.slice(0,3)){const target=dateNoon(day.date),leadHours=(target-now)/3600000;if(!Number.isFinite(leadHours)||leadHours<-12||leadHours>84)continue;const regime=predictedRegime(day),horizon=horizonBucket(leadHours),predictions=currentPredictions(day,ensembleByDate.get(day.date)),weights=regularizedWeights(historical,regime,horizon,day.date),local=weightedPrediction(predictions,weights);if(local)predictions.push(local);const signature=`${day.date}:${slot}`,index=store.captures.findIndex(item=>`${item.targetDate}:${Math.floor(Date.parse(item.issuedAt)/(3*3600000))}`===signature),capture={targetDate:day.date,issuedAt:new Date(now).toISOString(),leadHours,predictedRegime:regime,predictions};if(index>=0)store.captures[index]=capture;else store.captures.push(capture)}saveStore(locationKey,store)}
function referenceRows(data:any,source:string){const daily=data?.daily??{},times=Array.isArray(daily.time)?daily.time:[];return times.map((date:string,index:number)=>{const row={date:String(date),max:finite(daily.temperature_2m_max?.[index],NaN),min:finite(daily.temperature_2m_min?.[index],NaN),precipitation:Math.max(0,finite(daily.precipitation_sum?.[index],NaN)),weatherCode:finite(daily.weather_code?.[index],NaN),gust:finite(daily.wind_gusts_10m_max?.[index],NaN),sunshineDuration:finite(daily.sunshine_duration?.[index],NaN),source} as ForecastReference;row.regime=inferRegime(row);return row}).filter((row:ForecastReference)=>[row.max,row.min,row.precipitation].every(Number.isFinite)) as ForecastReference[]}
function utcDateOffset(days:number){const date=new Date(Date.now()+days*86400000);return date.toISOString().slice(0,10)}
const REFERENCE_DAILY='temperature_2m_max,temperature_2m_min,precipitation_sum,weather_code,wind_gusts_10m_max,sunshine_duration';
async function retrospectiveBestMatchRequest(location:Location,signal?:AbortSignal){const params=new URLSearchParams({latitude:String(location.latitude),longitude:String(location.longitude),timezone:'auto',past_days:'30',forecast_days:'1',models:'best_match',wind_speed_unit:'kn',daily:REFERENCE_DAILY}),response=await fetch(`https://api.open-meteo.com/v1/forecast?${params}`,{signal,cache:'no-store'});if(!response.ok)throw new Error(`Open-Meteo Rückblick HTTP ${response.status}`);return referenceRows(await response.json(),'Open-Meteo Best-Match-Rückblick')}
async function reanalysisReferenceRequest(location:Location,signal?:AbortSignal){const params=new URLSearchParams({latitude:String(location.latitude),longitude:String(location.longitude),timezone:'auto',start_date:utcDateOffset(-45),end_date:utcDateOffset(-1),models:'era5_land',wind_speed_unit:'kn',daily:REFERENCE_DAILY});if(Number.isFinite(location.elevation))params.set('elevation',String(location.elevation));const response=await fetch(`https://archive-api.open-meteo.com/v1/archive?${params}`,{signal,cache:'no-store'});if(!response.ok)throw new Error(`Open-Meteo Reanalyse HTTP ${response.status}`);return referenceRows(await response.json(),'Open-Meteo ERA5-Land-Reanalyse')}
async function referenceRequest(location:Location,signal?:AbortSignal){const settled=await Promise.allSettled([retrospectiveBestMatchRequest(location,signal),reanalysisReferenceRequest(location,signal)]);if(signal?.aborted)throw new DOMException('Abgebrochen','AbortError');const fallback=settled[0].status==='fulfilled'?settled[0].value:[],reanalysis=settled[1].status==='fulfilled'?settled[1].value:[];if(!fallback.length&&!reanalysis.length){const messages=settled.filter((row):row is PromiseRejectedResult=>row.status==='rejected').map(row=>row.reason instanceof Error?row.reason.message:String(row.reason));throw new Error(messages.join(' · ')||'Kein Rückblick verfügbar.')}const merged=new Map(fallback.map(row=>[row.date,row]));for(const row of reanalysis)merged.set(row.date,row);return[...merged.values()].sort((a,b)=>a.date.localeCompare(b.date))}
export async function refreshForecastReferences(locationKey:string,location:Location,signal?:AbortSignal){const store=readStore(locationKey),rows=await referenceRequest(location,signal),byDate=new Map(store.references.map(row=>[row.date,row]));for(const row of rows)byDate.set(row.date,row);store.references=[...byDate.values()].sort((a,b)=>a.date.localeCompare(b.date)).slice(-90);saveStore(locationKey,store);return store}
function currentWeightedForecasts(days:Day[],ensemble:EnsembleDay[],evaluations:Evaluation[]):LocalWeightedForecast[]{const ensembleByDate=new Map(ensemble.map(row=>[row.date,row])),now=Date.now();return days.slice(0,3).map(day=>{const leadHours=(dateNoon(day.date)-now)/3600000,horizon=horizonBucket(leadHours),regime=predictedRegime(day),weights=regularizedWeights(evaluations,regime,horizon),prediction=weightedPrediction(currentPredictions(day,ensembleByDate.get(day.date)),weights),ready=Boolean(prediction);return{date:day.date,horizon,regime,prediction,weights:weights.map(row=>({id:row.id,label:row.label,weight:row.weight})),ready,reason:ready?'Aus lokaler Güte nach Wetterlage und Prognosehorizont abgeleitet.':'Noch zu wenige abgeschlossene Vergleichsfälle für dieses Segment.'}})}
export function buildForecastVerificationReport(locationKey:string,days:Day[]=[],ensemble:EnsembleDay[]=[]):ForecastVerificationReport{const store=readStore(locationKey),evaluations=chosenEvaluations(store).slice(0,160),raw=statsFor(evaluations),eligible=raw.filter(row=>row.days>=Math.min(5,Math.max(2,evaluations.length))),inverse=eligible.filter(row=>!['best_match','mid_local_weighted'].includes(row.id)).reduce((sum,row)=>sum+1/Math.max(.25,row.score),0);for(const row of raw)row.weight=inverse&&!['best_match','mid_local_weighted'].includes(row.id)&&eligible.includes(row)?100*(1/Math.max(.25,row.score))/inverse:0;const segments:ForecastSegmentScore[]=[];for(const regime of['hochdruck','wechselhaft','schauer','dauerregen','gewitter','sturm','winterlich'] as WeatherRegime[])for(const horizon of HORIZONS){const matching=evaluations.filter(item=>item.regime===regime&&item.horizon===horizon),models=statsFor(matching);if(matching.length)segments.push({regime,horizon,days:matching.length,models,bestModel:models.find(row=>!['best_match','mid_local_weighted'].includes(row.id))??models[0]})}segments.sort((a,b)=>b.days-a.days||a.horizon-b.horizon);const reviews:ForecastDayReview[]=evaluations.slice(0,30).map(evaluation=>{const winner=[...evaluation.capture.predictions].sort((a,b)=>predictionDayScore(a,evaluation.reference)-predictionDayScore(b,evaluation.reference))[0];return{date:evaluation.date,issuedAt:evaluation.capture.issuedAt,leadHours:evaluation.capture.leadHours,horizon:evaluation.horizon,regime:evaluation.regime,reference:evaluation.reference,bestMatch:evaluation.capture.predictions.find(row=>row.id==='best_match'),localWeighted:evaluation.capture.predictions.find(row=>row.id==='mid_local_weighted'),winner:winner?raw.find(score=>score.id===winner.id):undefined}}),bestMatch=raw.find(row=>row.id==='best_match'),weighted=raw.find(row=>row.id==='mid_local_weighted'),currentForecasts=currentWeightedForecasts(days,ensemble,evaluations),uniqueDays=new Set(evaluations.map(item=>item.date)).size;return{days:uniqueDays,samples:evaluations.length,models:raw,segments,reviews,bestModel:raw.find(row=>!['best_match','mid_local_weighted'].includes(row.id))??raw[0],rainBrier:bestMatch?.brier,temperatureMae:bestMatch?.temperatureMae,weightingReady:uniqueDays>=5&&eligible.filter(row=>!['best_match','mid_local_weighted'].includes(row.id)).length>=2,weightedScore:weighted?.score,bestMatchScore:bestMatch?.score,weightedImprovement:weighted&&bestMatch?100*(bestMatch.score-weighted.score)/Math.max(.1,bestMatch.score):undefined,currentForecasts}}
