import {useEffect,useId,useMemo,useRef,useState,type CSSProperties,type ReactNode} from 'react';
import {ChevronDown,ChevronUp,Clock3,Droplets,Info,SlidersHorizontal,ThermometerSun,Wind} from 'lucide-react';
import {DWD_WIND_THRESHOLDS_KMH} from './dwdWarnings';
import {formatDecimalFixed} from './format';
import {WeatherPictogram,weatherPictogramKind} from './WeatherPictogram';
import {buildShortTermForecast,type ShortTermAnchor,type ShortTermForecastPoint} from './ShortTermForecast';
import {DwdPrecipitationTypeRadar} from './DwdPrecipitationTypeRadar';
import {currentIndex,dayPrecipitationAssessment,dayWeatherCharacter,dayWeatherCharacterText,label as weatherCodeLabel,precipitationDurationLabel,wind,type ClimateDay,type Day,type EnsembleDay,type EnsembleScenarioCluster,type Hour,type Location,type Minute15,type RadarNowcast,type WindUnit} from './weather';
import {precipitationParts} from './precipitation';
import {computeEnsembleConfidence} from './ensembleConfidence';
import {dailyTemperatureTone} from './temperatureTone';
import {dayPeriodHoursForDate,followingNightHoursForDate} from './forecastPeriods';

export type ForecastPresentationMode='classic'|'cockpit-tabs'|'cockpit-ribbons';
type ForecastHorizon='short-term'|'seven-day'|'fourteen-day';
type DayRegime='wet'|'showery'|'sunny'|'windy'|'warm'|'quiet';

type HorizonAvailability={
 shortTerm:boolean;
 sevenDay:boolean;
 fourteenDay:boolean;
};

type ForecastCockpitProps={
 mode:Exclude<ForecastPresentationMode,'classic'>;
 hours:Hour[];
 minutes15:Minute15[];
 days:Day[];
 ensemble:EnsembleDay[];
 scenarios:EnsembleScenarioCluster[];
 climate:ClimateDay[];
 timezone:string;
 unit:WindUnit;
 selectedDate:string;
 onSelectedDate:(date:string)=>void;
 availability:HorizonAvailability;
 sourceLabel:string;
 updatedLabel:string;
 ensembleLoading:boolean;
 cockpitDetails?:{sevenDay?:ReactNode;fourteenDay?:ReactNode};
 sevenDaySummary?:string;
 shortTermAnchor?:ShortTermAnchor;
 radarNowcast?:RadarNowcast;
 location:Location;
 showDwdPrecipitationTypeRadar:boolean;
 advancedMode:boolean;
};

const ACTIVE_HORIZON_KEY='mid:forecastCockpit:activeHorizon';
const HORIZONS:ForecastHorizon[]=['short-term','seven-day','fourteen-day'];
const KMH_PER_KT=1.852;

function clamp(value:number,minimum:number,maximum:number){return Math.min(maximum,Math.max(minimum,value))}
function formatDate(date:string,options:Intl.DateTimeFormatOptions){try{return new Intl.DateTimeFormat('de-DE',{...options,timeZone:'UTC'}).format(new Date(`${date}T12:00:00Z`))}catch{return date}}
function formatClock(epoch:number,timezone:string){try{return new Intl.DateTimeFormat('de-DE',{hour:'2-digit',minute:'2-digit',timeZone:timezone}).format(new Date(epoch))}catch{return new Date(epoch).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}}
function dateOnlyFromEpoch(epoch:number,timezone:string){try{const parts=new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:timezone}).formatToParts(new Date(epoch)),get=(type:string)=>parts.find(part=>part.type===type)?.value;return`${get('year')}-${get('month')}-${get('day')}`}catch{return new Date(epoch).toISOString().slice(0,10)}}
function cardinal(direction:number){const labels=['N','NO','O','SO','S','SW','W','NW'];return labels[Math.round((((direction%360)+360)%360)/45)%8]}
function flowDirection(fromDirection:number){return((fromDirection%360)+540)%360}
function plausiblePrecipitation(sample:Hour|Minute15){return precipitationParts(sample as Hour)}
function precipitationColor(sample:Hour|Minute15){const parts=plausiblePrecipitation(sample);if(['snow','snowShowers','snowGrains'].includes(parts.type))return'#66bce8';if(['thunderstorm','thunderstormHail'].includes(parts.type))return'#7869e8';if(['freezingRain','freezingDrizzle','sleet','sleetShowers'].includes(parts.type))return'#a769d8';return'#2697d8'}
function shortTermPrecipitationParts(point:Pick<ShortTermForecastPoint,'precipitation'|'probability'|'code'|'temperature'|'dewPoint'|'humidity'|'cloud'|'lowCloud'>){return precipitationParts({precipitation:point.precipitation,rain:point.precipitation,showers:0,snowfall:0,probability:point.probability,code:point.code,temperature:point.temperature,dewPoint:point.dewPoint,humidity:point.humidity,cloud:point.cloud,lowCloud:point.lowCloud})}
function shortTermVisibilityLabel(visibility:number){if(!Number.isFinite(visibility))return'–';if(visibility>=10000)return`${Math.round(visibility/1000)} km`;if(visibility>=1000)return`${formatDecimalFixed(visibility/1000,1)} km`;return`${Math.round(visibility)} m`}
function shortTermEstimatedPrecipitationDuration(point:Pick<ShortTermForecastPoint,'precipitation'|'probability'|'intervalLabel'>){const intervalMinutes=point.intervalLabel==='15 min'?15:point.intervalLabel==='3 h'?180:60,wetSignal=point.precipitation>=.05||point.probability>=20;if(!wetSignal)return'0 min';const estimated=Math.max(point.precipitation>=.05?Math.round(intervalMinutes*.25):0,Math.round(intervalMinutes*clamp(point.probability,0,100)/100));const rounded=Math.min(intervalMinutes,Math.max(point.precipitation>=.1?15:5,Math.round(estimated/5)*5));return`${rounded} min`}
function shortTermThunderRiskLabel(point:Pick<ShortTermForecastPoint,'thunderPercent'>){const percent=Math.round(Number(point.thunderPercent)||0);return percent>=70?`hoch · ${percent} %`:percent>=40?`erhöht · ${percent} %`:percent>=15?`gering · ${percent} %`:'gering'}
function shortTermPrecipitationDetail(point:Pick<ShortTermForecastPoint,'precipitation'|'probability'|'code'|'temperature'|'dewPoint'|'humidity'|'cloud'|'lowCloud'|'intervalLabel'>){const parts=shortTermPrecipitationParts(point),duration=shortTermEstimatedPrecipitationDuration(point);return`${formatDecimalFixed(point.precipitation,1)} mm · ${Math.round(point.probability)} % · ${parts.weatherLabel} · ${duration}`}
function shortTermWindDetail(point:Pick<ShortTermForecastPoint,'direction'|'wind'|'gust'>,unit:WindUnit){return`${cardinal(point.direction)} · ${wind(point.wind,unit)} · Böen ${wind(point.gust,unit)}`}
function windWarningLevel(gustKt:number){const kmh=gustKt*KMH_PER_KT;let level=0;for(const threshold of DWD_WIND_THRESHOLDS_KMH)if(kmh>=threshold.threshold)level=Math.max(level,threshold.level);return level}
function compactGustLabel(gustKt:number,unit:WindUnit){if(!Number.isFinite(gustKt))return'G–';if(unit==='kmh')return`G${Math.round(gustKt*KMH_PER_KT)} km/h`;if(unit==='ms')return`G${Math.round(gustKt*.514444)} m/s`;if(unit==='mph')return`G${Math.round(gustKt*1.15078)} mph`;return`G${Math.round(gustKt)} kt`}
function consistencyColor(value:number){const score=clamp(value,0,100),stops=[{v:0,c:[232,54,54]},{v:25,c:[244,125,48]},{v:50,c:[242,201,76]},{v:70,c:[199,214,54]},{v:85,c:[100,190,65]},{v:100,c:[45,193,90]}];let a=stops[0],b=stops[stops.length-1];for(let index=0;index<stops.length-1;index++)if(score>=stops[index].v&&score<=stops[index+1].v){a=stops[index];b=stops[index+1];break}const ratio=(score-a.v)/Math.max(1,b.v-a.v),rgb=a.c.map((channel,index)=>Math.round(channel+(b.c[index]-channel)*ratio));return`rgb(${rgb[0]}, ${rgb[1]}, ${rgb[2]})`}
function readActiveHorizon(availability:HorizonAvailability){try{const stored=localStorage.getItem(ACTIVE_HORIZON_KEY) as ForecastHorizon|null;if(stored&&horizonAvailable(stored,availability))return stored}catch{}return availability.shortTerm?'short-term':availability.sevenDay?'seven-day':'fourteen-day'}
function horizonAvailable(horizon:ForecastHorizon,availability:HorizonAvailability){return horizon==='short-term'?availability.shortTerm:horizon==='seven-day'?availability.sevenDay:availability.fourteenDay}
function horizonTitle(horizon:ForecastHorizon){return horizon==='short-term'?'Kurzfrist':horizon==='seven-day'?'7 Tage':'14 Tage'}
function horizonIcon(horizon:ForecastHorizon){return horizon==='short-term'?<Clock3 size={17}/>:horizon==='seven-day'?<ThermometerSun size={17}/>:<SlidersHorizontal size={17}/>}

function shortTermHours(hours:Hour[]){
 if(!hours.length)return[];
 const current=Math.max(0,currentIndex(hours)),start=Math.min(current,hours.length-1),startEpoch=hours[start]?.epoch??Date.now();
 return hours.slice(start).filter(hour=>hour.epoch<=startEpoch+24*3600000).slice(0,25);
}

function regularShortTermPoints(hours:Hour[],stepHours:number){
 const samples=shortTermHours(hours);if(!samples.length)return[];
 const start=samples[0]?.epoch??0;
 return samples.filter((hour,index)=>index===0||index===samples.length-1||Math.abs(((hour.epoch-start)/3600000)%stepHours)<.01);
}


function shortTermSummary(hours:Hour[],timezone:string,unit:WindUnit){
 const samples=shortTermHours(hours);if(!samples.length)return'Kurzfristdaten werden geladen.';
 const wet=samples.filter(sample=>(sample.precipitation>=.05&&sample.probability>=25)||sample.probability>=60),gust=samples.reduce((best,item)=>item.gust>best.gust?item:best,samples[0]);
 const gustPart=`Böen bis ${wind(gust.gust,unit)} um ${formatClock(gust.epoch,timezone)}`;
 if(!wet.length)return `Trocken · ${gustPart}`;
 const first=wet[0],parts=plausiblePrecipitation(first),kind=parts.type==='showers'?'Schauer':parts.type==='thunderstorm'||parts.type==='thunderstormHail'?'Gewitter':parts.weatherLabel;
 return `${kind} ab ${formatClock(first.epoch,timezone)} · ${gustPart}`;
}
function shortTermPointSummary(points:ShortTermForecastPoint[],unit:WindUnit){
 if(!points.length)return'Kurzfristdaten werden geladen.';
 const wet=points.filter(point=>(point.precipitation>=.05&&point.probability>=25)||point.probability>=60),gust=points.reduce((best,item)=>item.gust>best.gust?item:best,points[0]),gustPart=`Böen bis ${wind(gust.gust,unit)} um ${gust.timeLabel}`;
 if(!wet.length)return `Bis auf Weiteres trocken · ${gustPart}`;
 const first=wet[0],kind=/schauer/i.test(first.weatherLabel)?'Schauer':/gewitter/i.test(first.weatherLabel)?'Gewitter':first.weatherLabel;
 return `${kind} voraussichtlich ab ${first.timeLabel} · ${gustPart}`;
}
function shortTermCompactWeatherLabel(label:string){
 return label.replace(/^Überwiegend\s+/i,'').replace(/^Teilweise\s+/i,'').replace(/^Leicht\s+/i,'').replace(/^Mäßig\s+/i,'');
}
function aggregateShortTermBlock(group:ShortTermForecastPoint[]){
 const first=group[0],representative=group.reduce((best,point)=>cockpitWeatherImpact({code:point.code,precipitation:point.precipitation,probability:point.probability} as Hour)>cockpitWeatherImpact({code:best.code,precipitation:best.precipitation,probability:best.probability} as Hour)?point:best,first),sum=(key:'precipitation')=>group.reduce((total,point)=>total+Math.max(0,Number(point[key])||0),0),maximum=(key:'probability'|'gust'|'wind'|'cloud'|'lowCloud')=>Math.max(...group.map(point=>Number(point[key])||0)),mean=(key:'temperature'|'apparent'|'humidity'|'dewPoint'|'pressure'|'wind'|'direction'|'visibility'|'midCloud'|'highCloud')=>{const values=group.map(point=>Number(point[key])).filter(Number.isFinite);return values.length?values.reduce((total,value)=>total+value,0)/values.length:Number(first[key])||0};
 return {...first,id:`${first.id}:agg3h`,timeLabel:`${first.timeLabel}–${group.at(-1)?.timeLabel??first.timeLabel}`,intervalLabel:'3 h',temperature:mean('temperature'),apparent:mean('apparent'),humidity:mean('humidity'),dewPoint:mean('dewPoint'),pressure:mean('pressure'),precipitation:sum('precipitation'),probability:maximum('probability'),code:representative.code,weatherLabel:representative.weatherLabel,wind:mean('wind'),gust:maximum('gust'),direction:mean('direction'),cloud:maximum('cloud'),lowCloud:maximum('lowCloud'),midCloud:mean('midCloud'),highCloud:mean('highCloud'),visibility:mean('visibility'),isDay:representative.isDay,localAdjustment:Math.max(...group.map(point=>point.localAdjustment||0)),thunderPercent:Math.max(...group.map(point=>Number(point.thunderPercent)||0)),radarMode:representative.radarMode,radarRateMmh:representative.radarRateMmh,radarWeight:representative.radarWeight,radarHitClass:representative.radarHitClass,radarNearestWetKm:representative.radarNearestWetKm,radarSiteSupport:Math.max(...group.map(point=>Number(point.radarSiteSupport)||0)),radarFrameCount:group.reduce((sum,point)=>sum+(Number(point.radarFrameCount)||0),0),radarSiteFrameCount:group.reduce((sum,point)=>sum+(Number(point.radarSiteFrameCount)||0),0),radarInterrupted:group.some(point=>point.radarInterrupted)} satisfies ShortTermForecastPoint;
}
function selectShortTermPoints(points:ShortTermForecastPoint[],resolution:'1h'|'3h'){
 if(!points.length)return[];
 const hourly=points.filter(point=>point.source==='hourly');
 if(resolution==='1h')return hourly;
 const first=points[0],groups:ShortTermForecastPoint[][]=[];
 for(let index=0;index<hourly.length;index+=3)groups.push(hourly.slice(index,index+3));
 const aggregated=groups.filter(group=>group.length).map(group=>group.length===1?group[0]:aggregateShortTermBlock(group)),last=hourly.at(-1),merged=[first,...aggregated,last].filter(Boolean) as ShortTermForecastPoint[];
 return merged.filter((point,index,array)=>array.findIndex(candidate=>candidate.epoch===point.epoch&&candidate.intervalLabel===point.intervalLabel)===index);
}

function dayRegime(day:Day,hours:Hour[]):DayRegime{
 const daytime=dayPeriodHoursForDate(day.date,hours),character=dayWeatherCharacter(day,daytime),assessment=dayPrecipitationAssessment(day,daytime),text=dayWeatherCharacterText(character).toLocaleLowerCase('de-DE');
 const sunny=/sonnig|heiter|freundlich/.test(text),cloudy=/bedeckt|stark bewölkt|meist bewölkt/.test(text),warm=day.max>=30,windy=day.wind>=15||(day.gust>=34&&day.wind>=10)||(day.gust>=42);
 if(assessment.showery&&assessment.dominant)return'showery';
 if(assessment.dominant||character.precipitationDominant)return'wet';
 if(windy&&!cloudy)return'windy';
 if(sunny&&warm)return'warm';
 if(sunny)return'sunny';
 if(windy)return'windy';
 return'quiet';
}
function regimeLabel(regime:DayRegime){return regime==='wet'?'Regen':regime==='showery'?'Schauer':regime==='sunny'?'Sonnig':regime==='windy'?'Wind':regime==='warm'?'Heiß':'Ruhig'}

function cockpitCloudMean(hours:Hour[],key:'cloud'|'lowCloud'|'midCloud'|'highCloud'){const values=hours.map(hour=>Number(hour[key])).filter(Number.isFinite);return values.length?values.reduce((sum,value)=>sum+value,0)/values.length:undefined}
function cockpitWeatherImpact(hour:Hour){const kind=weatherPictogramKind(hour.code);return(kind==='thunder'||kind==='thunder-hail'?100:kind==='showers'||kind==='snow-showers'?78:kind==='rain'||kind==='freezing-rain'||kind==='sleet'||kind==='snow'?68:kind==='drizzle'||kind==='freezing-drizzle'||kind==='snow-grains'?48:kind==='fog'||kind==='rime-fog'?42:kind==='cloudy'?28:kind==='partly-cloudy'?18:kind==='mostly-clear'?9:0)+Math.min(18,Math.max(0,hour.precipitation)*6)+Math.max(0,hour.probability)*.12}
function cockpitPeriodVisual(hours:Hour[],dayPeriod:boolean,fallbackCode:number,fallbackTitle:string){const pool=hours.filter(hour=>hour.isDay===dayPeriod),fallback=pool.length?pool:hours.filter(hour=>{const clock=Number(hour.time.slice(11,13));return dayPeriod?clock>=7&&clock<=18:clock<=6||clock>=19}),candidates=fallback.length?fallback:hours;if(!candidates.length)return{available:false,code:fallbackCode,title:fallbackTitle};const representative=candidates.reduce((best,hour)=>cockpitWeatherImpact(hour)>cockpitWeatherImpact(best)?hour:best,candidates[0]),code=representative.code;return{available:true,code,title:`${dayPeriod?'Tagsüber':'Nachts'}: ${weatherCodeLabel(code)||fallbackTitle}`,cloud:cockpitCloudMean(candidates,'cloud'),lowCloud:cockpitCloudMean(candidates,'lowCloud'),midCloud:cockpitCloudMean(candidates,'midCloud'),highCloud:cockpitCloudMean(candidates,'highCloud')}}
function regimeSymbol(regime:DayRegime){return regime==='wet'?'●':regime==='showery'?'◆':regime==='sunny'?'☀':regime==='windy'?'↝':regime==='warm'?'▲':'•'}

function shortTermFocusDate(hours:Hour[],timezone:string){const samples=shortTermHours(hours);return samples.length?dateOnlyFromEpoch(samples[0].epoch,timezone):''}
function ecmwfTemperatureTone(value:number){const stops:[number,[number,number,number]][]=[[-40,[49,54,149]],[-25,[63,117,181]],[-10,[116,178,216]],[0,[224,243,248]],[10,[255,235,153]],[20,[253,174,97]],[30,[239,93,62]],[40,[165,15,38]]],temperature=Number(value),mix=(left:[number,number,number],right:[number,number,number],ratio:number)=>left.map((channel,index)=>Math.round(channel+(right[index]-channel)*ratio)) as [number,number,number];let rgb=stops[0][1];for(let index=1;index<stops.length;index+=1){if(temperature<=stops[index][0]){const[left,leftRgb]=stops[index-1],[right,rightRgb]=stops[index];rgb=mix(leftRgb,rightRgb,Math.max(0,Math.min(1,(temperature-left)/(right-left))));break}rgb=stops[index][1]}const channels=rgb.join(','),background=`linear-gradient(180deg,rgba(${channels},.18),rgba(${channels},.08))`;return{background,border:`rgba(${channels},.34)`,color:'var(--text)',title:`ECMWF-orientierte 2-m-Temperaturfarbskala · ${Math.round(temperature)} °C`}}
function ecmwfTemperatureLineColor(value:number){const stops:[number,[number,number,number]][]=[[-40,[49,54,149]],[-25,[63,117,181]],[-10,[116,178,216]],[0,[224,243,248]],[10,[255,235,153]],[20,[253,174,97]],[30,[239,93,62]],[40,[165,15,38]]],temperature=Number(value),mix=(left:[number,number,number],right:[number,number,number],ratio:number)=>left.map((channel,index)=>Math.round(channel+(right[index]-channel)*ratio)) as [number,number,number];let rgb=stops[0][1];for(let index=1;index<stops.length;index+=1){if(temperature<=stops[index][0]){const[left,leftRgb]=stops[index-1],[right,rightRgb]=stops[index];rgb=mix(leftRgb,rightRgb,Math.max(0,Math.min(1,(temperature-left)/(right-left))));break}rgb=stops[index][1]}return`rgb(${rgb.join(' ')})`}

function shortTermTickStep(range:number){if(range<=8)return 2;if(range<=16)return 4;if(range<=24)return 6;return 8}
function shortTermTickValues(minimum:number,maximum:number){const step=shortTermTickStep(Math.max(1,maximum-minimum)),start=Math.floor(minimum/step)*step,end=Math.ceil(maximum/step)*step,values:number[]=[];for(let value=end;value>=start;value-=step)values.push(value);if(values.length<3){values.unshift(end+step);values.push(start-step)}return values}
function buildShortTermChartPath(points:{x:number;y:number}[]){if(!points.length)return'';return points.map((point,index)=>`${index?'L':'M'} ${point.x.toFixed(2)} ${point.y.toFixed(2)}`).join(' ')}

function ShortTermRibbon({hours,minutes15,timezone,unit,onSelectedDate,anchor,radarNowcast,location,showDwdPrecipitationTypeRadar}:{hours:Hour[];minutes15:Minute15[];timezone:string;unit:WindUnit;onSelectedDate:(date:string)=>void;anchor?:ShortTermAnchor;radarNowcast?:RadarNowcast;location:Location;showDwdPrecipitationTypeRadar:boolean}){
 const [selectedId,setSelectedId]=useState(''),meteogramId=useId().replace(/:/g,''),chartViewportRef=useRef<HTMLDivElement|null>(null),[chartViewportWidth,setChartViewportWidth]=useState(1040);
 const adjusted=useMemo(()=>buildShortTermForecast(minutes15,hours,timezone,Date.now(),anchor,radarNowcast),[minutes15,hours,timezone,anchor,radarNowcast]),points=useMemo(()=>selectShortTermPoints(adjusted,'1h'),[adjusted]),hourlyPoints=points,now90=useMemo(()=>adjusted.filter(point=>point.offsetMinutes<=90),[adjusted]),summary=useMemo(()=>shortTermPointSummary(adjusted,unit),[adjusted,unit]),focusDate=useMemo(()=>shortTermFocusDate(hours,timezone),[hours,timezone]),locallyAdjusted=Boolean(anchor?.active&&adjusted.some(point=>point.localAdjustment>0));
 useEffect(()=>{if(focusDate)onSelectedDate(focusDate)},[focusDate,onSelectedDate]);
 const selectablePoints=useMemo(()=>{const map=new Map<string,ShortTermForecastPoint>();for(const point of [...adjusted,...points,...hourlyPoints])map.set(point.id,point);return [...map.values()].sort((left,right)=>left.epoch-right.epoch)},[adjusted,points,hourlyPoints]);
 useEffect(()=>{if(!selectablePoints.length)return;setSelectedId(current=>current&&selectablePoints.some(point=>point.id===current)?current:selectablePoints[0].id)},[selectablePoints]);
 if(!points.length)return <div className="cockpit-empty">Kurzfristdaten werden geladen …</div>;
 const previewPoints=hourlyPoints.slice(0,Math.min(12,hourlyPoints.length)),timelinePoints=hourlyPoints.slice(0,Math.min(24,hourlyPoints.length)),previewLead=previewPoints[0]??points[0],timelineLead=timelinePoints[0]??previewLead,timelineTail=timelinePoints.at(-1)??previewLead,peakGustPoint=previewPoints.reduce((best,item)=>item.gust>best.gust?item:best,previewLead),peakRainPoint=previewPoints.reduce((best,item)=>item.precipitation>best.precipitation?item:best,previewLead),peakWarmPoint=previewPoints.reduce((best,item)=>item.temperature>best.temperature?item:best,previewLead),coolestPoint=previewPoints.reduce((best,item)=>item.temperature<best.temperature?item:best,previewLead),selectedPoint=selectablePoints.find(point=>point.id===selectedId)??previewLead,timelineLeadDate=dateOnlyFromEpoch(timelineLead.epoch,timezone),timelineTailDate=dateOnlyFromEpoch(timelineTail.epoch,timezone),timelineDateRange=timelineLeadDate===timelineTailDate?`${formatDate(timelineLeadDate,{weekday:'long',day:'2-digit',month:'2-digit'})} · ${timelineLead.timeLabel} bis ${timelineTail.timeLabel}`:`Start ${formatDate(timelineLeadDate,{weekday:'short',day:'2-digit',month:'2-digit'})}, ${timelineLead.timeLabel} · Ende ${formatDate(timelineTailDate,{weekday:'short',day:'2-digit',month:'2-digit'})}, ${timelineTail.timeLabel}`;
 const activatePoint=(point:ShortTermForecastPoint)=>{setSelectedId(point.id);const dateOnly=dateOnlyFromEpoch(point.epoch,timezone);if(dateOnly)onSelectedDate(dateOnly)};
 useEffect(()=>{const node=chartViewportRef.current;if(!node||typeof ResizeObserver==='undefined')return;let frame=0;const update=()=>{if(frame)return;frame=window.requestAnimationFrame(()=>{frame=0;const measured=Math.max(820,Math.round(node.clientWidth||820));setChartViewportWidth(current=>current===measured?current:measured)})},observer=new ResizeObserver(update);update();observer.observe(node);return()=>{if(frame)window.cancelAnimationFrame(frame);observer.disconnect()}},[]);
 const chartSourcePoints=points.slice(0,Math.min(points.length,25));
 const chartPaddingLeft=62,chartPaddingRight=58,chartTop=74,chartBottom=300,chartHeight=360,chartWidth=Math.max(1040,chartViewportWidth),chartPlotWidth=chartWidth-chartPaddingLeft-chartPaddingRight,chartHorizontalStep=chartSourcePoints.length>1?chartPlotWidth/(chartSourcePoints.length-1):chartPlotWidth,chartRangeMin=Math.min(...chartSourcePoints.map(point=>Math.min(point.temperature,point.apparent))),chartRangeMax=Math.max(...chartSourcePoints.map(point=>Math.max(point.temperature,point.apparent))),chartTickValues=shortTermTickValues(chartRangeMin-2,chartRangeMax+2),chartTempMin=Math.min(...chartTickValues),chartTempMax=Math.max(...chartTickValues),chartTempSpan=Math.max(1,chartTempMax-chartTempMin),chartFirstTick=chartTickValues[0]??0,chartSecondTick=chartTickValues[1]??chartFirstTick,chartTickStepValue=Math.abs(chartFirstTick-chartSecondTick)||shortTermTickStep(chartTempSpan),chartMinorTickValues=chartTickValues.slice(0,-1).flatMap((tick,index)=>{const next=chartTickValues[index+1],middle=tick-chartTickStepValue/2;return Number.isFinite(next)&&middle>next?[middle]:[]}),chartRainMax=Math.max(1,Math.ceil(Math.max(...chartSourcePoints.map(point=>point.precipitation),0,.2))),chartRainTicks=[0,chartRainMax/2,chartRainMax],plotHeight=chartBottom-chartTop;
 const positionPct=(value:number)=>`${(value/chartWidth*100).toFixed(4)}%`,widthPct=(value:number)=>`${(value/chartWidth*100).toFixed(4)}%`;
 const chartXPositions=chartSourcePoints.map((_,index)=>chartSourcePoints.length<=1?chartPaddingLeft+chartPlotWidth/2:chartPaddingLeft+index*chartHorizontalStep);
 const chartPoints=chartSourcePoints.map((point,index)=>{const x=chartXPositions[index],previousX=index?chartXPositions[index-1]:chartPaddingLeft,nextX=index<chartXPositions.length-1?chartXPositions[index+1]:chartWidth-chartPaddingRight,columnLeft=index?((previousX+x)/2):chartPaddingLeft,columnRight=index<chartXPositions.length-1?((x+nextX)/2):chartWidth-chartPaddingRight,tempY=chartBottom-((point.temperature-chartTempMin)/chartTempSpan)*plotHeight,apparentY=chartBottom-((point.apparent-chartTempMin)/chartTempSpan)*plotHeight,rainHeight=(point.precipitation/chartRainMax)*plotHeight,dateValue=dateOnlyFromEpoch(point.epoch,timezone),previousDate=index?dateOnlyFromEpoch(chartSourcePoints[index-1].epoch,timezone):'',showDateMarker=!index||dateValue!==previousDate,showTimeLabel=!index||index===chartSourcePoints.length-1||showDateMarker||/^(00|03|06|09|12|15|18|21):/.test(point.timeLabel),rainTone=precipitationColor({precipitation:point.precipitation,rain:point.precipitation,showers:0,snowfall:0,probability:point.probability,code:point.code,time:'',epoch:point.epoch,timezone}),dayLabel=formatDate(dateValue,{weekday:'short',day:'2-digit',month:'2-digit'}),dayName=formatDate(dateValue,{weekday:'short'}),weatherY=clamp(tempY-38-(index%2?7:0),chartTop+4,chartBottom-34);return{point,index,x,tempY,apparentY,rainHeight,dateValue,showDateMarker,showTimeLabel,rainTone,dayLabel,dayName,columnLeft,columnRight,columnWidth:Math.max(16,columnRight-columnLeft),gust:point.gust,weatherY}});
 const chartDayBands=chartPoints.reduce((bands,item)=>{const last=bands[bands.length-1];if(last&&last.dateValue===item.dateValue){last.endX=item.columnRight;last.centerX=(last.startX+last.endX)/2;last.timeEndLabel=item.point.timeLabel;return bands}bands.push({dateValue:item.dateValue,label:item.dayName,startX:item.columnLeft,endX:item.columnRight,centerX:item.x,timeStartLabel:item.point.timeLabel,timeEndLabel:item.point.timeLabel});return bands},[] as {dateValue:string;label:string;startX:number;endX:number;centerX:number;timeStartLabel:string;timeEndLabel:string}[]);
 const chartAxisPoints=chartPoints.filter((item,index)=>item.showTimeLabel||!index||index===chartPoints.length-1),chartWeatherPoints=chartPoints,chartWindPoints=chartPoints;
 const actualPath=buildShortTermChartPath(chartPoints.map(item=>({x:item.x,y:item.tempY}))),apparentPath=buildShortTermChartPath(chartPoints.map(item=>({x:item.x,y:item.apparentY}))),selectedVisualPoint=chartPoints.find(item=>item.point.id===selectedPoint.id)??chartPoints[0],temperatureGradientId=`mid-meteogram-temp-${meteogramId}`,rainGradientId=`mid-meteogram-rain-${meteogramId}`;
 return <div className="cockpit-short-term" data-hyperlocal={locallyAdjusted?'true':'false'}>
  <div className="cockpit-brief"><span><small>Kurzfrist</small><strong>{summary}</strong>{locallyAdjusted?<em className="cockpit-local-badge">{anchor?.sourceLabel||'Hyperlokal angepasst'}</em>:null}</span><small className="cockpit-legend-inline">Darstellung durchgängig einstündig.</small></div>
  {now90.length?<div className="cockpit-now90"><header><b>Nächste 90 Minuten</b><small>{locallyAdjusted?'hyperlokal angeglichen · ':''}Wetter · Temperatur · Niederschlag · Wind</small></header><div className="cockpit-now90-grid" data-cockpit-horizontal-scroll="true">{now90.map(item=>{const temperatureTone=ecmwfTemperatureTone(item.temperature);return <button type="button" key={item.epoch} className={`cockpit-now90-slot${item.precipitation>=.01?' wet':''}${selectedPoint.id===item.id?' active':''}`} title={`${item.timeLabel}: ${item.weatherLabel} · ${Math.round(item.temperature)} °C · ${formatDecimalFixed(item.precipitation,1)} mm · ${Math.round(item.probability)} % · Wind ${wind(item.wind,unit)}, Böen ${wind(item.gust,unit)}`} onClick={()=>activatePoint(item)} aria-expanded={selectedPoint.id===item.id}><small>{item.timeLabel}</small><WeatherPictogram code={item.code} day={item.isDay} size={34} title={item.weatherLabel} cloud={item.cloud} lowCloud={item.lowCloud} midCloud={item.midCloud} highCloud={item.highCloud}/><b className="cockpit-now90-temp climate-tone" style={{background:temperatureTone.background,borderColor:temperatureTone.border,color:temperatureTone.color}} title={temperatureTone.title}>{Math.round(item.temperature)}°</b><span className="cockpit-now90-weather">{item.weatherLabel}</span><span className="cockpit-now90-meta"><i style={{background:precipitationColor({precipitation:item.precipitation,rain:item.precipitation,showers:0,snowfall:0,probability:item.probability,code:item.code,time:'',epoch:item.epoch,timezone})}}/>{formatDecimalFixed(item.precipitation,1)} mm · {Math.round(item.probability)} %</span><span className="cockpit-now90-wind"><InlineWindArrow direction={item.direction} gust={item.gust} size={15}/>{wind(item.wind,unit)}</span></button>})}</div></div>:null}
  <DwdPrecipitationTypeRadar location={location} enabled={showDwdPrecipitationTypeRadar}/>
  <div className="cockpit-short-insight-grid premium"><article className="cockpit-short-spotlight"><small>Wärmster Zeitpunkt</small><b>{Math.round(peakWarmPoint.temperature)} °C</b><span>{peakWarmPoint.timeLabel} · gefühlt {Math.round(peakWarmPoint.apparent)} °C</span></article><article className="cockpit-short-spotlight"><small>Kühlster Zeitpunkt</small><b>{Math.round(coolestPoint.temperature)} °C</b><span>{coolestPoint.timeLabel} · Taupunkt {Math.round(coolestPoint.dewPoint)} °C</span></article><article className="cockpit-short-spotlight"><small>Windhöhepunkt</small><b>{wind(peakGustPoint.gust,unit)}</b><span>Böen um {peakGustPoint.timeLabel}</span></article><article className="cockpit-short-spotlight"><small>Niederschlagsspitze</small><b>{formatDecimalFixed(peakRainPoint.precipitation,1)} mm</b><span>max. {Math.round(Math.max(...points.map(item=>item.probability)))} % · {peakRainPoint.timeLabel}</span></article></div>
  <section className="cockpit-meteogram-pro" aria-label="Kurzfrist-Meteogramm für 24 Stunden">
   <header className="cockpit-meteogram-pro__head"><span><small>Kurzfristdiagramm</small><b>24-h-Meteogramm</b><span>Wetter, Temperaturmittel mit ECMWF-Farbverlauf, gefühlte Temperatur, Niederschlag und Wind. Zeitpunkt antippen für Einzeldaten.</span></span><em>Stündlich · vollständig sichtbar</em></header>
   <div className="cockpit-meteogram-pro__stage">
    <div ref={chartViewportRef} className="cockpit-meteogram-pro__canvas" style={{width:'100%',height:`${chartHeight}px`} as CSSProperties}>
     <svg className="cockpit-meteogram-pro__svg" viewBox={`0 0 ${chartWidth} ${chartHeight}`} role="img" aria-label="Kurzfrist-Meteogramm mit Datum- und Zeitachse, Temperaturverlauf, gefühlter Temperatur, Niederschlag und meteorologischen Windfiedern">
      <defs><linearGradient id={temperatureGradientId} gradientUnits="userSpaceOnUse" x1={chartPaddingLeft} y1="0" x2={chartWidth-chartPaddingRight} y2="0">{chartPoints.map((item,index)=><stop key={`temp-stop-${item.point.id}`} offset={`${chartPoints.length<=1?0:index/(chartPoints.length-1)*100}%`} stopColor={ecmwfTemperatureLineColor(item.point.temperature)}/>)}</linearGradient><linearGradient id={rainGradientId} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#55c7f2"/><stop offset="100%" stopColor="#168ac7"/></linearGradient></defs>
      <rect className="plot-bg" x={chartPaddingLeft} y={chartTop} width={chartWidth-chartPaddingLeft-chartPaddingRight} height={plotHeight} rx="18" ry="18"/>
      {chartPoints.map(item=>!item.point.isDay?<rect key={`night-${item.point.id}`} className="night-band" x={item.columnLeft} y={chartTop} width={item.columnWidth} height={plotHeight}/>:null)}
      {chartMinorTickValues.map(tick=>{const y=chartBottom-((tick-chartTempMin)/chartTempSpan)*plotHeight;return <line key={`minor-${tick}`} className="minor-grid-line" x1={chartPaddingLeft} y1={y} x2={chartWidth-chartPaddingRight} y2={y}/>})}
      {chartTickValues.map(tick=>{const y=chartBottom-((tick-chartTempMin)/chartTempSpan)*plotHeight;return <g key={`tick-${tick}`}><line className="grid-line" x1={chartPaddingLeft} y1={y} x2={chartWidth-chartPaddingRight} y2={y}/><text className="axis-label left" x={8} y={y+5}>{`${tick}°C`}</text></g>})}
      {chartRainTicks.map(tick=>{const y=chartBottom-(tick/chartRainMax)*plotHeight;return <text key={`rain-${tick}`} className="axis-label right" x={chartWidth-chartPaddingRight+9} y={y+5}>{`${formatDecimalFixed(tick,1)} mm`}</text>})}
      {chartDayBands.slice(1).map(band=><line key={`day-separator-${band.dateValue}`} className="day-separator" x1={band.startX} y1={chartTop} x2={band.startX} y2={chartBottom}/>)}
      {chartPoints.map(item=><line key={`hour-${item.point.id}`} className={`hour-line${item.showDateMarker?' major':''}`} x1={item.x} y1={chartTop} x2={item.x} y2={chartBottom}/>) }
      <path className="apparent-line" d={apparentPath}/><path className="temperature-line" d={actualPath} stroke={`url(#${temperatureGradientId})`}/>
      {chartPoints.map(item=>item.rainHeight>.5?<rect key={`rainbar-${item.point.id}`} className="rain-bar" x={item.x-7} y={chartBottom-item.rainHeight} width="14" height={Math.max(2,item.rainHeight)} rx="7" style={{fill:item.rainTone||`url(#${rainGradientId})`}}/>:null)}
      {chartPoints.map(item=><circle key={`apparent-point-${item.point.id}`} className={`apparent-point${selectedVisualPoint?.point.id===item.point.id?' active':''}`} cx={item.x} cy={item.apparentY} r={selectedVisualPoint?.point.id===item.point.id?4.4:2.8}/>) }
      {chartPoints.map(item=><circle key={`temperature-point-${item.point.id}`} className={`temperature-point${selectedVisualPoint?.point.id===item.point.id?' active':''}`} cx={item.x} cy={item.tempY} r={selectedVisualPoint?.point.id===item.point.id?5:3.3} style={{fill:ecmwfTemperatureLineColor(item.point.temperature)}}/>) }
      <g className="cockpit-meteogram-pro__svg-weather" aria-hidden="true">{chartWeatherPoints.map(item=><WeatherPictogram key={`weather-${item.point.id}`} code={item.point.code} day={item.point.isDay} size={22} x={item.x-11} y={item.weatherY} title={`${item.point.timeLabel} · ${item.point.weatherLabel}`} cloud={item.point.cloud} lowCloud={item.point.lowCloud} midCloud={item.point.midCloud} highCloud={item.point.highCloud}/>)}</g>
     </svg>
     <div className="cockpit-meteogram-pro__overlay time" aria-hidden="true">{chartAxisPoints.map(item=><span key={`time-${item.point.id}`} style={{left:positionPct(item.x)}}><b>{item.point.timeLabel.replace(':00','')}</b></span>)}</div>
     <div className="cockpit-meteogram-pro__overlay calendar" aria-hidden="true">{chartDayBands.map(band=><span key={`day-${band.dateValue}`} style={{left:positionPct(band.centerX)}}><b>{band.label}</b><small>{formatDate(band.dateValue,{day:'2-digit',month:'2-digit'})}</small></span>)}</div>
     <div className="cockpit-meteogram-pro__overlay wind" aria-hidden="true">{chartWindPoints.map((point,index)=><span key={`wind-${point.point.id}`} className={index%2?'offset':''} style={{left:positionPct(point.x),color:windSignalColor(point.gust)}} title={`Wind aus ${cardinal(point.point.direction)} mit ${wind(point.point.wind,'kn')}`}><svg width="24" height="24" viewBox="-14 -14 28 28"><SvgWindBarb direction={point.point.direction} speed={point.point.wind} size={11.6} color={windSignalColor(point.gust)}/></svg></span>)}</div>
     <div className="cockpit-meteogram-pro__hitlayer">{chartPoints.map(item=><button type="button" key={`hit-${item.point.id}`} className={selectedVisualPoint?.point.id===item.point.id?'active':''} style={{left:positionPct(item.columnLeft),width:widthPct(item.columnWidth)}} onClick={()=>activatePoint(item.point)} aria-expanded={selectedPoint.id===item.point.id} title={`${item.dayLabel} ${item.point.timeLabel}: ${item.point.weatherLabel} · ${formatDecimalFixed(item.point.temperature,1)} °C · gefühlt ${formatDecimalFixed(item.point.apparent,1)} °C · ${formatDecimalFixed(item.point.precipitation,1)} mm · Wind ${wind(item.point.wind,unit)}`}><span className="sr-only">{item.dayLabel} {item.point.timeLabel}: {item.point.weatherLabel}</span></button>)}</div>
         </div>
   </div>
   <div className="cockpit-meteogram-pro__legend" aria-hidden="true"><span><i className="temperature"/>Temperatur (ECMWF)</span><span><i className="apparent"/>gefühlt</span><span><i className="rain"/>Niederschlag</span><span><i className="wind"/>Wind</span></div>
   <div className="cockpit-meteogram-pro__datafield" role="status" aria-live="polite"><div className="cockpit-meteogram-pro__tooltip-content"><div className="cockpit-meteogram-pro__tooltip-head"><span><small>Einzeldaten</small><b>{selectedVisualPoint?.dayLabel||chartPoints[0]?.dayLabel} · {selectedPoint.timeLabel}</b><small>{selectedPoint.weatherLabel}</small></span><WeatherPictogram code={selectedPoint.code} day={selectedPoint.isDay} size={40} compact title={selectedPoint.weatherLabel} cloud={selectedPoint.cloud} lowCloud={selectedPoint.lowCloud} midCloud={selectedPoint.midCloud} highCloud={selectedPoint.highCloud}/></div><strong>24 Stunden · vollständig sichtbar · gewählter Zeitpunkt</strong><dl><div><dt><i className="temp"/>Temperatur</dt><dd>{Math.round(selectedPoint.temperature)} °C</dd></div><div><dt><i className="apparent"/>Gefühlt</dt><dd>{Math.round(selectedPoint.apparent)} °C</dd></div><div><dt><i className="dew"/>Taupunkt</dt><dd>{formatDecimalFixed(selectedPoint.dewPoint,1)} °C</dd></div><div><dt><i className="rain" style={{background:precipitationColor({precipitation:selectedPoint.precipitation,rain:selectedPoint.precipitation,showers:0,snowfall:0,probability:selectedPoint.probability,code:selectedPoint.code,time:'',epoch:selectedPoint.epoch,timezone})}}/>Niederschlag</dt><dd>{shortTermPrecipitationDetail(selectedPoint)}</dd></div><div><dt><i className="gust"/>Gewitterrisiko</dt><dd>{shortTermThunderRiskLabel(selectedPoint)}</dd></div><div><dt><i className="wind"/>Wind</dt><dd>{shortTermWindDetail(selectedPoint,unit)}</dd></div><div><dt><i className="pressure"/>Luftdruck</dt><dd>{formatDecimalFixed(selectedPoint.pressure,1)} hPa</dd></div><div><dt><i className="dew"/>Sichtweite</dt><dd>{shortTermVisibilityLabel(selectedPoint.visibility)}</dd></div></dl></div></div>
  </section>
  <section className="cockpit-hourly-preview-shell" aria-label="Stündliche 24-Stunden-Vorschau">
   <header className="cockpit-hourly-preview-head"><span><small>24-Stunden-Leiste</small><b>Kompakte 24-h-Zeitachse</b><strong>{timelineDateRange}</strong></span><em>{timelinePoints.length>=18?'Seitlich wischbar – mobil flach verdichtet':'Kompakte Stundenübersicht'}</em></header>
   <div className="cockpit-hourly-preview" role="list" aria-label="Stündliche Kurzfristvorschau">{timelinePoints.map((point,index)=>{const pointDate=dateOnlyFromEpoch(point.epoch,timezone),previousDate=index?dateOnlyFromEpoch(timelinePoints[index-1].epoch,timezone):'',showDateMarker=!index||pointDate!==previousDate,precipFill=Math.max(8,Math.round(clamp(point.probability,0,100))),precipStyle={width:`${precipFill}%`,background:precipitationColor({precipitation:point.precipitation,rain:point.precipitation,showers:0,snowfall:0,probability:point.probability,code:point.code,time:'',epoch:point.epoch,timezone})} as CSSProperties,temperatureTone=ecmwfTemperatureTone(point.temperature);return <button type="button" key={point.epoch} className={`cockpit-hourly-chip${point.precipitation>=.05||point.probability>=45?' wet':''}${point.isDay?' day':' night'}${selectedPoint.id===point.id?' active':''}`} role="listitem" title={`${formatDate(pointDate,{weekday:'long',day:'2-digit',month:'2-digit'})} ${point.timeLabel}: ${point.weatherLabel} · ${Math.round(point.temperature)} °C · ${formatDecimalFixed(point.precipitation,1)} mm · ${Math.round(point.probability)} % · Wind ${wind(point.wind,unit)}, Böen ${wind(point.gust,unit)}`} onClick={()=>activatePoint(point)} aria-expanded={selectedPoint.id===point.id}>
     {showDateMarker?<span className="cockpit-hourly-day-marker">{formatDate(pointDate,{weekday:'short',day:'2-digit',month:'2-digit'})}</span>:<span className="cockpit-hourly-day-marker ghost">&nbsp;</span>}
     <div className="cockpit-hourly-chip-top"><time>{point.timeLabel}</time><b className="climate-tone" style={{background:temperatureTone.background,borderColor:temperatureTone.border,color:temperatureTone.color}} title={temperatureTone.title}>{Math.round(point.temperature)}°</b></div>
     <div className="cockpit-hourly-chip-main"><WeatherPictogram code={point.code} day={point.isDay} size={26} title={point.weatherLabel} cloud={point.cloud} lowCloud={point.lowCloud} midCloud={point.midCloud} highCloud={point.highCloud}/><small>{shortTermCompactWeatherLabel(point.weatherLabel)}</small></div>
     <span className="cockpit-hourly-rain"><span className="cockpit-hourly-probability-track"><i/><b style={precipStyle}/></span><span className="cockpit-hourly-meta-row"><Droplets size={12}/><b>{Math.round(point.probability)} %</b><small>{formatDecimalFixed(point.precipitation,1)} mm</small></span></span>
     <span className="cockpit-hourly-wind"><span className="cockpit-hourly-meta-row"><InlineWindArrow direction={point.direction} gust={point.gust} size={14}/><b>{wind(point.wind,unit)}</b><small>{compactGustLabel(point.gust,unit)}</small></span></span>
    </button>})}</div>
  </section>
 </div>
}

function SevenDayBand({days,hours,minutes15,climate,unit,selectedDate,onSelectedDate,summary,hourlyDetail}:{days:Day[];hours:Hour[];minutes15:Minute15[];climate:ClimateDay[];unit:WindUnit;selectedDate:string;onSelectedDate:(date:string)=>void;summary?:string;hourlyDetail?:ReactNode}){
 const [expandedDate,setExpandedDate]=useState<string|null>(null),visible=days.slice(0,7),climateByDate=useMemo(()=>new Map(climate.map(item=>[item.date,item])),[climate]);
 useEffect(()=>{setExpandedDate(current=>current&&selectedDate&&current!==selectedDate?selectedDate:current)},[selectedDate]);
 if(!visible.length)return <div className="cockpit-empty">7-Tage-Daten werden geladen …</div>;
 const allMinimum=Math.min(...visible.map(day=>day.min)),allMaximum=Math.max(...visible.map(day=>day.max)),temperatureRange=Math.max(1,allMaximum-allMinimum),selected=visible.find(day=>day.date===selectedDate)??visible[0],expanded=Boolean(hourlyDetail&&expandedDate===selected.date);
 function chooseDay(date:string){onSelectedDate(date);if(hourlyDetail)setExpandedDate(current=>current===date?null:date)}
 return <div className="cockpit-seven-day">
  <div className="cockpit-brief"><span><small>7-Tage-Trend</small><strong>{summary||'Der Verlauf wird aus den sieben Prognosetagen zusammengefasst.'}</strong></span><small className="cockpit-legend-inline">Tag antippen: stündlicher Verlauf. Farbton der Temperatur = Abweichung vom Tagesklimamittel.</small></div>
  <div className="cockpit-seven-grid" data-cockpit-horizontal-scroll="true" style={{'--cockpit-day-count':visible.length} as CSSProperties}>{visible.map(day=>{const dayHours=dayPeriodHoursForDate(day.date,hours),precipitationAssessment=dayPrecipitationAssessment(day,dayHours,minutes15),precipitationDuration=precipitationDurationLabel(precipitationAssessment.durationHours),weather=dayWeatherCharacter(day,dayHours),dayVisual=cockpitPeriodVisual(dayPeriodHoursForDate(day.date,hours),true,weather.code,dayWeatherCharacterText(weather)),nightVisual=cockpitPeriodVisual(followingNightHoursForDate(day.date,hours),false,weather.code,weather.label),left=(day.min-allMinimum)/temperatureRange*100,width=Math.max(8,(day.max-day.min)/temperatureRange*100),warning=windWarningLevel(day.gust),regime=dayRegime(day,dayHours),climateDay=climateByDate.get(day.date),minTone=dailyTemperatureTone(day.min,climateDay?.minMean,'min'),maxTone=dailyTemperatureTone(day.max,climateDay?.maxMean,'max'),isExpanded=expandedDate===day.date;return <button type="button" key={day.date} className={`cockpit-day regime-${regime}${selected.date===day.date?' active':''}${isExpanded?' hourly-open':''}`} data-regime={regimeLabel(regime)} title={`${regimeLabel(regime)} · ${dayWeatherCharacterText(weather)} · Niederschlagsdauer ${precipitationDuration}`} onClick={()=>chooseDay(day.date)} aria-pressed={selected.date===day.date} aria-expanded={hourlyDetail?isExpanded:undefined}>
   <span className="cockpit-day-date"><b>{formatDate(day.date,{weekday:'short'})}</b><small>{formatDate(day.date,{day:'2-digit',month:'2-digit'})}</small></span>
   <span className="cockpit-day-weather-pair"><WeatherPictogram className="cockpit-day-main-icon" code={dayVisual.code} day size={42} title={dayVisual.title} cloud={dayVisual.cloud} lowCloud={dayVisual.lowCloud} midCloud={dayVisual.midCloud} highCloud={dayVisual.highCloud}/>{nightVisual.available&&<span className="cockpit-day-night-icon"><WeatherPictogram className="cockpit-day-night-glyph" code={nightVisual.code} day={false} size={24} compact title={nightVisual.title} cloud={nightVisual.cloud} lowCloud={nightVisual.lowCloud} midCloud={nightVisual.midCloud} highCloud={nightVisual.highCloud}/></span>}</span>
   <span className={`cockpit-day-regime ${regime}`}><i>{regimeSymbol(regime)}</i>{regimeLabel(regime)}</span>
   <span className="cockpit-day-temps"><b className="climate-tone" style={{color:minTone.color,background:minTone.background,borderColor:minTone.border}} title={minTone.title}>{Math.round(day.min)}°</b><strong className="climate-tone" style={{color:maxTone.color,background:maxTone.background,borderColor:maxTone.border}} title={maxTone.title}>{Math.round(day.max)}°</strong></span>
   <span className="cockpit-day-temp-track"><i style={{left:`${left}%`,width:`${width}%`}}/></span>
   <span className="cockpit-day-rain" title={`${formatDecimalFixed(day.precipitation,1)} mm · ${Math.round(day.probability)} % · Dauer ${precipitationDuration}`}><b>{formatDecimalFixed(day.precipitation,1)} mm</b><small>{Math.round(day.probability)} % · {precipitationDuration}</small></span>
   <span className={`cockpit-day-wind warning-${warning}`} title={`Wind aus ${cardinal(day.direction)} · ${wind(day.wind,unit)}, Böen ${wind(day.gust,unit)}`}><InlineWindArrow direction={day.direction} gust={day.gust} size={17}/><small className={windAlertClass(day.gust)}>{compactGustLabel(day.gust,unit)}</small></span>
   {hourlyDetail?<span className="cockpit-day-hourly-cue"><Clock3 size={12}/>{isExpanded?'Tagesansicht':'Stunden'}{isExpanded?<ChevronUp size={12}/>:<ChevronDown size={12}/>}</span>:null}
  </button>})}</div>
  {expanded?<section className="cockpit-day-hourly-accordion" aria-label={`Stündlicher Verlauf für ${formatDate(selected.date,{weekday:'long',day:'2-digit',month:'2-digit'})}`}><header><span><Clock3 size={17}/><span><strong>{formatDate(selected.date,{weekday:'long',day:'2-digit',month:'2-digit'})}</strong><small>Stündlicher Tagesverlauf</small></span></span><button type="button" onClick={()=>setExpandedDate(null)}><ChevronUp size={15}/> Tagesansicht</button></header><div className="cockpit-day-hourly-content">{hourlyDetail}</div></section>:null}
 </div>
}
function ensembleSeries(ensemble:EnsembleDay[],days:Day[],climate:ClimateDay[]){
 const dayMap=new Map(days.map(day=>[day.date,day]));
 const climateMap=new Map(climate.map(item=>[item.date,item]));
 const maxModelCount=Math.max(1,...ensemble.map(item=>Math.max(1,item.modelCount||1)),1);
 return ensemble.slice(0,14).map((item,index)=>{const bestDay=dayMap.get(item.date),climateDay=climateMap.get(item.date),spread=Math.max(0,item.maxHigh-item.maxLow),consistency=computeEnsembleConfidence({spread,index,modelCount:item.modelCount||1,maxModelCount}),meanDayTemperature=((bestDay?.min??item.minMean)+(bestDay?.max??item.maxMean))/2,climateMean=climateDay?((climateDay.minMean+climateDay.maxMean)/2):NaN,weatherCode=bestDay?.code??3,weatherLabel=bestDay?weatherCodeLabel(bestDay.code):weatherCodeLabel(weatherCode),direction=((bestDay?.direction??0)%360+360)%360;return{date:item.date,index,bestMin:bestDay?.min??item.minMean,bestMax:bestDay?.max??item.maxMean,bestPrecipitation:bestDay?.precipitation??item.precipitationMean,bestPrecipitationProbability:bestDay?.probability??item.precipitationProbability,bestWind:bestDay?.wind??item.windMean,bestGust:bestDay?.gust??item.gustMean,maxLow:item.maxLow,maxHigh:item.maxHigh,minLow:item.minLow,minHigh:item.minHigh,precipitationLow:item.precipitationLow,precipitationHigh:item.precipitationHigh,windLow:item.windLow,windHigh:item.windHigh,gustLow:item.gustLow,gustHigh:item.gustHigh,temperatureSpread:spread,windMean:item.windMean,gustMean:item.gustMean,modelCount:item.modelCount||1,consistency,meanDayTemperature,climateMean,anomaly:Number.isFinite(climateMean)?meanDayTemperature-climateMean:NaN,weatherCode,weatherLabel,direction,climateMin:climateDay?.minMean,climateMax:climateDay?.maxMean}});
}
type CockpitGuideRow=ReturnType<typeof ensembleSeries>[number];
function cockpitGuideConfidenceLabel(value:number){return value>=82?'hoch':value>=66?'gut':value>=50?'mittel':'eingeschränkt'}
function cockpitTrendAverage(rows:CockpitGuideRow[],selector:(row:CockpitGuideRow)=>number){const values=rows.map(selector).filter(Number.isFinite);return values.length?values.reduce((sum,value)=>sum+value,0)/values.length:NaN}
function cockpitTrendSum(rows:CockpitGuideRow[],selector:(row:CockpitGuideRow)=>number){return rows.map(selector).filter(Number.isFinite).reduce((sum,value)=>sum+value,0)}
function cockpitForecastOutlook(data:CockpitGuideRow[],secureCount:number){
 const early=data.slice(0,Math.min(3,data.length)),start=Math.min(Math.max(secureCount,3),Math.max(0,data.length-1)),candidate=data.slice(start,Math.min(data.length,start+4)),later=candidate.length?candidate:data.slice(Math.min(3,data.length),Math.min(7,data.length));
 if(!early.length||!later.length)return{headline:'noch keine belastbare Folgetendenz',detail:'Für den anschließenden Zeitraum liegen noch zu wenige vergleichbare Tage vor.'};
 const earlyTemperature=cockpitTrendAverage(early,row=>(row.bestMax+row.bestMin)/2),laterTemperature=cockpitTrendAverage(later,row=>(row.bestMax+row.bestMin)/2),temperatureDelta=laterTemperature-earlyTemperature,earlyRain=cockpitTrendSum(early,row=>row.bestPrecipitation),laterRain=cockpitTrendSum(later,row=>row.bestPrecipitation),laterRainProbability=cockpitTrendAverage(later,row=>row.bestPrecipitationProbability),earlyGust=cockpitTrendAverage(early,row=>row.bestGust),laterGust=cockpitTrendAverage(later,row=>row.bestGust),gustDelta=laterGust-earlyGust;
 const temperatureText=temperatureDelta>=3?'deutlich wärmer':temperatureDelta>=1?'etwas wärmer':temperatureDelta<=-3?'deutlich kühler':temperatureDelta<=-1?'etwas kühler':'Temperaturen ähnlich',precipitationText=laterRainProbability>=60||laterRain>=Math.max(4,earlyRain+2.5)?'mit erhöhter Regenneigung':laterRainProbability<=25&&laterRain<1?'überwiegend trocken':'mit wechselhaftem Niederschlagsrisiko',windText=gustDelta>=6?', zudem windiger':gustDelta<=-6?', zudem ruhiger':'';
 return{headline:`${temperatureText}, ${precipitationText}${windText}`,detail:`Tendenz aus ${later.length} Folgetagen gegenüber dem frühen Prognoseabschnitt.`};
}
function cockpitForecastUncertaintyDriver(row:CockpitGuideRow|null){if(!row)return'Modelllösungen liegen noch eng beieinander';const drivers=[{label:'Temperatur',score:((row.maxHigh-row.maxLow)+(row.minHigh-row.minLow))/12},{label:'Niederschlag',score:(row.precipitationHigh-row.precipitationLow)/10},{label:'Wind und Böen',score:((row.windHigh-row.windLow)+(row.gustHigh-row.gustLow))/40}].sort((a,b)=>b.score-a.score);return`${drivers[0].label} streut an diesem Tag am stärksten`}
function cockpitForecastLeadDays(firstDate:string|undefined,lastDate:string|undefined){if(!firstDate||!lastDate)return 0;const first=Date.parse(`${firstDate}T12:00:00Z`),last=Date.parse(`${lastDate}T12:00:00Z`);return Number.isFinite(first)&&Number.isFinite(last)?Math.max(0,Math.round((last-first)/86400000)):0}
function CockpitForecastGuide({data,scenarios,advancedMode}:{data:CockpitGuideRow[];scenarios:EnsembleScenarioCluster[];advancedMode:boolean}){
 const first=data.slice(0,3),average=(rows:CockpitGuideRow[])=>rows.length?Math.round(rows.reduce((sum,row)=>sum+row.consistency,0)/rows.length):0,near=average(first),widest=data.slice(0,7).reduce<CockpitGuideRow|null>((best,row)=>!best||(row.maxHigh-row.maxLow+row.minHigh-row.minLow)>(best.maxHigh-best.maxLow+best.minHigh-best.minLow)?row:best,null),divergence=scenarios.find(item=>item.divergenceDate)?.divergenceDate,uncertaintyDate=divergence??widest?.date;
 const secureThreshold=72,secureUntilIndex=data.findIndex(row=>row.consistency<secureThreshold),secureCount=secureUntilIndex===-1?Math.min(data.length,14):secureUntilIndex,secureLast=secureCount>0?data[Math.min(secureCount-1,data.length-1)]:null,secureLeadDays=cockpitForecastLeadDays(data[0]?.date,secureLast?.date),outlook=cockpitForecastOutlook(data,secureCount),uncertaintyDriver=cockpitForecastUncertaintyDriver(widest),secureHeadline=secureLast?`bis ${formatDate(secureLast.date,{weekday:'long',day:'2-digit',month:'2-digit'})}`:'nur sehr kurzfristig',secureDetail=secureLast?(secureLeadDays===0?'für den aktuellen Tag mit guter Modellübereinstimmung':`${secureLeadDays} ${secureLeadDays===1?'Tag':'Tage'} im Voraus mit guter Modellübereinstimmung`):'Die Modelllösungen unterscheiden sich bereits im frühen Vorhersagezeitraum.';
 return <section className={`ensemble-forecast-compass cockpit-forecast-compass ${cockpitGuideConfidenceLabel(near)}`} aria-label="MID Prognose-Kompass"><header><span aria-hidden="true">◎</span><div><small>MID Prognose-Kompass</small><strong>Prognoseentwicklung</strong></div></header><div><span><small>Belastbarer Zeitraum</small><b>{secureHeadline}</b><em>{secureDetail}{advancedMode?` · Schwelle ${Math.round(secureThreshold)} % Konsistenz`:''}</em></span><span><small>Wahrscheinlichste Entwicklung</small><b>{outlook.headline}</b><em>{outlook.detail}</em></span><span><small>Zunehmende Unsicherheit</small><b>{uncertaintyDate?`ab ${formatDate(uncertaintyDate,{weekday:'long',day:'2-digit',month:'2-digit'})}`:'kein markanter Übergang erkennbar'}</b><em>{uncertaintyDriver}</em></span></div></section>
}
function uncertaintySummary(series:ReturnType<typeof ensembleSeries>,scenarios:EnsembleScenarioCluster[]){if(!series.length)return'Ensemble-Daten werden geladen.';const explicit=scenarios.find(item=>item.divergenceDate)?.divergenceDate,threshold=series.find(item=>item.index>=5&&item.temperatureSpread>=7)?.date,date=explicit||threshold,late=series.slice(7),lateConsistency=late.length?Math.round(late.reduce((sum,item)=>sum+item.consistency,0)/late.length):series[series.length-1].consistency;return date?`Ab ${formatDate(date,{weekday:'long',day:'2-digit',month:'2-digit'})} streuen die Lösungen deutlicher · spätere Konsistenz ${Math.round(lateConsistency)} %`:`Die Lösungen bleiben derzeit vergleichsweise gebündelt · spätere Konsistenz ${Math.round(lateConsistency)} %`}
function precipCombinedScore(amount:number,probability:number){return clamp((Math.min(1,Math.max(0,amount)/8)*58)+(clamp(probability,0,100)*.42),0,100)}
function anomalyColor(value:number){if(!Number.isFinite(value))return'#8aa0b3';if(value>=6)return'#ff6b39';if(value>=3)return'#ff9650';if(value>=1)return'#ffbf66';if(value<=-6)return'#2f87e0';if(value<=-3)return'#55a7ff';if(value<=-1)return'#8ec7ff';return'#9db36a'}
function anomalyLabel(value:number){if(!Number.isFinite(value))return'–';return `${value>=0?'+':''}${formatDecimalFixed(value,1)} K`}
function windAlertClass(gustKt:number){const level=windWarningLevel(gustKt);return level>=4?'severe':level===3?'marked':level===2?'noticeable':level===1?'elevated':'calm'}
function windSignalColor(gustKt:number){const level=windWarningLevel(gustKt);return level>=4?'#9b59c6':level===3?'#e74a4a':level===2?'#ef8d32':level===1?'#e6c229':'#2f9b6a'}
function buildWindBarbPrimitives(speedKt:number,size:number){const rounded=Math.max(0,Math.round((Number.isFinite(speedKt)?speedKt:0)/5)*5),staff=size,barbSpacing=size*.12,barbLength=size*.42,halfBarbLength=barbLength*.62,primitives:{type:'pennant'|'full'|'half';y:number}[]=[];let remaining=rounded,y=-staff+barbSpacing*.4;while(remaining>=50){primitives.push({type:'pennant',y});remaining-=50;y+=barbSpacing*1.55}while(remaining>=10){primitives.push({type:'full',y});remaining-=10;y+=barbSpacing*1.18}if(remaining>=5)primitives.push({type:'half',y});return{staff,barbSpacing,barbLength,halfBarbLength,rounded,primitives}}
function SvgWindBarb({direction,speed,size=18,color='#1f2329'}:{direction:number;speed:number;size?:number;color?:string}){const normalized=((direction%360)+360)%360,{staff,barbSpacing,barbLength,halfBarbLength,rounded,primitives}=buildWindBarbPrimitives(speed,size),description=`Wind aus ${Math.round(normalized)}° mit ${rounded} kt`;return <g className="svg-wind-barb" style={{color}} transform={`rotate(${normalized.toFixed(1)})`} role="img" aria-label={description}><title>{description}</title><circle cx="0" cy="0" r="1.8" fill="currentColor"/><line x1="0" y1="0" x2="0" y2={(-staff).toFixed(2)} stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/>{!rounded?<circle cx="0" cy="0" r={Math.max(3,size*.18).toFixed(2)} fill="none" stroke="currentColor" strokeWidth="1.5"/>:null}{primitives.map((primitive,index)=>primitive.type==='pennant'?<path key={`flag-${index}`} d={`M 0 ${primitive.y.toFixed(2)} L ${barbLength.toFixed(2)} ${(primitive.y+barbSpacing*.66).toFixed(2)} L 0 ${(primitive.y+barbSpacing*1.32).toFixed(2)} Z`} fill="currentColor"/>:primitive.type==='full'?<line key={`flag-${index}`} x1="0" y1={primitive.y.toFixed(2)} x2={barbLength.toFixed(2)} y2={(primitive.y+barbSpacing*.82).toFixed(2)} stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/>:<line key={`flag-${index}`} x1="0" y1={primitive.y.toFixed(2)} x2={halfBarbLength.toFixed(2)} y2={(primitive.y+barbSpacing*.58).toFixed(2)} stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/>)} </g>}
function InlineWindArrow({direction,gust,size=16}:{direction:number;gust:number;size?:number}){const level=windWarningLevel(gust),rotation=flowDirection(direction);return <span className={`cockpit-inline-wind-arrow warning-${level}`} style={{'--arrow-size':`${size}px`} as CSSProperties} aria-hidden="true"><span style={{transform:`rotate(${rotation}deg)`}}>↑</span></span>}

function FourteenDayHorizon({ensemble,days,scenarios,climate,selectedDate,onSelectedDate,loading,unit,advancedMode}:{ensemble:EnsembleDay[];days:Day[];scenarios:EnsembleScenarioCluster[];climate:ClimateDay[];selectedDate:string;onSelectedDate:(date:string)=>void;loading:boolean;unit:WindUnit;advancedMode:boolean}){
 const series=useMemo(()=>ensembleSeries(ensemble,days,climate),[ensemble,days,climate]);
 const selected=series.find(item=>item.date===selectedDate)??series[0];
 const selectedMinTone=selected?dailyTemperatureTone(selected.bestMin,selected.climateMin,'min'):undefined,selectedMaxTone=selected?dailyTemperatureTone(selected.bestMax,selected.climateMax,'max'):undefined;
 if(!series.length)return <div className="cockpit-empty">14-Tage-Daten werden geladen …</div>;
 return <div className="cockpit-fourteen-day">
  <div className="cockpit-brief compact-fourteen"><span><small>14-Tage-Übersicht</small></span><small className="cockpit-legend-inline">Kompakt pro Tag: Temperaturabweichung · Niederschlagssignal · Wind/Böen · Konsistenz.</small></div>
  <CockpitForecastGuide data={series} scenarios={scenarios} advancedMode={advancedMode}/>
  <div className="cockpit-fourteen-grid" data-cockpit-horizontal-scroll="true">{series.map(item=>{const amountScore=precipCombinedScore(item.bestPrecipitation,item.bestPrecipitationProbability),windScale=Math.max(1,...series.map(entry=>Math.max(entry.bestGust,entry.bestWind))),windWidth=Math.max(8,item.bestWind/windScale*100),gustWidth=Math.max(windWidth,item.bestGust/windScale*100),anomaly=item.anomaly,positive=Number.isFinite(anomaly)&&anomaly>=0,anomalyWidth=Math.min(48,Math.max(6,Math.abs(Number.isFinite(anomaly)?anomaly:0)*7)),warning=windWarningLevel(item.bestGust),windTone=windAlertClass(item.bestGust),minTone=dailyTemperatureTone(item.bestMin,item.climateMin,'min'),maxTone=dailyTemperatureTone(item.bestMax,item.climateMax,'max');return <button type="button" key={item.date} className={`cockpit-fourteen-card${selected?.date===item.date?' active':''}`} onClick={()=>onSelectedDate(item.date)} aria-pressed={selected?.date===item.date}><header><span className="cockpit-fourteen-heading"><WeatherPictogram code={item.weatherCode} day size={32} title={item.weatherLabel}/><span className="cockpit-fourteen-heading-copy"><b>{formatDate(item.date,{weekday:'short'})}</b><small>{formatDate(item.date,{day:'2-digit',month:'2-digit'})}</small><span className="cockpit-fourteen-weather-label">{item.weatherLabel}</span></span></span><em style={{background:consistencyColor(item.consistency)}}>{Math.round(item.consistency)} %</em></header><div className="cockpit-fourteen-row"><label><ThermometerSun size={12}/> Temp</label><span className="cockpit-anomaly-track"><i className="zero"/><b className={positive?'positive':'negative'} style={{width:`${anomalyWidth}%`,background:anomalyColor(anomaly),[positive?'left':'right']:'50%'} as CSSProperties}/></span><small>{anomalyLabel(anomaly)}</small></div><div className="cockpit-fourteen-row"><label><Droplets size={12}/> Regen</label><span className="cockpit-rain-track"><b style={{width:`${amountScore}%`,opacity:Math.max(.34,item.bestPrecipitationProbability/100)}}/></span><small>{formatDecimalFixed(item.bestPrecipitation,1)} mm · {Math.round(item.bestPrecipitationProbability)} %</small></div><div className="cockpit-fourteen-row"><label><Wind size={12}/> Wind</label><span className="cockpit-wind-track"><i style={{width:`${gustWidth}%`}}/><b style={{width:`${windWidth}%`}}/></span><small className={`cockpit-fourteen-wind-meta warning-${warning} ${windTone}`}><InlineWindArrow direction={item.direction} gust={item.bestGust} size={15}/>{wind(item.bestWind,unit)} · Böen {wind(item.bestGust,unit)}</small></div><footer className="cockpit-fourteen-temps"><b className="climate-tone" style={{color:minTone.color,background:minTone.background,borderColor:minTone.border}} title={minTone.title}>{Math.round(item.bestMin)}°</b><em>/</em><strong className="climate-tone" style={{color:maxTone.color,background:maxTone.background,borderColor:maxTone.border}} title={maxTone.title}>{Math.round(item.bestMax)}°</strong></footer></button>})}</div>
  {selected?<div className="cockpit-focus-card fourteen"><span className="cockpit-fourteen-selected-summary"><WeatherPictogram code={selected.weatherCode} day size={42} title={selected.weatherLabel}/><span><b>{formatDate(selected.date,{weekday:'long',day:'2-digit',month:'2-digit'})}</b><small>{selected.weatherLabel}</small><small>{loading?'Weitere Modellläufe werden ergänzt.':`Konsistenz ${Math.round(selected.consistency)} % · ${selected.modelCount} Modelle`}</small></span></span><span className="cockpit-fourteen-selected-temps"><b className="climate-tone" style={{color:selectedMinTone?.color,background:selectedMinTone?.background,borderColor:selectedMinTone?.border}} title={selectedMinTone?.title}>{Math.round(selected.bestMin)}°</b><em>/</em><strong className="climate-tone" style={{color:selectedMaxTone?.color,background:selectedMaxTone?.background,borderColor:selectedMaxTone?.border}} title={selectedMaxTone?.title}>{Math.round(selected.bestMax)}°</strong><small>{Number.isFinite(selected.anomaly)?`Abweichung zum Klimamittel ${anomalyLabel(selected.anomaly)}`:'Klimamittel nicht verfügbar'}</small></span><span><b>{formatDecimalFixed(selected.bestPrecipitation,1)} mm · {Math.round(selected.bestPrecipitationProbability)} %</b><small>Niederschlagssignal</small></span><span className="cockpit-fourteen-selected-wind"><b><InlineWindArrow direction={selected.direction} gust={selected.bestGust} size={17}/>{cardinal(selected.direction)} {wind(selected.bestWind,unit)} <em className={windAlertClass(selected.bestGust)}>Böen {wind(selected.bestGust,unit)}</em></b><small>Wind und Böen</small></span></div>:null}
 </div>
}

function MiniRibbon({horizon,hours,days,ensemble,climate,timezone}:{horizon:ForecastHorizon;hours:Hour[];days:Day[];ensemble:EnsembleDay[];climate:ClimateDay[];timezone:string}){
 if(horizon==='short-term'){const points=regularShortTermPoints(hours,3).slice(0,8);return <span className="cockpit-mini-ribbon short">{points.map(point=>{const part=plausiblePrecipitation(point);return <i key={point.epoch} style={{height:`${Math.max(16,Math.round(point.probability))}%`,background:precipitationColor(point)}} title={`${formatClock(point.epoch,timezone)} · ${part.weatherLabel} · ${Math.round(point.probability)} %`}/>})}</span>}
 if(horizon==='seven-day'){const selected=days.slice(0,7);const minimum=Math.min(...selected.map(day=>day.min),0),maximum=Math.max(...selected.map(day=>day.max),1),range=Math.max(1,maximum-minimum);return <span className="cockpit-mini-ribbon seven">{selected.map(day=>{const left=((day.min-minimum)/range)*100,width=Math.max(8,(day.max-day.min)/range*100);return <i key={day.date}><b style={{left:`${left}%`,width:`${width}%`}}/></i>})}</span>}
 const series=ensembleSeries(ensemble,days,climate);return <span className="cockpit-mini-ribbon fourteen">{series.slice(0,14).map(item=><i key={item.date} style={{height:`${clamp(item.consistency,16,100)}%`,opacity:item.index>=7?.72:.96,background:consistencyColor(item.consistency)}} title={`${formatDate(item.date,{weekday:'short',day:'2-digit',month:'2-digit'})}: Konsistenz ${Math.round(item.consistency)} %`}/>)}</span>
}
function summaryByHorizon(horizon:ForecastHorizon,{hours,days,timezone,unit,sevenDaySummary,ensemble,scenarios,climate,shortPoints}:{hours:Hour[];days:Day[];timezone:string;unit:WindUnit;sevenDaySummary?:string;ensemble:EnsembleDay[];scenarios:EnsembleScenarioCluster[];climate:ClimateDay[];shortPoints?:ShortTermForecastPoint[]}){if(horizon==='short-term')return shortPoints?.length?shortTermPointSummary(shortPoints,unit):shortTermSummary(hours,timezone,unit);if(horizon==='seven-day')return sevenDaySummary||'Die nächsten sieben Tage werden in Tageskarten verdichtet.';const series=ensembleSeries(ensemble,days,climate);return uncertaintySummary(series,scenarios)}

function AnalysisReveal({open,onToggle,label='Ensemble-Analyse öffnen',children}:{open:boolean;onToggle:()=>void;label?:string;children?:ReactNode}){if(!children)return null;return <div className={`cockpit-analysis${open?' open':''}`}><button type="button" className="cockpit-analysis-toggle" onClick={onToggle} aria-expanded={open}><span><SlidersHorizontal size={18}/><strong>{label}</strong></span>{open?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</button>{open?<div className="cockpit-analysis-panel">{children}</div>:null}</div>}


export function ForecastCockpit({mode,hours,minutes15,days,ensemble,scenarios,climate,timezone,unit,selectedDate,onSelectedDate,availability,sourceLabel,updatedLabel,ensembleLoading,cockpitDetails,sevenDaySummary,shortTermAnchor,radarNowcast,location,showDwdPrecipitationTypeRadar,advancedMode}:ForecastCockpitProps){
 const availableHorizons=HORIZONS.filter(horizon=>horizonAvailable(horizon,availability));
 const [activeHorizon,setActiveHorizon]=useState<ForecastHorizon>(()=>readActiveHorizon(availability));
 const [analysisOpen,setAnalysisOpen]=useState(false);
 const shortPoints=useMemo(()=>buildShortTermForecast(minutes15,hours,timezone,Date.now(),shortTermAnchor,radarNowcast),[minutes15,hours,timezone,shortTermAnchor,radarNowcast]);
 const wrapRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{if(!horizonAvailable(activeHorizon,availability))setActiveHorizon(readActiveHorizon(availability))},[activeHorizon,availability]);
 useEffect(()=>{try{localStorage.setItem(ACTIVE_HORIZON_KEY,activeHorizon)}catch{}},[activeHorizon]);
 useEffect(()=>{setAnalysisOpen(false)},[activeHorizon]);
 useEffect(()=>{const node=wrapRef.current;if(!node)return;requestAnimationFrame(()=>node.scrollTo({top:0,left:0,behavior:'smooth'}))},[activeHorizon]);
 const headerSummary=summaryByHorizon(activeHorizon,{hours,days,timezone,unit,sevenDaySummary,ensemble,scenarios,climate,shortPoints});
 const activeAnalysis=activeHorizon==='fourteen-day'?cockpitDetails?.fourteenDay:undefined,footerHint=activeHorizon==='seven-day'?'Tag antippen: Stundenverlauf':activeHorizon==='fourteen-day'?'Tag antippen: Ensemblewerte':'Zeitpunkt antippen: Kurzfristdetails';
 return <section ref={wrapRef} className={`forecast-cockpit mode-${mode}`}><header className="cockpit-header"><small>MID Prognose-Cockpit</small><strong>Kurzfrist · 7 Tage · 14 Tage</strong><span>{headerSummary}</span></header><div className={`cockpit-tabs tabs-${availableHorizons.length}`}>{availableHorizons.map(horizon=>{const summary=summaryByHorizon(horizon,{hours,days,timezone,unit,sevenDaySummary,ensemble,scenarios,climate,shortPoints});return <button type="button" key={horizon} className={activeHorizon===horizon?'active':''} onClick={()=>setActiveHorizon(horizon)} aria-pressed={activeHorizon===horizon} title={`${horizonTitle(horizon)}: ${summary}`}><span className="cockpit-tab-icon" aria-hidden="true">{horizonIcon(horizon)}</span><span className="cockpit-tab-copy"><b>{horizonTitle(horizon)}</b><small>{summary}</small></span>{mode==='cockpit-ribbons'?<MiniRibbon horizon={horizon} hours={hours} days={days} ensemble={ensemble} climate={climate} timezone={timezone}/>:null}</button>})}</div><div className="cockpit-body">{activeHorizon==='short-term'?<ShortTermRibbon hours={hours} minutes15={minutes15} timezone={timezone} unit={unit} onSelectedDate={onSelectedDate} anchor={shortTermAnchor} radarNowcast={radarNowcast} location={location} showDwdPrecipitationTypeRadar={showDwdPrecipitationTypeRadar}/>:null}{activeHorizon==='seven-day'?<SevenDayBand days={days} hours={hours} minutes15={minutes15} climate={climate} unit={unit} selectedDate={selectedDate} onSelectedDate={onSelectedDate} summary={sevenDaySummary} hourlyDetail={cockpitDetails?.sevenDay}/>:null}{activeHorizon==='fourteen-day'?<FourteenDayHorizon ensemble={ensemble} days={days} scenarios={scenarios} climate={climate} selectedDate={selectedDate} onSelectedDate={onSelectedDate} loading={ensembleLoading} unit={unit} advancedMode={advancedMode}/>:null}<AnalysisReveal open={analysisOpen} onToggle={()=>setAnalysisOpen(value=>!value)}>{activeAnalysis}</AnalysisReveal></div><footer><span>{sourceLabel}</span><span>{updatedLabel}</span><button type="button" className="cockpit-footer-info" aria-label="Hinweis zur Prognosedarstellung"><Info size={14}/><small>{footerHint}</small></button></footer></section>
}

export default ForecastCockpit;
