import {buildWorkerUrl,fetchWorkerJson,workerBaseCandidates} from './workerClient';
import {loadAndSampleRadolan} from './RadolanRasterSource';
import type {ThunderstormNowcast} from './weather';

export type HeavyRainLevel='yellow'|'orange'|'red'|'purple';
export type RadolanFrame={time:string;fileUrl:string};
type RadolanMeta={coverage:boolean;provider:string;product:string;frames:RadolanFrame[];observedAt?:string;temporalResolutionMinutes?:number;nativeResolutionKm?:number;license?:string;error?:string};
type RvAccumulation={coverage:boolean;provider:string;product:string;observedAt?:string;forecast30:number;forecast60:number;forecast120:number;frames?:{time:string;leadMinutes:number;rateMmH:number;amountMm:number;source:string}[];approximate?:boolean;license?:string;error?:string};
type RainStation={available:boolean;name?:string;stationId?:string;observedAt?:string;distanceKm?:number;amount10m?:number;provider?:string;error?:string};
export type KostraDuration=30|60|360;
export type KostraThreshold={returnPeriodYears:number;amountMm:number};
export type KostraPoint={durationMinutes:KostraDuration;thresholds:KostraThreshold[]};
export type HeavyRainBase={coverage:boolean;observedAt?:string;observed15:number;observed30:number;observed60:number;observed180:number;observed360:number;nearby60:number;forecast30:number;forecast60:number;forecast120:number;radolanCompleteness:Record<string,number>;kostra:KostraPoint[];station?:RainStation;diagnostics:string[]};
export type HeavyRainInfo={level:HeavyRainLevel;headline:string;summary:string;source:string;flashFloodPotential:boolean;details:string[]};

type ZipEntry={name:string;method:number;compressedSize:number;uncompressedSize:number;dataOffset:number};
const kostraPromiseCache=new Map<KostraDuration,Promise<ArrayBuffer>>();
const pointCache=new Map<string,Promise<KostraPoint[]>>();

function abortError(signal?:AbortSignal){return signal?.reason instanceof Error?signal.reason:new DOMException('Vorgang abgebrochen.','AbortError')}
async function fetchWorkerBinary(mode:string,params:Record<string,string|number>,signal?:AbortSignal,timeoutMs=20000){const candidates=workerBaseCandidates('radar'),errors:string[]=[];for(const base of candidates){if(signal?.aborted)throw abortError(signal);const controller=new AbortController(),timer=window.setTimeout(()=>controller.abort(new DOMException('Zeitüberschreitung.','TimeoutError')),timeoutMs),abort=()=>controller.abort(signal?.reason);signal?.addEventListener('abort',abort,{once:true});try{const response=await fetch(buildWorkerUrl(base,mode,params),{signal:controller.signal,cache:'force-cache'});if(!response.ok)throw new Error(`HTTP ${response.status}`);return await response.arrayBuffer()}catch(error){if(signal?.aborted)throw abortError(signal);errors.push(error instanceof Error?error.message:String(error))}finally{window.clearTimeout(timer);signal?.removeEventListener('abort',abort)}}throw new Error(`${mode} nicht erreichbar${errors.length?`: ${errors.slice(-2).join(' · ')}`:''}`)}
function readU16(view:DataView,offset:number){return view.getUint16(offset,true)}function readU32(view:DataView,offset:number){return view.getUint32(offset,true)}
function zipEntries(buffer:ArrayBuffer):ZipEntry[]{const view=new DataView(buffer),bytes=new Uint8Array(buffer);let eocd=-1;for(let offset=Math.max(0,bytes.length-65557);offset<=bytes.length-22;offset++)if(readU32(view,offset)===0x06054b50)eocd=offset;if(eocd<0)throw new Error('KOSTRA-ZIP ohne Zentralverzeichnis.');const count=readU16(view,eocd+10),centralOffset=readU32(view,eocd+16),decoder=new TextDecoder(),entries:ZipEntry[]=[];let offset=centralOffset;for(let index=0;index<count;index++){if(readU32(view,offset)!==0x02014b50)break;const method=readU16(view,offset+10),compressedSize=readU32(view,offset+20),uncompressedSize=readU32(view,offset+24),nameLength=readU16(view,offset+28),extraLength=readU16(view,offset+30),commentLength=readU16(view,offset+32),localOffset=readU32(view,offset+42),name=decoder.decode(bytes.slice(offset+46,offset+46+nameLength)).replace(/\\/g,'/'),localNameLength=readU16(view,localOffset+26),localExtraLength=readU16(view,localOffset+28),dataOffset=localOffset+30+localNameLength+localExtraLength;entries.push({name,method,compressedSize,uncompressedSize,dataOffset});offset+=46+nameLength+extraLength+commentLength}return entries}
async function entryText(buffer:ArrayBuffer,entry:ZipEntry){const compressed=buffer.slice(entry.dataOffset,entry.dataOffset+entry.compressedSize);let raw:ArrayBuffer;if(entry.method===0)raw=compressed;else if(entry.method===8){const Stream=DecompressionStream as unknown as new(format:string)=>TransformStream<Uint8Array,Uint8Array>,stream=new Blob([compressed]).stream().pipeThrough(new Stream('deflate-raw'));raw=await new Response(stream).arrayBuffer()}else throw new Error(`ZIP-Kompression ${entry.method} wird nicht unterstützt.`);if(entry.uncompressedSize&&Math.abs(raw.byteLength-entry.uncompressedSize)>8)throw new Error('KOSTRA-ZIP-Eintrag ist unvollständig.');return new TextDecoder('utf-8').decode(raw)}
function returnPeriod(name:string){const upper=name.toUpperCase(),match=upper.match(/(?:HN|RN|UC)[_-]?0*(1|2|3|5|10|20|30|50|100)A(?:[_\-.]|$)/)||upper.match(/(?:^|[_-])T[_-]?0*(1|2|3|5|10|20|30|50|100)(?:A|J|YR|[_\-.])/);return match?Number(match[1]):undefined}
function q(phi:number,e2:number){const e=Math.sqrt(e2),sin=Math.sin(phi),denominator=1-e2*sin*sin;return(1-e2)*(sin/denominator-(1/(2*e))*Math.log((1-e*sin)/(1+e*sin)))}
function epsg3035(latDeg:number,lonDeg:number):[number,number]{const r=Math.PI/180,phi=latDeg*r,lambda=lonDeg*r,phi0=52*r,lambda0=10*r,e2=2/298.257222101-1/298.257222101**2,qp=q(Math.PI/2,e2),beta=Math.asin(q(phi,e2)/qp),beta0=Math.asin(q(phi0,e2)/qp),a=6378137,rq=a*Math.sqrt(qp/2),m0=Math.cos(phi0)/Math.sqrt(1-e2*Math.sin(phi0)**2),d=a*m0/(rq*Math.cos(beta0)),denominator=1+Math.sin(beta0)*Math.sin(beta)+Math.cos(beta0)*Math.cos(beta)*Math.cos(lambda-lambda0),b=rq*Math.sqrt(2/denominator);return[4321000+b*d*Math.cos(beta)*Math.sin(lambda-lambda0),3210000+(b/d)*(Math.cos(beta0)*Math.sin(beta)-Math.sin(beta0)*Math.cos(beta)*Math.cos(lambda-lambda0))]}
function ascValue(text:string,x:number,y:number){const lines=text.trim().split(/\r?\n/),header:Record<string,number>={};let dataStart=0;for(;dataStart<Math.min(12,lines.length);dataStart++){const match=lines[dataStart].trim().match(/^([A-Za-z_]+)\s+(-?\d+(?:[.,]\d+)?)/);if(!match)break;header[match[1].toLowerCase()]=Number(match[2].replace(',','.'))}const ncols=header.ncols,nrows=header.nrows,cell=header.cellsize,xll=header.xllcorner??header.xllcenter-cell/2,yll=header.yllcorner??header.yllcenter-cell/2;if(![ncols,nrows,cell,xll,yll].every(Number.isFinite))throw new Error('KOSTRA-ASC-Header unvollständig.');const col=Math.floor((x-xll)/cell),rowFromBottom=Math.floor((y-yll)/cell),row=nrows-1-rowFromBottom;if(col<0||col>=ncols||row<0||row>=nrows)return undefined;const values=lines[dataStart+row]?.trim().split(/\s+/);if(!values||col>=values.length)return undefined;const value=Number(values[col].replace(',','.'));return Number.isFinite(value)&&value>-90?value:undefined}
async function kostraBuffer(duration:KostraDuration,signal?:AbortSignal){let promise=kostraPromiseCache.get(duration);if(!promise){promise=fetchWorkerBinary('kostra-file',{duration},signal,30000).catch(error=>{kostraPromiseCache.delete(duration);throw error});kostraPromiseCache.set(duration,promise)}return promise}
async function kostraPointForDuration(duration:KostraDuration,lat:number,lon:number,signal?:AbortSignal):Promise<KostraPoint>{const buffer=await kostraBuffer(duration,signal),entries=zipEntries(buffer).filter(entry=>/\.asc$/i.test(entry.name)&&/(?:^|[_-])HN(?:[_\-.]|$)/i.test(entry.name)),[x,y]=epsg3035(lat,lon),thresholds:KostraThreshold[]=[];for(const entry of entries){const years=returnPeriod(entry.name);if(!years)continue;const value=ascValue(await entryText(buffer,entry),x,y);if(value!==undefined)thresholds.push({returnPeriodYears:years,amountMm:value})}thresholds.sort((a,b)=>a.returnPeriodYears-b.returnPeriodYears);if(thresholds.length<3)throw new Error(`KOSTRA ${duration} min: keine ausreichenden HN-Rasterwerte.`);return{durationMinutes:duration,thresholds}}
async function loadKostra(lat:number,lon:number,signal?:AbortSignal){const key=`${lat.toFixed(3)}:${lon.toFixed(3)}`;let promise=pointCache.get(key);if(!promise){promise=Promise.all(([30,60,360] as KostraDuration[]).map(duration=>kostraPointForDuration(duration,lat,lon,signal))).catch(error=>{pointCache.delete(key);throw error});pointCache.set(key,promise)}return promise}
function sumWindow(samples:{time:number;amount:number;nearby:number}[],latest:number,minutes:number,key:'amount'|'nearby'='amount'){return samples.filter(sample=>sample.time>latest-minutes*60000&&sample.time<=latest+60000).reduce((sum,sample)=>sum+sample[key],0)}
async function sampleFrames(frames:RadolanFrame[],lat:number,lon:number,signal?:AbortSignal){const output:{time:number;amount:number;nearby:number}[]=[];let cursor=0;const workers=Array.from({length:Math.min(6,frames.length)},async()=>{while(cursor<frames.length){const index=cursor++,frame=frames[index];try{const sample=await loadAndSampleRadolan(frame.fileUrl,lat,lon,signal),time=Date.parse(frame.time);if(sample.covered&&Number.isFinite(time))output.push({time,amount:sample.amountMm,nearby:sample.nearbyAmountMm})}catch(error){if(signal?.aborted)throw error}}});await Promise.all(workers);return output.sort((a,b)=>a.time-b.time)}
export async function loadHeavyRainBase(lat:number,lon:number,country:string|undefined,signal?:AbortSignal):Promise<HeavyRainBase>{const code=String(country||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase(),knownGermany=['DE','GERMANY','DEUTSCHLAND','ALLEMAGNE','GERMANIA'].includes(code),knownForeign=/^[A-Z]{2}$/.test(code)&&code!=='DE',germany=knownGermany||(!knownForeign&&lat>=47&&lat<=55.3&&lon>=5.4&&lon<=15.7);if(!germany)return{coverage:false,observed15:0,observed30:0,observed60:0,observed180:0,observed360:0,nearby60:0,forecast30:0,forecast60:0,forecast120:0,radolanCompleteness:{},kostra:[],diagnostics:['Außerhalb Deutschlands']};const diagnostics:string[]=[];const [metaResult,rvResult,stationResult,kostraResult]=await Promise.allSettled([fetchWorkerJson<RadolanMeta>('radolan-yw-meta',{lat,lon},{purpose:'radar',signal,timeoutMs:15000}),fetchWorkerJson<RvAccumulation>('rv-accumulation',{lat,lon,country:'DE'},{purpose:'radar',signal,timeoutMs:30000}),fetchWorkerJson<RainStation>('dwd-rain-station',{lat,lon,country:'DE'},{purpose:'radar',signal,timeoutMs:15000}),loadKostra(lat,lon,signal)]);const meta=metaResult.status==='fulfilled'?metaResult.value:null;if(!meta)diagnostics.push(`RADOLAN: ${metaResult.status==='rejected'?(metaResult.reason instanceof Error?metaResult.reason.message:String(metaResult.reason)):'nicht verfügbar'}`);const samples=meta?.frames?.length?await sampleFrames(meta.frames,lat,lon,signal):[],latest=samples.at(-1)?.time??Date.parse(meta?.observedAt||'');const completeness:Record<string,number>={};for(const duration of[15,30,60,180,360]){const actual=samples.filter(sample=>sample.time>latest-duration*60000&&sample.time<=latest+60000).length;completeness[String(duration)]=Math.min(1,actual/(duration/5))}const value=(duration:number,key:'amount'|'nearby'='amount')=>Number.isFinite(latest)&&completeness[String(duration)]>=.55?sumWindow(samples,latest,duration,key):0,rv=rvResult.status==='fulfilled'?rvResult.value:null,station=stationResult.status==='fulfilled'?stationResult.value:undefined,kostra=kostraResult.status==='fulfilled'?kostraResult.value:[];if(rvResult.status==='rejected')diagnostics.push(`RV: ${rvResult.reason instanceof Error?rvResult.reason.message:String(rvResult.reason)}`);if(kostraResult.status==='rejected')diagnostics.push(`KOSTRA: ${kostraResult.reason instanceof Error?kostraResult.reason.message:String(kostraResult.reason)}`);return{coverage:Boolean(meta?.coverage||rv?.coverage),observedAt:Number.isFinite(latest)?new Date(latest).toISOString():meta?.observedAt,observed15:value(15),observed30:value(30),observed60:value(60),observed180:value(180),observed360:value(360),nearby60:value(60,'nearby'),forecast30:rv?.forecast30??0,forecast60:rv?.forecast60??0,forecast120:rv?.forecast120??0,radolanCompleteness:completeness,kostra,station,diagnostics}}
function annuality(amount:number,point:KostraPoint|undefined){if(!point||amount<=0)return 0;let years=0;for(const threshold of point.thresholds)if(amount>=threshold.amountMm)years=threshold.returnPeriodYears;return years}
function formatMm(value:number){return value<10?value.toFixed(1).replace('.',','):String(Math.round(value))}
function konradText(thunder:ThunderstormNowcast|null){const cell=thunder?.nearest;if(!thunder?.available||!cell||cell.heavyRainFlag<=0||cell.relevanceDistanceKm>80)return'';const movement=cell.isApproaching&&Number.isFinite(cell.arrivalMinutes)?` · nähert sich${Number(cell.arrivalMinutes)>0?` in etwa ${Math.round(Number(cell.arrivalMinutes))} min`:''}`:'',distance=Math.round(cell.relevanceDistanceKm);return`KONRAD3D Starkregenstufe ${cell.heavyRainFlag} · Zelle ${distance} km${movement}`}
export function combineHeavyRain(base:HeavyRainBase|null,thunder:ThunderstormNowcast|null):HeavyRainInfo|null{if(!base?.coverage)return null;const cell=thunder?.nearest,konradRelevant=Boolean(thunder?.available&&cell&&(cell.currentDistanceKm<=40||(cell.isApproaching&&cell.relevanceDistanceKm<=80))),flag=konradRelevant&&cell?Number(cell.heavyRainFlag)||0:0,station=base.station?.available?Number(base.station.amount10m)||0:0,stationDistance=Number(base.station?.distanceKm),stationSignal=station>=5&&Number.isFinite(stationDistance)&&stationDistance<=15,a30=annuality(Math.max(base.observed30,base.forecast30),base.kostra.find(item=>item.durationMinutes===30)),a60=annuality(Math.max(base.observed60,base.forecast60),base.kostra.find(item=>item.durationMinutes===60)),a360=annuality(base.observed360,base.kostra.find(item=>item.durationMinutes===360)),years=Math.max(a30,a60,a360),actualSignal=base.observed15>=5||base.observed30>=8||base.observed60>=10||base.observed180>=20||base.observed360>=30||base.forecast30>=8||base.forecast60>=10||base.forecast120>=18||base.nearby60>=12||flag>0||stationSignal||years>=2;if(!actualSignal)return null;let level:HeavyRainLevel='yellow';if(base.observed60>=40||base.forecast60>=40||base.observed360>=70||years>=50||flag>=3)level='purple';else if(base.observed60>=25||base.forecast60>=25||base.observed360>=50||years>=20||flag>=2)level='red';else if(base.observed30>=15||base.observed60>=15||base.forecast60>=15||base.observed360>=35||base.nearby60>=20||years>=5||flag>=1)level='orange';const flashFloodPotential=(level==='red'||level==='purple')&&(base.observed180>=30||base.observed360>=45||base.forecast120>=30||years>=20),headline=flashFloodPotential?'Erhöhtes Starkregen-/Sturzflutpotenzial':level==='purple'?'Extremes Starkregensignal':level==='red'?'Heftiges Starkregensignal':level==='orange'?'Starkregensignal':'Erhöhter Regen',details=[`RADOLAN YW: ${formatMm(base.observed15)} mm/15 min · ${formatMm(base.observed30)} mm/30 min · ${formatMm(base.observed60)} mm/60 min · ${formatMm(base.observed180)} mm/3 h · ${formatMm(base.observed360)} mm/6 h${base.nearby60>base.observed60+2?` · 3-km-Umfeld bis ${formatMm(base.nearby60)} mm/60 min`:''}`,`DWD RV: +${formatMm(base.forecast30)} mm/30 min · +${formatMm(base.forecast60)} mm/60 min · +${formatMm(base.forecast120)} mm/120 min`];if(years)details.push(`KOSTRA-DWD-2020: höchste Einordnung etwa ${years}-jährlich (${a60===years?'60 min':a30===years?'30 min':'360 min'})`);const konrad=konradText(thunder);if(konrad)details.push(konrad);if(base.station?.available&&station>0)details.push(`${base.station.name||'DWD-Station'}: ${formatMm(station)} mm/10 min · ${Math.round(base.station.distanceKm||0)} km entfernt`);return{level,headline,summary:details.slice(0,2).join('. ')+'.',source:`${details.slice(2).join(' · ')}${details.length>2?' · ':''}Automatische meteorologische Analyse – keine amtliche Warnung`,flashFloodPotential,details}}
