import {formatDecimalFixed} from './format';
import {useLayoutEffect,useRef,useState} from 'react';
export function useSignalChartWidth(){const ref=useRef<HTMLDivElement>(null),[width,setWidth]=useState(760);useLayoutEffect(()=>{const node=ref.current;if(!node)return;const update=()=>setWidth(Math.max(240,Math.round(node.getBoundingClientRect().width)));update();const observer=new ResizeObserver(update);observer.observe(node);return()=>observer.disconnect()});return[ref,width] as const}
export type SignalPoint={id:string;label:string;mean:number|null;low?:number|null;high?:number|null;q25?:number|null;q75?:number|null;detail?:string};
export type SignalSeries={id:string;label:string;color:string;points:SignalPoint[]};
/** Discrete period intervals; gaps never become a connected forecast. */
export function HorizonSignalChart({series,unit,zero=true,label}:{series:SignalSeries[];unit:string;zero?:boolean;label:string}){
 const [chartRef,width]=useSignalChartWidth(),[selected,setSelected]=useState<string|null>(null);
 const points=series[0]?.points??[],values=series.flatMap(row=>row.points.flatMap(point=>[point.mean,point.low,point.high])).filter((value):value is number=>typeof value==='number'&&Number.isFinite(value)),minimum=zero?Math.min(0,...values):Math.min(...values),maximum=zero?Math.max(0,...values):Math.max(...values),span=Math.max(unit==='K'?2:1,maximum-minimum),lo=Number.isFinite(minimum)?minimum-span*.12:0,hi=Number.isFinite(maximum)?maximum+span*.12:1,height=250,left=60,right=22,top=22,bottom=48,x=(index:number)=>left+(index+.5)*(width-left-right)/Math.max(1,points.length),y=(value:number)=>top+(hi-value)/(hi-lo)*(height-top-bottom),ticks=Array.from({length:5},(_,index)=>lo+(hi-lo)*index/4);
 if(!values.length)return <div ref={chartRef} className="long-range-info"><p>Keine vergleichbaren Periodenwerte verfügbar. Fehlende Daten werden nicht als Nullsignal dargestellt.</p></div>;
 return <div ref={chartRef} className="long-range-chart" data-horizon-signal="period-intervals"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={label}>
  {ticks.map((tick,index)=><g key={index}><line className="grid" x1={left} x2={width-right} y1={y(tick)} y2={y(tick)}/><text className="axis-label" x={left-8} y={y(tick)+4} textAnchor="end">{formatDecimalFixed(tick,1)}</text></g>)}
  {zero&&lo<=0&&hi>=0?<line x1={left} x2={width-right} y1={y(0)} y2={y(0)} stroke="currentColor" strokeWidth={1.5} strokeDasharray="4 4" opacity={.65}/>:null}
  {series.map((row,rowIndex)=><g key={row.id} data-signal-series={row.id}>{row.points.map((point,index)=>{if(point.mean===null||!Number.isFinite(point.mean))return null;const px=x(index)+(rowIndex-(series.length-1)/2)*10;return <g key={point.id} role="button" tabIndex={0} aria-label={`${point.label}: ${formatDecimalFixed(point.mean,1)} ${unit} · ${point.detail??row.label}`} onClick={()=>setSelected(point.id)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setSelected(point.id)}}}><title>{`${row.label} · ${point.label}: ${formatDecimalFixed(point.mean,1)} ${unit}${point.detail?` · ${point.detail}`:''}${point.low!=null&&point.high!=null?` · P10–P90 ${formatDecimalFixed(point.low,1)} bis ${formatDecimalFixed(point.high,1)} ${unit}`:''}`}</title>{point.low!=null&&point.high!=null?<><line x1={px} x2={px} y1={y(point.low)} y2={y(point.high)} stroke={row.color} strokeWidth={2} opacity={.55}/><path d={`M ${px-4} ${y(point.low)} H ${px+4} M ${px-4} ${y(point.high)} H ${px+4}`} stroke={row.color}/></>:null}{point.q25!=null&&point.q75!=null?<line x1={px} x2={px} y1={y(point.q25)} y2={y(point.q75)} stroke={row.color} strokeWidth={8} opacity={.3}/>:null}<circle cx={px} cy={y(point.mean)} r={4} fill={row.color}/></g>})}</g>)}
  {points.filter((_,index)=>index%Math.max(1,Math.ceil(points.length/(width<500?4:8)))===0).map(point=><text key={point.id} className="month-label" x={x(points.indexOf(point))} y={height-20} textAnchor="middle">{point.label}</text>)}
 </svg><div className="long-range-model-line-legend">{series.map(row=><span key={row.id}><i style={{borderTopColor:row.color}}/><b>{row.label}</b></span>)}<span><b>{unit} · schmal P10–P90{series.some(row=>row.points.some(point=>point.q25!=null&&point.q75!=null))?' · breit P25–P75':''}</b></span></div>{selected?<p role="status">{series.map(row=>{const point=row.points.find(item=>item.id===selected);return point&&point.mean!==null?`${row.label} · ${point.label}: ${formatDecimalFixed(point.mean,1)} ${unit}${point.low!=null&&point.high!=null?` · P10–P90 ${formatDecimalFixed(point.low,1)} bis ${formatDecimalFixed(point.high,1)} ${unit}`:''} · ${point.detail??''}`:null}).filter(Boolean).join(' · ')}</p>:null}</div>;
}
