import {loadPx250Metadata} from './Px250Source';
import {projectWgs84,projectionFromDefinition} from './radarProjection';

type H5Node={value?:ArrayLike<number>|unknown;shape?:number[];attrs?:Record<string,unknown>};
type H5File={get(path:string):H5Node};
export type HxBoundaryCheck={available:boolean;observedAt?:string;ageMinutes?:number;centerRate:number;siteSupport:number;nearestWetKm?:number;strongEcho:boolean;source:'DWD HX 250 m';error?:string};

function text(value:unknown):string{if(typeof value==='string')return value.replace(/\0/g,'').trim();if(value instanceof Uint8Array)return new TextDecoder().decode(value).replace(/\0/g,'').trim();if(ArrayBuffer.isView(value)){const view=value as unknown as ArrayLike<number>;return Array.from({length:view.length},(_,index)=>String.fromCharCode(Number(view[index])||0)).join('').replace(/\0/g,'').trim()}return String(value??'').replace(/\0/g,'').trim()}
function scalar(value:unknown):number|undefined{if(ArrayBuffer.isView(value)){const view=value as unknown as ArrayLike<number>;value=view.length?view[0]:undefined}else if(Array.isArray(value))value=value[0];const n=Number(value);return Number.isFinite(n)?n:undefined}
function attr(node:H5Node|undefined,...names:string[]){const attrs=node?.attrs??{};for(const name of names){if(name in attrs)return attrs[name];const key=Object.keys(attrs).find(item=>item.toLowerCase()===name.toLowerCase());if(key)return attrs[key]}return undefined}
function get(file:H5File,path:string){try{return file.get(path)}catch{return undefined}}
function selectReflectivity(file:H5File){for(let dataset=1;dataset<=5;dataset++)for(let data=1;data<=6;data++){const base=`dataset${dataset}/data${data}`,node=get(file,`${base}/data`),what=get(file,`${base}/what`),quantity=text(attr(what,'quantity')).toUpperCase();if(node?.value&&node.shape?.length===2&&/DBZH|DBZ|TH/.test(quantity))return{node,what,quantity}}throw new Error('Kein Reflektivitätsraster im DWD-HX-HDF5 gefunden.')}
function rateFromDbz(dbz:number){if(!Number.isFinite(dbz)||dbz<-10)return 0;const z=Math.pow(10,dbz/10);return Math.max(0,Math.pow(Math.max(0,z/200),1/1.6))}

export async function loadHxBoundaryCheck(lat:number,lon:number,siteThreshold=.05,signal?:AbortSignal):Promise<HxBoundaryCheck>{
 try{
  const meta=await loadPx250Metadata(lat,lon,signal),observed=Date.parse(meta.observedAt||''),ageMinutes=Number.isFinite(observed)?Math.round((Date.now()-observed)/60000):undefined;
  if(!meta.available||meta.product!=='hx'||!meta.fileUrl||!Number.isFinite(observed)||Math.abs(Number(ageMinutes))>35)return{available:false,observedAt:meta.observedAt,ageMinutes,centerRate:0,siteSupport:0,strongEcho:false,source:'DWD HX 250 m',error:meta.reason||'Kein frisches nationales HX-Komposit.'};
  const response=await fetch(meta.fileUrl,{cache:'force-cache',signal});if(!response.ok)throw new Error(`DWD HX HTTP ${response.status}`);const buffer=await response.arrayBuffer();if(buffer.byteLength<1024)throw new Error('DWD-HX-Datei ist unvollständig.');const hdf5=await import('jsfive'),file=new hdf5.File(buffer,meta.fileUrl) as unknown as H5File,where=get(file,'where')??get(file,'dataset1/where'),projection=projectionFromDefinition(text(attr(where,'projdef','projection_definition','proj4'))),selection=selectReflectivity(file),shape=selection.node.shape??[],height=Number(shape[0]),width=Number(shape[1]),values=selection.node.value as ArrayLike<number>;
  if(!projection||!width||!height||!values||values.length<width*height)throw new Error('HX-Projektion oder Rastergeometrie ist unvollständig.');
  const projected=projectWgs84(lat,lon,projection);if(!projected)throw new Error('Standort kann nicht in das HX-Raster projiziert werden.');const xScale=Math.abs(scalar(attr(where,'xscale','x_scale'))??250),yScale=Math.abs(scalar(attr(where,'yscale','y_scale'))??250),llX=scalar(attr(where,'LL_x','ll_x')),ulX=scalar(attr(where,'UL_x','ul_x')),urY=scalar(attr(where,'UR_y','ur_y')),ulY=scalar(attr(where,'UL_y','ul_y'));
  const candidates:[number,number][]=[];if(llX!==undefined&&urY!==undefined)candidates.push([(projected[0]-llX)/xScale,(urY-projected[1])/yScale]);if(ulX!==undefined&&ulY!==undefined)candidates.push([(projected[0]-ulX)/xScale,(ulY-projected[1])/yScale]);candidates.push([projected[0]/xScale,-projected[1]/yScale]);const selectedIndex=candidates.find(([column,row])=>column>=-1&&column<width+1&&row>=-1&&row<height+1);if(!selectedIndex)throw new Error('Standort liegt außerhalb des HX-Rasters.');const column=Math.round(selectedIndex[0]),row=Math.round(selectedIndex[1]),gain=scalar(attr(selection.what,'gain'))??.5,offset=scalar(attr(selection.what,'offset'))??-32.5,nodata=scalar(attr(selection.what,'nodata'))??65535,undetect=scalar(attr(selection.what,'undetect'))??0,read=(x:number,y:number)=>{if(x<0||x>=width||y<0||y>=height)return 0;const raw=Number(values[y*width+x]);if(!Number.isFinite(raw)||raw===nodata||raw===undetect)return 0;return rateFromDbz(raw*gain+offset)},centerRate=read(column,row);let wet=0,total=0,nearest=Infinity;
  const threshold=Math.max(.035,siteThreshold*.7);for(let dy=-12;dy<=12;dy++)for(let dx=-12;dx<=12;dx++){const rate=read(column+dx,row+dy);if(Math.abs(dx)<=2&&Math.abs(dy)<=2){total++;if(rate>=threshold)wet++}if(rate>=threshold)nearest=Math.min(nearest,Math.hypot(dx*xScale,dy*yScale)/1000)}const siteSupport=total?wet/total:0;
  return{available:true,observedAt:meta.observedAt,ageMinutes,centerRate:Number(centerRate.toFixed(3)),siteSupport:Number(siteSupport.toFixed(2)),nearestWetKm:Number.isFinite(nearest)?Number(nearest.toFixed(2)):undefined,strongEcho:centerRate>=Math.max(.5,siteThreshold*4)||siteSupport>=.72,source:'DWD HX 250 m'};
 }catch(error){if(signal?.aborted)throw error;return{available:false,centerRate:0,siteSupport:0,strongEcho:false,source:'DWD HX 250 m',error:error instanceof Error?error.message:String(error)}}
}
