import {useMemo,useRef,useState} from 'react';
import {Check,ClipboardCopy,Cloud,CloudDownload,CloudUpload,FileCheck2,RefreshCw,ShieldCheck,Smartphone} from 'lucide-react';
import {readLastICloudBackup,restoreICloudBackup,saveICloudBackup,type ICloudBackupSummary} from './iCloudBackup';

function formatDate(value?:string){if(!value)return'Noch keine Sicherung';const date=new Date(value);return Number.isFinite(date.getTime())?date.toLocaleString('de-DE',{dateStyle:'medium',timeStyle:'short'}):value}
function formatBytes(bytes:number){if(!Number.isFinite(bytes)||bytes<=0)return'–';if(bytes<1024*1024)return`${Math.round(bytes/1024)} KB`;return`${(bytes/1024/1024).toLocaleString('de-DE',{maximumFractionDigits:1})} MB`}
function summaryText(summary:ICloudBackupSummary|null){if(!summary)return'Favoriten, App-Einstellungen, Standorte und Wetterzwillingsdaten können als eine Datei in iCloud Drive gesichert werden.';return`${summary.localEntries} App-Einträge · ${summary.weatherTwinLocations} Wetterzwilling-Orte · ${formatBytes(summary.bytes)}`}
function standalone(){const nav=navigator as Navigator&{standalone?:boolean};return window.matchMedia?.('(display-mode: standalone)').matches===true||nav.standalone===true}

export function ICloudBackupSettings({advancedMode=false}:{advancedMode?:boolean}){
 const inputRef=useRef<HTMLInputElement>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[last,setLast]=useState<ICloudBackupSummary|null>(readLastICloudBackup),[prepareSync,setPrepareSync]=useState(true),[handoffCode,setHandoffCode]=useState(''),[copied,setCopied]=useState(false),status=useMemo(()=>summaryText(last),[last]),isStandalone=standalone();
 const backup=async()=>{setBusy(true);setMessage('Sicherung wird vorbereitet …');try{const result=await saveICloudBackup();setLast(result.summary);setMessage(result.mode==='share'?'Teilen-Menü geöffnet. Dort „In Dateien sichern“ und iCloud Drive auswählen.':'Sicherungsdatei wurde heruntergeladen. Sie kann anschließend in iCloud Drive abgelegt werden.')}catch(error){if((error as DOMException)?.name==='AbortError')setMessage('Sicherung abgebrochen.');else setMessage(error instanceof Error?error.message:'Sicherung fehlgeschlagen.')}finally{setBusy(false)}};
 const copyCode=async()=>{if(!handoffCode)return;try{await navigator.clipboard.writeText(handoffCode);setCopied(true);window.setTimeout(()=>setCopied(false),1800)}catch{setMessage('Der Übernahmecode konnte nicht automatisch kopiert werden. Bitte markieren und kopieren.')}};
 const restore=async(file?:File)=>{if(!file)return;if(!window.confirm('MID-Sicherung vollständig wiederherstellen? Gesicherte Favoriten, Einstellungen, Standorte und Wetterzwillingsdaten ersetzen den lokalen Stand.'))return;setBusy(true);setMessage('Sicherung wird geprüft und vollständig wiederhergestellt …');setHandoffCode('');try{const result=await restoreICloudBackup(file,{prepareDeviceSync:prepareSync});setLast(result.summary);setHandoffCode(result.sync.formattedCode||'');if(isStandalone){setMessage(`Wiederhergestellt: ${result.summary.localEntries} App-Einträge und ${result.weatherTwin.locations} Wetterzwilling-Orte. MID wird neu geladen …${result.sync.error?` Cloud-Abgleich: ${result.sync.error}`:''}`);window.setTimeout(()=>location.reload(),1100)}else if(result.sync.enabled){setMessage(`Wiederherstellung abgeschlossen. iOS kann eine installierte Web-App nicht automatisch aus Safari öffnen. Öffne MID vom Home-Bildschirm und verbinde sie einmal mit dem unten angezeigten Übernahmecode.${result.sync.uploaded?' Der vollständige Stand liegt verschlüsselt zum Abruf bereit.':result.sync.error?` Cloud-Abgleich derzeit nicht möglich: ${result.sync.error}`:''}`)}else setMessage('Wiederherstellung abgeschlossen. Lade diese Ansicht neu oder spiele die Datei direkt innerhalb der installierten MID-Web-App ein.')}catch(error){setMessage(error instanceof Error?error.message:'Wiederherstellung fehlgeschlagen.')}finally{setBusy(false);if(inputRef.current)inputRef.current.value=''}};
 return <section className="icloud-backup-settings"><header><Cloud size={22}/><span><strong>iCloud-Drive-Sicherung</strong><small>Vollständige Sicherung gegen Datenverlust nach PWA-Neuinstallation oder Gerätewechsel.</small></span></header><div className="icloud-backup-status"><FileCheck2 size={19}/><span><strong>{formatDate(last?.createdAt)}</strong><small>{status}</small></span></div><label className="icloud-backup-sync-option"><input type="checkbox" checked={prepareSync} onChange={event=>setPrepareSync(event.target.checked)}/><Smartphone size={18}/><span><b>Geräteübernahme vorbereiten</b><small>Nach dem Import wird ein verschlüsselter Geräteverbund angelegt oder wiederverwendet. So kann die installierte iOS-Web-App denselben Stand übernehmen.</small></span></label><div className="icloud-backup-actions"><button type="button" disabled={busy} onClick={()=>void backup()}><CloudUpload size={17}/>In iCloud Drive sichern</button><button type="button" disabled={busy} onClick={()=>inputRef.current?.click()}><CloudDownload size={17}/>Sicherung wiederherstellen</button><input ref={inputRef} hidden type="file" accept=".midbackup,application/json" onChange={event=>void restore(event.target.files?.[0])}/></div>{handoffCode&&<div className="icloud-backup-handoff"><header><Smartphone size={18}/><span><strong>Übernahmecode für die installierte MID-App</strong><small>In MID vom Home-Bildschirm: Einstellungen → Daten &amp; Synchronisation → Bestehenden Geräteverbund verwenden.</small></span></header><code>{handoffCode}</code><div><button type="button" onClick={()=>void copyCode()}>{copied?<Check size={16}/>:<ClipboardCopy size={16}/>} {copied?'Kopiert':'Code kopieren'}</button><button type="button" onClick={()=>location.reload()}><RefreshCw size={16}/>Diese Ansicht neu laden</button></div></div>}<div className="icloud-backup-note"><ShieldCheck size={16}/><span><b>Gesichert werden:</b> Favoriten, Gruppen und Profile, aktiver Standort, App- und Diagrammeinstellungen, Modulzustände, lokale Wetterzwilling-Profile sowie das vollständige Wetterzwilling-Langzeitarchiv. Gerätegebundene Push-Abonnements, Stationspasswörter und Zugangsschlüssel bleiben aus Sicherheitsgründen ausgeschlossen.</span></div>{advancedMode&&<small className="icloud-backup-technical">Technik: Sicherungsformat v2 mit Integritätsprüfung und optionaler Wiederherstellung des verschlüsselten Geräteverbunds. iOS trennt Safari- und Home-Bildschirm-Speicher teilweise; deshalb dient der Übernahmecode als sichere Brücke.</small>}{message&&<p className="icloud-backup-message" role="status">{message}</p>}</section>
}
