import {useMemo,useRef,useState} from 'react';
import {Check,ClipboardCopy,CloudDownload,CloudUpload,FileCheck2,RefreshCw,ShieldCheck,Smartphone} from 'lucide-react';
import {readLastICloudBackup,restoreICloudBackup,saveICloudBackup,type ICloudBackupSummary} from './iCloudBackup';
import {PORTABLE_USER_DATA_EXCLUDED,PORTABLE_USER_DATA_INCLUDED} from './portableUserData';

function formatDate(value?:string){if(!value)return'Noch keine Sicherheitskopie';const date=new Date(value);return Number.isFinite(date.getTime())?date.toLocaleString('de-DE',{dateStyle:'medium',timeStyle:'short'}):value}
function formatBytes(bytes:number){if(!Number.isFinite(bytes)||bytes<=0)return'–';if(bytes<1024*1024)return`${Math.round(bytes/1024)} KB`;return`${(bytes/1024/1024).toLocaleString('de-DE',{maximumFractionDigits:1})} MB`}
function summaryText(summary:ICloudBackupSummary|null){if(!summary)return'Zusätzliche manuelle Sicherheitskopie für Wiederherstellung, Gerätewechsel oder Neuinstallation.';return`${summary.localEntries} portable App-Einträge · ${summary.weatherTwinLocations} Wetterzwilling-Orte · ${formatBytes(summary.bytes)}`}
function standalone(){const nav=navigator as Navigator&{standalone?:boolean};return window.matchMedia?.('(display-mode: standalone)').matches===true||nav.standalone===true}

export function ICloudBackupSettings({advancedMode=false}:{advancedMode?:boolean}){
 const inputRef=useRef<HTMLInputElement>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[last,setLast]=useState<ICloudBackupSummary|null>(readLastICloudBackup),[prepareSync,setPrepareSync]=useState(true),[handoffCode,setHandoffCode]=useState(''),[copied,setCopied]=useState(false),status=useMemo(()=>summaryText(last),[last]),isStandalone=standalone();
 const backup=async()=>{setBusy(true);setMessage('Sicherheitskopie wird vorbereitet …');try{const result=await saveICloudBackup();setLast(result.summary);setMessage(result.mode==='share'?'Teilen-Menü geöffnet. „In Dateien sichern“ und anschließend iCloud Drive wählen.':'Sicherheitskopie wurde heruntergeladen und kann in iCloud Drive abgelegt werden.')}catch(error){if((error as DOMException)?.name==='AbortError')setMessage('Sicherung abgebrochen.');else setMessage(error instanceof Error?error.message:'Sicherung fehlgeschlagen.')}finally{setBusy(false)}};
 const copyCode=async()=>{if(!handoffCode)return;try{await navigator.clipboard.writeText(handoffCode);setCopied(true);window.setTimeout(()=>setCopied(false),1800)}catch{setMessage('Code konnte nicht automatisch kopiert werden. Bitte markieren und kopieren.')}};
 const restore=async(file?:File)=>{if(!file)return;if(!window.confirm('MID-Sicherheitskopie vollständig einspielen? Die enthaltenen portablen Einstellungen, Favoriten, Standorte und Wetterzwilling-Daten ersetzen den lokalen Stand dieser Web-App.'))return;setBusy(true);setMessage('Sicherheitskopie wird geprüft und vollständig eingespielt …');setHandoffCode('');try{const result=await restoreICloudBackup(file,{prepareDeviceSync:prepareSync});setLast(result.summary);setHandoffCode(result.sync.formattedCode||'');if(isStandalone){setMessage(`Wiederhergestellt: ${result.summary.localEntries} App-Einträge und ${result.weatherTwin.locations} Wetterzwilling-Orte. Diese Web-App wird neu geladen …${result.sync.error?` Synchronisation: ${result.sync.error}`:''}`);window.setTimeout(()=>location.reload(),1100)}else if(result.sync.enabled){setMessage(`Die Daten wurden in dieser Browser-Ansicht wiederhergestellt. Eine bereits installierte Home-Bildschirm-Web-App besitzt auf iOS teilweise einen eigenen Speicher und kann nicht automatisch geöffnet werden. Dort einmal den unten angezeigten Code unter „Daten & Synchronisation“ eingeben.${result.sync.uploaded?' Der vollständige Stand liegt verschlüsselt bereit.':result.sync.error?` Cloud-Abgleich derzeit nicht möglich: ${result.sync.error}`:''}`)}else setMessage('Wiederherstellung abgeschlossen. Diese Ansicht neu laden. Für eine andere installierte Web-App die Sicherheitskopie dort ebenfalls einspielen oder die automatische Synchronisation verwenden.')}catch(error){setMessage(error instanceof Error?error.message:'Wiederherstellung fehlgeschlagen.')}finally{setBusy(false);if(inputRef.current)inputRef.current.value=''}};
 return <section className="icloud-backup-settings"><header><FileCheck2 size={22}/><span><strong>Manuelle iCloud-Sicherheitskopie</strong><small>Zusätzlicher Schutz vor Datenverlust. Eine Sicherungsdatei ist kein laufender Geräteabgleich.</small></span></header><div className="icloud-backup-status"><FileCheck2 size={19}/><span><strong>{formatDate(last?.createdAt)}</strong><small>{status}</small></span></div><label className="icloud-backup-sync-option"><input type="checkbox" checked={prepareSync} onChange={event=>setPrepareSync(event.target.checked)}/><Smartphone size={18}/><span><b>Nach dem Einspielen für andere Web-Apps bereitstellen</b><small>Erzeugt oder übernimmt einen verschlüsselten Geräteverbund. Andere installierte MID-Web-Apps können den wiederhergestellten Stand anschließend mit dem angezeigten Code vollständig übernehmen.</small></span></label><div className="icloud-backup-actions"><button type="button" disabled={busy} onClick={()=>void backup()}><CloudUpload size={17}/>Sicherheitskopie erstellen</button><button type="button" disabled={busy} onClick={()=>inputRef.current?.click()}><CloudDownload size={17}/>Sicherheitskopie einspielen</button><input ref={inputRef} hidden type="file" accept=".midbackup,application/json" onChange={event=>void restore(event.target.files?.[0])}/></div>{handoffCode&&<div className="icloud-backup-handoff"><header><Smartphone size={18}/><span><strong>Code für eine weitere MID-Web-App</strong><small>In der installierten Web-App: Einstellungen → Daten &amp; Synchronisation → „Diese Web-App mit vorhandenem Stand verbinden“.</small></span></header><code>{handoffCode}</code><div><button type="button" onClick={()=>void copyCode()}>{copied?<Check size={16}/>:<ClipboardCopy size={16}/>} {copied?'Kopiert':'Code kopieren'}</button><button type="button" onClick={()=>location.reload()}><RefreshCw size={16}/>Diese Ansicht neu laden</button></div></div>}<div className="icloud-backup-note"><ShieldCheck size={16}/><span><b>Enthalten:</b> {PORTABLE_USER_DATA_INCLUDED.join(', ')}. <b>Nicht enthalten:</b> {PORTABLE_USER_DATA_EXCLUDED.join(', ')}.</span></div>{advancedMode&&<small className="icloud-backup-technical">Technik: Sicherungsformat v3 mit SHA-256-Integritätsprüfung und optionaler Übernahme des verschlüsselten Geräteverbunds. Safari und eine installierte iOS-Web-App können getrennte Speicherbereiche besitzen; deshalb ist für die andere Web-App einmal der Synchronisationscode erforderlich.</small>}{message&&<p className="icloud-backup-message" role="status">{message}</p>}</section>
}
