import {useMemo,useRef,useState} from 'react';
import {Cloud,CloudDownload,CloudUpload,FileCheck2,ShieldCheck} from 'lucide-react';
import {readLastICloudBackup,restoreICloudBackup,saveICloudBackup,type ICloudBackupSummary} from './iCloudBackup';

function formatDate(value?:string){if(!value)return'Noch keine Sicherung';const date=new Date(value);return Number.isFinite(date.getTime())?date.toLocaleString('de-DE',{dateStyle:'medium',timeStyle:'short'}):value}
function formatBytes(bytes:number){if(!Number.isFinite(bytes)||bytes<=0)return'–';if(bytes<1024*1024)return`${Math.round(bytes/1024)} KB`;return`${(bytes/1024/1024).toLocaleString('de-DE',{maximumFractionDigits:1})} MB`}
function summaryText(summary:ICloudBackupSummary|null){if(!summary)return'Favoriten, App-Einstellungen und Wetterzwillingsdaten können als eine Datei in iCloud Drive gesichert werden.';return`${summary.localEntries} App-Einträge · ${summary.weatherTwinLocations} Wetterzwilling-Orte · ${formatBytes(summary.bytes)}`}

export function ICloudBackupSettings({advancedMode=false}:{advancedMode?:boolean}){
 const inputRef=useRef<HTMLInputElement>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[last,setLast]=useState<ICloudBackupSummary|null>(readLastICloudBackup),status=useMemo(()=>summaryText(last),[last]);
 const backup=async()=>{setBusy(true);setMessage('Sicherung wird vorbereitet …');try{const result=await saveICloudBackup();setLast(result.summary);setMessage(result.mode==='share'?'Teilen-Menü geöffnet. Dort „In Dateien sichern“ und iCloud Drive auswählen.':'Sicherungsdatei wurde heruntergeladen. Sie kann anschließend in iCloud Drive abgelegt werden.')}catch(error){if((error as DOMException)?.name==='AbortError')setMessage('Sicherung abgebrochen.');else setMessage(error instanceof Error?error.message:'Sicherung fehlgeschlagen.')}finally{setBusy(false)}};
 const restore=async(file?:File)=>{if(!file)return;if(!window.confirm('MID-Sicherung wiederherstellen? Gesicherte Favoriten, Einstellungen und Wetterzwillingsdaten überschreiben gleichnamige aktuelle Werte.'))return;setBusy(true);setMessage('Sicherung wird geprüft und wiederhergestellt …');try{const result=await restoreICloudBackup(file);setLast(result.summary);setMessage(`Wiederhergestellt: ${result.summary.localEntries} App-Einträge und ${result.weatherTwin.locations} Wetterzwilling-Orte. MID wird neu geladen …`);window.setTimeout(()=>location.reload(),900)}catch(error){setMessage(error instanceof Error?error.message:'Wiederherstellung fehlgeschlagen.')}finally{setBusy(false);if(inputRef.current)inputRef.current.value=''}};
 return <section className="icloud-backup-settings"><header><Cloud size={22}/><span><strong>iCloud-Drive-Sicherung</strong><small>Externe Sicherung gegen Datenverlust nach PWA-Neuinstallation oder Gerätewechsel.</small></span></header><div className="icloud-backup-status"><FileCheck2 size={19}/><span><strong>{formatDate(last?.createdAt)}</strong><small>{status}</small></span></div><div className="icloud-backup-actions"><button type="button" disabled={busy} onClick={()=>void backup()}><CloudUpload size={17}/>In iCloud Drive sichern</button><button type="button" disabled={busy} onClick={()=>inputRef.current?.click()}><CloudDownload size={17}/>Sicherung wiederherstellen</button><input ref={inputRef} hidden type="file" accept=".midbackup,application/json" onChange={event=>void restore(event.target.files?.[0])}/></div><div className="icloud-backup-note"><ShieldCheck size={16}/><span><b>Gesichert werden:</b> Favoriten, Gruppen und Profile, App- und Diagrammeinstellungen, lokale Wetterzwilling-Profile sowie das vollständige Wetterzwilling-Langzeitarchiv. Zugangsschlüssel, Stationspasswörter, temporäre Wettercaches und Push-Abonnements werden bewusst nicht exportiert.</span></div>{advancedMode&&<small className="icloud-backup-technical">Technik: lokale MID-Daten plus IndexedDB-Wetterzwillingarchiv in einer integritätsgeprüften <code>.midbackup</code>-Datei. Auf iPhone/iPad öffnet MID das Teilen-Menü; dort „In Dateien sichern“ → „iCloud Drive“ wählen.</small>}{message&&<p className="icloud-backup-message" role="status">{message}</p>}</section>
}
