import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {CalendarRange,CloudRain,ExternalLink,Info,RefreshCw,ThermometerSun} from 'lucide-react';
import {formatDecimalFixed} from './format';
import {loadSeasonalForecast,type SeasonalForecastBundle,type SeasonalMonth,type SeasonalPointModel} from './seasonalForecast';
import type {Location} from './weather';

type Props={location:Location;locationName:string;advancedMode:boolean};
type Metric='temperature'|'precipitation';
type ChartUnit='K'|'%'|'mm/Tag';
type CombinedMonth={date:string;label:string;mean:number|null;low:number|null;q25:number|null;q75:number|null;high:number|null;modelCount:number;contributorLabels:string[]};
function finite(values:(number|null|undefined)[]){return values.filter((value):value is number=>Number.isFinite(value))}
function mean(values:number[]){return values.length?values.reduce((sum,value)=>sum+value,0)/values.length:null}
function niceAbsMax(values:number[],minimum:number){const max=Math.max(minimum,...values.map(value=>Math.abs(value)));if(max<=1)return Math.ceil(max*2)/2;if(max<=3)return Math.ceil(max);if(max<=10)return Math.ceil(max/2)*2;return Math.ceil(max/10)*10}
function pointX(index:number,count:number,left:number,width:number,padding=34){if(count<=1)return left+width/2;const usable=Math.max(0,width-padding*2);return left+padding+index*usable/(count-1)}
function temperatureAnomalyColor(value:number){const abs=Math.abs(value);if(abs<.15)return'#9ba8b2';if(value<0)return abs>=3?'#24439b':abs>=1.5?'#3f7ec4':abs>=.6?'#78b7df':'#b5d8ef';return abs>=3?'#a71930':abs>=1.5?'#db4c48':abs>=.6?'#ef8a72':'#f4c6b8'}
function precipitationAnomalyColor(value:number){const abs=Math.abs(value);if(abs<.08)return'#a6afb5';if(value<0)return abs>=2?'#8c510a':abs>=1?'#bf812d':abs>=.35?'#dfc27d':'#f1dfb5';return abs>=2?'#2166ac':abs>=1?'#35978f':abs>=.35?'#80cdc1':'#c7e9df'}
function metricColor(value:number,metric:Metric){return metric==='temperature'?temperatureAnomalyColor(value):precipitationAnomalyColor(value)}
function singleValue(month:SeasonalMonth,metric:Metric,unit:ChartUnit){if(metric==='temperature')return month.temperatureAnomaly;return unit==='%'?month.precipitationAnomalyPercent:month.precipitationAnomaly}
function singleLow(month:SeasonalMonth,metric:Metric,unit:ChartUnit){if(metric==='temperature')return month.temperatureAnomalyLow;return unit==='%'?month.precipitationAnomalyPercentLow:month.precipitationAnomalyLow}
function singleQ25(month:SeasonalMonth,metric:Metric,unit:ChartUnit){if(metric==='temperature')return month.temperatureAnomalyQ25;return unit==='%'?month.precipitationAnomalyPercentQ25:month.precipitationAnomalyQ25}
function singleQ75(month:SeasonalMonth,metric:Metric,unit:ChartUnit){if(metric==='temperature')return month.temperatureAnomalyQ75;return unit==='%'?month.precipitationAnomalyPercentQ75:month.precipitationAnomalyQ75}
function singleHigh(month:SeasonalMonth,metric:Metric,unit:ChartUnit){if(metric==='temperature')return month.temperatureAnomalyHigh;return unit==='%'?month.precipitationAnomalyPercentHigh:month.precipitationAnomalyHigh}
function formatValue(value:number,unit:ChartUnit){if(unit==='K')return`${value>=0?'+':''}${formatDecimalFixed(value,1)} K`;if(unit==='%')return`${value>=0?'+':''}${Math.round(value)} %`;return`${value>=0?'+':''}${formatDecimalFixed(value,2)} mm/Tag`}
function anomalySummary(model:SeasonalPointModel,metric:Metric){const unit:ChartUnit=metric==='temperature'?'K':model.months.some(month=>Number.isFinite(month.precipitationAnomalyPercent))?'%':'mm/Tag',rows=model.months.map(month=>({month,value:singleValue(month,metric,unit)})).filter((row):row is{month:SeasonalMonth;value:number}=>Number.isFinite(row.value));if(!rows.length)return'Noch keine belastbaren Monatsanomalien verfügbar.';const strongest=rows.reduce((best,row)=>Math.abs(row.value)>Math.abs(best.value)?row:best,rows[0]);return`${strongest.month.label}: ${formatValue(strongest.value,unit)} gegenüber dem Modellklima.`}
function quantile(values:number[],q:number){if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b),position=(sorted.length-1)*q,lower=Math.floor(position),upper=Math.ceil(position);if(lower===upper)return sorted[lower];const weight=position-lower;return sorted[lower]*(1-weight)+sorted[upper]*weight}
function buildCombinedMonths(models:SeasonalPointModel[],metric:Metric):CombinedMonth[]{const labels=new Map<string,string>();models.forEach(model=>model.months.forEach(month=>labels.set(month.date,labels.get(month.date)??month.label)));return[...labels.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([date,label])=>{const contributors=models.flatMap(model=>{const month=model.months.find(entry=>entry.date===date);if(!month)return[];const center=metric==='temperature'?month.temperatureAnomaly:month.precipitationAnomaly;if(!Number.isFinite(center))return[];return[{label:model.family,center:Number(center)}]});const centers=contributors.map(item=>item.center);return{date,label,mean:mean(centers),low:quantile(centers,.1),q25:quantile(centers,.25),q75:quantile(centers,.75),high:quantile(centers,.9),modelCount:contributors.length,contributorLabels:contributors.map(item=>item.label)}})}
function combinedSummary(months:CombinedMonth[],unit:ChartUnit){const rows=months.filter((row):row is CombinedMonth&{mean:number}=>Number.isFinite(row.mean));if(!rows.length)return'Noch kein gemeinsames Multi-Modell-Signal verfügbar.';const strongest=rows.reduce((best,row)=>Math.abs(row.mean)>Math.abs(best.mean)?row:best,rows[0]);return`${strongest.label}: ${formatValue(strongest.mean,unit)} im gleichgewichteten Multi-Modell-Mittel.`}
function areaPath(months:{mean:number|null;low:number|null;high:number|null}[],x:(index:number)=>number,y:(value:number)=>number){const upper=months.map((month,index)=>Number.isFinite(month.high)?`${index?'L':'M'} ${x(index)} ${y(Number(month.high))}`:null).filter(Boolean) as string[],lower=[...months].reverse().map((month,index)=>{const actual=months.length-1-index;return Number.isFinite(month.low)?`L ${x(actual)} ${y(Number(month.low))}`:null}).filter(Boolean) as string[];return upper.length&&lower.length?`${upper.join(' ')} ${lower.join(' ')} Z`:''}
function linePath(months:{mean:number|null}[],x:(index:number)=>number,y:(value:number)=>number){return months.reduce((path,month,index)=>Number.isFinite(month.mean)?`${path}${path?' L':'M'} ${x(index)} ${y(Number(month.mean))}`:path,'')}
function PlumeChart({months,metric,unit,combined=false}:{months:CombinedMonth[]|SeasonalMonth[];metric:Metric;unit:ChartUnit;combined?:boolean}){const width=760,height=250,left=58,right=18,top=24,bottom=46,plotWidth=width-left-right,plotHeight=height-top-bottom,normalised=months.map(month=>'modelCount'in month?month:{date:month.date,label:month.label,mean:singleValue(month,metric,unit),low:singleLow(month,metric,unit),q25:singleQ25(month,metric,unit),q75:singleQ75(month,metric,unit),high:singleHigh(month,metric,unit),modelCount:1,contributorLabels:[]}),valid=finite(normalised.flatMap(month=>[month.mean,month.low,month.q25,month.q75,month.high])),minimum=unit==='K'?1:unit==='%'?25:.5,absMax=niceAbsMax(valid,minimum),y=(value:number)=>top+(absMax-value)/(absMax*2)*plotHeight,x=(index:number)=>pointX(index,normalised.length,left,plotWidth,36),ticks=[absMax,absMax/2,0,-absMax/2,-absMax],outerPlume=areaPath(normalised,x,y),innerCount=Math.max(1,Math.ceil(normalised.length/2)),innerRows=normalised.map((month,index)=>index<innerCount?{mean:month.mean,low:month.q25,high:month.q75}:{mean:month.mean,low:null,high:null}),innerPlume=areaPath(innerRows,x,y),line=linePath(normalised,x,y);return <div className={`long-range-chart ${metric} ${combined?'combined':'single'}`}><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={metric==='temperature'?'Monatliche Temperaturanomalie':'Monatliche Niederschlagsanomalie'}>{ticks.map(tick=><g key={tick}><line x1={left} x2={width-right} y1={y(tick)} y2={y(tick)} className={tick===0?'zero':'grid'}/><text x={left-9} y={y(tick)+4} textAnchor="end" className="axis-label">{unit==='K'?`${tick>0?'+':''}${formatDecimalFixed(tick,1)} K`:unit==='%'?`${tick>0?'+':''}${Math.round(tick)} %`:`${tick>0?'+':''}${formatDecimalFixed(tick,1)}`}</text></g>)}{normalised.map((month,index)=><g key={month.date}><line x1={x(index)} x2={x(index)} y1={top} y2={height-bottom} className="vertical-grid"/><text x={x(index)} y={height-19} textAnchor="middle" className="month-label">{month.label}</text></g>)}{outerPlume?<path d={outerPlume} className="anomaly-plume outer"/>:null}{innerPlume?<path d={innerPlume} className="anomaly-plume inner"/>:null}{line?<path d={line} className="anomaly-mean-line"/>:null}{normalised.map((month,index)=>Number.isFinite(month.mean)?<g key={`dot-${month.date}`}><circle cx={x(index)} cy={y(Number(month.mean))} r={5} className="anomaly-dot" style={{fill:metricColor(Number(month.mean),metric)}}/><title>{`${month.label}: ${formatValue(Number(month.mean),unit)}${combined&&month.modelCount>1?` · ${month.modelCount} Modellfamilien`:''}`}</title></g>:null)}</svg><div className={`long-range-scale ${metric}`} aria-hidden="true"><span>{metric==='temperature'?'kälter':'trockener'}</span><i/><span>normal</span><i/><span>{metric==='temperature'?'wärmer':'feuchter'}</span></div></div>}

function dwdQualityLabel(classification:'better'|'similar'|'worse'|'unknown'){return classification==='better'?'signifikant besser':classification==='similar'?'vergleichbar':classification==='worse'?'schwächer':'noch ohne Einstufung'}
function dwdQualityDetails(metric:{mse:number|null;msess:number|null;rpss:number|null;correlation:number|null}){const values:string[]=[];if(Number.isFinite(metric.mse))values.push(`MSE ${formatDecimalFixed(Number(metric.mse),2)}`);if(Number.isFinite(metric.msess))values.push(`MSESS ${formatDecimalFixed(Number(metric.msess),2)}`);if(Number.isFinite(metric.rpss))values.push(`RPSS ${formatDecimalFixed(Number(metric.rpss),2)}`);if(Number.isFinite(metric.correlation))values.push(`r ${formatDecimalFixed(Number(metric.correlation),2)}`);return values.join(' · ')}
function sourceStateLabel(state:SeasonalForecastBundle['c3sNumericStatus']['state']){return state==='live'?'Numerisch aktiv':state==='configured'?'Datenpfad bereit':state==='outside-domain'?'außerhalb Datengebiet':state==='error'?'Quelle gestört':'noch nicht konfiguriert'}
function dwdPrecipValue(period:NonNullable<SeasonalForecastBundle['dwdPerspective']>['periods'][number]){if(Number.isFinite(period.precipitationAnomalyPercent))return`${Number(period.precipitationAnomalyPercent)>=0?'+':''}${Math.round(Number(period.precipitationAnomalyPercent))} %`;if(Number.isFinite(period.precipitationAnomaly))return`${Number(period.precipitationAnomaly)>=0?'+':''}${formatDecimalFixed(Number(period.precipitationAnomaly),2)} mm/Tag`;return'–'}

export default function LongRangePanel({location,locationName,advancedMode}:Props){
 const locationKey=`${location.latitude.toFixed(2)},${location.longitude.toFixed(2)}`,modelStorageKey=`mid:long-range:selected-model:${locationKey}`,scrollStorageKey=`mid:long-range:model-scroll:${locationKey}`;
 const[data,setData]=useState<SeasonalForecastBundle|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(''),[infoOpen,setInfoOpen]=useState(false),[selectedModelId,setSelectedModelId]=useState(''),[legendOpen,setLegendOpen]=useState(()=>{try{return localStorage.getItem('mid:long-range:legend-details')==='1'}catch{return false}});
 const controllerRef=useRef<AbortController|null>(null),modelSelectorRef=useRef<HTMLDivElement|null>(null);
 const load=useCallback(async(refresh=false)=>{
  controllerRef.current?.abort();const controller=new AbortController();controllerRef.current=controller;
  if(refresh)setRefreshing(true);else setLoading(true);setError('');
  try{
   const value=await loadSeasonalForecast(location.latitude,location.longitude,controller.signal,{refresh});if(controller.signal.aborted)return;
   setData(value);let stored='';try{stored=localStorage.getItem(modelStorageKey)||''}catch{}setSelectedModelId((current:string)=>value.pointModels.some((item:SeasonalPointModel)=>item.id===stored)?stored:value.pointModels.some((item:SeasonalPointModel)=>item.id===current)?current:(value.pointModels[0]?.id??''));
  }catch(reason){if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:'Langfristdaten konnten nicht geladen werden.')}
  finally{if(controllerRef.current===controller)controllerRef.current=null;if(!controller.signal.aborted){setLoading(false);setRefreshing(false)}}
 },[location.latitude,location.longitude,modelStorageKey]);
 useEffect(()=>{void load(false);return()=>{controllerRef.current?.abort();controllerRef.current=null}},[load]);
 useEffect(()=>{if(!selectedModelId)return;try{localStorage.setItem(modelStorageKey,selectedModelId)}catch{}},[modelStorageKey,selectedModelId]);
 useEffect(()=>{try{localStorage.setItem('mid:long-range:legend-details',legendOpen?'1':'0')}catch{}},[legendOpen]);
 const models=data?.pointModels??[];
 useEffect(()=>{const node=modelSelectorRef.current;if(!node)return;try{const saved=Number(localStorage.getItem(scrollStorageKey));if(Number.isFinite(saved)&&saved>0)node.scrollLeft=saved}catch{}let frame=0;const save=()=>{if(frame)return;frame=window.requestAnimationFrame(()=>{frame=0;try{localStorage.setItem(scrollStorageKey,String(Math.round(node.scrollLeft)))}catch{}})};node.addEventListener('scroll',save,{passive:true});return()=>{if(frame)window.cancelAnimationFrame(frame);node.removeEventListener('scroll',save);try{localStorage.setItem(scrollStorageKey,String(Math.round(node.scrollLeft)))}catch{}}},[scrollStorageKey,models.length]);
 const model=models.find((item:SeasonalPointModel)=>item.id===selectedModelId)??models[0],months=model?.months??[],tempCombined=useMemo(()=>buildCombinedMonths(models,'temperature'),[models]),precipCombined=useMemo(()=>buildCombinedMonths(models,'precipitation'),[models]),multiModel=models.length>=2,precipUnit:ChartUnit=model?.months.some((month:SeasonalMonth)=>Number.isFinite(month.precipitationAnomalyPercent))?'%':'mm/Tag',showLegendDetails=advancedMode||legendOpen;
 const cacheLabel=data?.cacheStatus==='fresh-cache'?`Cache · ${data.cacheAgeMinutes??0} min`:data?.cacheStatus==='stale-cache'?`Fallback-Cache · ${data.cacheAgeMinutes??0} min`:data?.cacheStatus==='mixed-stale'?`teilweise Cache · ${data.cacheAgeMinutes??0} min`:'';
 return <section className="long-range-panel">
  <header className="long-range-head"><div><span>LANGFRIST</span><h3>Monatstrend · {locationName}</h3><p>Großräumige Monatsanomalien am jeweils nächstgelegenen Modellgitterpunkt – inklusive Ensemble- und Multi-Modell-Unsicherheit.</p>{cacheLabel?<small className="long-range-cache-state">{cacheLabel}</small>:null}</div><div className="long-range-head-actions"><button type="button" onClick={()=>void load(true)} disabled={refreshing} aria-label="Saisonmodelle ausdrücklich aktualisieren" title="Saisonmodelle neu abrufen"><RefreshCw size={17} className={refreshing?'spin':''}/></button><button type="button" className={infoOpen?'active':''} onClick={()=>setInfoOpen((value:boolean)=>!value)} aria-label="Methodik"><Info size={17}/></button></div></header>
  {infoOpen?<div className="long-range-info"><p>Die Rauchfahnen kombinieren ausschließlich numerisch geladene unabhängige Modellfamilien. C3S-Punktdaten werden als echte numerische Ensemblewerte geladen; Kartenfarben werden niemals zu Zahlen zurückgerechnet. DWD GCFS2.2 / EPISODES wird als eigenständige Deutschland-Perspektive geführt, weil die DWD-Auswertung 3-Monats-Zeiträume und eigene Qualitätsmaße verwendet.</p><p>Die langsamen Saisonquellen werden gemeinsam für vier Stunden zwischengespeichert. Bei einem temporären Quellfehler kann MID einen höchstens 36 Stunden alten letzten erfolgreichen Stand verwenden; „Aktualisieren“ fordert bewusst einen neuen Abruf an.</p></div>:null}
  {loading&&!models.length?<div className="long-range-loading"><RefreshCw className="spin" size={18}/>Saisonmodelle werden geladen …</div>:null}
  {error&&!models.length?<div className="long-range-error"><strong>Langfristdaten derzeit nicht verfügbar</strong><small>{error}</small></div>:null}
  {error&&models.length?<div className="long-range-info"><p><b>Aktualisierung nicht vollständig:</b> {error}</p></div>:null}
  {data?<div className="long-range-gateway-status"><span className={`state-${data.c3sNumericStatus.state}`}><b>C3S/CDS</b><em>{sourceStateLabel(data.c3sNumericStatus.state)}</em>{advancedMode?<small>{data.c3sNumericStatus.detail}</small>:null}</span>{data.dwdEpisodesStatus.state!=='outside-domain'?<span className={`state-${data.dwdEpisodesStatus.state}`}><b>DWD GCFS2.2 / EPISODES</b><em>{sourceStateLabel(data.dwdEpisodesStatus.state)}</em>{advancedMode?<small>{data.dwdEpisodesStatus.detail}</small>:null}</span>:null}</div>:null}
  {multiModel?<section className="long-range-overview"><header><div><strong>Echtes Multi-Modell</strong><small>{models.map((item:SeasonalPointModel)=>item.family).join(' + ')} · gleichgewichtete Modellfamilien</small></div><div className="long-range-family-chips">{models.map((item:SeasonalPointModel)=><span key={item.id}>{item.family}<small>{item.ensembleMembers>1?`${item.ensembleMembers} Member`:'Ensemble-Mittel'}</small></span>)}</div></header><div className="long-range-grid"><article><header><ThermometerSun size={18}/><div><strong>Temperatur · Rauchfahne</strong><small>{combinedSummary(tempCombined,'K')}</small></div></header><PlumeChart months={tempCombined} metric="temperature" unit="K" combined/>{showLegendDetails?<footer><span>außen P10–P90 · innen P25–P75 bis Hälfte</span><span>Linie = Multi-Modell-Mittel</span></footer>:null}</article><article><header><CloudRain size={18}/><div><strong>Niederschlag · Rauchfahne</strong><small>{combinedSummary(precipCombined,'mm/Tag')}</small></div></header><PlumeChart months={precipCombined} metric="precipitation" unit="mm/Tag" combined/>{showLegendDetails?<footer><span>Abweichung zum jeweiligen Modellklima in mm/Tag</span><span>außen P10–P90 · innen P25–P75 bis Hälfte</span></footer>:null}</article></div></section>:models.length===1?<div className="long-range-info"><p><b>Ensemble verfügbar, Multi-Modell noch nicht:</b> aktuell konnte nur {models[0].family} numerisch geladen werden. MID zeigt keine künstliche Multi-Modell-Linie aus Varianten derselben Modellfamilie.</p></div>:null}
  {(models.length>1||!advancedMode)?<div className="long-range-controls section-sticky-controls">{models.length>1?<div className="long-range-model-selector" ref={modelSelectorRef}>{models.map((item:SeasonalPointModel)=><button key={item.id} type="button" className={item.id===model?.id?'active':''} onClick={()=>setSelectedModelId(item.id)}><b>{item.family}</b><small>{item.ensembleMembers>1?`${item.ensembleMembers} Member · `:''}{item.horizonMonths} Monate</small></button>)}</div>:null}{!advancedMode?<button type="button" className={`long-range-legend-toggle${legendOpen?' active':''}`} onClick={()=>setLegendOpen(value=>!value)} aria-expanded={legendOpen}>{legendOpen?'Legende kompakt':'Legende Details'}</button>:null}</div>:null}
  {model&&months.length?<><div className="long-range-source-line"><span><CalendarRange size={15}/><b>{model.label}</b><small>{model.ensembleMembers} Member · {model.gridPoint?`${model.gridPoint.gridLabel} · ${Math.round(model.gridPoint.distanceKm)} km entfernt`:model.provider}</small></span><em>Stand {model.runLabel}</em></div><div className="long-range-grid"><article><header><ThermometerSun size={18}/><div><strong>Temperatur · {model.family}</strong><small>{anomalySummary(model,'temperature')}</small></div></header><PlumeChart months={months} metric="temperature" unit="K"/>{showLegendDetails?<footer><span>blau = kälter · rot = wärmer</span><span>{model.uncertaintyLabel}</span></footer>:null}</article><article><header><CloudRain size={18}/><div><strong>Niederschlag · {model.family}</strong><small>{anomalySummary(model,'precipitation')}</small></div></header><PlumeChart months={months} metric="precipitation" unit={precipUnit}/>{showLegendDetails?<footer><span>braun = trockener · blau/türkis = feuchter</span><span>{model.uncertaintyLabel}</span></footer>:null}</article></div></>:null}
  {data?.dwdPerspective?<section className="long-range-dwd"><header><div><span>DWD DEUTSCHLAND-PERSPEKTIVE</span><h4>{data.dwdPerspective.modelVersion} / {data.dwdPerspective.downscaling}</h4><p>3-Monats-Anomalien · Referenz {data.dwdPerspective.referencePeriod}{data.dwdPerspective.gridPoint?` · ${data.dwdPerspective.gridPoint.gridLabel} · ${Math.round(data.dwdPerspective.gridPoint.distanceKm)} km entfernt`:''}</p></div><em>Stand {data.dwdPerspective.runLabel}</em></header><div className="long-range-dwd-periods">{data.dwdPerspective.periods.map(period=><article key={period.id}><header><strong>{period.label}</strong>{period.startDate&&period.endDate?<small>{period.startDate} – {period.endDate}</small>:null}</header><div className="long-range-dwd-values"><span><small>Temperatur</small><b>{Number.isFinite(period.temperatureAnomaly)?`${Number(period.temperatureAnomaly)>=0?'+':''}${formatDecimalFixed(Number(period.temperatureAnomaly),1)} K`:'–'}</b><em className={`quality-${period.temperatureQuality.classification}`}>{dwdQualityLabel(period.temperatureQuality.classification)}</em>{advancedMode&&dwdQualityDetails(period.temperatureQuality)?<small>{dwdQualityDetails(period.temperatureQuality)}</small>:null}</span><span><small>Niederschlag</small><b>{dwdPrecipValue(period)}</b><em className={`quality-${period.precipitationQuality.classification}`}>{dwdQualityLabel(period.precipitationQuality.classification)}</em>{advancedMode&&dwdQualityDetails(period.precipitationQuality)?<small>{dwdQualityDetails(period.precipitationQuality)}</small>:null}</span></div></article>)}</div>{advancedMode?<footer>Qualität gegenüber Referenz/Klimatologie: MID zeigt die gelieferten DWD-QA-Maße MSE/Pearson-r und – sofern der Adapter die DWD-Skill-Auswertung mitliefert – MSESS/RPSS. Keine Skill-Einstufung wird aus Kartenfarben abgeleitet.</footer>:null}</section>:data&&data.dwdEpisodesStatus.state!=='outside-domain'?<section className="long-range-dwd pending"><header><div><span>DWD DEUTSCHLAND-PERSPEKTIVE</span><h4>GCFS2.2 / EPISODES</h4><p>{data.dwdEpisodesStatus.state==='unconfigured'?'Numerische Punktdaten sind für dieses Modell derzeit noch nicht verfügbar.':data.dwdEpisodesStatus.detail}</p></div></header>{advancedMode?<small>MID verwendet dafür keine archivierten GCFS2.1-Karten oder aus Kartenfarben abgeleitete Werte.</small>:null}</section>:null}
  {data?<section className="long-range-models"><header><div><span>C3S MULTI-MODELL</span><h4>Saisonale Großmodelle</h4><small className="long-range-c3s-status">{sourceStateLabel(data.c3sNumericStatus.state)}{data.c3sNumericStatus.modelCount?` · ${data.c3sNumericStatus.modelCount} Systeme lokal numerisch`:''}</small></div><a href={data.c3sCatalogueUrl} target="_blank" rel="noreferrer">C3S-Vergleich <ExternalLink size={13}/></a></header><div className="long-range-model-strip">{data.c3sModels.map((item:SeasonalForecastBundle['c3sModels'][number])=><article key={item.id} className={item.numericalState==='live'?'live':''}><div className="long-range-model-title"><strong>{item.label}</strong><b>{item.numericalState==='live'?'Numerisch':'Katalog'}</b></div><small>{item.system}</small><span>{item.horizon}</span><em>{item.gridLabel}</em></article>)}</div>{advancedMode?<div className="long-range-method"><b>Methodik</b><p>C3S: lokale numerische Rauchfahnen mit Ensemble-Mittel und echten Memberwerten; ECMWF und NOAA-NMME bleiben als bestehende numerische Baseline verfügbar. Nicht konfigurierte C3S-Zentren bleiben sichtbar, fließen aber nicht in die Rauchfahne ein. DWD GCFS2.2 / EPISODES ist ein separater Deutschland-Pfad mit 3-Monats-Anomalien und Qualitätsmaßen. Kartenfarben werden an keiner Stelle numerisch rekonstruiert.</p></div>:null}</section>:null}
 </section>
}
