import {useEffect,useMemo,useState} from 'react';
import {CloudRain,ThermometerSun} from 'lucide-react';
import {formatDecimalFixed} from './format';
import type {SeasonalMonth,SeasonalPointModel} from './seasonalForecast';

type Metric='temperature'|'precipitation';
type Props={models:SeasonalPointModel[]};
type ModelSeries={model:SeasonalPointModel;values:(number|null)[];color:string;dash?:string};

const MODEL_COLORS=[
 'var(--model-series-1)','var(--model-series-2)','var(--model-series-3)','var(--model-series-4)','var(--model-series-5)',
 'var(--model-series-6)','var(--model-series-7)','var(--model-series-8)','var(--model-series-9)','var(--model-series-10)','var(--model-series-11)','var(--model-series-12)'
];
const MODEL_DASH_CYCLES=['','7 3','3 3','10 3 2 3'];

function finite(value:number|null|undefined):value is number{return Number.isFinite(value)}
function metricValue(month:SeasonalMonth|undefined,metric:Metric){if(!month)return null;return metric==='temperature'?month.temperatureAnomaly:month.precipitationAnomaly}
function formatValue(value:number|undefined|null,metric:Metric){if(!finite(value))return'–';return metric==='temperature'?`${value>=0?'+':''}${formatDecimalFixed(value,1)} K`:`${value>=0?'+':''}${formatDecimalFixed(value,2)} mm/Tag`}
function niceAbsMax(values:number[],metric:Metric){const minimum=metric==='temperature'?1:.5,max=Math.max(minimum,...values.map(value=>Math.abs(value)));if(max<=1)return Math.ceil(max*2)/2;if(max<=3)return Math.ceil(max);if(max<=10)return Math.ceil(max/2)*2;return Math.ceil(max/10)*10}
function linePath(values:(number|null)[],x:(index:number)=>number,y:(value:number)=>number){let path='';let active=false;values.forEach((value,index)=>{if(!finite(value)){active=false;return;}path+=`${active?' L':'M'} ${x(index)} ${y(value)}`;active=true;});return path}

export default function LongRangeModelComparison({models}:Props){
 const months=useMemo(()=>{const map=new Map<string,string>();models.forEach(model=>model.months.forEach(month=>map.set(month.date,map.get(month.date)??month.label)));return[...map.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([date,label])=>({date,label}))},[models]);
 const[metric,setMetric]=useState<Metric>(()=>{try{return localStorage.getItem('mid:long-range:comparison-metric')==='precipitation'?'precipitation':'temperature'}catch{return'temperature'}});
 useEffect(()=>{try{localStorage.setItem('mid:long-range:comparison-metric',metric)}catch{}},[metric]);
 if(models.length<2||!months.length)return null;
 const series:ModelSeries[]=models.map((model,index)=>({model,values:months.map(row=>metricValue(model.months.find(month=>month.date===row.date),metric)),color:MODEL_COLORS[index%MODEL_COLORS.length],dash:MODEL_DASH_CYCLES[Math.floor(index/MODEL_COLORS.length)%MODEL_DASH_CYCLES.length]})).filter(item=>item.values.some(finite));
 if(series.length<2)return null;
 const width=780,height=286,left=58,right=18,top=24,bottom=50,plotWidth=width-left-right,plotHeight=height-top-bottom,allValues=series.flatMap(item=>item.values.filter(finite)),absMax=niceAbsMax(allValues,metric),x=(index:number)=>months.length<=1?left+plotWidth/2:left+index*plotWidth/(months.length-1),y=(value:number)=>top+(absMax-value)/(absMax*2)*plotHeight,ticks=[absMax,absMax/2,0,-absMax/2,-absMax],Icon=metric==='temperature'?ThermometerSun:CloudRain;
 return <section className="long-range-models long-range-model-comparison"><header><div><span>EINZELMODELLE GEMEINSAM</span><h4>{metric==='temperature'?'Temperatur':'Niederschlag'} · alle verfügbaren numerischen Modelle</h4><small className="long-range-c3s-status">Jede Linie ist ein tatsächlich geladenes unabhängiges Modellsystem bzw. dessen Ensemble-Mittel; reine Katalogverweise werden nicht dargestellt.</small></div></header><div className="long-range-controls section-sticky-controls"><div className="long-range-model-selector long-range-comparison-metric"><button type="button" className={metric==='temperature'?'active':''} onClick={()=>setMetric('temperature')}><b>Temperatur</b><small>Anomalie zum Modellklima</small></button><button type="button" className={metric==='precipitation'?'active':''} onClick={()=>setMetric('precipitation')}><b>Niederschlag</b><small>Anomalie zum Modellklima</small></button></div></div><article className="long-range-model-overlay"><header><Icon size={18}/><div><strong>{series.length} Modellsysteme in einem Diagramm</strong><small>Null-Linie = jeweiliges Modellklima · Unterschiede bleiben bewusst sichtbar.</small></div></header><div className={`long-range-chart long-range-model-overlay-chart ${metric}`}><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${metric==='temperature'?'Temperatur':'Niederschlag'}: alle verfügbaren Saisonmodelle gemeinsam`}>{ticks.map(tick=><g key={tick}><line x1={left} x2={width-right} y1={y(tick)} y2={y(tick)} className={tick===0?'zero':'grid'}/><text x={left-9} y={y(tick)+4} textAnchor="end" className="axis-label">{metric==='temperature'?`${tick>0?'+':''}${formatDecimalFixed(tick,1)} K`:`${tick>0?'+':''}${formatDecimalFixed(tick,1)}`}</text></g>)}{months.map((month,index)=><g key={month.date}><line x1={x(index)} x2={x(index)} y1={top} y2={height-bottom} className="vertical-grid"/><text x={x(index)} y={height-19} textAnchor="middle" className="month-label">{month.label}</text></g>)}{series.map(item=>{const path=linePath(item.values,x,y);return <g key={item.model.id} className="long-range-model-series">{path?<path d={path} fill="none" stroke={item.color} strokeWidth={2.5} strokeDasharray={item.dash||undefined} strokeLinecap="round" strokeLinejoin="round"/>:null}{item.values.map((value,index)=>finite(value)?<circle key={`${item.model.id}-${months[index].date}`} cx={x(index)} cy={y(value)} r={3.3} fill={item.color} className="model-series-dot"><title>{`${item.model.family} · ${months[index].label}: ${formatValue(value,metric)}`}</title></circle>:null)}</g>})}</svg></div><div className="long-range-model-line-legend">{series.map(item=><span key={item.model.id} title={`${item.model.label} · Stand ${item.model.runLabel}`}><i style={{borderTopColor:item.color,borderTopStyle:item.dash?'dashed':'solid'}}/><b>{item.model.family}</b><small>{item.model.ensembleMembers>1?`${item.model.ensembleMembers} Member`:'Ensemble-Mittel'}</small></span>)}</div></article></section>
}
