import {Children,isValidElement,useEffect,useMemo,type ReactElement,type ReactNode} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import * as maplibregl from 'maplibre-gl';
import {GeoJsonLayers,HtmlMarker,MidMapLibre,RasterTileLayer,WmsTileLayer,registerMapLayerOrder,unregisterMapLayerOrder,useMidMap,type MidMap,type MidGeoLayer} from './MapLibreCore';

type LatLon=[number,number];
type DivIcon={html?:string;className?:string;iconSize?:[number,number];iconAnchor?:[number,number];popupAnchor?:[number,number]};
type PathOptions={color?:string;weight?:number;opacity?:number;fillColor?:string;fillOpacity?:number;dashArray?:string;lineCap?:string;lineJoin?:string;className?:string;pane?:string};
type ChildInfo={popup?:ReactNode;tooltip?:{children:ReactNode;className?:string;opacity?:number}};

function staticHtml(value:ReactNode){try{return renderToStaticMarkup(<>{value}</>)}catch{return String(value??'')}}
function childInfo(children:ReactNode):ChildInfo{const info:ChildInfo={};Children.forEach(children,child=>{if(!isValidElement(child))return;const element=child as ReactElement<any>;if(element.type===Popup)info.popup=element.props.children;else if(element.type===Tooltip)info.tooltip={children:element.props.children,className:element.props.className,opacity:element.props.opacity}});return info}
function safeId(value:string){return value.replace(/[^a-zA-Z0-9_-]/g,'_')}
let compatSequence=0;
function useCompatId(prefix:string){return useMemo(()=>`${prefix}-${++compatSequence}`,[])}
function lonLat(value:LatLon){return [value[1],value[0]] as [number,number]}
function toLineCoords(positions:any):any{return Array.isArray(positions?.[0]?.[0])?positions.map((part:any)=>part.map((point:LatLon)=>lonLat(point))):positions.map((point:LatLon)=>lonLat(point))}
function circlePolygon(center:LatLon,radiusMeters:number,steps=48){const [lat,lon]=center,latRad=lat*Math.PI/180,earth=6371008.8,angular=Math.max(1,radiusMeters)/earth,coordinates:Array<[number,number]>=[];for(let i=0;i<=steps;i++){const bearing=2*Math.PI*i/steps,sinLat=Math.sin(latRad)*Math.cos(angular)+Math.cos(latRad)*Math.sin(angular)*Math.cos(bearing),outLat=Math.asin(sinLat),outLon=lon*Math.PI/180+Math.atan2(Math.sin(bearing)*Math.sin(angular)*Math.cos(latRad),Math.cos(angular)-Math.sin(latRad)*Math.sin(outLat));coordinates.push([outLon*180/Math.PI,outLat*180/Math.PI])}return coordinates}
function dashArray(value?:string){if(!value)return undefined;const parts=value.trim().split(/[ ,]+/).map(Number).filter(Number.isFinite);return parts.length?parts:undefined}
const PANE_Z_INDEX=new Map<string,number>();
function paneZIndex(name?:string){return name?PANE_Z_INDEX.get(name)??0:0}

export const L={
 divIcon:(options:DivIcon)=>options,
 svg:(_options?:unknown)=>({})
};

export function MapContainer({center,zoom=7,minZoom,maxZoom,className,scrollWheelZoom=false,children}:{center:LatLon;zoom?:number;minZoom?:number;maxZoom?:number;className?:string;scrollWheelZoom?:boolean;preferCanvas?:boolean;fadeAnimation?:boolean;zoomAnimation?:boolean;markerZoomAnimation?:boolean;children?:ReactNode}){return <MidMapLibre center={center} zoom={zoom} minZoom={minZoom} maxZoom={maxZoom} className={className} scrollZoom={scrollWheelZoom}>{children}</MidMapLibre>}

export function TileLayer({url,opacity=1,attribution,maxZoom=22,maxNativeZoom,zIndex=0,eventHandlers}:{url:string;opacity?:number;attribution?:string;maxZoom?:number;maxNativeZoom?:number;zIndex?:number;keepBuffer?:number;updateWhenIdle?:boolean;updateWhenZooming?:boolean;eventHandlers?:{tileerror?:()=>void;load?:()=>void}}){const id=useCompatId('raster');return <RasterTileLayer id={id} url={url} opacity={opacity} maxZoom={maxNativeZoom??maxZoom} attribution={attribution} zIndex={zIndex} onReady={eventHandlers?.load} onError={eventHandlers?.tileerror}/>}

export function WMSTileLayer({url,opacity=1,attribution,params,zIndex=0,eventHandlers}:{url:string;opacity?:number;attribution?:string;params:Record<string,string|number|boolean|undefined>;zIndex?:number;keepBuffer?:number;updateWhenIdle?:boolean;updateWhenZooming?:boolean;eventHandlers?:{tileerror?:()=>void;load?:()=>void}}){const id=useCompatId('wms');return <WmsTileLayer id={id} baseUrl={url} params={params} opacity={opacity} attribution={attribution} zIndex={zIndex} onReady={eventHandlers?.load} onError={eventHandlers?.tileerror}/>}

export function Pane({name,style,children}:{name?:string;style?:Record<string,unknown>;children?:ReactNode}){if(name){const value=Number(style?.zIndex);PANE_Z_INDEX.set(name,Number.isFinite(value)?value:0)}return <>{children}</>}
export function Popup({children}:{children?:ReactNode}){return <>{children}</>}
export function Tooltip({children}:{children?:ReactNode;permanent?:boolean;direction?:string;opacity?:number;className?:string}){return <>{children}</>}

function ShapeLayer({kind,positions,pathOptions={},children}:{kind:'line'|'fill';positions:any;pathOptions?:PathOptions;children?:ReactNode}){const id=useCompatId(`shape-${kind}`),info=childInfo(children),coordinates=toLineCoords(positions),geometry=kind==='line'?{type:Array.isArray(coordinates?.[0]?.[0])?'MultiLineString':'LineString',coordinates}:{type:'Polygon',coordinates:Array.isArray(coordinates?.[0]?.[0]?.[0])?coordinates:[coordinates]};const data=useMemo(()=>({type:'FeatureCollection',features:[{type:'Feature',properties:{popup:info.popup?staticHtml(info.popup):''},geometry}]}),[JSON.stringify(geometry),info.popup]);const layers:MidGeoLayer[]=kind==='line'?[{id:'line',type:'line',paint:{'line-color':pathOptions.color??'#3684b8','line-width':pathOptions.weight??2,'line-opacity':pathOptions.opacity??1,...(dashArray(pathOptions.dashArray)?{'line-dasharray':dashArray(pathOptions.dashArray)}:{})},layout:{'line-cap':pathOptions.lineCap??'round','line-join':pathOptions.lineJoin??'round'}}]:[{id:'fill',type:'fill',paint:{'fill-color':pathOptions.fillColor??pathOptions.color??'#3684b8','fill-opacity':pathOptions.fillOpacity??.18,'fill-outline-color':pathOptions.color??'#3684b8'}},{id:'outline',type:'line',paint:{'line-color':pathOptions.color??'#3684b8','line-width':pathOptions.weight??2,'line-opacity':pathOptions.opacity??1,...(dashArray(pathOptions.dashArray)?{'line-dasharray':dashArray(pathOptions.dashArray)}:{})}}];return <GeoJsonLayers id={id} data={data} layers={layers} zIndex={paneZIndex(pathOptions.pane)}/>}
export function Polyline({positions,pathOptions,pane,children}:{positions:any;pathOptions?:PathOptions;renderer?:unknown;interactive?:boolean;pane?:string;children?:ReactNode}){return <ShapeLayer kind="line" positions={positions} pathOptions={{...pathOptions,pane:pathOptions?.pane??pane}}>{children}</ShapeLayer>}
export function Polygon({positions,pathOptions,pane,children}:{positions:any;pathOptions?:PathOptions;interactive?:boolean;pane?:string;children?:ReactNode}){return <ShapeLayer kind="fill" positions={positions} pathOptions={{...pathOptions,pane:pathOptions?.pane??pane}}>{children}</ShapeLayer>}

function ClickableCircle({center,radius,pathOptions={},children}:{center:LatLon;radius:number;pathOptions?:PathOptions;children?:ReactNode}){const map=useMidMap(),id=useCompatId('circle'),sourceId=`${safeId(id)}-source`,layerId=`${safeId(id)}-layer`,info=childInfo(children);useEffect(()=>{if(!map)return;const data={type:'FeatureCollection',features:[{type:'Feature',properties:{},geometry:{type:'Point',coordinates:lonLat(center)}}]} as any;try{map.addSource(sourceId,{type:'geojson',data});map.addLayer({id:layerId,type:'circle',source:sourceId,paint:{'circle-radius':radius,'circle-color':pathOptions.fillColor??pathOptions.color??'#3684b8','circle-opacity':pathOptions.fillOpacity??.65,'circle-stroke-color':pathOptions.color??'#3684b8','circle-stroke-width':pathOptions.weight??1.5,'circle-stroke-opacity':pathOptions.opacity??1}});registerMapLayerOrder(map,layerId,paneZIndex(pathOptions.pane))}catch{}let popup:maplibregl.Popup|null=null;const click=(event:maplibregl.MapLayerMouseEvent)=>{if(!info.popup)return;popup?.remove();popup=new maplibregl.Popup({offset:10,maxWidth:'330px'}).setLngLat(event.lngLat).setHTML(staticHtml(info.popup)).addTo(map)},enter=()=>{if(info.popup)map.getCanvas().style.cursor='pointer'},leave=()=>{map.getCanvas().style.cursor=''};if(info.popup){map.on('click',layerId,click);map.on('mouseenter',layerId,enter);map.on('mouseleave',layerId,leave)}return()=>{popup?.remove();if(info.popup){map.off('click',layerId,click);map.off('mouseenter',layerId,enter);map.off('mouseleave',layerId,leave)}unregisterMapLayerOrder(map,layerId);try{if(map.getLayer(layerId))map.removeLayer(layerId);if(map.getSource(sourceId))map.removeSource(sourceId)}catch{}}},[map,sourceId,layerId,center[0],center[1],radius,pathOptions.color,pathOptions.fillColor,pathOptions.fillOpacity,pathOptions.opacity,pathOptions.weight,pathOptions.pane,info.popup]);return info.tooltip?<HtmlMarker latitude={center[0]} longitude={center[1]} html={staticHtml(info.tooltip.children)} className={`mid-map-tooltip ${info.tooltip.className??''}`} anchor="center"/>:null}
export function CircleMarker({center,radius=5,pathOptions,pane,children}:{center:LatLon;radius?:number;pathOptions?:PathOptions;interactive?:boolean;renderer?:unknown;pane?:string;children?:ReactNode}){return <ClickableCircle center={center} radius={radius} pathOptions={{...pathOptions,pane:pathOptions?.pane??pane}}>{children}</ClickableCircle>}
export function Circle({center,radius,pathOptions,pane,children}:{center:LatLon;radius:number;pathOptions?:PathOptions;interactive?:boolean;pane?:string;children?:ReactNode}){return <Polygon positions={circlePolygon(center,radius)} pathOptions={{...pathOptions,pane:pathOptions?.pane??pane}}>{children}</Polygon>}

export function Marker({position,icon,children,eventHandlers,zIndexOffset=0,pane}:{position:LatLon;icon?:DivIcon;children?:ReactNode;eventHandlers?:{click?:()=>void};zIndexOffset?:number;interactive?:boolean;pane?:string}){const info=childInfo(children),size=icon?.iconSize??[24,24],anchor=icon?.iconAnchor??[size[0]/2,size[1]/2],offset:[number,number]=[size[0]/2-anchor[0],size[1]/2-anchor[1]];return <HtmlMarker latitude={position[0]} longitude={position[1]} html={icon?.html??'<span class="mid-default-marker"></span>'} className={icon?.className??'mid-map-marker'} anchor="center" offset={offset} popupHtml={info.popup?staticHtml(info.popup):undefined} onClick={eventHandlers?.click} zIndex={paneZIndex(pane)+zIndexOffset}/>}

type CompatBounds={contains:(point:LatLon)=>boolean;pad:(fraction:number)=>CompatBounds};
type CompatMap={setView:(center:LatLon,zoom?:number,options?:{animate?:boolean})=>void;flyTo:(center:LatLon,zoom?:number,options?:{duration?:number;animate?:boolean})=>void;getZoom:()=>number;getSize:()=>{x:number;y:number};latLngToContainerPoint:(point:LatLon)=>{x:number;y:number};getBounds:()=>CompatBounds;getCenter:()=>{lat:number;lng:number};dragging:{enable:()=>void;disable:()=>void};touchZoom:{enable:()=>void;disable:()=>void};doubleClickZoom:{enable:()=>void;disable:()=>void};boxZoom:{enable:()=>void;disable:()=>void};keyboard:{enable:()=>void;disable:()=>void}};
function boundsAdapter(map:MidMap,west:number,south:number,east:number,north:number):CompatBounds{return{contains:([lat,lon])=>lon>=west&&lon<=east&&lat>=south&&lat<=north,pad:(fraction:number)=>{const dx=(east-west)*fraction,dy=(north-south)*fraction;return boundsAdapter(map,west-dx,south-dy,east+dx,north+dy)}}}
function mapAdapter(map:MidMap):CompatMap{return{setView:(center,zoom,options)=>{const payload={center:lonLat(center),...(zoom!==undefined?{zoom}:{})};options?.animate?map.easeTo({...payload,duration:450}):map.jumpTo(payload)},flyTo:(center,zoom,options)=>map.flyTo({center:lonLat(center),...(zoom!==undefined?{zoom}:{}),duration:(options?.duration??.65)*1000,essential:true}),getZoom:()=>map.getZoom(),getSize:()=>{const el=map.getContainer();return{x:el.clientWidth,y:el.clientHeight}},latLngToContainerPoint:point=>map.project(lonLat(point)),getBounds:()=>{const b=map.getBounds();return boundsAdapter(map,b.getWest(),b.getSouth(),b.getEast(),b.getNorth())},getCenter:()=>{const c=map.getCenter();return{lat:c.lat,lng:c.lng}},dragging:{enable:()=>map.dragPan.enable(),disable:()=>map.dragPan.disable()},touchZoom:{enable:()=>{map.touchZoomRotate.enable();map.touchZoomRotate.disableRotation()},disable:()=>map.touchZoomRotate.disable()},doubleClickZoom:{enable:()=>map.doubleClickZoom.enable(),disable:()=>map.doubleClickZoom.disable()},boxZoom:{enable:()=>map.boxZoom.enable(),disable:()=>map.boxZoom.disable()},keyboard:{enable:()=>map.keyboard.enable(),disable:()=>map.keyboard.disable()}}}
export function useMap(){const map=useMidMap();return useMemo(()=>map?mapAdapter(map):null as unknown as CompatMap,[map]) as CompatMap}
export function useMapEvents(events:Record<string,(event?:unknown)=>void>){const map=useMidMap();useEffect(()=>{if(!map)return;const entries=Object.entries(events);for(const [name,handler] of entries)map.on(name as any,handler as any);return()=>{for(const [name,handler] of entries)map.off(name as any,handler as any)}},[map,...Object.values(events)]);return map?mapAdapter(map):null as unknown as CompatMap}

export default L;
