export type MapReferenceSettings={countries:boolean;regions:boolean;cities:boolean;water:boolean;roads:boolean};
export const MAP_REFERENCE_KEY='mid:map-reference:v1';
export const DEFAULT_MAP_REFERENCE:MapReferenceSettings={countries:true,regions:true,cities:true,water:false,roads:false};
export function readMapReferenceSettings(){try{const d=JSON.parse(localStorage.getItem(MAP_REFERENCE_KEY)||'{}');return Object.fromEntries(Object.entries(DEFAULT_MAP_REFERENCE).map(([key,value])=>[key,typeof d[key]==='boolean'?d[key]:value])) as MapReferenceSettings}catch{return {...DEFAULT_MAP_REFERENCE}}}
export function compositeReferenceLayers(opacity:number,settings:MapReferenceSettings=DEFAULT_MAP_REFERENCE){const boundaryColor=typeof document!=='undefined'&&(document.documentElement.dataset.theme==='dark'||document.documentElement.classList.contains('dark'))?'#c6dfed':'#405e73';const alpha=Math.max(0,Math.min(1,opacity)),nonMaritime=['any',['!',['has','maritime']],['==',['get','maritime'],0],['==',['get','maritime'],'0'],['==',['get','maritime'],false],['==',['get','maritime'],'false']],adminLevel=(level:number)=>['any',['==',['get','admin_level'],level],['==',['get','admin_level'],String(level)]];return[
 {id:'coastlines',type:'line' as const,sourceLayer:'water',filter:['==',['get','class'],'ocean'],paint:{'line-color':boundaryColor,'line-width':['interpolate',['linear'],['zoom'],3,1.25,7,1.8,11,2.2],'line-opacity':alpha}},
 {id:'country-boundaries',type:'line' as const,sourceLayer:'boundary',filter:['all',adminLevel(2),nonMaritime],paint:{'line-color':boundaryColor,'line-width':['interpolate',['linear'],['zoom'],3,1.25,7,1.8,11,2.2],'line-opacity':alpha}},
 {id:'regional-boundaries',type:'line' as const,sourceLayer:'boundary',minzoom:5,filter:['all',adminLevel(4),nonMaritime],paint:{'line-color':'#8798a3','line-width':['interpolate',['linear'],['zoom'],5,.6,10,1.4],'line-opacity':.72*alpha,'line-dasharray':[2,2]}},
 {id:'places',type:'symbol' as const,sourceLayer:'place',minzoom:3,filter:['match',['get','class'],['city','town'],true,false],layout:{'text-field':['coalesce',['get','name:de'],['get','name']],'text-font':['Noto Sans Regular'],'text-size':['interpolate',['linear'],['zoom'],3,10,7,12,11,14],'text-max-width':9,'text-allow-overlap':false,'text-optional':true},paint:{'text-color':'#f7fbfd','text-halo-color':'rgba(18,31,39,.92)','text-halo-width':1.5,'text-halo-blur':.35,'text-opacity':.95*alpha}},
 {id:'waterways',type:'line' as const,sourceLayer:'waterway',minzoom:5,paint:{'line-color':'#639bb6','line-width':['interpolate',['linear'],['zoom'],5,.5,12,1.7],'line-opacity':alpha}},
 {id:'roads',type:'line' as const,sourceLayer:'transportation',minzoom:6,filter:['match',['get','class'],['motorway','trunk','primary','secondary'],true,false],paint:{'line-color':'#94a0a6','line-width':['interpolate',['linear'],['zoom'],6,.5,12,1.3],'line-opacity':.65*alpha}}
].filter(layer=>settings[({ coastlines:'countries','country-boundaries':'countries','regional-boundaries':'regions',places:'cities',waterways:'water',roads:'roads'} as const)[layer.id as 'coastlines'|'country-boundaries'|'regional-boundaries'|'places'|'waterways'|'roads']]) as any}
