import {decodeNativeMapGzip} from './nativeMapCompression';
import {mercatorY} from './precipitationTotals';
export type SynopticFrame={hour:number;resolutionKm?:number;time:string;file:string;sha256:string;bytes:number;decodedBytes:number;encoding:'gzip-json';cloudWeather?:boolean};
export type SynopticModel={label:string;run:string;resolutionKm:number;license:string;frames:SynopticFrame[]};
type Contours={type:'FeatureCollection';features:{type:'Feature';properties:{level:number;label:string};geometry:{type:'LineString';coordinates:number[][]}}[]};
export type SynopticField={schema:string;model:string;run:string;time:string;resolutionKm:number;unit:string;scale:number;lats:number[];lons:number[];thetae:(number|null)[];height:Contours;pressure:Contours;humidity:Contours;thetaContours?:Contours;wind:number[][];cloudWeather?:{cloudUnit:'%';weatherUnit:'WMO 4677';cloudScale:number;cloud:(number|null)[];weather:(number|null)[]}};
export type SynopticIndex={schema:string;models:Record<string,SynopticModel>};
const HOURS=[0,3,6,9,12,15,18,21,24,30,36,42,48,60,72,180,...Array.from({length:13},(_,i)=>96+i*24)],CORE_HOURS=[0,3,6,9,12,18,24,36,48],MODELS=['icon-d2','icon-eu','icon','gfs','ifs'],MAX_HORIZON:Record<string,number>={'icon-d2':48,'icon-eu':120,icon:180,gfs:384,ifs:360};
const sha=async(bytes:ArrayBuffer)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');
export async function loadSynopticIndex(signal:AbortSignal){
 const r=await fetch(`/ruc/latest.json?mid_synoptic=${Date.now()}`,{signal,cache:'no-store'});if(!r.ok)throw Error('Synoptik-Katalog nicht verfügbar.');const meta=await r.json(),key=meta.synopticFields?.key,match=typeof key==='string'?key.match(/^runs\/[a-zA-Z0-9_-]+__synoptic_([a-f0-9]{16})\/synoptic-fields\/index.json$/):null;if(!match)throw Error('Synoptik-Datenkatalog noch nicht veröffentlicht. Bitte erneut laden.');
 const response=await fetch(`/ruc/${key}`,{signal});if(!response.ok)throw Error('Synoptik-Index nicht erreichbar.');const bytes=await response.arrayBuffer();if((await sha(bytes)).slice(0,16)!==match[1])throw Error('Synoptik-Index-Prüfsumme ungültig.');const index=JSON.parse(new TextDecoder().decode(bytes)) as SynopticIndex;
 if(index.schema!=='mid.synoptic.fields.v1'||!index.models||Object.keys(index.models).length>5)throw Error('Synoptik-Schema ungültig.');
 for(const [id,m] of Object.entries(index.models)){const stamp=Date.parse(m.run);if(!MODELS.includes(id)||!Number.isFinite(stamp)||stamp>Date.now()+3600000||Date.now()-stamp>24*3600000||typeof m.label!=='string'||!Number.isFinite(m.resolutionKm)||m.resolutionKm<1||m.resolutionKm>100||!Array.isArray(m.frames)||m.frames.length<9||m.frames.length>30||!CORE_HOURS.every(h=>m.frames.some(f=>f.hour===h))||new Set(m.frames.map(f=>f.hour)).size!==m.frames.length||m.frames.some(f=>!HOURS.includes(f.hour)||(f.resolutionKm!==undefined&&(!Number.isFinite(f.resolutionKm)||f.resolutionKm<1||f.resolutionKm>100))||f.hour>(id==='icon'&&[6,18].includes(new Date(stamp).getUTCHours())?120:MAX_HORIZON[id])||Date.parse(f.time)!==stamp+f.hour*3600000||f.file!==`${id}-${String(f.hour).padStart(3,'0')}.bin`||f.encoding!=='gzip-json'||!Number.isInteger(f.bytes)||f.bytes<1||f.bytes>12000000||!Number.isInteger(f.decodedBytes)||f.decodedBytes<1||f.decodedBytes>12000000||!/^[a-f0-9]{64}$/.test(f.sha256)))throw Error('Modelllauf oder vollständige Termine ungültig.')}
 return {index,base:`/ruc/${key.slice(0,-10)}`};
}
export function validateSynopticField(d:SynopticField,id:string,model:SynopticModel,ref:SynopticFrame){
 const axis=(a:number[])=>Array.isArray(a)&&a.length>=10&&a.length<2500&&a.every((v,i)=>Number.isFinite(v)&&(!i||v>a[i-1]&&Math.abs(v-a[i-1]-(a[1]-a[0]))<1e-5));
 if(d?.schema!=='mid.synoptic.field.v1'||d.model!==id||d.run!==model.run||d.time!==ref.time||d.resolutionKm!==(ref.resolutionKm??model.resolutionKm)||d.unit!=='°C'||d.scale!==.1||!axis(d.lats)||!axis(d.lons)||d.lats[0]<29.5||d.lats.at(-1)!>70.5||d.lons[0]<-23.5||d.lons.at(-1)!>62.5||!Array.isArray(d.thetae)||d.thetae.length!==d.lats.length*d.lons.length||d.thetae.filter(v=>v!==null).length<d.thetae.length*.4||d.thetae.some(v=>v!==null&&(!Number.isInteger(v)||v<-1000||v>1800)))throw Error('Synoptik-Raster oder Einheit ungültig.');
 const point=(p:number[])=>Array.isArray(p)&&p.length===2&&p.every(Number.isFinite)&&p[0]>=d.lons[0]-1e-4&&p[0]<=d.lons.at(-1)!+1e-4&&p[1]>=d.lats[0]-1e-4&&p[1]<=d.lats.at(-1)!+1e-4;
 for(const [key,low,high] of [['height',350,650],['pressure',850,1100],['humidity',0,150],...(d.thetaContours?[['thetaContours',-100,180] as const]:[])] as const){const fc=d[key];if(fc?.type!=='FeatureCollection'||!Array.isArray(fc.features)||fc.features.length>10000||fc.features.some(f=>f.type!=='Feature'||f.geometry?.type!=='LineString'||!Array.isArray(f.geometry.coordinates)||f.geometry.coordinates.length<3||!f.geometry.coordinates.every(point)||!Number.isFinite(f.properties?.level)||f.properties.level<low||f.properties.level>high||f.properties.label!==String(f.properties.level)))throw Error('Synoptik-Konturen ungültig.')}
 if(!Array.isArray(d.wind)||d.wind.length>10000||d.wind.some(w=>w.length!==4||!point(w.slice(0,2))||!w.slice(2).every(v=>Number.isFinite(v)&&Math.abs(v)<=200)))throw Error('Strömungsvektoren ungültig.');
 if(ref.cloudWeather===true&&!d.cloudWeather)throw Error('Wolken-/Wetterfeld fehlt.');
 if(d.cloudWeather){const c=d.cloudWeather,n=d.lats.length*d.lons.length;if(c.cloudUnit!=='%'||c.weatherUnit!=='WMO 4677'||c.cloudScale!==.1||!Array.isArray(c.cloud)||!Array.isArray(c.weather)||c.cloud.length!==n||c.weather.length!==n||c.cloud.some(v=>v!==null&&(!Number.isInteger(v)||v<0||v>1000))||c.weather.some(v=>v!==null&&(!Number.isInteger(v)||v<0||v>99)))throw Error('Wolken-/Wetterraster oder Einheit ungültig.');}
 return d;
}
export async function loadSynopticField(base:string,id:string,model:SynopticModel,ref:SynopticFrame,signal:AbortSignal){const r=await fetch(base+ref.file,{signal});if(!r.ok)throw Error('Synoptik-Feld nicht erreichbar.');const bytes=await r.arrayBuffer();if(bytes.byteLength!==ref.bytes||await sha(bytes)!==ref.sha256)throw Error('Synoptik-Feld-Prüfsumme ungültig.');return validateSynopticField(JSON.parse(await decodeNativeMapGzip(bytes,ref.decodedBytes)),id,model,ref)}
export function synopticAt(d:SynopticField,lat:number,lon:number){if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat<d.lats[0]||lat>d.lats.at(-1)!||lon<d.lons[0]||lon>d.lons.at(-1)!)return null;const y=(lat-d.lats[0])/(d.lats[1]-d.lats[0]),x=(lon-d.lons[0])/(d.lons[1]-d.lons[0]),row=Math.min(d.lats.length-2,Math.floor(y)),col=Math.min(d.lons.length-2,Math.floor(x)),dy=y-row,dx=x-col,v=[d.thetae[row*d.lons.length+col],d.thetae[row*d.lons.length+col+1],d.thetae[(row+1)*d.lons.length+col],d.thetae[(row+1)*d.lons.length+col+1]];if(v.some(a=>a===null))return null;return ((v[0]!*(1-dx)+v[1]!*dx)*(1-dy)+(v[2]!*(1-dx)+v[3]!*dx)*dy)*d.scale}
export const THETAE_COLORS:[number,string][]=[[-18,'#580966'],[-6,'#ba15e5'],[6,'#245cea'],[18,'#19d68b'],[30,'#b5eb77'],[36,'#f5f075'],[42,'#ffe027'],[48,'#ffb42e'],[54,'#f58a28'],[60,'#e65c2d'],[66,'#c62a42'],[72,'#a72070'],[78,'#c220a4'],[90,'#742461']];
function interpolatedColor(value:number){const found=THETAE_COLORS.findIndex(c=>c[0]>=value),i=found<0?THETAE_COLORS.length-1:found,a=THETAE_COLORS[Math.max(0,i-1)],b=THETAE_COLORS[i]??THETAE_COLORS.at(-1)!,t=Math.min(1,Math.max(0,(value-a[0])/Math.max(1,b[0]-a[0])));return [1,3,5].map(k=>Math.round(parseInt(a[1].slice(k,k+2),16)*(1-t)+parseInt(b[1].slice(k,k+2),16)*t))}
const THETAE_RGB=Array.from({length:19},(_,i)=>interpolatedColor(-18+i*6));
export function synopticColor(value:number){return THETAE_RGB[Math.max(0,Math.min(18,Math.floor((value+18)/6)))]}
export function synopticRaster(d:SynopticField){const canvas=document.createElement('canvas');canvas.width=Math.max(800,Math.min(1600,d.lons.length));canvas.height=Math.max(600,Math.min(1600,d.lats.length));const c=canvas.getContext('2d');if(!c)throw Error('Rasterdarstellung nicht verfügbar.');const image=c.createImageData(canvas.width,canvas.height),north=mercatorY(d.lats.at(-1)!),south=mercatorY(d.lats[0]);for(let y=0;y<canvas.height;y++){const lat=(2*Math.atan(Math.exp(north-(y+.5)/canvas.height*(north-south)))-Math.PI/2)*180/Math.PI;for(let x=0;x<canvas.width;x++){const lon=d.lons[0]+(x+.5)/canvas.width*(d.lons.at(-1)!-d.lons[0]),value=synopticAt(d,lat,lon);if(value===null)continue;const p=(y*canvas.width+x)*4;const rgb=synopticColor(value);image.data[p]=rgb[0];image.data[p+1]=rgb[1];image.data[p+2]=rgb[2];image.data[p+3]=235}}c.putImageData(image,0,0);return canvas.toDataURL('image/png')}

export const JET_WIND_THRESHOLD_KT=60;
export function jetWindStyle(u:number,v:number){const speed=Math.hypot(u,v),knots=speed*1.9438444924406;if(!Number.isFinite(knots)||knots<JET_WIND_THRESHOLD_KT)return null;return {speed,knots,length:Math.min(38,12+(knots-60)*.22),width:Math.min(3.2,1.1+(knots-60)/65)}}
export const THETAE_BANDS:[number,string][]=Array.from({length:19},(_,i)=>{const value=-18+i*6;return [value,'#'+synopticColor(value).map(v=>v.toString(16).padStart(2,'0')).join('')]});
