import {decodeNativeMapGzip} from './nativeMapCompression';
import {mercatorY,totalsColor} from './precipitationTotals';
import {createMapColorScale,roundMapScale,mapColorAt,type MapColorMode,type MapColorScale} from './modelMapColorScale';
import {modelMapDisplayFactor} from './modelMapUnits';
import type {WindUnit} from './weather';
import {ecmwfTemperatureColor} from './temperatureTone';
export type NativeFieldKind='temperature'|'pressure'|'wind'|'gust'|'cloud'|'thetae'|'sigwx'|'precipitation';
export type NativeField={schema:'mid.icon-d2.field.v1';run:string;time:string;kind:NativeFieldKind;unit:string;scale:number;lats:number[];lons:number[];values:number[];isobars:{level:number;paths:number[][][]}[]};
export type NativeFrameRef={hour:number;time:string;file:string;sha256:string;bytes:number;intervalHours:number;encoding?:'gzip-json';decodedBytes?:number};
export type NativeIndex={schema:string;run:string;products:Partial<Record<NativeFieldKind,{unit:string;frames:NativeFrameRef[]}>>};
export const NATIVE_LEGENDS:Record<NativeFieldKind,[number,string][]>={
 temperature:[-30,-20,-10,0,5,10,15,20,25,30,35,40].map(value=>[value,ecmwfTemperatureColor(value)]),
 pressure:[[960,'#644f91'],[980,'#5389bf'],[1000,'#72bec3'],[1010,'#a8d39a'],[1020,'#e9d776'],[1030,'#eab05e'],[1040,'#bf6155']],
 wind:[[0,'#b8d9ea'],[10,'#70c4d0'],[20,'#55be9f'],[30,'#a2d160'],[40,'#f1d15b'],[60,'#ed894c'],[80,'#d3475a'],[100,'#854b93']],
 gust:[[0,'#b8d9ea'],[20,'#70c4d0'],[40,'#55be9f'],[60,'#e7cf65'],[80,'#ed894c'],[100,'#d3475a'],[120,'#854b93']],
 cloud:[[0,'#b3ddf0'],[20,'#a2bbcc'],[40,'#8d9eaf'],[60,'#77899b'],[80,'#5f7088'],[100,'#485a70']],
 thetae:[[270,'#645195'],[285,'#508ac6'],[300,'#5cc4cd'],[315,'#86d59b'],[330,'#e7dc6a'],[345,'#efa050'],[360,'#d45062']],
 sigwx:[[0,'#9bb6cc'],[40,'#b6c7d7'],[50,'#57b7d2'],[60,'#229fd0'],[70,'#a7baf4'],[80,'#41c285'],[90,'#e68641']],
 precipitation:[[.1,'#b9ddfc'],[1,'#83bef5'],[3,'#429be9'],[5,'#197ecc'],[10,'#145a91'],[15,'#099d45'],[20,'#19c32c'],[30,'#b4ee13'],[40,'#ffed18'],[50,'#ffbd48'],[70,'#fb5140'],[100,'#b9183c']]
};
export function nativeColor(kind:NativeFieldKind,value:number){if(kind==='precipitation')return totalsColor(value);let color=NATIVE_LEGENDS[kind][0][1];for(const [threshold,next] of NATIVE_LEGENDS[kind]){if(value<threshold)break;color=next}return color}
export function nativeMapScale(data:NativeField,mode:MapColorMode,unit:WindUnit='kmh'){
 const values={*[Symbol.iterator](){for(const value of data.values)yield value*data.scale}};
 return roundMapScale(createMapColorScale(NATIVE_LEGENDS[data.kind],values,mode,{categorical:data.kind==='sigwx',transparentBelow:data.kind==='precipitation'?.1:undefined,nonnegative:['wind','gust','cloud','precipitation'].includes(data.kind),minimumSpan:data.kind==='precipitation'?.1:1}),modelMapDisplayFactor(data.kind,unit),data.kind==='precipitation'?.1:1);
}
export function nativeAt(data:NativeField,lat:number,lon:number){if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat<data.lats[0]||lat>data.lats.at(-1)!||lon<data.lons[0]||lon>data.lons.at(-1)!)return null;const row=Math.round((lat-data.lats[0])/(data.lats[1]-data.lats[0])),col=Math.round((lon-data.lons[0])/(data.lons[1]-data.lons[0]));return data.values[row*data.lons.length+col]*data.scale}
export function validateNativeField(raw:unknown,index:NativeIndex,ref:NativeFrameRef,kind:NativeFieldKind):NativeField{
 const d=raw as NativeField,axis=(a:number[])=>Array.isArray(a)&&a.length>1&&a.length<2000&&a.every((v,i)=>Number.isFinite(v)&&(!i||v>a[i-1])&&(!i||Math.abs(v-a[i-1]-(a[1]-a[0]))<1e-5));
 const units:Record<NativeFieldKind,string>={temperature:'°C',pressure:'hPa',wind:'km/h',gust:'km/h',cloud:'%',thetae:'K',sigwx:'WMO',precipitation:'mm/1 h'};
 if(d?.unit!==units[kind])throw new Error('Modelleinheit passt nicht zum verifizierten Parametervertrag.');
 if(d?.schema!=='mid.icon-d2.field.v1'||d.run!==index.run||d.time!==ref.time||d.kind!==kind||d.unit!==index.products[kind]?.unit||d.scale!==.1||!axis(d.lats)||!axis(d.lons)||d.lats[0]>47.03||d.lats.at(-1)!<55.17||d.lons[0]>5.53||d.lons.at(-1)!<15.57||!Array.isArray(d.values)||d.values.length!==d.lats.length*d.lons.length||!d.values.every(v=>Number.isInteger(v)&&Math.abs(v)<100000))throw new Error('Modellraster, Parameter oder Gültigkeitszeit ungültig.');
 if(!Array.isArray(d.isobars)||d.isobars.length>100||d.isobars.some(c=>!Number.isFinite(c.level)||!Array.isArray(c.paths)||c.paths.some(p=>!Array.isArray(p)||p.length!==2||p.some(a=>a.length!==2||!a.every(Number.isFinite)||a[0]<47||a[0]>55.2||a[1]<5.5||a[1]>15.6))))throw new Error('Ungültige Druckkonturen.');
 const bounds:Record<NativeFieldKind,[number,number]>={temperature:[-100,70],pressure:[800,1100],wind:[0,600],gust:[0,600],cloud:[0,100.1],thetae:[150,500],sigwx:[0,99],precipitation:[0,6500]},[low,high]=bounds[kind];if(d.values.some(v=>v*d.scale<low||v*d.scale>high||(kind==='sigwx'&&v%10!==0)))throw new Error('Modellwerte außerhalb des Parametervertrags.');
 return d;
}
export async function loadNativeIndex(signal:AbortSignal){const r=await fetch(`/ruc/latest.json?mid_fields=${Date.now()}`,{signal,cache:'no-store'});if(!r.ok)throw new Error('Modellkarten nicht verfügbar.');const meta=await r.json(),key=meta.modelFields?.key;if(typeof key!=='string'||!/^runs\/[a-zA-Z0-9_-]+\/model-fields\/index\.json$/.test(key))throw new Error('Direkte DWD-Modellraster werden vorbereitet.');const response=await fetch(`/ruc/${key}`,{signal});if(!response.ok)throw new Error('Kartenindex nicht verfügbar.');const index=await response.json() as NativeIndex,stamp=Date.parse(index.run);if(index.schema!=='mid.icon-d2.fields.v1'||!Number.isFinite(stamp)||Date.now()-stamp>24*3600000||stamp>Date.now()+3600000)throw new Error('Kein aktueller Modelllauf verfügbar.');for(const [kind,product] of Object.entries(index.products||{})){if(!(kind in NATIVE_LEGENDS)||!product?.frames.length||product.frames.length>48||new Set(product.frames.map(f=>f.hour)).size!==product.frames.length||product.frames.some(f=>![1,3,6,12,24,48].includes(f.hour)||Date.parse(f.time)!==stamp+f.hour*3600000||f.file!==`${kind}-${String(f.hour).padStart(3,'0')}.${f.encoding==='gzip-json'?'bin':'json'}`||(f.encoding!==undefined&&f.encoding!=='gzip-json')||(f.encoding==='gzip-json'&&(!Number.isInteger(f.decodedBytes)||f.decodedBytes!<1||f.decodedBytes!>12000000))||!/^[a-f0-9]{64}$/.test(f.sha256)||!Number.isInteger(f.bytes)||f.bytes<1||f.bytes>12000000||!Number.isFinite(f.intervalHours)||f.intervalHours<0||f.intervalHours>f.hour))throw new Error('Kartenindex ungültig.')}return{index,base:`/ruc/${key.slice(0,-10)}`}}
export async function loadNativeField(index:NativeIndex,base:string,ref:NativeFrameRef,kind:NativeFieldKind,signal:AbortSignal){const response=await fetch(base+ref.file,{signal});if(!response.ok)throw new Error('Modellfeld nicht verfügbar.');const bytes=await response.arrayBuffer();if(bytes.byteLength!==ref.bytes)throw new Error('Unvollständiges Modellfeld.');const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');if(digest!==ref.sha256)throw new Error('Prüfsumme des Modellfeldes stimmt nicht.');return validateNativeField(JSON.parse(ref.encoding==='gzip-json'?await decodeNativeMapGzip(bytes,ref.decodedBytes!):new TextDecoder().decode(bytes)),index,ref,kind)}
export function nativeRaster(data:NativeField,scale:MapColorScale=nativeMapScale(data,'absolute')){const canvas=document.createElement('canvas');canvas.width=data.lons.length;canvas.height=data.lats.length;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Kartendarstellung nicht verfügbar.');const image=ctx.createImageData(canvas.width,canvas.height),north=mercatorY(data.lats.at(-1)!),south=mercatorY(data.lats[0]);for(let y=0;y<canvas.height;y++){const lat=(2*Math.atan(Math.exp(north-(y+.5)/canvas.height*(north-south)))-Math.PI/2)*180/Math.PI,row=Math.min(canvas.height-1,Math.max(0,Math.round((lat-data.lats[0])/(data.lats[1]-data.lats[0]))));for(let x=0;x<canvas.width;x++){const color=mapColorAt(scale,data.values[row*canvas.width+x]*data.scale);if(color==='transparent')continue;const i=(y*canvas.width+x)*4;image.data[i]=parseInt(color.slice(1,3),16);image.data[i+1]=parseInt(color.slice(3,5),16);image.data[i+2]=parseInt(color.slice(5,7),16);image.data[i+3]=215}}ctx.putImageData(image,0,0);return canvas.toDataURL('image/png')}
