import {useEffect,useMemo,useState} from 'react';
import {GeoJsonLayers,HtmlMarker,ImageQuadLayer,MapCenter,MapFitBounds,MidMapLibre,RasterTileLayer} from './MapLibreCore';
import ModelMapContextOverlay from './ModelMapContextOverlay';
import {WEATHER_MAP_BASEMAPS,type WeatherMapBasemapId} from './weatherMapBasemaps';
import {loadNativeField,loadNativeIndex,nativeAt,nativeRaster,NATIVE_LEGENDS,type NativeField,type NativeFieldKind,type NativeIndex} from './nativeModelFields';
import ModelMapColorLegend from './ModelMapColorLegend';
import {TOTALS_COLORS} from './precipitationTotals';
import {compactPrecipitationAmount} from './forecastAmountFormat';
import {formatDecimal} from './format';
import {exportNativeField} from './nativeModelMapExport';
import type {WeatherMapFavoriteLocation} from './PrecipitationTotalsMap';
import './weatherMapsTotals.css';
const stamp=(value:string)=>new Intl.DateTimeFormat('de-DE',{timeZone:'UTC',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value))+' UTC';
const escaped=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export default function NativeModelMap({kind,label,favorites,basemap}:{kind:NativeFieldKind;label:string;favorites:WeatherMapFavoriteLocation[];basemap:WeatherMapBasemapId}){
 const [catalog,setCatalog]=useState<{index:NativeIndex;base:string}|null>(null),[field,setField]=useState<NativeField|null>(null),[hour,setHour]=useState(6),[error,setError]=useState(''),[revision,setRevision]=useState(0),[playing,setPlaying]=useState(false),[exporting,setExporting]=useState(false),[selected,setSelected]=useState('');
 const places=useMemo(()=>favorites.filter(p=>p.name&&Number.isFinite(p.latitude)&&Number.isFinite(p.longitude)).sort((a,b)=>a.name.localeCompare(b.name,'de-DE')),[favorites]),place=places.find(p=>p.id===selected),frames=catalog?.index.products[kind]?.frames??[],ref=frames.find(f=>f.hour===hour),activeBasemap=WEATHER_MAP_BASEMAPS[basemap];
 useEffect(()=>{const c=new AbortController();setCatalog(null);setField(null);setError('');setPlaying(false);void loadNativeIndex(c.signal).then(setCatalog).catch(e=>{if(!c.signal.aborted)setError(String(e.message||e))});return()=>c.abort()},[revision]);
 useEffect(()=>{setPlaying(false);if(frames.length&&!frames.some(f=>f.hour===hour))setHour(frames[0].hour);else if(catalog&&!frames.length)setError('Dieser Parameter ist im geprüften Modelllauf nicht verfügbar.')},[kind,catalog]);
 useEffect(()=>{const c=new AbortController();setField(null);setError('');if(catalog&&ref)void loadNativeField(catalog.index,catalog.base,ref,kind,c.signal).then(setField).catch(e=>{if(!c.signal.aborted){setPlaying(false);setError(String(e.message||e))}});return()=>c.abort()},[catalog,kind,ref]);
 useEffect(()=>{if(!playing||!field||frames.length<2)return;const timer=window.setTimeout(()=>setHour(frames[(frames.findIndex(f=>f.hour===hour)+1)%frames.length].hour),2400);return()=>window.clearTimeout(timer)},[playing,field,frames,hour]);
 const raster=useMemo(()=>field?nativeRaster(field):'',[field]),format=(v:number|null)=>v===null?'–':kind==='precipitation'?compactPrecipitationAmount(v):kind==='sigwx'?String(Math.round(v)):formatDecimal(v,1),legendStops=useMemo(()=>kind==='sigwx'?null:(kind==='precipitation'?TOTALS_COLORS:NATIVE_LEGENDS[kind]).map(([value,color])=>({label:String(value),color})),[kind]);
 const isobars=useMemo(()=>({type:'FeatureCollection',features:field?.isobars.flatMap(c=>c.paths.map(path=>({type:'Feature',properties:{level:c.level},geometry:{type:'LineString',coordinates:path.map(([lat,lon])=>[lon,lat])}})))??[]}),[field]);
 const download=async(format:'png'|'svg')=>{if(!field||!raster)return;setExporting(true);try{await exportNativeField(field,label,raster,places,format,ref?.intervalHours??0)}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setError(String(e))}finally{setExporting(false)}};
 return <section className="weather-precipitation-totals" aria-label={label}><div className="weather-precipitation-layout">
  <section className="weather-precipitation-map-column"><div className="weather-precipitation-map-shell"><MidMapLibre center={[51.05,10.45]} zoom={5.25} minZoom={4} maxZoom={9} className="weather-precipitation-map" scrollZoom={false}>
   {place?<MapCenter latitude={place.latitude} longitude={place.longitude} zoom={6.8}/>:<MapFitBounds south={47} west={5.5} north={55.2} east={15.6} padding={20} maxZoom={6}/>}
   <RasterTileLayer id={`native-basemap-${basemap}`} url={activeBasemap.url} tone={activeBasemap.tone} attribution={activeBasemap.attribution}/>
   {field&&raster?<ImageQuadLayer id={`native-${kind}-${field.time}`} url={raster} bounds={[[field.lats[0],field.lons[0]],[field.lats.at(-1)!,field.lons.at(-1)!]]} opacity={.85}/>:null}
   {field?.isobars.length?<GeoJsonLayers id={`native-isobars-${kind}`} data={isobars} layers={[{id:'lines',type:'line',paint:{'line-color':'#192c3f','line-width':1.1,'line-opacity':.8}}]}/>:null}
   <ModelMapContextOverlay/>
   {places.filter(p=>p.latitude>=47&&p.latitude<=55.2&&p.longitude>=5.5&&p.longitude<=15.6).map(p=><HtmlMarker key={p.id} latitude={p.latitude} longitude={p.longitude} anchor="center" zIndex={2} className="precipitation-favorite-marker" html="<span></span>" popupHtml={`<strong>${escaped(p.name)}</strong><br/>${field?escaped(format(nativeAt(field,p.latitude,p.longitude)))+' '+escaped(field.unit):'Daten werden geladen'}`} onClick={()=>setSelected(p.id)}/>)}
  </MidMapLibre>{!field?<div className="weather-precipitation-data-state" role="status"><span><strong>{error?'Kein verifiziertes Modellfeld verfügbar':'Modellfeld wird geladen …'}</strong><small>{error}</small></span></div>:null}
  {kind==='sigwx'?<div className="weather-precipitation-legend-placeholder" aria-label={`${label} Kategorienlegende`}>{NATIVE_LEGENDS.sigwx.map(([value,color])=><span key={value}><i style={{background:color}}/>{value}</span>)}<span>{field?.unit||catalog?.index.products[kind]?.unit}</span></div>:legendStops?<ModelMapColorLegend label={label} unit={field?.unit||catalog?.index.products[kind]?.unit||'–'} mode="fixed" scales={{range:{stops:legendStops},fixed:{stops:legendStops}}} onModeChange={()=>{}} disabled={playing} disabledModes={['range']}/>:null}</div>
  <p className="weather-precipitation-attribution">DWD ICON-D2 · direkte GRIB2-Raster · DWD-Lat/Lon-Aufbereitung 0,02° · CC BY 4.0. Kartenbasis: © OpenStreetMap-Mitwirkende, ODbL. Grenzen und Ortsnamen: Natural Earth (Public Domain), über dem Wetterfeld.</p></section>
  <aside className="weather-precipitation-summary"><section className="weather-precipitation-period"><small>BESTÄTIGTE MODELLTERMINE</small><h4>{label}</h4><div className="weather-precipitation-window-options">{frames.map(f=><button key={f.hour} type="button" aria-pressed={hour===f.hour} onClick={()=>{setPlaying(false);setHour(f.hour)}}>+{f.hour} h</button>)}</div><p>Keine zeitliche Interpolation. {kind==='precipitation'?'Niederschlag in der letzten Stunde vor dem gewählten Termin.':kind==='gust'?`Maximale Böe im bestätigten ${ref?.intervalHours??'–'}-h-Modellintervall.`:kind==='sigwx'?'WMO-Wettercode aus dem Modell; keine amtliche Warnung.':'Momentanwert zum gewählten Modelltermin.'}</p><button type="button" disabled={frames.length<2||!field} aria-pressed={playing} onClick={()=>setPlaying(v=>!v)}>{playing?'Animation pausieren':'Animation starten'}</button></section>
  <dl className="weather-precipitation-meta"><div><dt>Modelllauf</dt><dd>{catalog?stamp(catalog.index.run):'–'}</dd></div><div><dt>Gültig</dt><dd>{field?stamp(field.time):'–'}</dd></div><div><dt>Ortswerte</dt><dd>Nächster dargestellter DWD-Rasterpunkt</dd></div></dl><div className="weather-precipitation-exports"><button type="button" disabled={!field||exporting} onClick={()=>void download('png')}>PNG herunterladen</button><button type="button" disabled={!field||exporting} onClick={()=>void download('svg')}>SVG herunterladen</button></div></aside>
  <section className="weather-precipitation-favorites"><header><h4>Favoriten</h4><span>{field?.unit||'Wert'} · gleicher Rasterpunkt wie Karte</span></header><div className="weather-precipitation-table-wrap"><table><thead><tr><th>Ort</th><th>Wert</th><th>Datenstatus</th></tr></thead><tbody>{places.map(p=>{const v=field?nativeAt(field,p.latitude,p.longitude):null;return <tr key={p.id}><th><button type="button" disabled={v===null} onClick={()=>setSelected(current=>current===p.id?'':p.id)}>{p.name}</button></th><td>{format(v)} {v!==null?field?.unit:''}</td><td>{v===null?'nicht abgedeckt / nicht verfügbar':'DWD-Rasterpunkt'}</td></tr>})}{!places.length?<tr><td colSpan={3}>Noch keine Favoriten gespeichert.</td></tr>:null}</tbody></table></div></section>
 </div>{error&&field?<p role="alert">{error}</p>:null}<button type="button" className="weather-maps-reload" onClick={()=>setRevision(v=>v+1)}>Daten aktualisieren</button><p className="weather-precipitation-disclaimer">Modellprognose · keine Messwerte · keine amtliche Warnung.</p></section>
}
