import germany from './precipitationGermany.json';
import {loadModelMapGeography,type ModelMapGeography} from './modelMapGeography';
import {mercatorY,totalsStartAt,totalsMapScale,totalsAt,type TotalsData,type TotalsFrame} from './precipitationTotals';
import {compactPrecipitationAmount} from './forecastAmountFormat';
import {mapScaleSvg,type MapColorScale} from './modelMapColorScale';
type Place={name:string;latitude:number;longitude:number};
function xml(value:string){return value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!))}
export function totalsSvg(data:TotalsData,frame:TotalsFrame,raster:string,places:Place[],states:ModelMapGeography['states']=[],scale:MapColorScale=totalsMapScale(data,frame,'absolute')){
 const rows=places.map(place=>({...place,value:totalsAt(data,frame,place.latitude,place.longitude)})),legendY=Math.max(960,250+rows.length*30),height=legendY+180,west=data.lons[0],east=data.lons.at(-1)!,south=mercatorY(data.lats[0]),north=mercatorY(data.lats.at(-1)!),x=(lon:number)=>50+(lon-west)/(east-west)*630,y=(lat:number)=>170+(north-mercatorY(lat))/(north-south)*760;
 const polygons=germany.geometry.type==='MultiPolygon'?germany.geometry.coordinates:[germany.geometry.coordinates];
 const paths=(polygons as unknown as number[][][][]).flatMap(poly=>poly.map(ring=>`<path d="${ring.map(([lon,lat],i)=>`${i?'L':'M'}${x(lon).toFixed(1)},${y(lat).toFixed(1)}`).join(' ')}Z"/>`)).join('');
 const statePaths=states.flatMap(state=>state.rings.map(ring=>`<path d="${ring.map(([lon,lat],i)=>`${i?'L':'M'}${x(lon).toFixed(1)},${y(lat).toFixed(1)}`).join(' ')}Z"/>`)).join('');
 const dates=(value:string)=>new Date(value).toISOString().replace('T',' ').slice(0,16)+' UTC';
 return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="${height}" viewBox="0 0 1200 ${height}"><rect width="1200" height="${height}" fill="#08131f"/><g font-family="Arial,sans-serif" fill="#e5eff8"><text x="50" y="57" font-size="30" font-weight="bold">MID · NIEDERSCHLAGSSUMME · ${frame.hours} H</text><text x="50" y="89" font-size="18">${data.kind==='observed'?'RADOLAN · Messstand':'ICON-D2 · Lauf'} ${dates(data.run)}</text><text x="50" y="118" font-size="17">${dates(totalsStartAt(data,frame))} – ${dates(frame.validTo)} · Maximum im Kartenausschnitt ${xml(compactPrecipitationAmount(frame.maximum))} mm</text><rect x="50" y="170" width="630" height="760" fill="#112434"/><image href="${raster}" x="50" y="170" width="630" height="760" preserveAspectRatio="none"/><g fill="none" stroke="#edf5fa" stroke-width="1.4">${paths}</g><g fill="none" stroke="#edf5fa" stroke-width=".75">${statePaths}</g><text x="720" y="190" font-size="22" font-weight="bold">FAVORITEN · ${rows.length} ORTE</text>${rows.map((p,i)=>`<rect x="710" y="${211+i*30}" width="445" height="28" fill="${i%2?'#102332':'#142c3d'}"/><text x="725" y="${231+i*30}" font-size="15">${xml(p.name.slice(0,34))}</text><text x="1140" y="${231+i*30}" font-size="15" text-anchor="end">${p.value===null?'–':xml(compactPrecipitationAmount(p.value))+' mm'}</text>${p.value===null?'':`<circle cx="${x(p.longitude)}" cy="${y(p.latitude)}" r="4" fill="#fff"/>`}`).join('')}<text x="50" y="${legendY}" font-size="15">Summe in mm · Wasseräquivalent · trocken &lt;0,1 mm</text>${mapScaleSvg(scale,v=>compactPrecipitationAmount(v),'mm',50,legendY+17)}<text x="50" y="${height-65}" font-size="13">${data.kind==='observed'?'Radargestützte Messanalyse · grau = fehlende Messdaten':'Modellprognose · keine Messwerte'} · keine amtliche Warnung · Ortswerte: nächster dargestellter Rasterpunkt</text><text x="50" y="${height-45}" font-size="12">Daten: Deutscher Wetterdienst, CC BY 4.0 · bearbeitet durch MID · Grenzen: Natural Earth (Public Domain) · opendata.dwd.de</text><a href="https://creativecommons.org/licenses/by/4.0/"><text x="50" y="${height-25}" font-size="12">creativecommons.org/licenses/by/4.0/</text></a></g></svg>`;
}
export async function exportTotals(data:TotalsData,frame:TotalsFrame,raster:string,places:Place[],kind:'png'|'svg',scale:MapColorScale=totalsMapScale(data,frame,'absolute')){
 const geography=await loadModelMapGeography();const svg=totalsSvg(data,frame,raster,places,geography.states,scale);let blob=new Blob([svg],{type:'image/svg+xml'});
 if(kind==='png'){const url=URL.createObjectURL(blob);try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const context=canvas.getContext('2d');if(!context)throw new Error('Bildexport nicht verfügbar.');context.drawImage(image,0,0);blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(result=>result?resolve(result):reject(new Error('PNG konnte nicht erstellt werden.')),'image/png'))}finally{URL.revokeObjectURL(url)}}
 const filename=`MID-${data.kind==='observed'?'RADOLAN':'ICON-D2'}-${data.run.slice(0,13).replace(/[^0-9]/g,'')}-${frame.hours}h.${kind}`,file=new File([blob],filename,{type:blob.type}),shareData={title:'MID · Niederschlagssummen',files:[file]};
 if(typeof navigator.share==='function'&&navigator.canShare?.(shareData)){await navigator.share(shareData);return}const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;link.rel='noopener';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);
}
