import {useEffect,useMemo,useState} from 'react';
import {Bell,Clock3,CloudLightning,CloudRain,Info,LocateFixed,RefreshCw,Send,ShieldCheck,ShieldX,AlertTriangle} from 'lucide-react';
import {disablePushNotifications,enablePushNotifications,getPushStatus,sendPushTestNotification,type PushNotificationInterval,type PushRuleFavorite,type PushStatus} from './pushNotifications';
import type {Location} from './weather';

type PushRules={precipitationStart:boolean;thunderstormApproach:boolean};
type FavoriteForPush={id:string;location:Location;alias:string;rules:{precipitationStart?:boolean;thunderstormApproach?:boolean}};
type PushRuleKey=keyof PushRules;

type PushSettingsProps={
 favorites:FavoriteForPush[];
 onRuleChange:(id:string,key:PushRuleKey,value:boolean)=>void;
 locationTracking:boolean;
 trackedLocation:Location|null;
 trackedRules:PushRules;
 onTrackedRuleChange:(key:PushRuleKey,value:boolean)=>void;
 modelChangeLocation:Location|null;
 modelChangeAvailable:boolean;
 modelChangeNotificationEnabled:boolean;
 onModelChangeNotificationChange:(value:boolean)=>void;
 notificationIntervalMinutes:PushNotificationInterval;
 onNotificationIntervalChange:(value:PushNotificationInterval)=>void;
 advancedMode:boolean;
};

function payload(favorites:FavoriteForPush[],locationTracking:boolean,trackedLocation:Location|null,trackedRules:PushRules,modelChangeLocation:Location|null,modelChangeNotificationEnabled:boolean):PushRuleFavorite[]{
 const rows:PushRuleFavorite[]=favorites.map(item=>({id:item.id,name:item.alias||item.location.name,latitude:item.location.latitude,longitude:item.location.longitude,country:item.location.country_code||item.location.country,rules:{precipitationStart:Boolean(item.rules.precipitationStart),thunderstormApproach:Boolean(item.rules.thunderstormApproach),forecastMaterialChange:false}}));
 if(locationTracking&&trackedLocation)rows.unshift({id:'tracked-location',name:`Aktueller Standort · ${trackedLocation.name}`,latitude:trackedLocation.latitude,longitude:trackedLocation.longitude,country:trackedLocation.country_code||trackedLocation.country,rules:{...trackedRules,forecastMaterialChange:false}});
 if(modelChangeNotificationEnabled&&modelChangeLocation)rows.unshift({id:'model-change-location',name:`Vorhersageänderung · ${modelChangeLocation.name}`,latitude:modelChangeLocation.latitude,longitude:modelChangeLocation.longitude,country:modelChangeLocation.country_code||modelChangeLocation.country,rules:{precipitationStart:false,thunderstormApproach:false,forecastMaterialChange:true}});
 return rows;
}

function RuleRows({rules,onChange,advancedMode}:{rules:PushRules;onChange:(key:PushRuleKey,value:boolean)=>void;advancedMode:boolean}){
 return <div className="push-rule-grid"><label className={rules.precipitationStart?'active':''}><input type="checkbox" checked={rules.precipitationStart} onChange={event=>onChange('precipitationStart',event.target.checked)}/><CloudRain size={18}/><span><b>Niederschlagsbeginn</b><small>{advancedMode?'Meldung kurz vor beziehungsweise beim Beginn von Regen, Schauern oder Schnee.':'Regen oder Schnee beginnt.'}</small></span></label><label className={rules.thunderstormApproach?'active':''}><input type="checkbox" checked={rules.thunderstormApproach} onChange={event=>onChange('thunderstormApproach',event.target.checked)}/><CloudLightning size={18}/><span><b>Gewitterzelle nähert sich</b><small>{advancedMode?'Radarbasierter Hinweis auf eine relevante sich nähernde Zelle; keine amtliche Warnung.':'Hinweis auf ein heranziehendes Gewitter.'}</small></span></label></div>;
}

export function PushSettingsPanel({favorites,onRuleChange,locationTracking,trackedLocation,trackedRules,onTrackedRuleChange,modelChangeLocation,modelChangeAvailable,modelChangeNotificationEnabled,onModelChangeNotificationChange,notificationIntervalMinutes,onNotificationIntervalChange,advancedMode}:PushSettingsProps){
 const[status,setStatus]=useState<PushStatus|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const activeRules=useMemo(()=>favorites.reduce((sum,item)=>sum+Number(Boolean(item.rules.precipitationStart))+Number(Boolean(item.rules.thunderstormApproach)),(locationTracking?Number(trackedRules.precipitationStart)+Number(trackedRules.thunderstormApproach):0)+Number(modelChangeNotificationEnabled&&Boolean(modelChangeLocation))),[favorites,locationTracking,trackedRules.precipitationStart,trackedRules.thunderstormApproach,modelChangeNotificationEnabled,modelChangeLocation]);
 const pushPayload=()=>payload(favorites,locationTracking,trackedLocation,trackedRules,modelChangeLocation,modelChangeNotificationEnabled);
 const refresh=async()=>{try{setStatus(await getPushStatus())}catch(error){setMessage(error instanceof Error?error.message:String(error))}};
 useEffect(()=>{void refresh()},[]);
 const activate=async()=>{setBusy(true);setMessage('');try{await enablePushNotifications(pushPayload(),notificationIntervalMinutes);setMessage('Benachrichtigungen wurden auf diesem Gerät aktiviert.');await refresh()}catch(error){setMessage(error instanceof Error?error.message:'Benachrichtigungen konnten nicht aktiviert werden.')}finally{setBusy(false)}};
 const deactivate=async()=>{setBusy(true);setMessage('');try{await disablePushNotifications();setMessage('Benachrichtigungen wurden auf diesem Gerät deaktiviert.');await refresh()}catch(error){setMessage(error instanceof Error?error.message:'Benachrichtigungen konnten nicht deaktiviert werden.')}finally{setBusy(false)}};
 const sendTest=async()=>{setBusy(true);setMessage('');try{await sendPushTestNotification();setMessage('Testmitteilung wurde an dieses Gerät gesendet.');await refresh()}catch(error){setMessage(error instanceof Error?error.message:'Testmitteilung konnte nicht gesendet werden.')}finally{setBusy(false)}};
 const permission=status?.permission,technicalNote='Die Push-Abonnementadresse und die aktivierten Koordinaten werden im privaten Cloudflare-KV-Speicher des MID-Workers hinterlegt. Bei Standortverfolgung verwendet der Worker die zuletzt erfolgreich ermittelte Position; eine dauerhafte Hintergrund-Ortung findet nicht statt.';
 return <section className={`settings-section push-settings-panel${advancedMode?' advanced':''}`}><header><span>Hinweise</span><h3>Benachrichtigungen</h3><p>{advancedMode?'Push-Verbindung, Mindestabstand und ortsbezogene Regeln werden hier zentral verwaltet.':'Wähle hier Gerät, Häufigkeit und Orte für Wetterhinweise.'}</p></header>
  <section className="push-settings-group push-device-group"><header><span>Gerät</span><strong>Benachrichtigungen auf diesem Gerät</strong>{advancedMode&&<small>Aktivierung und technischer Status gelten nur für dieses Gerät.</small>}</header><div className={`push-status-card settings-option-card ${status?.operational?'active':permission==='denied'?'blocked':status?.subscribed?'warning':''}`}><div>{status?.operational?<ShieldCheck size={24}/>:permission==='denied'?<ShieldX size={24}/>:status?.subscribed?<AlertTriangle size={24}/>:<Bell size={24}/>}<span><strong>{status?.operational?'Aktiv':permission==='denied'?'Vom System blockiert':status?.subscribed?'Prüfung erforderlich':'Nicht aktiviert'}</strong><small>{status?.message||'Status wird geprüft …'}</small></span></div><button type="button" onClick={()=>void refresh()} disabled={busy} aria-label="Status aktualisieren"><RefreshCw size={16} className={busy?'spin':''}/></button></div>{advancedMode&&status?.workerUrl&&<small className="push-worker-url">Worker: {status.workerUrl}{status.schedulerLastRunAt?` · letzter Prüfzyklus ${new Date(status.schedulerLastRunAt).toLocaleString('de-DE')}`:''}</small>}<div className="push-actions">{status?.subscribed?<><button type="button" className="danger" onClick={()=>void deactivate()} disabled={busy}>{busy?<RefreshCw className="spin" size={17}/>:<ShieldX size={17}/>}Deaktivieren</button>{!status.serverRegistered&&status.configured&&<button type="button" className="primary" onClick={()=>void activate()} disabled={busy||permission==='denied'}>{busy?<RefreshCw className="spin" size={17}/>:<RefreshCw size={17}/>}Registrierung reparieren</button>}{status.serverRegistered&&<button type="button" onClick={()=>void sendTest()} disabled={busy}>{busy?<RefreshCw className="spin" size={17}/>:<Send size={17}/>}Test senden</button>}</>:<button type="button" className="primary" onClick={()=>void activate()} disabled={busy||status?.supported===false||status?.configured===false||permission==='denied'}>{busy?<RefreshCw className="spin" size={17}/>:<Bell size={17}/>}Benachrichtigungen aktivieren</button>}<small>{activeRules} aktive Regel{activeRules===1?'':'n'}{advancedMode&&status?.serverRegistered?` · ${status.activeFavorites} Ort${status.activeFavorites===1?'':'e'} im Worker registriert`:advancedMode?' · Freigabe gilt nur für dieses Gerät.':''}</small></div></section>
  <section className="push-settings-group push-frequency-group"><header><span>Häufigkeit</span><strong>Mindestabstand zwischen Mitteilungen</strong>{advancedMode&&<small>Der Dienst prüft regelmäßig, sendet innerhalb des gewählten Zeitraums aber höchstens eine Mitteilung.</small>}</header><label className="push-interval-setting settings-option-card active"><Clock3 size={22}/><span><strong>Benachrichtigungsintervall</strong><small>{advancedMode?'Gilt geräteweit für Niederschlag, Gewitter und Vorhersageänderungen.':'Legt fest, wie häufig Hinweise erscheinen dürfen.'}</small></span><select value={notificationIntervalMinutes} onChange={event=>onNotificationIntervalChange(Number(event.target.value) as PushNotificationInterval)} aria-label="Mindestabstand zwischen Benachrichtigungen"><option value={15}>15 Minuten · häufig</option><option value={30}>30 Minuten · ausgewogen</option><option value={60}>60 Minuten · ruhig</option><option value={120}>2 Stunden</option><option value={180}>3 Stunden</option></select></label></section>
  <section className="push-settings-group push-places-group"><header><span>Regeln</span><strong>Orte und Ereignisse</strong>{advancedMode&&<small>Alle Benachrichtigungsoptionen sind ausschließlich in diesem Bereich gebündelt.</small>}</header><label className={`settings-toggle-card push-model-change-setting${!modelChangeAvailable||!modelChangeLocation?' disabled':''}`}><input type="checkbox" disabled={!modelChangeAvailable||!modelChangeLocation} checked={modelChangeNotificationEnabled} onChange={event=>onModelChangeNotificationChange(event.target.checked)}/><RefreshCw size={21}/><span><strong>Bei materieller Änderung benachrichtigen</strong><small>{modelChangeAvailable&&modelChangeLocation?`${modelChangeLocation.name} · deutliche Änderung der nächsten drei Tage`:'Im Erweiterten Modus zunächst das Änderungsradar aktivieren.'}</small></span></label><div className="push-favorite-list">{locationTracking&&<article className="tracked-push-location settings-option-card"><header><strong><LocateFixed size={16}/> Aktueller Standort</strong><small>{trackedLocation?`${trackedLocation.name} · zuletzt bestimmt`:'Wird bei der nächsten Standortbestimmung hinterlegt.'}</small></header><RuleRows rules={trackedRules} onChange={onTrackedRuleChange} advancedMode={advancedMode}/></article>}{favorites.map(item=><article key={item.id} className="settings-option-card"><header><strong>{item.alias||item.location.name}</strong><small>{[item.location.admin1,item.location.country].filter(Boolean).join(' · ')}</small></header><RuleRows rules={{precipitationStart:Boolean(item.rules.precipitationStart),thunderstormApproach:Boolean(item.rules.thunderstormApproach)}} onChange={(key,value)=>onRuleChange(item.id,key,value)} advancedMode={advancedMode}/></article>)}{!locationTracking&&!favorites.length&&<div className="favorite-empty"><Bell size={24}/><strong>Noch keine Orte</strong><span>Aktiviere den Standort oder speichere einen Favoriten.</span></div>}</div></section>
  {message&&<p className="push-message">{message}</p>}{advancedMode?<small className="push-privacy-note">{technicalNote}</small>:<details className="settings-info-disclosure"><summary><Info size={16}/><span>Datenschutz und Technik</span></summary><p>{technicalNote}</p></details>}
 </section>;
}
