import {useEffect,useMemo,useState} from 'react';
import {GeoJsonLayers} from './MapLibreCore';
import type {OperaRasterFrame} from './CompositeData';
import {loadOperaRasterData,operaRasterPoint,type OperaRaster} from './OperaRasterSource';
import {loadWeatherPhaseGrid,type WeatherPhaseGridData,type WeatherPhaseGridFrame} from './WeatherMapsData';

export type RadarModelPhaseStatus='idle'|'loading'|'ready'|'error';
type Phase='rain'|'mixed'|'snow'|'freezing'|'uncertain';
type PhaseResult={phase:Phase;label:string;color:string;confidence:'hoch'|'mittel'|'eingeschränkt';modelEvidence:boolean};
function finite(value:unknown){const number=Number(value);return Number.isFinite(number)?number:NaN}
function wetBulbStull(t:number,rh:number){if(!Number.isFinite(t)||!Number.isFinite(rh))return NaN;const humidity=Math.max(1,Math.min(100,rh));return t*Math.atan(.151977*Math.sqrt(humidity+8.313659))+Math.atan(t+humidity)-Math.atan(humidity-1.676331)+.00391838*Math.pow(humidity,1.5)*Math.atan(.023101*humidity)-4.686035}
function phaseFor(frame:WeatherPhaseGridFrame,index:number):PhaseResult{
 const code=Math.round(finite(frame.weatherCode[index])||0),temperature=finite(frame.temperature2m[index]),humidity=finite(frame.relativeHumidity2m[index]),directWetBulb=finite(frame.wetBulbTemperature2m[index]),wetBulb=Number.isFinite(directWetBulb)?directWetBulb:wetBulbStull(temperature,humidity),precipitation=Math.max(0,finite(frame.precipitation[index])||0),rain=Math.max(0,finite(frame.rain[index])||0),showers=Math.max(0,finite(frame.showers[index])||0),snowfall=Math.max(0,finite(frame.snowfall[index])||0),snowfallHeight=finite(frame.snowfallHeight[index]),freezingLevel=finite(frame.freezingLevelHeight[index]),elevation=finite(frame.elevation[index]),explicitFreezing=[56,57,66,67].includes(code),explicitSnow=[71,73,75,77,85,86].includes(code),explicitMixed=[68,69].includes(code),explicitThunder=[95,96,99].includes(code),explicitRain=[51,53,55,61,63,65,80,81,82].includes(code),liquid=rain+showers,modelEvidence=precipitation>=.005||liquid>=.005||snowfall>=.005||explicitFreezing||explicitSnow||explicitMixed||explicitThunder||explicitRain;
 if(explicitFreezing)return{phase:'freezing',label:'gefrierender Niederschlag · ICON-D2',color:'#f02d44',confidence:Number.isFinite(wetBulb)&&wetBulb<=.8?'hoch':'mittel',modelEvidence};
 if(explicitMixed||(snowfall>=.005&&liquid>=.005))return{phase:'mixed',label:'Schneeregen / Mischphase',color:'#a66be8',confidence:'hoch',modelEvidence};
 const snowLevelSupports=Number.isFinite(snowfallHeight)&&Number.isFinite(elevation)&&snowfallHeight<=elevation+180,liquidLevelSupports=Number.isFinite(snowfallHeight)&&Number.isFinite(elevation)&&snowfallHeight>=elevation+350,freezeSupports=Number.isFinite(freezingLevel)&&Number.isFinite(elevation)&&freezingLevel<=elevation+250;
 if(explicitSnow||snowfall>=.005){if((Number.isFinite(wetBulb)&&wetBulb<=.8)||snowLevelSupports)return{phase:'snow',label:'Schnee',color:'#e96adf',confidence:explicitSnow?'hoch':'mittel',modelEvidence};if(Number.isFinite(wetBulb)&&wetBulb<=1.6)return{phase:'mixed',label:'Mischphase möglich',color:'#a66be8',confidence:'mittel',modelEvidence}}
 if(explicitRain||explicitThunder||liquid>=.005){if((Number.isFinite(wetBulb)&&wetBulb>=1.4)||liquidLevelSupports)return{phase:'rain',label:explicitThunder?'konvektiver Niederschlag · flüssige Phase':'Regen',color:'#18c287',confidence:explicitRain?'hoch':'mittel',modelEvidence};if(Number.isFinite(wetBulb)&&wetBulb>=.3&&wetBulb<1.4)return{phase:'mixed',label:'Mischphase möglich',color:'#a66be8',confidence:'eingeschränkt',modelEvidence}}
 if(modelEvidence&&Number.isFinite(wetBulb)){if(wetBulb<=.25&&snowLevelSupports)return{phase:'snow',label:'Schneephase wahrscheinlich',color:'#e96adf',confidence:'mittel',modelEvidence};if(wetBulb>=1.8&&!freezeSupports)return{phase:'rain',label:'flüssige Phase wahrscheinlich',color:'#18c287',confidence:'mittel',modelEvidence}}
 return{phase:'uncertain',label:'Phase nicht belastbar bestimmbar',color:'#7f7f7f',confidence:'eingeschränkt',modelEvidence};
}
function buildPhaseGeoJson(data:WeatherPhaseGridData,raster:OperaRaster){
 const frame=data.frame,features:any[]=[],latStep=data.lats.length>1?Math.abs(data.lats[1]-data.lats[0]):.05,lonStep=data.lons.length>1?Math.abs(data.lons[1]-data.lons[0]):.05,subdivisions=1;
 for(let row=0;row<data.lats.length;row++)for(let col=0;col<data.lons.length;col++){const index=row*data.lons.length+col,phase=phaseFor(frame,index);if(phase.phase==='uncertain'||phase.confidence==='eingeschränkt')continue;const centerLat=data.lats[row],centerLon=data.lons[col];for(let sy=0;sy<subdivisions;sy++)for(let sx=0;sx<subdivisions;sx++){const south=centerLat-latStep/2+sy*latStep/subdivisions,north=south+latStep/subdivisions,west=centerLon-lonStep/2+sx*lonStep/subdivisions,east=west+lonStep/subdivisions,lat=(south+north)/2,lon=(west+east)/2,echo=operaRasterPoint(raster,lat,lon);if(!echo.covered||!Number.isFinite(echo.dbz))continue;const dbz=Number(echo.dbz),minimumDbz=phase.phase==='snow'||phase.phase==='freezing'?5:7;if(dbz<minimumDbz)continue;const confidenceFactor=phase.confidence==='hoch'?1:phase.confidence==='mittel'?0.82:0.62,echoFactor=dbz>=45?1:dbz>=30?0.9:dbz>=15?0.78:0.64,alpha=.16+.22*confidenceFactor*echoFactor,label=`Radar + ICON-D2 · ${phase.label} · ${Math.round(dbz)} dBZ · Modellkonsistenz ${phase.confidence}`;features.push({type:'Feature',properties:{phase:phase.phase,color:phase.color,alpha,label,dbz},geometry:{type:'Polygon',coordinates:[[[west,south],[east,south],[east,north],[west,north],[west,south]]]}})}}
 return{type:'FeatureCollection',features};
}
export default function RadarModelPrecipTypeOverlay({latitude,longitude,targetTime,operaFrame,opacity=.9,onStatus}:{latitude:number;longitude:number;targetTime?:string;operaFrame?:OperaRasterFrame|null;opacity?:number;onStatus?:(status:RadarModelPhaseStatus,message?:string)=>void}){
 const[data,setData]=useState<WeatherPhaseGridData|null>(null),[raster,setRaster]=useState<OperaRaster|null>(null);
 useEffect(()=>{const controller=new AbortController();setData(null);setRaster(null);if(!operaFrame?.fileUrl){onStatus?.('error','OPERA-CIRRUS-Echomaske fehlt; die Niederschlagsart bleibt aus.');return()=>controller.abort()}const targetIso=targetTime||operaFrame.time,targetMs=Date.parse(targetIso),operaMs=Date.parse(operaFrame.time);if(!Number.isFinite(targetMs)||!Number.isFinite(operaMs)||Math.abs(targetMs-operaMs)>12*60000){onStatus?.('error','OPERA-CIRRUS liegt zeitlich zu weit vom gewählten Radarstand entfernt.');return()=>controller.abort()}onStatus?.('loading','Beobachtete OPERA-CIRRUS-Echofläche und zeitnahes ICON-D2-Phasenraster werden geprüft.');Promise.all([loadWeatherPhaseGrid(latitude,longitude,targetIso,controller.signal),loadOperaRasterData(operaFrame.fileUrl,controller.signal)]).then(([grid,nextRaster])=>{if(controller.signal.aborted)return;if(grid.error)throw new Error(grid.error);const modelMs=Date.parse(grid.frame?.time||''),referenceMs=Date.parse(grid.referenceTime||'');if(!Number.isFinite(modelMs)||Math.abs(modelMs-targetMs)>20*60000)throw new Error('Kein ausreichend zeitnahes ICON-D2-Phasenfeld.');if(Number.isFinite(referenceMs)&&modelMs-referenceMs>5*60*60000)throw new Error('Der ICON-D2-Modelllauf ist für eine belastbare Radarphase zu alt.');setData(grid);setRaster(nextRaster);onStatus?.('ready',`OPERA ${operaFrame.time.slice(11,16)} UTC + ICON-D2 ${grid.frame.time.slice(11,16)} UTC · ${grid.coverage||`ca. ${grid.gridSpacingKm??'?'} km Phasenraster`} · unsichere Grenzfälle transparent`) }).catch(error=>{if(!controller.signal.aborted)onStatus?.('error',error instanceof Error?error.message:String(error))});return()=>controller.abort()},[latitude,longitude,targetTime,operaFrame?.fileUrl,operaFrame?.time,onStatus]);
 const geojson=useMemo(()=>data&&raster?buildPhaseGeoJson(data,raster):null,[data,raster]);if(!geojson||!geojson.features.length)return null;return <GeoJsonLayers id="radar-model-precip-type" data={geojson} layers={[{id:'phase',type:'fill',paint:{'fill-color':['get','color'],'fill-opacity':['*',['get','alpha'],Math.max(.2,Math.min(1,opacity))],'fill-outline-color':['get','color']}}]} hoverProperty="label" zIndex={450}/>;
}
