import {Fragment,lazy,Suspense,useCallback,useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import {CloudSun,Droplets,Gauge,Info,Layers3,LocateFixed,Pause,Play,RadioTower,Satellite,SkipBack,SkipForward,Zap} from 'lucide-react';
import {CircleMarker,MapContainer,Polyline,Popup,TileLayer,Tooltip,WMSTileLayer,useMap,useMapEvents} from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import type {RadarNowcast} from './weather';
import {formatDecimal} from './format';
import {loadPx250Metadata,type Px250Meta} from './Px250Source';
import {
 compositeWmsProxy,
 loadCompositeTimes,
 loadLightningPoints,
 loadModelContours,
 loadOperaRaster,
 loadRainViewer,
 type CompositeProduct,
 type CompositeProductTimes,
 type CompositeSource,
 type ContourLevel,
 type LightningPoint,
 type LightningPointResponse,
 type ModelContourResponse,
 type OperaRasterFrame,
 type ProductTime,
 type RainViewerFrame,
 type WmsProvider
} from './CompositeData';
import {blendOpacity,blendTimedFrames,buildCompositeTimeline,clamp,dominantBlendFrame,uniqueTimedFrames,type BlendFrame,type TimedFrame} from './CompositeTimeline';
import {useDismissibleLayer} from './useDismissibleLayer';

const LazyPx250Overlay=lazy(()=>import('./Px250Overlay'));
const LazyOperaRasterOverlay=lazy(()=>import('./OperaRasterOverlay'));
type RadarFrame=RainViewerFrame&{future?:boolean};
type PxStatus='idle'|'loading'|'ready'|'error';
type OperaStatus='idle'|'loading'|'ready'|'error';
type BasemapId='osm'|'positron'|'dark';
type ModelLineMode='off'|'isobars'|'isoheights'|'both';
type CompositeSettings={basemap:BasemapId;showRadar:boolean;highResolution:boolean;showSatellite:boolean;showLightning:boolean;modelLines:ModelLineMode;radarOpacity:number;satelliteOpacity:number;lightningOpacity:number;modelOpacity:number};
const SETTINGS_KEY='mid:composite-settings:v2';
const LAYERS_KEY='mid:composite-layers:v1';
const BASEMAPS:Record<BasemapId,{label:string;detail:string;url:string;attribution:string}>={
 osm:{label:'OpenStreetMap',detail:'Standard',url:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',attribution:'&copy; OpenStreetMap-Mitwirkende'},
 positron:{label:'Schlicht hell',detail:'CARTO Positron',url:'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',attribution:'&copy; OpenStreetMap-Mitwirkende &copy; CARTO'},
 dark:{label:'Schlicht dunkel',detail:'CARTO Dark Matter',url:'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',attribution:'&copy; OpenStreetMap-Mitwirkende &copy; CARTO'}
};
const DWD_RATE_LEGEND=[
 {value:'0,1',color:'#d9f3ff'},{value:'0,5',color:'#72c9ff'},{value:'1',color:'#2f91e3'},{value:'2,5',color:'#43c879'},
 {value:'5',color:'#f0d447'},{value:'10',color:'#f59b3d'},{value:'20',color:'#e34b4b'},{value:'50＋',color:'#b83fc8'}
];
const RAINVIEWER_LEGEND=[{dbz:10,color:'#d2c48b'},{dbz:20,color:'#00a3e0'},{dbz:30,color:'#005588'},{dbz:40,color:'#ffaa00'},{dbz:50,color:'#c10000'},{dbz:60,color:'#ff62ff'}];
const LIGHTNING_AGES=[{label:'0–20 min',color:'#ffffff'},{label:'20–40',color:'#fff36b'},{label:'40–60',color:'#ffad16'},{label:'60–80',color:'#ef432d'},{label:'80–100',color:'#b71c1c'},{label:'100–120',color:'#650b0d'}];
const EMPTY_PRODUCT_TIMES:CompositeProductTimes={satelliteDay:[],satelliteIr:[],satellitePrecip:[],mtgLightning:[],dwdLightning:[],dwdRadar:[]};
const MODEL_LINE_MODES:ModelLineMode[]=['off','isobars','isoheights','both'];

function epochMs(value:ProductTime|undefined|null){
 if(typeof value==='number')return Number.isFinite(value)?(Math.abs(value)<1e12?value*1000:value):NaN;
 const text=String(value??'').trim();if(!text)return NaN;
 if(/^-?\d+(?:\.\d+)?$/.test(text)){const number=Number(text);return Number.isFinite(number)?(Math.abs(number)<1e12?number*1000:number):NaN}
 return Date.parse(text);
}
function normalisedIsoTimes(values:ProductTime[]|undefined,referenceMs=Date.now(),historyMinutes=190,futureMinutes=130){
 const minimum=referenceMs-historyMinutes*60000,maximum=referenceMs+futureMinutes*60000;
 return[...new Set((values??[]).map(epochMs).filter(value=>Number.isFinite(value)&&value>=minimum&&value<=maximum).map(value=>new Date(value).toISOString()))].sort((a,b)=>Date.parse(a)-Date.parse(b));
}
function toFrames(values:ProductTime[]|undefined,referenceSeconds:number){return normalisedIsoTimes(values,referenceSeconds*1000).map(value=>({time:Math.floor(Date.parse(value)/1000),path:''}))}
function storedSettings():CompositeSettings{
 const defaults:CompositeSettings={basemap:'positron',showRadar:true,highResolution:false,showSatellite:false,showLightning:false,modelLines:'off',radarOpacity:76,satelliteOpacity:58,lightningOpacity:92,modelOpacity:82};
 try{
  const raw=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}') as Partial<CompositeSettings>,layers=JSON.parse(localStorage.getItem(LAYERS_KEY)||'{}') as Partial<Pick<CompositeSettings,'showRadar'|'highResolution'|'showSatellite'|'showLightning'|'modelLines'>>,basemap=raw.basemap&&BASEMAPS[raw.basemap]?raw.basemap:defaults.basemap,showRadar=typeof layers.showRadar==='boolean'?layers.showRadar:typeof raw.showRadar==='boolean'?raw.showRadar:defaults.showRadar,highResolution=showRadar&&(typeof layers.highResolution==='boolean'?layers.highResolution:raw.highResolution===true),selectedModelLines=layers.modelLines??raw.modelLines,modelLines=MODEL_LINE_MODES.includes(selectedModelLines as ModelLineMode)?selectedModelLines as ModelLineMode:defaults.modelLines;
  return{basemap,showRadar,highResolution,showSatellite:typeof layers.showSatellite==='boolean'?layers.showSatellite:typeof raw.showSatellite==='boolean'?raw.showSatellite:defaults.showSatellite,showLightning:typeof layers.showLightning==='boolean'?layers.showLightning:typeof raw.showLightning==='boolean'?raw.showLightning:defaults.showLightning,modelLines,radarOpacity:clamp(Number(raw.radarOpacity)||defaults.radarOpacity,15,100),satelliteOpacity:clamp(Number(raw.satelliteOpacity)||defaults.satelliteOpacity,15,100),lightningOpacity:clamp(Number(raw.lightningOpacity)||defaults.lightningOpacity,20,100),modelOpacity:clamp(Number(raw.modelOpacity)||defaults.modelOpacity,20,100)};
 }catch{return defaults}
}
function formatInZone(value:number,timeZone:string|undefined,options:Intl.DateTimeFormatOptions){try{return new Intl.DateTimeFormat('de-DE',{...options,timeZone:timeZone||undefined}).format(new Date(value))}catch{return new Intl.DateTimeFormat('de-DE',options).format(new Date(value))}}
function relativeLabel(targetSeconds:number,referenceSeconds:number){const minutes=Math.round((targetSeconds-referenceSeconds)/60);if(Math.abs(minutes)<3)return'Jetzt';const sign=minutes<0?'−':'+';const absolute=Math.abs(minutes),hours=Math.floor(absolute/60),rest=absolute%60;if(hours&&rest)return`${sign}${hours} h ${rest} min`;if(hours)return`${sign}${hours} h`;return`${sign}${absolute} min`}
function sourceForLocation(analysis:RadarNowcast|null|undefined,lat:number,lon:number):CompositeSource{if(analysis?.source&&analysis.source!=='model'&&analysis.coverage!==false)return analysis.source;const expected=String(analysis?.expectedSource||'').toLowerCase();if(expected.includes('dwd')||(lat>=46.5&&lat<=56&&lon>=4.5&&lon<=16.5))return'dwd';if(expected.includes('opera')||(lat>=31.5&&lat<=72.5&&lon>=-30.5&&lon<=50.5))return'opera';return'rainviewer'}
function Title({eye,title,action}:{eye:string;title:string;action?:ReactNode}){return <header className="title"><div><span>{eye}</span><h2>{title}</h2></div>{action}</header>}
function CompositeInfo({rows,children}:{rows:{label:string;value:ReactNode}[];children:ReactNode}){
 const ref=useRef<HTMLSpanElement>(null),[open,setOpen]=useState(false);useDismissibleLayer(ref,open,()=>setOpen(false));
 return <span ref={ref} className={`mode-info composite-info${open?' open':''}`}><button type="button" onClick={()=>setOpen(value=>!value)} aria-expanded={open} aria-haspopup="dialog" aria-label="Quellen, Datenstand und Lizenz anzeigen" title="Quellen, Datenstand und Lizenz"><Info size={16}/></button>{open&&<span className="mode-info-popover composite-info-popover" role="dialog" aria-label="Informationen zum Kompositbild"><strong>Kompositbild · Dateninformation</strong><dl>{rows.map(row=><Fragment key={row.label}><dt>{row.label}</dt><dd>{row.value}</dd></Fragment>)}</dl><p>{children}</p></span>}</span>
}
function MoveMap({lat,lon,locateRequest}:{lat:number;lon:number;locateRequest:number}){const map=useMap();useEffect(()=>{map.setView([lat,lon],7,{animate:true})},[lat,lon,map]);useEffect(()=>{if(locateRequest>0)map.flyTo([lat,lon],map.getZoom(),{animate:true,duration:.65})},[locateRequest,lat,lon,map]);return null}
function RasterCacheRevision({onZoomStart,onZoomEnd}:{onZoomStart:()=>void;onZoomEnd:()=>void}){useMapEvents({zoomstart:onZoomStart,zoomend:onZoomEnd});return null}
function LayerSwitch({active,disabled=false,title,onClick,icon,label,detail}:{active:boolean;disabled?:boolean;title:string;onClick:()=>void;icon:ReactNode;label:string;detail?:string}){return <button type="button" className={`composite-switch${active?' active':''}`} disabled={disabled} aria-pressed={active} title={title} onClick={onClick}>{icon}<span><b>{label}</b>{detail&&<small>{detail}</small>}</span></button>}
function lightningStyle(point:LightningPoint,target:number,fallbackTime?:string){const stamp=Date.parse(point.observedAt||fallbackTime||''),age=Number.isFinite(stamp)?Math.max(0,(target-stamp)/60000):0,color=age<=20?'#ffffff':age<=40?'#fff36b':age<=60?'#ffad16':age<=80?'#ef432d':age<=100?'#b71c1c':'#650b0d',ageOpacity=clamp(1-age/150,.18,1),strength=clamp(Math.abs(Number(point.intensity))||Number(point.count)||1,1,80),radius=3.8+Math.log2(strength+1)*.82,weight=clamp(1.65+Math.log10(strength+1)*.5,1.7,2.8);return{age,color,opacity:ageOpacity,radius,weight,newest:age<=2}}
function formatAge(age:number){return age<1?'gerade eben':`${Math.round(age)} min alt`}
function RadarScale({source,highResolution,satelliteFallback}:{source:CompositeSource;highResolution:boolean;satelliteFallback:boolean}){if(satelliteFallback)return <div className="compact-scale rate satellite-rate"><span>Sat.-Rate</span><i>{DWD_RATE_LEGEND.map(item=><b key={item.value} style={{background:item.color}}/>)}</i><span>mm/h</span></div>;if(source==='dwd'&&!highResolution)return <div className="compact-scale rate"><span>0,1</span><i>{DWD_RATE_LEGEND.map(item=><b key={item.value} style={{background:item.color}}/>)}</i><span>50＋ mm/h</span></div>;return <div className="compact-scale dbz"><span>10</span><i>{RAINVIEWER_LEGEND.map(item=><b key={item.dbz} style={{background:item.color}}/>)}</i><span>60＋ dBZ</span></div>}
function CompositeLegend({source,showRadar,highResolution,showSatellite,satelliteName,showLightning,lightningProvider,vectorLightning,relative,pxSite,satellitePrecip,modelLines}:{source:CompositeSource;showRadar:boolean;highResolution:boolean;showSatellite:boolean;satelliteName:string;showLightning:boolean;lightningProvider:string;vectorLightning:boolean;relative:string;pxSite?:string;satellitePrecip:boolean;modelLines:ModelLineMode}){const provider=highResolution?(pxSite?.includes('HX')?'DWD HX':'DWD 250 m'):source==='dwd'?'DWD-RV':source==='opera'?'EUMETNET OPERA':source==='rainviewer'?'RainViewer':'kein Radar';return <div className="radarlegend compact"><div className="radarlegend-head"><strong>{relative}</strong><span>{showRadar?provider:'Komposit'}</span></div><div className="legend-active-chips">{showRadar&&<em>Niederschlag{pxSite?` · ${pxSite}`:''}</em>}{satellitePrecip&&<em>Satelliten-Niederschlagsrate</em>}{showSatellite&&<em>{satelliteName}</em>}{showLightning&&<em>{lightningProvider}</em>}{modelLines!=='off'&&<em>{modelLines==='isobars'?'Isobaren':modelLines==='isoheights'?'500-hPa-Isohypsen':'Isobaren + Isohypsen'}</em>}{!showRadar&&!showSatellite&&!showLightning&&modelLines==='off'&&<em>nur Kartenbasis</em>}</div>{showRadar&&<RadarScale source={source} highResolution={highResolution} satelliteFallback={satellitePrecip}/>} {showLightning&&vectorLightning&&<div className="lightning-age-legend ring-legend">{LIGHTNING_AGES.map(item=><span key={item.label}><i style={{borderColor:item.color}}/>{item.label}</span>)}</div>}</div>}
function wmsUrl(provider:WmsProvider){return compositeWmsProxy(provider)||(provider==='dwd'?'https://maps.dwd.de/geoserver/wms':'https://view.eumetsat.int/geoserver/wms')}
function rasterVersionUrl(base:string,revision:number,frame:string){const separator=base.includes('?')?'&':'?';return`${base}${separator}_mid_frame=${encodeURIComponent(frame||'latest')}&_mid_revision=${revision}`}
function blendStamp<T extends TimedFrame>(blend:BlendFrame<T>[],referenceSeconds:number,timezone?:string,fallbackTime?:number){if(!blend.length){if(Number.isFinite(fallbackTime)){const time=fallbackTime as number;return`letzter Stand ${formatInZone(time*1000,timezone,{hour:'2-digit',minute:'2-digit'})} (${relativeLabel(time,referenceSeconds)}) · ausgeblendet`}return'kein Quellenstand'}const ordered=[...blend].sort((a,b)=>a.frame.time-b.frame.time),times=ordered.map(item=>formatInZone(item.frame.time*1000,timezone,{hour:'2-digit',minute:'2-digit'})),dominant=dominantBlendFrame(blend),relative=dominant?relativeLabel(dominant.time,referenceSeconds):'';return times.length>1?`Stand ${times.join(' ↔ ')} · interpoliert`:`Stand ${times[0]}${relative&&relative!=='Jetzt'?` (${relative})`:''}`}
function contourLabel(level:number,type:'isobars'|'isoheights'){return type==='isobars'?`${Math.round(level)} hPa`:`${Math.round(level/10)} gpdm`}
function pathKm(path:[number,number][]) {let total=0;for(let index=1;index<path.length;index++){const a=path[index-1],b=path[index],rad=Math.PI/180,lat1=a[0]*rad,lat2=b[0]*rad,dLat=(b[0]-a[0])*rad,dLon=(b[1]-a[1])*rad,h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;total+=12742*Math.asin(Math.min(1,Math.sqrt(h)))}return total}
function pointAlong(path:[number,number][],fraction:number){const lengths=path.slice(1).map((point,index)=>pathKm([path[index],point])),total=lengths.reduce((sum,value)=>sum+value,0);if(!total)return path[Math.floor(path.length/2)];let target=total*fraction;for(let index=0;index<lengths.length;index++){if(target<=lengths[index]){const a=path[index],b=path[index+1],ratio=lengths[index]?target/lengths[index]:0;return[a[0]+(b[0]-a[0])*ratio,a[1]+(b[1]-a[1])*ratio] as [number,number]}target-=lengths[index]}return path[path.length-1]}
function Contours({levels,type,opacity}:{levels:ContourLevel[];type:'isobars'|'isoheights';opacity:number}){return <>{levels.map((level,index)=>{const major=type==='isobars'?Math.round(level.level)%4===0:Math.round(level.level)%160===0,labelled=type==='isoheights'||major,ranked=(level.paths as [number,number][][]).map(path=>({path,length:pathKm(path)})).filter(item=>item.path.length>2).sort((a,b)=>b.length-a.length),labelPaths=labelled?ranked.filter(item=>item.length>280).slice(0,2):[];return <Fragment key={`${type}:${level.level}:${index}`}>{ranked.map((item,pathIndex)=><Polyline key={`${type}:${level.level}:${pathIndex}`} positions={item.path as any} pathOptions={{color:type==='isobars'?'#f8fbff':'#ffe16b',weight:major?1.75:type==='isobars'?1.15:1.25,opacity:opacity*(major?1:.72),dashArray:type==='isoheights'?'7 4':undefined,className:`mid-model-contour ${type}${major?' major':''}`}}/>)}{labelPaths.flatMap((item,pathIndex)=>{const fractions=item.length>1600?[.32,.68]:[.5];return fractions.map((fraction,labelIndex)=>{const center=pointAlong(item.path,fraction);return <CircleMarker key={`label:${type}:${level.level}:${pathIndex}:${labelIndex}`} center={center} radius={.1} interactive={false} pathOptions={{opacity:0,fillOpacity:0}}><Tooltip permanent direction="center" opacity={Math.max(.55,opacity)} className={`mid-contour-label ${type}`}>{contourLabel(level.level,type)}</Tooltip></CircleMarker>})})}</Fragment>})}</>}
function PressureCenters({centers,opacity}:{centers:NonNullable<ModelContourResponse['frames'][number]['centers']>;opacity:number}){return <>{centers.map((center,index)=><CircleMarker key={`${center.type}:${center.lat}:${center.lon}:${index}`} center={[center.lat,center.lon]} radius={.1} interactive={false} pathOptions={{opacity:0,fillOpacity:0}}><Tooltip permanent direction="center" opacity={opacity} className={`mid-pressure-center ${center.type==='H'?'high':'low'}`}><span>{center.type}</span><small>{Math.round(center.value)} hPa</small></Tooltip></CircleMarker>)}</>}


export default function RadarPanel({lat,lon,timezone,analysis,isDay=true}:{lat:number;lon:number;timezone?:string;analysis?:RadarNowcast|null;isDay?:boolean}){
 const initial=useMemo(storedSettings,[]),source=sourceForLocation(analysis,lat,lon);
 const[nowMs,setNowMs]=useState(Date.now()),[clockOffsetMs,setClockOffsetMs]=useState(0),[radarFrames,setRadarFrames]=useState<RadarFrame[]>([]),[host,setHost]=useState(''),[index,setIndex]=useState(12),[playing,setPlaying]=useState(false),[locateRequest,setLocateRequest]=useState(0);
 const[showRadar,setShowRadar]=useState(initial.showRadar),[highResolution,setHighResolution]=useState(initial.highResolution),[showSatellite,setShowSatellite]=useState(initial.showSatellite),[showLightning,setShowLightning]=useState(initial.showLightning),[modelLines,setModelLines]=useState<ModelLineMode>(initial.modelLines),[satelliteFallback,setSatelliteFallback]=useState(false);
 const[radarOpacity,setRadarOpacity]=useState(initial.radarOpacity),[satelliteOpacity,setSatelliteOpacity]=useState(initial.satelliteOpacity),[lightningOpacity,setLightningOpacity]=useState(initial.lightningOpacity),[modelOpacity,setModelOpacity]=useState(initial.modelOpacity),[basemap,setBasemap]=useState<BasemapId>(initial.basemap);
 const[pxMeta,setPxMeta]=useState<Px250Meta|null>(null),[pxLoading,setPxLoading]=useState(false),[pxStatus,setPxStatus]=useState<PxStatus>('idle'),[pxMessage,setPxMessage]=useState('');
 const[operaFrames,setOperaFrames]=useState<OperaRasterFrame[]>([]),[operaError,setOperaError]=useState(''),[operaStatus,setOperaStatus]=useState<OperaStatus>('idle'),[operaMessage,setOperaMessage]=useState(''),[lightningData,setLightningData]=useState<LightningPointResponse>({points:[]}),[lightningError,setLightningError]=useState(''),[compositeError,setCompositeError]=useState(''),[productTimes,setProductTimes]=useState<CompositeProductTimes>(EMPTY_PRODUCT_TIMES),[modelData,setModelData]=useState<ModelContourResponse>({frames:[]}),[modelError,setModelError]=useState('');
 const[radarTileError,setRadarTileError]=useState(''),[satelliteTileError,setSatelliteTileError]=useState(''),[tileRevision,setTileRevision]=useState(0),[rasterZooming,setRasterZooming]=useState(false);
 const previousTimeline=useRef<number>(0),dwdLightning=lat>=47&&lat<=55.5&&lon>=5&&lon<=16,mtgLightning=lat>=-60&&lat<=72&&lon>=-75&&lon<=80;
 const referenceMs=nowMs+clockOffsetMs,referenceSeconds=Math.floor(referenceMs/1000);

 useEffect(()=>{const timer=window.setInterval(()=>setNowMs(Date.now()),30000);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{setRadarTileError('')},[lat,lon,source]);
 useEffect(()=>{try{localStorage.setItem(SETTINGS_KEY,JSON.stringify({basemap,showRadar,highResolution,showSatellite,showLightning,modelLines,radarOpacity,satelliteOpacity,lightningOpacity,modelOpacity} satisfies CompositeSettings));localStorage.setItem(LAYERS_KEY,JSON.stringify({showRadar,highResolution,showSatellite,showLightning,modelLines}))}catch{}},[basemap,showRadar,highResolution,showSatellite,showLightning,modelLines,radarOpacity,satelliteOpacity,lightningOpacity,modelOpacity]);
 useEffect(()=>{
  let alive=true;setPlaying(false);
  if(source==='dwd'){
   const supplied=(Array.isArray(analysis?.timeline)?analysis.timeline:[]).map(epochMs).filter(Number.isFinite).map(value=>Math.floor(value/1000)).sort((a,b)=>a-b),observed=epochMs(analysis?.observedAt),single=Number.isFinite(observed)?[Math.floor(observed/1000)]:[];
   setRadarFrames((supplied.length?supplied:single).map(time=>({time,path:'',future:time>Math.floor(Date.now()/1000)+90})));
  }else if(source!=='rainviewer')setRadarFrames([]);
  const fallbackNeeded=source==='rainviewer'||operaStatus==='error'||Boolean(source==='dwd'&&radarTileError&&!operaFrames.length);
  if(!fallbackNeeded||!showRadar||highResolution){if(source!=='rainviewer'){setHost('');if(source!=='dwd')setRadarFrames([])}return()=>{alive=false}}
  const controller=new AbortController(),load=()=>loadRainViewer(lat,lon,controller.signal).then(data=>{if(!alive)return;setHost(data.host);setRadarFrames([...(data.radar?.past??[]),...(data.radar?.nowcast??[]).map(item=>({...item,future:true}))])}).catch(()=>{if(alive){setRadarFrames([]);setHost('')}});void load();const timer=window.setInterval(load,300000);return()=>{alive=false;controller.abort();window.clearInterval(timer)};
 },[lat,lon,source,showRadar,highResolution,analysis?.observedAt,analysis?.timeline?.join('|'),operaStatus,radarTileError,operaFrames.length]);
 useEffect(()=>{const eligible=lat>=31.5&&lat<=72.5&&lon>=-30.5&&lon<=50.5;if(!eligible||!showRadar||highResolution){setOperaFrames([]);setOperaError('');setOperaStatus('idle');setOperaMessage('');return}const controller=new AbortController(),load=()=>{setOperaStatus(current=>current==='ready'?current:'loading');return loadOperaRaster(lat,lon,controller.signal).then(data=>{if(!data.frames?.length)throw new Error(data.error||'OPERA liefert derzeit keine Rasterstände.');setOperaFrames(data.frames);setOperaError('');setOperaMessage('');setOperaStatus(current=>current==='ready'?'ready':'loading')}).catch(error=>{if(!controller.signal.aborted){const message=error instanceof Error?error.message:String(error);setOperaFrames([]);setOperaError(message);setOperaMessage(message);setOperaStatus('error')}})};void load();const timer=window.setInterval(load,300000);return()=>{controller.abort();window.clearInterval(timer)}},[lat,lon,showRadar,highResolution]);
 useEffect(()=>{if(!showLightning){setLightningData({points:[]});setLightningError('');return}const controller=new AbortController(),load=()=>loadLightningPoints(lat,lon,controller.signal).then(data=>{setLightningData(data);setLightningError('')}).catch(error=>{if(!controller.signal.aborted){setLightningData({points:[],fallback:mtgLightning?'mtg-li':'none'});setLightningError(error instanceof Error?error.message:String(error))}});void load();const timer=window.setInterval(load,120000);return()=>{controller.abort();window.clearInterval(timer)}},[lat,lon,showLightning,mtgLightning]);
 useEffect(()=>{
  const needed=showSatellite||showLightning||showRadar;if(!needed){setProductTimes(EMPTY_PRODUCT_TIMES);setCompositeError('');return}
  const controller=new AbortController(),load=()=>loadCompositeTimes(lat,lon,controller.signal).then(data=>{setProductTimes(data);const server=epochMs(data.serverTime);setClockOffsetMs(Number.isFinite(server)&&Math.abs(server-Date.now())<=10*60000?server-Date.now():0);setCompositeError(data.errors?.join(' | ')||'')}).catch(error=>{if(!controller.signal.aborted){setProductTimes(EMPTY_PRODUCT_TIMES);setCompositeError(error instanceof Error?error.message:String(error))}});void load();const timer=window.setInterval(load,300000);return()=>{controller.abort();window.clearInterval(timer)};
 },[lat,lon,showSatellite,showLightning,showRadar]);
 useEffect(()=>{if(modelLines==='off'){setModelData({frames:[]});setModelError('');return}const controller=new AbortController(),load=()=>loadModelContours(lat,lon,controller.signal).then(data=>{setModelData(data);setModelError('')}).catch(error=>{if(!controller.signal.aborted){setModelData({frames:[]});setModelError(error instanceof Error?error.message:String(error))}});void load();const timer=window.setInterval(load,30*60000);return()=>{controller.abort();window.clearInterval(timer)}},[lat,lon,modelLines]);
 useEffect(()=>{let alive=true,controller:AbortController|null=null;setPxStatus('idle');setPxMessage('');const load=()=>{controller?.abort();controller=new AbortController();const request=controller;setPxLoading(true);loadPx250Metadata(lat,lon,request.signal).then(data=>{if(!alive||request.signal.aborted)return;const observed=epochMs(data.observedAt),fresh=data.available&&Number.isFinite(observed)&&observed>=Date.now()-60*60000&&observed<=Date.now()+15*60000,normalised=fresh?data:data.available?{...data,available:false,stale:true,reason:`Der gemeldete 250-m-Stand ist nicht aktuell (${data.observedAt||'Zeit unbekannt'}) und wird nicht als Livebild verwendet.`}:data;setPxMeta(normalised);if(!normalised.available)setHighResolution(false)}).catch(error=>{if(alive&&!request.signal.aborted){setPxMeta({available:false,nativeResolutionM:250,reason:error instanceof Error?error.message:String(error)});setHighResolution(false)}}).finally(()=>{if(alive&&!request.signal.aborted)setPxLoading(false)})};void load();const timer=window.setInterval(load,180000);return()=>{alive=false;controller?.abort();window.clearInterval(timer)}},[lat,lon]);
 useEffect(()=>{setSatelliteFallback(false);setSatelliteTileError('')},[isDay,lat,lon]);

 const dayTimes=normalisedIsoTimes(productTimes.satelliteDay,referenceMs),irTimes=normalisedIsoTimes(productTimes.satelliteIr,referenceMs);
 const legacyDay:CompositeProduct|undefined=dayTimes.length?{provider:'eumetsat',layer:'mtg_fd:vis06_hrfi',label:'MTG FCI VIS 0,6 HRFI',resolutionKm:.5,times:dayTimes}:undefined;
 const legacyIr:CompositeProduct|undefined=irTimes.length?{provider:'eumetsat',layer:'mtg_fd:ir105_hrfi',label:'MTG FCI IR 10,5 HRFI',resolutionKm:1,times:irTimes}:undefined;
 const satelliteProduct:CompositeProduct|undefined=isDay&&!satelliteFallback?(productTimes.satelliteDayProduct||legacyDay):(productTimes.satelliteIrProduct||legacyIr),satellitePrecipProduct=productTimes.satellitePrecipProduct;
 const satelliteAvailableTimes=normalisedIsoTimes(satelliteProduct?.times,referenceMs),satelliteLatestIso=Number.isFinite(epochMs(satelliteProduct?.latestTime))?new Date(epochMs(satelliteProduct?.latestTime)).toISOString():'',satelliteLayer=satelliteProduct?.layer||'',satelliteProvider=satelliteProduct?.provider||'eumetsat',satelliteName=satelliteProduct?.label||(isDay&&!satelliteFallback?'Satellit Tag':'Satellit IR'),satelliteResolution=satelliteProduct?.resolutionKm?`${satelliteProduct.resolutionKm.toLocaleString('de-DE')} km`:'';
 const satPrecipTimes=normalisedIsoTimes(satellitePrecipProduct?.times,referenceMs),satPrecipLayer=satellitePrecipProduct?.layer||'',satPrecipProvider=satellitePrecipProduct?.provider||'eumetsat';
 const dwdTimeline=useMemo(()=>uniqueTimedFrames<RadarFrame>([...radarFrames,...toFrames(productTimes.dwdRadar,referenceSeconds)],referenceSeconds-190*60,referenceSeconds+130*60),[radarFrames,productTimes.dwdRadar,referenceSeconds]);
 const operaTimeline=useMemo(()=>uniqueTimedFrames(operaFrames.map(frame=>({time:Math.floor(Date.parse(frame.time)/1000),frame})),referenceSeconds-190*60,referenceSeconds+20*60),[operaFrames,referenceSeconds]);
 const satelliteTimeline=useMemo(()=>satelliteAvailableTimes.map(value=>({time:Math.floor(Date.parse(value)/1000),iso:value})),[satelliteAvailableTimes.join('|')]);
 const satellitePrecipTimeline=useMemo(()=>satPrecipTimes.map(value=>({time:Math.floor(Date.parse(value)/1000),iso:value})),[satPrecipTimes.join('|')]);
 const lightningAvailableTimes=normalisedIsoTimes(dwdLightning?productTimes.dwdLightning:productTimes.mtgLightning,referenceMs),lightningTimeline=useMemo(()=>lightningAvailableTimes.map(value=>({time:Math.floor(Date.parse(value)/1000),iso:value})),[lightningAvailableTimes.join('|')]);
 const modelTimeline=useMemo(()=>(modelData.frames??[]).map(frame=>({time:Math.floor(Date.parse(frame.time)/1000),frame})).filter(item=>Number.isFinite(item.time)),[modelData.frames]);
 const pxObservedMs=pxMeta?.observedAt?epochMs(pxMeta.observedAt):NaN,pxFresh=Boolean(pxMeta?.available)&&Number.isFinite(pxObservedMs)&&pxObservedMs>=referenceMs-60*60000&&pxObservedMs<=referenceMs+15*60000;
 useEffect(()=>{if(highResolution&&!pxFresh){setHighResolution(false);setShowRadar(true)}},[highResolution,pxFresh]);

 const frames=useMemo(()=>buildCompositeTimeline(referenceSeconds),[Math.floor(referenceSeconds/300)]);
 useEffect(()=>{const target=previousTimeline.current||referenceSeconds,indexForTarget=frames.reduce((best,frame,i)=>Math.abs(frame.time-target)<Math.abs(frames[best].time-target)?i:best,0);setIndex(clamp(indexForTarget,0,frames.length-1))},[frames[0]?.time]);
 const canAnimate=showRadar||showSatellite||showLightning||modelLines!=='off';
 useEffect(()=>{if(!playing||!canAnimate)return;const timer=window.setInterval(()=>setIndex(current=>current>=frames.length-1?0:current+1),900);return()=>window.clearInterval(timer)},[playing,canAnimate,frames.length]);
 const targetSeconds=frames[index]?.time??referenceSeconds,targetMs=targetSeconds*1000;previousTimeline.current=targetSeconds;

 const dwdBlend=blendTimedFrames(dwdTimeline,targetSeconds,{interpolationGapSeconds:12*60,earlyGraceSeconds:8*60,lateGraceSeconds:8*60,fadeSeconds:25*60});
 const rainBlend=blendTimedFrames(radarFrames,targetSeconds,{interpolationGapSeconds:15*60,earlyGraceSeconds:15*60,lateGraceSeconds:20*60,fadeSeconds:100*60});
 const operaBlend=blendTimedFrames(operaTimeline,targetSeconds,{interpolationGapSeconds:7*60,earlyGraceSeconds:7*60,lateGraceSeconds:7*60,fadeSeconds:35*60});
 const dwdUnavailable=Boolean(radarTileError)||!dwdTimeline.length,activeSource:CompositeSource=source==='dwd'?(dwdUnavailable?(operaFrames.length&&operaStatus!=='error'?'opera':'rainviewer'):'dwd'):source==='opera'?(operaFrames.length&&operaStatus!=='error'?'opera':operaStatus==='error'?'rainviewer':'opera'):source;
 const primaryRadarBlend=activeSource==='dwd'?dwdBlend:activeSource==='rainviewer'?rainBlend:operaBlend,primaryRadarFactor=showRadar&&!highResolution?blendOpacity(primaryRadarBlend as BlendFrame<TimedFrame>[]):0;
 const satelliteBlend=satelliteProduct?.latestOnly?blendTimedFrames([{time:referenceSeconds,iso:''}],targetSeconds,{earlyGraceSeconds:10*60,lateGraceSeconds:10*60,fadeSeconds:35*60}):blendTimedFrames(satelliteTimeline,targetSeconds,{interpolationGapSeconds:35*60,earlyGraceSeconds:45*60,lateGraceSeconds:45*60,fadeSeconds:105*60});
 const satPrecipRawBlend=blendTimedFrames(satellitePrecipTimeline,targetSeconds,{interpolationGapSeconds:35*60,earlyGraceSeconds:45*60,lateGraceSeconds:45*60,fadeSeconds:105*60}),satPrecipRawFactor=blendOpacity(satPrecipRawBlend),satPrecipFactor=showRadar&&!highResolution&&activeSource!=='dwd'?Math.min(satPrecipRawFactor,Math.max(0,1-primaryRadarFactor)):0,satPrecipScale=satPrecipRawFactor>0?satPrecipFactor/satPrecipRawFactor:0;
 const lightningRasterBlend=blendTimedFrames(lightningTimeline,targetSeconds,{interpolationGapSeconds:15*60,earlyGraceSeconds:12*60,lateGraceSeconds:12*60,fadeSeconds:35*60});
 const pxBlend=pxFresh?blendTimedFrames([{time:Math.floor(pxObservedMs/1000)}],targetSeconds,{earlyGraceSeconds:10*60,lateGraceSeconds:15*60,fadeSeconds:45*60}):[],pxFactor=blendOpacity(pxBlend);
 const modelBlend=blendTimedFrames(modelTimeline,targetSeconds,{interpolationGapSeconds:75*60,earlyGraceSeconds:40*60,lateGraceSeconds:40*60,fadeSeconds:45*60});
 const future=targetSeconds>referenceSeconds+90,relative=relativeLabel(targetSeconds,referenceSeconds),dwdLayer=productTimes.dwdRadarLayer||analysis?.radarLayer||'dwd:Radar_rv_product_1x1km_ger';
 const pointProvider=Boolean(lightningData.points?.length),licensedGlobal=Boolean(lightningData.commercial&&lightningData.provider),lightningProvider=lightningData.provider||(!dwdLightning&&mtgLightning?'EUMETSAT MTG-LI':'keine freie Punktquelle'),lightningResolution=lightningData.nativeResolutionKm?`${formatDecimal(lightningData.nativeResolutionKm,1)} km`:pointProvider?'Punktortung':dwdLightning?'1 km':mtgLightning?'2 km':'optional',lightningName=pointProvider?`${lightningProvider} · ${lightningResolution}`:licensedGlobal?`${lightningProvider} · keine Aktivität im aktuellen Zeitfenster`:dwdLightning?'DWD Blitzdichte 1 km':mtgLightning?'EUMETSAT MTG-LI AFA 2 km':'keine frei nutzbare Echtzeitquelle';
 const visibleLightning=(lightningData.points??[]).filter(point=>{const stamp=Date.parse(point.observedAt||lightningData.observedAt||'');if(!Number.isFinite(stamp))return Math.abs(targetMs-referenceMs)<8*60000;const age=(targetMs-stamp)/60000;return age>=-1&&age<=120}),vectorLightning=visibleLightning.length>0,showPxAtTime=showRadar&&highResolution&&pxFactor>0,currentBasemap=BASEMAPS[basemap]??BASEMAPS.positron;
 const satelliteFactor=showSatellite?blendOpacity(satelliteBlend):0,satelliteDisplayFrame=dominantBlendFrame(satelliteBlend),satPrecipDisplayFrame=dominantBlendFrame(satPrecipRawBlend),showSatelliteAtTime=Boolean(satelliteProduct)&&satelliteFactor>0,modelFrameBlend=modelBlend.map(item=>({...item,frame:item.frame.frame})),dominantModelFrame=dominantBlendFrame(modelFrameBlend as any) as ModelContourResponse['frames'][number]|undefined,operaDisplayItem=dominantBlendFrame(operaBlend) as {time:number;frame:OperaRasterFrame}|undefined,operaDisplayFrame=operaDisplayItem?.frame,operaFactor=blendOpacity(operaBlend),rainDisplayFrame=dominantBlendFrame(rainBlend);
 const latestVectorStamp=(lightningData.points??[]).map(point=>Date.parse(point.observedAt||lightningData.observedAt||'')).filter(Number.isFinite).sort((a,b)=>a-b).at(-1),vectorStamp=Number.isFinite(latestVectorStamp)?`Stand ${formatInZone(latestVectorStamp!,timezone,{hour:'2-digit',minute:'2-digit'})}`:'keine Zeitangabe';
 const latestRadarTime=(activeSource==='dwd'?dwdTimeline:activeSource==='rainviewer'?radarFrames:operaTimeline).at(-1)?.time,latestSatelliteTime=satelliteTimeline.at(-1)?.time,latestSatPrecipTime=satellitePrecipTimeline.at(-1)?.time,latestLightningTime=lightningTimeline.at(-1)?.time,latestModelTime=modelTimeline.at(-1)?.time;
 const pxDetail=pxLoading?'Prüfung …':pxFresh?`${pxMeta?.product==='hx'?'DWD HX · Deutschland':pxMeta?.siteName??pxMeta?.site?.toUpperCase()} · 250 m · Stand ${formatInZone(pxObservedMs,timezone,{hour:'2-digit',minute:'2-digit'})}`:pxMeta?.stale?'Quelle veraltet':'nicht verfügbar';
 const radarStamp=blendStamp(primaryRadarBlend as BlendFrame<TimedFrame>[],referenceSeconds,timezone,latestRadarTime),satPrecipStamp=blendStamp(satPrecipRawBlend,referenceSeconds,timezone,latestSatPrecipTime),radarDetail=activeSource==='dwd'?`DWD · 1 km · ${radarStamp}`:activeSource==='opera'?`OPERA CIRRUS · 1 km · 5 min · ${radarStamp}`:`RainViewer-Fallback · ${radarStamp}${satPrecipFactor>.04?` · H SAF ${satPrecipStamp}`:''}`;
 const satelliteDetail=satelliteProduct?`${satelliteResolution}${satelliteProduct.fallback?' · Fallback':''} · ${satelliteProduct.latestOnly?(satelliteLatestIso?`Stand ${formatInZone(Date.parse(satelliteLatestIso),timezone,{hour:'2-digit',minute:'2-digit'})}`:'aktueller Dienststand'):blendStamp(satelliteBlend,referenceSeconds,timezone,latestSatelliteTime)}`:'Quelle nicht verfügbar',lightningDetail=pointProvider?`${lightningResolution} · ${vectorStamp}`:dwdLightning?`DWD · 1 km · ${blendStamp(lightningRasterBlend,referenceSeconds,timezone,latestLightningTime)}`:mtgLightning?`MTG-LI · 2 km · ${blendStamp(lightningRasterBlend,referenceSeconds,timezone,latestLightningTime)}`:'global optional';
 const modelModeLabel=modelLines==='isobars'?'Isobaren':modelLines==='isoheights'?'500-hPa-Isohypsen':modelLines==='both'?'Isobaren + Isohypsen':'Aus',modelDetail=modelLines==='off'?'Aus':modelData.frames?.length?`${modelModeLabel} · ${modelData.grid?.scope||'Großregion'} · ${modelData.model||'Best Match'} · ${blendStamp(modelBlend,referenceSeconds,timezone,latestModelTime)}`:'wird geladen …';
 const onPxStatus=useCallback((status:PxStatus,message='')=>{setPxStatus(status);setPxMessage(message)},[]),onOperaStatus=useCallback((status:OperaStatus,message='')=>{setOperaStatus(status);setOperaMessage(message);if(status==='error')setOperaError(message);else if(status==='ready')setOperaError('')},[]),step=(amount:number)=>{setPlaying(false);setIndex(current=>clamp(current+amount,0,frames.length-1))},togglePlay=()=>{if(!canAnimate)return;if(!playing&&index>=frames.length-1)setIndex(0);setPlaying(value=>!value)},selectPrecipitation=(mode:'off'|'standard'|'px250')=>{setPlaying(false);setShowRadar(mode!=='off');setHighResolution(mode==='px250')},toggleRadar=()=>selectPrecipitation(showRadar&&!highResolution?'off':'standard'),toggleHighRes=()=>{if(!pxFresh)return;selectPrecipitation(showRadar&&highResolution?'off':'px250')},cycleModelLines=()=>setModelLines(current=>MODEL_LINE_MODES[(MODEL_LINE_MODES.indexOf(current)+1)%MODEL_LINE_MODES.length]);
 const sourceText=showRadar?(highResolution?(pxMeta?.product==='hx'?'DWD HX über MID-Worker; nationales 250-m-Deutschlandkomposit':'DWD PX250 über MID-Worker; 250-m-Standortradar'):activeSource==='dwd'?'DWD-RV; offizielles 1-km-Komposit mit Beobachtungen und Nowcast':activeSource==='opera'?'EUMETNET OPERA CIRRUS/ORD; echtes europäisches 1-km-Reflektivitätsraster im 5-Minuten-Zyklus, CC BY 4.0':activeSource==='rainviewer'?'RainViewer nur als letzter Radar-Fallback; danach mit klarer Altersfahne ausgeblendet':'keine verwertbare Radarkarte'):'Radar ausgeblendet';
 const radarDisplayItem=dominantBlendFrame(primaryRadarBlend as BlendFrame<TimedFrame>[]),displayedRadarSeconds=highResolution&&Number.isFinite(pxObservedMs)?Math.floor(pxObservedMs/1000):radarDisplayItem?.time,displayedRadarMs=displayedRadarSeconds!==undefined?displayedRadarSeconds*1000:NaN,radarAgeMinutes=Number.isFinite(displayedRadarMs)?Math.max(0,Math.round((referenceMs-displayedRadarMs)/60000)):undefined;
 const radarProvider=highResolution?(pxMeta?.product==='hx'?'DWD HX':'DWD PX250'):activeSource==='dwd'?'DWD RV':activeSource==='opera'?'EUMETNET OPERA CIRRUS':activeSource==='rainviewer'?'RainViewer-Fallback':'keine Radarquelle',radarProduct=highResolution?'Reflektivität':activeSource==='dwd'?'Niederschlagsrate und offizielles Nowcast':activeSource==='opera'?'Maximalreflektivität DBZH':activeSource==='rainviewer'?'Reflektivität / Anbieter-Nowcast':'nicht verfügbar',radarResolution=highResolution?'250 m':activeSource==='dwd'||activeSource==='opera'?'1 km':activeSource==='rainviewer'?'anbieterabhängig':'—';
 const radarStatus=!showRadar?'ausgeblendet':highResolution?'beobachtet':activeSource==='dwd'&&displayedRadarSeconds!==undefined&&displayedRadarSeconds>referenceSeconds+90?'offizielle Vorhersage':activeSource==='rainviewer'&&Boolean(rainDisplayFrame?.future)?'Anbieter-Nowcast · Fallback':primaryRadarBlend.length>1?'beobachtet · MID-Überblendung realer Stände':'beobachtet',radarLicense=highResolution||activeSource==='dwd'?'DWD Open Data':activeSource==='opera'?'CC BY 4.0 · EUMETNET OPERA':activeSource==='rainviewer'?'RainViewer-Nutzungsbedingungen':'—';
 const infoRows=[{label:'Quelle',value:radarProvider},{label:'Produkt',value:radarProduct},{label:'Auflösung',value:radarResolution},{label:'Stand',value:Number.isFinite(displayedRadarMs)?`${formatInZone(displayedRadarMs,timezone,{hour:'2-digit',minute:'2-digit'})} Uhr`:'nicht verfügbar'},{label:'Alter',value:radarAgeMinutes===undefined?'nicht bestimmbar':radarAgeMinutes<1?'unter 1 min':`${radarAgeMinutes} min`},{label:'Status',value:radarStatus},{label:'Lizenz',value:radarLicense},{label:'Fallback',value:'DWD → OPERA CIRRUS → RainViewer'}];
 const dwdProxy=wmsUrl('dwd'),eumetProxy=wmsUrl('eumetsat'),satelliteProxy=satelliteProvider==='dwd'?dwdProxy:eumetProxy,satPrecipProxy=satPrecipProvider==='dwd'?dwdProxy:eumetProxy;

 return <section className="card composite-card"><Title eye="Radar · Satellit · Blitze" title="Kompositbild" action={<CompositeInfo rows={infoRows}>Aktive Ebenen: {sourceText}{showSatellite&&satelliteProduct?` · ${satelliteName}${satelliteResolution?` ${satelliteResolution}`:''}`:''}{showLightning?` · ${lightningName}`:''}{modelLines!=='off'?` · ${modelData.provider||'Open-Meteo'} Modelllinien (${modelData.resolutionNote||'regional'})`:''}. Die Zeitachse reicht von −1 bis +2 Stunden. Reale Produktstände werden nur weich überblendet; außerhalb der Datenabdeckung sinkt die Deckkraft, statt nicht vorhandene Beobachtungen zu erfinden. Kartenbasis: {currentBasemap.label}. Keine amtliche Warnung.</CompositeInfo>}/>
  <div className="composite-layer-switches" aria-label="Komposit-Layer">
   <LayerSwitch active={showRadar&&!highResolution} title="Standard-Niederschlagsradar ein- oder ausblenden" onClick={toggleRadar} icon={<Droplets size={18}/>} label="Niederschlag · 1 km" detail={radarDetail}/>
   <LayerSwitch active={showRadar&&highResolution} disabled={pxLoading||!pxFresh} title={pxMeta?.reason||'Bestes verfügbares DWD-Radarprodukt mit 250 m Rasterweite'} onClick={toggleHighRes} icon={<RadioTower size={18}/>} label="Niederschlag · 250 m" detail={pxDetail}/>
   <LayerSwitch active={showSatellite} title="Bestes aktuell verfügbares Satellitenprodukt für Tag beziehungsweise Nacht ein- oder ausblenden" onClick={()=>setShowSatellite(value=>!value)} icon={isDay?<CloudSun size={18}/>:<Satellite size={18}/>} label={`Satellit ${isDay?'Tag':'IR'}`} detail={satelliteDetail}/>
   <LayerSwitch active={showLightning} title="Zeitcodierte Blitzaktivität ein- oder ausblenden" onClick={()=>setShowLightning(value=>!value)} icon={<Zap size={18}/>} label="Echtzeitblitze" detail={lightningDetail}/>
   <LayerSwitch active={modelLines!=='off'} title="Modelllinien durchschalten: Aus, Isobaren, 500-hPa-Isohypsen, beide" onClick={cycleModelLines} icon={<Gauge size={18}/>} label="Modelllinien" detail={modelDetail}/>
  </div>
  <div className="radarmap">
   <div className="composite-basemap-control"><Layers3 size={14}/><label><span>Kartenbasis</span><select value={basemap} onChange={event=>setBasemap(event.target.value as BasemapId)}>{(Object.entries(BASEMAPS) as [BasemapId,(typeof BASEMAPS)[BasemapId]][]).map(([id,item])=><option key={id} value={id}>{item.label} · {item.detail}</option>)}</select></label></div>
   <button type="button" className="composite-locate-button" onClick={()=>setLocateRequest(value=>value+1)} title="Karte wieder auf den gewählten Standort zentrieren" aria-label="Karte auf Standort zentrieren"><LocateFixed size={16}/></button>
   <MapContainer center={[lat,lon]} zoom={7} className="leafletmap" scrollWheelZoom={false} fadeAnimation={false} zoomAnimation={false}><MoveMap lat={lat} lon={lon} locateRequest={locateRequest}/><RasterCacheRevision onZoomStart={()=>setRasterZooming(true)} onZoomEnd={()=>{setTileRevision(value=>value+1);requestAnimationFrame(()=>setRasterZooming(false))}}/><TileLayer key={basemap} attribution={currentBasemap.attribution} url={currentBasemap.url} zIndex={100} keepBuffer={0} updateWhenZooming={false}/>
    {!rasterZooming&&showSatellite&&satelliteProduct&&satelliteDisplayFrame&&(()=>{const iso=(satelliteDisplayFrame as any).iso||satelliteLatestIso||'',opacity=satelliteOpacity/100*satelliteFactor;return opacity>.01&&<WMSTileLayer key={`${satelliteProvider}:${satelliteLayer}:${iso||'latest'}:${tileRevision}`} url={rasterVersionUrl(satelliteProxy,tileRevision,iso)} opacity={opacity} zIndex={220} keepBuffer={0} updateWhenZooming={false} eventHandlers={{load:()=>setSatelliteTileError(''),tileerror:()=>{setSatelliteTileError(`${satelliteName} lieferte ${iso?`für ${iso}`:'als aktuellsten Quellenstand'} keine Kartenkachel.`);if(isDay&&!satelliteFallback&&(productTimes.satelliteIrProduct||legacyIr))setSatelliteFallback(true)}}} params={({layers:satelliteLayer,styles:'',format:'image/png',transparent:true,version:satelliteProvider==='eumetsat'?'1.3.0':'1.1.1',...(iso?{time:iso}:{})} as any)} attribution={satelliteProvider==='dwd'?'Satellit &copy; DWD':'Satellit &copy; EUMETSAT'}/>})()}
    {!rasterZooming&&showRadar&&!highResolution&&activeSource==='dwd'&&dwdBlend.map(({frame,weight})=>{const iso=new Date(frame.time*1000).toISOString();return <WMSTileLayer key={`dwd-radar:${dwdLayer}:${iso}:${tileRevision}`} url={rasterVersionUrl(dwdProxy,tileRevision,iso)} opacity={radarOpacity/100*weight} zIndex={360} keepBuffer={0} updateWhenZooming={false} eventHandlers={{load:()=>setRadarTileError(''),tileerror:()=>setRadarTileError(`DWD-Radar lieferte für ${iso} keine Kartenkachel.`)}} params={({layers:dwdLayer,styles:'',format:'image/png',transparent:true,version:'1.1.1',time:iso,tiled:true} as any)} attribution="Radar und Nowcast &copy; DWD"/>})}
    {showRadar&&!highResolution&&activeSource==='opera'&&operaDisplayFrame&&operaFactor>.01&&<Suspense fallback={null}><LazyOperaRasterOverlay key={operaDisplayFrame.fileUrl} frame={operaDisplayFrame} opacity={radarOpacity/100*operaFactor} onStatus={onOperaStatus}/></Suspense>}
    {!rasterZooming&&showRadar&&!highResolution&&activeSource==='rainviewer'&&rainBlend.map(({frame,weight})=>frame.path&&host?<TileLayer key={`${frame.time}:${frame.path}:${tileRevision}`} attribution="Radar &copy; RainViewer" url={`${host}${frame.path}/256/{z}/{x}/{y}/2/1_1.png`} maxNativeZoom={7} maxZoom={12} opacity={radarOpacity/100*weight} zIndex={360} keepBuffer={0} updateWhenZooming={false}/>:null)}
    {!rasterZooming&&showRadar&&!highResolution&&activeSource!=='dwd'&&satellitePrecipProduct&&satPrecipScale>0&&satPrecipDisplayFrame&&(()=>{const iso=(satPrecipDisplayFrame as any).iso;return <WMSTileLayer key={`sat-precip:${satPrecipLayer}:${iso}:${tileRevision}`} url={rasterVersionUrl(satPrecipProxy,tileRevision,iso)} opacity={radarOpacity/100*satPrecipFactor} zIndex={350} keepBuffer={0} updateWhenZooming={false} params={({layers:satPrecipLayer,styles:'',format:'image/png',transparent:true,version:'1.3.0',time:iso} as any)} attribution="Satelliten-Niederschlagsrate &copy; EUMETSAT H SAF"/>})()}
    {showPxAtTime&&pxMeta?.available&&<Suspense fallback={null}><LazyPx250Overlay meta={pxMeta} opacity={radarOpacity/100*pxFactor} onStatus={onPxStatus}/></Suspense>}
    {showLightning&&vectorLightning&&visibleLightning.map(point=>{const style=lightningStyle(point,targetMs,lightningData.observedAt);return <CircleMarker key={point.id} center={[point.lat,point.lon]} radius={style.radius} pathOptions={{color:style.color,weight:style.weight,opacity:style.opacity*lightningOpacity/100,fillOpacity:0,className:`mid-lightning-ring${style.newest?' newest':''}`}}><Popup><strong>{lightningProvider}</strong><br/>{formatAge(style.age)}{point.pulseType&&<><br/>{point.pulseType.toUpperCase()}</>}{point.observedAt&&<><br/>{formatInZone(Date.parse(point.observedAt),timezone,{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</>}</Popup></CircleMarker>})}
    {!rasterZooming&&showLightning&&!vectorLightning&&dwdLightning&&lightningRasterBlend.map(({frame,weight})=><WMSTileLayer key={`dwd-lightning:${(frame as any).iso}:${tileRevision}`} url={rasterVersionUrl(dwdProxy,tileRevision,(frame as any).iso)} opacity={lightningOpacity/100*weight} zIndex={470} keepBuffer={0} updateWhenZooming={false} params={({layers:'dwd:Blitzdichte',styles:'',format:'image/png',transparent:true,version:'1.1.1',time:(frame as any).iso,tiled:true} as any)} attribution="Blitzdichte &copy; DWD"/>)}
    {!rasterZooming&&showLightning&&!vectorLightning&&!dwdLightning&&mtgLightning&&lightningRasterBlend.map(({frame,weight})=><WMSTileLayer key={`mtg-li:${(frame as any).iso}:${tileRevision}`} url={rasterVersionUrl(eumetProxy,tileRevision,(frame as any).iso)} opacity={lightningOpacity/100*weight} zIndex={470} keepBuffer={0} updateWhenZooming={false} params={({layers:'mtg_fd:li_afa',styles:'',format:'image/png',transparent:true,version:'1.1.1',time:(frame as any).iso,tiled:true} as any)} attribution="Lightning Imager &copy; EUMETSAT"/>)}
    {modelLines!=='off'&&modelFrameBlend.map(({frame,weight})=><Fragment key={`model:${frame.time}`}>{(modelLines==='isobars'||modelLines==='both')&&<Contours levels={frame.isobars} type="isobars" opacity={modelOpacity/100*weight}/>} {(modelLines==='isoheights'||modelLines==='both')&&<Contours levels={frame.isoheights} type="isoheights" opacity={modelOpacity/100*weight}/>}</Fragment>)}{modelLines!=='off'&&dominantModelFrame?.centers?.length?<PressureCenters centers={dominantModelFrame.centers} opacity={modelOpacity/100}/>:null}
    <CircleMarker center={[lat,lon]} radius={7} pathOptions={{color:'#fff',weight:2,fillColor:'#1f8cff',fillOpacity:0.95}}><Popup>Gewählter Standort</Popup></CircleMarker>
   </MapContainer>
   <CompositeLegend source={activeSource} showRadar={showRadar} highResolution={highResolution} showSatellite={showSatellite&&showSatelliteAtTime} satelliteName={`${satelliteName}${showSatelliteAtTime?` · ${blendStamp(satelliteBlend,referenceSeconds,timezone,latestSatelliteTime)}`:''}`} showLightning={showLightning} lightningProvider={lightningProvider} vectorLightning={vectorLightning} relative={relative} pxSite={highResolution?(pxMeta?.product==='hx'?'Deutschlandkomposit HX':pxMeta?.siteName):undefined} satellitePrecip={satPrecipFactor>.04} modelLines={modelLines}/>
  </div>
  <div className="radarcontrols composite-controls">
   <div className="radar-playback-buttons"><button className="secondary" disabled={!canAnimate||index<=0} onClick={()=>step(-1)} title="Vorheriger Kompositzeitschritt" aria-label="Vorheriger Kompositzeitschritt"><SkipBack size={17}/></button><button className="secondary play" disabled={!canAnimate} onClick={togglePlay} title={playing?'Animation pausieren':'Kompositfilm abspielen'} aria-label={playing?'Animation pausieren':'Kompositfilm abspielen'}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><button className="secondary" disabled={!canAnimate||index>=frames.length-1} onClick={()=>step(1)} title="Nächster Kompositzeitschritt" aria-label="Nächster Kompositzeitschritt"><SkipForward size={17}/></button></div>
   <div className="range timeline"><small>{canAnimate?`Kompositfilm ${frames.length} Schritte · −1 h bis +2 h`:'Keine zeitabhängigen Layer aktiv'}</small><input type="range" min={0} max={frames.length-1} value={index} disabled={!canAnimate} onChange={event=>{setPlaying(false);setIndex(Number(event.target.value))}}/></div>
   <time className={future?'future':''}><span>{relative}</span><small>{formatInZone(targetMs,timezone,{hour:'2-digit',minute:'2-digit'})}{future?' · Prognosefenster':''}</small></time>
   <div className="layer-opacity-controls" aria-label="Deckkraft je Layer">{showRadar&&<label><span>Niederschlag</span><b>{radarOpacity}%</b><input type="range" min={15} max={100} value={radarOpacity} onChange={event=>setRadarOpacity(Number(event.target.value))}/></label>}{showSatellite&&<label><span>Satellit</span><b>{satelliteOpacity}%</b><input type="range" min={15} max={100} value={satelliteOpacity} onChange={event=>setSatelliteOpacity(Number(event.target.value))}/></label>}{showLightning&&<label><span>Blitze</span><b>{lightningOpacity}%</b><input type="range" min={20} max={100} value={lightningOpacity} onChange={event=>setLightningOpacity(Number(event.target.value))}/></label>}{modelLines!=='off'&&<label><span>Modelllinien</span><b>{modelOpacity}%</b><input type="range" min={20} max={100} value={modelOpacity} onChange={event=>setModelOpacity(Number(event.target.value))}/></label>}</div>
  </div>
  {highResolution&&pxStatus==='loading'&&<small className="source composite-source-note"><RadioTower size={12}/>DWD-250-m-HDF5-Daten werden über den Worker geladen und lokal gerendert …</small>}
  {highResolution&&pxStatus==='error'&&<small className="source warning">Das 250-m-Radar konnte nicht dargestellt werden: {pxMessage}</small>}
  {highResolution&&!showPxAtTime&&<small className="source warning">Der 250-m-Einzelstand wird außerhalb seines realen Produktzeitpunkts allmählich ausgeblendet.</small>}
  {showRadar&&activeSource==='dwd'&&!highResolution&&!dwdTimeline.length&&<small className="source warning">Der Worker meldet derzeit keine gültigen DWD-Radarzeitpunkte.</small>}
  {showRadar&&source==='dwd'&&radarTileError&&<small className="source warning">{radarTileError}</small>}
  {showRadar&&!highResolution&&operaStatus==='loading'&&activeSource==='opera'&&<small className="source composite-source-note"><RadioTower size={12}/>EUMETNET-OPERA-CIRRUS-Raster (1 km) wird über den Worker geladen und lokal reprojiziert …</small>}
  {showRadar&&!highResolution&&operaError&&<small className="source warning">OPERA-CIRRUS konnte nicht geladen werden: {operaMessage||operaError}{activeSource==='rainviewer'?' · RainViewer ist als letzter Fallback aktiv.':''}</small>}
  {showSatellite&&!satelliteProduct&&<small className="source warning">Der Worker meldet derzeit kein verfügbares Satellitenprodukt.</small>}{showSatellite&&satelliteProduct?.latestOnly&&<small className="source warning">Für dieses Satellitenprodukt ist keine verlässliche Zeitdimension verfügbar. Der Dienststand wird nur in einem engen Fenster um „Jetzt“ eingeblendet.</small>}
  {showSatellite&&satelliteTileError&&<small className="source warning">{satelliteTileError}{isDay&&!satelliteFallback?' MID wechselt automatisch auf das IR-Produkt.':''}</small>}
  {(showSatellite||showLightning||showRadar)&&compositeError&&<small className="source warning">Produktzeiten konnten teilweise nicht geprüft werden: {compositeError}</small>}
  {showLightning&&lightningError&&<small className="source warning">Blitzpunkte konnten nicht geladen werden; sofern der Ort abgedeckt ist, wird das DWD- beziehungsweise MTG-LI-Raster verwendet.</small>}
  {showLightning&&!dwdLightning&&!mtgLightning&&!pointProvider&&!licensedGlobal&&<small className="source warning">Für diesen Ort ist ohne lizenzierte globale Zugangsdaten keine frei nutzbare Echtzeit-Blitzquelle verfügbar.</small>}
  {modelLines!=='off'&&modelError&&<small className="source warning">Modelllinien konnten nicht geladen werden: {modelError}</small>}
 </section>;
}
