import {lazy,Suspense,useCallback,useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import {CloudSun,Droplets,Layers3,LocateFixed,Pause,Play,RadioTower,Satellite,SkipBack,SkipForward,Zap} from 'lucide-react';
import {CircleMarker,MapContainer,Popup,TileLayer,WMSTileLayer,useMap} from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import type {RadarNowcast} from './weather';
import {loadPx250Metadata,type Px250Meta} from './Px250Source';
import {loadCompositeTimes,loadLightningPoints,loadOperaGrid,type CompositeProductTimes,type CompositeSource,type LightningPoint,type LightningPointResponse,type OperaGridFrame,type OperaGridPoint} from './CompositeData';

const LazyPx250Overlay=lazy(()=>import('./Px250Overlay'));
type RadarFrame={time:number;path?:string;future?:boolean};
type RadarResponse={host:string;radar:{past:RadarFrame[];nowcast?:RadarFrame[]}};
type PxStatus='idle'|'loading'|'ready'|'error';
type BasemapId='osm'|'positron'|'dark';
type CompositeSettings={basemap:BasemapId;showRadar:boolean;highResolution:boolean;showSatellite:boolean;showLightning:boolean;radarOpacity:number;satelliteOpacity:number;lightningOpacity:number};
const SETTINGS_KEY='mid:composite-settings:v2';
const BASEMAPS:Record<BasemapId,{label:string;detail:string;url:string;attribution:string}>={
 osm:{label:'OpenStreetMap',detail:'Standard',url:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',attribution:'&copy; OpenStreetMap-Mitwirkende'},
 positron:{label:'Schlicht hell',detail:'CARTO Positron',url:'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',attribution:'&copy; OpenStreetMap-Mitwirkende &copy; CARTO'},
 dark:{label:'Schlicht dunkel',detail:'CARTO Dark Matter',url:'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',attribution:'&copy; OpenStreetMap-Mitwirkende &copy; CARTO'}
};
const DWD_RATE_LEGEND=[
 {value:'0,1',color:'#d9f3ff'},{value:'0,5',color:'#72c9ff'},{value:'1',color:'#2f91e3'},{value:'2,5',color:'#43c879'},
 {value:'5',color:'#f0d447'},{value:'10',color:'#f59b3d'},{value:'20',color:'#e34b4b'},{value:'50＋',color:'#b83fc8'}
];
const RAINVIEWER_LEGEND=[{dbz:10,color:'#d2c48b'},{dbz:20,color:'#00a3e0'},{dbz:30,color:'#005588'},{dbz:40,color:'#ffaa00'},{dbz:50,color:'#c10000'},{dbz:60,color:'#ff62ff'}];
const LIGHTNING_AGES=[{label:'0–5 min',color:'#ff3b76'},{label:'5–15',color:'#ff8a20'},{label:'15–30',color:'#ffd24a'},{label:'30–60',color:'#9eb8dc'}];

function clamp(value:number,min:number,max:number){return Math.max(min,Math.min(max,value))}
function storedSettings():CompositeSettings{const defaults:CompositeSettings={basemap:'positron',showRadar:true,highResolution:false,showSatellite:false,showLightning:false,radarOpacity:76,satelliteOpacity:58,lightningOpacity:92};try{const raw=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}') as Partial<CompositeSettings>,basemap=raw.basemap&&BASEMAPS[raw.basemap]?raw.basemap:defaults.basemap;return{basemap,showRadar:typeof raw.showRadar==='boolean'?raw.showRadar:defaults.showRadar,highResolution:typeof raw.highResolution==='boolean'?raw.highResolution:defaults.highResolution,showSatellite:typeof raw.showSatellite==='boolean'?raw.showSatellite:defaults.showSatellite,showLightning:typeof raw.showLightning==='boolean'?raw.showLightning:defaults.showLightning,radarOpacity:clamp(Number(raw.radarOpacity)||defaults.radarOpacity,15,100),satelliteOpacity:clamp(Number(raw.satelliteOpacity)||defaults.satelliteOpacity,15,100),lightningOpacity:clamp(Number(raw.lightningOpacity)||defaults.lightningOpacity,20,100)}}catch{return defaults}}
function formatInZone(value:number,timeZone:string|undefined,options:Intl.DateTimeFormatOptions){try{return new Intl.DateTimeFormat('de-DE',{...options,timeZone:timeZone||undefined}).format(new Date(value))}catch{return new Intl.DateTimeFormat('de-DE',options).format(new Date(value))}}
function Title({eye,title}:{eye:string;title:string}){return <header className="title"><div><span>{eye}</span><h2>{title}</h2></div></header>}
function MoveMap({lat,lon,locateRequest}:{lat:number;lon:number;locateRequest:number}){const map=useMap();useEffect(()=>{map.setView([lat,lon],7,{animate:true})},[lat,lon,map]);useEffect(()=>{if(locateRequest>0)map.flyTo([lat,lon],map.getZoom(),{animate:true,duration:.65})},[locateRequest,lat,lon,map]);return null}
function LayerSwitch({active,disabled=false,title,onClick,icon,label,detail}:{active:boolean;disabled?:boolean;title:string;onClick:()=>void;icon:ReactNode;label:string;detail?:string}){return <button type="button" className={`composite-switch${active?' active':''}`} disabled={disabled} aria-pressed={active} title={title} onClick={onClick}>{icon}<span><b>{label}</b>{detail&&<small>{detail}</small>}</span></button>}
function rateColour(rate:number){if(rate>=50)return'#b83fc8';if(rate>=20)return'#e34b4b';if(rate>=10)return'#f59b3d';if(rate>=5)return'#f0d447';if(rate>=2.5)return'#43c879';if(rate>=1)return'#2f91e3';if(rate>=.5)return'#72c9ff';return'#d9f3ff'}
function nearestFrame<T extends {time:number}>(frames:T[],target:number,maxDifference=12*60000){let best:T|undefined,bestDelta=Infinity;for(const frame of frames){const delta=Math.abs(frame.time-target);if(delta<bestDelta){best=frame;bestDelta=delta}}return bestDelta<=maxDifference?best:undefined}
function nearestProductIso(times:string[],target:number,maxDifference=18*60000){let best='',delta=Infinity;for(const value of times){const stamp=Date.parse(value),difference=Math.abs(stamp-target);if(Number.isFinite(stamp)&&difference<delta){best=value;delta=difference}}return delta<=maxDifference?best:''}
function compactFrames(frames:RadarFrame[],anchor:number){const min=anchor-65*60000,max=anchor+65*60000,usable=[...new Map(frames.filter(frame=>frame.time>=min&&frame.time<=max).sort((a,b)=>a.time-b.time).map(frame=>[frame.time,frame])).values()];if(usable.length<=15)return usable;const selected=usable.filter((frame,index)=>index===0||index===usable.length-1||Math.abs(frame.time-anchor)<180000||index%2===0);return selected.slice(0,15)}
function lightningStyle(point:LightningPoint,target:number,fallbackTime?:string){const stamp=Date.parse(point.observedAt||fallbackTime||''),age=Number.isFinite(stamp)?Math.max(0,(target-stamp)/60000):0,color=age<=5?'#ff3b76':age<=15?'#ff8a20':age<=30?'#ffd24a':'#9eb8dc',ageOpacity=clamp(1-age/72,.16,.98),strength=clamp(Math.abs(Number(point.intensity))||Number(point.count)||1,1,80),radius=5+Math.log2(strength+1)*1.7,weight=clamp(1.25+Math.log10(strength+1),1.3,3.2);return{age,color,opacity:ageOpacity,radius,weight}}
function formatAge(age:number){return age<1?'gerade eben':`${Math.round(age)} min alt`}
function RadarScale({source,highResolution}:{source:CompositeSource;highResolution:boolean}){if((source==='opera'||source==='dwd')&&!highResolution)return <div className="compact-scale rate"><span>0,1</span><i>{DWD_RATE_LEGEND.map(item=><b key={item.value} style={{background:item.color}}/>)}</i><span>50＋ mm/h</span></div>;return <div className="compact-scale dbz"><span>10</span><i>{RAINVIEWER_LEGEND.map(item=><b key={item.dbz} style={{background:item.color}}/>)}</i><span>60＋ dBZ</span></div>}
function CompositeLegend({source,showRadar,highResolution,showSatellite,satelliteName,showLightning,lightningProvider,vectorLightning,future,minutesAhead,pxSite}:{source:CompositeSource;showRadar:boolean;highResolution:boolean;showSatellite:boolean;satelliteName:string;showLightning:boolean;lightningProvider:string;vectorLightning:boolean;future:boolean;minutesAhead:number;pxSite?:string}){const provider=highResolution?'DWD PX250':source==='dwd'?'DWD-RV':source==='opera'?'EUMETNET OPERA':source==='rainviewer'?'RainViewer':'kein Radar';return <div className="radarlegend compact"><div className="radarlegend-head"><strong>{future?`+${minutesAhead} min`:'Aktive Layer'}</strong><span>{showRadar?provider:'Komposit'}</span></div><div className="legend-active-chips">{showRadar&&<em>Niederschlag{pxSite?` · ${pxSite}`:''}</em>}{showSatellite&&<em>{satelliteName}</em>}{showLightning&&<em>{lightningProvider}</em>}{!showRadar&&!showSatellite&&!showLightning&&<em>nur Kartenbasis</em>}</div>{showRadar&&(highResolution||source!=='model')&&<RadarScale source={source} highResolution={highResolution}/>} {showLightning&&vectorLightning&&<div className="lightning-age-legend ring-legend">{LIGHTNING_AGES.map(item=><span key={item.label}><i style={{borderColor:item.color}}/>{item.label}</span>)}</div>}</div>}

export default function RadarPanel({lat,lon,timezone,analysis,isDay=true}:{lat:number;lon:number;timezone?:string;analysis?:RadarNowcast|null;isDay?:boolean}){
 const initial=useMemo(storedSettings,[]),source:CompositeSource=analysis?.coverage===false?'model':analysis?.source??'model';
 const[radarFrames,setRadarFrames]=useState<RadarFrame[]>([]),[host,setHost]=useState(''),[index,setIndex]=useState(0),[latestObserved,setLatestObserved]=useState(0),[playing,setPlaying]=useState(false),[locateRequest,setLocateRequest]=useState(0);
 const[showRadar,setShowRadar]=useState(initial.showRadar),[highResolution,setHighResolution]=useState(initial.highResolution),[showSatellite,setShowSatellite]=useState(initial.showSatellite),[showLightning,setShowLightning]=useState(initial.showLightning),[satelliteFallback,setSatelliteFallback]=useState(false);
 const[radarOpacity,setRadarOpacity]=useState(initial.radarOpacity),[satelliteOpacity,setSatelliteOpacity]=useState(initial.satelliteOpacity),[lightningOpacity,setLightningOpacity]=useState(initial.lightningOpacity),[basemap,setBasemap]=useState<BasemapId>(initial.basemap);
 const[pxMeta,setPxMeta]=useState<Px250Meta|null>(null),[pxLoading,setPxLoading]=useState(false),[pxStatus,setPxStatus]=useState<PxStatus>('idle'),[pxMessage,setPxMessage]=useState('');
 const[operaFrames,setOperaFrames]=useState<OperaGridFrame[]>([]),[operaError,setOperaError]=useState(''),[lightningData,setLightningData]=useState<LightningPointResponse>({points:[]}),[lightningError,setLightningError]=useState(''),[productTimes,setProductTimes]=useState<CompositeProductTimes>({satelliteDay:[],satelliteIr:[],mtgLightning:[],dwdLightning:[]});
 const previousTimeline=useRef<number>(0),dwdLightning=lat>=47&&lat<=55.5&&lon>=5&&lon<=16,mtgLightning=lat>=-60&&lat<=72&&lon>=-75&&lon<=80;

 useEffect(()=>{try{localStorage.setItem(SETTINGS_KEY,JSON.stringify({basemap,showRadar,highResolution,showSatellite,showLightning,radarOpacity,satelliteOpacity,lightningOpacity} satisfies CompositeSettings))}catch{}},[basemap,showRadar,highResolution,showSatellite,showLightning,radarOpacity,satelliteOpacity,lightningOpacity]);
 useEffect(()=>{let alive=true;setPlaying(false);setHost('');if(source==='dwd'){const supplied=(Array.isArray(analysis?.timeline)?analysis.timeline:[]).map(value=>Math.floor(new Date(value).getTime()/1000)).filter(Number.isFinite).sort((a,b)=>a-b),observedAt=analysis?.observedAt?Math.floor(new Date(analysis.observedAt).getTime()/1000):0,anchor=observedAt||Math.floor(Date.now()/300000)*300,items=compactFrames((supplied.length?supplied:Array.from({length:25},(_,i)=>anchor+(i-12)*300)).map(time=>({time,future:time>anchor})),anchor);setRadarFrames(items);setLatestObserved(anchor);return()=>{alive=false}}
  if(source==='rainviewer'){fetch('https://api.rainviewer.com/public/weather-maps.json',{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error(`RainViewer HTTP ${response.status}`);return response.json()}).then((data:RadarResponse)=>{if(!alive)return;const past=data.radar?.past??[],last=past.at(-1)?.time??0,nowcast=(data.radar?.nowcast??[]).map(item=>({...item,future:true})),items=compactFrames([...past,...nowcast],last);setHost(data.host);setRadarFrames(items);setLatestObserved(last)}).catch(()=>{if(alive){setRadarFrames([]);setHost('')}});return()=>{alive=false}}
  setRadarFrames([]);setLatestObserved(analysis?.observedAt?Math.floor(Date.parse(analysis.observedAt)/1000):Math.floor(Date.now()/300000)*300);return()=>{alive=false}
 },[lat,lon,source,analysis?.observedAt,analysis?.timeline?.join('|')]);
 useEffect(()=>{if(source!=='opera'){setOperaFrames([]);setOperaError('');return}const controller=new AbortController(),load=()=>loadOperaGrid(lat,lon,controller.signal).then(data=>{setOperaFrames(data.frames?.length?data.frames:[{time:data.observedAt||new Date().toISOString(),points:data.points??[]}]);setOperaError('')}).catch(error=>{if(!controller.signal.aborted){setOperaFrames([]);setOperaError(error instanceof Error?error.message:String(error))}});void load();const timer=window.setInterval(load,300000);return()=>{controller.abort();window.clearInterval(timer)}},[lat,lon,source]);
 useEffect(()=>{if(!showLightning){setLightningData({points:[]});setLightningError('');return}const controller=new AbortController(),load=()=>loadLightningPoints(lat,lon,controller.signal).then(data=>{setLightningData(data);setLightningError('')}).catch(error=>{if(!controller.signal.aborted){setLightningData({points:[],fallback:mtgLightning?'mtg-li':'none'});setLightningError(error instanceof Error?error.message:String(error))}});void load();const timer=window.setInterval(load,120000);return()=>{controller.abort();window.clearInterval(timer)}},[lat,lon,showLightning,mtgLightning]);
 useEffect(()=>{if(!showSatellite&&!showLightning){setProductTimes({satelliteDay:[],satelliteIr:[],mtgLightning:[],dwdLightning:[]});return}const controller=new AbortController(),load=()=>loadCompositeTimes(lat,lon,controller.signal).then(data=>setProductTimes(data)).catch(()=>{if(!controller.signal.aborted)setProductTimes({satelliteDay:[],satelliteIr:[],mtgLightning:[],dwdLightning:[]})});void load();const timer=window.setInterval(load,300000);return()=>{controller.abort();window.clearInterval(timer)}},[lat,lon,showSatellite,showLightning]);
 useEffect(()=>{let alive=true;setPxStatus('idle');setPxMessage('');const load=()=>{setPxLoading(true);loadPx250Metadata(lat,lon).then(data=>{if(!alive)return;setPxMeta(data);if(!data.available)setHighResolution(false)}).catch(error=>{if(alive){setPxMeta({available:false,nativeResolutionM:250,reason:error instanceof Error?error.message:String(error)});setHighResolution(false)}}).finally(()=>{if(alive)setPxLoading(false)})};void load();const timer=window.setInterval(load,300000);return()=>{alive=false;window.clearInterval(timer)}},[lat,lon]);
 useEffect(()=>{setSatelliteFallback(false)},[isDay,lat,lon]);

 const operaTimeline=useMemo(()=>operaFrames.map(frame=>({time:Math.floor(Date.parse(frame.time)/1000),future:false})).filter(frame=>Number.isFinite(frame.time)),[operaFrames]);
 const satelliteTimeline=useMemo(()=>((isDay&&!satelliteFallback?productTimes.satelliteDay:productTimes.satelliteIr)||[]).map(value=>({time:Math.floor(Date.parse(value)/1000),future:false})).filter(frame=>Number.isFinite(frame.time)),[isDay,satelliteFallback,productTimes.satelliteDay,productTimes.satelliteIr]);
 const lightningTimeline=useMemo(()=>{const raster=(dwdLightning?productTimes.dwdLightning:productTimes.mtgLightning)||[],pointBins=(lightningData.points??[]).map(point=>Date.parse(point.observedAt||lightningData.observedAt||'')).filter(Number.isFinite).map(stamp=>Math.floor(stamp/300000)*300000),values=[...new Set([...raster.map(Date.parse),...pointBins])].filter(Number.isFinite).sort((a,b)=>a-b);return values.map(value=>({time:Math.floor(value/1000),future:false}))},[dwdLightning,productTimes.dwdLightning,productTimes.mtgLightning,lightningData.points,lightningData.observedAt]);
 const anchorSeconds=latestObserved||Math.floor(Date.now()/300000)*300;
 const frames=useMemo(()=>{let candidates:RadarFrame[]=[];if(showRadar&&!highResolution){if(source==='dwd'||source==='rainviewer')candidates=radarFrames;else if(source==='opera')candidates=operaTimeline}if(!candidates.length){const product=[...(showSatellite?satelliteTimeline:[]),...(showLightning?lightningTimeline:[])];candidates=[...new Map(product.sort((a,b)=>a.time-b.time).map(frame=>[frame.time,frame])).values()]}if(!candidates.length&&(showSatellite||showLightning))candidates=[{time:anchorSeconds,future:false}];if(!candidates.length&&highResolution&&pxMeta?.observedAt)candidates=[{time:Math.floor(Date.parse(pxMeta.observedAt)/1000),future:false}];return candidates},[showRadar,highResolution,source,radarFrames,operaTimeline,showSatellite,showLightning,satelliteTimeline,lightningTimeline,dwdLightning,mtgLightning,anchorSeconds,pxMeta?.observedAt]);
 useEffect(()=>{const target=previousTimeline.current||anchorSeconds,indexForTarget=frames.reduce((best,frame,i)=>Math.abs(frame.time-target)<Math.abs(frames[best]?.time-target)?i:best,0);setIndex(frames.length?clamp(indexForTarget,0,frames.length-1):0)},[frames.map(frame=>frame.time).join('|'),anchorSeconds]);
 const canAnimate=frames.length>1&&(showSatellite||showLightning||showRadar&&!highResolution);
 useEffect(()=>{if(!playing||!canAnimate)return;const timer=window.setInterval(()=>setIndex(current=>current>=frames.length-1?0:current+1),950);return()=>window.clearInterval(timer)},[playing,canAnimate,frames.length]);

 const frame=frames[index],targetSeconds=frame?.time||anchorSeconds,targetMs=targetSeconds*1000;previousTimeline.current=targetSeconds;
 const radarFrame=nearestFrame(radarFrames,targetSeconds,source==='rainviewer'?7*60000:6*60000),operaFrame=operaFrames.reduce<OperaGridFrame|undefined>((best,item)=>!best||Math.abs(Date.parse(item.time)-targetMs)<Math.abs(Date.parse(best.time)-targetMs)?item:best,undefined),operaPoints:OperaGridPoint[]=operaFrame&&Math.abs(Date.parse(operaFrame.time)-targetMs)<=9*60000?operaFrame.points:[];
 const future=targetSeconds>anchorSeconds+90,minutesAhead=future?Math.max(0,Math.round((targetSeconds-anchorSeconds)/60)):0,dwdLayer=analysis?.source==='dwd'&&analysis.radarLayer?analysis.radarLayer:'dwd:Niederschlagsradar',rainViewerUrl=radarFrame?.path&&host?`${host}${radarFrame.path}/256/{z}/{x}/{y}/2/1_1.png`:'',radarTimeIso=new Date((radarFrame?.time||targetSeconds)*1000).toISOString();
 const satelliteDay=isDay&&!satelliteFallback,satelliteLayer=satelliteDay?'mtg_fd:vis06_hrfi':'mtg_fd:ir105_hrfi',satelliteName=satelliteDay?'HRV/HRFI VIS 0,6':'IR 10,5',satelliteAvailableTimes=satelliteDay?productTimes.satelliteDay:productTimes.satelliteIr,satelliteTimeIso=satelliteAvailableTimes.length?nearestProductIso(satelliteAvailableTimes,targetMs):undefined,lightningAvailableTimes=dwdLightning?productTimes.dwdLightning:productTimes.mtgLightning,lightningTimeIso=lightningAvailableTimes.length?nearestProductIso(lightningAvailableTimes,targetMs):undefined;
 const pointProvider=Boolean(lightningData.points?.length),licensedGlobal=Boolean(lightningData.commercial&&lightningData.provider),lightningProvider=lightningData.provider||(!dwdLightning&&mtgLightning?'EUMETSAT MTG-LI':'keine freie Punktquelle'),lightningResolution=lightningData.nativeResolutionKm?`${lightningData.nativeResolutionKm} km`:pointProvider?'Punktortung':dwdLightning?'1 km':mtgLightning?'2 km':'optional',lightningName=pointProvider?`${lightningProvider} · ${lightningResolution}`:licensedGlobal?`${lightningProvider} · keine Aktivität im aktuellen Zeitfenster`:dwdLightning?'DWD Blitzdichte 1 km':mtgLightning?'EUMETSAT MTG-LI AFA 2 km':'keine frei nutzbare Echtzeitquelle';
 const visibleLightning=(lightningData.points??[]).filter(point=>{const stamp=Date.parse(point.observedAt||lightningData.observedAt||'');if(!Number.isFinite(stamp))return Math.abs(targetMs-Date.now())<8*60000;const age=(targetMs-stamp)/60000;return age>=-1&&age<=60});
 const vectorLightning=visibleLightning.length>0,pxObserved=pxMeta?.observedAt?Date.parse(pxMeta.observedAt):0,showPxAtTime=showRadar&&highResolution&&Boolean(pxMeta?.available)&&(!frames.length||Math.abs(targetMs-pxObserved)<=8*60000),currentBasemap=BASEMAPS[basemap]??BASEMAPS.positron;
 const timelineStart=frames.length?Math.round((frames[0].time-anchorSeconds)/60):0,timelineEnd=frames.length?Math.round((frames.at(-1)!.time-anchorSeconds)/60):0,timelineSpan=`${timelineStart<0?'−'+Math.abs(timelineStart):'+'+timelineStart} bis ${timelineEnd<0?'−'+Math.abs(timelineEnd):'+'+timelineEnd} min`;
 const onPxStatus=useCallback((status:PxStatus,message='')=>{setPxStatus(status);setPxMessage(message)},[]),step=(amount:number)=>{setPlaying(false);setIndex(current=>clamp(current+amount,0,Math.max(0,frames.length-1)))},togglePlay=()=>{if(!canAnimate)return;if(!playing&&index>=frames.length-1)setIndex(0);setPlaying(value=>!value)},toggleRadar=()=>setShowRadar(value=>!value),toggleHighRes=()=>{if(!pxMeta?.available)return;setShowRadar(true);setPlaying(false);setHighResolution(value=>!value)};
 const pxDetail=pxLoading?'Prüfung …':pxMeta?.available?`${pxMeta.siteName??pxMeta.site?.toUpperCase()} · 250 m`:'nicht verfügbar',radarDetail=source==='dwd'?'DWD · 1 km':source==='opera'?'OPERA · 2 km':source==='rainviewer'?'RainViewer · regional':'nicht verfügbar';
 const sourceText=useMemo(()=>showRadar?(highResolution?'DWD-PX250 über MID-Worker; 250-m-Standortradar, zeitlich aktueller Einzelstand':source==='dwd'?'DWD-RV; 1-km-Komposit und Nowcast, Kartenfilm maximal ±1 Stunde':source==='opera'?'EUMETNET OPERA/ORD; aktuelle europäische Komposite mit 2 km Produktauflösung, historischer Film bis 60 Minuten':source==='rainviewer'?'RainViewer als weltweiter Radar-Fallback; Film nach verfügbarer lokaler Kachelhistorie':'keine verwertbare Radarkarte'):'Radar ausgeblendet',[showRadar,highResolution,source]);

 return <section className="card composite-card"><Title eye="Radar · Satellit · Blitze" title="Kompositbild"/>
  <div className="composite-layer-switches" aria-label="Komposit-Layer">
   <LayerSwitch active={showRadar&&!highResolution} title="Standard-Niederschlagsradar ein- oder ausblenden" onClick={toggleRadar} icon={<Droplets size={18}/>} label="Niederschlag" detail={radarDetail}/>
   <LayerSwitch active={highResolution} disabled={pxLoading||!pxMeta?.available} title={pxMeta?.reason||'DWD-PX250-Reflektivität mit 250 m Rasterweite über den MID-Worker'} onClick={toggleHighRes} icon={<RadioTower size={18}/>} label="Radar 250 m" detail={pxDetail}/>
   <LayerSwitch active={showSatellite} title={`${isDay?'Hochaufgelöster sichtbarer MTG-FCI-Kanal':'Hochaufgelöster infraroter MTG-FCI-Kanal'} ein- oder ausblenden`} onClick={()=>setShowSatellite(value=>!value)} icon={isDay?<CloudSun size={18}/>:<Satellite size={18}/>} label={`Satellit ${isDay?'HRV':'IR'}`} detail={satelliteFallback?'IR-Fallback':satelliteName}/>
   <LayerSwitch active={showLightning} title="Zeitcodierte Blitzaktivität ein- oder ausblenden; außerhalb der freien Abdeckung wird ein konfigurierter globaler Provider geprüft" onClick={()=>setShowLightning(value=>!value)} icon={<Zap size={18}/>} label="Echtzeitblitze" detail={pointProvider?`${lightningResolution} · Ringe`:licensedGlobal?`${lightningResolution} · aktuell ruhig`:dwdLightning?'DWD · 1 km':mtgLightning?'MTG-LI · 2 km':'global optional'}/>
  </div>
  <div className="radarmap">
   <div className="composite-basemap-control"><Layers3 size={14}/><label><span>Kartenbasis</span><select value={basemap} onChange={event=>setBasemap(event.target.value as BasemapId)}>{(Object.entries(BASEMAPS) as [BasemapId,(typeof BASEMAPS)[BasemapId]][]).map(([id,item])=><option key={id} value={id}>{item.label} · {item.detail}</option>)}</select></label></div>
   <button type="button" className="composite-locate-button" onClick={()=>setLocateRequest(value=>value+1)} title="Karte wieder auf den gewählten Standort zentrieren" aria-label="Karte auf Standort zentrieren"><LocateFixed size={16}/></button>
   <MapContainer center={[lat,lon]} zoom={7} className="leafletmap" scrollWheelZoom={false} fadeAnimation zoomAnimation><MoveMap lat={lat} lon={lon} locateRequest={locateRequest}/><TileLayer key={basemap} attribution={currentBasemap.attribution} url={currentBasemap.url} zIndex={100}/>
    {showSatellite&&(!satelliteAvailableTimes.length||Boolean(satelliteTimeIso))&&<WMSTileLayer key={`${satelliteLayer}:${satelliteTimeIso||'latest'}`} url="https://view.eumetsat.int/geoserver/wms" opacity={satelliteOpacity/100} zIndex={220} eventHandlers={{tileerror:()=>{if(satelliteDay)setSatelliteFallback(true)}}} params={({layers:satelliteLayer,styles:'',format:'image/png',transparent:true,version:'1.3.0',time:satelliteTimeIso||undefined} as any)} attribution="Satellit &copy; EUMETSAT"/>}
    {showRadar&&!highResolution&&source==='dwd'&&radarFrame&&<WMSTileLayer key={`${dwdLayer}:${radarTimeIso}`} url="https://maps.dwd.de/geoserver/wms" opacity={radarOpacity/100} zIndex={360} params={({layers:dwdLayer,styles:'',format:'image/png',transparent:true,version:'1.3.0',time:radarTimeIso} as any)} attribution="Radar und Nowcast &copy; DWD"/>}
    {showRadar&&!highResolution&&source==='opera'&&operaPoints.map((point,pointIndex)=><CircleMarker key={`${point.lat}:${point.lon}:${point.observedAt??pointIndex}`} center={[point.lat,point.lon]} radius={Math.max(4,Math.min(15,4+Math.sqrt(Math.max(0,point.rate))*2))} pathOptions={{color:rateColour(point.rate),weight:1,fillColor:rateColour(point.rate),fillOpacity:Math.max(.12,radarOpacity/120)}}><Popup><strong>EUMETNET OPERA</strong><br/>{point.rate.toLocaleString('de-DE',{maximumFractionDigits:1})} mm/h{point.observedAt&&<><br/>{formatInZone(Date.parse(point.observedAt),timezone,{hour:'2-digit',minute:'2-digit'})}</>}</Popup></CircleMarker>)}
    {showRadar&&!highResolution&&source==='rainviewer'&&rainViewerUrl&&<TileLayer key={rainViewerUrl} attribution="Radar &copy; RainViewer" url={rainViewerUrl} opacity={radarOpacity/100} zIndex={360}/>} 
    {showPxAtTime&&pxMeta?.available&&<Suspense fallback={null}><LazyPx250Overlay meta={pxMeta} opacity={radarOpacity/100} onStatus={onPxStatus}/></Suspense>}
    {showLightning&&vectorLightning&&visibleLightning.map(point=>{const style=lightningStyle(point,targetMs,lightningData.observedAt);return <CircleMarker key={point.id} center={[point.lat,point.lon]} radius={style.radius} pathOptions={{color:style.color,weight:style.weight,opacity:style.opacity*lightningOpacity/100,fillOpacity:0,dashArray:style.age>30?'3 3':undefined}}><Popup><strong>{lightningProvider}</strong><br/>{formatAge(style.age)}{point.pulseType&&<><br/>{point.pulseType.toUpperCase()}</>}{point.observedAt&&<><br/>{formatInZone(Date.parse(point.observedAt),timezone,{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</>}</Popup></CircleMarker>})}
    {showLightning&&!pointProvider&&dwdLightning&&(!lightningAvailableTimes.length||Boolean(lightningTimeIso))&&<WMSTileLayer key={`dwd-lightning:${lightningTimeIso||'latest'}`} url="https://maps.dwd.de/geoserver/wms" opacity={lightningOpacity/100} zIndex={470} params={({layers:'dwd:Blitzdichte',styles:'',format:'image/png',transparent:true,version:'1.3.0',time:lightningTimeIso||undefined} as any)} attribution="Blitzdichte &copy; DWD"/>}
    {showLightning&&!pointProvider&&!dwdLightning&&mtgLightning&&(!lightningAvailableTimes.length||Boolean(lightningTimeIso))&&<WMSTileLayer key={`mtg-li:${lightningTimeIso||'latest'}`} url="https://view.eumetsat.int/geoserver/wms" opacity={lightningOpacity/100} zIndex={470} params={({layers:'mtg_fd:li_afa',styles:'',format:'image/png',transparent:true,version:'1.3.0',time:lightningTimeIso||undefined} as any)} attribution="Lightning Imager &copy; EUMETSAT"/>}
    <CircleMarker center={[lat,lon]} radius={7} pathOptions={{color:'#fff',weight:2,fillColor:'#1f8cff',fillOpacity:0.95}}><Popup>Gewählter Standort</Popup></CircleMarker>
   </MapContainer>
   <CompositeLegend source={source} showRadar={showRadar} highResolution={highResolution} showSatellite={showSatellite} satelliteName={satelliteName} showLightning={showLightning} lightningProvider={lightningProvider} vectorLightning={vectorLightning} future={future} minutesAhead={minutesAhead} pxSite={highResolution?pxMeta?.siteName:undefined}/>
  </div>
  <div className="radarcontrols composite-controls">
   <div className="radar-playback-buttons"><button className="secondary" disabled={!canAnimate||index<=0} onClick={()=>step(-1)} title="Vorheriger Kompositzeitschritt" aria-label="Vorheriger Kompositzeitschritt"><SkipBack size={17}/></button><button className="secondary play" disabled={!canAnimate} onClick={togglePlay} title={playing?'Animation pausieren':'Kompositfilm abspielen'} aria-label={playing?'Animation pausieren':'Kompositfilm abspielen'}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><button className="secondary" disabled={!canAnimate||index>=frames.length-1} onClick={()=>step(1)} title="Nächster Kompositzeitschritt" aria-label="Nächster Kompositzeitschritt"><SkipForward size={17}/></button></div>
   <div className="range timeline"><small>{canAnimate?`Kompositfilm ${frames.length} Schritte · ${timelineSpan}`:'Aktiver Layer stellt nur einen aktuellen Einzelstand bereit'}</small><input type="range" min={0} max={Math.max(0,frames.length-1)} value={index} disabled={!canAnimate} onChange={event=>{setPlaying(false);setIndex(Number(event.target.value))}}/></div>
   <time className={future?'future':''}>{targetMs?formatInZone(targetMs,timezone,{hour:'2-digit',minute:'2-digit'}):'–:–'}{future?' Prognose':''}</time>
   <div className="layer-opacity-controls" aria-label="Deckkraft je Layer">{showRadar&&<label><span>Niederschlag</span><b>{radarOpacity}%</b><input type="range" min={15} max={100} value={radarOpacity} onChange={event=>setRadarOpacity(Number(event.target.value))}/></label>}{showSatellite&&<label><span>Satellit</span><b>{satelliteOpacity}%</b><input type="range" min={15} max={100} value={satelliteOpacity} onChange={event=>setSatelliteOpacity(Number(event.target.value))}/></label>}{showLightning&&<label><span>Blitze</span><b>{lightningOpacity}%</b><input type="range" min={20} max={100} value={lightningOpacity} onChange={event=>setLightningOpacity(Number(event.target.value))}/></label>}</div>
  </div>
  {highResolution&&pxStatus==='loading'&&<small className="source composite-source-note"><RadioTower size={12}/>DWD-PX250-HDF5-Daten werden über den Worker geladen und lokal gerendert …</small>}
  {highResolution&&pxStatus==='error'&&<small className="source warning">PX250 konnte nicht dargestellt werden: {pxMessage}</small>}
  {highResolution&&!showPxAtTime&&canAnimate&&<small className="source warning">PX250 ist nur am aktuellen Produktzeitpunkt sichtbar; beim zeitlichen Blättern bleibt der Layer außerhalb eines ±8-Minuten-Fensters ausgeblendet.</small>}
  {showRadar&&source==='opera'&&operaError&&<small className="source warning">OPERA-Kartenraster konnte nicht geladen werden: {operaError}</small>}
  {showLightning&&lightningError&&<small className="source warning">Blitzpunkte konnten nicht geladen werden; sofern der Ort abgedeckt ist, wird das DWD- beziehungsweise MTG-LI-Raster verwendet.</small>}
  {showLightning&&!dwdLightning&&!mtgLightning&&!pointProvider&&!licensedGlobal&&<small className="source warning">Für diesen Ort ist ohne lizenzierte Xweather-/GLD360-Zugangsdaten keine frei nutzbare Echtzeit-Blitzquelle verfügbar.</small>}
  <small className="source">Kompositquellen: {sourceText}{showSatellite?` · EUMETSAT MTG-FCI ${satelliteName}`:''}{showLightning?` · ${lightningName}`:''}. Layerauswahl, Kartenbasis und Deckkräfte werden lokal gespeichert. Zeitliche Animation verwendet nur verfügbare Produktzeiten und höchstens rund zwei Stunden Kartenfenster; fehlt eine Zeitdimension, zeigt MID ausschließlich den aktuellen Standardstand. Kartenbasis: {currentBasemap.label}. Keine amtliche Warnung.</small>
 </section>
}
