import type {RadarNowcast,RadarNowcastFrame} from './weather';
import type {DwdRsCalibration} from './DwdRsSource';
import type {HxBoundaryCheck} from './HxRadarPointSource';

export type RadarRainStationCalibration={available:boolean;name?:string;observedAt?:string;distanceKm?:number;amount10m?:number;provider?:string;error?:string};

function clamp(value:number,min:number,max:number){return Math.max(min,Math.min(max,value))}
function numeric(value:unknown,fallback=0){const result=Number(value);return Number.isFinite(result)?result:fallback}
function observedEpoch(radar:RadarNowcast,now=Date.now()){const parsed=Date.parse(radar.observedAt||'');return Number.isFinite(parsed)?parsed:now}
function frameEpoch(frame:RadarNowcastFrame){return Date.parse(frame.time)}
function frameStepMinutes(frames:RadarNowcastFrame[],index:number){const current=frameEpoch(frames[index]),nextFrame=frames[index+1],next=nextFrame?frameEpoch(nextFrame):Number.NaN;return Number.isFinite(current)&&Number.isFinite(next)?clamp((next-current)/60000,2.5,10):5}
function rawFrameAmount(frames:RadarNowcastFrame[],index:number){const existing=Number(frames[index].amountMm);if(Number.isFinite(existing)&&existing>=0)return existing;return Math.max(0,numeric(frames[index].rate))*frameStepMinutes(frames,index)/60}
function quantile(values:number[],p:number){if(!values.length)return 0;const sorted=[...values].sort((a,b)=>a-b),position=(sorted.length-1)*clamp(p,0,1),lower=Math.floor(position),upper=Math.ceil(position);if(lower===upper)return sorted[lower];const weight=position-lower;return sorted[lower]*(1-weight)+sorted[upper]*weight}
function growthFactor(radar:RadarNowcast,leadMinutes:number){const rate=clamp(numeric(radar.growthRatePerHour),-.9,.45),leadHours=Math.max(0,leadMinutes)/60;if(Math.abs(rate)<.02)return 1;const raw=Math.exp(rate*leadHours*.62);return rate>0?clamp(raw,1,1.14):clamp(raw,.52,1)}

export function needsHxBoundaryCheck(radar:RadarNowcast|null|undefined){
 if(!radar||radar.source!=='dwd'||radar.coverage===false)return false;
 if(radar.rateUncertain)return true;
 const siteThreshold=Math.max(.02,numeric(radar.siteEchoThreshold,.05)),observed=observedEpoch(radar),frames=radar.nowcastSeries??[];
 return frames.some(frame=>{const epoch=frameEpoch(frame),lead=(epoch-observed)/60000;if(!Number.isFinite(lead)||lead<-10||lead>55)return false;const support=Number(frame.siteSupport),nearest=Number(frame.nearestWetKm),rate=numeric(frame.rate);return rate>=siteThreshold*.65&&rate<=3&&(Number.isFinite(support)&&support>0&&support<.62||Number.isFinite(nearest)&&nearest<=3.2)});
}

export function applyRsAmountCalibration(radar:RadarNowcast,rs:DwdRsCalibration|undefined|null):RadarNowcast{
 const frames=[...(radar.nowcastSeries??[])].sort((a,b)=>frameEpoch(a)-frameEpoch(b));if(!frames.length)return radar;
 const base=observedEpoch(radar),anchors=new Map((rs?.available?rs.anchors:[]).map(anchor=>[anchor.leadMinutes,anchor])),windows:Array<[number,number,60|120]>=[[0,60,60],[60,120,120]],futureIndexes=frames.map((frame,index)=>({frame,index,lead:(frameEpoch(frame)-base)/60000})).filter(row=>row.frame.future&&Number.isFinite(row.lead)&&row.lead>0&&row.lead<=122);
 const amounts=new Map<number,{amount:number;raw:number;source:string;confidence:'high'|'medium'|'low';growth:number}>();
 for(const row of futureIndexes){const raw=rawFrameAmount(frames,row.index),growth=growthFactor(radar,row.lead),shaped=raw*growth;amounts.set(row.index,{amount:shaped,raw,source:'DWD RV · Wachstum/Zerfall',confidence:radar.growthConfidence==='high'?'medium':'low',growth})}
 let usedRs=false;const anchorDiagnostics:{leadMinutes:number;targetMm:number;rawMm:number;scale:number}[]=[];
 for(const [start,end,anchorLead] of windows){const rows=futureIndexes.filter(row=>row.lead>start+.1&&row.lead<=end+2),anchor=anchors.get(anchorLead);if(!rows.length||!anchor)continue;const shaped=rows.reduce((sum,row)=>sum+(amounts.get(row.index)?.amount??0),0),raw=rows.reduce((sum,row)=>sum+(amounts.get(row.index)?.raw??0),0),target=Math.max(0,numeric(anchor.amountMm));if(shaped<=.002){anchorDiagnostics.push({leadMinutes:anchorLead,targetMm:target,rawMm:raw,scale:1});continue}const directScale=target/shaped,scale=directScale>1?Math.min(1.15,directScale):Math.max(0,directScale);for(const row of rows){const item=amounts.get(row.index);if(!item)continue;amounts.set(row.index,{...item,amount:item.amount*scale,source:'DWD RS-kalibriertes RV',confidence:'high'})}usedRs=true;anchorDiagnostics.push({leadMinutes:anchorLead,targetMm:target,rawMm:raw,scale:Number(scale.toFixed(3))})}
 const nextFrames=frames.map((frame,index)=>{const calibrated=amounts.get(index);if(!calibrated)return frame;return{...frame,rawAmountMm:Number(calibrated.raw.toFixed(4)),amountMm:Number(calibrated.amount.toFixed(4)),amountSource:calibrated.source,amountConfidence:calibrated.confidence,growthFactor:Number(calibrated.growth.toFixed(3))}}),future=nextFrames.filter(frame=>frame.future&&frameEpoch(frame)>base&&frameEpoch(frame)<=base+122*60000),forecastAmount60=future.filter(frame=>frameEpoch(frame)<=base+62*60000).reduce((sum,frame)=>sum+Math.max(0,numeric(frame.amountMm)),0),forecastAmount120=future.reduce((sum,frame)=>sum+Math.max(0,numeric(frame.amountMm)),0);
 return{...radar,nowcastSeries:nextFrames,forecastAmount60:Number(forecastAmount60.toFixed(3)),forecastAmount120:Number(forecastAmount120.toFixed(3)),amountSource:usedRs?'DWD RS · 1-h-Mengenanker + DWD RV 5-min-Timing':'DWD RV · Wachstum/Zerfall-korrigiert',rsObservedAt:usedRs?rs?.observedAt:undefined,diagnostics:{...(radar.diagnostics||{}),rsCalibration:{available:Boolean(rs?.available),used:usedRs,anchors:anchorDiagnostics,error:rs?.error}}};
}

export function applyHxBoundaryCalibration(radar:RadarNowcast,hx:HxBoundaryCheck|undefined|null):RadarNowcast{
 if(!hx?.available)return{...radar,diagnostics:{...(radar.diagnostics||{}),hxBoundary:{available:false,error:hx?.error}}};
 const base=observedEpoch(radar),siteThreshold=Math.max(.02,numeric(radar.siteEchoThreshold,.05)),weakBoundary=!hx.strongEcho&&hx.siteSupport<.35&&(!Number.isFinite(Number(hx.nearestWetKm))||Number(hx.nearestWetKm)>.55),veryWeak=weakBoundary&&hx.siteSupport<.12&&(!Number.isFinite(Number(hx.nearestWetKm))||Number(hx.nearestWetKm)>1),frames=(radar.nowcastSeries??[]).map(frame=>{const epoch=frameEpoch(frame),lead=(epoch-base)/60000,rate=Math.max(0,numeric(frame.rate)),support=Number(frame.siteSupport);if(!frame.future||!Number.isFinite(lead)||lead<0||lead>50||rate<siteThreshold||rate>3.5)return frame;const rvBoundary=Number.isFinite(support)?support<.62:true;if(!rvBoundary)return frame;if(hx.strongEcho)return{...frame,siteSupport:Math.max(numeric(frame.siteSupport),hx.siteSupport),hxBoundaryFactor:1};const factor=veryWeak?.42:weakBoundary?.68:.86,amount=Number(frame.amountMm),nextRate=rate*factor,hitClass=nextRate<siteThreshold&&numeric(frame.nearbyRate)>=numeric(radar.nearbyEchoThreshold,.18)?'nearby':frame.hitClass;return{...frame,rate:Number(nextRate.toFixed(3)),amountMm:Number.isFinite(amount)?Number((amount*factor).toFixed(4)):frame.amountMm,siteSupport:Number(Math.min(numeric(frame.siteSupport,1),Math.max(.03,hx.siteSupport)).toFixed(2)),hitClass,hxBoundaryFactor:factor}}),probabilityFactor=veryWeak?.78:weakBoundary?.88:1,radarProbability=Math.round(clamp(numeric(radar.radarProbability)*probabilityFactor,0,100));
 return{...radar,nowcastSeries:frames,radarProbability,hxBoundaryCheck:{observedAt:hx.observedAt,siteSupport:hx.siteSupport,nearestWetKm:hx.nearestWetKm,centerRate:hx.centerRate,factor:probabilityFactor,source:hx.source},diagnostics:{...(radar.diagnostics||{}),hxBoundary:{available:true,observedAt:hx.observedAt,siteSupport:hx.siteSupport,nearestWetKm:hx.nearestWetKm,centerRate:hx.centerRate,strongEcho:hx.strongEcho,probabilityFactor}}};
}

export function applyStationAmountCalibration(radar:RadarNowcast,station:RadarRainStationCalibration|undefined|null,now=Date.now()):RadarNowcast{
 if(!station?.available||!Number.isFinite(Number(station.amount10m))||!Number.isFinite(Number(station.distanceKm))||Number(station.distanceKm)>15)return radar;const stationEpoch=Date.parse(station.observedAt||'');if(!Number.isFinite(stationEpoch)||Math.abs(now-stationEpoch)>30*60000)return radar;
 const frames=[...(radar.nowcastSeries??[])].sort((a,b)=>frameEpoch(a)-frameEpoch(b)),observed=frames.filter(frame=>!frame.future&&frameEpoch(frame)<=stationEpoch+6*60000&&frameEpoch(frame)>=stationEpoch-14*60000).slice(-3),radarObserved=observed.reduce((sum,frame,index)=>sum+Math.max(0,numeric(frame.amountMm,Math.max(0,numeric(frame.rate))*frameStepMinutes(observed,index)/60)),0),stationAmount=Math.max(0,numeric(station.amount10m));if(radarObserved<.015&&stationAmount<.015)return radar;
 const rawRatio=stationAmount<=.005&&radarObserved>.04?.55:(stationAmount+.015)/(radarObserved+.015),ratio=clamp(rawRatio,.55,1.08),cape=numeric((radar.diagnostics as Record<string,any>|undefined)?.meteorologicalContext?.cape),convective=cape>=300||numeric(radar.currentRate)>=8,distanceKm=Math.max(0,numeric(station.distanceKm)),ageMinutes=Math.max(0,Math.abs(now-stationEpoch)/60000),distanceWeight=clamp(1-distanceKm/20,.25,1),ageWeight=clamp(1-ageMinutes/35,.25,1),base=observedEpoch(radar),nextFrames:RadarNowcastFrame[]=frames.map(frame=>{if(!frame.future)return frame;const lead=(frameEpoch(frame)-base)/60000;if(!Number.isFinite(lead)||lead<0||lead>120)return frame;const amount=Number(frame.amountMm);if(!Number.isFinite(amount)||amount<=0)return frame;const horizonWeight=lead<=30?.48:lead<=60?.34:.16,weight=horizonWeight*distanceWeight*ageWeight*(convective?.45:1),factor=1+(ratio-1)*weight;return{...frame,amountMm:Number((amount*factor).toFixed(4)),stationCalibrationFactor:Number(factor.toFixed(3)),amountSource:`${frame.amountSource||'Radar'} · lokale Stationskontrolle`,amountConfidence:(frame.amountConfidence==='high'?'high':'medium') as 'high'|'medium'}}),calibration={name:station.name,provider:station.provider,observedAt:station.observedAt,distanceKm:station.distanceKm,amount10m:stationAmount,radarAmount10m:Number(radarObserved.toFixed(3)),ratio:Number(ratio.toFixed(3)),distanceWeight:Number(distanceWeight.toFixed(2)),ageWeight:Number(ageWeight.toFixed(2)),convectiveWeightReduced:convective};
 return{...radar,nowcastSeries:nextFrames,stationCalibration:calibration,diagnostics:{...(radar.diagnostics||{}),stationCalibration:calibration}};
}

export function applyRadarNowcastEnsemble(radar:RadarNowcast):RadarNowcast{
 const base=observedEpoch(radar),frames=[...(radar.nowcastSeries??[])].sort((a,b)=>frameEpoch(a)-frameEpoch(b)),future=frames.filter(frame=>frame.future&&frameEpoch(frame)>base&&frameEpoch(frame)<=base+122*60000);if(!future.length)return radar;const highConfidence=String(radar.amountSource||'').includes('DWD RS'),motionUncertainty=radar.motionConfidence==='high'?5:radar.motionConfidence==='medium'?8:12,intensityFactors=highConfidence?[.92,1,1.08]:radar.quality==='high'?[.84,1,1.16]:[.72,1,1.28],timingOffsets=[-motionUncertainty,0,motionUncertainty],supportThresholds=[.06,.12,.18,.24,.30,.36,.44,.52,.62],baseRows=future.map(frame=>({frame,epoch:frameEpoch(frame),amount:Math.max(0,numeric(frame.amountMm,numeric(frame.rate)*5/60)),support:clamp(numeric(frame.siteSupport,frame.hitClass==='site'?1:.3),0,1)})),members:{total:number;slots:number[]}[]=[];
 let memberIndex=0;for(const timing of timingOffsets)for(const intensity of intensityFactors){const supportGate=supportThresholds[memberIndex++]??.3,slots=baseRows.map(row=>{const target=row.epoch-timing*60000,source=baseRows.reduce((best,item)=>Math.abs(item.epoch-target)<Math.abs(best.epoch-target)?item:best,baseRows[0]);if(source.support<supportGate)return 0;const geometry=source.support<.35&&timing!==0?.68:source.support<.6&&timing!==0?.86:1;return source.amount*intensity*geometry}),total=slots.reduce((sum,value)=>sum+value,0);members.push({total,slots})}
 const totalValues=members.map(member=>member.total),totalP25=quantile(totalValues,.25),totalMedian=quantile(totalValues,.5),totalP75=quantile(totalValues,.75),hitProbability=Math.round(members.filter(member=>member.total>=.01).length/members.length*100),slotStats=baseRows.map((row,index)=>{const values=members.map(member=>member.slots[index]),p25=quantile(values,.25),median=quantile(values,.5),p75=quantile(values,.75),hit=Math.round(values.filter(value=>value>=.002).length/values.length*100);return{epoch:row.epoch,p25,median,p75,hit}}),statsByEpoch=new Map(slotStats.map(stat=>[stat.epoch,stat])),nextFrames=frames.map(frame=>{const stat=statsByEpoch.get(frameEpoch(frame));return stat?{...frame,amountP25:Number(stat.p25.toFixed(4)),amountP75:Number(stat.p75.toFixed(4)),hitProbability:stat.hit}:frame}),ensemble={members:9 as const,totalP25:Number(totalP25.toFixed(3)),totalMedian:Number(totalMedian.toFixed(3)),totalP75:Number(totalP75.toFixed(3)),hitProbability,method:'9-member timing/intensity ensemble; RS anchor preserved as central estimate'};
 const forecastAmount60=baseRows.filter(row=>row.epoch<=base+62*60000).reduce((sum,row)=>sum+row.amount,0);return{...radar,nowcastSeries:nextFrames,forecastAmount60:Number(forecastAmount60.toFixed(3)),forecastAmount120:ensemble.totalMedian,ensemble,diagnostics:{...(radar.diagnostics||{}),ensemble}};
}

export function finalizeRadarNowcastCalibration(radar:RadarNowcast,input:{rs?:DwdRsCalibration|null;hx?:HxBoundaryCheck|null;station?:RadarRainStationCalibration|null;now?:number}):RadarNowcast{let next=applyRsAmountCalibration(radar,input.rs);if(input.hx)next=applyHxBoundaryCalibration(next,input.hx);if(input.station)next=applyStationAmountCalibration(next,input.station,input.now);return applyRadarNowcastEnsemble(next)}
