import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {CloudRain,CloudSun,Gauge,Info,RefreshCw,ThermometerSun,Wind} from 'lucide-react';
import {formatDecimalFixed} from './format';
import {guardedOpenMeteoFetch} from './openMeteoGuard';
import type {Location} from './weather';

type Props={location:Location;advancedMode:boolean};
type TrendMetric='temperature'|'precipitation'|'pressure'|'cloud'|'wind';
type TrendWeekValue={mean:number;p10:number;p25:number;p75:number;p90:number;samples:number[];modelCount:number};
type TrendWeek={id:string;label:string;startDate:string;endDate:string;values:Record<TrendMetric,TrendWeekValue|null>};
type TrendModel={id:string;family:string;label:string;provider:string;members:number;horizonDays:number;gridLabel:string;weeks:TrendWeek[]};
type TrendBundle={generatedAt:string;models:TrendModel[];cacheStatus:'network'|'fresh-cache'|'stale-cache'|'mixed-stale';cacheAgeMinutes:number};
type ApiPayload={latitude?:number;longitude?:number;daily?:Record<string,unknown>;daily_units?:Record<string,string>};
type MetricDefinition={id:TrendMetric;label:string;unit:string;api:string;aggregate:'mean'|'sum';icon:typeof ThermometerSun};

const ECMWF_ENDPOINT='https://seasonal-api.open-meteo.com/v1/seasonal';
const ENSEMBLE_ENDPOINT='https://ensemble-api.open-meteo.com/v1/ensemble';
const CACHE_TTL_MS=2*60*60*1000;
const STALE_IF_ERROR_MS=12*60*60*1000;
const CACHE_PREFIX='mid:subseasonal-trend:v1:';
const METRICS:MetricDefinition[]=[
 {id:'temperature',label:'Temperatur',unit:'°C',api:'temperature_2m_mean',aggregate:'mean',icon:ThermometerSun},
 {id:'precipitation',label:'Niederschlag',unit:'mm/Woche',api:'precipitation_sum',aggregate:'sum',icon:CloudRain},
 {id:'pressure',label:'Luftdruck',unit:'hPa',api:'pressure_msl_mean',aggregate:'mean',icon:Gauge},
 {id:'cloud',label:'Bewölkung',unit:'%',api:'cloud_cover_mean',aggregate:'mean',icon:CloudSun},
 {id:'wind',label:'Windmittel',unit:'km/h',api:'wind_speed_10m_mean',aggregate:'mean',icon:Wind}
];
const DAILY_VARIABLES=METRICS.map(metric=>metric.api).join(',');

function finite(value:unknown){const numeric=Number(value);return Number.isFinite(numeric)?numeric:null}
function mean(values:number[]){return values.length?values.reduce((sum,value)=>sum+value,0)/values.length:null}
function quantile(values:number[],q:number){if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b),position=(sorted.length-1)*q,lower=Math.floor(position),upper=Math.ceil(position);if(lower===upper)return sorted[lower];const weight=position-lower;return sorted[lower]*(1-weight)+sorted[upper]*weight}
function summarize(samples:number[],modelCount=1):TrendWeekValue|null{const clean=samples.filter(Number.isFinite);if(!clean.length)return null;return{mean:mean(clean)!,p10:quantile(clean,.1)!,p25:quantile(clean,.25)!,p75:quantile(clean,.75)!,p90:quantile(clean,.9)!,samples:clean,modelCount}}
function memberSeries(daily:Record<string,unknown>,base:string){const keys=Object.keys(daily).filter(key=>key.startsWith(`${base}_member`)&&Array.isArray(daily[key])).sort();if(keys.length)return keys.map(key=>(daily[key] as unknown[]).map(finite));const direct=Array.isArray(daily[base])?(daily[base] as unknown[]).map(finite):[];return direct.length?[direct]:[]}
function formatDate(date:string){try{return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',timeZone:'UTC'}).format(new Date(`${date}T12:00:00Z`))}catch{return date.slice(5)}}
function aggregateMember(series:(number|null)[],start:number,end:number,mode:'mean'|'sum'){const values=series.slice(start,end).filter((value):value is number=>Number.isFinite(value));if(!values.length)return null;return mode==='sum'?values.reduce((sum,value)=>sum+value,0):values.reduce((sum,value)=>sum+value,0)/values.length}
function buildWeeks(payload:ApiPayload){const daily=payload.daily??{},time=Array.isArray(daily.time)?daily.time.map(String):[];if(time.length<=14)return{weeks:[] as TrendWeek[],members:0};const series=Object.fromEntries(METRICS.map(metric=>[metric.id,memberSeries(daily,metric.api)])) as Record<TrendMetric,(number|null)[][]>,members=Math.max(0,...METRICS.map(metric=>series[metric.id].length)),weeks:TrendWeek[]=[];for(let start=14;start<time.length;start+=7){const end=Math.min(time.length,start+7),startDate=time[start],endDate=time[end-1];if(!startDate||!endDate)continue;const values={} as Record<TrendMetric,TrendWeekValue|null>;for(const metric of METRICS){const samples=series[metric.id].map(member=>aggregateMember(member,start,end,metric.aggregate)).filter((value):value is number=>Number.isFinite(value));values[metric.id]=summarize(samples)}weeks.push({id:`${startDate}/${endDate}`,label:`Tag ${start+1}–${end}`,startDate,endDate,values})}return{weeks,members}}
function modelFromPayload(id:string,family:string,label:string,provider:string,horizonDays:number,gridLabel:string,payload:ApiPayload):TrendModel|null{const parsed=buildWeeks(payload);if(!parsed.weeks.length)return null;return{id,family,label,provider,members:parsed.members,horizonDays,gridLabel,weeks:parsed.weeks}}
function metricDefinition(metric:TrendMetric){return METRICS.find(item=>item.id===metric)!}
function cacheKey(location:Location){return`${CACHE_PREFIX}${location.latitude.toFixed(3)},${location.longitude.toFixed(3)}`}
function readCache(location:Location){try{const parsed=JSON.parse(localStorage.getItem(cacheKey(location))||'null') as {at:number;models:TrendModel[]}|null;return parsed&&Number.isFinite(parsed.at)&&Array.isArray(parsed.models)?parsed:null}catch{return null}}
function writeCache(location:Location,models:TrendModel[]){try{localStorage.setItem(cacheKey(location),JSON.stringify({at:Date.now(),models}))}catch{}}
function cacheBundle(record:{at:number;models:TrendModel[]},status:TrendBundle['cacheStatus']):TrendBundle{return{generatedAt:new Date(record.at).toISOString(),models:record.models,cacheStatus:status,cacheAgeMinutes:Math.max(0,Math.round((Date.now()-record.at)/60000))}}
async function fetchJson(url:string,signal:AbortSignal,refresh:boolean){const response=await guardedOpenMeteoFetch(url,{signal,cache:refresh?'reload':'default'},{priority:'normal'});let payload:unknown;try{payload=await response.json()}catch{throw new Error(`Trendquelle lieferte kein gültiges JSON (HTTP ${response.status}).`)}if(!response.ok){const reason=payload&&typeof payload==='object'&&'reason'in payload?String((payload as {reason?:unknown}).reason||''):'';throw new Error(reason||`Trendquelle HTTP ${response.status}`)}return payload as ApiPayload}
async function fetchEcmwf(location:Location,signal:AbortSignal,refresh:boolean){const params=new URLSearchParams({latitude:String(location.latitude),longitude:String(location.longitude),models:'ecmwf_ec46',daily:DAILY_VARIABLES,forecast_days:'46',timezone:'GMT',cell_selection:'nearest'}),payload=await fetchJson(`${ECMWF_ENDPOINT}?${params}`,signal,refresh);return modelFromPayload('ecmwf-ec46','ECMWF EC46','ECMWF · EC46','ECMWF via Open-Meteo Seasonal API',46,'ECMWF O320 · ca. 36 km',payload)}
async function fetchGefs(location:Location,signal:AbortSignal,refresh:boolean){const params=new URLSearchParams({latitude:String(location.latitude),longitude:String(location.longitude),models:'ncep_gefs05',daily:DAILY_VARIABLES,forecast_days:'35',timezone:'GMT',cell_selection:'nearest'}),payload=await fetchJson(`${ENSEMBLE_ENDPOINT}?${params}`,signal,refresh);return modelFromPayload('noaa-gefs35','NOAA GEFS','NOAA · GEFS 0,5°','NOAA NCEP via Open-Meteo Ensemble API',35,'GEFS 0,5° · ca. 50 km',payload)}
async function loadTrend(location:Location,signal:AbortSignal,refresh=false):Promise<TrendBundle>{const cached=readCache(location),age=cached?Date.now()-cached.at:Infinity;if(!refresh&&cached&&age<=CACHE_TTL_MS)return cacheBundle(cached,'fresh-cache');const settled=await Promise.allSettled([fetchEcmwf(location,signal,refresh),fetchGefs(location,signal,refresh)]);if(signal.aborted)throw new DOMException('Abgebrochen','AbortError');const models=settled.flatMap(result=>result.status==='fulfilled'&&result.value?[result.value]:[]),failures=settled.filter(result=>result.status==='rejected');if(models.length){let merged=models,status:TrendBundle['cacheStatus']='network';if(failures.length&&cached&&age<=STALE_IF_ERROR_MS){const ids=new Set(merged.map(model=>model.id));merged=[...merged,...cached.models.filter(model=>!ids.has(model.id))];status='mixed-stale'}writeCache(location,merged);return{generatedAt:new Date().toISOString(),models:merged,cacheStatus:status,cacheAgeMinutes:0}}if(cached&&age<=STALE_IF_ERROR_MS)return cacheBundle(cached,'stale-cache');const reason=failures.map(result=>result.status==='rejected'?(result.reason instanceof Error?result.reason.message:String(result.reason)):'').filter(Boolean).join(' · ');throw new Error(reason||'Subseasonale Ensemblequellen derzeit nicht verfügbar.')}
function resample(samples:number[],count=51){if(!samples.length)return[];const sorted=[...samples].sort((a,b)=>a-b);if(sorted.length===1)return Array.from({length:count},()=>sorted[0]);return Array.from({length:count},(_,index)=>quantile(sorted,index/(count-1))!).filter(Number.isFinite)}
function combineWeeks(models:TrendModel[]):TrendWeek[]{const ids=new Map<string,{label:string;startDate:string;endDate:string}>();models.forEach(model=>model.weeks.forEach(week=>ids.set(week.id,{label:week.label,startDate:week.startDate,endDate:week.endDate})));return[...ids.entries()].sort((a,b)=>a[1].startDate.localeCompare(b[1].startDate)).map(([id,meta])=>{const values={} as Record<TrendMetric,TrendWeekValue|null>;for(const metric of METRICS){const contributors=models.flatMap(model=>{const value=model.weeks.find(week=>week.id===id)?.values[metric.id];return value?.samples.length?[value.samples]:[]});values[metric.id]=contributors.length?summarize(contributors.flatMap(samples=>resample(samples)),contributors.length):null}return{id,...meta,values}})}
function formatMetric(value:number,metric:TrendMetric){const def=metricDefinition(metric);if(metric==='precipitation')return`${formatDecimalFixed(value,1)} ${def.unit}`;if(metric==='cloud'||metric==='pressure')return`${Math.round(value)} ${def.unit}`;return`${formatDecimalFixed(value,1)} ${def.unit}`}
function spreadLabel(value:TrendWeekValue,metric:TrendMetric){return`${formatMetric(value.p10,metric)} – ${formatMetric(value.p90,metric)}`}
function trendDescription(weeks:TrendWeek[],metric:TrendMetric){const rows=weeks.map(week=>week.values[metric]).filter((value):value is TrendWeekValue=>Boolean(value));if(rows.length<2)return'Noch kein belastbarer Verlauf über mehrere Wochen.';const first=rows[0].mean,last=rows.at(-1)!.mean,delta=last-first;if(metric==='temperature')return Math.abs(delta)<1?'Temperaturniveau über den Zeitraum relativ stabil.':delta>0?`Im Verlauf tendenziell wärmer · ${formatDecimalFixed(delta,1)} K zwischen erster und letzter Periode.`:`Im Verlauf tendenziell kühler · ${formatDecimalFixed(Math.abs(delta),1)} K zwischen erster und letzter Periode.`;if(metric==='precipitation'){const ratio=first>.2?last/first:1;return ratio>1.35?'Spätere Wochen zeigen ein feuchteres Niederschlagsregime.':ratio<.65?'Spätere Wochen zeigen ein trockeneres Niederschlagsregime.':'Kein ausgeprägter Wechsel des Niederschlagsregimes im Multi-Modell.'}if(metric==='pressure')return Math.abs(delta)<3?'Großräumiges Druckniveau ohne markanten Trend.':delta>0?'Tendenz zu höherem Luftdruck in den späteren Wochen.':'Tendenz zu niedrigerem Luftdruck in den späteren Wochen.';if(metric==='cloud')return Math.abs(delta)<8?'Bewölkungsniveau im Verlauf relativ stabil.':delta>0?'Spätere Wochen tendenziell wolkenreicher.':'Spätere Wochen tendenziell wolkenärmer.';return Math.abs(delta)<3?'Windniveau im Verlauf relativ stabil.':delta>0?'Spätere Wochen tendenziell windiger.':'Spätere Wochen tendenziell ruhiger.'}
function pathFor(rows:TrendWeek[],metric:TrendMetric,key:'mean'|'p10'|'p25'|'p75'|'p90',x:(index:number)=>number,y:(value:number)=>number){return rows.reduce((path,row,index)=>{const value=row.values[metric]?.[key];return Number.isFinite(value)?`${path}${path?' L':'M'} ${x(index)} ${y(Number(value))}`:path},'')}
function areaFor(rows:TrendWeek[],metric:TrendMetric,low:'p10'|'p25',high:'p75'|'p90',x:(index:number)=>number,y:(value:number)=>number){const upper=rows.map((row,index)=>{const value=row.values[metric]?.[high];return Number.isFinite(value)?`${index?'L':'M'} ${x(index)} ${y(Number(value))}`:null}).filter(Boolean) as string[],lower=[...rows].reverse().map((row,index)=>{const actual=rows.length-1-index,value=row.values[metric]?.[low];return Number.isFinite(value)?`L ${x(actual)} ${y(Number(value))}`:null}).filter(Boolean) as string[];return upper.length&&lower.length?`${upper.join(' ')} ${lower.join(' ')} Z`:''}
function TrendChart({weeks,metric}:{weeks:TrendWeek[];metric:TrendMetric}){const width=760,height=250,left=62,right=18,top=24,bottom=48,values=weeks.flatMap(week=>{const value=week.values[metric];return value?[value.p10,value.p25,value.mean,value.p75,value.p90]:[]}).filter(Number.isFinite);if(!values.length)return <div className="long-range-info"><p>Für diesen Parameter liegen im gewählten Zeitraum keine Ensemblewerte vor.</p></div>;let min=Math.min(...values),max=Math.max(...values);if(min===max){min-=1;max+=1}const pad=Math.max((max-min)*.12,metric==='pressure'?2:metric==='temperature'?1:.5);min-=pad;max+=pad;if(metric==='precipitation'||metric==='cloud'||metric==='wind')min=Math.max(0,min);const plotWidth=width-left-right,plotHeight=height-top-bottom,x=(index:number)=>left+(weeks.length<=1?.5:index/(weeks.length-1))*plotWidth,y=(value:number)=>top+(max-value)/(max-min)*plotHeight,ticks=Array.from({length:5},(_,index)=>max-(max-min)*index/4),outer=areaFor(weeks,metric,'p10','p90',x,y),inner=areaFor(weeks,metric,'p25','p75',x,y),line=pathFor(weeks,metric,'mean',x,y);return <div className={`long-range-chart combined ${metric==='temperature'?'temperature':metric==='precipitation'?'precipitation':''}`}><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${metricDefinition(metric).label} im Witterungstrend`}>{ticks.map((tick,index)=><g key={index}><line x1={left} x2={width-right} y1={y(tick)} y2={y(tick)} className="grid"/><text x={left-8} y={y(tick)+4} textAnchor="end" className="axis-label">{metric==='pressure'||metric==='cloud'?Math.round(tick):formatDecimalFixed(tick,1)}</text></g>)}{weeks.map((week,index)=><g key={week.id}><line x1={x(index)} x2={x(index)} y1={top} y2={height-bottom} className="vertical-grid"/><text x={x(index)} y={height-22} textAnchor="middle" className="month-label">{week.label.replace('Tag ','T')}</text><text x={x(index)} y={height-10} textAnchor="middle" className="month-label">{formatDate(week.startDate)}</text></g>)}{outer?<path d={outer} className="anomaly-plume outer"/>:null}{inner?<path d={inner} className="anomaly-plume inner"/>:null}{line?<path d={line} className="anomaly-mean-line"/>:null}{weeks.map((week,index)=>{const value=week.values[metric];return value?<g key={`dot-${week.id}`}><circle cx={x(index)} cy={y(value.mean)} r={5} className="anomaly-dot" style={{fill:'var(--accent)'}}/><title>{`${week.label} · ${formatDate(week.startDate)}–${formatDate(week.endDate)}: ${formatMetric(value.mean,metric)} · P10–P90 ${spreadLabel(value,metric)} · ${value.modelCount} Modellfamilie${value.modelCount===1?'':'n'}`}</title></g>:null})}</svg></div>}

export default function SubseasonalTrendPanel({location,advancedMode}:Props){
 const[data,setData]=useState<TrendBundle|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(''),[metric,setMetric]=useState<TrendMetric>(()=>{try{const stored=localStorage.getItem('mid:subseasonal-trend:metric');return METRICS.some(item=>item.id===stored)?stored as TrendMetric:'temperature'}catch{return'temperature'}}),[view,setView]=useState('combined'),[infoOpen,setInfoOpen]=useState(false),controllerRef=useRef<AbortController|null>(null);
 const load=useCallback(async(refresh=false)=>{controllerRef.current?.abort();const controller=new AbortController();controllerRef.current=controller;if(refresh)setRefreshing(true);else setLoading(true);setError('');try{const bundle=await loadTrend(location,controller.signal,refresh);if(!controller.signal.aborted){setData(bundle);setView(current=>current==='combined'||bundle.models.some(model=>model.id===current)?current:'combined')}}catch(reason){if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:'Witterungstrend konnte nicht geladen werden.')}finally{if(controllerRef.current===controller)controllerRef.current=null;if(!controller.signal.aborted){setLoading(false);setRefreshing(false)}}},[location.latitude,location.longitude]);
 useEffect(()=>{void load(false);return()=>controllerRef.current?.abort()},[load]);
 useEffect(()=>{try{localStorage.setItem('mid:subseasonal-trend:metric',metric)}catch{}},[metric]);
 const models=data?.models??[],combined=useMemo(()=>combineWeeks(models),[models]),selectedWeeks=view==='combined'?combined:models.find(model=>model.id===view)?.weeks??combined,selectedLabel=view==='combined'?'Multi-Modell':models.find(model=>model.id===view)?.family??'Multi-Modell',def=metricDefinition(metric),Icon=def.icon,cacheLabel=data?.cacheStatus==='fresh-cache'?`Cache · ${data.cacheAgeMinutes} min`:data?.cacheStatus==='stale-cache'?`Fallback-Cache · ${data.cacheAgeMinutes} min`:data?.cacheStatus==='mixed-stale'?`teilweise Cache · ${data.cacheAgeMinutes} min`:'';
 return <section className="long-range-overview"><header><div><strong>Witterungstrend · Tag 15–46</strong><small>Wochenblöcke statt scheinpräziser Tageswerte · ECMWF EC46 + NOAA GEFS bis Tag 35</small>{cacheLabel?<small>{cacheLabel}</small>:null}</div><div className="long-range-head-actions"><button type="button" onClick={()=>void load(true)} disabled={refreshing} aria-label="Witterungstrend aktualisieren" title="EC46 und GEFS neu abrufen"><RefreshCw size={16} className={refreshing?'spin':''}/></button><button type="button" className={infoOpen?'active':''} onClick={()=>setInfoOpen(value=>!value)} aria-label="Witterungstrend-Methodik"><Info size={16}/></button></div></header>
  {infoOpen?<div className="long-range-info"><p><b>Horizontvertrag:</b> Ab Tag 15 zeigt MID keine verlängerte deterministische Tagesprognose. Die Werte werden zu Wochenblöcken verdichtet. Innerhalb jeder Modellfamilie stammen Mittel und P10/P25/P75/P90 aus den Ensemblemitgliedern; im Multi-Modell werden die Modellfamilien gleich gewichtet. Ab Tag 36 steht derzeit nur EC46 zur Verfügung und wird entsprechend als Ein-Modell-Signal gekennzeichnet.</p>{advancedMode?<small>Die dargestellten Temperatur-, Niederschlags-, Druck-, Bewölkungs- und Windwerte sind direkte Modellwerte ohne lokale Beobachtungskorrektur. EC46 ist in diesem Pfad nicht bias-korrigiert. Dieser Subseasonal-Layer wird nicht in den kanonischen Kurzfrist-Forecast zurückgemischt.</small>:null}</div>:null}
  {loading&&!models.length?<div className="long-range-loading"><RefreshCw className="spin" size={17}/>EC46- und GEFS-Ensembles werden geladen …</div>:null}
  {error&&!models.length?<div className="long-range-error"><strong>Witterungstrend derzeit nicht verfügbar</strong><small>{error}</small></div>:null}
  {error&&models.length?<div className="long-range-info"><p><b>Teilaktualisierung:</b> {error}</p></div>:null}
  {models.length?<><div className="long-range-family-chips">{models.map(model=><span key={model.id}>{model.family}<small>{model.members||'–'} Member · bis Tag {model.horizonDays}</small></span>)}</div><div className="long-range-controls section-sticky-controls" style={{display:'grid'}}><div className="long-range-model-selector"><button type="button" className={view==='combined'?'active':''} onClick={()=>setView('combined')}><b>Multi-Modell</b><small>{models.length} unabhängige Familien</small></button>{models.map(model=><button key={model.id} type="button" className={view===model.id?'active':''} onClick={()=>setView(model.id)}><b>{model.family}</b><small>{model.members} Member · {model.gridLabel}</small></button>)}</div><div className="long-range-model-selector">{METRICS.map(item=><button key={item.id} type="button" className={metric===item.id?'active':''} onClick={()=>setMetric(item.id)}><b>{item.label}</b><small>{item.unit}</small></button>)}</div></div><div className="long-range-grid" style={{gridTemplateColumns:'1fr'}}><article><header><Icon size={18}/><div><strong>{def.label} · {selectedLabel}</strong><small>{trendDescription(selectedWeeks,metric)}</small></div></header><TrendChart weeks={selectedWeeks} metric={metric}/><footer><span>Außen P10–P90 · innen P25–P75 · Linie = Ensemble-Mittel</span><span>{view==='combined'?'Modellfamilien gleich gewichtet':'Ensemblemitglieder des gewählten Modells'}</span></footer></article></div><section className="long-range-models"><header><div><span>ENSEMBLE-VERGLEICH</span><h4>{def.label} je Wochenblock</h4></div></header><div className="long-range-model-strip">{combined.map(week=><article key={week.id}><strong>{week.label}</strong><small>{formatDate(week.startDate)} – {formatDate(week.endDate)}</small>{models.map(model=>{const value=model.weeks.find(row=>row.id===week.id)?.values[metric];return value?<span key={model.id}>{model.family}: {formatMetric(value.mean,metric)}<small> · P10–P90 {spreadLabel(value,metric)}</small></span>:null})}{week.values[metric]?<em>Multi: {formatMetric(week.values[metric]!.mean,metric)} · {week.values[metric]!.modelCount} Modellfamilie{week.values[metric]!.modelCount===1?'':'n'}</em>:null}</article>)}</div>{advancedMode?<div className="long-range-method"><b>Quellen und Reichweite</b><p>ECMWF EC46: 36-km-Subseasonal-Ensemble bis 46 Tage. NOAA GEFS 0,5°: 31 Member bis 35 Tage. MID verdichtet beide auf identische Wochenblöcke und hält die Inter-Modell-Gewichtung unabhängig von der Memberzahl bei 1:1.</p></div>:null}</section></>:null}
 </section>
}
