import type {Day,EnsembleDay,Hour,Location,RadarNowcast,Station,ThunderstormNowcast} from './weather';
import {readWeatherTwinSettings,type TwinActivity} from './forecastVerification';
import {fetchWorkerJson} from './workerClient';

export type SynopticFrontType='cold'|'warm'|'occlusion'|'trough'|'convergence'|'none';
export type SynopticConfidence='high'|'medium'|'low';
export type SynopticLifecycle='detected'|'approaching'|'passage'|'departing'|'verified'|'dissipated';
export type SynopticPoint=[number,number];
export type SynopticSignal={key:string;label:string;value:number;unit:string;support:number};
export type SynopticModelCandidate={
 modelId:string;modelLabel:string;type:SynopticFrontType;arrivalAt:string;score:number;confidence:SynopticConfidence;
 line:SynopticPoint[];motionDirectionDeg?:number;signals:SynopticSignal[];summary:string;runTime?:string;
};
export type SynopticStationPlot={id:string;name:string;provider:string;lat:number;lon:number;distanceKm:number;observedAt?:string;temperature?:number;dewPoint?:number;pressure?:number;windSpeedKt?:number;windDirection?:number;precipitation?:number;phase?:'before'|'transition'|'after';quality?:number};
export type SynopticOfficialAnalysis={available:boolean;label:string;sourcePage:string;imageUrl?:string;nominalTime?:string;publishedAt?:string;checkedAt:string;license:string;error?:string};
export type SynopticAgreement={modelCount:number;supportingModels:number;type:SynopticFrontType;typeAgreement:number;medianArrivalAt?:string;windowStart?:string;windowEnd?:string;spreadHours?:number;meanScore:number;confidence:SynopticConfidence;summary:string};
export type SynopticObservationCorridor={bearingDeg?:number;widthDeg:number;lengthKm:number;stations:SynopticStationPlot[];phaseSupport:number;summary:string};
export type SynopticTiming={modelMedianAt?:string;assimilatedAt?:string;windowStart?:string;windowEnd?:string;observationAdjustmentMinutes:number;radarAdjustmentMinutes:number;confidence:SynopticConfidence;reasons:string[]};
export type SynopticSource={label:string;kind:'official-analysis'|'model'|'observation'|'nowcast'|'local-archive';dataTime?:string;checkedAt?:string;detail:string};
export type SynopticWorkerResponse={officialAnalysis:SynopticOfficialAnalysis;candidates:SynopticModelCandidate[];agreement:SynopticAgreement;corridor:SynopticObservationCorridor;timing:SynopticTiming;sources:SynopticSource[];generatedAt:string;error?:string};
export type SynopticPhase={key:'before'|'during'|'after';title:string;period:string;temperature?:number;dewPoint?:number;pressure?:number;windKt?:number;gustKt?:number;windDirection?:number;rainProbability?:number;precipitation?:number;summary:string};
export type SynopticUncertaintyCause={key:'modelTiming'|'frontType'|'observations'|'sourceAge'|'analogues'|'nowcast';label:string;share:number;detail:string};
export type SynopticImpact={activity:TwinActivity|'general';label:string;level:'low'|'medium'|'high';summary:string;actions:string[]};
export type SynopticEventRecord={id:string;locationKey:string;type:SynopticFrontType;firstSeen:string;lastUpdated:string;predictedAt:string;windowStart:string;windowEnd:string;confidence:SynopticConfidence;lifecycle:SynopticLifecycle;modelArrivals:Record<string,string>;score:number;before?:SynopticPhase;after?:SynopticPhase;observedAt?:string;timingErrorMinutes?:number;impactSignature:string;verified:boolean};
export type SynopticAnalogue={id:string;date:string;type:SynopticFrontType;similarity:number;timingErrorMinutes?:number;summary:string};
export type SynopticIntelligence={event:SynopticEventRecord|null;phases:SynopticPhase[];uncertainty:SynopticUncertaintyCause[];causalChain:string[];impacts:SynopticImpact[];analogues:SynopticAnalogue[];verification:{events:number;verified:number;meanAbsoluteTimingErrorMinutes?:number;summary:string};nextChangeSummary:string};

const ARCHIVE_PREFIX='mid:synoptic-events:v1:';
const SNAPSHOT_PREFIX='mid:synoptic-snapshot:v1:';
const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value));
const finite=(value:unknown,fallback=NaN)=>{const n=Number(value);return Number.isFinite(n)?n:fallback};
const circularDifference=(a:number,b:number)=>Math.abs(((a-b+540)%360)-180);
const frontLabel=(type:SynopticFrontType)=>({cold:'Kaltfront',warm:'Warmfront',occlusion:'Okklusion',trough:'Trogachse',convergence:'Konvergenzlinie',none:'kein markanter Frontkandidat'} as const)[type];
export {frontLabel};

export async function loadSynopticAnalysis(location:Location,signal?:AbortSignal){
 return fetchWorkerJson<SynopticWorkerResponse>('synoptic-analysis',{lat:location.latitude,lon:location.longitude,country:location.country_code||location.country||''},{purpose:'radar',signal,timeoutMs:28000,maxAgeMs:20*60000,staleIfErrorMs:3*3600000,cacheKey:`${location.latitude.toFixed(3)}:${location.longitude.toFixed(3)}`});
}

function localDateTime(value:string|number,timeZone?:string){const date=new Date(value);if(!Number.isFinite(date.getTime()))return'–';return new Intl.DateTimeFormat('de-DE',{timeZone:timeZone||undefined,weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(date)}
function hourClosest(hours:Hour[],target:number){let best:Hour|undefined,bestDelta=Infinity;for(const hour of hours){const epoch=finite(hour.epoch,Date.parse(hour.time));const delta=Math.abs(epoch-target);if(delta<bestDelta){best=hour;bestDelta=delta}}return best}
function phaseFromHour(key:SynopticPhase['key'],title:string,target:number,hours:Hour[],timeZone:string|undefined,spanHours:number){const hour=hourClosest(hours,target),near=hours.filter(item=>Math.abs(finite(item.epoch,Date.parse(item.time))-target)<=spanHours*3600000),rain=near.reduce((sum,item)=>sum+Math.max(0,finite(item.precipitation,0)),0),probability=near.length?Math.max(...near.map(item=>finite(item.probability,0))):undefined;if(!hour)return{key,title,period:localDateTime(target,timeZone),summary:'Für diesen Zeitraum liegen noch keine vollständigen Stundenwerte vor.'};const summary=key==='before'?`Ausgangsluftmasse: ${Math.round(hour.temperature)} °C, Taupunkt ${Math.round(hour.dewPoint)} °C und ${Math.round(hour.pressure)} hPa.`:key==='during'?`${rain>=1?'Niederschlagsschwerpunkt':'Wetterwechsel'} mit Winddrehung und möglicher Drucktendenzänderung.`:`Nachfolgende Luftmasse: ${Math.round(hour.temperature)} °C, Wind ${Math.round(hour.wind)} kt, Druck ${Math.round(hour.pressure)} hPa.`;return{key,title,period:localDateTime(target,timeZone),temperature:hour.temperature,dewPoint:hour.dewPoint,pressure:hour.pressure,windKt:hour.wind,gustKt:hour.gust,windDirection:hour.direction,rainProbability:probability,precipitation:rain,summary}}

export function localFrontCandidate(hours:Hour[],location:Location):SynopticModelCandidate|null{
 const now=Date.now(),usable=hours.filter(hour=>finite(hour.epoch,Date.parse(hour.time))>=now-2*3600000&&finite(hour.epoch,Date.parse(hour.time))<=now+84*3600000);let best:{index:number;score:number;type:SynopticFrontType;signals:SynopticSignal[]}|null=null;
 for(let index=3;index<usable.length-3;index++){const before=usable[index-3],current=usable[index],after=usable[index+3],temperatureChange=after.temperature-before.temperature,dewChange=after.dewPoint-before.dewPoint,pressureTrough=Math.max(0,(before.pressure+after.pressure)/2-current.pressure),windShift=circularDifference(before.direction,after.direction),rain=usable.slice(Math.max(0,index-2),index+3).reduce((sum,item)=>sum+Math.max(0,item.precipitation),0),cloud=Math.max(current.cloud,after.cloud),gustJump=Math.max(0,after.gust-before.gust),score=clamp(Math.abs(temperatureChange)*11+Math.abs(dewChange)*7+pressureTrough*12+windShift*.42+Math.min(18,rain*4)+Math.max(0,cloud-65)*.18+gustJump*.45,0,100);let type:SynopticFrontType='trough';if(temperatureChange<=-1.6&&windShift>=22)type='cold';else if(temperatureChange>=1.3&&windShift>=18)type='warm';else if(Math.abs(temperatureChange)<1.7&&Math.abs(dewChange)>=2&&rain>=1&&pressureTrough>=.7)type='occlusion';else if(windShift>=45&&rain>=.4&&pressureTrough<1.2)type='convergence';const signals:SynopticSignal[]=[{key:'temperature',label:'Temperaturänderung',value:Number(temperatureChange.toFixed(1)),unit:'K / 6 h',support:clamp(Math.abs(temperatureChange)/4,0,1)},{key:'dewpoint',label:'Taupunktänderung',value:Number(dewChange.toFixed(1)),unit:'K / 6 h',support:clamp(Math.abs(dewChange)/4,0,1)},{key:'pressure',label:'Druckrinne',value:Number(pressureTrough.toFixed(1)),unit:'hPa',support:clamp(pressureTrough/3,0,1)},{key:'wind',label:'Winddrehung',value:Math.round(windShift),unit:'°',support:clamp(windShift/90,0,1)},{key:'precipitation',label:'Niederschlag',value:Number(rain.toFixed(1)),unit:'mm / 5 h',support:clamp(rain/5,0,1)}];if(score>=34&&(!best||score>best.score))best={index,score,type,signals}}
 if(!best)return null;const hour=usable[best.index],angle=(hour.direction+90)%360,length=2.5,latScale=Math.cos(location.latitude*Math.PI/180),dy=Math.cos(angle*Math.PI/180)*length,dx=Math.sin(angle*Math.PI/180)*length/Math.max(.35,latScale),line=[[location.latitude-dy,location.longitude-dx],[location.latitude+dy,location.longitude+dx]] as SynopticPoint[];return{modelId:'best-match-local',modelLabel:'Best Match · lokaler Stundenverlauf',type:best.type,arrivalAt:new Date(finite(hour.epoch,Date.parse(hour.time))).toISOString(),score:Math.round(best.score),confidence:best.score>=68?'high':best.score>=48?'medium':'low',line,motionDirectionDeg:hour.direction,signals:best.signals,summary:`${frontLabel(best.type)} als lokaler Wetterwechselsignal-Kandidat aus Temperatur, Taupunkt, Druck, Wind und Niederschlag.`};
}

function archiveKey(locationKey:string){return`${ARCHIVE_PREFIX}${locationKey}`}
function readArchive(locationKey:string):SynopticEventRecord[]{try{const rows=JSON.parse(localStorage.getItem(archiveKey(locationKey))||'[]');return Array.isArray(rows)?rows.filter(row=>row&&typeof row==='object').slice(-80):[]}catch{return[]}}
function writeArchive(locationKey:string,rows:SynopticEventRecord[]){try{localStorage.setItem(archiveKey(locationKey),JSON.stringify(rows.slice(-80)))}catch{}}
function eventId(locationKey:string,type:SynopticFrontType,predictedAt:string){const slot=Math.round(Date.parse(predictedAt)/(6*3600000));return`${locationKey}:${type}:${slot}`}
function lifecycle(predictedAt:string,verified:boolean){const hours=(Date.parse(predictedAt)-Date.now())/3600000;if(verified)return'verified';if(hours>18)return'detected';if(hours>2)return'approaching';if(hours>=-2)return'passage';if(hours>=-12)return'departing';return'dissipated'}
function observationPassage(station:Station|null|undefined,event:SynopticEventRecord,hours:Hour[]){if(!station?.timestamp)return undefined;const observed=Date.parse(station.timestamp),predicted=Date.parse(event.predictedAt);if(!Number.isFinite(observed)||Math.abs(observed-predicted)>8*3600000)return undefined;const model=hourClosest(hours,observed),temperatureDelta=model&&Number.isFinite(station.temperature)?Math.abs(Number(station.temperature)-model.temperature):0,pressureDelta=model&&Number.isFinite(station.pressure)?Math.abs(Number(station.pressure)-model.pressure):0,windDelta=model&&Number.isFinite(station.windDirection)?circularDifference(Number(station.windDirection),model.direction):0;if(temperatureDelta>=2||pressureDelta>=2||windDelta>=45)return observed;return undefined}
function updateEventArchive(locationKey:string,candidate:SynopticModelCandidate,agreement:SynopticAgreement,timing:SynopticTiming,phases:SynopticPhase[],station:Station|null|undefined,hours:Hour[]){const predictedAt=timing.assimilatedAt||agreement.medianArrivalAt||candidate.arrivalAt,spread=Math.max(90,Math.round((agreement.spreadHours||3)*60/2)),windowStart=timing.windowStart||new Date(Date.parse(predictedAt)-spread*60000).toISOString(),windowEnd=timing.windowEnd||new Date(Date.parse(predictedAt)+spread*60000).toISOString(),id=eventId(locationKey,agreement.type==='none'?candidate.type:agreement.type,predictedAt),rows=readArchive(locationKey),previous=rows.find(row=>row.id===id),modelArrivals=Object.fromEntries((agreement.supportingModels?[]:[candidate]).concat([]).map(item=>[item.modelId,item.arrivalAt]));const base:SynopticEventRecord={id,locationKey,type:agreement.type==='none'?candidate.type:agreement.type,firstSeen:previous?.firstSeen||new Date().toISOString(),lastUpdated:new Date().toISOString(),predictedAt,windowStart,windowEnd,confidence:timing.confidence||agreement.confidence,lifecycle:'detected',modelArrivals:{...(previous?.modelArrivals||{}),...modelArrivals,[candidate.modelId]:candidate.arrivalAt},score:Math.round((candidate.score+agreement.meanScore)/2),before:phases[0],after:phases[2],impactSignature:`${Math.round(phases[1]?.gustKt||0)}:${Math.round(phases[1]?.rainProbability||0)}:${Math.round((phases[2]?.temperature||0)-(phases[0]?.temperature||0))}`,verified:previous?.verified||false,observedAt:previous?.observedAt,timingErrorMinutes:previous?.timingErrorMinutes};const passage=observationPassage(station,base,hours);if(passage){base.verified=true;base.observedAt=new Date(passage).toISOString();base.timingErrorMinutes=Math.round((passage-Date.parse(predictedAt))/60000)}base.lifecycle=lifecycle(predictedAt,base.verified);const next=rows.filter(row=>row.id!==id);next.push(base);writeArchive(locationKey,next);return base}

function analogues(locationKey:string,event:SynopticEventRecord|null){if(!event)return[];const rows=readArchive(locationKey).filter(row=>row.id!==event.id&&row.type===event.type&&row.verified);return rows.map(row=>{const scoreDelta=Math.abs(row.score-event.score),signatureA=row.impactSignature.split(':').map(Number),signatureB=event.impactSignature.split(':').map(Number),impactDelta=signatureA.reduce((sum,value,index)=>sum+Math.abs(value-(signatureB[index]||0)),0),similarity=clamp(100-scoreDelta*.65-impactDelta*.8,0,99);return{id:row.id,date:row.observedAt||row.predictedAt,type:row.type,similarity:Math.round(similarity),timingErrorMinutes:row.timingErrorMinutes,summary:`${frontLabel(row.type)} · damaliger Timingfehler ${Number.isFinite(row.timingErrorMinutes)?`${Math.abs(Number(row.timingErrorMinutes))} min`:'noch ohne Wertung'}`}}).sort((a,b)=>b.similarity-a.similarity).slice(0,3)}
function verification(locationKey:string){const rows=readArchive(locationKey),verified=rows.filter(row=>row.verified&&Number.isFinite(row.timingErrorMinutes)),mae=verified.length?Math.round(verified.reduce((sum,row)=>sum+Math.abs(Number(row.timingErrorMinutes)),0)/verified.length):undefined;return{events:rows.length,verified:verified.length,meanAbsoluteTimingErrorMinutes:mae,summary:verified.length?`${verified.length} Ereignisse verifiziert · mittlerer absoluter Timingfehler ${mae} min.`:'Das Analogarchiv beginnt mit diesem Standort; verifizierbare Frontpassagen werden fortlaufend ergänzt.'}}

function buildUncertainty(response:SynopticWorkerResponse|undefined,analogCount:number,radar:RadarNowcast|null|undefined):SynopticUncertaintyCause[]{const agreement=response?.agreement,stations=response?.corridor?.stations.length||0,age=response?.generatedAt?Math.max(0,(Date.now()-Date.parse(response.generatedAt))/60000):180,raw=[{key:'modelTiming' as const,label:'Modell-Timing',weight:clamp((agreement?.spreadHours||10)/12,0.1,1),detail:`Zeitspanne der Modelle: ${Number.isFinite(agreement?.spreadHours)?`${Number(agreement?.spreadHours).toFixed(1)} h`:'noch nicht belastbar'}.`},{key:'frontType' as const,label:'Fronttyp / Stärke',weight:clamp(1-(agreement?.typeAgreement||0),.08,1),detail:`Typübereinstimmung ${Math.round((agreement?.typeAgreement||0)*100)} %.`},{key:'observations' as const,label:'Beobachtungskorridor',weight:clamp(1-stations/8,.08,1),detail:`${stations} verwertbare stromaufwärtige Stationsplots.`},{key:'sourceAge' as const,label:'Datenalter',weight:clamp(age/180,.05,1),detail:`Analyse vor rund ${Math.round(age)} min aktualisiert.`},{key:'analogues' as const,label:'Lokale Analogfälle',weight:clamp(1-analogCount/4,.08,1),detail:`${analogCount} ähnliche verifizierte lokale Fälle.`},{key:'nowcast' as const,label:'Radar-/Nowcast-Stützung',weight:radar?.coverage?clamp(1-(radar.quality==='high'?0.85:(radar.quality==='medium'?0.62:0.35)),.08,1):.9,detail:radar?.coverage?`Radarqualität ${radar.quality}; Niederschlagsband wird separat assimiliert.`:'Keine belastbare Radarstützung für das Fronttiming.'}],total=raw.reduce((sum,item)=>sum+item.weight,0);return raw.map(item=>({key:item.key,label:item.label,share:Math.round(item.weight/total*100),detail:item.detail})).sort((a,b)=>b.share-a.share)}
function radarAdjustment(candidateAt:string,radar:RadarNowcast|null|undefined){if(!radar?.coverage||!Number.isFinite(radar.arrivalMinutes))return{minutes:0,reason:''};const modelMinutes=(Date.parse(candidateAt)-Date.now())/60000;if(modelMinutes<0||modelMinutes>720)return{minutes:0,reason:''};const delta=clamp(Number(radar.arrivalMinutes)-modelMinutes,-120,120);return{minutes:Math.round(delta*.35),reason:`Radar-/Nowcast-Niederschlagsband verschiebt die Ereignismitte begrenzt um ${Math.round(delta*.35)} min.`}}
function impacts(phases:SynopticPhase[],type:SynopticFrontType):SynopticImpact[]{const settings=readWeatherTwinSettings(),before=phases[0],during=phases[1],after=phases[2],gust=Math.max(during?.gustKt||0,after?.gustKt||0),rain=during?.rainProbability||0,tempChange=(after?.temperature||0)-(before?.temperature||0),base:SynopticImpact={activity:'general',label:'Allgemeine Auswirkungen',level:gust>=35||rain>=80?'high':gust>=24||rain>=55?'medium':'low',summary:`${frontLabel(type)}: ${tempChange<=-3?'deutlich kühler':tempChange>=3?'deutlich milder':'nur mäßige Temperaturänderung'}, Böen bis etwa ${Math.round(gust)} kt und Regenwahrscheinlichkeit bis ${Math.round(rain)} % während des Übergangs.`,actions:[rain>=60?'Nasse Fahrbahn und zeitweise schlechtere Sicht einplanen.':'Kurzzeitige Wetterverschlechterung im Übergangsfenster beachten.',gust>=28?'Lose Gegenstände und empfindliche Außenanlagen sichern.':'Keine ausgeprägte Windwirkung aus den aktuellen Daten ableitbar.']};const labels:Record<TwinActivity,string>={commute:'Berufsverkehr',outdoor:'Draußen',garden:'Garten',rowing:'Rudern',dog:'Hundespaziergang',ski:'Ski/Berg',heat:'Hitzebelastung'},items=[base];for(const activity of Object.keys(settings.activities) as TwinActivity[]){const profile=settings.activities[activity];if(!profile.enabled)continue;const high=rain>profile.maxRainProbability||gust>profile.maxGustKt||(during?.temperature??20)<profile.minTemperature||(during?.temperature??20)>profile.maxTemperature,level=high?'high':rain>.7*profile.maxRainProbability||gust>.7*profile.maxGustKt?'medium':'low';items.push({activity,label:labels[activity],level,summary:level==='high'?`Das Frontfenster überschreitet mindestens einen persönlichen Schwellenwert für ${labels[activity]}.`:`Die persönlichen Grenzwerte für ${labels[activity]} werden ${level==='medium'?'annähernd erreicht':'voraussichtlich eingehalten'}.`,actions:[level==='high'?'Aktivität möglichst vor oder nach dem Übergangsfenster legen.':`Zeitfenster mit geringerem Regen- und Böenrisiko bevorzugen.`,activity==='garden'&&gust>=25?'Markise, Abdeckung und leichte Gartenmöbel rechtzeitig sichern.':activity==='rowing'&&gust>=profile.maxGustKt?'Wassertraining im Frontfenster vermeiden.':'Lokale Kurzfristentwicklung vor Beginn erneut prüfen.']})}return items}
function causalChain(locationKey:string,candidate:SynopticModelCandidate,response:SynopticWorkerResponse|undefined,timing:SynopticTiming,radarReason:string){let previous:SynopticEventRecord|undefined;try{previous=JSON.parse(localStorage.getItem(`${SNAPSHOT_PREFIX}${locationKey}`)||'null')||undefined}catch{}const chain=[`${candidate.modelLabel} erkennt ${frontLabel(candidate.type)} mit ${candidate.score}/100 Punkten aus den objektiven Feldsignalen.`,response?.agreement.supportingModels?`${response.agreement.supportingModels} Modelle stützen das Ereignis; die Typübereinstimmung beträgt ${Math.round(response.agreement.typeAgreement*100)} %.`:'Der Best-Match-Stundenverlauf liefert derzeit die lokale Ersatzanalyse.',response?.corridor.stations.length?`${response.corridor.stations.length} stromaufwärtige Beobachtungen prüfen, ob die vorgelagerte beziehungsweise nachfolgende Luftmasse bereits messbar ist.`:'Der Beobachtungskorridor ist noch dünn besetzt.',...timing.reasons,radarReason].filter(Boolean) as string[];if(previous&&previous.type===candidate.type){const delta=Math.round((Date.parse(timing.assimilatedAt||candidate.arrivalAt)-Date.parse(previous.predictedAt))/60000);if(Math.abs(delta)>=15)chain.push(`Gegenüber der letzten MID-Bewertung verschiebt sich die Ereignismitte um ${Math.abs(delta)} min ${delta<0?'nach vorn':'nach hinten'}.`);else chain.push('Gegenüber der letzten MID-Bewertung bleibt das Fronttiming nahezu stabil.')}try{localStorage.setItem(`${SNAPSHOT_PREFIX}${locationKey}`,JSON.stringify({type:candidate.type,predictedAt:timing.assimilatedAt||candidate.arrivalAt,updatedAt:new Date().toISOString()}))}catch{}return chain}

export function buildSynopticIntelligence(input:{location:Location;locationKey:string;hours:Hour[];days:Day[];ensemble:EnsembleDay[];station?:Station|null;radar?:RadarNowcast|null;thunder?:ThunderstormNowcast|null;worker?:SynopticWorkerResponse|null}):SynopticIntelligence{
 const fallback=localFrontCandidate(input.hours,input.location),workerCandidates=input.worker?.candidates||[],primary=workerCandidates.slice().sort((a,b)=>b.score-a.score)[0]||fallback;if(!primary)return{event:null,phases:[],uncertainty:[],causalChain:['In den nächsten 84 Stunden wird aus den verfügbaren Feldern kein ausreichend markanter, kohärenter Wetterwechsel erkannt.'],impacts:[],analogues:[],verification:verification(input.locationKey),nextChangeSummary:'Kein markanter Frontdurchgang in den nächsten 84 Stunden objektiviert.'};const response=input.worker||undefined,agreement=response?.agreement||{modelCount:1,supportingModels:1,type:primary.type,typeAgreement:1,medianArrivalAt:primary.arrivalAt,windowStart:new Date(Date.parse(primary.arrivalAt)-3*3600000).toISOString(),windowEnd:new Date(Date.parse(primary.arrivalAt)+3*3600000).toISOString(),spreadHours:6,meanScore:primary.score,confidence:primary.confidence,summary:'Lokale Ersatzanalyse aus Best Match.'},radar=radarAdjustment(agreement.medianArrivalAt||primary.arrivalAt,input.radar),baseTiming=response?.timing||{modelMedianAt:agreement.medianArrivalAt,assimilatedAt:agreement.medianArrivalAt,windowStart:agreement.windowStart,windowEnd:agreement.windowEnd,observationAdjustmentMinutes:0,radarAdjustmentMinutes:0,confidence:agreement.confidence,reasons:[]},assimilatedBase=baseTiming.assimilatedAt||agreement.medianArrivalAt||primary.arrivalAt,assimilatedAt=new Date(Date.parse(assimilatedBase)+radar.minutes*60000).toISOString(),timing={...baseTiming,assimilatedAt,radarAdjustmentMinutes:radar.minutes,reasons:[...baseTiming.reasons,...(radar.reason?[radar.reason]:[])]},center=Date.parse(assimilatedAt),phases=[phaseFromHour('before','Vorher',center-9*3600000,input.hours,input.location.timezone,3),phaseFromHour('during','Während',center,input.hours,input.location.timezone,3),phaseFromHour('after','Nachher',center+9*3600000,input.hours,input.location.timezone,3)],event=updateEventArchive(input.locationKey,primary,agreement,timing,phases,input.station,input.hours),analogueRows=analogues(input.locationKey,event),uncertainty=buildUncertainty(response,analogueRows.length,input.radar),impactRows=impacts(phases,event.type),chain=causalChain(input.locationKey,primary,response,timing,radar.reason),window=`${localDateTime(event.windowStart,input.location.timezone)} bis ${localDateTime(event.windowEnd,input.location.timezone)}`,strongest=primary.signals.slice().sort((a,b)=>b.support-a.support)[0];return{event,phases,uncertainty,causalChain:chain,impacts:impactRows,analogues:analogueRows,verification:verification(input.locationKey),nextChangeSummary:`${frontLabel(event.type)} voraussichtlich ${window}. Markantestes Signal: ${strongest?.label||'kombinierter Feldwechsel'}${strongest?` (${strongest.value} ${strongest.unit})`:''}.`}
}
