import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {CanvasOverlay,GeoJsonLayers,ImageQuadLayer} from './MapLibreCore';
import {loadSynopticIndex,loadSynopticField,synopticRaster,THETAE_BANDS,jetWindStyle,type SynopticField} from './nativeSynopticFields';
import {synopticCompositePlan} from './synopticComposite';
export function useSynopticCatalog(revision:number){const [catalog,setCatalog]=useState<Awaited<ReturnType<typeof loadSynopticIndex>>|null>(null),[error,setError]=useState('');useEffect(()=>{const c=new AbortController();const timeout=window.setTimeout(()=>{setError('Synoptik-Katalog: Zeitüberschreitung. Bitte erneut laden.');c.abort()},20000);setCatalog(null);setError('');void loadSynopticIndex(c.signal).then(d=>{if(!c.signal.aborted)setCatalog(d)}).catch(e=>{if(!c.signal.aborted)setError(String(e.message||e))}).finally(()=>window.clearTimeout(timeout));return()=>{window.clearTimeout(timeout);c.abort()}},[revision]);return {catalog,error}}
export function useSynopticComposite(enabled:boolean,target:number,_revision:number,_showFill:boolean,modelId:string,catalog:ReturnType<typeof useSynopticCatalog>){
 const [field,setField]=useState<SynopticField|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),cache=useRef(new Map<string,SynopticField>()),model=catalog.catalog?.index.models[modelId],plan=useMemo(()=>enabled?synopticCompositePlan(model,target):null,[enabled,model,target]);
 const remember=(key:string,value:SynopticField)=>{cache.current.set(key,value);while(cache.current.size>4)cache.current.delete(cache.current.keys().next().value!)};
 useEffect(()=>{
  const controller=new AbortController();setField(previous=>enabled&&previous?.model===modelId?previous:null);setError('');setLoading(false);
  if(!plan||!model||!catalog.catalog)return()=>controller.abort();
  const key=`${modelId}:${plan.frame.sha256}`,cached=cache.current.get(key);if(cached){setField(cached);return()=>controller.abort()}
  setLoading(true);const timer=window.setTimeout(()=>{setError('Synoptik-Feld: Zeitüberschreitung. Der bisherige Stand bleibt sichtbar.');setLoading(false);controller.abort()},30000);
  void loadSynopticField(catalog.catalog.base,modelId,model,plan.frame,controller.signal).then(value=>{if(!controller.signal.aborted){remember(key,value);setField(value)}}).catch(e=>{if(!controller.signal.aborted)setError(String(e.message||e))}).finally(()=>{window.clearTimeout(timer);if(!controller.signal.aborted)setLoading(false)});
  return()=>{window.clearTimeout(timer);controller.abort()};
 },[plan?.time,plan?.run,modelId,catalog.catalog]);
 return {plan,field,loading,error:error||catalog.error,ready:Boolean(field&&field.time===plan?.time&&field.run===plan?.run),model};
}
export function SynopticCompositeLayers({state,opacity,showFill,thetaOnly=false,heightOnly=false}:{state:ReturnType<typeof useSynopticComposite>;opacity:number;showFill:boolean;thetaOnly?:boolean;heightOnly?:boolean}){
 const field=state.field,raster=useMemo(()=>field&&showFill&&!heightOnly?synopticRaster(field):'',[field,showFill,heightOnly]);
 const draw=useCallback((map:Parameters<Parameters<typeof CanvasOverlay>[0]['render']>[0],canvas:HTMLCanvasElement)=>{const size=map.getContainer().getBoundingClientRect(),ratio=devicePixelRatio||1;canvas.width=size.width*ratio;canvas.height=size.height*ratio;const c=canvas.getContext('2d');if(!c||!field)return;c.scale(ratio,ratio);c.strokeStyle='#15202b';c.lineWidth=1.2;const occupied=new Set<string>();for(const [lon,lat,u,v] of field.wind){const style=jetWindStyle(u,v);if(!style)continue;const p=map.project([lon,lat]),cell=`${Math.floor(p.x/40)}:${Math.floor(p.y/40)}`;if(p.x<0||p.y<0||p.x>size.width||p.y>size.height||occupied.has(cell))continue;occupied.add(cell);c.lineWidth=style.width;const {speed,length}=style,dx=u/speed*length,dy=-v/speed*length;c.beginPath();c.moveTo(p.x-dx/2,p.y-dy/2);c.lineTo(p.x+dx/2,p.y+dy/2);const angle=Math.atan2(dy,dx);for(const side of [-1,1]){c.moveTo(p.x+dx/2,p.y+dy/2);c.lineTo(p.x+dx/2-5*Math.cos(angle+side*.55),p.y+dy/2-5*Math.sin(angle+side*.55))}c.stroke()}},[field]);
 if(!field)return null;const dark=heightOnly&&(document.documentElement.dataset.theme==='dark'||document.documentElement.classList.contains('dark')),heightColor=dark?'#e5edf3':'#17212b';
 const contours=(key:'height'|'pressure'|'humidity',color:string,dashed=false)=><GeoJsonLayers key={key} id={`synoptic-${key}`} data={key==='humidity'?{...field.humidity,features:field.humidity.features.filter(f=>f.properties.level===60||f.properties.level===80)}:field[key]} zIndex={key==='pressure'?680:675} hoverProperty={key==='humidity'?undefined:'label'} layers={[{id:'line',type:'line',...(dashed?{filter:['==',['get','level'],60]}:{}),paint:{'line-color':color,'line-width':key==='height'?1.7:1.25,'line-opacity':opacity/100,...(dashed?{'line-dasharray':[3,2]}:{})}},...(dashed?[{id:'solid',type:'line' as const,filter:['==',['get','level'],80],paint:{'line-color':color,'line-width':1.25,'line-opacity':opacity/100}}]:[]),...(key==='humidity'?[]:[{id:'label',type:'symbol' as const,layout:{'symbol-placement':'line','symbol-spacing':180,'text-field':['get','label'],'text-size':10,'text-font':['Noto Sans Regular']},paint:{'text-color':color,'text-halo-color':key==='pressure'?'#354753':'#e4e8e3','text-halo-width':1,'text-opacity':opacity/100}}])]}/>;
 return <>{field.thetaContours&&showFill&&!heightOnly&&<GeoJsonLayers id="synoptic-theta-contours" data={field.thetaContours} zIndex={670} layers={[{id:'line',type:'line',paint:{'line-color':'#666666','line-width':.65,'line-opacity':opacity/100*.45}},{id:'label',type:'symbol',filter:['==',['%', ['get','level'],12],0],layout:{'symbol-placement':'line','symbol-spacing':240,'text-field':['get','label'],'text-size':9,'text-font':['Noto Sans Regular']},paint:{'text-color':'#4c4c4c','text-halo-color':'#f3f3f3','text-halo-width':.5,'text-opacity':opacity/100*.8}}]}/>} {raster&&<ImageQuadLayer id="synoptic-thetae" url={raster} bounds={[[field.lats[0],field.lons[0]],[field.lats.at(-1)!,field.lons.at(-1)!]]} opacity={opacity/100} zIndex={300}/>} {!thetaOnly&&contours('height',heightColor)}{!thetaOnly&&!heightOnly&&<>{contours('pressure','#fff')}{contours('humidity','#448ad1',true)}<CanvasOverlay id="synoptic-wind300" opacity={opacity/100} zIndex={690} render={draw}/></>}</>;
}
export function SynopticCompositeLegend({state}:{state:ReturnType<typeof useSynopticComposite>}){if(!state.model)return null;return <details className="unified-source-info"><summary>Farblegende · Theta-E 850 hPa (°C)</summary><div style={{display:'flex',height:16,background:`linear-gradient(to right,${THETAE_BANDS.flatMap((c,i)=>[`${c[1]} ${i/THETAE_BANDS.length*100}%`,`${c[1]} ${(i+1)/THETAE_BANDS.length*100}%`]).join(',')})`}}/><div style={{display:'flex',justifyContent:'space-between',fontSize:12}}>{[-18,6,30,54,78,90].map(v=><span key={v}>{v}°</span>)}</div><p>Theta-E 850 hPa: Farbfläche · Höhenlinien 500 hPa: schwarz, dam · MSL-Isobaren: weiß, hPa · Feuchte 700 hPa: 60 % blau gestrichelt, 80 % blau durchgezogen · Wind 300 hPa: schwarze Pfeile ab 60 kt, Länge und Dicke nach Stärke. Theta-E: 6-Grad-Farbstufen mit dezenten grauen Konturen, Linienbeschriftung alle 12 °C.</p><p>{state.model.label} · {state.model.resolutionKm} km veröffentlichtes Raster · {state.model.license}. Gleicher Lauf und Termin für alle fünf Komponenten.</p></details>}
