import {Fragment,memo,useEffect,useMemo,useState} from 'react';
import {Activity,AlertTriangle,ArrowRight,Clock3,Database,ExternalLink,GitCompareArrows,Info,MapPinned,RefreshCw,ShieldCheck,Wind} from 'lucide-react';
import L from 'leaflet';
import {CircleMarker,MapContainer,Marker,Pane,Polyline,TileLayer,Tooltip,useMap} from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import type {Day,EnsembleDay,Hour,Location,RadarNowcast,Station,ThunderstormNowcast} from './weather';
import {loadModelContours,type ModelContourFrame,type ModelContourResponse} from './CompositeData';
import {buildSynopticIntelligence,frontLabel,loadSynopticAnalysis,type SynopticFrontType,type SynopticIntelligence,type SynopticModelCandidate,type SynopticPoint,type SynopticStationPlot,type SynopticWorkerResponse} from './synoptic';

type Props={location:Location;locationKey:string;hours:Hour[];days:Day[];ensemble:EnsembleDay[];station?:Station|null;radar?:RadarNowcast|null;thunder?:ThunderstormNowcast|null;timezone:string;advancedMode:boolean};
type Bounds={south:number;north:number;west:number;east:number};
const FRONT_COLORS:Record<SynopticFrontType,string>={cold:'#1987ff',warm:'#ee4a55',occlusion:'#b34bd7',trough:'#845c3b',convergence:'#d99a00',none:'#8b95a1'};
const BASEMAP={url:'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',attribution:'&copy; OpenStreetMap-Mitwirkende &copy; CARTO'};
const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value));
const safeTime=(value?:string,timeZone?:string)=>{if(!value)return'–';const date=new Date(value);if(!Number.isFinite(date.getTime()))return'–';return new Intl.DateTimeFormat('de-DE',{timeZone:timeZone||undefined,day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(date)};
const confidenceLabel=(value?:string)=>value==='high'?'hoch':value==='medium'?'mittel':'eingeschränkt';
const lifecycleLabel=(value?:string)=>({detected:'erkannt',approaching:'annähernd',passage:'im Durchgang',departing:'abziehend',verified:'verifiziert',dissipated:'nicht mehr aktiv'} as Record<string,string>)[String(value)]||'–';
const escapeHtml=(value:string)=>value.replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]||char));
const isFiniteNumber=(value:unknown):value is number=>typeof value==='number'&&Number.isFinite(value);
const compassDirection=(value?:number)=>{if(!isFiniteNumber(value))return'–';const labels=['N','NNO','NO','ONO','O','OSO','SO','SSO','S','SSW','SW','WSW','W','WNW','NW','NNW'];return labels[Math.round(((value%360)+360)%360/22.5)%16]};
const signedDirectionChange=(from?:number,to?:number)=>isFiniteNumber(from)&&isFiniteNumber(to)?((((to-from)+540)%360)-180):undefined;
const windTurnText=(shift?:number)=>!isFiniteNumber(shift)?'Richtung unvollständig':Math.abs(shift)<15?'kaum Richtungsänderung':`${Math.abs(Math.round(shift))}° ${shift>0?'rechtsdrehend':'rückdrehend'}`;
function WindArrow({direction}:{direction?:number}){return <i className="synoptic-wind-arrow" style={{transform:`rotate(${isFiniteNumber(direction)?direction:0}deg)`}} aria-hidden="true">↑</i>}

function mapBounds(location:Location,frame:ModelContourFrame|undefined,candidates:SynopticModelCandidate[],stations:SynopticStationPlot[]):Bounds{
 const points:SynopticPoint[]=[[location.latitude,location.longitude],...candidates.flatMap(item=>item.line),...stations.map(item=>[item.lat,item.lon] as SynopticPoint)];
 for(const level of frame?.isobars||[])for(const path of level.paths||[])for(const point of path)if(Math.abs(point[0]-location.latitude)<=6.5&&Math.abs(point[1]-location.longitude)<=9.5)points.push(point);
 let south=Math.min(...points.map(point=>point[0])),north=Math.max(...points.map(point=>point[0])),west=Math.min(...points.map(point=>point[1])),east=Math.max(...points.map(point=>point[1]));
 const latPad=Math.max(1.35,(north-south)*.1),lonPad=Math.max(1.8,(east-west)*.1);south=Math.max(-85,south-latPad);north=Math.min(85,north+latPad);west-=lonPad;east+=lonPad;return{south,north,west,east};
}
function nearestFrame(contours:ModelContourResponse|null,candidateAt?:string){if(!contours?.frames?.length)return undefined;const target=Date.parse(String(candidateAt||''));return contours.frames.slice().sort((a,b)=>Math.abs(Date.parse(a.time)-target)-Math.abs(Date.parse(b.time)-target))[0]}
function inBounds(point:SynopticPoint,bounds:Bounds,pad=.35){return point[0]>=bounds.south-pad&&point[0]<=bounds.north+pad&&point[1]>=bounds.west-pad&&point[1]<=bounds.east+pad}
function destinationPoint(lat:number,lon:number,bearingDeg:number,distanceKm:number):SynopticPoint{const radius=6371,angular=distanceKm/radius,bearing=bearingDeg*Math.PI/180,lat1=lat*Math.PI/180,lon1=lon*Math.PI/180,lat2=Math.asin(Math.sin(lat1)*Math.cos(angular)+Math.cos(lat1)*Math.sin(angular)*Math.cos(bearing)),lon2=lon1+Math.atan2(Math.sin(bearing)*Math.sin(angular)*Math.cos(lat1),Math.cos(angular)-Math.sin(lat1)*Math.sin(lat2));return[lat2*180/Math.PI,((lon2*180/Math.PI+540)%360)-180]}
function interpolateLine(line:SynopticPoint[],count:number){if(line.length<2)return[];const result:{point:SynopticPoint;angle:number;index:number}[]=[];for(let i=0;i<count;i++){const ratio=(i+1)/(count+1),segment=Math.min(line.length-2,Math.floor(ratio*(line.length-1))),local=ratio*(line.length-1)-segment,a=line[segment],b=line[segment+1],lat=a[0]+(b[0]-a[0])*local,lon=a[1]+(b[1]-a[1])*local,angle=Math.atan2(b[1]-a[1],b[0]-a[0])*180/Math.PI;result.push({point:[lat,lon],angle,index:i})}return result}
function frontIcon(type:SynopticFrontType,angle:number,index:number){const variant=type==='occlusion'?(index%2?'warm':'cold'):type;return L.divIcon({className:'synoptic-front-marker',html:`<span class="${variant}" style="--front-color:${FRONT_COLORS[type]};--front-angle:${angle.toFixed(0)}deg"></span>`,iconSize:[16,16],iconAnchor:[8,8]})}
function centerIcon(type:'H'|'T',value:number){return L.divIcon({className:'synoptic-center-marker',html:`<span class="${type==='H'?'high':'low'}"><b>${type}</b><small>${Math.round(value)}</small></span>`,iconSize:[42,42],iconAnchor:[21,21]})}
function labelIcon(text:string,className:string){return L.divIcon({className:`synoptic-map-label ${className}`,html:`<span>${escapeHtml(text)}</span>`,iconSize:[1,1],iconAnchor:[0,0]})}
function stationIcon(station:SynopticStationPlot){const temp=isFiniteNumber(station.temperature)?Math.round(station.temperature):'–',dew=isFiniteNumber(station.dewPoint)?Math.round(station.dewPoint):'–',pressure=isFiniteNumber(station.pressure)?Math.round(station.pressure):'–',rotation=isFiniteNumber(station.windDirection)?station.windDirection:0,length=18+Math.min(12,Math.max(0,Number(station.windSpeedKt||0))*.25);return L.divIcon({className:'synoptic-station-marker',html:`<div class="synoptic-station-plot phase-${station.phase||'before'}"><span class="temp">${temp}</span><span class="dew">${dew}</span><span class="pressure">${pressure}</span><i class="core"></i><i class="wind" style="--wind-angle:${rotation}deg;--wind-length:${length}px"></i></div>`,iconSize:[62,46],iconAnchor:[31,23]})}
function frontDash(type:SynopticFrontType){return type==='trough'?'10 7':type==='convergence'?'4 5':undefined}

function FitSynopticBounds({bounds}:{bounds:Bounds}){const map=useMap();useEffect(()=>{map.fitBounds([[bounds.south,bounds.west],[bounds.north,bounds.east]],{padding:[22,22],maxZoom:7,animate:false})},[map,bounds.south,bounds.north,bounds.west,bounds.east]);return null}

const SynopticMap=memo(function SynopticMap({location,frame,candidates,stations,corridorBearing}:{location:Location;frame?:ModelContourFrame;candidates:SynopticModelCandidate[];stations:SynopticStationPlot[];corridorBearing?:number}){
 const bounds=useMemo(()=>mapBounds(location,frame,candidates,stations),[location.latitude,location.longitude,frame,candidates,stations]),corridorEnd=useMemo(()=>isFiniteNumber(corridorBearing)?destinationPoint(location.latitude,location.longitude,corridorBearing,Math.min(300,Math.max(130,(stations.at(-1)?.distanceKm||220)))):null,[location.latitude,location.longitude,corridorBearing,stations]);
 const visibleIsobars=useMemo(()=>(frame?.isobars||[]).map(level=>({...level,paths:(level.paths||[]).filter(path=>path.some(point=>inBounds(point,bounds)))})).filter(level=>level.paths.length),[frame,bounds]);
 const visibleCenters=useMemo(()=>(frame?.centers||[]).filter(center=>inBounds([center.lat,center.lon],bounds,.7)),[frame,bounds]);
 return <div className="synoptic-map-wrap">
  <MapContainer className="synoptic-leaflet-map" center={[location.latitude,location.longitude]} zoom={5} minZoom={3} maxZoom={11} scrollWheelZoom={false} zoomControl attributionControl>
   <TileLayer url={BASEMAP.url} attribution={BASEMAP.attribution}/><FitSynopticBounds bounds={bounds}/>
   <Pane name="synoptic-isobars" style={{zIndex:430}}>{visibleIsobars.map(level=><Fragment key={`iso-${level.level}`}>{level.paths.map((path,index)=><Fragment key={index}><Polyline positions={path as [number,number][]} pathOptions={{color:'#ffffff',weight:5.4,opacity:.98,interactive:false,lineCap:'round',lineJoin:'round'}}/><Polyline positions={path as [number,number][]} pathOptions={{color:'#102b40',weight:2.35,opacity:.96,interactive:false,lineCap:'round',lineJoin:'round'}}/></Fragment>)}{level.paths[0]?.length?<Marker interactive={false} position={level.paths[0][Math.floor(level.paths[0].length/2)] as [number,number]} icon={labelIcon(`${Math.round(level.level)} hPa`,'isobar')}/>:null}</Fragment>)}</Pane>
   <Pane name="synoptic-centers" style={{zIndex:470}}>{visibleCenters.map((center,index)=><Marker key={`${center.type}-${index}`} position={[center.lat,center.lon]} icon={centerIcon(center.type,center.value)}><Tooltip>{center.type==='H'?'Hoch':'Tief'}druckzentrum · {center.value.toFixed(0)} hPa</Tooltip></Marker>)}</Pane>
   {corridorEnd&&isFiniteNumber(corridorBearing)?<Pane name="synoptic-corridor" style={{zIndex:445}}><Polyline positions={[[location.latitude,location.longitude],corridorEnd]} pathOptions={{color:'#4a7d97',weight:3,opacity:.72,dashArray:'6 7'}}/><Marker position={corridorEnd} icon={labelIcon(`→ zur Front ${Math.round(corridorBearing)}°`,'corridor')} interactive={false}/></Pane>:null}
   <Pane name="synoptic-fronts" style={{zIndex:520}}>{candidates.map(candidate=><Fragment key={candidate.modelId}><Polyline positions={candidate.line as [number,number][]} pathOptions={{color:FRONT_COLORS[candidate.type],weight:5,opacity:clamp(.58+candidate.score/220,.66,1),dashArray:frontDash(candidate.type),lineCap:'round'}}><Tooltip sticky>{candidate.modelLabel}: {frontLabel(candidate.type)} · {candidate.score}/100</Tooltip></Polyline>{interpolateLine(candidate.line,Math.min(7,Math.max(3,candidate.line.length*2))).map(item=><Marker key={`${candidate.modelId}-${item.index}`} position={item.point} icon={frontIcon(candidate.type,item.angle,item.index)} interactive={false}/>)}{candidate.line[Math.floor(candidate.line.length/2)]?<Marker position={candidate.line[Math.floor(candidate.line.length/2)]} icon={labelIcon(candidate.modelLabel.replace('DWD ','').replace('NOAA ',''),'front')} interactive={false}/>:null}</Fragment>)}</Pane>
   <Pane name="synoptic-stations" style={{zIndex:560}}>{stations.slice(0,12).map(station=><Marker key={station.id} position={[station.lat,station.lon]} icon={stationIcon(station)}><Tooltip direction="top" offset={[0,-18]}><strong>{station.name}</strong><br/>{station.provider} · {Math.round(station.distanceKm)} km<br/>{isFiniteNumber(station.temperature)?`${station.temperature.toFixed(1)} °C`:''}{isFiniteNumber(station.dewPoint)?` · Td ${station.dewPoint.toFixed(1)} °C`:''}{isFiniteNumber(station.pressure)?` · ${Math.round(station.pressure)} hPa`:''}</Tooltip></Marker>)}</Pane>
   <CircleMarker center={[location.latitude,location.longitude]} radius={7} pathOptions={{color:'#087cef',weight:3,fillColor:'#fff',fillOpacity:1}}><Tooltip permanent direction="right" offset={[10,0]} className="synoptic-site-label">{location.name}</Tooltip></CircleMarker>
  </MapContainer>
  <div className="synoptic-map-legend"><span><i className="basemap"/>Kartengrundlage</span><span><i className="isobar"/>Isobaren</span><span><i className="center"/>H/T</span><span><i className="station"/>Stationsplot</span><span><i className="front"/>MID-Front</span><span><i className="corridor"/>zur Front</span></div>
 </div>
});

function SourceStrip({worker,contours,timezone}:{worker:SynopticWorkerResponse|null;contours:ModelContourResponse|null;timezone:string}){const sources=[...(worker?.sources||[]),...(contours?[{label:`${contours.provider||'Open-Meteo'} · ${contours.model||'Modellkonturen'}`,kind:'model' as const,dataTime:contours.frames?.[0]?.time,checkedAt:contours.checkedAt,detail:contours.resolutionNote||'MSLP-Isobaren und Druckzentren'}]:[])];return <div className="synoptic-sources"><Database size={15}/><div><strong>Datenstand und Quellen</strong><span>{sources.length?sources.map(source=>`${source.label}${source.dataTime?` · ${safeTime(source.dataTime,timezone)}`:''}`).join(' · '):'Lokale Best-Match-Ersatzanalyse; externe Synoptikdaten werden geladen.'}</span></div></div>}
function PhaseCards({intelligence}:{intelligence:SynopticIntelligence}){const before=intelligence.phases[0],after=intelligence.phases[2],shift=signedDirectionChange(before?.windDirection,after?.windDirection),shiftLevel=isFiniteNumber(shift)&&Math.abs(shift)>=60?'marked':isFiniteNumber(shift)&&Math.abs(shift)>=25?'noticeable':'slight';return <div className="synoptic-phase-overview"><div className="synoptic-phase-flow">{intelligence.phases.map((phase,index)=><article key={phase.key} className={`synoptic-phase-node ${phase.key}`} title={phase.summary}><header><span>{index+1}</span><div><strong>{phase.title}</strong><small>{phase.period}</small></div></header><div className="synoptic-phase-metrics"><span><b>{isFiniteNumber(phase.temperature)?`${Math.round(phase.temperature)}°`:'–'}</b>T</span><span><b>{isFiniteNumber(phase.pressure)?Math.round(phase.pressure):'–'}</b>hPa</span><span className="wind"><b><WindArrow direction={phase.windDirection}/>{isFiniteNumber(phase.windKt)?Math.round(phase.windKt):'–'}</b><small>{compassDirection(phase.windDirection)} · kt</small></span><span><b>{isFiniteNumber(phase.gustKt)?Math.round(phase.gustKt):'–'}</b>Böe kt</span><span><b>{isFiniteNumber(phase.rainProbability)?`${Math.round(phase.rainProbability)}%`:'–'}</b>Regen</span></div><div className="synoptic-phase-bars" aria-label="Grauer Balken: Böengeschwindigkeit. Blauer Balken: Regenwahrscheinlichkeit."><span className="gust"><em>Böen</em><i><b style={{width:`${clamp(Number(phase.gustKt||0)*1.35,4,100)}%`}}/></i><strong>{isFiniteNumber(phase.gustKt)?`${Math.round(phase.gustKt)} kt`:'–'}</strong></span><span className="rain"><em>Regen</em><i><b style={{width:`${clamp(Number(phase.rainProbability||0),4,100)}%`}}/></i><strong>{isFiniteNumber(phase.rainProbability)?`${Math.round(phase.rainProbability)} %`:'–'}</strong></span></div>{index<2?<ArrowRight className="synoptic-phase-arrow" size={18}/>:null}</article>)}</div><div className={`synoptic-wind-transition ${shiftLevel}`}><Wind size={17}/><span><small>Windrichtung vor → nach dem Frontdurchgang</small><b><WindArrow direction={before?.windDirection}/>{compassDirection(before?.windDirection)} {isFiniteNumber(before?.windDirection)?`${Math.round(before.windDirection)}°`:'–'} <ArrowRight size={14}/> <WindArrow direction={after?.windDirection}/>{compassDirection(after?.windDirection)} {isFiniteNumber(after?.windDirection)?`${Math.round(after.windDirection)}°`:'–'}</b></span><em>{windTurnText(shift)}</em></div></div>}
function ImpactStrip({intelligence}:{intelligence:SynopticIntelligence}){return <div className="synoptic-impact-strip">{intelligence.impacts.map(impact=><article key={impact.activity} className={`synoptic-impact-chip ${impact.level}`} title={[impact.summary,...impact.actions].join(' · ')}><Activity size={15}/><div><strong>{impact.label}</strong><small>{impact.summary}</small></div><span>{impact.level==='high'?'deutlich':impact.level==='medium'?'beachten':'gering'}</span></article>)}</div>}
function ModelAgreementGraphic({worker,event,timezone,candidates}:{worker:SynopticWorkerResponse|null;event:SynopticIntelligence['event'];timezone:string;candidates:SynopticModelCandidate[]}){return <><div className="synoptic-model-lanes">{candidates.map(candidate=><div key={candidate.modelId}><span className="model-dot" style={{background:FRONT_COLORS[candidate.type]}}/><strong>{candidate.modelLabel}</strong><small>{frontLabel(candidate.type)} · {safeTime(candidate.arrivalAt,timezone)}</small><div><i style={{width:`${clamp(candidate.score,4,100)}%`,background:FRONT_COLORS[candidate.type]}}/></div><b>{candidate.score}</b></div>)}</div><div className="synoptic-timing-graphic"><span><small>Modell</small><b>{safeTime(worker?.timing.modelMedianAt||event?.predictedAt,timezone)}</b></span><ArrowRight size={19}/><span><small>assimiliert</small><b>{safeTime(worker?.timing.assimilatedAt||event?.predictedAt,timezone)}</b></span><div><i className="observation"/><small>Beob. {worker?.timing.observationAdjustmentMinutes||0} min</small><i className="radar"/><small>Radar {worker?.timing.radarAdjustmentMinutes||0} min</small></div></div></>}
function CorridorGraphic({worker,stations}:{worker:SynopticWorkerResponse|null;stations:SynopticStationPlot[]}){const length=Math.max(1,worker?.corridor.lengthKm||420),bearing=worker?.corridor.bearingDeg;return <div className="synoptic-corridor-graphic"><header><span><MapPinned size={15}/>Standort</span><b>{isFiniteNumber(bearing)?`zur Front ${Math.round(bearing)}°`:'Richtung noch unsicher'} →</b></header><div className="synoptic-corridor-axis"><i className="site"/>{stations.slice(0,10).map(station=><i key={station.id} className={`station phase-${station.phase||'before'}`} style={{left:`${clamp(station.distanceKm/length*100,5,96)}%`}} title={`${station.name} · ${Math.round(station.distanceKm)} km · ${isFiniteNumber(station.temperature)?station.temperature.toFixed(1)+' °C':''}`}/>)}</div><div className="synoptic-station-chips">{stations.slice(0,6).map(item=><span key={item.id}><b>{item.name}</b><small>{Math.round(item.distanceKm)} km · {isFiniteNumber(item.temperature)?`${item.temperature.toFixed(1)}°`:''}{isFiniteNumber(item.pressure)?` · ${Math.round(item.pressure)} hPa`:''}</small></span>)}</div></div>}
function UncertaintyBudget({intelligence}:{intelligence:SynopticIntelligence}){return <section className="synoptic-subpanel"><div className="synoptic-subhead"><GitCompareArrows size={17}/><div><strong>Unsicherheitsbudget nach Ursache</strong><small>Ursachen statt unklarer Gesamtzahl.</small></div></div><div className="synoptic-budget">{intelligence.uncertainty.map(cause=><div key={cause.key} title={cause.detail}><header><span>{cause.label}</span><b>{cause.share}%</b></header><div><i style={{width:`${cause.share}%`}}/></div></div>)}</div></section>}

function SynopticPanel({location,locationKey,hours,days,ensemble,station,radar,thunder,timezone,advancedMode}:Props){
 const[worker,setWorker]=useState<SynopticWorkerResponse|null>(null),[contours,setContours]=useState<ModelContourResponse|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');Promise.allSettled([loadSynopticAnalysis(location,controller.signal),loadModelContours(location.latitude,location.longitude,controller.signal)]).then(results=>{if(controller.signal.aborted)return;const synoptic=results[0],model=results[1];if(synoptic.status==='fulfilled')setWorker(synoptic.value);else setError(synoptic.reason instanceof Error?synoptic.reason.message:String(synoptic.reason));if(model.status==='fulfilled')setContours(model.value)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[location.latitude,location.longitude,location.country_code]);
 const intelligence=useMemo(()=>buildSynopticIntelligence({location,locationKey,hours,days,ensemble,station,radar,thunder,worker}),[location.latitude,location.longitude,locationKey,hours,days,ensemble,station?.timestamp,radar?.observedAt,radar?.arrivalMinutes,thunder?.observedAt,worker]),event=intelligence.event,primary=useMemo(()=>(worker?.candidates||[]).slice().sort((a,b)=>b.score-a.score)[0],[worker]),frame=useMemo(()=>nearestFrame(contours,event?.predictedAt),[contours,event?.predictedAt]),stations=worker?.corridor.stations||[],candidates=(worker?.candidates?.length?worker.candidates:(primary?[primary]:[]));
 return <section className="synoptic-panel">
  <div className="synoptic-change-card"><div className="synoptic-change-icon"><MapPinned size={23}/></div><div className="synoptic-change-main"><small>Nächster markanter Wetterwechsel</small><h3>{event?frontLabel(event.type):'Kein markanter Frontdurchgang erkannt'}</h3><p>{intelligence.nextChangeSummary}</p></div><div className="synoptic-change-meta"><span className={`confidence ${event?.confidence||'low'}`}>Sicherheit {confidenceLabel(event?.confidence)}</span><span><Clock3 size={14}/>{event?lifecycleLabel(event.lifecycle):'ruhig'}</span>{loading?<span><RefreshCw className="spin" size={14}/>Synoptikdaten</span>:null}</div></div>
  {error?<div className="synoptic-notice"><AlertTriangle size={16}/><span>Externe Synoptikanalyse derzeit eingeschränkt: {error}. MID verwendet vorübergehend den lokalen Best-Match-Wetterwechsel.</span></div>:null}
  {event?<PhaseCards intelligence={intelligence}/>:null}{event?<ImpactStrip intelligence={intelligence}/>:null}
  {advancedMode?<><div className="synoptic-reference-grid"><section className="synoptic-subpanel official-analysis"><div className="synoptic-subhead"><ShieldCheck size={17}/><div><strong>Amtliche DWD-Bodenanalyse</strong><small>Unveränderte amtliche Referenz.</small></div></div>{worker?.officialAnalysis.available&&worker.officialAnalysis.imageUrl?<a href={worker.officialAnalysis.sourcePage} target="_blank" rel="noreferrer" className="official-analysis-image"><img src={worker.officialAnalysis.imageUrl} alt="Amtliche DWD-Bodenanalyse mit Fronten, Isobaren, Druckzentren und Stationsbeobachtungen" loading="lazy"/><span><ExternalLink size={14}/>DWD-Originalseite öffnen</span></a>:<div className="synoptic-empty"><Info size={17}/><span>{worker?.officialAnalysis.error||'Die amtliche Karte wird vom Worker ermittelt. Bis dahin bleibt die objektive MID-Analyse sichtbar.'}</span></div>}<footer>Datenstand: {safeTime(worker?.officialAnalysis.nominalTime||worker?.officialAnalysis.publishedAt,timezone)} · Quelle: Deutscher Wetterdienst · {worker?.officialAnalysis.license||'DWD Open Data'}</footer></section><section className="synoptic-subpanel synoptic-map-panel"><div className="synoptic-subhead"><Wind size={17}/><div><strong>Interaktive MID-Synoptik</strong><small>Kartengrundlage, Isobaren, H/T, lesbare Stationsplots und objektive Modellfronten.</small></div></div><SynopticMap location={location} frame={frame} candidates={candidates} stations={stations} corridorBearing={worker?.corridor.bearingDeg}/><footer>{frame?`Modellgültigkeit ${safeTime(frame.time,timezone)} · ${contours?.model||'Modellkonturen'}`:'Konturen werden geladen.'} · Fronten: „MID-Frontkandidat · objektive Modellanalyse“</footer></section></div>
   <div className="synoptic-diagnostics-grid"><section className="synoptic-subpanel"><div className="synoptic-subhead"><GitCompareArrows size={17}/><div><strong>Modellübereinstimmung & Timing</strong><small>Ein Blick statt langer Modelltexte.</small></div></div><ModelAgreementGraphic worker={worker} event={event} timezone={timezone} candidates={candidates}/></section><section className="synoptic-subpanel"><div className="synoptic-subhead"><MapPinned size={17}/><div><strong>Beobachtungskorridor stromaufwärts · zur Front</strong><small>Stromaufwärts heißt: vom Standort in Richtung der annähernden Front – bei Warmfronten ausdrücklich zur Warmfront hin.</small></div></div><CorridorGraphic worker={worker} stations={stations}/><footer>{worker?.corridor.summary||'Der Korridor wird aus der Herkunftsrichtung der frontführenden Strömung abgeleitet.'}</footer></section></div>
   <UncertaintyBudget intelligence={intelligence}/><div className="synoptic-diagnostics-grid"><section className="synoptic-subpanel"><div className="synoptic-subhead"><GitCompareArrows size={17}/><div><strong>Erklärbare Kausalkette</strong><small>Nur die entscheidenden Schritte.</small></div></div><ol className="synoptic-causal">{intelligence.causalChain.slice(0,6).map((item,index)=><li key={`${index}-${item}`}><span>{index+1}</span><p>{item}</p></li>)}</ol></section><section className="synoptic-subpanel"><div className="synoptic-subhead"><Database size={17}/><div><strong>Lokales Analogarchiv und Ereignisverifikation</strong><small>Lebenszyklus und lokale Vergleichsfälle.</small></div></div><p>{intelligence.verification.summary}</p><div className="synoptic-analogues">{intelligence.analogues.length?intelligence.analogues.slice(0,4).map(item=><article key={item.id}><strong>{safeTime(item.date,timezone)}</strong><span>{frontLabel(item.type)} · {item.similarity}% ähnlich</span></article>):<div className="synoptic-empty"><Info size={16}/><span>Noch keine verifizierten lokalen Analogfälle dieses Typs.</span></div>}</div>{event?<div className="synoptic-event-line"><span>Objekt <b>{event.id.split(':').slice(-2).join(':')}</b></span><span>Status <b>{lifecycleLabel(event.lifecycle)}</b></span><span>Erkannt <b>{safeTime(event.firstSeen,timezone)}</b></span></div>:null}</section></div></>:null}
  <SourceStrip worker={worker} contours={contours} timezone={timezone}/>
 </section>
}
export default memo(SynopticPanel);
