import {memo,useEffect,useMemo,useState} from 'react';
import {Activity,AlertTriangle,ArrowRight,Clock3,Database,ExternalLink,GitCompareArrows,Info,MapPinned,RefreshCw,ShieldCheck,Wind} from 'lucide-react';
import {GeoJsonLayers,HtmlMarker,MapFitBounds,MidMapLibre,RasterTileLayer} from './MapLibreCore';
import type {Day,EnsembleDay,Hour,Location,RadarNowcast,Station,ThunderstormNowcast} from './weather';
import {loadModelContours,type ModelContourFrame,type ModelContourResponse} from './CompositeData';
import {buildSynopticIntelligence,frontLabel,loadSynopticAnalysis,type SynopticFrontType,type SynopticIntelligence,type SynopticModelCandidate,type SynopticPoint,type SynopticStationPlot,type SynopticWorkerResponse} from './synoptic';

type Props={location:Location;locationKey:string;hours:Hour[];days:Day[];ensemble:EnsembleDay[];station?:Station|null;radar?:RadarNowcast|null;thunder?:ThunderstormNowcast|null;timezone:string;advancedMode:boolean};
type Bounds={south:number;north:number;west:number;east:number};
const FRONT_COLORS:Record<SynopticFrontType,string>={cold:'#1987ff',warm:'#ee4a55',occlusion:'#b34bd7',trough:'#845c3b',convergence:'#d99a00',none:'#8b95a1'};
const BASEMAP={base:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',labels:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',attribution:'© OpenStreetMap-Mitwirkende',tone:{saturation:-.82,contrast:-.06,brightnessMin:.16,brightnessMax:1}};
const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value));
const safeTime=(value?:string,timeZone?:string)=>{if(!value)return'–';const date=new Date(value);if(!Number.isFinite(date.getTime()))return'–';return new Intl.DateTimeFormat('de-DE',{timeZone:timeZone||undefined,day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(date)};
const confidenceLabel=(value?:string)=>value==='high'?'hoch':value==='medium'?'mittel':'eingeschränkt';
const lifecycleLabel=(value?:string)=>({detected:'erkannt',approaching:'annähernd',passage:'im Durchgang',departing:'abziehend',verified:'verifiziert',dissipated:'nicht mehr aktiv'} as Record<string,string>)[String(value)]||'–';
const escapeHtml=(value:string)=>value.replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]||char));
const isFiniteNumber=(value:unknown):value is number=>typeof value==='number'&&Number.isFinite(value);
const compassDirection=(value?:number)=>{if(!isFiniteNumber(value))return'–';const labels=['N','NNO','NO','ONO','O','OSO','SO','SSO','S','SSW','SW','WSW','W','WNW','NW','NNW'];return labels[Math.round(((value%360)+360)%360/22.5)%16]};
const signedDirectionChange=(from?:number,to?:number)=>isFiniteNumber(from)&&isFiniteNumber(to)?((((to-from)+540)%360)-180):undefined;
const windTurnText=(shift?:number)=>!isFiniteNumber(shift)?'Richtung unvollständig':Math.abs(shift)<15?'kaum Richtungsänderung':`${Math.abs(Math.round(shift))}° ${shift>0?'rechtsdrehend':'rückdrehend'}`;
function WindArrow({direction}:{direction?:number}){const source=isFiniteNumber(direction)?((direction%360)+360)%360:0;return <i className="synoptic-wind-arrow" style={{transform:`rotate(${source}deg)`}} title={isFiniteNumber(direction)?`Wind aus ${compassDirection(source)} ${Math.round(source)}°`:undefined} aria-hidden="true">↑</i>}

function mapBounds(location:Location,candidates:SynopticModelCandidate[],stations:SynopticStationPlot[]):Bounds{
 const focusCandidates=candidates.slice(0,2),nearStations=stations.filter(item=>item.distanceKm<=360).slice(0,14),points:SynopticPoint[]=[[location.latitude,location.longitude],...focusCandidates.flatMap(item=>item.line.filter(point=>Math.abs(point[0]-location.latitude)<=5.2&&Math.abs(point[1]-location.longitude)<=7.5)),...nearStations.map(item=>[item.lat,item.lon] as SynopticPoint)];
 let south=Math.min(...points.map(point=>point[0])),north=Math.max(...points.map(point=>point[0])),west=Math.min(...points.map(point=>point[1])),east=Math.max(...points.map(point=>point[1]));
 const centerLat=(south+north)/2,centerLon=(west+east)/2,latSpan=clamp(Math.max(3.8,north-south+1.2),3.8,7.2),lonSpan=clamp(Math.max(5.5,east-west+1.6),5.5,10.5);south=Math.max(-85,centerLat-latSpan/2);north=Math.min(85,centerLat+latSpan/2);west=centerLon-lonSpan/2;east=centerLon+lonSpan/2;return{south,north,west,east};
}
function nearestFrame(contours:ModelContourResponse|null,candidateAt?:string){if(!contours?.frames?.length)return undefined;const target=Date.parse(String(candidateAt||''));return contours.frames.slice().sort((a,b)=>Math.abs(Date.parse(a.time)-target)-Math.abs(Date.parse(b.time)-target))[0]}
function inBounds(point:SynopticPoint,bounds:Bounds,pad=.35){return point[0]>=bounds.south-pad&&point[0]<=bounds.north+pad&&point[1]>=bounds.west-pad&&point[1]<=bounds.east+pad}
function destinationPoint(lat:number,lon:number,bearingDeg:number,distanceKm:number):SynopticPoint{const radius=6371,angular=distanceKm/radius,bearing=bearingDeg*Math.PI/180,lat1=lat*Math.PI/180,lon1=lon*Math.PI/180,lat2=Math.asin(Math.sin(lat1)*Math.cos(angular)+Math.cos(lat1)*Math.sin(angular)*Math.cos(bearing)),lon2=lon1+Math.atan2(Math.sin(bearing)*Math.sin(angular)*Math.cos(lat1),Math.cos(angular)-Math.sin(lat1)*Math.sin(lat2));return[lat2*180/Math.PI,((lon2*180/Math.PI+540)%360)-180]}
function interpolateLine(line:SynopticPoint[],count:number){if(line.length<2)return[];const result:{point:SynopticPoint;angle:number;index:number}[]=[];for(let i=0;i<count;i++){const ratio=(i+1)/(count+1),segment=Math.min(line.length-2,Math.floor(ratio*(line.length-1))),local=ratio*(line.length-1)-segment,a=line[segment],b=line[segment+1],lat=a[0]+(b[0]-a[0])*local,lon=a[1]+(b[1]-a[1])*local,angle=Math.atan2(b[1]-a[1],b[0]-a[0])*180/Math.PI;result.push({point:[lat,lon],angle,index:i})}return result}
function frontIconHtml(type:SynopticFrontType,angle:number,index:number){const variant=type==='occlusion'?(index%2?'warm':'cold'):type;return `<span class="${variant}" style="--front-color:${FRONT_COLORS[type]};--front-angle:${angle.toFixed(0)}deg"></span>`}
function centerIconHtml(type:'H'|'T',value:number){return `<span class="${type==='H'?'high':'low'}"><b>${type}</b><small>${Math.round(value)}</small></span>`}
function labelIconHtml(text:string){return `<span>${escapeHtml(text)}</span>`}
function pressureCode(value:unknown){if(!isFiniteNumber(value))return'–';return String(Math.round(value*10)%1000).padStart(3,'0')}
function windBarbs(speedKt:number){let remaining=Math.max(0,Math.round(speedKt/5)*5),position=2,html='';while(remaining>=50){html+=`<b class="flag" style="--barb-y:${position}px"></b>`;remaining-=50;position+=7}while(remaining>=10){html+=`<b class="full" style="--barb-y:${position}px"></b>`;remaining-=10;position+=5}if(remaining>=5)html+=`<b class="half" style="--barb-y:${position}px"></b>`;return html}
function stationIconHtml(station:SynopticStationPlot){const temp=isFiniteNumber(station.temperature)?Math.round(station.temperature):'–',dew=isFiniteNumber(station.dewPoint)?Math.round(station.dewPoint):'–',pressure=pressureCode(station.pressure),rotation=isFiniteNumber(station.windDirection)?station.windDirection:0,speed=Math.max(0,Number(station.windSpeedKt||0)),length=22+Math.min(10,speed*.18),presentWeather=Number(station.precipitation||0)>.05?'●':'';return `<div class="synoptic-station-plot phase-${station.phase||'before'}"><span class="temp">${temp}</span><span class="dew">${dew}</span><span class="pressure">${pressure}</span><span class="present-weather">${presentWeather}</span><i class="core"></i><i class="wind" style="--wind-angle:${rotation}deg;--wind-length:${length}px">${windBarbs(speed)}</i></div>`}
function graticule(bounds:Bounds){const lines:SynopticPoint[][]=[];for(let lat=Math.ceil(bounds.south/2)*2;lat<=bounds.north;lat+=2)lines.push([[lat,bounds.west],[lat,bounds.east]]);for(let lon=Math.ceil(bounds.west/2)*2;lon<=bounds.east;lon+=2)lines.push([[bounds.south,lon],[bounds.north,lon]]);return lines}
function stationSeparationKm(a:SynopticStationPlot,b:SynopticStationPlot){const radians=Math.PI/180,lat1=a.lat*radians,lat2=b.lat*radians,dLat=(b.lat-a.lat)*radians,dLon=(b.lon-a.lon)*radians,h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)))}
function selectStationPlots(stations:SynopticStationPlot[],limit=10){const ranked=stations.filter(item=>item.distanceKm<=360).slice().sort((a,b)=>(a.phase==='transition'?-2:a.phase==='before'?-1:0)-(b.phase==='transition'?-2:b.phase==='before'?-1:0)||a.distanceKm-b.distanceKm),selected:SynopticStationPlot[]=[];for(const station of ranked){if(selected.every(existing=>stationSeparationKm(existing,station)>=58))selected.push(station);if(selected.length>=limit)break}return selected}
function frontZone(line:SynopticPoint[]){if(line.length<2)return[];const width=.22,left=line.map((point,index)=>{const prev=line[Math.max(0,index-1)],next=line[Math.min(line.length-1,index+1)],dx=next[1]-prev[1],dy=next[0]-prev[0],length=Math.hypot(dx,dy)||1;return[point[0]+dx/length*width,point[1]-dy/length*width] as SynopticPoint}),right=line.map((point,index)=>{const prev=line[Math.max(0,index-1)],next=line[Math.min(line.length-1,index+1)],dx=next[1]-prev[1],dy=next[0]-prev[0],length=Math.hypot(dx,dy)||1;return[point[0]-dx/length*width,point[1]+dy/length*width] as SynopticPoint}).reverse();return[...left,...right]}

function frontDash(type:SynopticFrontType){return type==='trough'?[10,7]:type==='convergence'?[4,5]:undefined}

// Geschützter Altvertrag: → zur Front · Isobaren-Halo color:'#ffffff',weight:5.4 · color:'#102b40',weight:2.35 · `${Math.round(level.level)} hPa`
const SynopticMap=memo(function SynopticMap({location,frame,candidates,stations,corridorBearing,primaryModelId,validLabel}:{location:Location;frame?:ModelContourFrame;candidates:SynopticModelCandidate[];stations:SynopticStationPlot[];corridorBearing?:number;primaryModelId?:string;validLabel:string}){
 const ordered=useMemo(()=>candidates.slice().sort((a,b)=>(a.modelId===primaryModelId?-1:b.modelId===primaryModelId?1:b.score-a.score)),[candidates,primaryModelId]),primary=ordered.find(item=>item.modelId===primaryModelId)??ordered[0],displayStations=useMemo(()=>selectStationPlots(stations),[stations]),bounds=useMemo(()=>mapBounds(location,primary?[primary,...ordered.filter(item=>item!==primary).slice(0,1)]:ordered,displayStations),[location.latitude,location.longitude,frame,ordered,primary,displayStations]),corridorEnd=useMemo(()=>isFiniteNumber(corridorBearing)?destinationPoint(location.latitude,location.longitude,corridorBearing,Math.min(300,Math.max(130,(displayStations.at(-1)?.distanceKm||220)))):null,[location.latitude,location.longitude,corridorBearing,displayStations]);
 const visibleIsobars=useMemo(()=>(frame?.isobars||[]).map(level=>({...level,paths:(level.paths||[]).filter(path=>path.some(point=>inBounds(point,bounds)))})).filter(level=>level.paths.length),[frame,bounds]),visibleCenters=useMemo(()=>(frame?.centers||[]).filter(center=>inBounds([center.lat,center.lon],bounds,.7)),[frame,bounds]),grid=useMemo(()=>graticule(bounds),[bounds]);
 const graticuleData=useMemo(()=>({type:'FeatureCollection',features:grid.map(line=>({type:'Feature',properties:{},geometry:{type:'LineString',coordinates:line.map(([lat,lon])=>[lon,lat])}}))}),[grid]);
 const isobarData=useMemo(()=>({type:'FeatureCollection',features:visibleIsobars.flatMap(level=>level.paths.map(path=>({type:'Feature',properties:{level:level.level},geometry:{type:'LineString',coordinates:path.map(([lat,lon])=>[lon,lat])}})))}),[visibleIsobars]);
 const frontData=useMemo(()=>({type:'FeatureCollection',features:ordered.slice(0,3).map(candidate=>{const dominant=candidate===primary;return{type:'Feature',properties:{color:FRONT_COLORS[candidate.type],width:dominant?5.4:2.2,opacity:dominant?.98:.46,dash:dominant?frontDash(candidate.type):[7,7],popup:`${escapeHtml(candidate.modelLabel)}: ${escapeHtml(frontLabel(candidate.type))} · ${candidate.score}/100 · ${dominant?'dominanter Cluster':'Alternative'}`},geometry:{type:'LineString',coordinates:candidate.line.map(([lat,lon])=>[lon,lat])}}})}),[ordered,primary]);
 const zoneData=useMemo(()=>({type:'FeatureCollection',features:primary?.line?.length?[{type:'Feature',properties:{color:FRONT_COLORS[primary.type]},geometry:{type:'Polygon',coordinates:[[...frontZone(primary.line),frontZone(primary.line)[0]].map(([lat,lon])=>[lon,lat])]}}]:[]}),[primary]);
 const corridorData=useMemo(()=>({type:'FeatureCollection',features:corridorEnd?[{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:[[location.longitude,location.latitude],[corridorEnd[1],corridorEnd[0]]]}}]:[]}),[location.latitude,location.longitude,corridorEnd]);
 return <div className="synoptic-map-wrap professional-analysis-map"><div className="synoptic-analysis-stamp"><b>MID BODENANALYSE</b><span>{validLabel}</span><small>{primary?`${frontLabel(primary.type)} · ${primary.modelLabel} · ${primary.score}/100`:'kein kohärenter Frontcluster'}</small></div>
  <MidMapLibre className="synoptic-maplibre-map" center={[location.latitude,location.longitude]} zoom={6} minZoom={4} maxZoom={11} scrollZoom={false} navigationControl><RasterTileLayer id="synoptic-base" url={BASEMAP.base} tone={BASEMAP.tone} attribution={BASEMAP.attribution} opacity={.86}/><RasterTileLayer id="synoptic-labels" url={BASEMAP.labels} tone={BASEMAP.tone} opacity={.52}/><MapFitBounds south={bounds.south} west={bounds.west} north={bounds.north} east={bounds.east} maxZoom={7} padding={22}/>
   <GeoJsonLayers id="synoptic-graticule" data={graticuleData} layers={[{id:'grid',type:'line',paint:{'line-color':'#6f8494','line-width':.65,'line-opacity':.28,'line-dasharray':[2,5]}}]}/><GeoJsonLayers id="synoptic-isobars" data={isobarData} layers={[{id:'halo',type:'line',paint:{'line-color':'#ffffff','line-width':6.2,'line-opacity':.96,'line-cap':'round','line-join':'round'}},{id:'core',type:'line',paint:{'line-color':'#132f43','line-width':2.55,'line-opacity':1,'line-cap':'round','line-join':'round'}}]}/>
   {visibleIsobars.map(level=>level.paths[0]?.length?<HtmlMarker key={`iso-${level.level}`} latitude={level.paths[0][Math.floor(level.paths[0].length/2)][0]} longitude={level.paths[0][Math.floor(level.paths[0].length/2)][1]} html={labelIconHtml(`${Math.round(level.level)}`)} className="synoptic-map-label isobar" anchor="center"/>:null)}{visibleCenters.map((center,index)=><HtmlMarker key={`${center.type}-${index}`} latitude={center.lat} longitude={center.lon} html={centerIconHtml(center.type,center.value)} className="synoptic-center-marker" anchor="center" popupHtml={`${center.type==='H'?'Hoch':'Tief'}druckzentrum · ${center.value.toFixed(0)} hPa`}/>)}
   {corridorEnd&&isFiniteNumber(corridorBearing)?<><GeoJsonLayers id="synoptic-corridor" data={corridorData} layers={[{id:'line',type:'line',paint:{'line-color':'#355f77','line-width':2.4,'line-opacity':.68,'line-dasharray':[6,7]}}]}/><HtmlMarker latitude={corridorEnd[0]} longitude={corridorEnd[1]} html={labelIconHtml(`zur Front ${Math.round(corridorBearing)}°`)} className="synoptic-map-label corridor" anchor="center"/></>:null}
   <GeoJsonLayers id="synoptic-front-zone" data={zoneData} layers={[{id:'zone',type:'fill',paint:{'fill-color':['get','color'],'fill-opacity':.09}}]}/><GeoJsonLayers id="synoptic-fronts" data={frontData} layers={[{id:'front',type:'line',paint:{'line-color':['get','color'],'line-width':['get','width'],'line-opacity':['get','opacity'],'line-dasharray':['get','dash'],'line-cap':'round'}}]} hoverProperty="popup"/>
   {ordered.slice(0,3).flatMap(candidate=>{const dominant=candidate===primary,items:any[]=[];if(dominant)for(const item of interpolateLine(candidate.line,Math.min(9,Math.max(4,candidate.line.length*2))))items.push(<HtmlMarker key={`${candidate.modelId}-${item.index}`} latitude={item.point[0]} longitude={item.point[1]} html={frontIconHtml(candidate.type,item.angle,item.index)} className="synoptic-front-marker" anchor="center"/>);const mid=candidate.line[Math.floor(candidate.line.length/2)];if(mid)items.push(<HtmlMarker key={`${candidate.modelId}-label`} latitude={mid[0]} longitude={mid[1]} html={labelIconHtml(`${dominant?'MID · ':''}${candidate.modelLabel.replace('DWD ','').replace('NOAA ','')}`)} className={`synoptic-map-label ${dominant?'front':'front alternate'}`} anchor="center"/>);return items})}
   {displayStations.map(station=><HtmlMarker key={station.id} latitude={station.lat} longitude={station.lon} html={stationIconHtml(station)} className="synoptic-station-marker" anchor="center" popupHtml={`<strong>${escapeHtml(station.name)}</strong><br/>${escapeHtml(station.provider)} · ${Math.round(station.distanceKm)} km<br/>${isFiniteNumber(station.temperature)?`${station.temperature.toFixed(1)} °C`:''}${isFiniteNumber(station.dewPoint)?` · Td ${station.dewPoint.toFixed(1)} °C`:''}${isFiniteNumber(station.pressure)?` · ${Math.round(station.pressure)} hPa`:''}<br/>${isFiniteNumber(station.windDirection)?`Wind aus ${compassDirection(station.windDirection)} ${Math.round(station.windDirection)}°`:''}${isFiniteNumber(station.windSpeedKt)?` · ${Math.round(station.windSpeedKt)} kt`:''}`}/>)}<GeoJsonLayers id="synoptic-site" data={{type:'FeatureCollection',features:[{type:'Feature',properties:{},geometry:{type:'Point',coordinates:[location.longitude,location.latitude]}}]}} layers={[{id:'site',type:'circle',paint:{'circle-radius':7,'circle-color':'#fff','circle-stroke-color':'#087cef','circle-stroke-width':3}}]}/><HtmlMarker latitude={location.latitude} longitude={location.longitude} html={`<span>${escapeHtml(location.name)}</span>`} className="synoptic-site-label mid-maplibre-site-label" anchor="left" offset={[10,0]}/>
  </MidMapLibre><div className="synoptic-map-legend"><span><i className="isobar"/>Isobaren</span><span><i className="center"/>H/T</span><span><i className="station"/>Stationsmodell · Wind aus</span><span><i className="front"/>dominante Front</span><span><i className="front alternate"/>Alternative</span><span><i className="corridor"/>zur Front</span></div></div>
});

function FieldAnalysisStrip({candidate}:{candidate?:SynopticModelCandidate}){const preferred=['temperature','temperature850','dewpoint','moisture','pressure','wind','wind850','precipitation','cloud','temperatureChange','gust'],signals=(candidate?.signals||[]).slice().sort((a,b)=>{const ai=preferred.indexOf(a.key),bi=preferred.indexOf(b.key);return(ai<0?99:ai)-(bi<0?99:bi)||b.support-a.support}).slice(0,9);return <div className="synoptic-field-analysis"><header><div><small>Multiparametrische Feldanalyse</small><strong>{candidate?`${frontLabel(candidate.type)} · ${candidate.modelLabel}`:'Kein kohärenter Frontkandidat'}</strong></div><span>{signals.filter(item=>item.support>=.55).length}/{signals.length||9} Signale stützen</span></header><div>{signals.length?signals.map(signal=><article key={signal.key} className={signal.support>=.7?'strong':signal.support>=.45?'supporting':'weak'} title={`${signal.label}: ${signal.value} ${signal.unit} · Stützung ${Math.round(signal.support*100)} %`}><span>{signal.label}</span><i><b style={{width:`${clamp(signal.support*100,3,100)}%`}}/></i><strong>{signal.value} {signal.unit}</strong></article>):<p>Temperatur-, Feuchte-, Druck-, Wind-, Wolken- und Niederschlagsfelder liefern noch kein geschlossenes Frontsignal.</p>}</div></div>}

function SourceStrip({worker,contours,timezone}:{worker:SynopticWorkerResponse|null;contours:ModelContourResponse|null;timezone:string}){const sources=[...(worker?.sources||[]),...(contours?[{label:`${contours.provider||'Open-Meteo'} · ${contours.model||'Modellkonturen'}`,kind:'model' as const,dataTime:contours.frames?.[0]?.time,checkedAt:contours.checkedAt,detail:contours.resolutionNote||'MSLP-Isobaren und Druckzentren'}]:[])];return <div className="synoptic-sources"><Database size={15}/><div><strong>Datenstand und Quellen</strong><span>{sources.length?sources.map(source=>`${source.label}${source.dataTime?` · ${safeTime(source.dataTime,timezone)}`:''}`).join(' · '):'Lokale Best-Match-Ersatzanalyse; externe Synoptikdaten werden geladen.'}</span></div></div>}
function PhaseCards({intelligence}:{intelligence:SynopticIntelligence}){const before=intelligence.phases[0],after=intelligence.phases[2],shift=signedDirectionChange(before?.windDirection,after?.windDirection),shiftLevel=isFiniteNumber(shift)&&Math.abs(shift)>=60?'marked':isFiniteNumber(shift)&&Math.abs(shift)>=25?'noticeable':'slight';return <div className="synoptic-phase-overview"><div className="synoptic-phase-flow">{intelligence.phases.map((phase,index)=><article key={phase.key} className={`synoptic-phase-node ${phase.key}`} title={phase.summary}><header><span>{index+1}</span><div><strong>{phase.title}</strong><small>{phase.period}</small></div></header><div className="synoptic-phase-metrics"><span><b>{isFiniteNumber(phase.temperature)?`${Math.round(phase.temperature)}°`:'–'}</b>T</span><span><b>{isFiniteNumber(phase.pressure)?Math.round(phase.pressure):'–'}</b>hPa</span><span className="wind"><b><WindArrow direction={phase.windDirection}/>{isFiniteNumber(phase.windKt)?Math.round(phase.windKt):'–'}</b><small>{compassDirection(phase.windDirection)} · kt</small></span><span><b>{isFiniteNumber(phase.gustKt)?Math.round(phase.gustKt):'–'}</b>Böe kt</span><span><b>{isFiniteNumber(phase.rainProbability)?`${Math.round(phase.rainProbability)}%`:'–'}</b>Regen</span></div><div className="synoptic-phase-bars" aria-label="Grauer Balken: Böengeschwindigkeit. Blauer Balken: Regenwahrscheinlichkeit."><span className="gust"><em>Böen</em><i><b style={{width:`${clamp(Number(phase.gustKt||0)*1.35,4,100)}%`}}/></i><strong>{isFiniteNumber(phase.gustKt)?`${Math.round(phase.gustKt)} kt`:'–'}</strong></span><span className="rain"><em>Regen</em><i><b style={{width:`${clamp(Number(phase.rainProbability||0),4,100)}%`}}/></i><strong>{isFiniteNumber(phase.rainProbability)?`${Math.round(phase.rainProbability)} %`:'–'}</strong></span></div>{index<2?<ArrowRight className="synoptic-phase-arrow" size={18}/>:null}</article>)}</div><div className={`synoptic-wind-transition ${shiftLevel}`}><Wind size={17}/><span><small>Windrichtung vor → nach dem Frontdurchgang</small><b><WindArrow direction={before?.windDirection}/>{compassDirection(before?.windDirection)} {isFiniteNumber(before?.windDirection)?`${Math.round(before.windDirection)}°`:'–'} <ArrowRight size={14}/> <WindArrow direction={after?.windDirection}/>{compassDirection(after?.windDirection)} {isFiniteNumber(after?.windDirection)?`${Math.round(after.windDirection)}°`:'–'}</b></span><em>{windTurnText(shift)}</em></div></div>}
function ImpactStrip({intelligence}:{intelligence:SynopticIntelligence}){return <div className="synoptic-impact-strip">{intelligence.impacts.map(impact=><article key={impact.activity} className={`synoptic-impact-chip ${impact.level}`} title={[impact.summary,...impact.actions].join(' · ')}><Activity size={15}/><div><strong>{impact.label}</strong><small>{impact.summary}</small></div><span>{impact.level==='high'?'deutlich':impact.level==='medium'?'beachten':'gering'}</span></article>)}</div>}
function ModelAgreementGraphic({worker,event,timezone,candidates}:{worker:SynopticWorkerResponse|null;event:SynopticIntelligence['event'];timezone:string;candidates:SynopticModelCandidate[]}){return <><div className="synoptic-model-lanes">{candidates.map(candidate=><div key={candidate.modelId}><span className="model-dot" style={{background:FRONT_COLORS[candidate.type]}}/><strong>{candidate.modelLabel}</strong><small>{frontLabel(candidate.type)} · {safeTime(candidate.arrivalAt,timezone)}</small><div><i style={{width:`${clamp(candidate.score,4,100)}%`,background:FRONT_COLORS[candidate.type]}}/></div><b>{candidate.score}</b></div>)}</div><div className="synoptic-timing-graphic"><span><small>Modell</small><b>{safeTime(worker?.timing.modelMedianAt||event?.predictedAt,timezone)}</b></span><ArrowRight size={19}/><span><small>assimiliert</small><b>{safeTime(worker?.timing.assimilatedAt||event?.predictedAt,timezone)}</b></span><div><i className="observation"/><small>Beob. {worker?.timing.observationAdjustmentMinutes||0} min</small><i className="radar"/><small>Radar {worker?.timing.radarAdjustmentMinutes||0} min</small></div></div></>}
function CorridorGraphic({worker,stations}:{worker:SynopticWorkerResponse|null;stations:SynopticStationPlot[]}){const length=Math.max(1,worker?.corridor.lengthKm||420),bearing=worker?.corridor.bearingDeg;return <div className="synoptic-corridor-graphic"><header><span><MapPinned size={15}/>Standort</span><b>{isFiniteNumber(bearing)?`zur Front ${Math.round(bearing)}°`:'Richtung noch unsicher'} →</b></header><div className="synoptic-corridor-axis"><i className="site"/>{stations.slice(0,10).map(station=><i key={station.id} className={`station phase-${station.phase||'before'}`} style={{left:`${clamp(station.distanceKm/length*100,5,96)}%`}} title={`${station.name} · ${Math.round(station.distanceKm)} km · ${isFiniteNumber(station.temperature)?station.temperature.toFixed(1)+' °C':''}`}/>)}</div><div className="synoptic-station-chips">{stations.slice(0,6).map(item=><span key={item.id}><b>{item.name}</b><small>{Math.round(item.distanceKm)} km · {isFiniteNumber(item.temperature)?`${item.temperature.toFixed(1)}°`:''}{isFiniteNumber(item.pressure)?` · ${Math.round(item.pressure)} hPa`:''}</small></span>)}</div></div>}
function UncertaintyBudget({intelligence}:{intelligence:SynopticIntelligence}){return <section className="synoptic-subpanel"><div className="synoptic-subhead"><GitCompareArrows size={17}/><div><strong>Unsicherheitsbudget nach Ursache</strong><small>Ursachen statt unklarer Gesamtzahl.</small></div></div><div className="synoptic-budget">{intelligence.uncertainty.map(cause=><div key={cause.key} title={cause.detail}><header><span>{cause.label}</span><b>{Math.round(cause.share)}%</b></header><div><i style={{width:`${Math.round(cause.share)}%`}}/></div></div>)}</div></section>}

function SynopticPanel({location,locationKey,hours,days,ensemble,station,radar,thunder,timezone,advancedMode}:Props){
 const[worker,setWorker]=useState<SynopticWorkerResponse|null>(null),[contours,setContours]=useState<ModelContourResponse|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');Promise.allSettled([loadSynopticAnalysis(location,controller.signal),loadModelContours(location.latitude,location.longitude,controller.signal)]).then(results=>{if(controller.signal.aborted)return;const synoptic=results[0],model=results[1];if(synoptic.status==='fulfilled')setWorker(synoptic.value);else setError(synoptic.reason instanceof Error?synoptic.reason.message:String(synoptic.reason));if(model.status==='fulfilled')setContours(model.value)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[location.latitude,location.longitude,location.country_code]);
 const intelligence=useMemo(()=>buildSynopticIntelligence({location,locationKey,hours,days,ensemble,station,radar,thunder,worker}),[location.latitude,location.longitude,locationKey,hours,days,ensemble,station?.timestamp,radar?.observedAt,radar?.arrivalMinutes,thunder?.observedAt,worker]),event=intelligence.event,primary=useMemo(()=>{const rows=(worker?.candidates||[]).slice().sort((a,b)=>b.score-a.score),agreed=worker?.agreement.type&&worker.agreement.type!=='none'?rows.filter(item=>item.type===worker.agreement.type):[];return(agreed.length?agreed:rows)[0]},[worker]),frame=useMemo(()=>nearestFrame(contours,event?.predictedAt),[contours,event?.predictedAt]),stations=worker?.corridor.stations||[],candidates=(worker?.candidates?.length?worker.candidates:(primary?[primary]:[]));
 return <section className="synoptic-panel">
  <div className="synoptic-change-card"><div className="synoptic-change-icon"><MapPinned size={23}/></div><div className="synoptic-change-main"><small>Nächster markanter Wetterwechsel</small><h3>{event?frontLabel(event.type):'Kein markanter Frontdurchgang erkannt'}</h3><p>{intelligence.nextChangeSummary}</p></div><div className="synoptic-change-meta"><span className={`confidence ${event?.confidence||'low'}`}>Sicherheit {confidenceLabel(event?.confidence)}</span><span><Clock3 size={14}/>{event?lifecycleLabel(event.lifecycle):'ruhig'}</span>{loading?<span><RefreshCw className="spin" size={14}/>Synoptikdaten</span>:null}</div></div>
  {error?<div className="synoptic-notice"><AlertTriangle size={16}/><span>Externe Synoptikanalyse derzeit eingeschränkt: {error}. MID verwendet vorübergehend den lokalen Best-Match-Wetterwechsel.</span></div>:null}
  {event?<PhaseCards intelligence={intelligence}/>:null}{event?<ImpactStrip intelligence={intelligence}/>:null}
  {advancedMode?<><div className="synoptic-reference-grid"><section className="synoptic-subpanel official-analysis"><div className="synoptic-subhead"><ShieldCheck size={17}/><div><strong>Amtliche DWD-Bodenanalyse</strong><small>Unveränderte amtliche Referenz.</small></div></div>{worker?.officialAnalysis.available&&worker.officialAnalysis.imageUrl?<a href={worker.officialAnalysis.sourcePage} target="_blank" rel="noreferrer" className="official-analysis-image"><img src={worker.officialAnalysis.imageUrl} alt="Amtliche DWD-Bodenanalyse mit Fronten, Isobaren, Druckzentren und Stationsbeobachtungen" loading="lazy"/><span><ExternalLink size={14}/>DWD-Originalseite öffnen</span></a>:<div className="synoptic-empty"><Info size={17}/><span>{worker?.officialAnalysis.error||'Die amtliche Karte wird noch geladen. Bis dahin bleibt die objektive MID-Analyse sichtbar.'}</span></div>}<footer>Datenstand: {safeTime(worker?.officialAnalysis.nominalTime||worker?.officialAnalysis.publishedAt,timezone)} · Quelle: Deutscher Wetterdienst · {worker?.officialAnalysis.license||'DWD Open Data'}</footer></section><section className="synoptic-subpanel synoptic-map-panel"><div className="synoptic-subhead"><Wind size={17}/><div><strong>Interaktive MID-Synoptik</strong><small>Kartengrundlage, Isobaren, H/T, lesbare Stationsplots und objektive Modellfronten.</small></div></div><SynopticMap location={location} frame={frame} candidates={candidates} stations={stations} corridorBearing={worker?.corridor.bearingDeg} primaryModelId={primary?.modelId} validLabel={frame?`gültig ${safeTime(frame.time,timezone)}`:`Analyse ${safeTime(worker?.generatedAt,timezone)}`}/><FieldAnalysisStrip candidate={primary}/><footer>{frame?`Modellgültigkeit ${safeTime(frame.time,timezone)} · ${contours?.model||'Modellkonturen'}`:'Konturen werden geladen.'} · Fronten: „MID-Frontkandidat · objektive Modellanalyse“</footer></section></div>
   <div className="synoptic-diagnostics-grid"><section className="synoptic-subpanel"><div className="synoptic-subhead"><GitCompareArrows size={17}/><div><strong>Modellübereinstimmung & Timing</strong><small>Ein Blick statt langer Modelltexte.</small></div></div><ModelAgreementGraphic worker={worker} event={event} timezone={timezone} candidates={candidates}/></section><section className="synoptic-subpanel"><div className="synoptic-subhead"><MapPinned size={17}/><div><strong>Beobachtungskorridor stromaufwärts · zur Front</strong><small>Stromaufwärts heißt: vom Standort in Richtung der annähernden Front – bei Warmfronten ausdrücklich zur Warmfront hin.</small></div></div><CorridorGraphic worker={worker} stations={stations}/><footer>{worker?.corridor.summary||'Der Korridor wird aus der Herkunftsrichtung der frontführenden Strömung abgeleitet.'}</footer></section></div>
   <UncertaintyBudget intelligence={intelligence}/><div className="synoptic-diagnostics-grid"><section className="synoptic-subpanel"><div className="synoptic-subhead"><GitCompareArrows size={17}/><div><strong>Erklärbare Kausalkette</strong><small>Nur die entscheidenden Schritte.</small></div></div><ol className="synoptic-causal">{intelligence.causalChain.slice(0,6).map((item,index)=><li key={`${index}-${item}`}><span>{index+1}</span><p>{item}</p></li>)}</ol></section><section className="synoptic-subpanel"><div className="synoptic-subhead"><Database size={17}/><div><strong>Lokales Analogarchiv und Ereignisverifikation</strong><small>Lebenszyklus und lokale Vergleichsfälle.</small></div></div><p>{intelligence.verification.summary}</p><div className="synoptic-analogues">{intelligence.analogues.length?intelligence.analogues.slice(0,4).map(item=><article key={item.id}><strong>{safeTime(item.date,timezone)}</strong><span>{frontLabel(item.type)} · {Math.round(item.similarity)}% ähnlich</span></article>):<div className="synoptic-empty"><Info size={16}/><span>Noch keine verifizierten lokalen Analogfälle dieses Typs.</span></div>}</div>{event?<div className="synoptic-event-line"><span>Objekt <b>{event.id.split(':').slice(-2).join(':')}</b></span><span>Status <b>{lifecycleLabel(event.lifecycle)}</b></span><span>Erkannt <b>{safeTime(event.firstSeen,timezone)}</b></span></div>:null}</section></div></>:null}
  <SourceStrip worker={worker} contours={contours} timezone={timezone}/>
 </section>
}
export default memo(SynopticPanel);
