import {useCallback,useEffect,useMemo,useState} from 'react';
import {CanvasOverlay,GeoJsonLayers,ImageQuadLayer} from './MapLibreCore';
import {loadSynopticIndex,loadSynopticField,synopticRaster,THETAE_COLORS,type SynopticField} from './nativeSynopticFields';
import {synopticCompositePlan} from './synopticComposite';
export function useSynopticCatalog(revision:number){const [catalog,setCatalog]=useState<Awaited<ReturnType<typeof loadSynopticIndex>>|null>(null),[error,setError]=useState('');useEffect(()=>{const c=new AbortController();setCatalog(null);setError('');void loadSynopticIndex(c.signal).then(d=>{if(!c.signal.aborted)setCatalog(d)}).catch(e=>{if(!c.signal.aborted)setError(String(e.message||e))});return()=>c.abort()},[revision]);return {catalog,error}}
export function useSynopticComposite(enabled:boolean,target:number,_revision:number,_showFill:boolean,modelId:string,catalog:ReturnType<typeof useSynopticCatalog>){
 const [field,setField]=useState<SynopticField|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),model=catalog.catalog?.index.models[modelId],plan=useMemo(()=>enabled?synopticCompositePlan(model,target):null,[enabled,model,target]);
 useEffect(()=>{const c=new AbortController();setField(null);setError('');setLoading(false);if(!plan||!model||!catalog.catalog)return()=>c.abort();setLoading(true);void loadSynopticField(catalog.catalog.base,modelId,model,plan.frame,c.signal).then(d=>{if(!c.signal.aborted)setField(d)}).catch(e=>{if(!c.signal.aborted)setError(String(e.message||e))}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[plan?.time,plan?.run,modelId,catalog.catalog]);
 return {plan,field,loading,error:error||catalog.error,ready:Boolean(field),model};
}
export function SynopticCompositeLayers({state,opacity,showFill,thetaOnly=false,heightOnly=false}:{state:ReturnType<typeof useSynopticComposite>;opacity:number;showFill:boolean;thetaOnly?:boolean;heightOnly?:boolean}){
 const field=state.field,raster=useMemo(()=>field&&showFill&&!heightOnly?synopticRaster(field):'',[field,showFill,heightOnly]);
 const draw=useCallback((map:Parameters<Parameters<typeof CanvasOverlay>[0]['render']>[0],canvas:HTMLCanvasElement)=>{const size=map.getContainer().getBoundingClientRect(),ratio=devicePixelRatio||1;canvas.width=size.width*ratio;canvas.height=size.height*ratio;const c=canvas.getContext('2d');if(!c||!field)return;c.scale(ratio,ratio);c.strokeStyle='#15202b';c.lineWidth=1.2;for(const [lon,lat,u,v] of field.wind){const speed=Math.hypot(u,v);if(speed<1)continue;const p=map.project([lon,lat]),length=Math.min(22,7+speed*.2),dx=u/speed*length,dy=-v/speed*length;c.beginPath();c.moveTo(p.x-dx/2,p.y-dy/2);c.lineTo(p.x+dx/2,p.y+dy/2);const angle=Math.atan2(dy,dx);for(const side of [-1,1]){c.moveTo(p.x+dx/2,p.y+dy/2);c.lineTo(p.x+dx/2-5*Math.cos(angle+side*.55),p.y+dy/2-5*Math.sin(angle+side*.55))}c.stroke()}},[field]);
 if(!field)return null;const dark=heightOnly&&(document.documentElement.dataset.theme==='dark'||document.documentElement.classList.contains('dark')),heightColor=dark?'#e5edf3':'#17212b';
 const contours=(key:'height'|'pressure'|'humidity',color:string,dashed=false)=><GeoJsonLayers key={key} id={`synoptic-${key}`} data={key==='humidity'?{...field.humidity,features:field.humidity.features.filter(f=>f.properties.level>=60)}:field[key]} zIndex={key==='pressure'?680:675} hoverProperty="label" layers={[{id:'line',type:'line',paint:{'line-color':color,'line-width':key==='height'?1.7:1.25,'line-opacity':opacity/100,...(dashed?{'line-dasharray':[3,2]}:{})}},{id:'label',type:'symbol',layout:{'symbol-placement':'line','symbol-spacing':180,'text-field':['get','label'],'text-size':10,'text-font':['Noto Sans Regular']},paint:{'text-color':color,'text-halo-color':key==='pressure'?'#354753':'#e4e8e3','text-halo-width':1,'text-opacity':opacity/100}}]}/>;
 return <>{raster&&<ImageQuadLayer id="synoptic-thetae" url={raster} bounds={[[field.lats[0],field.lons[0]],[field.lats.at(-1)!,field.lons.at(-1)!]]} opacity={opacity/100} zIndex={300}/>} {!thetaOnly&&contours('height',heightColor)}{!thetaOnly&&!heightOnly&&<>{contours('pressure','#fff')}{contours('humidity','#448ad1',true)}<CanvasOverlay id="synoptic-wind300" opacity={opacity/100} zIndex={690} render={draw}/></>}</>;
}
export function SynopticCompositeLegend({state}:{state:ReturnType<typeof useSynopticComposite>}){if(!state.model)return null;return <details className="unified-source-info"><summary>Farblegende · Theta-E 850 hPa (°C)</summary><div style={{display:'flex',height:16,background:`linear-gradient(to right,${THETAE_COLORS.map(c=>c[1]).join(',')})`}}/><div style={{display:'flex',justifyContent:'space-between',fontSize:12}}>{[-18,6,30,54,78,90].map(v=><span key={v}>{v}°</span>)}</div><p>Theta-E 850 hPa: Farbfläche · Höhenlinien 500 hPa: schwarz, dam · MSL-Isobaren: weiß, hPa · Feuchte 700 hPa: blau gestrichelt, % · Strömung 300 hPa: schwarze Pfeile.</p><p>{state.model.label} · {state.model.resolutionKm} km veröffentlichtes Raster · {state.model.license}. Gleicher Lauf und Termin für alle fünf Komponenten.</p></details>}
