import {memo,useEffect,useMemo,useState} from 'react';
import {Activity,AlertTriangle,ArrowRight,Clock3,Database,ExternalLink,GitCompareArrows,Info,MapPinned,RefreshCw,ShieldCheck,Wind} from 'lucide-react';
import type {Day,EnsembleDay,Hour,Location,RadarNowcast,Station,ThunderstormNowcast} from './weather';
import {loadModelContours,type ModelContourFrame,type ModelContourResponse} from './CompositeData';
import {buildSynopticIntelligence,frontLabel,loadSynopticAnalysis,type SynopticFrontType,type SynopticIntelligence,type SynopticModelCandidate,type SynopticPoint,type SynopticStationPlot,type SynopticWorkerResponse} from './synoptic';

type Props={location:Location;locationKey:string;hours:Hour[];days:Day[];ensemble:EnsembleDay[];station?:Station|null;radar?:RadarNowcast|null;thunder?:ThunderstormNowcast|null;timezone:string;advancedMode:boolean};
type Bounds={south:number;north:number;west:number;east:number};
const FRONT_COLORS:Record<SynopticFrontType,string>={cold:'#1987ff',warm:'#ee4a55',occlusion:'#b34bd7',trough:'#845c3b',convergence:'#e6b31e',none:'#8b95a1'};
const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value));
const safeTime=(value?:string,timeZone?:string)=>{if(!value)return'–';const date=new Date(value);if(!Number.isFinite(date.getTime()))return'–';return new Intl.DateTimeFormat('de-DE',{timeZone:timeZone||undefined,day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(date)};
const confidenceLabel=(value?:string)=>value==='high'?'hoch':value==='medium'?'mittel':'eingeschränkt';
const lifecycleLabel=(value?:string)=>({detected:'erkannt',approaching:'annähernd',passage:'im Durchgang',departing:'abziehend',verified:'verifiziert',dissipated:'nicht mehr aktiv'} as Record<string,string>)[String(value)]||'–';

function mapBounds(location:Location,frame:ModelContourFrame|undefined,candidates:SynopticModelCandidate[],stations:SynopticStationPlot[]):Bounds{
 const points:SynopticPoint[]=[[location.latitude,location.longitude],...candidates.flatMap(item=>item.line),...stations.map(item=>[item.lat,item.lon] as SynopticPoint)];
 for(const level of frame?.isobars||[])for(const path of level.paths||[])for(const point of path)if(Math.abs(point[0]-location.latitude)<=7&&Math.abs(point[1]-location.longitude)<=11)points.push(point);
 let south=Math.min(...points.map(point=>point[0])),north=Math.max(...points.map(point=>point[0])),west=Math.min(...points.map(point=>point[1])),east=Math.max(...points.map(point=>point[1]));
 const latPad=Math.max(2.2,(north-south)*.12),lonPad=Math.max(3.1,(east-west)*.12);south=Math.max(-85,south-latPad);north=Math.min(85,north+latPad);west-=lonPad;east+=lonPad;return{south,north,west,east};
}
function pointProject(point:SynopticPoint,bounds:Bounds,width=1000,height=540){const x=(point[1]-bounds.west)/Math.max(.01,bounds.east-bounds.west)*width,y=height-(point[0]-bounds.south)/Math.max(.01,bounds.north-bounds.south)*height;return[x,y] as const}
function pathData(path:SynopticPoint[],bounds:Bounds){return path.map((point,index)=>{const[x,y]=pointProject(point,bounds);return`${index?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`}).join(' ')}
function windEnd(station:SynopticStationPlot,bounds:Bounds){const[x,y]=pointProject([station.lat,station.lon],bounds),length=10+Math.min(24,Number(station.windSpeedKt||0)*.45),towards=((Number(station.windDirection)||0)+180)*Math.PI/180;return{x1:x,y1:y,x2:x+Math.sin(towards)*length,y2:y-Math.cos(towards)*length}}
function nearestFrame(contours:ModelContourResponse|null,candidateAt?:string){if(!contours?.frames?.length)return undefined;const target=Date.parse(String(candidateAt||''));return contours.frames.slice().sort((a,b)=>Math.abs(Date.parse(a.time)-target)-Math.abs(Date.parse(b.time)-target))[0]}
function frontDash(type:SynopticFrontType){return type==='trough'?'10 7':type==='convergence'?'4 5':''}

const SynopticMap=memo(function SynopticMap({location,frame,candidates,stations}:{location:Location;frame?:ModelContourFrame;candidates:SynopticModelCandidate[];stations:SynopticStationPlot[]}){
 const bounds=useMemo(()=>mapBounds(location,frame,candidates,stations),[location.latitude,location.longitude,frame,candidates,stations]),[siteX,siteY]=pointProject([location.latitude,location.longitude],bounds);
 return <div className="synoptic-map-wrap">
  <svg className="synoptic-map" viewBox="0 0 1000 540" role="img" aria-label="MID-Synoptikkarte mit Isobaren, Druckzentren, Stationsplots und objektiven Frontkandidaten">
   <defs><pattern id="synopticGrid" width="100" height="90" patternUnits="userSpaceOnUse"><path d="M 100 0 L 0 0 0 90" fill="none" stroke="currentColor" strokeOpacity=".08" strokeWidth="1"/></pattern><filter id="synopticGlow"><feGaussianBlur stdDeviation="2" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
   <rect width="1000" height="540" className="synoptic-map-bg"/><rect width="1000" height="540" fill="url(#synopticGrid)"/>
   {(frame?.isobars||[]).map(level=><g key={`p-${level.level}`}>{level.paths.map((path,index)=><path key={index} d={pathData(path,bounds)} className="synoptic-isobar"/>)}{level.paths[0]?.length?<text x={pointProject(level.paths[0][Math.floor(level.paths[0].length/2)],bounds)[0]} y={pointProject(level.paths[0][Math.floor(level.paths[0].length/2)],bounds)[1]-4} className="synoptic-isobar-label">{Math.round(level.level)}</text>:null}</g>)}
   {(frame?.centers||[]).map((center,index)=>{const[x,y]=pointProject([center.lat,center.lon],bounds);return <g key={`${center.type}-${index}`} className={`synoptic-center ${center.type==='H'?'high':'low'}`}><circle cx={x} cy={y} r="20"/><text x={x} y={y+7}>{center.type}</text><title>{center.type==='H'?'Hoch':'Tief'}druckzentrum · {center.value.toFixed(0)} hPa</title></g>})}
   {candidates.map(candidate=><g key={candidate.modelId} className="synoptic-front"><path d={pathData(candidate.line,bounds)} stroke={FRONT_COLORS[candidate.type]} strokeDasharray={frontDash(candidate.type)} opacity={clamp(.45+candidate.score/180,.55,1)}/><text x={pointProject(candidate.line[Math.floor(candidate.line.length/2)],bounds)[0]+8} y={pointProject(candidate.line[Math.floor(candidate.line.length/2)],bounds)[1]-10} fill={FRONT_COLORS[candidate.type]}>{candidate.modelLabel.replace('DWD ','').replace('NOAA ','')}</text><title>{candidate.modelLabel}: {frontLabel(candidate.type)} · {candidate.score}/100</title></g>)}
   {stations.slice(0,16).map(station=>{const[x,y]=pointProject([station.lat,station.lon],bounds),wind=windEnd(station,bounds);return <g key={station.id} className={`synoptic-station phase-${station.phase||'before'}`}><line {...wind}/><circle cx={x} cy={y} r="7"/><text x={x+10} y={y-5}>{Number.isFinite(station.temperature)?Math.round(Number(station.temperature)):''}</text><text x={x+10} y={y+10}>{Number.isFinite(station.pressure)?Math.round(Number(station.pressure)):''}</text><title>{station.name} · {station.provider} · {Number.isFinite(station.temperature)?`${Number(station.temperature).toFixed(1)} °C`:''}</title></g>})}
   <g className="synoptic-site" filter="url(#synopticGlow)"><circle cx={siteX} cy={siteY} r="11"/><circle cx={siteX} cy={siteY} r="3"/><text x={siteX+15} y={siteY+5}>{location.name}</text></g>
  </svg>
  <div className="synoptic-map-legend"><span><i className="isobar"/>Isobaren</span><span><i className="center"/>H/T</span><span><i className="station"/>Stationsplot</span><span><i className="front"/>MID-Frontkandidat</span></div>
 </div>
});

function SourceStrip({worker,contours,timezone}:{worker:SynopticWorkerResponse|null;contours:ModelContourResponse|null;timezone:string}){const sources=[...(worker?.sources||[]),...(contours?[{label:`${contours.provider||'Open-Meteo'} · ${contours.model||'Modellkonturen'}`,kind:'model' as const,dataTime:contours.frames?.[0]?.time,checkedAt:contours.checkedAt,detail:contours.resolutionNote||'MSLP-Isobaren und Druckzentren'}]:[])];return <div className="synoptic-sources"><Database size={15}/><div><strong>Datenstand und Quellen</strong><span>{sources.length?sources.map(source=>`${source.label}${source.dataTime?` · ${safeTime(source.dataTime,timezone)}`:''}`).join(' · '):'Lokale Best-Match-Ersatzanalyse; externe Synoptikdaten werden geladen.'}</span></div></div>}
function PhaseCards({intelligence}:{intelligence:SynopticIntelligence}){return <div className="synoptic-phases">{intelligence.phases.map((phase,index)=><article key={phase.key} className={`synoptic-phase ${phase.key}`}><header><span>{index+1}</span><div><strong>{phase.title}</strong><small>{phase.period}</small></div>{index<2?<ArrowRight size={17}/>:null}</header><p>{phase.summary}</p><div className="synoptic-phase-values"><span><b>{Number.isFinite(phase.temperature)?`${Math.round(Number(phase.temperature))}°`:'–'}</b>Temperatur</span><span><b>{Number.isFinite(phase.pressure)?`${Math.round(Number(phase.pressure))}`:'–'}</b>hPa</span><span><b>{Number.isFinite(phase.gustKt)?`${Math.round(Number(phase.gustKt))}`:'–'}</b>kt Böen</span><span><b>{Number.isFinite(phase.rainProbability)?`${Math.round(Number(phase.rainProbability))}%`:'–'}</b>Regen</span></div></article>)}</div>}
function UncertaintyBudget({intelligence}:{intelligence:SynopticIntelligence}){return <section className="synoptic-subpanel"><div className="synoptic-subhead"><GitCompareArrows size={17}/><div><strong>Unsicherheitsbudget nach Ursache</strong><small>Nicht nur eine Gesamtzahl: Die größten Unsicherheitsquellen werden getrennt ausgewiesen.</small></div></div><div className="synoptic-budget">{intelligence.uncertainty.map(cause=><div key={cause.key}><header><span>{cause.label}</span><b>{cause.share}%</b></header><div><i style={{width:`${cause.share}%`}}/></div><small>{cause.detail}</small></div>)}</div></section>}

function SynopticPanel({location,locationKey,hours,days,ensemble,station,radar,thunder,timezone,advancedMode}:Props){
 const[worker,setWorker]=useState<SynopticWorkerResponse|null>(null),[contours,setContours]=useState<ModelContourResponse|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');Promise.allSettled([loadSynopticAnalysis(location,controller.signal),loadModelContours(location.latitude,location.longitude,controller.signal)]).then(results=>{if(controller.signal.aborted)return;const synoptic=results[0],model=results[1];if(synoptic.status==='fulfilled')setWorker(synoptic.value);else setError(synoptic.reason instanceof Error?synoptic.reason.message:String(synoptic.reason));if(model.status==='fulfilled')setContours(model.value)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[location.latitude,location.longitude,location.country_code]);
 const intelligence=useMemo(()=>buildSynopticIntelligence({location,locationKey,hours,days,ensemble,station,radar,thunder,worker}),[location.latitude,location.longitude,locationKey,hours,days,ensemble,station?.timestamp,radar?.observedAt,radar?.arrivalMinutes,thunder?.observedAt,worker]),event=intelligence.event,primary=useMemo(()=>(worker?.candidates||[]).slice().sort((a,b)=>b.score-a.score)[0],[worker]),frame=useMemo(()=>nearestFrame(contours,event?.predictedAt),[contours,event?.predictedAt]),stations=worker?.corridor.stations||[];
 return <section className="synoptic-panel">
  <div className="synoptic-change-card">
   <div className="synoptic-change-icon"><MapPinned size={23}/></div><div className="synoptic-change-main"><small>Nächster markanter Wetterwechsel</small><h3>{event?frontLabel(event.type):'Kein markanter Frontdurchgang erkannt'}</h3><p>{intelligence.nextChangeSummary}</p></div><div className="synoptic-change-meta"><span className={`confidence ${event?.confidence||'low'}`}>Sicherheit {confidenceLabel(event?.confidence)}</span><span><Clock3 size={14}/>{event?lifecycleLabel(event.lifecycle):'ruhig'}</span>{loading?<span><RefreshCw className="spin" size={14}/>Synoptikdaten</span>:null}</div>
  </div>
  {error?<div className="synoptic-notice"><AlertTriangle size={16}/><span>Externe Synoptikanalyse derzeit eingeschränkt: {error}. MID verwendet vorübergehend den lokalen Best-Match-Wetterwechsel.</span></div>:null}
  {event?<PhaseCards intelligence={intelligence}/>:null}
  {event?<div className="synoptic-impact-grid">{intelligence.impacts.map(impact=><article key={impact.activity} className={`synoptic-impact ${impact.level}`}><header><Activity size={16}/><strong>{impact.label}</strong><span>{impact.level==='high'?'deutlich':impact.level==='medium'?'beachten':'gering'}</span></header><p>{impact.summary}</p><ul>{impact.actions.map(action=><li key={action}>{action}</li>)}</ul></article>)}</div>:null}
  {advancedMode?<>
   <div className="synoptic-reference-grid">
    <section className="synoptic-subpanel official-analysis"><div className="synoptic-subhead"><ShieldCheck size={17}/><div><strong>Amtliche DWD-Bodenanalyse</strong><small>Unveränderte amtliche Referenz; nicht mit den objektiven MID-Frontkandidaten vermischt.</small></div></div>{worker?.officialAnalysis.available&&worker.officialAnalysis.imageUrl?<a href={worker.officialAnalysis.sourcePage} target="_blank" rel="noreferrer" className="official-analysis-image"><img src={worker.officialAnalysis.imageUrl} alt="Amtliche DWD-Bodenanalyse mit Fronten, Isobaren, Druckzentren und Stationsbeobachtungen" loading="lazy"/><span><ExternalLink size={14}/>DWD-Originalseite öffnen</span></a>:<div className="synoptic-empty"><Info size={17}/><span>{worker?.officialAnalysis.error||'Die amtliche Karte wird vom Worker ermittelt. Bis dahin bleibt die objektive MID-Analyse sichtbar.'}</span></div>}<footer>Datenstand: {safeTime(worker?.officialAnalysis.nominalTime||worker?.officialAnalysis.publishedAt,timezone)} · Quelle: Deutscher Wetterdienst · {worker?.officialAnalysis.license||'DWD Open Data'}</footer></section>
    <section className="synoptic-subpanel"><div className="synoptic-subhead"><Wind size={17}/><div><strong>Interaktive MID-Synoptik</strong><small>Isobaren, Druckzentren, Stationsplots und klar getrennte objektive Modellfronten.</small></div></div><SynopticMap location={location} frame={frame} candidates={(worker?.candidates?.length?worker.candidates:(primary?[primary]:[]))} stations={stations}/><footer>{frame?`Modellgültigkeit ${safeTime(frame.time,timezone)} · ${contours?.model||'Modellkonturen'}`:'Konturen werden geladen.'} · Fronten: „MID-Frontkandidat · objektive Modellanalyse“</footer></section>
   </div>
   <div className="synoptic-diagnostics-grid">
    <section className="synoptic-subpanel"><div className="synoptic-subhead"><GitCompareArrows size={17}/><div><strong>Fronten-Übereinstimmung und Timing-Assimilation</strong><small>Vollständige Modellereignisse statt Parameterkreuzung.</small></div></div><div className="synoptic-models">{(worker?.candidates?.length?worker.candidates:(primary?[primary]:[])).map(candidate=><article key={candidate.modelId}><header><span style={{background:FRONT_COLORS[candidate.type]}}/><strong>{candidate.modelLabel}</strong><b>{candidate.score}/100</b></header><p>{frontLabel(candidate.type)} · {safeTime(candidate.arrivalAt,timezone)}</p><small>{candidate.summary}</small></article>)}</div><div className="synoptic-timing"><span><b>Modellmedian</b>{safeTime(worker?.timing.modelMedianAt||event?.predictedAt,timezone)}</span><ArrowRight size={18}/><span><b>Assimiliert</b>{safeTime(worker?.timing.assimilatedAt||event?.predictedAt,timezone)}</span><span><b>Beobachtung</b>{worker?.timing.observationAdjustmentMinutes||0} min</span><span><b>Radar</b>{worker?.timing.radarAdjustmentMinutes||0} min</span></div></section>
    <section className="synoptic-subpanel"><div className="synoptic-subhead"><MapPinned size={17}/><div><strong>Beobachtungskorridor stromaufwärts</strong><small>Offizielle und professionelle Stationen entlang der erwarteten Zugrichtung.</small></div></div><p className="synoptic-corridor-summary">{worker?.corridor.summary||'Der Korridor wird aus der Frontbewegung abgeleitet.'}</p><div className="synoptic-station-list">{stations.slice(0,8).map(item=><article key={item.id}><strong>{item.name}</strong><span>{Math.round(item.distanceKm)} km · {item.phase==='after'?'nachfolgende':item.phase==='transition'?'Übergangs-':'vorgelagerte'} Luftmasse</span><small>{Number.isFinite(item.temperature)?`${Number(item.temperature).toFixed(1)} °C`:''}{Number.isFinite(item.dewPoint)?` · Td ${Number(item.dewPoint).toFixed(1)} °C`:''}{Number.isFinite(item.pressure)?` · ${Math.round(Number(item.pressure))} hPa`:''}</small></article>)}</div></section>
   </div>
   <UncertaintyBudget intelligence={intelligence}/>
   <div className="synoptic-diagnostics-grid">
    <section className="synoptic-subpanel"><div className="synoptic-subhead"><GitCompareArrows size={17}/><div><strong>Erklärbare Kausalkette</strong><small>Warum sich Prognose und Fronttiming ändern.</small></div></div><ol className="synoptic-causal">{intelligence.causalChain.map((item,index)=><li key={`${index}-${item}`}><span>{index+1}</span><p>{item}</p></li>)}</ol></section>
    <section className="synoptic-subpanel"><div className="synoptic-subhead"><Database size={17}/><div><strong>Lokales Analogarchiv und Ereignisverifikation</strong><small>Ereignisobjekte werden über Erkennung, Annäherung, Durchgang und Verifikation fortgeschrieben.</small></div></div><p>{intelligence.verification.summary}</p><div className="synoptic-analogues">{intelligence.analogues.length?intelligence.analogues.map(item=><article key={item.id}><strong>{safeTime(item.date,timezone)}</strong><span>{frontLabel(item.type)} · Ähnlichkeit {item.similarity}%</span><small>{item.summary}</small></article>):<div className="synoptic-empty"><Info size={16}/><span>Noch keine verifizierten lokalen Analogfälle dieses Typs.</span></div>}</div>{event?<div className="synoptic-event-line"><span>Objekt <b>{event.id.split(':').slice(-2).join(':')}</b></span><span>Lebenszyklus <b>{lifecycleLabel(event.lifecycle)}</b></span><span>Erste Erkennung <b>{safeTime(event.firstSeen,timezone)}</b></span></div>:null}</section>
   </div>
  </>:null}
  <SourceStrip worker={worker} contours={contours} timezone={timezone}/>
 </section>
}
export default memo(SynopticPanel);
