import type {Hour,OfficialAlert,RadarNowcast,Station,ThunderstormNowcast} from './weather';

export type ThunderInfoLevel='clear'|'yellow'|'orange'|'red'|'purple';
export type ThunderInfo={level:ThunderInfoLevel;headline:string;summary:string;source:string;official:boolean};
const levelRank:Record<ThunderInfoLevel,number>={clear:0,yellow:1,orange:2,red:3,purple:4};
function thunderAlert(alert:OfficialAlert){return /gewitter|thunder|hagel|hail/i.test(`${alert.event||''} ${alert.headline||''} ${alert.description||''}`)}
function alertLevel(value:OfficialAlert['level']):ThunderInfoLevel{return value==='purple'||value==='red'||value==='orange'||value==='yellow'?value:'yellow'}
function severityLevel(severity:number,hailFlag:number,heavyRainFlag:number):ThunderInfoLevel{const score=Math.max(Number(severity)||0,Number(hailFlag)||0,Number(heavyRainFlag)||0);return score>=3?'purple':score>=2?'red':score>=1?'orange':'yellow'}
function trendText(value:number){return value>=2?'schnell anwachsend':value===1?'anwachsend':value<=-2?'schnell abschwächend':value===-1?'abschwächend':'stabil'}
function cellDetails(cell:NonNullable<ThunderstormNowcast['nearest']>){const details=[`KONRAD3D ${['schwach','moderat','stark','extrem'][Math.max(0,Math.min(3,Math.round(cell.severity)))]}`,trendText(cell.trend)];if(cell.lightningRate>0)details.push(`${Math.round(cell.lightningRate)} Blitze/5 min`);if(cell.hailFlag>0||cell.areaHail>0)details.push(cell.hailFlag>=2||cell.areaLargeHail>0?'Großhagelsignal':'Hagelsignal');if(cell.heavyRainFlag>0)details.push(`Starkregenstufe ${cell.heavyRainFlag}`);if((cell.gustFlag??0)>0)details.push(`Böenstufe ${cell.gustFlag}`);return details.join(' · ')}
function stationRainText(station:Station|null){const rain=Number(station?.precipitation);if(!Number.isFinite(rain)||rain<.1)return'';return `${station?.provider?.includes('DWD')?'DWD-Station':'Station'} bestätigt Niederschlag`}
export function combineThunderstormInformation(nowcast:ThunderstormNowcast|null,alerts:OfficialAlert[],hours:Hour[],radar:RadarNowcast|null,station:Station|null,loading:boolean,error:string):ThunderInfo{
 const warning=alerts.filter(thunderAlert).sort((a,b)=>levelRank[alertLevel(b.level)]-levelRank[alertLevel(a.level)])[0];
 if(warning)return{level:alertLevel(warning.level),headline:'Amtliche Gewitterwarnung',summary:warning.headline,source:`${warning.source} · amtliche Warnung`,official:true};
 const cell=nowcast?.nearest;if(nowcast?.available&&cell&&cell.relevanceDistanceKm<=80){const nearNow=cell.currentDistanceKm<=25,approaching=cell.isApproaching&&Number.isFinite(cell.arrivalMinutes)&&Number(cell.arrivalMinutes)<=90,headline=nearNow?'Gewitterzelle nahe':approaching?'Gewitterzelle nähert sich':'Gewitterzelle im Umfeld',distance=Math.round(nearNow?cell.currentDistanceKm:cell.relevanceDistanceKm),arrival=approaching&&!nearNow?` · mögliche Annäherung in etwa ${Math.round(Number(cell.arrivalMinutes))} min`:'';return{level:severityLevel(cell.severity,cell.hailFlag,cell.heavyRainFlag),headline,summary:`${distance} km entfernt${arrival}. ${cellDetails(cell)}.`,source:`DWD KONRAD3D · 5-minütig${nowcast.observedAt?' · aktueller Zelllauf':''}`,official:false}}
 const now=Date.now(),next=hours.filter(hour=>hour.epoch>=now-30*60000&&hour.epoch<=now+3*3600000),thunder=next.find(hour=>[95,96,97,98,99].includes(Math.round(hour.code))),highCape=Math.max(0,...next.map(hour=>Number(hour.cape)||0)),radarRate=Number(radar?.currentRate||0),stationRain=stationRainText(station);
 if(thunder||highCape>=1000){const severe=Boolean(thunder&&[96,97,98,99].includes(Math.round(thunder.code)))||highCape>=1800,extra=[thunder?'Best-Match signalisiert Gewitter':'erhöhte Konvektionsenergie',radarRate>=8?`starkes Radarecho ${Math.round(radarRate)} mm/h`:'',stationRain].filter(Boolean).join(' · ');return{level:severe?'orange':'yellow',headline:'Gewitterpotenzial',summary:`In den kommenden drei Stunden: ${extra}.`,source:'Modell- und Radarabgleich · keine amtliche Warnung',official:false}}
 const source=loading?'KONRAD3D-Abgleich läuft …':error?'KONRAD3D vorübergehend nicht verfügbar':nowcast?.coverage===false?'außerhalb der DWD-KONRAD3D-Kernabdeckung':'DWD KONRAD3D · DWD-Warnungen · Best Match';return{level:'clear',headline:'Keine relevante Gewitterzelle',summary:radarRate>=8?`Aktuell starkes Niederschlagsecho, aber keine Gewitterzelle bestätigt${stationRain?` · ${stationRain}`:''}.`:'Im Nahbereich und im 3-Stunden-Modellfenster kein belastbares Gewittersignal.',source,official:false};
}
