import type {Hour,RadarNowcast,Station,ThunderstormNowcast} from './weather';

export type ThunderInfoLevel='yellow'|'orange'|'red'|'purple';
export type ThunderInfo={level:ThunderInfoLevel;headline:string;summary:string;source:string};
function severityLevel(severity:number,hailFlag:number,heavyRainFlag:number):ThunderInfoLevel{const score=Math.max(Number(severity)||0,Number(hailFlag)||0,Number(heavyRainFlag)||0);return score>=3?'purple':score>=2?'red':score>=1?'orange':'yellow'}
function trendText(value:number){return value>=2?'schnell anwachsend':value===1?'anwachsend':value<=-2?'schnell abschwächend':value===-1?'abschwächend':'stabil'}
function cellDetails(cell:NonNullable<ThunderstormNowcast['nearest']>){const details=[`KONRAD3D ${['schwach','moderat','stark','extrem'][Math.max(0,Math.min(3,Math.round(cell.severity)))]}`,trendText(cell.trend)];if(cell.lightningRate>0)details.push(`${Math.round(cell.lightningRate)} Blitze/5 min`);if(cell.hailFlag>0||cell.areaHail>0)details.push(cell.hailFlag>=2||cell.areaLargeHail>0?'Großhagelsignal':'Hagelsignal');if(cell.heavyRainFlag>0)details.push(`Starkregenstufe ${cell.heavyRainFlag}`);if((cell.gustFlag??0)>0)details.push(`Böenstufe ${cell.gustFlag}`);return details.join(' · ')}
function stationRainText(station:Station|null){const rain=Number(station?.precipitation);if(!Number.isFinite(rain)||rain<.1)return'';return `${station?.provider?.includes('DWD')?'DWD-Station':'Station'} bestätigt Niederschlag`}
export function combineThunderstormInformation(nowcast:ThunderstormNowcast|null,hours:Hour[],radar:RadarNowcast|null,station:Station|null):ThunderInfo|null{
 const cell=nowcast?.nearest;if(nowcast?.available&&cell&&cell.relevanceDistanceKm<=80){const nearNow=cell.currentDistanceKm<=25,approaching=cell.isApproaching&&Number.isFinite(cell.arrivalMinutes)&&Number(cell.arrivalMinutes)<=90,headline=nearNow?'Gewitterzelle nahe':approaching?'Gewitterzelle nähert sich':'Gewitterzelle im Umfeld',distance=Math.round(nearNow?cell.currentDistanceKm:cell.relevanceDistanceKm),arrival=approaching&&!nearNow?` · mögliche Annäherung in etwa ${Math.round(Number(cell.arrivalMinutes))} min`:'';return{level:severityLevel(cell.severity,cell.hailFlag,cell.heavyRainFlag),headline,summary:`${distance} km entfernt${arrival}. ${cellDetails(cell)}.`,source:`DWD KONRAD3D · 5-minütig${nowcast.observedAt?' · aktueller Zelllauf':''} · keine amtliche Warnung`}}
 const now=Date.now(),next=hours.filter(hour=>hour.epoch>=now-30*60000&&hour.epoch<=now+3*3600000),thunder=next.find(hour=>[95,96,97,98,99].includes(Math.round(hour.code))),highCape=Math.max(0,...next.map(hour=>Number(hour.cape)||0)),radarRate=Number(radar?.currentRate||0),stationRain=stationRainText(station),combinedConvectiveSignal=radarRate>=8&&highCape>=750;
 if(!thunder&&!combinedConvectiveSignal)return null;
 const severe=Boolean(thunder&&[96,97,98,99].includes(Math.round(thunder.code)))||highCape>=1800||radarRate>=25,extra=[thunder?'Best Match signalisiert Gewitter':'starkes Radarecho mit erhöhter Konvektionsenergie',radarRate>=8?`Radarecho ${Math.round(radarRate)} mm/h`:'',highCape>=750?`CAPE ${Math.round(highCape)} J/kg`:'',stationRain].filter(Boolean).join(' · ');return{level:severe?'orange':'yellow',headline:'Gewittersignal',summary:`In den kommenden drei Stunden: ${extra}.`,source:'Modell-, Radar- und Stationsabgleich · keine amtliche Warnung'};
}
