import {useEffect,useMemo,useRef,useState,type FormEvent,type ReactNode} from 'react';
import {AlertTriangle,CalendarRange,CheckCircle2,ChevronRight,CloudRain,Droplets,MapPin,Pencil,Pin,RefreshCw,Search,Snowflake,Sparkles,Sun,Thermometer,Wind} from 'lucide-react';
import {label,searchLocations,wind,type Location,type WindUnit} from './weather';
import {WeatherPictogram} from './WeatherPictogram';
import {addDays,bestTravelWindows,dateRange,daysBetween,fetchTravelClimatology,fetchTravelWaterClimatology,summarizeTravelPeriod,travelNarrative,travelPeriod,type TravelConstraints,type TravelPreference,type TravelWaterClimatology,type TravelWindowResult} from './travelPlanner';
import {loadTravelForecastFusion} from './travelForecastFusion';
import {TRAVEL_CENTER_UPDATED_EVENT,buildTravelCenterId,deleteTravelCenterRecord,markTravelCenterOpened,readTravelCenterRecords,upsertTravelCenterRecord,type TravelAnalysisSnapshot,type TravelCenterRecord} from './travelCenter';

type Props={initialLocation:Location;advancedMode:boolean;unit:WindUnit};
type PlannerMode='fixed'|'flexible';
type AnalysisState=TravelAnalysisSnapshot;
type TravelWorkspaceView='overview'|'editor'|'detail';
type ValueEvent={target:{value:string}};
type TravelWaterInfo=TravelWaterClimatology;

const MODE_KEY='mid:travel-planner:mode';
const PREFERENCE_KEY='mid:travel-planner:preference';
const START_KEY='mid:travel-planner:start';
const END_KEY='mid:travel-planner:end';
const TRIP_DAYS_KEY='mid:travel-planner:trip-days';

const PREFERENCES:{id:TravelPreference;label:string;detail:string}[]=[
 {id:'balanced',label:'Ausgewogen',detail:'mild, trocken, sonnig und nicht zu windig'},
 {id:'dry',label:'Möglichst trocken',detail:'wenig Niederschlag und wenige Regentage'},
 {id:'warm',label:'Möglichst warm',detail:'möglichst hohe erwartete Tageshöchstwerte'},
 {id:'cold',label:'Möglichst kalt',detail:'möglichst niedrige erwartete Tageshöchstwerte'},
 {id:'sunny',label:'Möglichst sonnig',detail:'viele Sonnenstunden und wenig Bewölkung'},
 {id:'snow',label:'Hohe Schneelage',detail:'hohe erwartete Schneelage; Klimatologie bleibt Referenz'},
 {id:'calm',label:'Möglichst windarm',detail:'geringe tägliche Windmaxima'}
];

function storageGet(key:string){try{return localStorage.getItem(key)||''}catch{return''}}
function storageSet(key:string,value:string){try{localStorage.setItem(key,value)}catch{}}
function localToday(){try{const parts=new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),get=(type:string)=>parts.find(part=>part.type===type)?.value;return`${get('year')}-${get('month')}-${get('day')}`}catch{return new Date().toISOString().slice(0,10)}}
function validStoredDate(key:string,fallback:string){const value=storageGet(key);return /^\d{4}-\d{2}-\d{2}$/.test(value)?value:fallback}
function validStoredTripDays(fallback:number){const value=Number(storageGet(TRIP_DAYS_KEY));return Number.isFinite(value)?Math.max(2,Math.min(42,Math.round(value))):fallback}
function dateValue(value:string){const match=value.match(/^(\d{4})-(\d{2})-(\d{2})$/);return match?new Date(Date.UTC(Number(match[1]),Number(match[2])-1,Number(match[3]),12)):new Date(Number.NaN)}
function formatDate(value:string,withYear=false){const date=dateValue(value);return Number.isFinite(date.getTime())?new Intl.DateTimeFormat('de-DE',{timeZone:'UTC',weekday:'short',day:'2-digit',month:'2-digit',year:withYear?'numeric':undefined}).format(date):value}
function formatPeriod(start:string,end:string){const startYear=start.slice(0,4),endYear=end.slice(0,4);return`${formatDate(start,startYear!==endYear)} – ${formatDate(end,true)}`}
function number(value:number,digits=1){return new Intl.NumberFormat('de-DE',{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(value)}
function optionalNumber(value:string){if(!value.trim())return undefined;const parsed=Number(value.replace(',','.'));return Number.isFinite(parsed)?parsed:undefined}
function destinationLabel(location:Location){return[location.icao?`${location.icao} · ${location.name}`:location.name,location.admin1,location.country].filter(Boolean).join(', ')}
function preferenceLabel(value:TravelPreference){return PREFERENCES.find(item=>item.id===value)?.label??value}
function windUnitLabel(unit:WindUnit){return unit==='kn'?'kt':unit==='kmh'?'km/h':unit==='ms'?'m/s':'mph'}
function windInputToKnots(value:number|undefined,unit:WindUnit){if(!Number.isFinite(value))return undefined;const numeric=Number(value);if(unit==='kmh')return numeric/1.852;if(unit==='ms')return numeric/0.514444;if(unit==='mph')return numeric/1.15078;return numeric}
function Metric({iconNode,labelText,value,detail}:{iconNode:ReactNode;labelText:string;value:string;detail:string}){return <article>{iconNode}<small>{labelText}</small><strong>{value}</strong><span>{detail}</span></article>}

export default function TravelPlannerPanel({initialLocation,advancedMode,unit}:Props){
 const initialStart=addDays(localToday(),30),initialEnd=addDays(initialStart,13),storedStart=validStoredDate(START_KEY,initialStart),storedEndRaw=validStoredDate(END_KEY,initialEnd),storedEnd=daysBetween(storedStart,storedEndRaw)>=0?storedEndRaw:storedStart,[destination,setDestination]=useState<Location>(initialLocation),[destinationSource,setDestinationSource]=useState<'current'|'custom'>('current'),[query,setQuery]=useState(''),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState(''),[searchResults,setSearchResults]=useState<Location[]>([]),[mode,setMode]=useState<PlannerMode>(()=>storageGet(MODE_KEY)==='flexible'?'flexible':'fixed'),[start,setStart]=useState(storedStart),[end,setEnd]=useState(storedEnd),[tripDays,setTripDays]=useState(()=>validStoredTripDays(14)),[alternativeGapDays,setAlternativeGapDays]=useState(()=>validStoredTripDays(14)),[preference,setPreference]=useState<TravelPreference>(()=>PREFERENCES.some(item=>item.id===storageGet(PREFERENCE_KEY))?storageGet(PREFERENCE_KEY) as TravelPreference:'balanced'),[minAvgMax,setMinAvgMax]=useState(''),[maxAvgMax,setMaxAvgMax]=useState(''),[maxWetDays,setMaxWetDays]=useState(''),[minSunHours,setMinSunHours]=useState(''),[maxWind,setMaxWind]=useState(''),[minSnowDepth,setMinSnowDepth]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[analysis,setAnalysis]=useState<AnalysisState|null>(null),[activeIndex,setActiveIndex]=useState(0),[waterInfo,setWaterInfo]=useState<TravelWaterInfo|null>(null),[waterError,setWaterError]=useState(''),[savedTrips,setSavedTrips]=useState<TravelCenterRecord[]>(()=>readTravelCenterRecords()),[selectedTripId,setSelectedTripId]=useState<string|null>(null),[workspaceView,setWorkspaceView]=useState<TravelWorkspaceView>(()=>readTravelCenterRecords().length?'overview':'editor'),searchController=useRef<AbortController|null>(null),analysisController=useRef<AbortController|null>(null);
 useEffect(()=>()=>{searchController.current?.abort();analysisController.current?.abort()},[]);
 useEffect(()=>{const sync=()=>setSavedTrips(readTravelCenterRecords());window.addEventListener(TRAVEL_CENTER_UPDATED_EVENT,sync);window.addEventListener('storage',sync);return()=>{window.removeEventListener(TRAVEL_CENTER_UPDATED_EVENT,sync);window.removeEventListener('storage',sync)}},[]);
 const preferenceInfo=PREFERENCES.find(item=>item.id===preference)??PREFERENCES[0],constraints=useMemo<TravelConstraints>(()=>{const windLimit=optionalNumber(maxWind),snowDepthLimit=optionalNumber(minSnowDepth);return{minAvgMax:optionalNumber(minAvgMax),maxAvgMax:optionalNumber(maxAvgMax),maxWetDays:optionalNumber(maxWetDays),minSunHoursPerDay:optionalNumber(minSunHours),maxWindKt:windInputToKnots(windLimit,unit),maxWindLabel:Number.isFinite(windLimit)?`${number(Number(windLimit))} ${windUnitLabel(unit)}`:undefined,minSnowDepthCm:Number.isFinite(snowDepthLimit)?Math.max(0,Math.round(Number(snowDepthLimit))):undefined}},[minAvgMax,maxAvgMax,maxWetDays,minSunHours,maxWind,minSnowDepth,unit]),active=analysis?.windows[activeIndex]??analysis?.windows[0],span=dateRange(start,end).length,minAlternativeGapDays=Math.max(1,Math.ceil(tripDays/2)),snowDepthRequired=mode==='fixed'||(mode==='flexible'&&(preference==='snow'||Number.isFinite(constraints.minSnowDepthCm)));
 useEffect(()=>{if(destinationSource==='current')setDestination(initialLocation)},[destinationSource,initialLocation]);
 useEffect(()=>{storageSet(START_KEY,start)},[start]);
 useEffect(()=>{storageSet(END_KEY,end)},[end]);
 useEffect(()=>{storageSet(TRIP_DAYS_KEY,String(tripDays))},[tripDays]);
 useEffect(()=>{if(daysBetween(start,end)<0)setEnd(start)},[start,end]);
 function updateStart(next:string){setStart(next);if(daysBetween(next,end)<0)setEnd(next)}
 function updateEnd(next:string){setEnd(daysBetween(start,next)<0?start:next)}
 useEffect(()=>{
  if(!analysis||!active){setWaterInfo(null);setWaterError('');return}
  const controller=new AbortController();let cancelled=false;setWaterError('');
  fetchTravelWaterClimatology(destination,active.start,active.end,controller.signal).then(info=>{if(cancelled||controller.signal.aborted)return;setWaterInfo(info);setWaterError('')}).catch(reason=>{if(cancelled||controller.signal.aborted)return;setWaterInfo(null);setWaterError(reason instanceof Error?reason.message:'Historische Wassertemperatur ist vorübergehend nicht verfügbar.')});
  return()=>{cancelled=true;controller.abort()}
 },[analysis,active?.start,active?.end,destination.latitude,destination.longitude,destination.id]);

 async function runSearch(event:FormEvent){event.preventDefault();const value=query.trim();if(value.length<2){setSearchError('Bitte mindestens zwei Zeichen eingeben.');return}searchController.current?.abort();const controller=new AbortController();searchController.current=controller;setSearching(true);setSearchError('');try{const results=await searchLocations(value,controller.signal);setSearchResults(results);if(!results.length)setSearchError('Kein passender Ort gefunden.')}catch(reason){if(!controller.signal.aborted)setSearchError(reason instanceof Error?reason.message:'Ortssuche fehlgeschlagen.')}finally{if(searchController.current===controller&&!controller.signal.aborted)setSearching(false)}}
 function chooseLocation(location:Location,source:'current'|'custom'='custom'){setDestination(location);setDestinationSource(source);setSearchResults([]);setQuery('');setSearchError('')}
 function changeMode(next:PlannerMode){setMode(next);storageSet(MODE_KEY,next);setAnalysis(null);setError('')}
 async function analyse(event:FormEvent){
  event.preventDefault();setError('');setAnalysis(null);setWaterInfo(null);setWaterError('');setActiveIndex(0);
  if(!destination){setError('Bitte zuerst einen Zielort auswählen.');return}
  if(!span||span<1){setError('Der gewählte Zeitraum ist ungültig.');return}
  if(span>120){setError('Der auswertbare Zeitraum ist auf 120 Tage begrenzt.');return}
  if(mode==='flexible'&&(tripDays<2||tripDays>42||tripDays>span)){setError('Die Reisedauer muss zwischen 2 und 42 Tagen liegen und in den Suchzeitraum passen.');return}
  const includeSnowDepth=snowDepthRequired;setLoading(true);storageSet(PREFERENCE_KEY,preference);
  analysisController.current?.abort();const controller=new AbortController();analysisController.current=controller;
  try{
   const climateDataset=await fetchTravelClimatology(destination,includeSnowDepth,controller.signal);if(mode==='flexible'&&preference==='snow'&&!climateDataset.snowDepthIncluded)throw new Error(climateDataset.snowDepthWarning||'Historische Schneehöhe ist derzeit nicht verfügbar; „Hohe Schneelage“ kann deshalb nicht belastbar optimiert werden.');
   const fusion=await loadTravelForecastFusion(destination,climateDataset,start,end,controller.signal).catch(reason=>{if(controller.signal.aborted)throw reason;return{dataset:climateDataset,sourceMode:'Nur Klimatologie' as const,sourceDetail:`Aktuelle Modellquellen konnten nicht vollständig ausgewertet werden; ${climateDataset.source} (${climateDataset.referencePeriod}) bleibt die Basis.`,modelSharePct:0,modelFamilyCount:0,modelCoveredDays:0,modelSources:[] as string[],sourceStatuses:[] as import('./travelForecastFusion').TravelForecastSourceStatus[],warnings:[reason instanceof Error?reason.message:String(reason)]}}),dataset=fusion.dataset;let windows:TravelWindowResult[];
   if(mode==='fixed'){
    const points=travelPeriod(dataset,start,end);if(points.length!==span)throw new Error('Für den gewählten Zeitraum fehlen Tageswerte.');const summary=summarizeTravelPeriod(points);windows=[{start,end,points,summary,score:0,meetsAll:true,unmet:[]}];
   }else{
    const candidates=bestTravelWindows(dataset,start,end,tripDays,preference,constraints,120);windows=[];for(const candidate of candidates){if(windows.some(existing=>Math.abs(daysBetween(existing.start,candidate.start))<alternativeGapDays))continue;windows.push(candidate);if(windows.length>=3)break}
   }
   if(!windows.length)throw new Error('Innerhalb des Suchzeitraums konnte kein vollständiges Reisezeitfenster gebildet werden.');let initialWater:TravelWaterInfo|null=null;try{initialWater=await fetchTravelWaterClimatology(destination,windows[0].start,windows[0].end,controller.signal);setWaterError('')}catch(reason){if(controller.signal.aborted)throw reason;setWaterError(reason instanceof Error?reason.message:'Historische Wassertemperatur ist vorübergehend nicht verfügbar.')}setWaterInfo(initialWater);setAnalysis({windows,snowDepthIncluded:dataset.snowDepthIncluded,snowDepthWarning:dataset.snowDepthWarning,referencePeriod:dataset.referencePeriod,source:dataset.source,sourceMode:fusion.sourceMode,sourceDetail:fusion.sourceDetail,modelSharePct:fusion.modelSharePct,modelFamilyCount:fusion.modelFamilyCount,modelCoveredDays:fusion.modelCoveredDays,modelSources:fusion.modelSources,sourceStatuses:fusion.sourceStatuses,sourceWarnings:fusion.warnings});setSelectedTripId(null);setWorkspaceView('detail');
  }catch(reason){if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:'Klimatologische Auswertung fehlgeschlagen.')}finally{if(analysisController.current===controller&&!controller.signal.aborted)setLoading(false)}
 }
 function applyRecord(record:TravelCenterRecord,view:TravelWorkspaceView){
  setDestination(record.location);setDestinationSource('custom');setMode(record.mode);setStart(record.start);setEnd(record.end);setTripDays(record.tripDays);setAlternativeGapDays(record.alternativeGapDays);setPreference(record.preference);setMinAvgMax(record.constraintInputs.minAvgMax);setMaxAvgMax(record.constraintInputs.maxAvgMax);setMaxWetDays(record.constraintInputs.maxWetDays);setMinSunHours(record.constraintInputs.minSunHours);setMaxWind(record.constraintInputs.maxWind);setMinSnowDepth(record.constraintInputs.minSnowDepth);setAnalysis(record.analysis);setActiveIndex(Math.max(0,Math.min(record.analysis.windows.length-1,record.activeIndex)));setWaterInfo(record.waterInfo);setSelectedTripId(record.id);markTravelCenterOpened(record.id);setWorkspaceView(view);setError('');setWaterError('');
 }
 function pinCurrentTrip(){
  if(!analysis||!active)return;const now=Date.now(),previous=selectedTripId?savedTrips.find(item=>item.id===selectedTripId):null,id=previous?.id??buildTravelCenterId(destination,active.start,active.end),record:TravelCenterRecord={id,title:destination.name,location:destination,mode,start,end,tripDays,alternativeGapDays,preference,constraintInputs:{minAvgMax,maxAvgMax,maxWetDays,minSunHours,maxWind,minSnowDepth},activeIndex,createdAt:previous?.createdAt??now,updatedAt:now,lastOpenedAt:now,analysis,waterInfo};upsertTravelCenterRecord(record);setSavedTrips(readTravelCenterRecords());setSelectedTripId(id);setWorkspaceView('detail');
 }
 function unpinTrip(record:TravelCenterRecord){deleteTravelCenterRecord(record.id);const records=readTravelCenterRecords();setSavedTrips(records);if(selectedTripId===record.id){setSelectedTripId(null);if(workspaceView!=='editor')setWorkspaceView(records.length?'overview':'editor')}}
 function startNewTrip(){setSelectedTripId(null);setAnalysis(null);setWaterInfo(null);setWaterError('');setError('');setWorkspaceView('editor')}
 const selectedTrip=selectedTripId?savedTrips.find(item=>item.id===selectedTripId)??null:null;
 return <section className="travel-planner">
  <header className="travel-head forecast-entry-head forecast-entry-head-travel"><div><span>REISEPLANUNG</span><h3>Reisewetter & Reiseplaner</h3><p>Geplante Reisen festpinnen, meteorologische Eckdaten vergleichen und bei Bedarf vollständig auswerten.</p></div><span className="travel-climate-badge">Prognose · Witterung · Klima</span></header>

  <nav className="travel-center-nav" aria-label="Reise-Center">
   <button type="button" className={workspaceView==='overview'?'active':''} onClick={()=>setWorkspaceView(savedTrips.length?'overview':'editor')}><span>Übersicht</span><small>{savedTrips.length} festgepinnt</small></button>
   <button type="button" className={workspaceView==='editor'?'active':''} onClick={()=>setWorkspaceView('editor')}><span>Planung</span><small>Reise anlegen oder ändern</small></button>
   <button type="button" className={workspaceView==='detail'?'active':''} disabled={!analysis||!active} onClick={()=>analysis&&active&&setWorkspaceView('detail')}><span>Details</span><small>Komplette Auswertung</small></button>
  </nav>

  {workspaceView==='overview'&&<section className="travel-center-overview">
   <header><div><span>REISE-CENTER</span><h4>Festgepinnte Reisen</h4><small>Die Karten zeigen die meteorologischen Eckdaten der letzten Auswertung. „Details“ öffnet den vollständigen Reiseüberblick.</small></div><button type="button" className="primary" onClick={startNewTrip}><CalendarRange size={15}/> Neue Reise</button></header>
   {savedTrips.length?<div className="travel-center-grid">{savedTrips.map(record=>{const window=record.analysis.windows[record.activeIndex]??record.analysis.windows[0],summary=window?.summary;if(!summary)return null;return <article key={record.id} className={record.id===selectedTripId?'active':''}>
    <button type="button" className="travel-center-unpin" onClick={()=>unpinTrip(record)} aria-label="Reise lösen" title="Reise lösen"><Pin size={15} fill="currentColor"/></button>
    <div className="travel-center-card-head"><span><strong>{record.title||record.location.name}</strong><small>{formatPeriod(window.start,window.end)} · {record.mode==='flexible'?preferenceLabel(record.preference):'Fester Zeitraum'}</small></span><MapPin size={16}/></div>
    <div className="travel-center-quick-metrics">
     <span><Thermometer size={13}/><b>{number(summary.avgMax,0)}° / {number(summary.avgMin,0)}°</b><small>Tmax / Tmin</small></span>
     <span><CloudRain size={13}/><b>{number(summary.precipitationTotal,0)} mm</b><small>≈ {number(summary.wetDaysExpected,0)} Regentage</small></span>
     <span><Sun size={13}/><b>{number(summary.sunshinePerDay)} h</b><small>Sonne/Tag</small></span>
     <span><Wind size={13}/><b>{wind(summary.windMaxMean,unit)}</b><small>Windmaximum</small></span>
     <span><Snowflake size={13}/><b>{record.analysis.snowDepthIncluded&&Number.isFinite(summary.snowDepthMean)?`${number(Number(summary.snowDepthMean),0)} cm`:`Σ ${number(summary.snowfallTotal)} cm`}</b><small>{record.analysis.snowDepthIncluded?'Schneehöhe':'Schneefall'}</small></span>
     {record.waterInfo?<span><Droplets size={13}/><b>{number(record.waterInfo.temperature)} °C</b><small>Wasser</small></span>:null}
    </div>
    <div className="travel-center-source"><small>{record.analysis.sourceMode||'Klimatologie'}</small><span>{record.analysis.source}</span></div>
    <footer><button type="button" className="primary" onClick={()=>applyRecord(record,'detail')}>Details <ChevronRight size={14}/></button><button type="button" className="secondary" onClick={()=>applyRecord(record,'editor')}><Pencil size={14}/> Bearbeiten</button></footer>
   </article>})}</div>:<div className="travel-center-empty"><CalendarRange size={18}/><span>Noch keine Reise festgepinnt.</span><button type="button" className="primary" onClick={startNewTrip}>Erste Reise planen</button></div>}
  </section>}

  {workspaceView==='editor'&&<>
  <div className="travel-destination-card">
   <div className="travel-selected-destination"><MapPin size={18}/><span><small>{destinationSource==='current'?'Aktuell ausgewählter MID-Ort':'Ausgewähltes Reiseziel'}</small><strong>{destinationLabel(destination)}</strong><em>{number(destination.latitude,2)}°, {number(destination.longitude,2)}°{Number.isFinite(destination.elevation)?` · ${Math.round(Number(destination.elevation))} m ü. NHN`:''}</em></span><button type="button" className="secondary" onClick={()=>chooseLocation(initialLocation,'current')}>Aktueller MID-Ort</button></div>
   <form className="travel-location-search" onSubmit={runSearch}><label><span>Anderes Reiseziel suchen</span><div><Search size={16}/><input value={query} onChange={(event:ValueEvent)=>setQuery(event.target.value)} placeholder="Ort, Region, Reiseziel oder ICAO"/></div></label><button type="submit" className="secondary" disabled={searching}>{searching?<RefreshCw className="spin" size={16}/>:<Search size={16}/>} Suchen</button></form>
   {searchError&&<small className="travel-search-error">{searchError}</small>}
   {searchResults.length>0&&<div className="travel-search-results" role="listbox" aria-label="Reiseziele">{searchResults.slice(0,8).map(location=><button type="button" key={`${location.id}:${location.latitude}:${location.longitude}`} onClick={()=>chooseLocation(location)}><MapPin size={15}/><span><strong>{location.icao?`${location.icao} · ${location.name}`:location.name}</strong><small>{[location.poiCategory,location.admin1,location.country].filter(Boolean).join(' · ')||`${number(location.latitude,2)}°, ${number(location.longitude,2)}°`}</small></span></button>)}</div>}
  </div>

  <div className="travel-mode-switch" role="tablist" aria-label="Planungsart"><button type="button" className={mode==='fixed'?'active':''} onClick={()=>changeMode('fixed')} aria-selected={mode==='fixed'}><CalendarRange size={16}/><span><strong>Fester Zeitraum</strong><small>Erwartbares Klima anzeigen</small></span></button><button type="button" className={mode==='flexible'?'active':''} onClick={()=>changeMode('flexible')} aria-selected={mode==='flexible'}><Sparkles size={16}/><span><strong>Bestes Zeitfenster</strong><small>Kürzere Reise im Suchraum finden</small></span></button></div>

  <form className="travel-plan-form" onSubmit={analyse}>
   <div className="travel-period-fields"><label><span>{mode==='fixed'?'Reisebeginn':'Suchzeitraum von'}</span><input type="date" value={start} onChange={(event:ValueEvent)=>updateStart(event.target.value)}/></label><label><span>{mode==='fixed'?'Reiseende':'Suchzeitraum bis'}</span><input type="date" value={end} min={start} onChange={(event:ValueEvent)=>updateEnd(event.target.value)}/></label>{mode==='flexible'&&<><label><span>Gewünschte Reisedauer</span><div className="travel-duration"><input type="number" min="2" max="42" value={tripDays} onChange={(event:ValueEvent)=>{const next=Math.max(2,Math.min(42,Number(event.target.value)||2));setTripDays(next);setAlternativeGapDays(next)}}/><b>Tage</b></div></label><label><span>Mindestabstand Alternativen</span><div className="travel-duration"><input type="number" min={minAlternativeGapDays} max="120" value={alternativeGapDays} onChange={(event:ValueEvent)=>setAlternativeGapDays(Math.max(minAlternativeGapDays,Math.min(120,Number(event.target.value)||minAlternativeGapDays)))}/><b>Tage</b></div><small>Standard: Reisedauer · Minimum: 50 % der Reisedauer</small></label></>}</div>
   {mode==='flexible'&&<div className="travel-preference"><label><span>Optimieren für</span><select value={preference} onChange={(event:ValueEvent)=>setPreference(event.target.value as TravelPreference)}>{PREFERENCES.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select><small>{preferenceInfo.detail}</small></label>{preference==='snow'&&<div className="travel-snow-detail"><Snowflake size={16}/><span><strong>Schneehöhe ist das Optimierungskriterium</strong><small>MID lädt dafür die historische Schneehöhe automatisch. Kumulierter Schneefall wird separat zusätzlich ausgewiesen und bestimmt nicht das beste Zeitfenster.</small></span></div>}</div>}
   {mode==='flexible'&&<details className="travel-constraints"><summary>Eigene Bedingungen <small>optional</small></summary><div><label><span>Mind. Ø Tageshöchstwert</span><input inputMode="decimal" value={minAvgMax} onChange={(event:ValueEvent)=>setMinAvgMax(event.target.value)} placeholder="z. B. 24"/><b>°C</b></label><label><span>Max. Ø Tageshöchstwert</span><input inputMode="decimal" value={maxAvgMax} onChange={(event:ValueEvent)=>setMaxAvgMax(event.target.value)} placeholder="z. B. 5"/><b>°C</b></label><label><span>Max. erwartete Regentage</span><input inputMode="decimal" value={maxWetDays} onChange={(event:ValueEvent)=>setMaxWetDays(event.target.value)} placeholder="z. B. 3"/><b>Tage</b></label><label><span>Mind. Sonne pro Tag</span><input inputMode="decimal" value={minSunHours} onChange={(event:ValueEvent)=>setMinSunHours(event.target.value)} placeholder="z. B. 6"/><b>h</b></label><label><span>Max. Ø Windmaximum</span><input inputMode="decimal" value={maxWind} onChange={(event:ValueEvent)=>setMaxWind(event.target.value)} placeholder={unit==='kn'?'z. B. 15':unit==='kmh'?'z. B. 25':unit==='ms'?'z. B. 7':'z. B. 16'}/><b>{windUnitLabel(unit)}</b></label><label><span>Mind. mittlere Schneehöhe</span><input type="number" inputMode="numeric" min="0" step="1" value={minSnowDepth} onChange={(event:ValueEvent)=>setMinSnowDepth(event.target.value)} placeholder="z. B. 30"/><b>cm</b></label></div><p>Leere Felder werden nicht berücksichtigt. Bei „Hohe Schneelage“ oder einer Mindestschneehöhe lädt MID automatisch zusätzliche historische Schneehöhendaten.</p></details>}
   <button type="submit" className="primary travel-analyse" disabled={loading}>{loading?<RefreshCw className="spin" size={17}/>:mode==='flexible'?<Sparkles size={17}/>:<CalendarRange size={17}/>} {loading?'Prognose & Klima werden ausgewertet …':mode==='flexible'?'Bestes Reisezeitfenster finden':'Reisewetter auswerten'}</button>
  </form>
  </>}

  {workspaceView!=='overview'&&<div className="travel-method-note"><AlertTriangle size={15}/><span>MID nutzt für konkrete Reisetermine zuerst die tatsächlich verfügbare Prognoseskala: operationelle Multi-Modell-Ensembles bis etwa Tag 14, danach gedämpfte EC46-Wochenanomalien mit GEFS-Bestätigung und ab Tag 47 nur noch schwach gewichtete Saisonanomalien. Mit wachsendem Vorlauf gewinnt die ERA5-Seamless-Klimatologie 1991–2020 bewusst an Gewicht; nicht verfügbare Parameter bleiben klimatologisch. Dadurch werden Mittelfrist- und Witterungssignale übernommen, ohne für weit entfernte Tage Scheingenauigkeit zu erzeugen. Für Küstenorte bleibt NOAA OISST v2.1 die klimatologische Wassertemperatur-Referenz.</span></div>}
  {workspaceView!=='overview'&&error&&<div className="error">{error}</div>}
  {workspaceView!=='overview'&&loading&&<div className="travel-loading"><RefreshCw className="spin" size={20}/><div><strong>Prognose, Witterung und Klimareferenz werden zusammengeführt</strong><span>{snowDepthRequired?'Zusätzlich wird die Schneehöhenreferenz berücksichtigt; Quellen außerhalb ihres gültigen Horizonts werden nicht unnötig geladen.':'MID lädt nur Quellen, deren Prognosehorizont den gewählten Reisezeitraum tatsächlich erreicht.'}</span></div></div>}

  {workspaceView==='detail'&&analysis&&active&&<section className="travel-result">
   <header><div><span>{mode==='flexible'?'EMPFOHLENES REISEFENSTER':'ERWARTBARES REISEWETTER'}</span><h4>{formatPeriod(active.start,active.end)}</h4><p>{destinationLabel(destination)} · {active.summary.days} Tage{mode==='flexible'?` · ${preferenceLabel(preference)}`:''}</p></div>{mode==='flexible'&&(active.meetsAll?<span className="travel-match good"><CheckCircle2 size={15}/> Bedingungen erfüllt</span>:<span className="travel-match partial"><AlertTriangle size={15}/> Beste Annäherung</span>)}</header>
   <div className="travel-result-toolbar"><button type="button" className="secondary" onClick={()=>setWorkspaceView('overview')} disabled={!savedTrips.length}>Übersicht</button><button type="button" className="secondary" onClick={()=>setWorkspaceView('editor')}><Pencil size={14}/> Planung bearbeiten</button><button type="button" className="primary" onClick={pinCurrentTrip}><Pin size={14} fill={selectedTrip?'currentColor':'none'}/>{selectedTrip?'Festgepinnt aktualisieren':'Reise festpinnen'}</button></div>
   {mode==='flexible'&&analysis.windows.length>1&&<div className="travel-alternatives" aria-label="Alternative Reisezeiträume">{analysis.windows.map((window,index)=><button type="button" className={index===activeIndex?'active':''} key={window.start} onClick={()=>setActiveIndex(index)}><small>{index===0?'Beste Wahl':`Alternative ${index}`}</small><strong>{formatPeriod(window.start,window.end)}</strong></button>)}</div>}
   <div className="travel-summary-text"><Sparkles size={18}/><p>{travelNarrative(active.summary,preference,analysis.snowDepthIncluded,analysis.sourceMode)}</p></div>
   {!active.meetsAll&&active.unmet.length>0&&<div className="travel-unmet"><strong>Nicht vollständig erfüllt:</strong><span>{active.unmet.join(' · ')}</span></div>}
   {analysis.snowDepthWarning&&<div className="travel-snow-warning"><Snowflake size={15}/><span>{analysis.snowDepthWarning} Kumulierter Schneefall bleibt separat verfügbar, ersetzt aber keine Schneehöhenbewertung.</span></div>}
   {waterError&&<div className="travel-snow-warning"><Droplets size={15}/><span>{waterError} Die übrige Reiseklimatologie bleibt davon unberührt; MID versucht die SST beim nächsten Abruf erneut.</span></div>}
   <div className="travel-metrics">
    <Metric iconNode={<Thermometer/>} labelText="Temperatur" value={`${number(active.summary.avgMax)} / ${number(active.summary.avgMin)} °C`} detail={`Ø Höchst / Tiefst · häufig ${number(active.summary.avgMaxP25)}–${number(active.summary.avgMaxP75)} °C`}/>
    <Metric iconNode={<CloudRain/>} labelText="Niederschlag" value={`${number(active.summary.precipitationTotal)} mm`} detail={`rund ${Math.round(active.summary.wetDaysExpected)} Tage mit ≥ 1 mm`}/>
    <Metric iconNode={<Sun/>} labelText="Sonnenschein" value={`${number(active.summary.sunshinePerDay)} h/Tag`} detail={`${number(active.summary.sunshineTotal)} h im Zeitraum`}/>
    <Metric iconNode={<Wind/>} labelText="Wind" value={wind(active.summary.windMaxMean,unit)} detail="Ø tägliches Windmaximum"/>
    <Metric iconNode={<Snowflake/>} labelText={mode==='fixed'||analysis.snowDepthIncluded?'Schneelage':'Schneefall'} value={analysis.snowDepthIncluded&&Number.isFinite(active.summary.snowDepthMean)?`${number(Number(active.summary.snowDepthMean),0)} cm`:mode==='fixed'?'—':`${number(active.summary.snowfallTotal)} cm`} detail={analysis.snowDepthIncluded?`Ø modellierte Schneehöhe${Number.isFinite(active.summary.snowCoverDaysExpected)?` · Schneedecke etwa ${number(Number(active.summary.snowCoverDaysExpected))} Tage`:''} · Schneefall Σ ${number(active.summary.snowfallTotal)} cm`:mode==='fixed'?`Modellierte Schneehöhe derzeit nicht verfügbar · Schneefall Σ ${number(active.summary.snowfallTotal)} cm`:'kumulierter langjähriger Schneefall im Zeitraum'}/>
    {waterInfo&&<Metric iconNode={<Droplets/>} labelText="Wassertemperatur" value={`${number(waterInfo.temperature)} °C`} detail={`NOAA-OISST-Mittel für den Reisezeitraum · ${waterInfo.referencePeriod} · nächstes Meeresgitter ${number(waterInfo.gridDistanceKm,0)} km`}/>} 
   </div>
   <div className="travel-daily-climate"><header><div><span>{analysis.sourceMode==='Nur Klimatologie'?'KLIMAVERLAUF':'ERWARTETER VERLAUF'}</span><h5>{analysis.sourceMode==='Nur Klimatologie'?'Typische Bedingungen im Zeitraum':'Modellgestützte Erwartung mit Klimareferenz'}</h5></div><small>horizontal wischen</small></header><div className="travel-day-strip">{active.points.map(point=><article key={point.date}><time>{formatDate(point.date)}</time><span className="travel-day-icon"><WeatherPictogram code={point.weatherCode} day title={label(point.weatherCode)}/></span><strong>{number(point.maxMean,0)}°</strong><small>{number(point.minMean,0)}°</small><span className="travel-day-rain"><CloudRain size={12}/>{number(point.wetProbability,0)} %</span><span className="travel-day-sun"><Sun size={12}/>{number(point.sunshineMeanHours)} h</span>{analysis.snowDepthIncluded&&Number.isFinite(point.snowDepthMean)&&<span className="travel-day-snow"><Snowflake size={12}/>{number(Number(point.snowDepthMean),0)} cm</span>}</article>)}</div></div>
   <details className="travel-source-details" open={advancedMode}><summary><span><b>{analysis.sourceMode||'Nur Klimatologie'}</b><small>{analysis.modelCoveredDays?`${analysis.modelCoveredDays} Tage modellgestützt · Ø ${analysis.modelSharePct??0} % aktueller Modellanteil · ${analysis.modelFamilyCount??0} unabhängige Modellfamilien`:`Klimatologische Referenz ${analysis.referencePeriod}`}</small></span><ChevronRight size={15}/></summary><div className="travel-source-details-body"><p>{analysis.sourceDetail||`Quelle: ${analysis.source} · Referenzperiode ${analysis.referencePeriod}`}</p>{analysis.modelSources?.length?<p><strong>Verwendete Modellfamilien:</strong> {analysis.modelSources.join(' · ')}</p>:null}{analysis.sourceStatuses?.length?<div className="travel-source-status-grid">{analysis.sourceStatuses.map(status=><article key={status.id} className={status.state}><header><strong>{status.label}</strong><span>{status.state==='used'?'verwendet':status.state==='outside-horizon'?'außerhalb Horizont':'nicht verfügbar'}</span></header><small>{status.coverage}{status.parameters.length?` · ${status.parameters.join(', ')}`:''}</small><p>{status.detail}</p></article>)}</div>:null}{analysis.sourceWarnings?.length?<p className="travel-source-warning"><AlertTriangle size={13}/>{analysis.sourceWarnings.join(' · ')}</p>:null}</div></details><footer><span>Basis: {analysis.source} · Referenzperiode {analysis.referencePeriod}</span><small>{advancedMode?'Operationelle Prognosen dominieren nur innerhalb ihres belastbaren Horizonts. Subseasonal-/Seasonal-Anomalien werden gegen modellkonsistente Hindcasts bzw. unabhängige Modellfamilien interpretiert und mit wachsendem Vorlauf zur lokalen Klimatologie hin regularisiert.':'Je weiter der Reisetermin entfernt ist, desto stärker dient die Klimatologie als Referenz statt einer scheinpräzisen Tagesvorhersage.'}</small></footer>
  </section>}

 </section>;
}
