import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Layers3} from 'lucide-react';
import {unifiedMapPresentation,unifiedWmsLineStyle,unifiedWmsFillStyle,nativeIsobarFeatures} from './unifiedMapPresentation';
import RadarPanel from './RadarPanel';
import {GeoJsonLayers,HtmlMarker,ImageQuadLayer,MapCenter,WmsTileLayer} from './MapLibreCore';
import ModelMapContextOverlay from './ModelMapContextOverlay';
import ModelMapProbe from './ModelMapProbe';
import ModelMapScaleLegend from './ModelMapScaleLegend';
import {loadNativeIndex,loadNativeField,nativeAt,nativeMapScale,nativeRaster,type NativeField,type NativeFieldKind,type NativeIndex} from './nativeModelFields';
import {loadTotals,loadTotalsAvailability,totalsAt,totalsMapScale,totalsRaster,totalsStartAt,type TotalsData} from './precipitationTotals';
import {modelMapUnit,modelMapValue} from './modelMapUnits';
import {exportNativeField} from './nativeModelMapExport';
import {exportTotals} from './precipitationTotalsExport';
import {compactPrecipitationAmount} from './forecastAmountFormat';
import {mapScaleTicks,type MapColorMode} from './modelMapColorScale';
import {availableUnifiedParameters,nearestUnifiedFrame,nearestUnifiedTime,readUnifiedMapSettings,UNIFIED_MAP_PARAMETERS,UNIFIED_MAP_SETTINGS_KEY,unifiedModelForParameter,unifiedSources,type UnifiedMapSettings} from './unifiedMapCatalog';
import {writeDurableStorageValue} from './storageSafety';
import type {WeatherMapFavoriteLocation} from './PrecipitationTotalsMap';
import type {RadarNowcast,ThunderstormNowcast,WindUnit} from './weather';
import {unifiedWmsChoices,unifiedWmsProduct} from './unifiedWmsCatalog';
import {loadWeatherMapMetadata,weatherMapAvailableTimes,weatherMapWmsProxy,loadWeatherMapPoint,type WeatherMapMetadata,type WeatherMapModelId} from './WeatherMapsData';
import './UnifiedWeatherMap.css';
import './weatherMapsTotals.css';

type Props={lat:number;lon:number;timezone:string;locationName:string;analysis:RadarNowcast|null;thunder:ThunderstormNowcast|null;isDay:boolean;actualLocation:boolean;focusMode:boolean;favorites:WeatherMapFavoriteLocation[];unit?:WindUnit;requestedProductId?:string};
const timeLabel=(time:string,timezone:string)=>new Intl.DateTimeFormat('de-DE',{timeZone:timezone,day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',timeZoneName:'short'}).format(new Date(time));
const htmlEscape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));

export default function UnifiedWeatherMap(props:Props){
 const [settings,setSettings]=useState(readUnifiedMapSettings),settingsRef=useRef(settings);
 const update=(patch:Partial<UnifiedMapSettings>)=>{const next={...settingsRef.current,...patch};writeDurableStorageValue(UNIFIED_MAP_SETTINGS_KEY,JSON.stringify({...next,updatedAt:Date.now()}));settingsRef.current=next;setSettings(next)};
 const [catalog,setCatalog]=useState<{index:NativeIndex;base:string}|null>(null),[totals,setTotals]=useState<TotalsData|null>(null),[observed,setObserved]=useState<TotalsData|null>(null),[catalogErrors,setCatalogErrors]=useState<string[]>([]),[revision,setRevision]=useState(0),[target,setTarget]=useState(Date.now()),[field,setField]=useState<NativeField|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[colorMode,setColorMode]=useState<MapColorMode>('absolute'),[selected,setSelected]=useState(''),[exporting,setExporting]=useState(false);
 const [metadata,setMetadata]=useState<WeatherMapMetadata|null>(null),[wmsError,setWmsError]=useState(''),[loadedWms,setLoadedWms]=useState<Set<string>>(()=>new Set()),[pressureField,setPressureField]=useState<NativeField|null>(null),[pressureError,setPressureError]=useState('');
 const fieldCache=useRef(new Map<string,NativeField>());
 const [availability,setAvailability]=useState({forecast:false,observed:false});
 const onTimeChange=useCallback((value:number)=>setTarget(value),[]);
 const [observationLayers,setObservationLayers]=useState(true);
 const onObservationLayersChange=useCallback((active:boolean)=>setObservationLayers(active),[]);
 const presentation=unifiedMapPresentation(settings,observationLayers),showFill=presentation==='fill';
 useEffect(()=>{const c=new AbortController();setCatalogErrors([]);setCatalog(null);setTotals(null);setObserved(null);fieldCache.current.clear();
  const failure=(label:string,e:unknown)=>{if(!c.signal.aborted)setCatalogErrors(current=>[...current,`${label}: ${e instanceof Error?e.message:String(e)}`])};
  void loadNativeIndex(c.signal).then(d=>{if(!c.signal.aborted)setCatalog(d)}).catch(e=>failure('Modellfelder',e));
  void loadTotalsAvailability(c.signal).then(d=>{if(!c.signal.aborted)setAvailability(d)}).catch(e=>failure('Summenkatalog',e));
  return()=>c.abort();
 },[revision]);
 useEffect(()=>{if(props.requestedProductId?.startsWith('icon-d2-precipitation-totals'))update({enabled:true,parameter:'totals',modelId:'icon-d2'})},[props.requestedProductId]);
 const available=useMemo(()=>availableUnifiedParameters(catalog?.index??null,availability.forecast,availability.observed),[catalog,availability]);
 const parameter=settings.parameter,isTotals=parameter==='totals'||parameter==='observed',kind=parameter as NativeFieldKind,product=UNIFIED_MAP_PARAMETERS.find(p=>p.id===parameter)!,modelId=settings.modelId,modelLabel=modelId==='radolan'?'DWD RADOLAN · Messanalyse':modelId==='icon-d2'?'DWD ICON-D2':unifiedWmsChoices().find(c=>c.model.id===modelId)?.model.label||'DWD',frames=(!isTotals?catalog?.index.products[kind]?.frames:undefined)??[],ref=modelId==='icon-d2'?nearestUnifiedFrame(frames,target):undefined,data=parameter==='observed'?observed:totals,frame=data?.frames.find(f=>f.hours===settings.hours),fieldKey=ref&&catalog?`${catalog.index.run}:${kind}:${ref.sha256}`:'',unit=props.unit??'kn';
 useEffect(()=>{if(!settings.enabled||!isTotals||data)return;const c=new AbortController();setLoading(true);setError('');void loadTotals(c.signal,parameter==='observed'?'observed':'forecast').then(d=>{if(!c.signal.aborted){if(parameter==='observed')setObserved(d);else setTotals(d)}}).catch(e=>{if(!c.signal.aborted)setError(String(e.message||e))}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[settings.enabled,parameter,isTotals,data,revision]);
 useEffect(()=>{const c=new AbortController();setField(null);if(isTotals)return()=>c.abort();setError('');setLoading(false);if(!settings.enabled||!catalog||!ref)return()=>c.abort();
  const cached=fieldCache.current.get(fieldKey);if(cached){setField(cached);return()=>c.abort()}
  setLoading(true);void loadNativeField(catalog.index,catalog.base,ref,kind,c.signal).then(d=>{if(c.signal.aborted)return;fieldCache.current.set(fieldKey,d);while(fieldCache.current.size>8)fieldCache.current.delete(fieldCache.current.keys().next().value!);setField(d)}).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:String(e))}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort();
 },[settings.enabled,isTotals,catalog,fieldKey,kind]);
 // One adjacent immutable frame is prefetched, with the same integrity validation.
 useEffect(()=>{if(!field||!catalog||!ref)return;const next=frames[frames.indexOf(ref)+1];if(!next)return;const key=`${catalog.index.run}:${kind}:${next.sha256}`;if(fieldCache.current.has(key))return;const c=new AbortController();void loadNativeField(catalog.index,catalog.base,next,kind,c.signal).then(d=>{if(!c.signal.aborted){fieldCache.current.set(key,d);while(fieldCache.current.size>8)fieldCache.current.delete(fieldCache.current.keys().next().value!)}}).catch(()=>{});return()=>c.abort()},[field,catalog,fieldKey]);
 const range=useMemo(()=>isTotals?data&&frame?totalsMapScale(data,frame,'field'):null:field?nativeMapScale(field,'field',unit):null,[isTotals,data,frame,field,unit]),fixed=useMemo(()=>isTotals?data&&frame?totalsMapScale(data,frame,'absolute'):null:field?nativeMapScale(field,'absolute',unit):null,[isTotals,data,frame,field,unit]),scale=colorMode==='field'?range:fixed;
 const raster=useMemo(()=>showFill&&scale?(isTotals?data&&frame?totalsRaster(data,frame,scale):'':field?nativeRaster(field,scale):''):'',[showFill,scale,isTotals,data,frame,field]),displayUnit=isTotals?'mm':modelMapUnit(kind,field?.unit||catalog?.index.products[kind]?.unit||'',unit),format=(value:number|null)=>isTotals?value===null?'–':compactPrecipitationAmount(value):modelMapValue(kind,value,field?.unit||catalog?.index.products[kind]?.unit||'',unit);
 const wmsProduct=unifiedWmsProduct(parameter,modelId as WeatherMapModelId),wmsTimes=wmsProduct?weatherMapAvailableTimes(wmsProduct,metadata):[],wmsTime=nearestUnifiedTime(wmsTimes,target),wmsRun=metadata?.referenceTimes?.at(-1),levels=metadata?.elevations?.length?metadata.elevations:wmsProduct?.levels??[],level=levels.includes(settings.level)?settings.level:levels.includes(wmsProduct?.defaultLevel??NaN)?wmsProduct?.defaultLevel:levels[0],wmsUrl=weatherMapWmsProxy();
 useEffect(()=>{const c=new AbortController();setMetadata(null);setWmsError('');if(!settings.enabled||!wmsProduct)return()=>c.abort();void loadWeatherMapMetadata(wmsProduct.layer,c.signal).then(d=>{if(!c.signal.aborted)setMetadata(d)}).catch(e=>{if(!c.signal.aborted)setWmsError(String(e.message||e))});return()=>c.abort()},[settings.enabled,wmsProduct?.id,revision]);
 const active=settings.enabled&&(isTotals?Boolean(frame):Boolean(field?.kind===kind&&field.time===ref?.time&&field.run===catalog?.index.run))&&modelId===unifiedModelForParameter(parameter),wmsActive=settings.enabled&&Boolean(wmsProduct&&metadata?.layer===wmsProduct.layer&&wmsTime&&wmsRun&&wmsUrl),sample=(lat:number,lon:number)=>isTotals?data&&frame?totalsAt(data,frame,lat,lon):null:field?nativeAt(field,lat,lon):null;
 const places=props.favorites.filter(p=>p.name&&Number.isFinite(p.latitude)&&Number.isFinite(p.longitude)),place=places.find(p=>p.id===selected),bounds=isTotals&&data?[[data.lats[0],data.lons[0]],[data.lats.at(-1)!,data.lons.at(-1)!]]:field?[[field.lats[0],field.lons[0]],[field.lats.at(-1)!,field.lons.at(-1)!]]:null;
 const wmsLineStyle=unifiedWmsLineStyle(metadata?.layer===wmsProduct?.layer?metadata:null,level),wmsFillStyle=unifiedWmsFillStyle(metadata?.layer===wmsProduct?.layer?metadata:null),wmsStyle=showFill?wmsFillStyle:wmsLineStyle,wmsRenderable=wmsActive&&Boolean(wmsStyle);
 useEffect(()=>setWmsError(''),[wmsProduct?.id,wmsStyle,wmsTime,wmsRun,level]);
 const pressureContours=field?.kind===kind&&field.time===ref?.time&&field.run===catalog?.index.run&&field.isobars.length?field:pressureField?.time===ref?.time&&pressureField?.run===catalog?.index.run?pressureField:null;
 const showIsobars=settings.isobars||(presentation==='lines'&&parameter==='pressure');
 useEffect(()=>{setPressureField(null);setPressureError('');if(kind==='pressure'||!settings.enabled||!showIsobars||!catalog||!ref||field?.isobars.length)return;const pressureRef=catalog.index.products.pressure?.frames.find(f=>f.time===ref.time);if(!pressureRef)return;const c=new AbortController();void loadNativeField(catalog.index,catalog.base,pressureRef,'pressure',c.signal).then(d=>{if(!c.signal.aborted)setPressureField(d)}).catch(e=>{if(!c.signal.aborted)setPressureError('Zusätzliche Isobaren nicht verfügbar: '+String(e.message||e))});return()=>c.abort()},[settings.enabled,showIsobars,catalog,fieldKey,field,kind]);
 const contours=useMemo(()=>nativeIsobarFeatures(pressureContours?.isobars??[]),[pressureContours]);
 const linesActive=active&&showIsobars&&Boolean(contours.features.length);
 const noLines=settings.enabled&&presentation==='lines'&&!wmsRenderable&&!linesActive;
 const noFill=settings.enabled&&showFill&&Boolean(wmsProduct)&&!wmsFillStyle;
 const times=useMemo(()=>!settings.enabled||isTotals?[]:wmsProduct?wmsTimes:frames.map(f=>f.time),[settings.enabled,isTotals,wmsProduct,wmsTimes.join('|'),frames]);
 const download=async(type:'png'|'svg')=>{if(!active||!scale)return;setExporting(true);try{if(isTotals&&data&&frame)await exportTotals(data,frame,raster,places,type,scale);else if(field)await exportNativeField(field,product.label,raster,places,type,ref?.intervalHours??0,unit,scale)}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setError(String(e))}finally{setExporting(false)}};
 const sourcesFor=(p:string)=>unifiedSources(p,catalog?.index??null,availability.forecast,availability.observed);
 const shownParameters=settings.selectionMode==='model'?available.filter(p=>sourcesFor(p.id).some(c=>c.id===modelId)):available;
 const shownSources=settings.selectionMode==='model'?[...new Map(available.flatMap(p=>sourcesFor(p.id)).map(c=>[c.id,c])).values()]:sourcesFor(parameter);
 const controls=<section className="unified-model-controls" aria-label="Modell-Layer">
  <button type="button" className={`unified-model-toggle${settings.enabled?' active':''}`} aria-pressed={settings.enabled} onClick={()=>update({enabled:!settings.enabled})}><Layers3 size={18}/><span><b>Modell / Messraster</b><small>{settings.enabled?`${product.label} · ${modelLabel}`:'Isobaren, Höhenlinien und optionale Flächen'}</small></span></button>
  {settings.enabled&&<><div className="unified-presentation" role="group" aria-label="Darstellung des Modell-Layers">{([['auto','Auto'],['lines','Linien'],['fill','Flächen']] as const).map(([mode,label])=><button key={mode} type="button" aria-label={mode==='auto'?'Automatisch':label} aria-pressed={settings.presentation===mode} onClick={()=>update({presentation:mode})}>{label}</button>)}</div><p className="unified-presentation-hint">{settings.presentation==='auto'?(observationLayers?'Radar / Satellit aktiv · Linien empfohlen und ausgewählt.':'Ohne Radar / Satellit · Modellfläche ausgewählt.'):showFill?'Optionale Modellfläche · Radar und Satellit behalten ihre eigene Deckkraft.':'Linien über der Kartenbasis und den Beobachtungen.'}</p><div className="unified-selection-mode" role="group" aria-label="Auswahlrichtung"><button type="button" aria-pressed={settings.selectionMode==='parameter'} onClick={()=>update({selectionMode:'parameter'})}>Parameter zuerst</button><button type="button" aria-pressed={settings.selectionMode==='model'} onClick={()=>update({selectionMode:'model'})}>Modell zuerst</button></div><div className="unified-model-fields"><label>Parameter<select aria-label="Parameter-Layer" value={parameter} onChange={e=>{const next=e.target.value,choices=sourcesFor(next);update({parameter:next,modelId:choices.some(c=>c.id===modelId)?modelId:choices[0]?.id??modelId})}}>{!shownParameters.some(p=>p.id===parameter)&&<option value={parameter}>{product.label} · nicht verfügbar</option>}{shownParameters.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label>Modell / Quelle<select aria-label="Modell für Parameter" value={modelId} onChange={e=>{const next=e.target.value,compatible=available.filter(p=>sourcesFor(p.id).some(c=>c.id===next));update({modelId:next,parameter:compatible.some(p=>p.id===parameter)?parameter:compatible[0]?.id??parameter})}}>{!shownSources.some(c=>c.id===modelId)&&<option value={modelId} disabled>{modelLabel} · Katalog wird geprüft / nicht verfügbar</option>}{shownSources.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select><small>{settings.selectionMode==='parameter'?'Nur passende Quellen für diesen Parameter.':'Nur Parameter dieses Modells werden angeboten.'}</small></label></div>
  {wmsProduct&&levels.length>0&&<label>{wmsProduct.levelKind==='height'?'Höhe über Grund':'Druckfläche'}<select aria-label="Modell-Druckfläche oder Höhe" value={level} onChange={e=>update({level:Number(e.target.value)})}>{levels.map(l=><option key={l} value={l}>{l} {wmsProduct.levelKind==='height'?'m':'hPa'}</option>)}</select></label>}
  {isTotals&&<label>Summenfenster<select aria-label="Summenfenster" value={settings.hours} onChange={e=>update({hours:Number(e.target.value)})}>{(data?.frames??[]).map(f=><option value={f.hours} key={f.hours}>{f.hours} h</option>)}{!frame&&<option value={settings.hours}>{settings.hours} h · nicht verfügbar</option>}</select></label>}
  <div className="unified-model-fields"><label>{showFill?'Flächen':'Linien'}-Deckkraft · {settings.opacity}%<input aria-label="Modell-Deckkraft" type="range" min="15" max="100" value={settings.opacity} onChange={e=>update({opacity:Number(e.target.value)})}/></label>{!isTotals&&modelId==='icon-d2'&&!(presentation==='lines'&&parameter==='pressure')&&<label className="unified-check"><input type="checkbox" checked={settings.isobars} onChange={e=>update({isobars:e.target.checked})}/>Zusätzliche Isobaren desselben Modelltermins</label>}</div>
  <p className="unified-layer-status" role="status">{noFill?(metadata?'Die Quelle bietet keine verifizierte Fläche. Linien können separat ausgewählt werden.':'DWD-Darstellung wird geprüft …'):noLines?(loading?'Geprüfte Linien laden …':wmsError||error||'Für diesen Parameter / Termin bietet die Quelle keine verifizierten Linien. Flächen bleiben optional.') :wmsActive?wmsError||`${loadedWms.has(`${wmsProduct?.id}-${wmsTime}-${wmsRun}-${level??'surface'}-${wmsStyle}`)?'':'Kacheln laden · '}${modelLabel} · ${timeLabel(wmsTime!,props.timezone)} · INIT ${timeLabel(wmsRun!,props.timezone)} · DWD-Originaleinheit und Darstellung`:active?isTotals&&data&&frame?`${modelLabel} · ${timeLabel(totalsStartAt(data,frame),props.timezone)} – ${timeLabel(frame.validTo,props.timezone)}`:field?`${modelLabel} · Rastertermin ${timeLabel(field.time,props.timezone)} · INIT ${timeLabel(field.run,props.timezone)}`:'':loading?'Geprüftes Modellfeld lädt …':wmsError||error||'Kein verifiziertes Raster für diesen Parameter und Termin verfügbar.'} {product.detail}.{linesActive&&` · Isobaren desselben Modelltermins · ${settings.opacity}%`}{pressureError&&` · ${pressureError}`}</p>{noLines&&parameter!=='pressure'&&<button className="unified-line-suggestion" type="button" onClick={()=>update({parameter:'pressure',modelId:catalog?.index.products.pressure?'icon-d2':'icon',presentation:'lines'})}>Isobaren anzeigen</button>}</>}
 </section>;
 const overlay=<>{wmsRenderable&&wmsProduct?[wmsTime,wmsTimes[wmsTimes.indexOf(wmsTime!)+1]].filter((t):t is string=>Boolean(t)).map(t=>{const key=`${wmsProduct.id}-${t}-${wmsRun}-${level??'surface'}-${wmsStyle}`;return <WmsTileLayer key={key} id={`unified-dwd-${key}`} baseUrl={wmsUrl} zIndex={showFill?(t===wmsTime?300:299):(t===wmsTime?680:679)} opacity={t===wmsTime?settings.opacity/100:.001} params={{layers:wmsProduct.layer,styles:wmsStyle,format:'image/png',transparent:true,version:'1.1.1',width:512,height:512,time:t,dim_reference_time:wmsRun,...(level!==undefined?{elevation:level}:{})}} attribution="Wetterfeld © DWD · CC BY 4.0" onReady={()=>setLoadedWms(current=>{if(current.has(key))return current;const next=new Set(current);next.add(key);while(next.size>16)next.delete(next.values().next().value!);return next})} onError={()=>{if(t===wmsTime)setWmsError('DWD-Modellkacheln sind derzeit nicht erreichbar.')}}/>}):null}{wmsRenderable&&wmsProduct&&metadata?.pointUnit?<ModelMapProbe label={product.label} unit={metadata.pointUnit} source={`${modelLabel} · DWD-Rasterwert`} enabled contextKey={`${wmsProduct.id}-${wmsTime}-${wmsRun}-${level}`} sample={(lat,lon,signal)=>loadWeatherMapPoint(wmsProduct.layer,lat,lon,wmsTime!,wmsRun!,level,metadata.pointUnit!,signal)} format={value=>value===null?'–':String(Math.round(value*10)/10)}/>:null}{active&&showFill&&bounds&&raster?<ImageQuadLayer id="unified-model-field" onError={message=>setError(message)} url={raster} bounds={bounds as [[number,number],[number,number]]} opacity={settings.opacity/100} zIndex={300}/>:null}{linesActive?<GeoJsonLayers id="unified-model-isobars" data={contours} hoverProperty="label" zIndex={680} layers={[{id:'casing',type:'line',paint:{'line-color':'#fff','line-width':3,'line-opacity':settings.opacity/100}},{id:'line',type:'line',paint:{'line-color':'#20384d','line-width':1.3,'line-opacity':settings.opacity/100}}]}/>:null}<ModelMapContextOverlay labels={false}/>{active?<ModelMapProbe label={product.label} unit={displayUnit} source={`${modelLabel} · gleicher Rasterpunkt wie Karte`} enabled={!loading} contextKey={`${fieldKey}-${frame?.validTo}-${parameter}-${unit}`} sample={sample} format={format}/>:null}{place?<MapCenter latitude={place.latitude} longitude={place.longitude} fly/>:null}{places.map(p=><HtmlMarker key={p.id} latitude={p.latitude} longitude={p.longitude} html={'<span></span>'} className="precipitation-favorite-marker" zIndex={920} popupHtml={`<strong>${htmlEscape(p.name)}</strong>${active?`<br/>${htmlEscape(format(sample(p.latitude,p.longitude)))} ${htmlEscape(displayUnit)}`:''}`} onClick={()=>setSelected(p.id)}/>)}</>;
 return <section className="unified-weather-map" aria-label="Gemeinsame Wetterkarte"><RadarPanel {...props} focusMode={false} unified={{controls,overlay,times,enabled:settings.enabled,sourceLabel:modelLabel,run:wmsRun||catalog?.index.run,ready:!settings.enabled||(wmsProduct?Boolean(!wmsRenderable||(wmsRenderable&&loadedWms.has(`${wmsProduct.id}-${wmsTime}-${wmsRun}-${level??'surface'}-${wmsStyle}`))||wmsError):Boolean(active)||Boolean(error)||!ref),onTimeChange,onObservationLayersChange}}/>
  {active&&showFill&&scale&&range&&fixed?<>{scale.categorical?<div className="unified-categorical-legend">WMO-Wettercode {mapScaleTicks(scale).map(([v,c])=><span key={v}><i style={{background:c}}/>{v}</span>)}</div>:<ModelMapScaleLegend label={product.label} unit={displayUnit} scale={scale} range={range} format={format} onModeChange={setColorMode}/>}<div className="unified-export-controls" aria-busy={exporting}><button type="button" disabled={exporting} onClick={()=>void download('png')}>Raster + Ortswerte · PNG</button><button type="button" disabled={exporting} onClick={()=>void download('svg')}>Raster + Ortswerte · SVG</button><small>Export des ausgewählten Modell-/Messfeldes; keine Radar-/Satellitenmontage.</small></div></>:null}
  <details className="unified-favorites"><summary>Ortsdaten · {places.length} Favoriten</summary><div className="weather-precipitation-table-wrap">{!active?<><div className="unified-place-buttons">{places.map(p=><button type="button" key={p.id} onClick={()=>setSelected(p.id)}>{p.name}</button>)}</div><p className="unified-presentation-hint">{!settings.enabled?'Ort antippen, um die Karte dorthin zu verschieben.':wmsRenderable?'Ort antippen zum Zentrieren; verfügbare Punktwerte direkt auf der Karte abrufen.':'Ort antippen zum Zentrieren. Ein bestätigtes Ortsraster ist für diesen Layer / Termin noch nicht verfügbar.'}</p></>:<table><thead><tr><th>Ort</th><th>{settings.enabled?product.label:'Ortsauswahl'}</th><th>Quelle</th></tr></thead><tbody>{places.map(p=>{const value=active?sample(p.latitude,p.longitude):null;return <tr key={p.id}><th><button type="button" onClick={()=>setSelected(p.id)}>{p.name}</button></th><td>{format(value)} {value!==null?displayUnit:''}</td><td>{value!==null?modelLabel:'außerhalb des Rasters'}</td></tr>})}</tbody></table>}</div></details>
  <details className="unified-source-info"><summary>Quellen und Datenstatus</summary><p>Linien: native Isobaren aus demselben DWD-Modelltermin oder ausdrücklich im DWD-WMS-Katalog angebotene Isolinien / Windfiedern. Keine Umdeutung von Flächenbildern in Konturen. Modellfelder und Summen: direkte DWD-GRIB2-/RADOLAN-Raster, dieselbe geprüfte Publikationsstrecke wie die Summenkarten. Grenzen und Ortsnamen bleiben oberhalb aller Wetterflächen. Weitere Modelle: zeit- und laufgebundene DWD-Feldkacheln mit Originalfarbskala, keine statischen Übersichtsbilder. Radar/Satellit sind Beobachtungen, keine Modellprognosen; Layer zeigen jeweils ihren echten Termin. DWD CC BY 4.0 · OpenStreetMap ODbL · Natural Earth Public Domain.</p>{catalogErrors.map(e=><p key={e}>{e}</p>)}<button type="button" onClick={()=>setRevision(v=>v+1)}>Rasterkatalog aktualisieren</button></details>
 </section>;
}
