import {useCallback,useEffect,useState} from 'react';
import {Clock3,RefreshCw,Wind} from 'lucide-react';
import {fetchVentilationAdvice,readVentilationAssistantSettings,type VentilationAdvice,type VentilationAssistantSettings} from './ventilationAssistant';

function tone(status:string){return status==='open'?'good':status==='later'?'watch':status==='not-needed'?'neutral':'muted'}
function statusLabel(status:string){return status==='open'?'Jetzt lüften':status==='later'?'Später lüften':status==='not-needed'?'Derzeit nicht nötig':'Kein gutes Fenster'}
export function VentilationAssistantPanel(){
 const[settings,setSettings]=useState<VentilationAssistantSettings>(()=>readVentilationAssistantSettings()),[advice,setAdvice]=useState<VentilationAdvice|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const update=(event:Event)=>setSettings((event as CustomEvent<VentilationAssistantSettings>).detail||readVentilationAssistantSettings());window.addEventListener('mid:ventilation-settings',update);return()=>window.removeEventListener('mid:ventilation-settings',update)},[]);
 const refresh=useCallback(async()=>{if(!settings.enabled){setAdvice(null);setError('');return}setLoading(true);setError('');try{setAdvice(await fetchVentilationAdvice(settings))}catch(reason){setAdvice(null);setError(reason instanceof Error?reason.message:String(reason))}finally{setLoading(false)}},[settings]);
 useEffect(()=>{void refresh();if(!settings.enabled)return;const timer=window.setInterval(()=>void refresh(),10*60*1000),visible=()=>{if(document.visibilityState==='visible')void refresh()};document.addEventListener('visibilitychange',visible);return()=>{window.clearInterval(timer);document.removeEventListener('visibilitychange',visible)}},[refresh,settings.enabled]);
 return <section className="ventilation-assistant-panel"><header className="ventilation-assistant-header"><span><Wind size={20}/><strong>Lüftungsassistent</strong></span><button type="button" onClick={()=>void refresh()} disabled={loading||!settings.enabled} title="Lüftungsfenster neu berechnen" aria-label="Lüftungsfenster neu berechnen"><RefreshCw size={16} className={loading?'spin':undefined}/></button></header>{!settings.enabled?<div className="ventilation-empty"><strong>Noch nicht aktiviert</strong><span>Unter Einstellungen → Lokaler Wetterzwilling kannst du Netatmo verbinden und Räume für den Lüftungsassistenten freigeben.</span></div>:error?<div className="ventilation-empty error"><strong>Lüftungsanalyse nicht verfügbar</strong><span>{error}</span></div>:loading&&!advice?<div className="ventilation-empty"><RefreshCw size={18} className="spin"/><span>Innenraumsensoren und Wetterfenster werden geprüft …</span></div>:advice?.rooms?.length?<div className="ventilation-room-list">{advice.rooms.map(room=><article key={room.roomId} className={`ventilation-room-card ${tone(room.status)}`}><header><span><strong>{room.name}</strong><small>{statusLabel(room.status)}</small></span>{room.startLabel&&room.durationMinutes?<b><Clock3 size={14}/>{room.startLabel} · {room.durationMinutes} min</b>:null}</header><p>{room.summary}</p><div className="ventilation-room-metrics">{Number.isFinite(room.temperature)&&<span>Innen {Math.round(Number(room.temperature)*10)/10} °C</span>}{Number.isFinite(room.humidity)&&<span>{Math.round(Number(room.humidity))} % rF</span>}{Number.isFinite(room.co2)&&<span>CO₂ {Math.round(Number(room.co2))} ppm</span>}{Number.isFinite(room.outdoorTemperature)&&<span>Außen {Math.round(Number(room.outdoorTemperature)*10)/10} °C</span>}</div>{room.reasons?.length?<small className="ventilation-reasons">{room.reasons.slice(0,3).join(' · ')}</small>:null}</article>)}</div>:<div className="ventilation-empty"><strong>Keine Räume aktiv</strong><span>Aktiviere mindestens einen erkannten Innenraumsensor in den Einstellungen.</span></div>}{advice?.generatedAt?<footer>Berechnet {new Date(advice.generatedAt).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})} · Empfehlung, keine automatische Fenstersteuerung</footer>:null}</section>
}
