import {buildWorkerUrl,workerBaseCandidates} from './workerClient';
import {readConnectedStationConfig} from './connectedStation';

export const VENTILATION_SETTINGS_KEY='mid:ventilation-assistant:v1';
export type VentilationRoomRule={roomId:string;enabled:boolean;earliest:string;latest:string;minMinutes:number;maxMinutes:number};
export type VentilationAssistantSettings={enabled:boolean;notifications:boolean;roomRules:Record<string,VentilationRoomRule>};
export type VentilationAdviceRoom={roomId:string;name:string;status:'open'|'later'|'not-needed'|'wait';start?:string;end?:string;startLabel?:string;durationMinutes?:number;summary:string;reasons:string[];temperature?:number;humidity?:number;co2?:number;indoorAbsoluteHumidity?:number;outdoorTemperature?:number;outdoorHumidity?:number;outdoorAbsoluteHumidity?:number;precipitationProbability?:number;gustKmh?:number;leadHours?:number;windowKey?:string};
export type VentilationAdvice={ok?:boolean;error?:string;generatedAt:string;provider:string;stationName:string;timezone?:string;rooms:VentilationAdviceRoom[];outdoor?:{temperature?:number;humidity?:number;timestamp?:string};message?:string};
export type VentilationPushConfig={enabled:boolean;connectionId:string;deviceId?:string;roomRules:VentilationRoomRule[]};

const DEFAULT_SETTINGS:VentilationAssistantSettings={enabled:false,notifications:false,roomRules:{}};
function validTime(value:unknown,fallback:string){const raw=String(value||'');return /^([01]\d|2[0-3]):[0-5]\d$/.test(raw)?raw:fallback}
function normalizeRule(roomId:string,value:any):VentilationRoomRule{return{roomId,enabled:value?.enabled!==false,earliest:validTime(value?.earliest,'00:00'),latest:validTime(value?.latest,'23:59'),minMinutes:Math.max(10,Math.min(45,Math.round(Number(value?.minMinutes)||15))),maxMinutes:Math.max(15,Math.min(60,Math.round(Number(value?.maxMinutes)||30)))}}
export function readVentilationAssistantSettings():VentilationAssistantSettings{try{const raw=JSON.parse(localStorage.getItem(VENTILATION_SETTINGS_KEY)||'{}') as Partial<VentilationAssistantSettings>,rules:Record<string,VentilationRoomRule>={};if(raw.roomRules&&typeof raw.roomRules==='object')for(const [roomId,value] of Object.entries(raw.roomRules))if(roomId)rules[roomId]=normalizeRule(roomId,value);return{enabled:Boolean(raw.enabled),notifications:Boolean(raw.notifications),roomRules:rules}}catch{return{...DEFAULT_SETTINGS,roomRules:{}}}}
export function writeVentilationAssistantSettings(change:Partial<VentilationAssistantSettings>){const current=readVentilationAssistantSettings(),next={...current,...change,roomRules:change.roomRules??current.roomRules};try{localStorage.setItem(VENTILATION_SETTINGS_KEY,JSON.stringify(next))}catch{};window.dispatchEvent(new CustomEvent('mid:ventilation-settings',{detail:next}));return next}
export function updateVentilationRoomRule(roomId:string,change:Partial<VentilationRoomRule>){const settings=readVentilationAssistantSettings(),current=settings.roomRules[roomId]??normalizeRule(roomId,{}),roomRules={...settings.roomRules,[roomId]:normalizeRule(roomId,{...current,...change})};return writeVentilationAssistantSettings({roomRules})}
export function ensureVentilationRoomRules(roomIds:string[]){const settings=readVentilationAssistantSettings(),roomRules={...settings.roomRules};let changed=false;for(const roomId of roomIds)if(roomId&&!roomRules[roomId]){roomRules[roomId]=normalizeRule(roomId,{});changed=true}return changed?writeVentilationAssistantSettings({roomRules}):settings}

async function workerPost<T extends{error?:string}>(mode:string,body:unknown):Promise<T>{const candidates=workerBaseCandidates('general');if(!candidates.length)throw new Error('Cloudflare Worker ist nicht konfiguriert.');const errors:string[]=[];for(const base of candidates){try{const response=await fetch(buildWorkerUrl(base,mode),{method:'POST',cache:'no-store',headers:{Accept:'application/json','Content-Type':'application/json','Cache-Control':'no-cache'},body:JSON.stringify(body)}),text=await response.text();let data:T;try{data=JSON.parse(text) as T}catch{throw new Error(`Ungültige Worker-Antwort (HTTP ${response.status}).`)}if(!response.ok||data.error)throw new Error(data.error||`HTTP ${response.status}`);return data}catch(error){errors.push(error instanceof Error?error.message:String(error))}}throw new Error(errors.at(-1)||'Lüftungsdienst nicht erreichbar.')}
export function ventilationPushConfig(settings=readVentilationAssistantSettings()):VentilationPushConfig|null{const station=readConnectedStationConfig();if(!settings.enabled||!settings.notifications||!station.enabled||station.provider!=='netatmo'||!station.connectionId)return null;const roomRules=Object.values(settings.roomRules).filter(rule=>rule.enabled).map(rule=>normalizeRule(rule.roomId,rule));return roomRules.length?{enabled:true,connectionId:station.connectionId,deviceId:station.selectedDeviceId||undefined,roomRules}:null}
export async function fetchVentilationAdvice(settings=readVentilationAssistantSettings(),signal?:AbortSignal):Promise<VentilationAdvice>{const station=readConnectedStationConfig();if(!settings.enabled)throw new Error('Lüftungsassistent ist deaktiviert.');if(!station.enabled||station.provider!=='netatmo')throw new Error('Für den Lüftungsassistenten zuerst Netatmo verbinden und die Wetterstation aktivieren.');if(signal?.aborted)throw signal.reason;const result=await workerPost<VentilationAdvice>('ventilation-advice',{connectionId:station.connectionId,deviceId:station.selectedDeviceId||undefined,roomRules:Object.values(settings.roomRules)});if(signal?.aborted)throw signal.reason;return result}
