import {useEffect,useMemo,useState} from 'react';
import {Bell,Clock3,RefreshCw,Wind} from 'lucide-react';
import {connectedStationStatus,readConnectedStationConfig,type ConnectedEnvironmentSensor,type ConnectedStationStatus} from './connectedStation';
import {ensureVentilationRoomRules,readVentilationAssistantSettings,updateVentilationRoomRule,writeVentilationAssistantSettings,type VentilationAssistantSettings} from './ventilationAssistant';
import {preparePushNotifications} from './pushNotifications';

export function VentilationAssistantSettings(){
 const[settings,setSettings]=useState<VentilationAssistantSettings>(()=>readVentilationAssistantSettings()),[status,setStatus]=useState<ConnectedStationStatus|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const update=(event:Event)=>setSettings((event as CustomEvent<VentilationAssistantSettings>).detail||readVentilationAssistantSettings());window.addEventListener('mid:ventilation-settings',update);return()=>window.removeEventListener('mid:ventilation-settings',update)},[]);
 const refresh=async()=>{const station=readConnectedStationConfig();if(station.provider!=='netatmo'){setStatus(null);return}setLoading(true);setMessage('');try{const next=await connectedStationStatus(station);setStatus(next);const ids=(next.environment?.rooms||[]).map(room=>room.id);if(ids.length)setSettings(ensureVentilationRoomRules(ids))}catch(error){setMessage(error instanceof Error?error.message:String(error))}finally{setLoading(false)}};
 useEffect(()=>{void refresh();const update=()=>void refresh();window.addEventListener('mid:connected-station-settings',update);return()=>window.removeEventListener('mid:connected-station-settings',update)},[]);
 const rooms=useMemo<ConnectedEnvironmentSensor[]>(()=>status?.environment?.rooms||[],[status]),patch=(change:Partial<VentilationAssistantSettings>)=>setSettings(writeVentilationAssistantSettings(change)),patchRoom=(roomId:string,change:any)=>setSettings(updateVentilationRoomRule(roomId,change)),ready=Boolean(status?.connected&&rooms.length),toggleNotifications=async(enabled:boolean)=>{if(!enabled){patch({notifications:false});return}setLoading(true);setMessage('');try{await preparePushNotifications();patch({notifications:true});setMessage('Benachrichtigungen sind für den Lüftungsassistenten vorbereitet.')}catch(error){patch({notifications:false});setMessage(error instanceof Error?error.message:String(error))}finally{setLoading(false)}};
 return <section className="ventilation-settings"><header><Wind size={21}/><span><strong>Lüftungsassistent · Stufe 1</strong><small>Empfehlungen und Benachrichtigungen auf Basis von Innenraumsensoren und prognostiziertem Außenwetter. Keine automatische Fenster-, Lüfter- oder Anlagensteuerung.</small></span><button type="button" className="icon-button" onClick={()=>void refresh()} disabled={loading} title="Sensoren aktualisieren"><RefreshCw size={16} className={loading?'spin':undefined}/></button></header><label className={`settings-toggle-card${!ready?' disabled':''}`}><input type="checkbox" disabled={!ready} checked={settings.enabled} onChange={event=>patch({enabled:event.target.checked})}/><Wind size={21}/><span><strong>Lüftungsassistent aktivieren</strong><small>{ready?'MID sucht je Raum das nächste sinnvolle Lüftungsfenster und berücksichtigt Temperatur, absolute Feuchte, CO₂, Niederschlag, Gewitter und Wind.':'Zuerst Netatmo verbinden; mindestens ein Innenraumsensor muss verfügbar sein.'}</small></span></label><label className={`settings-toggle-card${!settings.enabled||!ready?' disabled':''}`}><input type="checkbox" disabled={!settings.enabled||!ready} checked={settings.notifications} onChange={event=>void toggleNotifications(event.target.checked)}/><Bell size={21}/><span><strong>Bei gutem Lüftungsfenster benachrichtigen</strong><small>Verwendet den bestehenden MID-Pushdienst. Die Mitteilung wird nur gesendet, wenn ein freigegebener Raum ein neues sinnvolles Zeitfenster erreicht.</small></span></label>{rooms.length?<div className="ventilation-room-settings"><header><strong>Räume & erlaubte Zeiten</strong><small>Beispiel: „erst ab 22:00 Uhr“ → früheste Zeit auf 22:00 setzen.</small></header>{rooms.map(room=>{const rule=settings.roomRules[room.id]??{roomId:room.id,enabled:true,earliest:'00:00',latest:'23:59',minMinutes:15,maxMinutes:30};return <article key={room.id}><label className="ventilation-room-enable"><input type="checkbox" checked={rule.enabled} onChange={event=>patchRoom(room.id,{enabled:event.target.checked})}/><span><strong>{room.name}</strong><small>{[Number.isFinite(room.temperature)?`${Number(room.temperature).toFixed(1)} °C`:'',Number.isFinite(room.humidity)?`${Math.round(Number(room.humidity))} % rF`:'',Number.isFinite(room.co2)?`CO₂ ${Math.round(Number(room.co2))} ppm`:''].filter(Boolean).join(' · ')||'Innenraumsensor'}</small></span></label><div className="ventilation-time-grid"><label><Clock3 size={14}/><span>frühestens</span><input type="time" value={rule.earliest} onChange={event=>patchRoom(room.id,{earliest:event.target.value})}/></label><label><Clock3 size={14}/><span>spätestens</span><input type="time" value={rule.latest} onChange={event=>patchRoom(room.id,{latest:event.target.value})}/></label></div></article>})}</div>:null}{message&&<div className="connected-station-message" role="status">{message}</div>}</section>
}
