import {useEffect,useMemo,useState} from 'react';
import {Activity,AlertTriangle,Anchor,CloudLightning,Compass,Droplets,Eye,Gauge,Navigation,RefreshCw,Sun,Thermometer,Timer,Waves,Wind} from 'lucide-react';
import {currentIndex,marineForecast,wind,type Hour,type Location,type MarineForecast,type Weather,type WindUnit} from './weather';

type WaterType='auto'|'sea'|'lake'|'river';
type WaterActivity='general'|'sailing'|'surfing'|'paddling'|'swimming';
type WaterConfig={enabled:boolean;waterType:WaterType;activity:WaterActivity;maxWaveHeight:number;maxGustKt:number;minWaterTemperature:number};
type Props={loc:Location;weather:Weather;hours:Hour[];unit:WindUnit;config:WaterConfig};

type TideEvent={kind:'high'|'low';time:string;level:number};

const activityLabels:Record<WaterActivity,string>={general:'Allgemein',sailing:'Segeln & Windsport',surfing:'Surfen',paddling:'Paddeln',swimming:'Schwimmen'};
const waterTypeLabels:Record<WaterType,string>={auto:'automatisch',sea:'Küste / Meer',lake:'See',river:'Fluss'};
function num(value:unknown){const number=Number(value);return value===null||value===undefined||value===''||!Number.isFinite(number)?Number.NaN:number}
function formatNumber(value:number,digits=1){return Number.isFinite(value)?value.toFixed(digits).replace('.',','):'–'}
function localNowKey(timeZone?:string){try{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timeZone||undefined,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()),get=(type:string)=>parts.find(x=>x.type===type)?.value;return`${get('year')}-${get('month')}-${get('day')}T${get('hour')}:${get('minute')}`}catch{return new Date().toISOString().slice(0,16)}}
function timeLabel(value?:string){const match=String(value||'').match(/T(\d{2}):(\d{2})/);return match?`${match[1]}:${match[2]}`:'–:–'}
function dateTimeLabel(value:string,timezone?:string){const today=localNowKey(timezone).slice(0,10),date=value.slice(0,10),time=timeLabel(value);if(date===today)return`${time} Uhr`;const d=new Date(`${date}T12:00:00Z`);return`${new Intl.DateTimeFormat('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',timeZone:'UTC'}).format(d)}, ${time} Uhr`}
function cardinal(degrees:number){if(!Number.isFinite(degrees))return'–';const labels=['N','NNO','NO','ONO','O','OSO','SO','SSO','S','SSW','SW','WSW','W','WNW','NW','NNW'];return labels[Math.round(((degrees%360)+360)%360/22.5)%16]}
function haversineKm(lat1:number,lon1:number,lat2:number,lon2:number){const r=6371,toRad=(value:number)=>value*Math.PI/180,dLat=toRad(lat2-lat1),dLon=toRad(lon2-lon1),a=Math.sin(dLat/2)**2+Math.cos(toRad(lat1))*Math.cos(toRad(lat2))*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.sqrt(a))}
function waveClass(height:number){if(!Number.isFinite(height))return'–';if(height<.1)return'glatt';if(height<.5)return'ruhig';if(height<1.25)return'leicht bewegt';if(height<2.5)return'mäßig';if(height<4)return'grob';return'sehr grob'}
function waterTemperatureClass(value:number){if(!Number.isFinite(value))return'';if(value<10)return'sehr kalt';if(value<15)return'kalt';if(value<20)return'frisch';if(value<25)return'mild';return'warm'}
function seaLevelText(value:number){if(!Number.isFinite(value))return'–';return`${value>=0?'+':''}${formatNumber(value,2)} m`}
function metric(data:MarineForecast|undefined,key:string){return num(data?.current?.[key])}
function array(data:MarineForecast|undefined,section:'hourly'|'minutely_15',key:string){const source=data?.[section] as Record<string,(number|string|null)[]>|undefined;return(source?.[key]??[]) as (number|string|null)[]}
function tideSeries(data:MarineForecast|undefined){const minuteTimes=array(data,'minutely_15','time').map(String),minuteLevels=array(data,'minutely_15','sea_level_height_msl').map(num);if(minuteTimes.length&&minuteLevels.some(Number.isFinite))return{times:minuteTimes,levels:minuteLevels,stepMinutes:15};const times=array(data,'hourly','time').map(String),levels=array(data,'hourly','sea_level_height_msl').map(num);return{times,levels,stepMinutes:60}}
function tideAnalysis(data:MarineForecast|undefined,timezone?:string){const{times,levels,stepMinutes}=tideSeries(data),nowKey=localNowKey(timezone);if(!times.length)return{events:[] as TideEvent[],trend:'nicht verfügbar',range:Number.NaN,current:Number.NaN};const start=Math.max(1,times.findIndex(time=>time>=nowKey)),smooth=levels.map((value,index)=>{const values=[levels[index-1],value,levels[index+1]].filter(Number.isFinite);return values.length?values.reduce((sum,item)=>sum+item,0)/values.length:Number.NaN}),events:TideEvent[]=[];let lastIndex=-999;for(let index=Math.max(2,start);index<smooth.length-2&&events.length<6;index++){const prev=smooth[index-1],value=smooth[index],next=smooth[index+1];if(![prev,value,next].every(Number.isFinite))continue;const kind=value>=prev&&value>next?'high':value<=prev&&value<next?'low':null;if(!kind)continue;const prominence=Math.min(Math.abs(value-prev),Math.abs(value-next));if(prominence<.003||index-lastIndex<Math.max(2,Math.round(120/stepMinutes)))continue;events.push({kind,time:times[index],level:levels[index]});lastIndex=index}const currentIndex=Math.max(0,times.findIndex(time=>time>=nowKey)),current=levels[currentIndex],future=levels[Math.min(levels.length-1,currentIndex+Math.max(1,Math.round(60/stepMinutes)))],trend=Number.isFinite(current)&&Number.isFinite(future)?future-current>.015?'steigend':future-current<-.015?'fallend':'nahezu gleichbleibend':'nicht verfügbar',futureLevels=levels.slice(currentIndex,currentIndex+Math.max(2,Math.round(24*60/stepMinutes))).filter(Number.isFinite),range=futureLevels.length?Math.max(...futureLevels)-Math.min(...futureLevels):Number.NaN;return{events,trend,range,current}}
function nextMarineRows(data:MarineForecast|undefined,hours:Hour[],timezone?:string){const times=array(data,'hourly','time').map(String),nowKey=localNowKey(timezone),start=Math.max(0,times.findIndex(time=>time>=nowKey));return times.slice(start,start+18).map((time,offset)=>({time,index:start+offset})).filter((_,index)=>index%3===0).slice(0,6).map(row=>{const atmospheric=hours.find(hour=>hour.time===row.time);return{time:row.time,wave:num(array(data,'hourly','wave_height')[row.index]),period:num(array(data,'hourly','wave_period')[row.index]),waterTemp:num(array(data,'hourly','sea_surface_temperature')[row.index]),current:num(array(data,'hourly','ocean_current_velocity')[row.index]),wind:atmospheric?.wind,gust:atmospheric?.gust,probability:atmospheric?.probability,code:atmospheric?.code}})}

export default function WaterSportsPanel({loc,weather,hours,unit,config}:Props){
 const[data,setData]=useState<MarineForecast|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const marineRequested=config.waterType==='auto'||config.waterType==='sea';
 useEffect(()=>{if(!config.enabled||!marineRequested){setData(null);setLoading(false);setError('');return}const controller=new AbortController();setLoading(true);setError('');marineForecast(loc.latitude,loc.longitude,weather.timezone,controller.signal).then(setData).catch(reason=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:'Meeresdaten konnten nicht geladen werden.')} ).finally(()=>!controller.signal.aborted&&setLoading(false));return()=>controller.abort()},[config.enabled,config.waterType,loc.latitude,loc.longitude,weather.timezone,marineRequested]);
 const gridDistance=data?haversineKm(loc.latitude,loc.longitude,data.latitude,data.longitude):Number.NaN,maxDistance=config.waterType==='sea'?160:80,marineUsable=Boolean(data&&Number.isFinite(gridDistance)&&gridDistance<=maxDistance),marine=marineUsable?data??undefined:undefined;
 const currentHour=hours[currentIndex(hours)]??hours[0],nextSix=hours.slice(Math.max(0,currentIndex(hours)),Math.max(0,currentIndex(hours))+6),thunder=nextSix.some(hour=>[95,96,97,99].includes(Math.round(hour.code))||hour.cape>=800),visibility=currentHour?.visibility??Number.NaN;
 const waterTemp=metric(marine,'sea_surface_temperature'),waveHeight=metric(marine,'wave_height'),waveDirection=metric(marine,'wave_direction'),wavePeriod=metric(marine,'wave_period'),wavePeakPeriod=metric(marine,'wave_peak_period'),windWaveHeight=metric(marine,'wind_wave_height'),windWaveDirection=metric(marine,'wind_wave_direction'),windWavePeriod=metric(marine,'wind_wave_period'),swellHeight=metric(marine,'swell_wave_height'),swellDirection=metric(marine,'swell_wave_direction'),swellPeriod=metric(marine,'swell_wave_period'),currentVelocity=metric(marine,'ocean_current_velocity'),currentDirection=metric(marine,'ocean_current_direction');
 const tides=useMemo(()=>tideAnalysis(marine,weather.timezone),[marine,weather.timezone]),timeline=useMemo(()=>nextMarineRows(marine,hours,weather.timezone),[marine,hours,weather.timezone]);
 const assessment=useMemo(()=>{let score=100;const notes:string[]=[];if(Number.isFinite(currentHour?.gust)&&currentHour.gust>config.maxGustKt){score-=30;notes.push(`Böen über ${formatNumber(config.maxGustKt,0)} kt`)}if(Number.isFinite(waveHeight)&&waveHeight>config.maxWaveHeight){score-=35;notes.push(`Wellen über ${formatNumber(config.maxWaveHeight)} m`)}if(Number.isFinite(waterTemp)&&waterTemp<config.minWaterTemperature){score-=20;notes.push(`Wasser unter ${formatNumber(config.minWaterTemperature,0)} °C`)}if(thunder){score-=45;notes.push('Gewitterrisiko')}if(Number.isFinite(visibility)&&visibility<3000){score-=20;notes.push('eingeschränkte Sicht')}if((currentHour?.probability??0)>=70){score-=15;notes.push('hohes Niederschlagsrisiko')}if(Number.isFinite(currentVelocity)&&currentVelocity>3){score-=15;notes.push('starke Strömung')}const level=score>=80?'günstig':score>=55?'eingeschränkt':'ungünstig';return{score:Math.max(0,score),level,notes}},[currentHour,config,waveHeight,waterTemp,thunder,visibility,currentVelocity]);
 const cards=[
  {icon:<Thermometer/>,label:'Wassertemperatur',value:Number.isFinite(waterTemp)?`${formatNumber(waterTemp)} °C`:'–',detail:Number.isFinite(waterTemp)?waterTemperatureClass(waterTemp):marineRequested?'nicht verfügbar':'für Binnengewässer keine offene Standardquelle'},
  {icon:<Waves/>,label:'Signifikante Wellenhöhe',value:Number.isFinite(waveHeight)?`${formatNumber(waveHeight)} m`:'–',detail:Number.isFinite(waveHeight)?waveClass(waveHeight):'keine belastbaren Wellendaten'},
  {icon:<Compass/>,label:'Wellenrichtung',value:Number.isFinite(waveDirection)?`aus ${cardinal(waveDirection)}`:'–',detail:Number.isFinite(waveDirection)?`${Math.round(waveDirection)}°`:'Richtung, aus der die Wellen kommen'},
  {icon:<Timer/>,label:'Wellenperiode',value:Number.isFinite(wavePeriod)?`${formatNumber(wavePeriod)} s`:'–',detail:Number.isFinite(wavePeakPeriod)?`Peak ${formatNumber(wavePeakPeriod)} s`:'mittlere Periode'},
  {icon:<Activity/>,label:'Dünung',value:Number.isFinite(swellHeight)?`${formatNumber(swellHeight)} m`:'–',detail:Number.isFinite(swellDirection)?`aus ${cardinal(swellDirection)} · ${formatNumber(swellPeriod)} s`:'keine getrennte Dünung'},
  {icon:<Wind/>,label:'Windsee',value:Number.isFinite(windWaveHeight)?`${formatNumber(windWaveHeight)} m`:'–',detail:Number.isFinite(windWaveDirection)?`aus ${cardinal(windWaveDirection)} · ${formatNumber(windWavePeriod)} s`:'keine getrennte Windsee'},
  {icon:<Navigation/>,label:'Strömung',value:Number.isFinite(currentVelocity)?wind(currentVelocity,unit):'–',detail:Number.isFinite(currentDirection)?`nach ${cardinal(currentDirection)} · ${Math.round(currentDirection)}°`:'Modellströmung nicht verfügbar'},
  {icon:<Anchor/>,label:'Wasserstand inkl. Tide',value:seaLevelText(tides.current),detail:Number.isFinite(tides.range)?`${tides.trend} · Spanne 24 h ${formatNumber(tides.range,2)} m`:tides.trend},
  {icon:<Wind/>,label:'Wind / Böen',value:currentHour?`${cardinal(currentHour.direction)} ${wind(currentHour.wind,unit)}`:'–',detail:currentHour?`Böen ${wind(currentHour.gust,unit)}`:'–'},
  {icon:<Thermometer/>,label:'Luft / gefühlt',value:currentHour?`${Math.round(currentHour.temperature)} / ${Math.round(currentHour.apparent)} °C`:'–',detail:Number.isFinite(waterTemp)&&currentHour?`Luft–Wasser ${formatNumber(currentHour.temperature-waterTemp)} K`:'Best Match'},
  {icon:<Sun/>,label:'UVI / Niederschlag',value:currentHour?`${formatNumber(currentHour.uvIndex)} · ${Math.round(currentHour.probability)} %`:'–',detail:'UVI · Niederschlagswahrscheinlichkeit'},
  {icon:thunder?<CloudLightning/>:<Eye/>,label:'Sicht / Gewitter',value:Number.isFinite(visibility)?visibility>=10000?`${Math.round(visibility/1000)} km`:`${formatNumber(visibility/1000)} km`:'–',detail:thunder?'Gewitterrisiko in den nächsten 6 h':'kein markantes Gewittersignal'}
 ];
 return <section className="card water-sports"><header className="title"><div><span>Favoritenprofil · Marine Best Match</span><h2>Wassersportmodus</h2></div><div className="water-profile-badges"><b>{activityLabels[config.activity]}</b><b>{waterTypeLabels[config.waterType]}</b></div></header>
  {loading&&!data?<div className="water-loading"><RefreshCw className="spin" size={18}/>Meeres- und Gezeitendaten werden geladen …</div>:null}
  <div className={`water-assessment ${assessment.level}`}><Gauge/><div><small>Aktuelle Eignung nach deinen Favoritenschwellen</small><strong>{assessment.level}</strong><span>{assessment.notes.length?assessment.notes.join(' · '):'Keine konfigurierten Schwellen überschritten'}</span></div><b>{assessment.score}/100</b></div>
  {!marineRequested&&<div className="water-info"><Droplets/><span><strong>Binnengewässerprofil</strong><small>Wetter, Wind, Sicht, UVI und Gewitter werden angezeigt. Für See- und Fluss-Wassertemperatur, Wellen und Pegel gibt es keine weltweit einheitliche offene Standardquelle; diese Werte werden nicht durch entfernte Meeresgitter ersetzt.</small></span></div>}
  {marineRequested&&!loading&&!marineUsable&&<div className="water-info warning"><AlertTriangle/><span><strong>Kein geeignetes Meeresgitter am Standort</strong><small>{error||`Das nächste Marine-Modellgitter liegt ${Number.isFinite(gridDistance)?`${Math.round(gridDistance)} km`:'zu weit'} entfernt. Meereswerte werden ausgeblendet.`}</small></span></div>}
  <div className="water-indicators">{cards.map(card=><article key={card.label}>{card.icon}<small>{card.label}</small><strong>{card.value}</strong><span>{card.detail}</span></article>)}</div>
  {tides.events.length>0&&<div className="water-tides"><header><div><span>Modellierter Wasserstand</span><h3>Gezeiten- und Wasserstandswendepunkte</h3></div><small>Bezug: globales mittleres Meeresspiegelniveau</small></header><div>{tides.events.slice(0,4).map(event=><article key={`${event.kind}:${event.time}`}><Anchor/><span>{event.kind==='high'?'Hochpunkt':'Tiefpunkt'}</span><strong>{dateTimeLabel(event.time,weather.timezone)}</strong><small>{seaLevelText(event.level)}</small></article>)}</div></div>}
  {timeline.length>0&&<div className="water-timeline">{timeline.map(row=><article key={row.time}><time>{timeLabel(row.time)}</time><Waves/><strong>{Number.isFinite(row.wave)?`${formatNumber(row.wave)} m`:'–'}</strong><span>{Number.isFinite(row.period)?`${formatNumber(row.period)} s`:''}{Number.isFinite(row.waterTemp)?` · Wasser ${formatNumber(row.waterTemp)}°`:''}</span><small>{Number.isFinite(row.wind as number)?`Wind ${wind(Number(row.wind),unit)} · Böen ${wind(Number(row.gust),unit)}`:'Wetterdaten fehlen'}{Number.isFinite(row.probability as number)?` · Regen ${Math.round(Number(row.probability))} %`:''}</small></article>)}</div>}
  <footer className="water-source"><span>Marine: Open-Meteo Best Match · Rasterabstand {marineUsable?`${formatNumber(gridDistance)} km`:'–'} · Wetter: ortsbezogener Best Match</span><small>Wellenrichtungen bezeichnen die Herkunft; Strömungsrichtungen das Ziel. `sea_level_height_msl` enthält Tide, Luftdruck- und weitere Meeresspiegelsignale und verwendet kein nautisches Kartennull. Küstenauflösung und Genauigkeit sind begrenzt. Nicht für Navigation, Rettungs- oder Sicherheitsentscheidungen.</small></footer>
 </section>
}
