import {memo,useEffect,useMemo,useState} from 'react';
import {ChevronLeft,ChevronRight,CloudRain,Info,Layers3,MapPinned,Pause,Play,RefreshCw} from 'lucide-react';
import {GeoJsonLayers,MapCenter,MidMapLibre,RasterTileLayer,WmsTileLayer} from './MapLibreCore';
import {loadWeatherMapGrid,loadWeatherMapMetadata,preferredWeatherMapTimeIndex,weatherMapModel,weatherMapProductsForModel,weatherMapProduct,weatherMapWmsProxy,WEATHER_MAP_MODELS,type WeatherMapGridData,type WeatherMapMetadata,type WeatherMapModelId,type WeatherMapProduct} from './WeatherMapsData';
import WeatherMapGridOverlay from './WeatherMapGridOverlay';

const SETTINGS_KEY='mid:weather-maps:v2';
type BasemapId='light'|'osm'|'dark';
type WeatherMapSettings={modelId:WeatherMapModelId;productId:string;level:number;opacity:number;basemap:BasemapId};
const BASEMAPS:Record<BasemapId,{label:string;url:string;attribution:string}>={light:{label:'Schlicht hell',url:'https://a.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',attribution:'© OpenStreetMap-Mitwirkende © CARTO'},osm:{label:'OpenStreetMap',url:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',attribution:'© OpenStreetMap-Mitwirkende'},dark:{label:'Schlicht dunkel',url:'https://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png',attribution:'© OpenStreetMap-Mitwirkende © CARTO'}};
function storedSettings():WeatherMapSettings{const fallbackProduct=weatherMapProduct('icon-eu-qff'),fallback:WeatherMapSettings={modelId:fallbackProduct.modelId,productId:fallbackProduct.id,level:fallbackProduct.defaultLevel??500,opacity:fallbackProduct.opacity??76,basemap:'light'};try{const parsed=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}') as Partial<WeatherMapSettings>,product=weatherMapProduct(String(parsed.productId||fallback.productId)),modelId=WEATHER_MAP_MODELS.some(item=>item.id===parsed.modelId)?parsed.modelId as WeatherMapModelId:product.modelId,validProduct=product.modelId===modelId?product:weatherMapProductsForModel(modelId)[0]??fallbackProduct,basemap=parsed.basemap&&BASEMAPS[parsed.basemap]?parsed.basemap:fallback.basemap,level=Number.isFinite(Number(parsed.level))?Number(parsed.level):validProduct.defaultLevel??fallback.level,opacity=Math.max(20,Math.min(100,Number(parsed.opacity)||validProduct.opacity||fallback.opacity));return{modelId,productId:validProduct.id,level,opacity,basemap}}catch{return fallback}}
function formatMapTime(value:string,timezone:string){const stamp=Date.parse(value);if(!Number.isFinite(stamp))return value;try{return new Intl.DateTimeFormat('de-DE',{timeZone:timezone,weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',timeZoneName:'short'}).format(new Date(stamp))}catch{return new Date(stamp).toLocaleString('de-DE')}}
function relativeMapTime(value:string){const stamp=Date.parse(value);if(!Number.isFinite(stamp))return'';const hours=Math.round((stamp-Date.now())/3600000);if(Math.abs(hours)<1)return'nahe jetzt';return hours>0?`+${hours} h`:`−${Math.abs(hours)} h`}
function leadTimeLabel(value:string,reference?:string){const stamp=Date.parse(value),base=reference?Date.parse(reference):NaN;if(!Number.isFinite(stamp)||!Number.isFinite(base))return relativeMapTime(value);const hours=Math.round((stamp-base)/3600000);return hours===0?'T+0':`T+${hours} h`}
function referenceTimeLabel(value:string|undefined,timezone:string){return value?formatMapTime(value,timezone):'neuester Modelllauf'}
function productLevel(product:WeatherMapProduct,selected:number,metadata:WeatherMapMetadata|null){const available=metadata?.elevations?.length?metadata.elevations:product.levels??[];if(!available.length)return undefined;if(available.includes(selected))return selected;if(product.defaultLevel&&available.includes(product.defaultLevel))return product.defaultLevel;return available[0]}
function levelLabel(product:WeatherMapProduct,value:number){return product.levelKind==='height'?`${value} m ü. Grund`:`${value} hPa`}

function WeatherMapsPanel({latitude,longitude,timezone,locationName}:{latitude:number;longitude:number;timezone:string;locationName:string}){
 const initial=useMemo(storedSettings,[]),[modelId,setModelId]=useState<WeatherMapModelId>(initial.modelId),[productId,setProductId]=useState(initial.productId),[selectedLevel,setSelectedLevel]=useState(initial.level),[opacity,setOpacity]=useState(initial.opacity),[basemap,setBasemap]=useState<BasemapId>(initial.basemap),[metadata,setMetadata]=useState<WeatherMapMetadata|null>(null),[gridData,setGridData]=useState<WeatherMapGridData|null>(null),[metadataError,setMetadataError]=useState(''),[tileError,setTileError]=useState(''),[loading,setLoading]=useState(false),[timeIndex,setTimeIndex]=useState(0),[playing,setPlaying]=useState(false),[revision,setRevision]=useState(0);
 const products=useMemo(()=>weatherMapProductsForModel(modelId),[modelId]),product=useMemo(()=>{const current=weatherMapProduct(productId);return current.modelId===modelId?current:products[0]??weatherMapProduct('icon-eu-qff')},[productId,modelId,products]),model=weatherMapModel(modelId),isGrid=product.source==='grid',wmsUrl=weatherMapWmsProxy(),times=isGrid?(gridData?.times??[]):(metadata?.times??[]),referenceTimes=isGrid?(gridData?.referenceTime?[gridData.referenceTime]:[]):(metadata?.referenceTimes??[]),referenceTime=referenceTimes.at(-1),selectedTime=times[Math.min(timeIndex,Math.max(0,times.length-1))]??'',selectedGridFrame=isGrid?(gridData?.frames.find(frame=>frame.time===selectedTime)??gridData?.frames[0]):undefined,level=productLevel(product,selectedLevel,metadata),currentBasemap=BASEMAPS[basemap];
 const availableLevels=useMemo(()=>{const candidates=metadata?.elevations?.length?metadata.elevations:product.levels??[];return[...new Set(candidates)].filter(Number.isFinite).sort((a,b)=>product.levelKind==='height'?a-b:b-a)},[metadata?.elevations,product.levels,product.levelKind]);
 useEffect(()=>{if(!product)return;const controller=new AbortController();setLoading(true);setMetadataError('');setTileError('');setPlaying(false);if(product.source==='grid'){setMetadata(null);void loadWeatherMapGrid(modelId,latitude,longitude,controller.signal).then(result=>{if(result.error)throw new Error(result.error);setGridData(result);setTimeIndex(preferredWeatherMapTimeIndex(result.times))}).catch(error=>{if(controller.signal.aborted)return;setGridData(null);setMetadataError(error instanceof Error?error.message:String(error));setTimeIndex(0)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)})}else{setGridData(null);void loadWeatherMapMetadata(product.layer,controller.signal).then(result=>{setMetadata(result);setTimeIndex(preferredWeatherMapTimeIndex(result.times));const levels=result.elevations?.length?result.elevations:product.levels??[],preferred=product.defaultLevel??selectedLevel;if(levels.length&&!levels.includes(selectedLevel))setSelectedLevel(levels.includes(preferred)?preferred:levels[0])}).catch(error=>{if(controller.signal.aborted)return;setMetadata(null);setMetadataError(error instanceof Error?error.message:String(error));setTimeIndex(0)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)})}return()=>controller.abort()},[product.id,modelId,latitude,longitude]);
 useEffect(()=>{if(!playing||times.length<2)return;const timer=window.setInterval(()=>setTimeIndex(index=>index>=times.length-1?0:index+1),950);return()=>window.clearInterval(timer)},[playing,times.length]);
 useEffect(()=>{try{localStorage.setItem(SETTINGS_KEY,JSON.stringify({modelId,productId:product.id,level:selectedLevel,opacity,basemap}))}catch{}},[modelId,product.id,selectedLevel,opacity,basemap]);
 useEffect(()=>{if(!products.some(item=>item.id===productId)&&products[0]){setProductId(products[0].id);setSelectedLevel(products[0].defaultLevel??500);setOpacity(products[0].opacity??76)}},[products,productId]);
 const chooseModel=(value:WeatherMapModelId)=>{const first=weatherMapProductsForModel(value)[0];setModelId(value);if(first){setProductId(first.id);setSelectedLevel(first.defaultLevel??500);setOpacity(first.opacity??76)}};
 const chooseProduct=(value:string)=>{const next=weatherMapProduct(value);setProductId(next.id);setSelectedLevel(next.defaultLevel??500);setOpacity(next.opacity??76)};
 const step=(delta:number)=>{setPlaying(false);setTimeIndex(index=>Math.max(0,Math.min(Math.max(0,times.length-1),index+delta)))};
 const params=useMemo(()=>({layers:product.layer,styles:'',format:'image/png',transparent:true,version:'1.1.1',tiled:true,...(selectedTime?{time:selectedTime}:{}),...(referenceTime?{dim_reference_time:referenceTime}:{}),...(level!==undefined?{elevation:String(level)}:{})} as any),[product.layer,selectedTime,referenceTime,level]);
 return <section className="weather-maps-panel"><header className="weather-maps-head"><span><small>Erweiterte Analyse · nur Modell-/Nowcastkarten</small><h2>Wetterkarten</h2><p>ICON-D2, ICON-EU, ICON Global, ICON-EPS, AICON und NowCastMIX – einschließlich SIGWX-/Wettercode-Karten der ICON-Serie – mit direkt auswählbaren Zeitschritten.</p></span><span className="weather-maps-source"><Layers3 size={18}/><b>{model.label}</b><small>{isGrid?(gridData?.provider||'DWD ICON-D2 Raster'):'DWD-Geodienst'}</small></span></header>
  <div className="weather-maps-toolbar">
   <label><span>Modell</span><select value={modelId} onChange={event=>chooseModel(event.target.value as WeatherMapModelId)}>{WEATHER_MAP_MODELS.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select><small>{model.detail}</small></label>
   <label><span>Karte</span><select value={product.id} onChange={event=>chooseProduct(event.target.value)}>{products.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select><small>{product.detail}</small></label>
   <label><span>Zeitschritt</span><select value={times.length?Math.min(timeIndex,times.length-1):-1} disabled={times.length<2} onChange={event=>{setPlaying(false);setTimeIndex(Number(event.target.value))}}>{times.length?times.map((value,index)=><option key={value} value={index}>{leadTimeLabel(value,referenceTime)} · {formatMapTime(value,timezone)}</option>):<option value={-1}>kein Gültigkeitszeitpunkt</option>}</select><small>{times.length?`${times.length} verfügbare Gültigkeitszeitpunkte`:'Kein Gültigkeitszeitpunkt verfügbar'}</small></label>
   {availableLevels.length?<label><span>{product.levelKind==='height'?'Höhe':'Druckfläche'}</span><select value={level??availableLevels[0]} onChange={event=>setSelectedLevel(Number(event.target.value))}>{availableLevels.map(value=><option key={value} value={value}>{levelLabel(product,value)}</option>)}</select><small>{product.levelKind==='height'?'Höhe über Grund':'Atmosphärisches Druckniveau'}</small></label>:null}
   <label><span>Kartenbasis</span><select value={basemap} onChange={event=>setBasemap(event.target.value as BasemapId)}>{Object.entries(BASEMAPS).map(([id,item])=><option key={id} value={id}>{item.label}</option>)}</select><small>Orientierungsebene</small></label>
  </div>
  <div className="weather-maps-validity"><span><small>INIT</small><b>{referenceTime?referenceTimeLabel(referenceTime,timezone):'–'}</b></span><span><small>GÜLTIG</small><b>{selectedTime?formatMapTime(selectedTime,timezone):'–'}</b></span></div>
  <div className="weather-maps-map-shell"><MidMapLibre center={[latitude,longitude]} zoom={product.defaultZoom} minZoom={2} maxZoom={10} className="weather-maps-maplibre" scrollZoom={false}><MapCenter latitude={latitude} longitude={longitude} zoom={product.defaultZoom}/><RasterTileLayer id={`weather-basemap-${basemap}`} url={currentBasemap.url} attribution={currentBasemap.attribution}/>{isGrid&&gridData&&selectedGridFrame&&product.gridKind?<WeatherMapGridOverlay data={gridData} frame={selectedGridFrame} kind={product.gridKind} opacity={opacity/100}/>:null}{!isGrid&&wmsUrl?<WmsTileLayer id={`weather-wms-${product.id}-${selectedTime||'latest'}-${referenceTime||'latest-run'}-${level??'surface'}-${revision}`} baseUrl={`${wmsUrl}${wmsUrl.includes('?')?'&':'?'}mid-map=${revision}`} opacity={opacity/100} params={params} onReady={()=>setTileError('')} onError={()=>setTileError(`${product.label} konnte für den gewählten Termin nicht geladen werden.`)} attribution="Wetterkarten © Deutscher Wetterdienst"/>:null}<GeoJsonLayers id="weather-selected-location" data={{type:'FeatureCollection',features:[{type:'Feature',properties:{label:`<strong>${locationName}</strong><br/>gewählter Standort`},geometry:{type:'Point',coordinates:[longitude,latitude]}}]}} layers={[{id:'halo',type:'circle',paint:{'circle-radius':7,'circle-color':'#1675d1','circle-opacity':.78,'circle-stroke-color':'#ffffff','circle-stroke-width':2}}]} hoverProperty="label"/></MidMapLibre>{!isGrid&&!wmsUrl?<div className="weather-maps-overlay-message"><CloudRain size={28}/><strong>Worker nicht konfiguriert</strong><span>Für die CORS-sicheren DWD-Wetterkarten wird der MID-Worker benötigt.</span></div>:null}{loading?<div className="weather-maps-loading"><RefreshCw className="spin" size={20}/>Kartenzeiten werden geprüft …</div>:null}</div>
  <div className="weather-maps-controls"><div className="weather-maps-playback"><button type="button" disabled={times.length<2||timeIndex<=0} onClick={()=>step(-1)} aria-label="Vorheriger Kartenzeitschritt"><ChevronLeft size={18}/></button><button type="button" disabled={times.length<2} onClick={()=>setPlaying(value=>!value)} aria-label={playing?'Kartenanimation pausieren':'Kartenanimation starten'}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><button type="button" disabled={times.length<2||timeIndex>=times.length-1} onClick={()=>step(1)} aria-label="Nächster Kartenzeitschritt"><ChevronRight size={18}/></button></div><label className="weather-maps-timeline"><span>{times.length?`${timeIndex+1} / ${times.length} Zeitschritte`:'kein Gültigkeitszeitpunkt'}</span><input type="range" min={0} max={Math.max(0,times.length-1)} value={Math.min(timeIndex,Math.max(0,times.length-1))} disabled={times.length<2} onChange={event=>{setPlaying(false);setTimeIndex(Number(event.target.value))}}/><b>{selectedTime?formatMapTime(selectedTime,timezone):'–'}{selectedTime?<small>{leadTimeLabel(selectedTime,referenceTime)}</small>:null}</b></label><label className="weather-maps-opacity"><span>Deckkraft <b>{Math.round(opacity)} %</b></span><input type="range" min={20} max={100} value={opacity} onChange={event=>setOpacity(Number(event.target.value))}/></label><button type="button" className="weather-maps-reload" onClick={()=>{setTileError('');setRevision(value=>value+1)}}><RefreshCw size={16}/>Neu laden</button></div>
  <div className="weather-maps-meta"><span><MapPinned size={15}/><b>{product.label}</b><small>{level!==undefined?levelLabel(product,level):product.detail}</small></span><span><Info size={15}/><b>INIT</b><small>{referenceTime?referenceTimeLabel(referenceTime,timezone):'nicht verfügbar'}</small></span><span><Layers3 size={15}/><b>Gültig</b><small>{selectedTime?formatMapTime(selectedTime,timezone):'nicht verfügbar'}</small></span><span><Layers3 size={15}/><b>Quelle</b><small>{isGrid?(gridData?.provider||'DWD ICON-D2 Raster'):product.layer}</small></span></div>
  {metadataError?<p className="weather-maps-warning">Kartendaten bzw. Gültigkeitszeitpunkt konnten nicht geladen werden: {metadataError}.</p>:null}{tileError?<p className="weather-maps-warning">{tileError}</p>:null}{product.category==='significant'?<p className="weather-maps-warning">Bei leerer Karte liegt im sichtbaren Ausschnitt aktuell entweder kein entsprechendes Signal vor oder der DWD stellt für diesen Zeitpunkt keinen passenden Datensatz bereit.</p>:null}{product.disclaimer?<p className="weather-maps-disclaimer">{product.disclaimer}</p>:<p className="weather-maps-disclaimer">DWD Open Data / WMS. Ausschließlich Modell- und Nowcastkarten; Satellitenbilder sind in diesem Modul bewusst ausgeschlossen.</p>}
 </section>
}
export default memo(WeatherMapsPanel);
