export type WindUnit='kn'|'kmh'|'ms'|'mph';
export type Location={id:number;name:string;latitude:number;longitude:number;elevation?:number;timezone?:string;country?:string;country_code?:string;admin1?:string;postcodes?:string[]};
export type Weather={latitude:number;longitude:number;elevation:number;timezone:string;current:Record<string,number|string>;hourly:Record<string,(number|string)[]>;daily:Record<string,(number|string)[]>};
export type Hour={time:string;temperature:number;apparent:number;humidity:number;dewPoint:number;precipitation:number;probability:number;code:number;wind:number;gust:number;direction:number;cloud:number;isDay:boolean};
export type Day={date:string;code:number;max:number;min:number;precipitation:number;probability:number;wind:number;gust:number;direction:number};
export type EnsembleDay={date:string;maxMean:number;maxLow:number;maxHigh:number;minMean:number;minLow:number;minHigh:number;precipitationMean:number;precipitationLow:number;precipitationHigh:number;modelCount:number};
export type Station={name:string;distance?:number;height?:number;timestamp?:string;temperature?:number;humidity?:number;dewPoint?:number;pressure?:number;windSpeed?:number;windDirection?:number;windGust?:number;cloudCover?:number;precipitation?:number};

const ensembleModels=['dwd_icon_eps_ensemble_mean_seamless','dwd_icon_eps_ensemble_mean_global','dwd_icon_eps_ensemble_mean_eu','dwd_icon_eps_ensemble_mean_d2','gfs_seamless_ensemble_mean','gfs025_ensemble_mean','gfs05_ensemble_mean','hgefs025_ensemble_mean','ecmwf_ifs025_ensemble_mean','ecmwf_aifs025_ensemble_mean','gem_global_ensemble_mean','bom_access_global_ensemble_mean','ukmo_global_ensemble_mean','ukmo_uk_ensemble_mean','meteoswiss_icon_ch1_ensemble_mean','meteoswiss_icon_ch2_ensemble_mean'];
async function j<T>(url:string,signal?:AbortSignal):Promise<T>{const r=await fetch(url,{signal,cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
export async function searchLocations(q:string,signal?:AbortSignal){const p=new URLSearchParams({name:q,count:'8',language:'de',format:'json'});return (await j<{results?:Location[]}>(`https://geocoding-api.open-meteo.com/v1/search?${p}`,signal)).results??[]}
export async function forecast(lat:number,lon:number,signal?:AbortSignal){const p=new URLSearchParams({latitude:String(lat),longitude:String(lon),timezone:'auto',forecast_days:'14',models:'best_match',wind_speed_unit:'kn',current:['temperature_2m','relative_humidity_2m','dew_point_2m','apparent_temperature','is_day','precipitation','weather_code','cloud_cover','pressure_msl','wind_speed_10m','wind_direction_10m','wind_gusts_10m'].join(','),hourly:['temperature_2m','relative_humidity_2m','dew_point_2m','apparent_temperature','precipitation_probability','precipitation','weather_code','cloud_cover','wind_speed_10m','wind_direction_10m','wind_gusts_10m','is_day'].join(','),daily:['weather_code','temperature_2m_max','temperature_2m_min','sunrise','sunset','precipitation_sum','precipitation_probability_max','wind_speed_10m_max','wind_gusts_10m_max','wind_direction_10m_dominant'].join(',')});return j<Weather>(`https://api.open-meteo.com/v1/forecast?${p}`,signal)}
export async function airQuality(lat:number,lon:number,signal?:AbortSignal){const p=new URLSearchParams({latitude:String(lat),longitude:String(lon),timezone:'auto',current:['european_aqi','pm10','pm2_5','nitrogen_dioxide','ozone','uv_index'].join(',')});return j<{current?:Record<string,number|string>}>(`https://air-quality-api.open-meteo.com/v1/air-quality?${p}`,signal)}
export async function station(lat:number,lon:number,country?:string,elevation?:number,signal?:AbortSignal):Promise<Station|null>{const de=country==='DE'||(!country&&lat>=47&&lat<=55.2&&lon>=5.5&&lon<=15.6);if(!de)return null;try{const p=new URLSearchParams({lat:String(lat),lon:String(lon),max_dist:'50000'});const d=await j<any>(`https://api.brightsky.dev/current_weather?${p}`,signal);const w=d.weather;const sources=(d.sources??[]) as any[];if(!w||!sources.length)return null;const num=(v:any)=>Number.isFinite(Number(v))?Number(v):undefined;const byId=sources.find((x:any)=>x.id===w.source_id);const scored=[...sources].sort((a:any,b:any)=>{const distA=num(a.distance)??999999,distB=num(b.distance)??999999;const hA=Math.abs((num(a.height)??0)-Number(elevation??0)),hB=Math.abs((num(b.height)??0)-Number(elevation??0));const sA=distA+hA*15,sB=distB+hB*15;return sA-sB});const s=byId??scored[0];return{name:s.station_name||'DWD-Station',distance:num(s.distance),height:num(s.height),timestamp:w.timestamp,temperature:num(w.temperature),humidity:num(w.relative_humidity),dewPoint:num(w.dew_point),pressure:num(w.pressure_msl),windSpeed:num(w.wind_speed),windDirection:num(w.wind_direction),windGust:num(w.wind_gust_speed),cloudCover:num(w.cloud_cover),precipitation:num(w.precipitation)}}catch{return null}}
export function mapHours(w:Weather):Hour[]{return (w.hourly.time as string[]).map((time,i)=>({time,temperature:Number(w.hourly.temperature_2m[i]),apparent:Number(w.hourly.apparent_temperature[i]),humidity:Number(w.hourly.relative_humidity_2m[i]),dewPoint:Number(w.hourly.dew_point_2m[i]),precipitation:Number(w.hourly.precipitation[i]),probability:Number(w.hourly.precipitation_probability[i]),code:Number(w.hourly.weather_code[i]),wind:Number(w.hourly.wind_speed_10m[i]),gust:Number(w.hourly.wind_gusts_10m[i]),direction:Number(w.hourly.wind_direction_10m[i]),cloud:Number(w.hourly.cloud_cover[i]),isDay:Number(w.hourly.is_day[i])===1}))}
export function mapDays(w:Weather):Day[]{return (w.daily.time as string[]).map((date,i)=>({date,code:Number(w.daily.weather_code[i]),max:Number(w.daily.temperature_2m_max[i]),min:Number(w.daily.temperature_2m_min[i]),precipitation:Number(w.daily.precipitation_sum[i]),probability:Number(w.daily.precipitation_probability_max[i]),wind:Number(w.daily.wind_speed_10m_max[i]),gust:Number(w.daily.wind_gusts_10m_max[i]),direction:Number(w.daily.wind_direction_10m_dominant[i])}))}
export function currentIndex(h:Hour[]){const n=Date.now();return h.reduce((b,x,i)=>{const d=Math.abs(new Date(x.time).getTime()-n);return d<b.d?{i,d}:b},{i:0,d:Infinity}).i}
function dailyEnsemble(w:Weather){const m=new Map<string,{t:number[];p:number[]}>();(w.hourly.time as string[]).forEach((time,i)=>{const d=time.slice(0,10);if(!m.has(d))m.set(d,{t:[],p:[]});const r=m.get(d)!;const t=Number(w.hourly.temperature_2m[i]),p=Number(w.hourly.precipitation[i]);if(Number.isFinite(t)&&t>-70&&t<70)r.t.push(t);if(Number.isFinite(p)&&p>=0&&p<500)r.p.push(Math.max(0,p))});const out=new Map<string,{max:number;min:number;precipitation:number}>();m.forEach((v,d)=>{if(v.t.length>=6)out.set(d,{max:Math.max(...v.t),min:Math.min(...v.t),precipitation:v.p.reduce((a,b)=>a+b,0)})});return out}
function plausibleModel(model:{model:string;daily:Map<string,{max:number;min:number;precipitation:number}>}){const rows=[...model.daily.values()];if(rows.length<10)return false;const jumps=rows.slice(1).filter((r,i)=>Math.abs(r.max-rows[i].max)>15||Math.abs(r.min-rows[i].min)>15).length;return jumps<=2&&rows.every(r=>Number.isFinite(r.max)&&Number.isFinite(r.min)&&r.max>=r.min&&r.max<55&&r.min>-45&&r.precipitation>=0&&r.precipitation<400)}
export async function ensembles(lat:number,lon:number,signal?:AbortSignal){
  const settled=await Promise.allSettled(ensembleModels.map(async model=>{const p=new URLSearchParams({latitude:String(lat),longitude:String(lon),timezone:'auto',forecast_days:'14',models:model,hourly:['temperature_2m','precipitation'].join(',')});const w=await j<Weather>(`https://ensemble-api.open-meteo.com/v1/ensemble?${p}`,signal);return{model,daily:dailyEnsemble(w)}}));
  const preliminary=settled.filter((x):x is PromiseFulfilledResult<any>=>x.status==='fulfilled').map(x=>x.value).filter(plausibleModel);
  const dates=[...new Set(preliminary.flatMap(x=>[...x.daily.keys()]))].sort().slice(0,14);
  const median=(vals:number[])=>{const a=[...vals].sort((x,y)=>x-y);if(!a.length)return NaN;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
  const q=(vals:number[],p:number)=>{const a=[...vals].sort((x,y)=>x-y);if(!a.length)return NaN;const idx=(a.length-1)*p,lo=Math.floor(idx),hi=Math.ceil(idx),w=idx-lo;return hi===lo?a[lo]:a[lo]*(1-w)+a[hi]*w};
  const refined=preliminary.filter(model=>{let n=0,sum=0,extreme=0;for(const date of dates){const own=model.daily.get(date);if(!own)continue;const pool=preliminary.map(x=>x.daily.get(date)).filter(Boolean) as {max:number;min:number;precipitation:number}[];const medMax=median(pool.map(x=>x.max)),medMin=median(pool.map(x=>x.min));const dev=(Math.abs(own.max-medMax)+Math.abs(own.min-medMin))/2;if(Number.isFinite(dev)){n++;sum+=dev;if(dev>8)extreme++;}}const mad=n?sum/n:999;return n>=10&&mad<=6&&extreme<=3});
  const ok=refined.length>=3?refined:preliminary;
  const avg=(v:number[])=>v.reduce((a,b)=>a+b,0)/Math.max(1,v.length);
  const cleaned=(vals:number[],absDev:number)=>{const src=vals.filter(Number.isFinite);if(src.length<3)return src;const med=median(src);const sorted=[...src].sort((a,b)=>a-b);const q1=q(sorted,.25),q3=q(sorted,.75),iqr=q3-q1;const lo=q1-1.5*iqr,hi=q3+1.5*iqr;const filtered=src.filter(v=>Math.abs(v-med)<=absDev&&v>=lo&&v<=hi);const relaxed=src.filter(v=>Math.abs(v-med)<=absDev);return filtered.length>=2?filtered:(relaxed.length>=2?relaxed:src)};
  const days:EnsembleDay[]=dates.map(date=>{const rows=ok.map(x=>x.daily.get(date)).filter(Boolean) as {max:number;min:number;precipitation:number}[];const maxRaw=rows.map(x=>x.max).filter(Number.isFinite),minRaw=rows.map(x=>x.min).filter(Number.isFinite),rainRaw=rows.map(x=>x.precipitation).filter(Number.isFinite);const maxima=cleaned(maxRaw,6),minima=cleaned(minRaw,6),rain=cleaned(rainRaw,15);if(!maxima.length||!minima.length)return null;const maxLow=maxima.length>=4?q(maxima,.25):Math.min(...maxima),maxHigh=maxima.length>=4?q(maxima,.75):Math.max(...maxima),minLow=minima.length>=4?q(minima,.25):Math.min(...minima),minHigh=minima.length>=4?q(minima,.75):Math.max(...minima),precipitationLow=rain.length>=4?q(rain,.25):Math.min(...rain),precipitationHigh=rain.length>=4?q(rain,.75):Math.max(...rain);return{date,maxMean:avg(maxima),maxLow,maxHigh,minMean:avg(minima),minLow,minHigh,precipitationMean:avg(rain),precipitationLow,precipitationHigh,modelCount:Math.min(maxima.length,minima.length)}}).filter(Boolean).filter(x=>Number.isFinite(x!.maxMean)&&Number.isFinite(x!.minMean)) as EnsembleDay[];
  return{days,models:ok.map(x=>x.model)}
}
export function label(c:number){const m:Record<number,string>={0:'Klar',1:'Überwiegend klar',2:'Teilweise bewölkt',3:'Bedeckt',45:'Nebel',48:'Reifnebel',51:'Nieselregen',53:'Nieselregen',55:'Starker Nieselregen',61:'Leichter Regen',63:'Regen',65:'Starker Regen',71:'Leichter Schneefall',73:'Schneefall',75:'Starker Schneefall',80:'Regenschauer',81:'Kräftige Schauer',82:'Starke Schauer',85:'Schneeschauer',86:'Starke Schneeschauer',95:'Gewitter',96:'Gewitter mit Hagel',99:'Starkes Gewitter'};return m[c]??'Wechselhaft'}
export function icon(c:number,day=true){if(c===0)return day?'☀️':'🌙';if(c===1)return day?'🌤️':'🌙';if(c===2)return'⛅';if(c===3)return'☁️';if([45,48].includes(c))return'🌫️';if([51,53,55,80].includes(c))return'🌦️';if([61,63,65,81,82].includes(c))return'🌧️';if([71,73,75,85,86].includes(c))return'🌨️';if([95,96,99].includes(c))return'⛈️';return'🌤️'}
export function wind(v:number,u:WindUnit){if(u==='kmh')return`${Math.round(v*1.852)} km/h`;if(u==='ms')return`${(v*.514444).toFixed(1)} m/s`;if(u==='mph')return`${Math.round(v*1.15078)} mph`;return`${Math.round(v)} kt`}
export function hazards(h:Hour[]){const s=h.slice(currentIndex(h),currentIndex(h)+24),max=Math.max(...s.map(x=>x.temperature)),min=Math.min(...s.map(x=>x.temperature)),gust=Math.max(...s.map(x=>x.gust)),rain=s.reduce((a,b)=>a+b.precipitation,0),thunder=s.some(x=>[95,96,99].includes(x.code));const a:{level:'yellow'|'red';title:string;text:string}[]=[];if(max>=32)a.push({level:max>=37?'red':'yellow',title:'Hitzebelastung',text:`Bis ${Math.round(max)} °C in 24 Stunden.`});if(min<=1)a.push({level:min<=-5?'red':'yellow',title:'Frost-/Glättepotenzial',text:`Tiefstwerte um ${Math.round(min)} °C.`});if(gust>=35)a.push({level:gust>=50?'red':'yellow',title:'Stürmische Böen',text:`Böen bis ${Math.round(gust)} kt.`});if(rain>=20)a.push({level:rain>=35?'red':'yellow',title:'Starkregenpotenzial',text:`Etwa ${Math.round(rain)} mm in 24 Stunden.`});if(thunder)a.push({level:'yellow',title:'Gewitterpotenzial',text:'Gewittersignale in der Kurzfristvorhersage.'});return a}
