export type WindUnit='kn'|'kmh'|'ms'|'mph';
export type Location={id:number;name:string;latitude:number;longitude:number;elevation?:number;timezone?:string;country?:string;country_code?:string;admin1?:string;postcodes?:string[]};
export type Weather={latitude:number;longitude:number;elevation:number;timezone:string;current:Record<string,number|string>;hourly:Record<string,(number|string|null)[]>;daily:Record<string,(number|string|null)[]>};
export type Hour={time:string;temperature:number;apparent:number;humidity:number;dewPoint:number;precipitation:number;probability:number;code:number;wind:number;gust:number;direction:number;cloud:number;isDay:boolean};
export type Day={date:string;code:number;max:number;min:number;precipitation:number;probability:number;wind:number;gust:number;direction:number};
export type EnsembleDay={date:string;maxMean:number;maxLow:number;maxHigh:number;minMean:number;minLow:number;minHigh:number;precipitationMean:number;precipitationLow:number;precipitationHigh:number;modelCount:number;memberCount:number};
export type Station={name:string;provider?:string;stationId?:string;distance?:number;height?:number;timestamp?:string;temperature?:number;humidity?:number;dewPoint?:number;pressure?:number;windSpeed?:number;windDirection?:number;windGust?:number;cloudCover?:number;precipitation?:number};

type EnsembleModel={id:string;label:string;baseWeight:number;provider:string};
const ensembleModels:EnsembleModel[]=[
 {id:'ensemble_icon_seamless',label:'DWD ICON EPS Seamless',baseWeight:1.25,provider:'DWD'},
 {id:'ensemble_gfs_seamless',label:'NOAA GFS Ensemble Seamless',baseWeight:1.08,provider:'NOAA'},
 {id:'ensemble_ecmwf_ifs025',label:'ECMWF IFS Ensemble',baseWeight:1.3,provider:'ECMWF'},
 {id:'ensemble_ecmwf_aifs025',label:'ECMWF AIFS Ensemble',baseWeight:1.15,provider:'ECMWF'},
 {id:'ensemble_gem_global',label:'GEM Global Ensemble',baseWeight:.95,provider:'ECCC'},
 {id:'ensemble_bom_access_global',label:'BOM ACCESS Global Ensemble',baseWeight:.72,provider:'BOM'},
 {id:'ensemble_ukmo_global',label:'UKMO Global Ensemble',baseWeight:1.0,provider:'UKMO'},
 {id:'ensemble_aigefs025',label:'NOAA AIGEFS 0.25°',baseWeight:1.05,provider:'NOAA'},
 {id:'ensemble_google_weathernext2',label:'Google WeatherNext 2',baseWeight:1.1,provider:'Google'}
];

async function j<T>(url:string,signal?:AbortSignal):Promise<T>{const r=await fetch(url,{signal,cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
export async function searchLocations(q:string,signal?:AbortSignal){const p=new URLSearchParams({name:q,count:'8',language:'de',format:'json'});return (await j<{results?:Location[]}>(`https://geocoding-api.open-meteo.com/v1/search?${p}`,signal)).results??[]}
export async function forecast(lat:number,lon:number,signal?:AbortSignal){const p=new URLSearchParams({latitude:String(lat),longitude:String(lon),timezone:'auto',forecast_days:'14',models:'best_match',wind_speed_unit:'kn',current:['temperature_2m','relative_humidity_2m','dew_point_2m','apparent_temperature','is_day','precipitation','weather_code','cloud_cover','pressure_msl','wind_speed_10m','wind_direction_10m','wind_gusts_10m'].join(','),hourly:['temperature_2m','relative_humidity_2m','dew_point_2m','apparent_temperature','precipitation_probability','precipitation','weather_code','cloud_cover','wind_speed_10m','wind_direction_10m','wind_gusts_10m','is_day'].join(','),daily:['weather_code','temperature_2m_max','temperature_2m_min','sunrise','sunset','precipitation_sum','precipitation_probability_max','wind_speed_10m_max','wind_gusts_10m_max','wind_direction_10m_dominant'].join(',')});return j<Weather>(`https://api.open-meteo.com/v1/forecast?${p}`,signal)}
export async function airQuality(lat:number,lon:number,signal?:AbortSignal){const p=new URLSearchParams({latitude:String(lat),longitude:String(lon),timezone:'auto',current:['european_aqi','pm10','pm2_5','nitrogen_dioxide','ozone','uv_index'].join(',')});return j<{current?:Record<string,number|string>}>(`https://air-quality-api.open-meteo.com/v1/air-quality?${p}`,signal)}

function haversine(lat1:number,lon1:number,lat2:number,lon2:number){const r=6371000,toRad=(x:number)=>x*Math.PI/180,dLat=toRad(lat2-lat1),dLon=toRad(lon2-lon1),a=Math.sin(dLat/2)**2+Math.cos(toRad(lat1))*Math.cos(toRad(lat2))*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.sqrt(a))}
async function brightSkyStation(lat:number,lon:number,elevation?:number,signal?:AbortSignal):Promise<Station|null>{try{const p=new URLSearchParams({lat:String(lat),lon:String(lon),max_dist:'75000'});const d=await j<any>(`https://api.brightsky.dev/current_weather?${p}`,signal);const w=d.weather,sources=(d.sources??[]) as any[];if(!w||!sources.length)return null;const num=(v:any)=>Number.isFinite(Number(v))?Number(v):undefined;const scored=[...sources].sort((a:any,b:any)=>{const distA=num(a.distance)??999999,distB=num(b.distance)??999999;const hA=Math.abs((num(a.height)??0)-Number(elevation??0)),hB=Math.abs((num(b.height)??0)-Number(elevation??0));return(distA+hA*12)-(distB+hB*12)});const byId=sources.find((x:any)=>x.id===w.source_id),s=byId??scored[0];return{name:s.station_name||'DWD/WMO-Station',provider:'Bright Sky / DWD',stationId:s.wmo_station_id||s.id,distance:num(s.distance),height:num(s.height),timestamp:w.timestamp,temperature:num(w.temperature),humidity:num(w.relative_humidity),dewPoint:num(w.dew_point),pressure:num(w.pressure_msl),windSpeed:num(w.wind_speed),windDirection:num(w.wind_direction),windGust:num(w.wind_gust_speed),cloudCover:num(w.cloud_cover),precipitation:num(w.precipitation)}}catch{return null}}
async function metarProxyStation(lat:number,lon:number,elevation?:number,signal?:AbortSignal):Promise<Station|null>{const base=((import.meta as any).env?.VITE_METAR_PROXY_URL as string|undefined)||localStorage.getItem('metarProxyUrl')||'';if(!base)return null;try{const u=new URL(base);u.searchParams.set('lat',String(lat));u.searchParams.set('lon',String(lon));u.searchParams.set('radius_km','120');const d=await j<any>(u.toString(),signal);const rows=(Array.isArray(d)?d:d.data??d.metars??[]) as any[];const candidates=rows.map(r=>{const rlat=Number(r.lat??r.latitude),rlon=Number(r.lon??r.longitude);if(!Number.isFinite(rlat)||!Number.isFinite(rlon))return null;const distance=haversine(lat,lon,rlat,rlon),height=Number(r.elev??r.elevation??r.elevation_m);const heightPenalty=Number.isFinite(height)&&Number.isFinite(elevation)?Math.abs(height-Number(elevation))*12:0;return{r,distance,score:distance+heightPenalty,height}}).filter(Boolean).sort((a:any,b:any)=>a.score-b.score);const c:any=candidates[0];if(!c)return null;const r=c.r,num=(v:any)=>Number.isFinite(Number(v))?Number(v):undefined;return{name:r.name||r.site||r.station||r.icaoId||'METAR/WMO-Station',provider:r.provider||'METAR / WMO',stationId:r.icaoId||r.wmoId||r.id,distance:c.distance,height:num(c.height),timestamp:r.reportTime||r.obsTime||r.timestamp,temperature:num(r.temp??r.temperature),dewPoint:num(r.dewp??r.dewPoint),humidity:num(r.relativeHumidity??r.humidity),pressure:num(r.altim??r.pressureMsl??r.pressure),windSpeed:num(r.wspd??r.windSpeed),windDirection:num(r.wdir??r.windDirection),windGust:num(r.wgst??r.windGust),cloudCover:num(r.cloudCover),precipitation:num(r.precipitation)}}catch{return null}}
export async function station(lat:number,lon:number,country?:string,elevation?:number,signal?:AbortSignal):Promise<Station|null>{const tasks=[metarProxyStation(lat,lon,elevation,signal)];if(country==='DE'||(!country&&lat>=47&&lat<=55.2&&lon>=5.5&&lon<=15.6))tasks.push(brightSkyStation(lat,lon,elevation,signal));const results=(await Promise.allSettled(tasks)).filter((x):x is PromiseFulfilledResult<Station|null>=>x.status==='fulfilled').map(x=>x.value).filter(Boolean) as Station[];if(!results.length)return null;return results.sort((a,b)=>{const da=a.distance??999999,db=b.distance??999999,ha=Math.abs((a.height??elevation??0)-(elevation??0)),hb=Math.abs((b.height??elevation??0)-(elevation??0));return(da+ha*12)-(db+hb*12)})[0]}

function n(v:unknown,fallback=NaN){return v===null||v===undefined||v===''?fallback:Number(v)}
export function mapHours(w:Weather):Hour[]{return (w.hourly.time as string[]).map((time,i)=>({time,temperature:n(w.hourly.temperature_2m[i]),apparent:n(w.hourly.apparent_temperature[i]),humidity:n(w.hourly.relative_humidity_2m[i]),dewPoint:n(w.hourly.dew_point_2m[i]),precipitation:n(w.hourly.precipitation[i],0),probability:n(w.hourly.precipitation_probability[i],0),code:n(w.hourly.weather_code[i],3),wind:n(w.hourly.wind_speed_10m[i],0),gust:n(w.hourly.wind_gusts_10m[i],0),direction:n(w.hourly.wind_direction_10m[i],0),cloud:n(w.hourly.cloud_cover[i],0),isDay:n(w.hourly.is_day[i],0)===1})).filter(x=>Number.isFinite(x.temperature))}
export function mapDays(w:Weather):Day[]{return (w.daily.time as string[]).map((date,i)=>({date,code:n(w.daily.weather_code[i],3),max:n(w.daily.temperature_2m_max[i]),min:n(w.daily.temperature_2m_min[i]),precipitation:n(w.daily.precipitation_sum[i],0),probability:n(w.daily.precipitation_probability_max[i],0),wind:n(w.daily.wind_speed_10m_max[i],0),gust:n(w.daily.wind_gusts_10m_max[i],0),direction:n(w.daily.wind_direction_10m_dominant[i],0)})).filter(d=>Number.isFinite(d.max)&&Number.isFinite(d.min)&&d.max>=d.min)}
export function currentIndex(h:Hour[]){const n=Date.now();return h.reduce((b,x,i)=>{const d=Math.abs(new Date(x.time).getTime()-n);return d<b.d?{i,d}:b},{i:0,d:Infinity}).i}

function quantile(values:number[],p:number){const a=[...values].sort((x,y)=>x-y);if(!a.length)return NaN;const idx=(a.length-1)*p,lo=Math.floor(idx),hi=Math.ceil(idx),w=idx-lo;return hi===lo?a[lo]:a[lo]*(1-w)+a[hi]*w}
function weightedQuantile(values:{value:number;weight:number}[],p:number){const a=values.filter(x=>Number.isFinite(x.value)&&x.weight>0).sort((x,y)=>x.value-y.value);const total=a.reduce((s,x)=>s+x.weight,0);if(!a.length||total<=0)return NaN;const target=total*p;let c=0;for(const x of a){c+=x.weight;if(c>=target)return x.value}return a[a.length-1].value}
function weightedMean(values:{value:number;weight:number}[]){const a=values.filter(x=>Number.isFinite(x.value)&&x.weight>0),w=a.reduce((s,x)=>s+x.weight,0);return w?a.reduce((s,x)=>s+x.value*x.weight,0)/w:NaN}
type MemberDay={date:string;max:number;min:number;precipitation:number};
type ModelResult={model:EnsembleModel;members:Map<string,MemberDay[]>};
function parseModelMembers(w:Weather,model:EnsembleModel):ModelResult|null{const times=(w.hourly.time as string[])??[],keys=Object.keys(w.hourly),tempKeys=keys.filter(k=>/^temperature_2m(?:_member\d+)?$/.test(k)),precipKeys=keys.filter(k=>/^precipitation(?:_member\d+)?$/.test(k));if(!times.length||!tempKeys.length)return null;const suffix=(k:string)=>k.replace('temperature_2m',''),pBySuffix=new Map(precipKeys.map(k=>[k.replace('precipitation',''),k]));const members=new Map<string,MemberDay[]>();for(const tk of tempKeys){const s=suffix(tk),pk=pBySuffix.get(s),temps=w.hourly[tk]??[],rain=pk?w.hourly[pk]??[]:[];const daily=new Map<string,{t:number[];p:number[]}>();for(let i=0;i<times.length;i++){const date=String(times[i]).slice(0,10),tr=temps[i],pr=rain[i],tv=tr===null||tr===undefined||tr===''?NaN:Number(tr),pv=pr===null||pr===undefined||pr===''?NaN:Number(pr);if(!daily.has(date))daily.set(date,{t:[],p:[]});const d=daily.get(date)!;if(Number.isFinite(tv)&&tv>-60&&tv<60)d.t.push(tv);if(Number.isFinite(pv)&&pv>=0&&pv<150)d.p.push(pv)}const rows:MemberDay[]=[];daily.forEach((d,date)=>{if(d.t.length>=12){const max=Math.max(...d.t),min=Math.min(...d.t),precipitation=d.p.reduce((a,b)=>a+b,0);if(Number.isFinite(max)&&Number.isFinite(min)&&max>=min&&max-min<35)rows.push({date,max,min,precipitation})}});if(rows.length>=2)members.set(s||'_control',rows)}return members.size?{model,members}:null}
function modelDayWeight(model:EnsembleModel,lead:number,memberCount:number){const horizonFactor=lead<=3?1.08:lead<=7?1:lead<=10?.93:.86;return model.baseWeight*horizonFactor/Math.max(1,memberCount)}
export async function ensembles(lat:number,lon:number,signal?:AbortSignal){const settled=await Promise.allSettled(ensembleModels.map(async model=>{const p=new URLSearchParams({latitude:String(lat),longitude:String(lon),timezone:'auto',forecast_days:'14',models:model.id,hourly:['temperature_2m','precipitation'].join(',')});const w=await j<Weather>(`https://ensemble-api.open-meteo.com/v1/ensemble?${p}`,signal);return parseModelMembers(w,model)}));const results=settled.filter((x):x is PromiseFulfilledResult<ModelResult|null>=>x.status==='fulfilled').map(x=>x.value).filter(Boolean) as ModelResult[];const allDates=[...new Set(results.flatMap(r=>[...r.members.values()].flatMap(m=>m.map(x=>x.date))))].sort().slice(0,14);const days:EnsembleDay[]=[];for(let lead=0;lead<allDates.length;lead++){const date=allDates[lead],maxVals:{value:number;weight:number}[]=[],minVals:{value:number;weight:number}[]=[],rainVals:{value:number;weight:number}[]=[],modelsUsed=new Set<string>();let memberCount=0;for(const r of results){const memberRows=[...r.members.values()].map(rows=>rows.find(x=>x.date===date)).filter(Boolean) as MemberDay[];if(!memberRows.length)continue;const medMax=quantile(memberRows.map(x=>x.max),.5),medMin=quantile(memberRows.map(x=>x.min),.5),filtered=memberRows.filter(x=>Math.abs(x.max-medMax)<=8&&Math.abs(x.min-medMin)<=8);const rows=filtered.length>=Math.max(3,Math.ceil(memberRows.length*.6))?filtered:memberRows;if(!rows.length)continue;modelsUsed.add(r.model.id);memberCount+=rows.length;const weight=modelDayWeight(r.model,lead,rows.length);for(const row of rows){maxVals.push({value:row.max,weight});minVals.push({value:row.min,weight});rainVals.push({value:row.precipitation,weight})}}
 if(modelsUsed.size<2||memberCount<12)continue;const maxLow=weightedQuantile(maxVals,.1),maxHigh=weightedQuantile(maxVals,.9),minLow=weightedQuantile(minVals,.1),minHigh=weightedQuantile(minVals,.9),precipitationLow=weightedQuantile(rainVals,.1),precipitationHigh=weightedQuantile(rainVals,.9);if(![maxLow,maxHigh,minLow,minHigh].every(Number.isFinite)||maxHigh<maxLow||minHigh<minLow)continue;days.push({date,maxMean:weightedMean(maxVals),maxLow,maxHigh,minMean:weightedMean(minVals),minLow,minHigh,precipitationMean:weightedMean(rainVals),precipitationLow,precipitationHigh,modelCount:modelsUsed.size,memberCount})}
 return{days,models:results.map(x=>x.model.label)} }

export function label(c:number){const m:Record<number,string>={0:'Klar',1:'Überwiegend klar',2:'Teilweise bewölkt',3:'Bedeckt',45:'Nebel',48:'Reifnebel',51:'Nieselregen',53:'Nieselregen',55:'Starker Nieselregen',61:'Leichter Regen',63:'Regen',65:'Starker Regen',71:'Leichter Schneefall',73:'Schneefall',75:'Starker Schneefall',80:'Regenschauer',81:'Kräftige Schauer',82:'Starke Schauer',85:'Schneeschauer',86:'Starke Schneeschauer',95:'Gewitter',96:'Gewitter mit Hagel',99:'Starkes Gewitter'};return m[c]??'Wechselhaft'}
export function icon(c:number,day=true){if(c===0)return day?'☀️':'🌙';if(c===1)return day?'🌤️':'🌙';if(c===2)return'⛅';if(c===3)return'☁️';if([45,48].includes(c))return'🌫️';if([51,53,55,80].includes(c))return'🌦️';if([61,63,65,81,82].includes(c))return'🌧️';if([71,73,75,85,86].includes(c))return'🌨️';if([95,96,99].includes(c))return'⛈️';return'🌤️'}
export function wind(v:number,u:WindUnit){if(u==='kmh')return`${Math.round(v*1.852)} km/h`;if(u==='ms')return`${(v*.514444).toFixed(1)} m/s`;if(u==='mph')return`${Math.round(v*1.15078)} mph`;return`${Math.round(v)} kt`}
export function hazards(h:Hour[]){const s=h.slice(currentIndex(h),currentIndex(h)+24),max=Math.max(...s.map(x=>x.temperature)),min=Math.min(...s.map(x=>x.temperature)),gust=Math.max(...s.map(x=>x.gust)),rain=s.reduce((a,b)=>a+b.precipitation,0),thunder=s.some(x=>[95,96,99].includes(x.code));const a:{level:'yellow'|'red';title:string;text:string}[]=[];if(max>=32)a.push({level:max>=37?'red':'yellow',title:'Hitzebelastung',text:`Bis ${Math.round(max)} °C in 24 Stunden.`});if(min<=1)a.push({level:min<=-5?'red':'yellow',title:'Frost-/Glättepotenzial',text:`Tiefstwerte um ${Math.round(min)} °C.`});if(gust>=35)a.push({level:gust>=50?'red':'yellow',title:'Stürmische Böen',text:`Böen bis ${Math.round(gust)} kt.`});if(rain>=20)a.push({level:rain>=35?'red':'yellow',title:'Starkregenpotenzial',text:`Etwa ${Math.round(rain)} mm in 24 Stunden.`});if(thunder)a.push({level:'yellow',title:'Gewitterpotenzial',text:'Gewittersignale in der Kurzfristvorhersage.'});return a}
