import {memo,useEffect,useMemo,useState} from 'react';
import {ChevronDown,CloudRain,Info,Layers3,MapPinned,RefreshCw,Settings2} from 'lucide-react';
import {GeoJsonLayers,MapCenter,MidMapLibre,RasterTileLayer,WmsTileLayer} from './MapLibreCore';
import {loadWeatherMapGrid,loadWeatherMapMetadata,preferredWeatherMapTimeIndex,weatherMapModel,weatherMapProductsForModel,weatherMapProduct,weatherMapWmsProxy,WEATHER_MAP_MODELS,type WeatherMapGridData,type WeatherMapMetadata,type WeatherMapModelId,type WeatherMapProduct} from './WeatherMapsData';
import WeatherMapGridOverlay from './WeatherMapGridOverlay';
import MapTimelineControls,{MapTimelineLiveButton,MapTimelineRange,MapTimelineTransport} from './MapTimelineControls';
import PrecipitationTotalsMap,{type WeatherMapFavoriteLocation} from './PrecipitationTotalsMap';
import './weatherMapsTotals.css';

function escapeHtml(value:string){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]||char))}
const SETTINGS_KEY='mid:weather-maps:v2';
type BasemapId='light'|'osm'|'dark';
type WeatherMapSettings={modelId:WeatherMapModelId;productId:string;level:number;opacity:number;basemap:BasemapId};
type BasemapTone={saturation?:number;contrast?:number;brightnessMin?:number;brightnessMax?:number};
const OSM_TILE_URL='https://tile.openstreetmap.org/{z}/{x}/{y}.png';
const BASEMAPS:Record<BasemapId,{label:string;url:string;attribution:string;tone?:BasemapTone}>={light:{label:'Schlicht hell',url:OSM_TILE_URL,attribution:'© OpenStreetMap-Mitwirkende',tone:{saturation:-.9,contrast:-.08,brightnessMin:.18,brightnessMax:1}},osm:{label:'OpenStreetMap',url:OSM_TILE_URL,attribution:'© OpenStreetMap-Mitwirkende'},dark:{label:'Schlicht dunkel',url:OSM_TILE_URL,attribution:'© OpenStreetMap-Mitwirkende',tone:{saturation:-1,contrast:.2,brightnessMin:0,brightnessMax:.48}}};
function storedSettings():WeatherMapSettings{const fallbackProduct=weatherMapProduct('icon-eu-qff'),fallback:WeatherMapSettings={modelId:fallbackProduct.modelId,productId:fallbackProduct.id,level:fallbackProduct.defaultLevel??500,opacity:fallbackProduct.opacity??76,basemap:'light'};try{const parsed=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}') as Partial<WeatherMapSettings>,product=weatherMapProduct(String(parsed.productId||fallback.productId)),modelId=WEATHER_MAP_MODELS.some(item=>item.id===parsed.modelId)?parsed.modelId as WeatherMapModelId:product.modelId,validProduct=product.modelId===modelId?product:weatherMapProductsForModel(modelId)[0]??fallbackProduct,basemap=parsed.basemap&&BASEMAPS[parsed.basemap]?parsed.basemap:fallback.basemap,level=Number.isFinite(Number(parsed.level))?Number(parsed.level):validProduct.defaultLevel??fallback.level,opacity=Math.max(20,Math.min(100,Number(parsed.opacity)||validProduct.opacity||fallback.opacity));return{modelId,productId:validProduct.id,level,opacity,basemap}}catch{return fallback}}
function formatMapTime(value:string,timezone:string){const stamp=Date.parse(value);if(!Number.isFinite(stamp))return value;try{return new Intl.DateTimeFormat('de-DE',{timeZone:timezone,weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',timeZoneName:'short'}).format(new Date(stamp))}catch{return new Date(stamp).toLocaleString('de-DE')}}
function relativeMapTime(value:string){const stamp=Date.parse(value);if(!Number.isFinite(stamp))return'';const hours=Math.round((stamp-Date.now())/3600000);if(Math.abs(hours)<1)return'nahe jetzt';return hours>0?`+${hours} h`:`−${Math.abs(hours)} h`}
function leadTimeLabel(value:string,reference?:string){const stamp=Date.parse(value),base=reference?Date.parse(reference):NaN;if(!Number.isFinite(stamp)||!Number.isFinite(base))return relativeMapTime(value);const hours=Math.round((stamp-base)/3600000);return hours===0?'T+0':`T+${hours} h`}
function referenceTimeLabel(value:string|undefined,timezone:string){return value?formatMapTime(value,timezone):'neuester Modelllauf'}
function productLevel(product:WeatherMapProduct,selected:number,metadata:WeatherMapMetadata|null){const available=metadata?.elevations?.length?metadata.elevations:product.levels??[];if(!available.length)return undefined;if(available.includes(selected))return selected;if(product.defaultLevel&&available.includes(product.defaultLevel))return product.defaultLevel;return available[0]}
function levelLabel(product:WeatherMapProduct,value:number){return product.levelKind==='height'?`${value} m ü. Grund`:`${value} hPa`}
function weatherMapPhase(product:WeatherMapProduct){return product.modelId==='nowcastmix'?(product.forecast?'nowcast':'analysis'):product.forecast?'forecast':'analysis'}
function weatherMapPhaseLabel(product:WeatherMapProduct){return product.modelId==='nowcastmix'?(product.forecast?'NowCastMIX · Kurzzeitprognose':'NowCastMIX · Analyse'):product.forecast?'Modell · Vorhersage':'Modell · Analyse'}
function weatherMapPrecipitationNote(product:WeatherMapProduct){if(product.gridKind==='pressure-precip')return'Niederschlagsrate · mm/h';const window=product.id.match(/rain-(1|3|6|24)h$/)?.[1];if(window)return`Niederschlagsprodukt · ${window}-h-Fenster · DWD-Originalfarbskala`;if(product.id.includes('total-precip'))return'Gesamtniederschlagsprodukt · DWD-Originalfarbskala';return''}

function WeatherMapsPanel({latitude,longitude,timezone,locationName,favorites}:{latitude:number;longitude:number;timezone:string;locationName:string;favorites:WeatherMapFavoriteLocation[]}){
  const initial=useMemo(storedSettings,[]),[modelId,setModelId]=useState<WeatherMapModelId>(initial.modelId),[productId,setProductId]=useState(initial.productId),[selectedLevel,setSelectedLevel]=useState(initial.level),[opacity,setOpacity]=useState(initial.opacity),[basemap,setBasemap]=useState<BasemapId>(initial.basemap),[totalsBasemap,setTotalsBasemap]=useState<BasemapId>(initial.basemap),[viewMode,setViewMode]=useState<'model'|'precipitation'>('model'),[metadata,setMetadata]=useState<WeatherMapMetadata|null>(null),[gridData,setGridData]=useState<WeatherMapGridData|null>(null),[metadataError,setMetadataError]=useState(''),[tileError,setTileError]=useState(''),[loading,setLoading]=useState(false),[timeIndex,setTimeIndex]=useState(0),[playing,setPlaying]=useState(false),[playbackSeconds,setPlaybackSeconds]=useState(1.2),[revision,setRevision]=useState(0);
  const products=useMemo(()=>weatherMapProductsForModel(modelId),[modelId]),product=useMemo(()=>{const current=weatherMapProduct(productId);return current.modelId===modelId?current:products[0]??weatherMapProduct('icon-eu-qff')},[productId,modelId,products]),model=weatherMapModel(modelId),isGrid=product.source==='grid',wmsUrl=weatherMapWmsProxy(),times=isGrid?(gridData?.times??[]):(metadata?.times??[]),referenceTimes=isGrid?(gridData?.referenceTime?[gridData.referenceTime]:[]):(metadata?.referenceTimes??[]),referenceTime=referenceTimes.at(-1),selectedTime=times[Math.min(timeIndex,Math.max(0,times.length-1))]??'',selectedGridFrame=isGrid?(gridData?.frames.find(frame=>frame.time===selectedTime)??gridData?.frames[0]):undefined,level=productLevel(product,selectedLevel,metadata),currentBasemap=BASEMAPS[basemap],phase=weatherMapPhase(product),phaseLabel=weatherMapPhaseLabel(product),precipitationNote=weatherMapPrecipitationNote(product),sourceLabel=isGrid?(gridData?.provider||'DWD ICON-D2 Raster'):`DWD WMS · ${product.layer}`;
 const availableLevels=useMemo(()=>{const candidates=metadata?.elevations?.length?metadata.elevations:product.levels??[];return[...new Set(candidates)].filter(Number.isFinite).sort((a,b)=>product.levelKind==='height'?a-b:b-a)},[metadata?.elevations,product.levels,product.levelKind]);
 useEffect(()=>{if(!product)return;const controller=new AbortController();setLoading(true);setMetadataError('');setTileError('');setPlaying(false);if(product.source==='grid'){setMetadata(null);void loadWeatherMapGrid(modelId,latitude,longitude,controller.signal).then(result=>{if(result.error)throw new Error(result.error);setGridData(result);setTimeIndex(preferredWeatherMapTimeIndex(result.times))}).catch(error=>{if(controller.signal.aborted)return;setGridData(null);setMetadataError(error instanceof Error?error.message:String(error));setTimeIndex(0)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)})}else{setGridData(null);void loadWeatherMapMetadata(product.layer,controller.signal).then(result=>{setMetadata(result);setTimeIndex(preferredWeatherMapTimeIndex(result.times));const levels=result.elevations?.length?result.elevations:product.levels??[],preferred=product.defaultLevel??selectedLevel;if(levels.length&&!levels.includes(selectedLevel))setSelectedLevel(levels.includes(preferred)?preferred:levels[0])}).catch(error=>{if(controller.signal.aborted)return;setMetadata(null);setMetadataError(error instanceof Error?error.message:String(error));setTimeIndex(0)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)})}return()=>controller.abort()},[product.id,modelId,latitude,longitude]);
  useEffect(()=>{if(!playing||times.length<2)return;const timer=window.setInterval(()=>setTimeIndex(index=>index>=times.length-1?0:index+1),playbackSeconds*1000);return()=>window.clearInterval(timer)},[playing,times.length,playbackSeconds]);
 useEffect(()=>{try{localStorage.setItem(SETTINGS_KEY,JSON.stringify({modelId,productId:product.id,level:selectedLevel,opacity,basemap}))}catch{}},[modelId,product.id,selectedLevel,opacity,basemap]);
 useEffect(()=>{if(!products.some(item=>item.id===productId)&&products[0]){setProductId(products[0].id);setSelectedLevel(products[0].defaultLevel??500);setOpacity(products[0].opacity??76)}},[products,productId]);
 const chooseModel=(value:WeatherMapModelId)=>{const first=weatherMapProductsForModel(value)[0];setModelId(value);if(first){setProductId(first.id);setSelectedLevel(first.defaultLevel??500);setOpacity(first.opacity??76)}};
 const chooseProduct=(value:string)=>{const next=weatherMapProduct(value);setProductId(next.id);setSelectedLevel(next.defaultLevel??500);setOpacity(next.opacity??76)};
 const step=(delta:number)=>{setPlaying(false);setTimeIndex(index=>Math.max(0,Math.min(Math.max(0,times.length-1),index+delta)))};
 const goNearNow=()=>{setPlaying(false);if(times.length)setTimeIndex(preferredWeatherMapTimeIndex(times))};
  const chooseView=(value:'model'|'precipitation')=>{setPlaying(false);setViewMode(value)};
 const params=useMemo(()=>({layers:product.layer,styles:'',format:'image/png',transparent:true,version:'1.1.1',tiled:true,...(selectedTime?{time:selectedTime}:{}),...(referenceTime?{dim_reference_time:referenceTime}:{}),...(level!==undefined?{elevation:String(level)}:{})} as any),[product.layer,selectedTime,referenceTime,level]);
   return <section className="weather-maps-panel c14-map-workspace">
   <div className="weather-maps-view-switch" role="group" aria-label="Wetterkartenansicht">
    <button type="button" aria-pressed={viewMode==='model'} className={viewMode==='model'?'active':''} onClick={()=>chooseView('model')}>Modellkarten</button>
    <button type="button" aria-pressed={viewMode==='precipitation'} className={viewMode==='precipitation'?'active':''} onClick={()=>chooseView('precipitation')}>Niederschlagssummen</button>
   </div>
   {viewMode==='precipitation'?<PrecipitationTotalsMap favorites={favorites} basemapOptions={BASEMAPS} basemapId={totalsBasemap} onBasemapChange={value=>setTotalsBasemap(value as BasemapId)}/>:<>
  <div className="weather-maps-primary-controls" aria-label="Primäre Kartenauswahl">
   <label><span>Modell</span><select value={modelId} onChange={event=>chooseModel(event.target.value as WeatherMapModelId)}>{WEATHER_MAP_MODELS.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select><small>{model.detail}</small></label>
   <label><span>Karte</span><select value={product.id} onChange={event=>chooseProduct(event.target.value)}>{products.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select><small>{product.detail}</small></label>
  </div>
  <div className="weather-maps-map-stage">
   <div className="weather-maps-map-shell"><MidMapLibre center={[latitude,longitude]} zoom={product.defaultZoom} minZoom={2} maxZoom={10} className="weather-maps-maplibre" scrollZoom={false}><MapCenter latitude={latitude} longitude={longitude} zoom={product.defaultZoom}/><RasterTileLayer id={`weather-basemap-${basemap}`} url={currentBasemap.url} tone={currentBasemap.tone} attribution={currentBasemap.attribution}/>{isGrid&&gridData&&selectedGridFrame&&product.gridKind?<WeatherMapGridOverlay data={gridData} frame={selectedGridFrame} kind={product.gridKind} opacity={opacity/100}/>:null}{!isGrid&&wmsUrl?<WmsTileLayer id={`weather-wms-${product.id}-${selectedTime||'latest'}-${referenceTime||'latest-run'}-${level??'surface'}-${revision}`} baseUrl={`${wmsUrl}${wmsUrl.includes('?')?'&':'?'}mid-map=${revision}`} opacity={opacity/100} params={params} onReady={()=>setTileError('')} onError={()=>setTileError(`${product.label} konnte für den gewählten Termin nicht geladen werden.`)} attribution="Wetterkarten © Deutscher Wetterdienst"/>:null}<GeoJsonLayers id="weather-selected-location" data={{type:'FeatureCollection',features:[{type:'Feature',properties:{label:`<strong>${escapeHtml(locationName)}</strong><br/>gewählter Standort`},geometry:{type:'Point',coordinates:[longitude,latitude]}}]}} layers={[{id:'halo',type:'circle',paint:{'circle-radius':7,'circle-color':'#1675d1','circle-opacity':.78,'circle-stroke-color':'#ffffff','circle-stroke-width':2}},{id:'hit-target',type:'circle',paint:{'circle-radius':22,'circle-color':'#1675d1','circle-opacity':.001}}]} hoverProperty="label"/></MidMapLibre>{!isGrid&&!wmsUrl?<div className="weather-maps-overlay-message"><CloudRain size={28}/><strong>Kartenquelle nicht verfügbar</strong><span>Die DWD-Wetterkarten können derzeit nicht geladen werden.</span></div>:null}{loading?<div className="weather-maps-loading"><RefreshCw className="spin" size={20}/>Kartenzeiten werden geprüft …</div>:null}</div>
    <div className="weather-maps-map-status" aria-live="polite"><span><b>{product.label}</b><small>{phaseLabel} · {sourceLabel}{level!==undefined?` · ${levelLabel(product,level)}`:''}{precipitationNote?` · ${precipitationNote}`:''}</small></span><span><b>{selectedTime?formatMapTime(selectedTime,timezone):'Gültigkeitszeit nicht verfügbar'}</b><small>{referenceTime?`Laufstart · INIT ${referenceTimeLabel(referenceTime,timezone)}${selectedTime?` · ${leadTimeLabel(selectedTime,referenceTime)}`:''}`:'Modelllauf/INIT nicht verfügbar'}</small></span></div>
  </div>
   <MapTimelineControls className="weather-maps-controls" transportClassName="weather-maps-playback" stepButtonClassName="weather-maps-step" playButtonClassName="weather-maps-step weather-maps-step-play" speedClassName="composite-playback-speed" rangeClassName="weather-maps-timeline" markerClassName="composite-frame-markers" timeClassName="weather-maps-time" liveButtonClassName="weather-maps-live" index={timeIndex} count={times.length} playing={playing} canAnimate={times.length>1} liveActive={Boolean(times.length)&&timeIndex===preferredWeatherMapTimeIndex(times)} liveDisabled={!times.length} playbackSeconds={playbackSeconds} onPlaybackSecondsChange={setPlaybackSeconds} onPrevious={()=>step(-1)} onToggle={()=>setPlaying(value=>!value)} onNext={()=>step(1)} onSeek={nextIndex=>{setPlaying(false);setTimeIndex(nextIndex)}} onLive={goNearNow} rangeLabel="Verfügbaren Kartenzeitpunkt auswählen" countLabel={times.length?`${timeIndex+1} / ${times.length} bestätigte Zeitschritte`:'kein Gültigkeitszeitpunkt'} valueLabel={selectedTime?formatMapTime(selectedTime,timezone):'–'} detailLabel={selectedTime?leadTimeLabel(selectedTime,referenceTime):undefined} playLabel="Kartenanimation starten" pauseLabel="Kartenanimation pausieren" markers={times.map((time,markerIndex)=>({key:`${time}-${markerIndex}`,phase}))}
    transportControl={<MapTimelineTransport className="weather-maps-playback" stepButtonClassName="weather-maps-step" playButtonClassName="weather-maps-step weather-maps-step-play" index={timeIndex} count={times.length} playing={playing} canAnimate={times.length>1} onPrevious={()=>step(-1)} onToggle={()=>setPlaying(value=>!value)} onNext={()=>step(1)} playLabel="Kartenanimation starten" pauseLabel="Kartenanimation pausieren"/>}
    rangeControl={<MapTimelineRange className="weather-maps-timeline" markerClassName="composite-frame-markers" index={timeIndex} count={times.length} canAnimate={times.length>1} onSeek={nextIndex=>{setPlaying(false);setTimeIndex(nextIndex)}} rangeLabel="Verfügbaren Kartenzeitpunkt auswählen" countLabel={times.length?`${timeIndex+1} / ${times.length} bestätigte Zeitschritte`:'kein Gültigkeitszeitpunkt'} markers={times.map((time,markerIndex)=>({key:`${time}-${markerIndex}`,phase}))}/>}
    liveControl={<MapTimelineLiveButton className="weather-maps-live" active={Boolean(times.length)&&timeIndex===preferredWeatherMapTimeIndex(times)} onClick={goNearNow} disabled={!times.length} label="Jetzt"/>}
   />
  <details className="weather-maps-advanced"><summary><Settings2 size={16}/><span><b>Darstellung & Ebenen</b><small>Druckfläche, Kartenbasis und Deckkraft</small></span><ChevronDown className="weather-maps-disclosure-icon" size={16}/></summary><div className="weather-maps-toolbar">
   {availableLevels.length?<label><span>{product.levelKind==='height'?'Höhe':'Druckfläche'}</span><select value={level??availableLevels[0]} onChange={event=>setSelectedLevel(Number(event.target.value))}>{availableLevels.map(value=><option key={value} value={value}>{levelLabel(product,value)}</option>)}</select><small>{product.levelKind==='height'?'Höhe über Grund':'Atmosphärisches Druckniveau'}</small></label>:null}
   <label><span>Kartenbasis</span><select value={basemap} onChange={event=>setBasemap(event.target.value as BasemapId)}>{Object.entries(BASEMAPS).map(([id,item])=><option key={id} value={id}>{item.label}</option>)}</select><small>Orientierungsebene</small></label>
   <label className="weather-maps-opacity"><span>Deckkraft <b>{Math.round(opacity)} %</b></span><input type="range" min={20} max={100} value={opacity} onChange={event=>setOpacity(Number(event.target.value))}/></label>
   <button type="button" className="weather-maps-reload" onClick={()=>{setTileError('');setRevision(value=>value+1)}}><RefreshCw size={16}/>Neu laden</button>
  </div></details>
  <details className="weather-maps-meta-details"><summary><Info size={16}/><span><b>Quelle & Lauf</b><small>{referenceTime?`INIT ${referenceTimeLabel(referenceTime,timezone)}`:'Lauf nicht verfügbar'}</small></span><ChevronDown className="weather-maps-disclosure-icon" size={16}/></summary><div className="weather-maps-meta"><span><MapPinned size={15}/><b>{product.label}</b><small>{level!==undefined?levelLabel(product,level):product.detail}</small></span><span><Info size={15}/><b>INIT</b><small>{referenceTime?referenceTimeLabel(referenceTime,timezone):'nicht verfügbar'}</small></span><span><Layers3 size={15}/><b>Gültig</b><small>{selectedTime?formatMapTime(selectedTime,timezone):'nicht verfügbar'}</small></span><span><Layers3 size={15}/><b>Quelle</b><small>{isGrid?(gridData?.provider||'DWD ICON-D2 Raster'):product.layer}</small></span></div></details>
  {metadataError?<p className="weather-maps-warning">Kartendaten bzw. Gültigkeitszeitpunkt konnten nicht geladen werden: {metadataError}.</p>:null}{tileError?<p className="weather-maps-warning">{tileError}</p>:null}{product.category==='significant'?<p className="weather-maps-warning">Bei leerer Karte liegt im sichtbaren Ausschnitt aktuell entweder kein entsprechendes Signal vor oder der DWD stellt für diesen Zeitpunkt keinen passenden Datensatz bereit.</p>:null}{product.disclaimer?<p className="weather-maps-disclaimer">{product.disclaimer}</p>:<p className="weather-maps-disclaimer">DWD Open Data / WMS. Ausschließlich Modell- und Nowcastkarten; Satellitenbilder sind in diesem Modul bewusst ausgeschlossen.</p>}
   </>}
   </section>
}
export default memo(WeatherMapsPanel);
