import {useEffect,useState} from 'react';
import {BrainCircuit,CheckCircle2,CloudRain,Scale,ShieldCheck,SlidersHorizontal,Target} from 'lucide-react';
import {readWeatherTwinSettings,writeWeatherTwinSettings,type WeatherTwinSettings} from './forecastVerification';

export function WeatherTwinSettings(){
 const[settings,setSettings]=useState<WeatherTwinSettings>(()=>readWeatherTwinSettings());
 useEffect(()=>{const update=(event:Event)=>setSettings((event as CustomEvent<WeatherTwinSettings>).detail||readWeatherTwinSettings());window.addEventListener('mid:weather-twin-settings',update);return()=>window.removeEventListener('mid:weather-twin-settings',update)},[]);
 const patch=(change:Partial<WeatherTwinSettings>)=>setSettings(writeWeatherTwinSettings(change));
 return <section className="weather-twin-settings"><header><BrainCircuit size={22}/><span><strong>Lokaler Wetterzwilling</strong><small>Globale Lern- und Korrekturoptionen. Standortprofil und Aktivitätsprofile bleiben im Modul „Prognosegüte und Rückblick“.</small></span></header><div><label className="settings-toggle-card"><input type="checkbox" checked={settings.enabled} onChange={event=>patch({enabled:event.target.checked})}/><Target size={21}/><span><strong>Wetterzwilling aktivieren</strong><small>Speichert Prognosestände, Rückblicke und lokale Güteprofile für jeden Standort.</small></span></label><label className={`settings-toggle-card${!settings.enabled?' disabled':''}`}><input type="checkbox" disabled={!settings.enabled} checked={settings.useAsMainForecast} onChange={event=>patch({useAsMainForecast:event.target.checked})}/><SlidersHorizontal size={21}/><span><strong>Lokal gelernte Prognose als Hauptprognose</strong><small>Nur bei ausreichender Datenbasis; Best Match bleibt Kontrollgruppe und unverändert im Archiv.</small></span></label><label className={`settings-toggle-card${!settings.enabled?' disabled':''}`}><input type="checkbox" disabled={!settings.enabled} checked={settings.nowcastAssimilation} onChange={event=>patch({nowcastAssimilation:event.target.checked})}/><CloudRain size={21}/><span><strong>Radar-/Nowcast-Assimilation</strong><small>Beobachtete Niederschlagssignale wirken ausschließlich auf die ersten Stunden der lokalen Prognose.</small></span></label><label className={`settings-toggle-card${!settings.enabled?' disabled':''}`}><input type="checkbox" disabled={!settings.enabled} checked={settings.biasCorrection} onChange={event=>patch({biasCorrection:event.target.checked})}/><Scale size={21}/><span><strong>Lokale Bias-Korrektur</strong><small>Systematische Modellabweichungen werden je Wetterlage, Parameter und Prognosehorizont vorsichtig korrigiert.</small></span></label><label className={`settings-toggle-card${!settings.enabled?' disabled':''}`}><input type="checkbox" disabled={!settings.enabled} checked={settings.probabilityCalibration} onChange={event=>patch({probabilityCalibration:event.target.checked})}/><ShieldCheck size={21}/><span><strong>Wahrscheinlichkeiten kalibrieren</strong><small>Regenwahrscheinlichkeiten werden mit der lokal tatsächlich beobachteten Trefferhäufigkeit abgeglichen.</small></span></label><label className={`settings-toggle-card${!settings.enabled?' disabled':''}`}><input type="checkbox" disabled={!settings.enabled} checked={settings.personalRecommendations} onChange={event=>patch({personalRecommendations:event.target.checked})}/><CheckCircle2 size={21}/><span><strong>Persönliche Empfehlungen</strong><small>Aktivitätsfenster werden aus der lokal angepassten Prognose und den gewählten Profilen abgeleitet.</small></span></label></div></section>
}
